### ISSUE TITLE
VCRedist is out of date

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#1021]
Porting this bug: https://github.com/dotnet/core/issues/356

**Comment by gkhanna79** [comment]
We want to point to the page that controls the actual links (hence, https://www.microsoft.com/en-us/download/details.aspx?id=48145) - we dont want to link the DL center direct links.

**Comment by Petermarcu** [comment]
I misread the initial bug. Closing this and reopening that one. It was in the right place.
