### ISSUE TITLE
Build DotNetHostPolicy packages with serviceable attribute

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/core-setup#110]
Since we decided not to mark assemblies as serviceable, instead, the packages as serviceable, the host policy package needs to be marked so as well.

@gkhanna79, just filing a tracking issue for RTM.

Ported from https://github.com/dotnet/cli/issues/2582 for @schellap

**Comment by gkhanna79** [comment]
I believe @schellap had a PR for this. @schellap Can you comment on its status?

**Comment by schellap** [comment]
The PR is in, buildtools is taken, will close post validation on the feed.

**Comment by gkhanna79** [comment]
@schellap Close this?

**Comment by schellap** [comment]
Verified on the feed for latest rc3 packages. Closing...
