### ISSUE TITLE
System.ValueTuple should be part of the shared framework.

### ISSUE THREAD

**Issue by ellismg** [dotnet/core-setup#1121]
I was looking at ingesting the newest version of Roslyn in dev/eng and I ran into an issue:

```
/home/matell/git/source-build/src/core-setup/pkg/projects/Microsoft.NETCore.App/Microsoft.NETCore.App.depproj(69,5): error : Unexpected System package System.ValueTuple
```

This is because newer version of Roslyn depend on Value tuple but it's not in Microsoft.NETCore.App.

**Comment by ericstj** [comment]
I think we want ValueTuple to be part of shared framework so this is a good catch.  @weshaggard do you agree?

**Comment by weshaggard** [comment]
Yes it should be added. I was tracking it with https://github.com/dotnet/core-setup/issues/325.

**Comment by gkhanna79** [comment]
Closing in favor of https://github.com/dotnet/core-setup/issues/325
