### ISSUE TITLE
Windows installation: Installing 1.1 removes 1.0.x host\fxr 

### ISSUE THREAD

**Issue by leecow** [dotnet/core-setup#1183]
Install 1.0.3 on a Win10 box
 
PS C:\Program Files\dotnet> dotnet --version
1.0.0-preview2-003156
PS C:\Program Files\dotnet> ls .\host\fxr\
 
 
    Directory: C:\Program Files\dotnet\host\fxr
 
 
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
da----        1/17/2017  11:00 AM                1.0.1
 
Install 1.1
 
PS C:\Program Files\dotnet> ls .\host\fxr\
 
 
    Directory: C:\Program Files\dotnet\host\fxr
 
 
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        1/17/2017  12:52 PM                1.1.0
 
 
PS C:\Program Files\dotnet> dotnet --version
1.0.0-preview2-1-003177

**Comment by gkhanna79** [comment]
We will need to get a fix for this in 1.0.x and 1.1.0 possibly. @schellap PTAL.

CC @ramarag

**Comment by gkhanna79** [comment]
Assigning this to you @rakeshsinghranchi and @vivmishra

**Comment by gkhanna79** [comment]
@rakeshsinghranchi @vivmishra Isnt this a dup of one of the issues already assigned to you for 1.0.X? If so, please close this as a dup.

**Comment by rakeshsinghranchi** [comment]
This is dupe of https://github.com/dotnet/core-setup/issues/1575
