### ISSUE TITLE
dotnet not recogonized - possible PATH issue?

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/core-setup#1192]
Moving https://github.com/dotnet/cli/issues/5148 on behalf of @fmorriso

We've seen a number of such reports about Shared Framework setup resulting in no dotnet on the Path. 

-----

## Steps to reproduce

1. Install
DotNetCore.1.0.1-VS2015Tools.Preview2.0.3.exe

2. Install
dotnet-win-x64.1.1.0.exe

3. Install 
dotnet-dev-win-x64.1.0.0-preview2-1-003177.exe

4. Open command prompt

5. Type 
dotnet --version

## Expected  behavior
Output of DotNet core version information

## Actual behavior

'dotnet ' is not recognized as an internal or external command

I cannot find anywhere in the documentation or readme information about what needs to be in the PATH and maybe what should NOT be in the PATH and in WHAT ORDER.
[path.txt](https://github.com/dotnet/cli/files/673189/path.txt)

## Environment data
`dotnet --info` output:
(unable to produce)

## PATH
See attached path.txt file which was produced via $env:PATH -split ';' | Out-File path.txt

**Comment by gkhanna79** [comment]
FYI @ramarag 

@schellap PTAL.

**Comment by gkhanna79** [comment]
Assigning to you @vivmishra and @rakeshsinghranchi

**Comment by rakeshsinghranchi** [comment]
Followed exactly the same steps, issue does not repro.

**Comment by danmosemsft** [comment]
@rakeshsinghranchi if this dosn't repro, please close this

**Comment by rakeshsinghranchi** [comment]
Closing this as this doesn't repro.
