### ISSUE TITLE
Should Microsoft.DotNet.PlatformAbstractions treat all RHEL 7 versions as "rhel.7"?

### ISSUE THREAD

**Issue by ellismg** [dotnet/core-setup#1217]
Today, the logic for computing the Runtime ID is very simple, look at [/etc/os-release and concatenate the version and version id fields](https://github.com/dotnet/core-setup/blob/afdc2ba4a62c860ac62265f8fc64081d465dc725/src/Microsoft.DotNet.PlatformAbstractions/Native/PlatformApis.cs#L100).

One place this falls down is with RHEL and some RHEL derivatives (Oracle Linux, Scientific Linux and others) because minor versions of RHEL bump the version ID, but there is still ABI compatibility between minor versions.

Previously, we've produced packages targeting the generic "rhel.7-x64" RID (which would never be produced by the tooling) and use the runtime graph to fallback minor RHEL's to this package.  The downside of this is we have to rev the runtime graph when minor versions of RHEL come out.  This means either publishing a new version of Microsoft.NETCore.Platforms or having a new package that adds the fallbacks and have folks add that to their csproj/project.json.  There are also a few rough edges int the tooling around the default publish behavior (at least this was the case for the csproj based tooling) where you'd really want to list "rhel.7" as a runtime in your project.json (so you don't have to list multiple RHEL versions) but then you have to be explicit and pass runtime arguments to commands like `dotnet publish`

Should we just change the code to understand intrinsically that when computing the RID for RHEL (and other rebuilds that follow this model like Scientific Linux and Oracle Linux) to just drop the minor part of the version number?  It's a bit unfortunate that we have to have this special logic in in the tooling, but centralizing it may make things easier for both end users and our own internal systems (lots of different places do a dance the unify RHEL 7.X to RHEL 7 and everyone does it differently.

/cc @omajid, @tmds (from RedHat who have been asking about this), @ericstj @weshaggard @Petermarcu  @mellinoe

**Comment by ericstj** [comment]
/cc @anurse 

Can we guarantee that RedHat is always binary compatible across their minor versions and folks will never need to carry a different asset for say RedHat 7.1 and 7.2 (presumably to deal with functional differences)?

**Comment by tmds** [comment]
> Can we guarantee that RedHat is always binary compatible across their minor versions and folks will never need to carry a different asset for say RedHat 7.1 and 7.2 (presumably to deal with functional differences)?

Yes, per [Red Hat Enterprise Linux Life Cycle](https://access.redhat.com/support/policy/updates/errata/):

> During the life cycle of a major Red Hat Enterprise Linux release, Red Hat makes commercially reasonable efforts to maintain binary compatibility for the core runtime environment across all minor releases and errata advisories. If necessary, Red Hat may make exceptions to this compatibility goal for Critical impact security or other significant issues.

**Comment by omajid** [comment]
It's worth taking a look at https://access.redhat.com/articles/rhel-abi-compatibility too for some additional information on how to best preserve binary compatibility and some specifics on which libraries will stay ABI compatible even across major RHEL releases.

**Comment by ericstj** [comment]
I see, in that sense this isn't much different to Windows, where we call a different API and ignore the minor version, build, etc due to the compat guarantee's of the OS.  I'm fine with it 👍

**Comment by RheaAyase** [comment]
This would definitely make life easier for both sides :+1:

**Comment by gkhanna79** [comment]
CC @livarcocc @piotrpMSFT

**Comment by livarcocc** [comment]
I can make the change once we decide we want to take it. But I don't understand the scenario well enough to make a call.

**Comment by tmds** [comment]
> I can make the change once we decide we want to take it. But I don't understand the scenario well enough to make a call.

By removing the minor it will no longer be possible to do minor-specific stuff. Which is okay because RHEL minors are point releases with binary compatibility.

**Comment by omajid** [comment]
Here's an example of something that will benefit immensely from this change.

Currently, building roslyn fails. This is what rolsyn is doing, which would probably apply to other projects too:

    $(BINARIES_PATH)/dotnet-cli/dotnet publish

This fails:

    Can not find runtime target for framework '.NETCoreApp,Version=v1.1' compatible with one of the target runtimes: 'rhel.7.3-x64'. Possible causes:
    1. The project has not been restored or restore failed - run `dotnet restore`
    2. The project does not list one of 'rhel.7.3-x64' in the 'runtimes' section.
    3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries.

For RHEL 7.3, I have to explicitly add `--runtime 'rhel.7-x64'` for this problem to be worked around. I don't know if any other platforms require this.

**Comment by gkhanna79** [comment]
For this scenario, isn't the RID computed by CLI publish infrastructure @livarcocc @eerhardt and if so, shouldn't it account for the missing/unknown RID and cap to the known ones?

**Comment by omajid** [comment]
At least part of the runtime knows about `rhel.7.3-x64`: https://github.com/dotnet/corefx/pull/15006

**Comment by ellismg** [comment]
> For this scenario, isn't the RID computed by CLI publish infrastructure @livarcocc @eerhardt and if so, shouldn't it account for the missing/unknown RID and cap to the known ones?

I believe that the RID is computed by using Microsoft.DotNet.PlatformAbstractions (and if it isn't, IMHO we should be fix that).

If we took this change, Roslyn would just have to list "rhel.7-x64" in their runtimes section and then we could publish on any RHEL version.

**Comment by tmds** [comment]
@ellismg Why does the roslyn publish operation care about the runtime id? Is this being published to run as a 'stand-alone' app?

**Comment by ellismg** [comment]
> @ellismg Why does the roslyn publish operation care about the runtime id? Is this being published to run as a 'stand-alone' app?

Yes, today they publish some stuff in their build infrastructure as a standalone app, hence the dependency on a rid.

**Comment by tmds** [comment]
> Yes, today they publish some stuff in their build infrastructure as a standalone app, hence the dependency on a rid.

Do you know why they publish it standalone? The source build doesn't need a standalone version of the compiler, right?

It would be best if the target rid doesn't need to exist. So for version 16 of my home-brew banana linux:
```
$ ./build-dotnet.sh --target-rid banana.16-x64 --build-rid linux-x64 --parent-rids linux,linux-x64
```
I am borrowing the terms `build` and `target` from the GCC (https://gcc.gnu.org/onlinedocs/gccint/Configure-Terms.html).

What do you think?

The discussion has triggered another question. When Red Hat builds .NET and provides this on RHEL we can include some fixes and backports. Now, when a user publishes his app standalone for RHEL, will those fixes be included? Is the behavior different when publishing from a RHEL system compared to a non-RHEL (e.g. Windows, Ubuntu) system?

**Comment by omajid** [comment]
I opened https://github.com/dotnet/roslyn/issues/17421 to track the roslyn issues

**Comment by tmds** [comment]
@ellismg I had some comments and questions in this thread (https://github.com/dotnet/core-setup/issues/1217#issuecomment-281591614). Can you have a look please?

**Comment by RheaAyase** [comment]
> The discussion has triggered another question. When Red Hat builds .NET and provides this on RHEL we can include some fixes and backports. Now, when a user publishes his app standalone for RHEL, will those fixes be included? Is the behavior different when publishing from a RHEL system compared to a non-RHEL (e.g. Windows, Ubuntu) system?

I touched on that topic in the issue #1599 as well, but I am yet to go through that thread so I've no idea where did it lead there. Too much traveling/pto this week, I won't have time til Sunday...
