### ISSUE TITLE
Host cannot find satellite assemblies listed in deps.json when using version Microsoft.NETCore.App 2.0

### ISSUE THREAD

**Issue by nguerrera** [dotnet/core-setup#1221]
## Steps to reproduce

* Install https://dotnetcli.blob.core.windows.net/dotnet/master/Installers/Latest/dotnet-win-x64.latest.exe

* From Windows command prompt:
  * git clone https://github.com/nguerrera/repros
  * cd repros\SatelliteAssemblyHostIssue
  * repro.cmd

## Expected  behavior

The program runs fine.

## Actual behavior
```
Error: assembly specified in the dependencies manifest was not found -- package: 'satelliterepro', version: '1.0.0', path: 'fr/SatelliteRepro.resources.dll'
```

## Environment data

```
Microsoft .NET Core 2.0.0 - Runtime (x64) 2.0.0.1384

.NET Command Line Tools (1.0.0-rc3-004512)

Product Information:
 Version:            1.0.0-rc3-004512
 Commit SHA-1 hash:  61b7841087

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\Src\repros\SatelliteAssemblyHostIssue\.dotnet_cli\sdk\1.0.0-rc3-004512
```

@gkhanna79 @ramarag

**Comment by nguerrera** [comment]
cc @Eilon @pranavkm @ryanbrandenburg 

This has been blocking ASP.NET for a while. It was logged first as a CLI issue (dotnet/CLI#5172), then an SDK (dotnet/sdk#673) issue, but after preparing the repro above and talking offline, this appears to be an issue in the 2.0 host.

**Comment by Eilon** [comment]
Thanks for the update. If you have a private build that you want us to try out, we can certainly do that as well to make sure the ASP.NET Core scenario is functional.

**Comment by gkhanna79** [comment]
@schellap Can you please take an initial stab at this?

**Comment by ryanbrandenburg** [comment]
Do we have an update on this? It's currently blocking progress on aspnet/Localization#315.

**Comment by gkhanna79** [comment]
@nguerrera The repro script (in your repro repo) no longer works since the CLI it is using is not present. Trying to use latest CLI (https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.zip) results in different restore errors.

Do you have a repro available offline that you can share with the CLI in question?

**Comment by gkhanna79** [comment]
Specifically, your repro using RC3 CLI (which no longer exists) and it does not restore using RC4 CLI.

**Comment by gkhanna79** [comment]
After modifying few configurations, I am able to build and repro the issue locally using the latest SharedFX (1450).

**Comment by gkhanna79** [comment]
I have a possible fix for this issue and working on validating it.

**Comment by gkhanna79** [comment]
PR with fix is at https://github.com/dotnet/core-setup/pull/1392
