### ISSUE TITLE
Implement MU Opt-In as part of setups

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/core-setup#1231]
Moved from https://github.com/dotnet/cli/issues/2953 on behalf of @schellap 
This switch is most pertinent in the Shared Framework installer as that is what apps, including CLI, will use to get the host which in turn depends on the ability to service via MU.

----

If Microsoft Update is not turned on in the box by default, the installing dotnet should allow to turn this on machine wide as part of installing Shared FX or perhaps any of our installers.

This would allow us to service all our components through MU.

@gkhanna79, @piotrpMSFT, @ericstj, @ellismg, @leecow.

**Comment by gkhanna79** [comment]
@rakeshsinghranchi @vivmishra Please work with @leecow on this.

**Comment by eerhardt** [comment]
@leecow - can you give some input on this policy?

**Comment by leecow** [comment]
Our installers need to provide the option for to enable updates. I would expect @rakeshsinghranchi to be familiar with the settings from his work on the Framework installers.

**Comment by vivmishra** [comment]
Framework installer does not carry this since we are part of WU and not MU. 
Though, we are aware of general guidance of how to do this work but this was kept low pri since we haven't had any instances of shipping a high pri patch on MU for .NET Core yet.

**Comment by gkhanna79** [comment]
@leecow Can you please update this per the last discussion we had on the topic?

CC @Petermarcu

**Comment by leecow** [comment]
As Vivek alludes to above, the next step is to investigate how the opt-in feature would be implemented in the runtime installer for Windows.

**Comment by gkhanna79** [comment]
I chatted with @leecow offline yesterday and he will determine if this needs to be punted or not.

**Comment by leecow** [comment]
I talking through this further, enabling the option on our installer isn't a priority. Customers have the ability to opt-in through the Windows control panel. The issue will be re-opened if specific compliance requirements are discovered.
