### ISSUE TITLE
Host should show message if failing due to Windows long file path

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/core-setup#1267]
## Steps to reproduce
On Windows:
Create a directory whose full name is > 270 characters
Copy a portable .NET Core app into the directory
`dotnet {path to app}/app.dll`

## Expected  behavior
Ideally, the app will run despite the long file path. Likely impossible, so instead print an error message upon failure that suggests that long file paths are a likely culprit.

## Actual behavior
Difficult-to-diagnose `file not found` style errors. E.g. Cannot load file hostpolicy.dll.

**Comment by Petermarcu** [comment]
I think this goes all the way down to the loader in the runtime.

**Comment by Petermarcu** [comment]
Does seem like a good idea to give a better error and once long file paths are handled in the loader, this would just work.

**Comment by gkhanna79** [comment]
Inability to load hostpolicy.dll stems from host and not from the loader.

**Comment by Petermarcu** [comment]
Oh good. Hopefully and easier fix then.

**Comment by gkhanna79** [comment]
Closing as dup of https://github.com/dotnet/core-setup/issues/1489
