### ISSUE TITLE
Installation failure when installing Shared Framework 1.0 after Shared Framework 1.1

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/core-setup#1408]
CLI saw installation failures after a recent PR reversed the order in which Shared Frameworks were installed within the CLI bundle. The immediate issue was resolved in CLI, but it seems there is a fundamental problem in play.
 
Users should not have to care about the order in which they install the Shared Frameworks. 1.0 should be able to install cleanly on a machine that already has 1.1, 2.0, etc. without knowledge of future SxS versions. I think we need to investigate this in terms of Shared Fx setup and get a fix into the Shared Framework installers.
 
The specific issue that was hit was that the HostFxr installer detected a later version on the box [brought by 1.1 hostfxr] and failed to avoid a downgrade. From our previous discussions, this is not the behavior we want for the host. Instead:
 
IF a newer host is installed, an older host should add to the ref count and claim success
IF a newer host FXR is installed, an older host FXR should silently install SxS. Thus, when the newer Host FXR gets uninstalled then the host can fall back to the older host FXR
IF a newer Shared FX is installed, an older Shared Fx should silently install SxS so apps can use either based on runtimeconfig.json.

**Comment by gkhanna79** [comment]
Assigning this to you @rakeshsinghranchi and @vivmishra

**Comment by rakeshsinghranchi** [comment]
All the issues mentioned above are fixed for 2.0.0 installers. 
This issue can be closed once below are closed ( for 1.1.x and 1.0.x ) :
https://github.com/dotnet/core-setup/issues/1645
https://github.com/dotnet/core-setup/issues/1646

**Comment by rakeshsinghranchi** [comment]
Closing as both issues are closed : #1645 and  #1646 .
