### ISSUE TITLE
Daily builds aren't very daily

### ISSUE THREAD

**Issue by benaadams** [dotnet/core-setup#1454]
Download build is `2.0.0-beta-001501-00` though current build should be `2.0.0-beta-25005-00`?

Means following the "Get a daily build" instructions from here don't get you a daily build https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md

**Comment by gkhanna79** [comment]
Core-Setup build number logic is different from what is used in CoreFX and CoreCLR. Hence, 1501 is expected. There is an effort underway (non-trivial overall engineering change for the repo) that, when completed, will result in similar build numbers.

Until then, the current scheme will be maintained.

Hope this clarifies.

**Comment by benaadams** [comment]
Hmm... this is NetCore App? Might need to go bug dotnetcli as the sdk install is `2.0.0-alpha-004775` so maybe its that that isn't daily

**Comment by gkhanna79** [comment]
Core-Setup repo only produces the SharedFX on a daily basis (using the build number scheme unique to it), modulo any build breaks.

SDK is produced in CLI repo. Thus, if you are asking about it, CLI is the right repo for it.

**Comment by Petermarcu** [comment]
It's not too slow although I don't think it's daily. I think its just a couple days old. We're still ironing out that flow. 

The version of the sdk is alpha but if you install it, you will see a version of netcoreapp that is beta installed. 

I see `2.0.0-beta-001486-00` in the installer from the CLI which is about 20 checkins behind core-setup. I do see that the links to just get the runtime are broken in the CLI master readme.md. @eerhardt, is that something you can fix up?

@benaadams, Curious why you thought it should be `2.0.0-beta-25005-00`. Trying to see if we have something pointing to higher versions?

**Comment by benaadams** [comment]
Going from the numbers in coreclr and corefx which are the versions I'm trying to use e.g. https://github.com/dotnet/coreclr/commit/e5d6ecbfe30c1824134a290ed5f2f8fb1dc43e7a and https://github.com/dotnet/corefx/commit/6e837bb7bc3b807b4dcc5f0c8096e82af00fd986

My method currently is build app self-contained `<RuntimeIdentifier>win7-x64</RuntimeIdentifier>` publish; build coreclr from source, copy over the binaries into the publish directory; as then I know what version I'm using.

**Comment by Petermarcu** [comment]
I see. Yeah, that should work. The intent of those instructions I believe we're to show people how to use the latest buildskyberg@microsoft.com to publish with rather than the "copy over" method. The 2.0 tooling stack is just being brought up as most of the focus is still on getting 1.0 tooling finished.

**Comment by eerhardt** [comment]
> I do see that the links to just get the runtime are broken in the CLI master readme.md. @eerhardt, is that something you can fix up?

If by "fix up" you mean "remove", then yes.  It doesn't make sense for the CLI readme to have the installer links for the runtime.  Instead, I'll just add a link from the CLI readme to the core-setup readme, which will always have the correct/updated links.

**Comment by eerhardt** [comment]
> My method currently is build app self-contained <RuntimeIdentifier>win7-x64</RuntimeIdentifier> publish; build coreclr from source, copy over the binaries into the publish directory; as then I know what version I'm using.

@benaadams - yes, if you need to use a private build of coreclr or corefx, this is the best option today.  It is unfortunate, but our tooling is all based around the `Microsoft.NETCore.App` NuGet package. So to use the default tooling behavior, you would need to build `dotnet/core-setup` using your private coreclr/corefx builds, which is not a trivial process at the moment.

**Comment by eerhardt** [comment]
One last FYI - the cli uses a versioning scheme that is based on the commit count.  So version `2.0.0-alpha-004775` of the CLI is from commit 4775 (which was the latest commit as of 9 hours ago before the latest PR was merged).

The advantage of this build/versioning scheme is that if there are 20 commits in one day, you can get a new official build in the middle of the day for a bug fix/feature.  You don't have to wait until tomorrow to get the fix in an official build.  Also, if there is 4 days without a change, there is no reason to build a daily build for those days.

**Comment by gkhanna79** [comment]
@benaadams Are there any outstanding questions/concerns around this?

**Comment by benaadams** [comment]
No; it sort of makes sense :)
