### ISSUE TITLE
We have duplicate IL for System.Private.Corelib.dll and mscorlib.dll

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#1484]
## Steps to reproduce
Look in the tar.gz's

## Expected  behavior
No System.Private.Corelib.dll next to System.Private.Corelib.ni.dll

## Actual behavior
They are both there.

## Environment data

**Comment by ericstj** [comment]
@gkhanna79 feel free to fix the duplicate entries in your CoreCLR packages.  EG: https://github.com/dotnet/coreclr/blob/89ba46aa6e113486428ac7528f662e3a0a5a55eb/src/.nuget/Microsoft.NETCore.Runtime.CoreCLR/ubuntu/14.04/Microsoft.NETCore.Runtime.CoreCLR.pkgproj#L21-L22

**Comment by jkotas** [comment]
FWIW, this duplication was introduced originally to make nuget guardrails happy: https://github.com/dotnet/coreclr/pull/3043#issuecomment-180515876

**Comment by ericstj** [comment]
@jkotas that's never been a problem for System.Private.Corelib.  It was needed to match ref of mscorlib with lib of mscorlib, but never S.P.C since there is no ref exposed for that.  This is purely a bug in the coreclr package.

**Comment by gkhanna79** [comment]
@brianrob @noahfalk Do you rely on having the IL version of SPC.dll to be present next to CoreCLR in SharedFX?

**Comment by brianrob** [comment]
@gkhanna79, I don't know of any reason why we need the IL version.  Confirming - if we did need IL for something, it's still in the NI, right?

**Comment by noahfalk** [comment]
No dependency that I am aware of from the diagnostics side.

**Comment by gkhanna79** [comment]
@brianrob IL is present in the NI image but the question is really about how you wish to access it. What is the use-case for IL when you would need it?

**Comment by brianrob** [comment]
@gkhanna79, I don't have a use-case for needing IL at this time.  I think you're fine to remove it.  I was just confirming my understanding.

**Comment by noahfalk** [comment]
Debuggers and profilers expect the IL/metadata to exist in the NI image. I don't think anyone was suggesting removing that content from the NI image, but mentioning it just in case. Both of those tools access the data by virtue of the NI being loaded at runtime, then native APIs the runtime provides allow that IL/metadata to be consumed by tools.

**Comment by gkhanna79** [comment]
Issue moved to [dotnet/coreclr #10097](https://github.com/dotnet/coreclr/issues/10097) via [**ZenHub**](https://www.zenhub.com/)
