### ISSUE TITLE
Fix the RID host is built for

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#1504]
The highest RID host is built for is a function of the RID that comes out of https://github.com/dotnet/core-setup/blob/master/build_projects/dotnet-host-build/PrepareTargets.cs#L100. I see the same in 1.1.0 as well - https://github.com/dotnet/core-setup/blob/release/1.1.0/build_projects/dotnet-host-build/PrepareTargets.cs#L50.
 
TargetRID from above is passed to CMake at https://github.com/dotnet/core-setup/blob/release/1.1.0/build_projects/dotnet-host-build/CompileTargets.cs#L191 and that is used to define TARGET_RUNTIME_RID at https://github.com/dotnet/core-setup/blob/release/1.1.0/src/corehost/cli/setup.cmake#L91 which is, then, used as the RID for the host to fallback at https://github.com/dotnet/core-setup/blob/release/1.1.0/src/corehost/cli/deps_format.cpp#L144.

In 1.0.0, I see that RID to be used by the host comes from https://github.com/dotnet/core-setup/blob/release/1.0.0/build_projects/dotnet-host-build/CompileTargets.cs#L173 that computes it from Stage0 path.

@ianhays added the win7-* check above in https://github.com/dotnet/core-setup/commit/20600ceb2e8be73bf63e72341132cf8125c8fcdb#diff-ff058bba01b969c51b1b7f3b68cd9fe0.

This is a rgeression that should be fixed in master (and would also involve ensuring that official builds are done on Win10 boxes so that we get the highest RID) and in 1.1.2 since we are close to stabilizing 1.1.1.

CC @eerhardt @ramarag @leecow @Petermarcu

**Comment by eerhardt** [comment]
Repro:

Reference the attached nupkg in a `netcoreapp1.0` app
[MyRidLib.1.0.0-alpha.nupkg.zip](https://github.com/dotnet/core-setup/files/762118/MyRidLib.1.0.0-alpha.nupkg.zip)

with the following code:

```C#
        static void Main(string[] args)
        {
            new ClassLibrary.Class1().PrintMessage();

            Console.WriteLine("Hello World!");
        }
```

run on a Windows 10 machine, and you get the output:

```
F:\RIDFallback>F:\cli\.dotnet_stage0\x64\dotnet.exe run -p App\App.csproj
This is on Windows10.
Hello World!
```

now upgrade your app to `netcoreapp2.0` and run it on the same machine:

```
F:\RIDFallback>F:\cli\.dotnet_stage0\x64\dotnet.exe run -p App\App.csproj
This is on Windows7.
Hello World!
```

Notice how the wrong asset got selected at runtime.  Instead of selecting the win10 asset, it is selecting the win7 asset on `netcoreapp2.0`.

**Comment by ianhays** [comment]
I'm going to revert the portion of [my commit](https://github.com/dotnet/core-setup/commit/20600ceb2e8be73bf63e72341132cf8125c8fcdb) that modified the rid being passed to the host build. I'll just special-case it for ARM64 since that's what I really wanted anyways.

**Comment by eerhardt** [comment]
From my understanding it is going to take building core-setup official builds on a win10 machine to fix this.

**Comment by ianhays** [comment]
That is also required, yes.

**Comment by naamunds** [comment]
Would Windows Server 2016 work?  Does that have a RID of win10?

**Comment by gkhanna79** [comment]
Server 2016 may work - I think it is peer of Win10. Is it not possible to get Win10 machines for the build?

**Comment by eerhardt** [comment]
IIRC, we used a technical preview of Server 2016 on mseng.  We should probably be able to use RTM by now.

**Comment by gkhanna79** [comment]
Closing since 1.1.x port is being tracked by https://github.com/dotnet/core-setup/issues/1548.
