### ISSUE TITLE
`Error resolving full path []` when running dotnet

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/core-setup#1507]
## Steps to reproduce
1. Run on Nano Server.  You can use the microsoft/dotnet-nightly:2.0-sdk-nanoserver Docker image.  
2. run any dotnet command e.g. dotnet

## Actual behavior
Keep getting multiple `Error resolving full path []` messages in the output.  The commands seem to work correctly however.

**Actual Output**
```
PS C:\app2> dotnet new
Error resolving full path []
Error resolving full path []
Created new C# project in C:\app2.
```

When I run with COREHOST_TRACE=1 set I spotted the following in the output.
```
Deps file:
Failed to obtain Program Files directory, HRESULT: 0x80004001 
```

Program files is located at the normal location
```
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
```

## Environment data
OS - Nano Server

dotnet --info
```
.NET Command Line Tools (2.0.0-alpha-004784)

Product Information:
 Version:            2.0.0-alpha-004784
 Commit SHA-1 hash:  33294e494c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-alpha-004784\
```

## Notes
I don't see this on Debian.  Haven't tried it on other OSs.  1.0.0 builds of CLI work correctly on NanoServer.

**Comment by MichaelSimons** [comment]
@ramarag - could this possibly be related to https://github.com/dotnet/core-setup/commit/31a4a03d38565d3fdd13101a830a78ad5fb6bf1e?

**Comment by ramarag** [comment]
@MichaelSimons please add/point to steps to get the repro environment. For expedient investigation a ready to use repro environment will be appreciated

**Comment by MichaelSimons** [comment]
@ramarag, 

1. IMO the quickest would be to use Docker
   1. https://docs.docker.com/docker-for-windows/install/
   1. Make sure you switch to windows containers - https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers
   1. To reproduce the problem run `docker run microsoft/dotnet-nightly:2.0-sdk-nanoserver dotnet --help`  This will run the latest 2.0 CLI within a Nano Server container.  The source for the Docker image is [here](https://github.com/dotnet/dotnet-docker-nightly/blob/master/2.0/nanoserver/sdk/Dockerfile).

1. If you want to setup an Azure VM, the instructions are [here](https://www.petri.com/install-nano-server-microsoft-azure)
1. If you want a VM or physical machine, the instructions are [here ](https://technet.microsoft.com/en-us/windows-server-docs/get-started/nano-server-quick-start).

If you are using a VM to repro the issue, install the latest 2.0 CLI and run a dotnet cmd such as `dotnet help`

**Comment by ramarag** [comment]
looks like nano does not recognize the guids for 
FOLDERID_Profile and FOLDERID_ProgramData

I have verified that value in the host are the same as what we find in https://msdn.microsoft.com/en-us/library/windows/desktop/dd378457(v=vs.85).aspx

Is there a good way to find the sdk headers for nano ?
The SHGetKnownFolderPath windows call on nano returns an error code ERROR_ENVVAR_NOT_FOUND  and E_NOTIMPL respectively 
 for the calls in 
https://github.com/dotnet/core-setup/blob/a7815178c4ce6c57b31b9bae86fb43e0c40935c8/src/corehost/common/pal.windows.cpp#L160

**Comment by Kralizek** [comment]
Got same issue running `dotnet --version` in a container created using `docker run -it --rm microsoft/dotnet:2.1.300-rc1-sdk`
