### ISSUE TITLE
Programatically Getting the path to the directory containing the framework?

### ISSUE THREAD

**Issue by fearthecowboy** [dotnet/core-setup#1532]
Ok, I have a reaaaaly strange question now.

We have app that generates c# code. 

We have unit tests that use the generator to generate c# code, then compiles the code using Roslyn, and then loads the generated assembly and  uses reflection to inspect the code to check that things went right.

When we were running on desktop clr, we used `AppDomain.GetAssemblies()` to get the assemblies that were loaded and added them to the Roslyn compiler as references.

Since we're now on `netcoreapp1.0` we don't have that. 

For some assemblies, I was able to cheat a bit and use stuff like `typeof(RestException).GetAssembly().Location,`

But in the end I needed to get a handful of assemblies from the current runtime folder.

I can hardcode them like this:

``` csharp
        protected static readonly string[] _assemblies = new[] {
            
            @"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.3\System.Runtime.dll",
            @"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.3\System.Net.Http.dll",
            @"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.3\mscorlib.dll",
            @"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.3\System.Threading.Tasks.dll",
            @"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.3\System.Net.Primitives.dll",
            @"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.3\System.Collections.dll",
            @"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.3\System.Text.Encoding.dll",
            @"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.3\System.Text.RegularExpressions.dll",
            @"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.3\System.IO.dll",
        ]
```

And it works.

This only works because I know the `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.3\` part of the path.

Is there *any means* to find out that path for the currently executing `netcoreapp1.0` program, so I can locate these programatically?

**Comment by Petermarcu** [comment]
@gkhanna79 , @weshaggard , can you guys give @fearthecowboy guidance here?

**Comment by weshaggard** [comment]
One approach that may work is to do typeof(object).GetAssembly().Location and then traverse for "*.dll" in that directory which will give you all the assemblies next to the core assembly. That will give you all the potential references not necessary what is loaded at runtime so depending on your scenario that might be enough.

**Comment by weshaggard** [comment]
Actually thinking about that a little more that would also pick-up native dlls which you don't want to pass to the compiler but you can probably do a little further filtering to things that start with "System" or "Microsoft".

**Comment by fearthecowboy** [comment]
I've been trying that. 

I can't seem to get one in the framework folder. They are all showing up as the ones in the `nuget` packages folder.

Have an idea of a type that's in `mscorlib` (but doesn't come from a pkg elsewhere?)

**Comment by fearthecowboy** [comment]
The closest I've come so far is :

``` csharp
        protected static string DOTNET = System.IO.Path.GetDirectoryName( System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName);
        protected static string FRAMEWORK= Path.Combine( DOTNET, "shared", "Microsoft.NETCore.App", "1.0.3" );

        protected static readonly string[] _assemblies = new[] {
            
            Path.Combine(FRAMEWORK, "System.Runtime.dll"),
            Path.Combine(FRAMEWORK, "System.Net.Http.dll"),
            Path.Combine(FRAMEWORK, "mscorlib.dll"),
            Path.Combine(FRAMEWORK, "System.Threading.Tasks.dll"),
            Path.Combine(FRAMEWORK, "System.Net.Primitives.dll"),
            Path.Combine(FRAMEWORK, "System.Collections.dll"),
            Path.Combine(FRAMEWORK, "System.Text.Encoding.dll"),
            Path.Combine(FRAMEWORK, "System.Text.RegularExpressions.dll"),
            Path.Combine(FRAMEWORK, "System.IO.dll"),
        ]
```

But I'd hate to hard-code the '1.0.3' part of that ...

**Comment by weshaggard** [comment]
How are you running? If you are doing "dotnet run" it does do a hybrid of loading assemblies from packages instead of the shared framework. If you do "dotnet <yourapp>" I think the approach I used would work.

I'm not sure what a great way to do that is for "dotnet run" scenario. 

Unfortunately we don't expose the shared framework version anywhere, especially not in "dotnet run" scenarios because it doesn't run on the shared framework.

**Comment by fearthecowboy** [comment]
It's unit tests, so it's run with `dotnet test`

**Comment by weshaggard** [comment]
Yeah I guess there isn't any great solution right now. Good news is that AppDomain.GetAssemblies() will be back in .NET Core 2.0.

For now in 1.0 you try another hack like getting the FX deps file location that the host sets up via AppContext.GetData("FX_DEPS_FILE") and getting the directory from that. I believe that might get you what you want for your scenarios right now.

**Comment by gkhanna79** [comment]
@fearthecowboy Does the above answer your question?

**Comment by gkhanna79** [comment]
@fearthecowboy Let us know if the above answers your question.

**Comment by fearthecowboy** [comment]
Yes, I'm doing pretty good with this approach.
