### ISSUE TITLE
Refactor checked-in build definitions to share common code

### ISSUE THREAD

**Issue by naamunds** [dotnet/core-setup#1555]
The checked-in build definitions (at https://github.com/dotnet/core-setup/tree/master/buildpipeline) share a lot of logic and could be consolidated into a smaller number of build definitions to make maintenance easier. This would follow the pattern used by CoreFX.

/cc @wtgodbe @gkhanna79 @chcosta @mmitche @MichaelSimons

**Comment by MichaelSimons** [comment]
Assigned to @wtgodbe per discussions with @gkhanna79.

**Comment by naamunds** [comment]
All build definitions should be made to upload build logs; currently only the Fedora 23 build definition does this (see https://github.com/dotnet/core-setup/blob/master/buildpipeline/Core-Setup-Fedora23-x64.json#L22-L39).  For the Windows build definitions, the `Contents` will need to use a backslash instead (`"**\\*.log"`).

/cc @ramarag

**Comment by MichaelSimons** [comment]
I logged #1835 to cover the build log issue @naamunds mentioned.  I did this because I am going to fix the shared build definition problem without fixing the build log issue.

Taking ownership of this issue.
