### ISSUE TITLE
Port Nuget lowercasing change to 1.0.X

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#1559]
@rrelyea @emgarten This is for 1.0.5

CC @eerhardt @piotrpMSFT @livarcocc @srivatsn @leecow

**Comment by joelverhagen** [comment]
This is my commit to 1.1.0 that implemented this: https://github.com/dotnet/core-setup/commit/e5d476944462bce31a61852cf8fa1692f7683e7f

**Comment by eerhardt** [comment]
`1.0.5` is open for check-in, correct?  Should we make this change now?

**Comment by gkhanna79** [comment]
Yes, we should get it in now.

**Comment by emgarten** [comment]
Great! I'll take a look at merging Joel's change.

**Comment by emgarten** [comment]
@gkhanna79 @eerhardt which branch should this go into for 1.0.5? master?

**Comment by gkhanna79** [comment]
release/1.0.0 and once your PR is prepared, please send email to shiproom.
