### ISSUE TITLE
Treat negative test failures as passing

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#1561]
Port https://github.com/dotnet/core-setup/pull/1560 and https://github.com/dotnet/core-setup/pull/1563

@wtgodbe do look into fixing this when servicing branch opens.

**Comment by Petermarcu** [comment]
@wtgodbe , can you take a look and give an update?

**Comment by wtgodbe** [comment]
Looks like I let this one slip through the cracks - my mistake. Here's a PR that ports the relevant changes: https://github.com/dotnet/core-setup/pull/2944. Putting up the same for 1.1.0 now.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/core-setup/pull/2945 is the PR for 1.1.0, for issue https://github.com/dotnet/core-setup/issues/1562

**Comment by wtgodbe** [comment]
@Petermarcu do these PRs need to go through shiproom?

**Comment by Petermarcu** [comment]
This is a test only change right? If so, go ahead and make the changes.

**Comment by wtgodbe** [comment]
That is correct - merged the 2 PRs.
