### ISSUE TITLE
Enable conditional rollforward when no candidate FX is found

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#1565]
After the patch rollforward that we do today, if the version of .NET required is not available on the machine, and DOTNET_NO_CANDIDATE_FX_ROLLFORWARD environment variable is set, we will load the next lowest version available and do patch rollforward on that version.

a.      If 1.0.1 is requested and only 1.1.0 and 1.1.1 are on the machine, then you would get 1.1.1
b.      If 1.0.1 is requested and only 1.1.1 and 1.2.0 are on the machine, then you would get 1.1.1
c.       If 1.0.1 is requested and only 2.0 and 2.0.1 are on the machine, then you would get 2.0.1

CC @glennc @DamianEdwards @leecow @bleroy

**Comment by DamianEdwards** [comment]
👍

**Comment by DamianEdwards** [comment]
Perhaps this should be possible via a cmd line arg and/or runtimeconfig.json setting also.

**Comment by cakine** [comment]
@gkhanna79 What is the expected behavior when dealing with prereleases?

For instance:
a. If 1.0.0-dummyA is requested and only 1.1.0-dummyC and 1.1.1-dummyB are on the machine.
b. If 1.0.0 is requested and only 1.1.0-dummy  and 1.2.0 are on the machine.
c. If 1.0.0-dummy is requested and only 1.2.0-dummy and 1.1.0 are on the machine.

**Comment by gkhanna79** [comment]
For pre-release versions, the current policy is to the return the next higher minimum version of the requested pre-release version is missing. There are no patch roll forwards for pre-release versions. Thus, for (a) above, it will return 1.1.0-dummyB after this feature is enabled.

For (b), since the requested version is non-prerelease, 1.2.0 will be returned after this feature is enabled (if you look at resolve_roll_forward implementation, you will see that it either deals with pre-release or non-pre-release requested version at a time - not both). 

For (c), 1.2.0-dummy will be returned after this feature is enabled.

**Comment by glennc** [comment]
@gkhanna79 I don't think C is correct in the example. I think you should get 1.1.0.

Rolling forward onto a pre-release of 1.2.0 when I asked for a 1.0.0 pre-release doesn't seem right. 

Moving to a `1.0.0-echo` or to the next lowest stable would be fine. But I am not convinced about moving to another pre-release of a different version. Do you have more reasoning about why you think it should float to 1.2.0-dummy?

**Comment by gkhanna79** [comment]
This change didn't affect how prerelease versions are handled and even today, if the requested prerelease version is missing, then we will move to the next higher build of the prerelease.

This is the thing that your scenario requested in 1.0.



Thanks,
Gaurav


-------- Original message --------

**Comment by glennc** [comment]
You are saying that today, before this change or if this change is not enabled, then `1.0.0-foo` will roll forward to `1.1.0-foo` if `1.0.0-foo` is not on the machine?

**Comment by cakine** [comment]
Actually, C will fail in the example. Pre-releases can only roll forward onto pre-releases with the same major, minor and patch values. But, like @gkhanna79 stated, this change didn't affect this behavior.

**Comment by glennc** [comment]
OK. That makes sense. It is rolling forward across major/minor versions that I was concerned about. Today a pre-release doesn't roll forward onto a stable either, and if I understand correctly this doesn't change that either. Is that correct?

**Comment by cakine** [comment]
Correct.

**Comment by mikaelm12** [comment]
> After the patch rollforward that we do today, if the version of .NET required is not available on the machine, and DOTNET_NO_CANDIDATE_FX_ROLLFORWARD environment variable is set, 

Just fyi, the environment variable is actually called  `DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX`.
[Located here](https://github.com/cakine/core-setup/blob/7245872288f911eedb7bf4daebf360f61e9c19be/src/corehost/cli/runtime_config.cpp#L83)
