### ISSUE TITLE
How to make a linux-x64 SDK

### ISSUE THREAD

**Issue by tmds** [dotnet/core-setup#1578]
There is a linux-x64 download link available at README.md. How can it be used to make a linux-x64 SDK?

**Comment by gkhanna79** [comment]
@piotrpMSFT @livarcocc would need to update CLI to consume it and build the SDK support for it.

CC @eerhardt

**Comment by gkhanna79** [comment]
@tmds Can you please move this to CLI repo where this is applicable to?

**Comment by tmds** [comment]
Moved to https://github.com/dotnet/cli/issues/5811
