### ISSUE TITLE
Ubuntu 16.04 and 14.04 arm32 builds don't seem to be hooked up to netcore.app

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#1589]
## Steps to reproduce
try to publish standalone for ubuntu.14.04-arm

I looked at runtimes.json in the package and its not referenced.

## Expected  behavior
You get a standalone app with all the assets

## Actual behavior
You get a shared framework app

## Environment data

**Comment by Petermarcu** [comment]
@ericstj

**Comment by Petermarcu** [comment]
@gkhanna79 as well. I can make the PR to fix this if someone points me at where this needs to be. I tried here: https://github.com/dotnet/core-setup/blob/master/pkg/projects/Microsoft.NETCore.App/Microsoft.NETCore.App.props but that doesn't seem to do it.

**Comment by ericstj** [comment]
@Petermarcu that's the right place to do it.  What made you think it wasn't working?

**Comment by Petermarcu** [comment]
I added the additional entries and built but didn't see them showing up in the runtimes.json under pkg\bin\localpkg. Where should I look to see if the change worked?

**Comment by Petermarcu** [comment]
I may see the problem with my change. Can you confirm I'm looking in the right place to verify the change?

**Comment by gkhanna79** [comment]
I would like to understand this better - https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.ubuntu.14.04-arm.Microsoft.NETCore.App is already getting published. Why do we need a change in the file above to ensure that CLI's standalone publish should work like it used to before this file was introduced?

**Comment by Petermarcu** [comment]
It seems like you either have to link it in the runtimes.json or explicitly reference the runtime package. I was also hoping that there wasn't a need to have a reference in the runtimes.json but it appeared to be the way it works.

**Comment by Petermarcu** [comment]
@ericstj , it was a bug in my change. It is now showing up in the runtime.json.

**Comment by gkhanna79** [comment]
> It seems like you either have to link it in the runtimes.json

Which runtimes.json is this and why is this change required to make standalone work (and not required earlier)?

**Comment by Petermarcu** [comment]
Here is my PR: https://github.com/dotnet/core-setup/pull/1592

**Comment by Petermarcu** [comment]
When I publish standalone for the new RID's the contents of the runtime package don't get placed into my publish folder.

**Comment by gkhanna79** [comment]
My question is that such a change was not required earlier as CLI would ensure that all artifacts would get to the publish folder. Why do we need to make a change Core-Setup now to support the standalone experience in CLI?

**Comment by Petermarcu** [comment]
I've had the same question in my head. I'd like to understand how all this hooks up better.

**Comment by ericstj** [comment]
Because core-setup builds RID specific packages.  Previously it did not.

FWIW vertical build for these RIDs still works just fine with no change.  It's just needed because we ship a single package for convenience of reference that needs to list all the RID-specific packages.

**Comment by Petermarcu** [comment]
I thought the whole design was to allow additional rids to hook up to netcoreapp without needing to modify it.

**Comment by ericstj** [comment]
That's right, it isn't needed for vertical build.  This package isn't a vertical build package.  Its a single RID-less package that has to be produced in one place.

**Comment by gkhanna79** [comment]
Fixed with https://github.com/dotnet/core-setup/pull/1592
