### ISSUE TITLE
Hi everyone, after suffring during three weeks, running through linux OS, installing, uninstalling, I finally find issue about segmentation fault on debian 8 to highier when running dotnet new/dotnet restore/dotnet build and so on. The issue is to downgrade libcurl3 instead of the newest version. Enjoy

### ISSUE THREAD

**Issue by nazal2013** [dotnet/core-setup#1591]
## Environment data

**Comment by Petermarcu** [comment]
Which version of Debian 8 are you on? We do testing on Debian 8+. Also, can you provide more details on the version of libcurl that didn't work and which one you downgraded to to get it working?

**Comment by nazal2013** [comment]
Dear Peter,

Thanks a lot for your interest in my answer, I have kali linux with latest update(now = debian 9) and after downgrade from libcurl3_7.58 to libcurl3_7.38, I fixed the Segmentation fault error. Thanks

________________________________
De : Peter Marcu <notifications@github.com>
Envoyé : dimanche 26 février 2017 17:38:11
À : dotnet/core-setup
Cc : Oumarou CHAÏBOU; Author
Objet : Re: [dotnet/core-setup] Hi everyone, after suffring during three weeks, running through linux OS, installing, uninstalling, I finally find issue about segmentation fault on debian 8 to highier when running dotnet new/dotnet restore/dotnet build and so ...


Which version of Debian 8 are you on? We do testing on Debian 8+. Also, can you provide more details on the version of libcurl that didn't work and which one you downgraded to to get it working?

**Comment by Petermarcu** [comment]
Thanks for the info. We'll take a look at whats going on with the newer curl. @janvorli @gkhanna79

**Comment by janvorli** [comment]
I am just installing Debian 9 and I will look into it.

**Comment by janvorli** [comment]
Unfortunately, Debian 9 VM gets into perpetual restart loop on my HyperV after the installation completion. I'll try to get the Kali Linux you've mentioned to see if that works for me. They have HyperV image, so that should work, I hope.

**Comment by nazal2013** [comment]
Try it must work 
________________________________________
De : Jan Vorlicek [notifications@github.com]
Envoyé : lundi 27 février 2017 17:43
À : dotnet/core-setup
Cc : Oumarou CHAÏBOU; Author
Objet : Re: [dotnet/core-setup] Hi everyone, after suffring during three weeks, running through linux OS, installing, uninstalling, I finally find issue about segmentation fault on debian 8 to highier when running dotnet new/dotnet restore/dotnet build and so ...

Unfortunately, Debian 9 VM gets into perpetual restart loop on my HyperV after the installation completion. I'll try to get the Kali Linux you've mentioned to see if that works for me. They have HyperV image, so that should work, I hope.

**Comment by janvorli** [comment]
@nazal2013 So I have installed the Kali Linux and it works in the VM. How do I install the latest update that will bring the debian 9 stuff in?
And can you please tell me which link have you used to install dotnet? We provide various versions and two ways of installation (tar.gz vs debian package).

**Comment by janvorli** [comment]
@nazal2013 Could you please respond to my previous comment? I have installed Kali Linux, tried `apt-get upgrade` and `apt-get dist-upgrade`, but I am probably still on some older stuff since my libcurl3 version is 7.52.1-3.

**Comment by nazal2013** [comment]
Hi, sorry for late, I download it from Debian packages website not via repositories. Just download libicurl3 version 7.38 as deb package and install it
________________________________________
De : Jan Vorlicek [notifications@github.com]
Envoyé : jeudi 2 mars 2017 15:50
À : dotnet/core-setup
Cc : Oumarou CHAÏBOU; Mention
Objet : Re: [dotnet/core-setup] Hi everyone, after suffring during three weeks, running through linux OS, installing, uninstalling, I finally find issue about segmentation fault on debian 8 to highier when running dotnet new/dotnet restore/dotnet build and so ...

@nazal2013<https://github.com/nazal2013> Could you please respond to my previous comment? I have installed Kali Linux, tried apt-get upgrade and apt-get dist-upgrade, but I am probably still on some older stuff since my libcurl3 version is 7.52.1-3.

**Comment by janvorli** [comment]
@nazal2013 I am not sure how could you have succeeded running dotnet restore on Debian 9. There is no `openssl1.0.0` package for it, only `openssl1.1.0` (based on this: https://security-tracker.debian.org/tracker/source-package/openssl) which we don't support and when I run `dotnet restore`, it fails with the following error due to the missing openssl1.0.0 dependency:
```
/home/janvorli/dotnet/sdk/2.0.0-alpha-005156/NuGet.targets(97,5): error : The type initializer for 'Crypto' threw an exception. [/home/janvorli/dotnet/test/test.csproj]
/home/janvorli/dotnet/sdk/2.0.0-alpha-005156/NuGet.targets(97,5): error :   Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found. [/home/janvorli/dotnet/test/test.csproj]
/home/janvorli/dotnet/sdk/2.0.0-alpha-005156/NuGet.targets(97,5): error :    (Exception from HRESULT: 0x8007007E) [/home/janvorli/dotnet/test/test.csproj]
```

**Comment by janvorli** [comment]
@nazal2013 I think I understand what you have done. You have probably installed libssl1.0.0, openssl1.0.0 and libcurl3 for Debian 8 and that made it work for you, right? I've tried these steps and they fixed the problem.

**Comment by karelz** [comment]
.NET Core 2.1 does not depend on libcurl anymore. The key source of problem should be gone now.

**Comment by nazal2013** [comment]
Thank you for sharing Sir

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
