### ISSUE TITLE
[release/1.0.0, release/1.1.0] Use NuGet v2 endpoint (not v1.6) to push to MyGet

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#1596]
Currently the release servicing branches push to the v1.6 MyGet url, which fails in some situations such as overwriting a package. https://github.com/dotnet/core-setup/pull/1567 needs to be ported to the release branch builds, when possible.

**Comment by ravimeda** [comment]
Update the value of NUGET_FEED_URL from "https://dotnet.myget.org/F/dotnet-core"  to  "https://dotnet.myget.org/F/dotnet-core/api/v2"  in all buildpipeline/*.json.

**Comment by gkhanna79** [comment]
@ravimeda Is this fixed for the upcoming servicing release?

**Comment by ravimeda** [comment]
No. Instead https://github.com/dotnet/core-setup/pull/1870  changed NUGET_FEED_URL from "https://dotnet.myget.org/F/dotnet-core" to "ENV_VAR_EMPTY_WORKAROUND"
@dagood is fixing this issue still relevant?

**Comment by dagood** [comment]
It is fixed now. These variables are now passed from the pipebuilds, and they're set up with the v2 urls.
