### ISSUE TITLE
Dynamically lightup of injected packages as part of application closure

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#1597]
Today, an application's closure is defined by its corresponding .deps.json file, which is statically computed and known at publish time. However, there are scenarios where certain packages may needed to be injected at runtime for them to become part of the application closure. 

To support this, the entity wishing to inject packages would produce a _lightup.deps.json_ and place it in a folder that mimic's the SharedFX layout. That is, the file will live in _<BaseFolder>\Shared\<SharedFXPackageName>\<SharedFrameworkVersion>\lightup.deps.json_. The host will then be pointed to _BaseFolder_  during application activation (either via an environment variable or command line argument) and will lookup _lightup.deps.json_ using the SharedFX package name/version from the application's deps.json.

The contents of this file will then be part of the deps.json merge step in the host, where the app's deps.json will still override it incase of conflicting packages (like it does today for fx.deps.json).

CC @DamianEdwards @glennc @davidfowl @ramarag @cakine @eerhardt @Petermarcu @richlander @bleroy

**Comment by eerhardt** [comment]
@gkhanna79 - Can you give a more concrete user scenario?

**Comment by glennc** [comment]
@eerhardt When you deploy your application to Azure App Service it will automatically log to the right place, taking into account Azure specific configuration, without you needing to remember to explicitly turn it on or configure it before a problem occurs. That's one end goal that we would enable using this.

**Comment by gkhanna79** [comment]
Initial PR for this is at https://github.com/dotnet/core-setup/pull/1727

**Comment by gkhanna79** [comment]
@davidfowl @DamianEdwards @glennc Do you have any thoughts on this?

**Comment by DamianEdwards** [comment]
@gkhanna79 I think it's fine for this feature to not be a capability of standalone apps. I think it's in keeping with the general ethos that standalone/self-contained apps are deployed that specifically because they don't want outside influences on them.

**Comment by gkhanna79** [comment]
@DamianEdwards, in that case, I would like to ensure that feature does not lightup for standalone scenarios. Are you fine with this enforcement?

Also, can you folks please chime in on https://github.com/dotnet/core-setup/pull/1727#discussion_r106680983 as well?

**Comment by DamianEdwards** [comment]
I'm fine with this not working for stand-alone apps.
