### ISSUE TITLE
Update corehost docs

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/core-setup#1614]
The corehost documentation is out of date. https://github.com/dotnet/cli/blob/master/Documentation/specs/corehost.md

For example, docs say the servicing index is configured via environment variable `DOTNET_SERVICING`, but at somepoint this was renamed to [`CORE_SERVICING`](https://github.com/dotnet/core-setup/blob/ccd5fdea16a55a9b79f551b5b060fe82de8b9fd4/src/corehost/common/pal.unix.cpp#L144)...and it this doesn't apply to [Windows](https://github.com/dotnet/core-setup/blob/ccd5fdea16a55a9b79f551b5b060fe82de8b9fd4/src/corehost/common/pal.windows.cpp#L181) anymore.

cc @gkhanna79 @piotrpMSFT

**Comment by gkhanna79** [comment]
@ramarag Can you please move this to Core-Setup repo and update the text as well?
