### ISSUE TITLE
Handle computed RIDs that are missing in RID fallback graph

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#1620]
With PR https://github.com/dotnet/core-setup/pull/1584, the host now computes it's RID at execution time. This works well so long as the RID in question is present in the RID fallback graph the host uses from the SharedFX.

However, if the OS the host is running upon is not supported in the RID fallback graph, then the asset lookup will fail on OSX and Linux (on Windows, we conservatively set the RID to Win10  - see [this](https://github.com/gkhanna79/core-setup/blob/master/src/corehost/common/pal.windows.cpp#L281)).

This issue is to track implementing the solution on what happens on such OS that are not yet supported in RID fallback graph.

CC @eerhardt @Petermarcu @weshaggard

**Comment by gkhanna79** [comment]
One manual workaround for such platforms is to set DOTNET_RUNTIME_ID environment variable to a supported RID.

**Comment by weshaggard** [comment]
Could we also add support for passing this as a parameter to the host? I really hate depending on environment variables.

**Comment by gkhanna79** [comment]
I have been thinking about this. While it is straightforward for us to cap Windows and OSX RIDs to the highest OS version known at the time FX was built (by hard-coding that information), it is not scalable for us to keep that information for Linux as we will need to maintain a list of all known distros and match against them to determine the version we know of. This becomes more fundamental as we work towards Portable Linux as the default.

Another approach to fundamentally address this would be to introduce a pseudo RID in the RID fallback graph definition for each platform/distro that points to the highest version we know at the time SharedFX was built. For example, OSX-Highest-x64 would fallback to OSX.10.12-x64. Likewise, LinuxMint-Highest-x64 would fallback to LinuxMint.18.1-x64.

With this approach, if the host computed RID is not found (e.g. OSX.10.14-x64), we will pretend the host computed RID to be OSX-Highest-X64 and commence RID fallback from there. This behaviour will be consistent across all platforms and the concept will _just_ work. This implies the following:

1) We will add new pseudo RIDs to the fallback graph
2) We will need to keep pseudo RIDs updated to point to the highest fallback version - a task that can be done the next time we supercede the current highest RID with a new one.

What do you think?

**Comment by weshaggard** [comment]
I'm not necessary seeing a difference between hard-coding these pseudo RIDs in the runtime.json for the RID graph vs in the host policy? They both can be updated independently as needed. 

I see a couple potential risks with having the pseudo RIDs in the runtime graph, that wouldn't exist if they were in the host policy. 

1. will start potentially using them in their packages and essentially cause their packages to float and not work after a new platform update.
2. Folks may try to redefine them in their own runtime.json file which could get us into an interesting state.

**Comment by gkhanna79** [comment]
One fundamental difference is that host code remains unchanged (aside from adding the look up of the new pseudo RID) and when we add new RIDs in future, we do not have a dependency to update the host as well. Otherwise, we need to update the everytime the RID graph is updated, splitting it into two different repos and coordinating the change.

Also, making the change in the host implies that we will need to add checks for parsing Linux distros in the host before determining which "highest version" to apply. With all this data in RID fallback graph, this just falls out and host logic remains simple (and abstracted from versioning). Essentially, we have all the information already available in RID fallback graph except the pointer to the last highest version. This is the goal of the pseudo RID.

**Comment by gkhanna79** [comment]
Needless to say, the guideline would be to not use these RIDs. I also corrected the representation of pseudo RID above.

**Comment by gkhanna79** [comment]
@Petermarcu @weshaggard and I chatted about this offline as well and agreed that we need to keep things simple. In that light, when the computed RID (which will not be capped to the known highest version for Windows and OSX) is not found in the RID fallback graph, we will use the base RID for all the platforms (e.g. win-x64, osx-x64, linux-x64).

**Comment by omajid** [comment]
I can't comment on Windows, but for an unknown linux distribution, handling it as `linux-x64` (which assumes a linux with recent-ish glibc) seems like a very good approach.
