### ISSUE TITLE
Segmentation fault on Raspberry Pi (Ubunty 16.04) when trying to run a Web API

### ISSUE THREAD

**Issue by challe** [dotnet/core-setup#1622]
## Steps to reproduce
`dotnet new webapi`

Change the `csproj`-file so that it looks like this:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
 <PropertyGroup>
   <TargetFramework>netcoreapp2.0</TargetFramework>
   <RuntimeFrameworkVersion>2.0.0-beta-001518-00</RuntimeFrameworkVersion>
   <ServerGarbageCollection>true</ServerGarbageCollection>
 </PropertyGroup>

 <ItemGroup>
   <PackageReference Include="Microsoft.AspNetCore" Version="1.2.0-preview1-23656" />
   <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.2.0-preview1-23656" />
   <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.2.0-preview1-23656" />
 </ItemGroup>
</Project>
```
Followed by
```
dotnet restore
dotnet publish
```

Now take all of the files that were created in the `bin/Debug/netcoreapp2.0/publish` and copy these files to the Raspberry Pi. Try to run the application by doing:
`usr/bin/dotnet /home/challe/dev/test/test.dll`

## Expected  behavior
Something along the lines of `Now listening on: http://localhost:5000`, or however it is supposed to say that it is running.

## Actual behavior
`Segmentation fault`

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-alpha-004853)

Product Information:
 Version:            2.0.0-alpha-004853
 Commit SHA-1 hash:  e7689a3116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-alpha-004853\

# Notes
I have created a wiki page [here](https://github.com/challe/dotnet-core-raspberry-pi/wiki/Setting-up-a-Web-API-on-a-Raspberry-Pi-3-(Ubuntu-16.04)-using-.NET-Core-2.x-(and-1.x)) describing all of the steps I have taken so far to making this work (currently stuck on the Segmentation fault). Perhaps there are more clues there as to what I am potentially doing wrong.

**Comment by gkhanna79** [comment]
Does the segmentation fault go away when the following is false?

`<ServerGarbageCollection>true</ServerGarbageCollection>`

CC @janvorli

**Comment by challe** [comment]
That's the one that is supposed to add `System.GC.Server` to your `runtimeconfig.json`, right? I have tried running it with it being set to both `true` and`false` with the same result:
```
{
  "runtimeOptions": {
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.0.0-beta-001518-00"
    },
    "configProperties": {
      "System.GC.Server": false
    }
  }
}
```

**Comment by challe** [comment]
After updating the runtime on my Raspberry Pi from `2.0.0-beta-001518-00` to 2.0.0-beta-001663-00, this error does no longer occur.

**Comment by gkhanna79** [comment]
Excellent @challe

**Comment by gkhanna79** [comment]
@challe I am closing this issue based upon your comment above.
