### ISSUE TITLE
Keep ~/resources/ThirdPartyNotices.txt up to date

### ISSUE THREAD

**Issue by richlander** [dotnet/core-setup#1638]
How does that happen? which  repos are "consulted" for this content?

https://github.com/dotnet/core-setup/blob/master/resources/ThirdPartyNotices.txt

**Comment by omajid** [comment]
I am also curious about the difference between `resources/ThirdPartyNotices.txt` and `THIRD-PARTY-NOTICES`.

**Comment by richlander** [comment]
THIRD-PARTY-NOTICES is a statement for the repository. You can see we have those in most of our repos.

This other file in resources is for the built product as a binary distribution. When you build any product, commercial or free, you need to include a notice (in some form) that states what third party components are included. Assuming the form is a file (which is quite common) then that file needs to materialize. It can itself be in the repo (as it is here) or be generated as part of the build/post-build.

So, these two files will always be different since the resources variant is for the whole scope of .NET Core while the one at the root is only for a given repo.

**Comment by gkhanna79** [comment]
@richlander What is the expected next step here?

**Comment by gkhanna79** [comment]
cc @leecow

**Comment by richlander** [comment]
@Petermarcu and I were discussing this. Here is the basic take-away:

- Each repo should have an up-to-date 3PN at the root using our uniform format.
- Each repo should publish repo-specific distributions that include that 3PN. This will typically be NuGet packages.
- A tool/process should be written that harvests and aggregates the 3PN files from either NuGet or GitHub (I don't personally care which) and then use that as the input for the file in question.
- Given our process, it's likely that the 3PN files are going to get updated ~ quarterly. So, the tool/process could be run per build or it could be run manually say once/month and checked in. On-demand would be possible, too. I am OK with latency of a month.

**Comment by Petermarcu** [comment]
@richlander can you work with @shawnro to get this tool on the engineering backlog? Its something that all our projects are going to need to have so things will flow properly.

**Comment by richlander** [comment]
Sure. Can do.

@bleroy - can you include this in your "build from source" effort with @shawnro. It's somewhat related.

**Comment by gkhanna79** [comment]
@leecow What are the next steps on this?

**Comment by weshaggard** [comment]
This was done with https://github.com/dotnet/core-setup/pull/2391.
