### ISSUE TITLE
Port #1424 to master

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#1653]
We merged a fix to `release/1.1.0`, but that fix isn't in the `master` branch.

See #1424.  in `release/1.1.0` we have DiaSymReader.Native `1.4.1`.  In `master` we still have `1.4.0`.

@gkhanna79 @tmat @mikem8361

**Comment by gkhanna79** [comment]
@tmat Can you please do the needful?

**Comment by gkhanna79** [comment]
@tmat Do you have an ETA on this?
