### ISSUE TITLE
Get Docker on ubuntu 16.04 Jenkins CI machines

### ISSUE THREAD

**Issue by brthor** [dotnet/core-setup#167]
See #164 

Docker is not available on Jenkins CI machines so we cannot build ubuntu 16.04 debian packages.

**Comment by joshfree** [comment]
@piotrpMSFT @Petermarcu

**Comment by piotrpMSFT** [comment]
This doesn't block us from building the packages in VSO. We still get the packages, but have to do a workaround in Jenkins CI. 

/cc @livarcocc

**Comment by ellismg** [comment]
I can take care of this after RTM.

**Comment by gkhanna79** [comment]
@ellismg What is this issue about and is there anything outstanding for it?

**Comment by ellismg** [comment]
> What is this issue about and is there anything outstanding for it?

The issue here is that we don't have docker install on our Ubuntu 16.04 machines, so core-setup can not build in a docker container during CI.  This prevents them from doing some testing because they don't have an isolated environment in which to install the packages they build to test them.

**Comment by brthor** [comment]
Ping @mmitche 

He had a thread with DDIT for setting this up in July. Did that ever come through?

**Comment by mmitche** [comment]
I thought this got finished.  Lemme hunt down some emails.

**Comment by mmitche** [comment]
Yes this is available in the latest 16.04 images.

**Comment by gkhanna79** [comment]
@mmitche @ellismg What is next here?

**Comment by mmitche** [comment]
@gkhanna79 Done
