### ISSUE TITLE
Is .Net Framework 4.5.1 required .Net Core Windows Hosting by force?

### ISSUE THREAD

**Issue by tloo** [dotnet/core-setup#1673]
Is .Net Framework 4.5.1 required .Net Core Windows Hosting by force?

## Steps to reproduce
On Windows Server 2008, we have .Net Framework 4.5.5 installed.

## Expected  behavior
.Net Core Windows Hosting should be installed correctly.

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/375419/23723943/0626ab68-0419-11e7-9999-7849ac8078e1.png)
The logs
[dd_DotNetCoreWinSvrHosting__20170308155829.log.txt](https://github.com/dotnet/core-setup/files/828962/dd_DotNetCoreWinSvrHosting__20170308155829.log.txt)

**Comment by gkhanna79** [comment]
@glennc @DamianEdwards Can you please loop in the right folks? Also, is there a more appropriate repo to move this issue to?

CC @leecow

**Comment by gkhanna79** [comment]
@DamianEdwards Can you help move this to appropriate repo and assign to right folks?

**Comment by glennc** [comment]
I think @joeloff is the right person for this, and can move it to where it should belong.

**Comment by joeloff** [comment]
Yup, you can assign to me. The requirement though is a minimum version

@tloo Can you share your setup logs? We specifically look at HKLM\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full and examine the Release value.

**Comment by gkhanna79** [comment]
@joeloff Is not on the assigned to list - @joeloff Can you please move this bug to appropriate repo?

**Comment by joeloff** [comment]
This issue was moved to aspnet/Home#1991

**Comment by joeloff** [comment]
@gkhanna79 I've moved the issue. you can go ahead and close it. I don't think I have permissions to do that.

**Comment by gkhanna79** [comment]
Thank you @joeloff
