### ISSUE TITLE
HostPolicy servicing maybe broken after RID split package support

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#1674]
See https://github.com/dotnet/core-setup/blob/master/src/corehost/cli/fxr/fx_muxer.cpp#L57

CC @ericstj

**Comment by gkhanna79** [comment]
This is a forcing function to understand how the following will work in 2.0.0:

1) Hammer servicing for M.N.App constituents
2) Ensure that RID split version of M.N.App only gets the locked versions of the host (or only gets the components that are serviced).

CC @weshaggard @eerhardt @ramarag

**Comment by ericstj** [comment]
I think @ramarag was undoing the change that merged the host into NETCore.App.  I don't care much what you do here, just make your scenarios work and understand that there is a desire to flatten the package graph for .NET Core App.  I think you can make either work and there are likely additional changes to make the merge work.

**Comment by weshaggard** [comment]
We need to be sure that we still have a working hammer servicing story for other things beyond just the hostpolicy. We need to make sure it works for everything in the flat NETCore.App package.

**Comment by ericstj** [comment]
That just works.  They are still in packages and the path is based on the package path.  Hammer servicing has always been 1:1 with the package ID, version, and path in the package.

**Comment by gkhanna79** [comment]
@ramarag I am assigning this to you since you are looking into fixing this.

**Comment by gkhanna79** [comment]
To close the loop, have we confirmed that fx.deps.json contains the data expected for this validation?



Thanks,
Gaurav


-------- Original message --------

**Comment by ramarag** [comment]
I have verified the entry in fx.deps.json and it now points to hostpolicy package.

Just for the sake of completeness, the version of hostpolicy in the  fx.deps.json is whatever that was specified in the M.N.App package and the assembly that is put in the shared framework is from the locked version in the core-setup repo, They could Diverge!!!

**Comment by gkhanna79** [comment]
I am not aware of this behavior being valid even before Eric's changes. Where do you see that happening? It is a bug.



Thanks,
Gaurav


-------- Original message --------
