### ISSUE TITLE
Merge core-setup and core repos

### ISSUE THREAD

**Issue by richlander** [dotnet/core-setup#1707]
I have been looking at the core-setup and core repos. It increasingly seems like they have overlapping goals. I am wondering if we would be best off by merging them. Also core-setup is a bad name, while Core is a good one (more intuitive / accurately descriptive).

If people agree, I would suggest that we rename this repo to core and delete the other one (import current core repo history here via an orphan branch).

Thoughts?

/cc @petermarcu @leecow

**Comment by Petermarcu** [comment]
It's an interesting thought. There are some things to consider. netcoreapp as well as uwp get built here. The cli and sdk repos likely need consideration as well. IMHO, they are in a much more confusing state. Whichever way we go, there will be a lot of infra and links to fix up and it would have to be a well coordinated effort.

**Comment by richlander** [comment]
Github repos preserve links on rename.

Major point is that I would like for the core repo to be more useful, including build information (like core-setup has) and the build from source effort is going to target that.

It could be that core-setupjust isn't the one to join forces with and I am willing to believe that.

In any case, now is the time to rethink some of this as the start of the 2.0 project.

**Comment by Petermarcu** [comment]
I agree with the direction. Let's see if we can come up with a proposal for the shape we want to get to. The links I'm talking about aren't the comment links. It's all ouright infra that points to different places and all the checked in links.

**Comment by richlander** [comment]
All the links should work (I believe), like `git clone core-setup`. Anyway, I agree with you ... let's come up with a plan. 

This is related: https://github.com/dotnet/core/issues/520#issuecomment-285753568

**Comment by omajid** [comment]
Request from (somewhat of) an outsider: it would be great if someone cloned github/dotnet/core and got the same thing as the "full" .NET Core: the SDK. That's equivalent to the current "cli" repo, right?

If not, +1 on making it match .NET Core runtime (aka current core-setup).

**Comment by gkhanna79** [comment]
>  It increasingly seems like they have overlapping goals.

Can you please elaborate on this @richlander ?

**Comment by richlander** [comment]
Sure. There is now engineering work in the core repo: https://github.com/dotnet/core/tree/master/tools/dotnet-bootstrap. This work enables you to build the whole product from source. The existing core-setup repo doesn't something similar in a different way. Is that right?

**Comment by gkhanna79** [comment]
> The existing core-setup repo doesn't something similar in a different way. Is that right?

I am not sure what the above mwans - Are you asking if Core-Setup offers similar capability?

**Comment by richlander** [comment]
Sorry. I mis-typed. I meant: "The existing core-setup repo does something similar in a different way". Also, the whole readme is an intro to .NET Core of sorts. That's what we had in mind for dotnet/core.

**Comment by richlander** [comment]
@leecow - Can you share our notes from our discussion today and then close the issue? We should also create an issue for @livarcocc in the dotnet/sdk repo, per the repo for the SDK. Thanks!

**Comment by leecow** [comment]
Meeting notes: 

**Core repos**
 - Common information, dependency info, etc are appropriate for a central location. Eg dotnet/core
     - Release documentation assets
     - Issue logging
     - Potentially sub-module as BfS entry point 

 - core-setup remains separate but common info in readme and info moves to /core
 - cli bootstrapper (https://github.com/dotnet/core/tree/master/tools/dotnet-bootstrap) can move to bfs repo as soon as it comes into the open
- Docker defs currently under dotnet-bootstrap could move to the Docker/Eng Infra repo being created by Michael Simmons.
     - CLI and SDK repos need to be rationalized/rebranded. [Issue 1004 opened in sdk repo](https://github.com/dotnet/sdk/issues/1004).

Currently the SDK repo seems to represent only msbuild tasks and templates whereas the CLI repo covers all engineering and building of what is the actual SDK. This creates a great deal of confusion both internal and external. The repo that builds the SDK should obviously be "the SDK". 

**Announcements repo** 
Announcement-only repo idea accepted and will be created (dotnet/announcments). Could be used to feed other comms channels such as Foundation forums, RSS feeds, etc

**Core Design repo**
Core "design" repo patterned after dotnet/csharplang. Content under core-proposal would use this to move currently private content into the open. Cross cutting features where no single repo would be a good fit for the design discussion.
 - Scope: Potentially everything other than languages
 - Principally future work
 - Customer experience, product design, PM driven
