### ISSUE TITLE
Core-Setup build should not rely on Dockerfile within the repository

### ISSUE THREAD

**Issue by ravimeda** [dotnet/core-setup#1719]
## Steps to reproduce

1. Perform an official build.

## Expected  behavior
Rather than consuming (or maintaining) a Dockerfile within a repository, it is more efficient to specify the image name required through PB_DockerImageName variable in a build task, and let PipeBuild pull the appropriate image on behalf of the build.  Investigate the possibility of reusing the shared images in `microsoft/dotnet-buildtools-prereqs`.

Given the scope of this change, do not consider this for existing servicing branches i.e., 1.0.0 and 1.1.0.

## Actual behavior
Builds relies on Dockerfiles located within the repository at `/core-setup/tree/master/scripts/docker`

**Comment by wtgodbe** [comment]
@MichaelSimons can you confirm that this has already been done?

**Comment by MichaelSimons** [comment]
@wtgodbe - Nothing has been done on this.  A dup was just logged yesterday - #2031.

**Comment by rakeshsinghranchi** [comment]
Please consider these docker files as well : https://github.com/dotnet/core-setup/tree/master/scripts/docker

**Comment by gkhanna79** [comment]
We should do this for 2.0 @wtgodbe.

CC @eerhardt

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/core-setup/commit/6887ab556bc8302390782711dcdd75b75e769cf5
