### ISSUE TITLE
Microsoft.NETCore.App 2.0 should no longer depend on Microsoft.NETCore.DotNetHost

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#1722]
End users will no longer consume the host that is contained in `Microsoft.NETCore.DotNetHost`.  It no longer makes sense to have every .NET Core console app depend on this host, and have tooling that just takes it out of the build/publish content.

Another approach we could take:

No longer build the `Microsoft.NETCore.DotNetAppHost` package.  Instead, just put the "AppHost" in the existing `Microsoft.NETCore.DotNetHost` package, replacing the existing `dotnet.exe` asset with the `apphost.exe`.

Going a step further, if we renamed `apphost.exe` to `dotnet.exe` in the package, then tooling wouldn't even need that much smarts in it.  The tooling can simply say:

1. Rename the resolved `dotnet.exe`file to `AppName.exe`.  (We do this today)
2. `[if TFM >= netcoreapp2.0]` EmbedAppNameInHost.

**Comment by gkhanna79** [comment]
I agree that doing this will definitely simplify things in SDK. However, it also requires thinking a bit more about how Core-Setup platform installers would need to be produced, how we specify the version of DotnetHost package to be used for platform installer generation, to name a few.

> Instead, just put the "AppHost" in the existing Microsoft.NETCore.DotNetHost package

We cannot do this as explained at https://github.com/dotnet/sdk/pull/978#discussion_r105721813. I think better approach would be to have HostFXR have a dependency on AppHost package but with that, we need to resolve the issue described above in this comment.
