### ISSUE TITLE
Sign the muxer (dotnet.exe)

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#174]
Currently, dotnet.exe is not signed since it is used by CLI for standalone apps. We need to determine how to enable "muxer" scenario to have signed binary and standalone scenarios do not run into issues with signing.

CC @piotrpMSFT @joshfree @leecow @ericstj

**Comment by schellap** [comment]
Blocked by https://github.com/dotnet/core-setup/issues/215 and https://github.com/dotnet/cli/issues/3850

**Comment by schellap** [comment]
Before signing, we must also prevent loading of all hostfxr.dll that don't do any checks and freely allow standalone loads. This includes hostfxr.dll 1.0.0 upto now.

The way to fix this would be to: make a new hostfxr.dll set a field on `hostfxr_interface_t` called `allow_signed_dotnet` in `hostfxr_load`. This field will be initialized to false by the new dotnet (before signing) when passing the init data to `hostfxr_load`.

When this field is unset, a new signed dotnet.exe will refuse to execute hostfxr_main.

**Comment by schellap** [comment]
@eerhardt, you wouldn't disable `%PATH%\dotnet.exe` activation for
standalone apps as it requires explicit extra arguments like `dotnet
app.dll`.

**Comment by gkhanna79** [comment]
@schellap Thank you for chiming in. As long as we disable 2.0 dotnet.exe to not support standalone apps explicitly, is there a reason we would need the approach you outlined above? Essentially:

1) For portable scenarios, 2.0 dotnet will load 1.X hostfxr and that will work.
2) For standalone apps using 2.0 FX, apphost will be used and 2.0 dotnet.exe, even if copied, will not work.
3) For standalone apps using 1.X FX, they will still be published using 1.X SDK that will copy corhost.exe from the SDK, as app.exe, and thus, will work.

@eerhardt @ramarag can chime in if my understanding of the design is off here.

Reopening this to ensure we track the closure properly.
