### ISSUE TITLE
Do not copy hostpolicy built afresh into SharedFX

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#1740]
See https://github.com/dotnet/core-setup/blob/master/build_projects/shared-build-targets-utils/Utils/SharedFrameworkPublisher.cs#L238-L242

This does not seem correct as there is nothing special about hostpolicy being in SharedFX anymore than any other binary that is part of it.

CC @eerhardt @ramarag @ellismg

**Comment by eerhardt** [comment]
Just an FYI - that comment came when we "Locked down the Muxer":

https://github.com/dotnet/cli/commit/62eda6c2d7fb398986fff98093e887d7ce6e13e3#diff-0318e14ec884b5700c20aa3e06d856ceR564

This came in on this PR: https://github.com/dotnet/cli/pull/2636

**Comment by gkhanna79** [comment]
I have thought about this more - this only applies to servicing scenarios and, conservatively, it is fine to do it there. 

I will close this issue.
