### ISSUE TITLE
Should we rename Microsoft.NetCore.App to avoid the problem that Mac's think its a package?

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#1749]
I've gotten feedback a few times now that people wish this weren't the case. Renaming has impact. I thought I'd at least file the issue and we can discuss the merits one way or the other.

**Comment by ericstj** [comment]
This isn't actionable.  Its a question and I don't own that decision.

**Comment by terrajobst** [comment]
I don't think we should rename the package; as you said: it's expensive and potentially far reaching.

@Petermarcu, what falls apart when the Mac treat the folder for this package as an application? In the end, we don't expect customers to see or interact with that folder at all.

**Comment by gkhanna79** [comment]
@Petermarcu I am moving this out to Future. Please close if this is not actionable.

**Comment by Petermarcu** [comment]
I think I agree that we have to leave it alone. If we could start over, we would have chosen a different name :(
