### ISSUE TITLE
dockerrun.sh explicit pre-build image pull uses wrong path: doesn't append /Dockerfile

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#1757]
When building using a dockerfile, for example:

    build.sh --skip-prereqs --configuration Release --docker ubuntu.14.04 --targets Default

The build emits this in the logs:

    grep: scripts/docker/fedora.23: Is a directory

[dockerrun.sh#L118](https://github.com/dotnet/core-setup/blob/19829e68d80a6ca249d230a09f7da8a90c0fb60d/scripts/dockerrun.sh#L118) should be trying to grep `scripts/docker/fedora.23/Dockerfile`. The `DOCKERFILE` variable is set to the directory, rather than the Dockerfile itself.

@ravimeda @MichaelSimons

**Comment by MichaelSimons** [comment]
@ravimeda - Is this issue fixed?  Can it be closed?

**Comment by ravimeda** [comment]
Yes, PRs are as follows -

- Master  https://github.com/dotnet/core-setup/pull/1759
- 1.1.0  https://github.com/dotnet/core-setup/pull/1769
- 1.0.0  https://github.com/dotnet/core-setup/pull/1767
