### ISSUE TITLE
Need to bump Microsoft.NETCore.App version in master

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#176]
The 'master' branch currently has Microsoft.NETCore.App versioned as "1.0.0-rc4", but we've already released "1.0.0".

We need to bump the first 3 digits to be higher than "1.0.0".

**Comment by weshaggard** [comment]
@ericstj I assume this is in your list of version bumps you are working on but if not and you need assistance I can pick-up this work.

**Comment by ericstj** [comment]
Could you pick up core-setup?  I'm going to do CoreFx, WCF, and TFS.

**Comment by weshaggard** [comment]
Yes I will pick it up.

**Comment by weshaggard** [comment]
Yes this was already done.
