### ISSUE TITLE
Muxer will invoke an SDK versioned "-1.-1.-1"

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/core-setup#1760]
## Steps to reproduce
mkdir -p sdk/-1.-1.-1/
touch sdk/-1.-1.-1/dotnet.dll
dotnet --version

## Expected  behavior
It should ignore the "-1.-1.-1" file. This is a placeholder version

## Actual behavior
It attempts to use sdk/-1.-1.-1/dotnet.dll.

## Environment data
Using dotnet 2.0.0-beta-001747-00

**Comment by gkhanna79** [comment]
@livarcocc @johnbeisner Is this being fixed for 2.0?
