### ISSUE TITLE
Installing packages appends many times to /etc/paths.d/dotnet

### ISSUE THREAD

**Issue by vcsjones** [dotnet/core-setup#18]
## Steps to reproduce

Run the .pkg for the SDK installer multiple times. Can be the same version, can be different ones.

## Expected  behavior

The `/etc/paths.d/dotnet` file contains a single line to the path of where the CLI tools are run.

## Actual behavior

Every time the package installer is run, another path line is added:

```
/usr/local/share/dotnet
/usr/local/share/dotnet
/usr/local/share/dotnet
/usr/local/share/dotnet
/usr/local/share/dotnet
/usr/local/share/dotnet
/usr/local/share/dotnet
/usr/local/share/dotnet
/usr/local/share/dotnet
..etc
```

I only discovered this because it looks like at some point, the path was once `/usr/local/share/dotnet/bin`, which was getting added to my path and causing problems.

## Environment data
`dotnet --info` output:

>.NET Command Line Tools (1.0.0-preview1-002700)
>
>Product Information:
> Version:     1.0.0-preview1-002700
> Commit Sha:  0336f6bb34

>Runtime Environment:
> OS Name:     Mac OS X
> OS Version:  10.11
> OS Platform: Darwin
> RID:         osx.10.11-x64

**Comment by vcsjones** [comment]
The culprit is this line, [here](https://github.com/dotnet/core-setup/blob/1db6c07638a70a621b312e78d4dc9fb31a530f2f/packaging/osx/sharedhost/scripts/postinstall#L14):

```shell
echo $INSTALL_DESTINATION | tee -a /etc/paths.d/dotnet
```

This echoes the path into the file as many times as it runs without checking if it exists.

I would propose just making this a straight overwrite:

```shell
echo $INSTALL_DESTINATION > tee -a /etc/paths.d/dotnet
```

If more paths need to be added later, it could be done as such:

```shell
echo $INSTALL_DESTINATION > /etc/paths.d/dotnet
echo $OTHERPATH >> /etc/paths.d/dotnet
```
Or us a separate file from `dotnet` entirely.

**Comment by blackdwarf** [comment]
`tee` already solves this, and its default is to actually overwrite, so just removing the `-a` fixes the thing. :)

**Comment by vcsjones** [comment]
@blackdwarf any particular reason to use `tee`? Does the path need to be printed to standard out?

**Comment by blackdwarf** [comment]
@vcsjones I believe I had problems with standard redirection under sudo to `/etc/` path.
