### ISSUE TITLE
HTTP 400 "The specified block list is invalid." when publishing to blob storage

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#1824]
In the official build, we sometimes get a 400 error when trying to publish artifacts onto Azure blob storage. https://devdiv.visualstudio.com/DevDiv/_build?buildId=631398:

```
<RequestResult>
  <HTTPStatusCode>400</HTTPStatusCode>
  <HttpStatusMessage>The specified block list is invalid.</HttpStatusMessage>
  [...]
  <Error>
    <Code>InvalidBlockList</Code>
    <Message>The specified block list is invalid.
```

```
...
at System.Threading.Tasks.Task.Wait()
at Microsoft.DotNet.Cli.Build.AzurePublisher.PublishFile(String blob, String file)
at Microsoft.DotNet.Host.Build.PublishTargets.PublishCoreHostPackages(BuildTargetContext c)
at Microsoft.DotNet.Cli.Build.Framework.BuildContext.ExecTarget(BuildTarget target)
```

---

Approaches:

 1. Remove our parallel overwrites: https://github.com/dotnet/core-setup/issues/1994.
 2. Catch and ignore this specific exception.
 3. Use more semaphores to avoid concurrent writes.

**Comment by markwilkie** [comment]
Do you know if there’s an issue tracking retries (or other hardening) for this Davis?

**Comment by dagood** [comment]
There isn't, but it sounds reasonable to fix this that way because it seems pretty random. This issue could track it, since it's specific to the core-setup build system.

**Comment by dagood** [comment]
@MattGal pointed out that Core-Setup is using a very old version of `WindowsAzure.Storage`, `6.2.2-preview` (Dec 2015). Latest: `8.1.1` (Feb 2017). We should try updating it.

**Comment by dagood** [comment]
The first build with https://github.com/dotnet/core-setup/pull/1935 merged worked. I'm going to proactively close this, in case this issue never repros.

**Comment by dagood** [comment]
https://github.com/dotnet/core-setup/issues/1994 is the underlying problem, but I think we can safely ignore this exception: it indicates that some other build successfully copied the same file, so the publish that encountered the error was unnecessary in the first place.

**Comment by dagood** [comment]
To make sure "2. Catch and ignore this specific exception." is a valid solution I checked two of the repros we've had to make sure the files weren't corrupted by the conflict. They weren't. I also wasn't able to find any web search results for `corrupt The specified block list is invalid` or anything similar.

**Comment by eerhardt** [comment]
Closed by https://github.com/dotnet/core-setup/pull/2153.
