### ISSUE TITLE
The "latest" folder in Azure for core-setup doesn't contain the exact artifacts as "1.0.0"

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#183]
Download https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/Latest/dotnet-debian-x64.latest.tar.gz

Download https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0/dotnet-debian-x64.1.0.0.tar.gz

Compare byte-for-byte, these two artifacts should be the same.

I think the issue is because "FinalizeBuild" gets confused because we've run multiple builds on the same build number, and it didn't update "latest" for this last build.

@brthor @piotrpMSFT @mellinoe

**Comment by eerhardt** [comment]
We should be able to fix this in Azure, no code changes needed and no need to run a new build.

**Comment by brthor** [comment]
These two artifacts should be the same, but FinalizeBuild is now based on a commit hash:
https://github.com/dotnet/core-setup/issues/169

More important, are the myget bits getting updated

**Comment by piotrpMSFT** [comment]
for `1.0.0-rtm` we will fix this offline

**Comment by piotrpMSFT** [comment]
Fixed.
