### ISSUE TITLE
Remove the VC Redist

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#1842]
As soon as the runtime is carrying the uCRT with it, we need to merge this change into master: https://github.com/Petermarcu/core-setup/commit/340ab6690d36610c6ca0c49deb64cc2da889ba5f

**Comment by Petermarcu** [comment]
@gkhanna79 - FYI

**Comment by gkhanna79** [comment]
This has been fixed in CoreCLR and @wtgodbe is cleaning up Core-Setup for VCRedist.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/core-setup/pull/1963 resolves
