### ISSUE TITLE
Remove version info from apphost.exe

### ISSUE THREAD

**Issue by ramarag** [dotnet/core-setup#1871]
cc @gkhanna79 @eerhardt

**Comment by gkhanna79** [comment]
We should also add an explicit resource (on Windows) that carries the original filename and explicitly set major/minor versions that can be updated when the shared host (i.e. dotnet.exe) is updated.

**Comment by gkhanna79** [comment]
@ramarag Are we using this as a tracker inspite of your comment at https://github.com/dotnet/core-setup/pull/2090#issuecomment-297218769?
