### ISSUE TITLE
runtime.RID.Microsoft.NETCore.App packages contain all the symbols

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#1884]
## Steps to reproduce
Look at the latest package on https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.opensuse.42.1-x64.Microsoft.NETCore.App

## Expected  behavior
It should be a reasonable size.

## Actual behavior
It is 90MB, since it contains all the symbol files.

/cc @ericstj @gkhanna79 @chcosta

**Comment by chcosta** [comment]
I'd imagine that it's expanding the transport packages from CoreFx and then just repackaging everything into the Microsoft.NETCore.App runtime package.  I'll look into adding an exclusion so that it doesn't repackage symbols.

**Comment by eerhardt** [comment]
FYI - this issue is blocking the CLI tests on the new runtime.  See https://github.com/dotnet/cli/pull/6181#issuecomment-290251792.  It breaks the `dotnet cache` command.

**Comment by eerhardt** [comment]
This is not fixed with build `2.0.0-preview1-001875-00.

https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.win7-x64.Microsoft.NETCore.App/2.0.0-preview1-001875-00

It is still 64MB, and opening the package up, I see symbols:

![image](https://cloud.githubusercontent.com/assets/8291187/24532343/6a2dd456-1585-11e7-8002-d5b4807a163c.png)

This is still blocking the CLI from taking a new runtime, because it is breaking the `dotnet cache` feature.

**Comment by chcosta** [comment]
I don't know why I didn't get a notification about your post @eerhardt , but I just checked the feed and found the same thing.  I'm investigating.

**Comment by chcosta** [comment]
A couple of strange things.  It looks like my change did fix the package.  We are now producing an 18 MB runtime.win7-x64.Microsoft.NETCore.App package without symbols (`.nupkg`),, and a 64 MB symbols package (`.symbols.nupkg`).  If I look at our internal storage, I can confirm that these are both present.  On MyGet, it appears that the package listed is the symbols package.  On the MyGet feed, we used to be able to see both the standard package and the symbols package, but I no longer see symbols packages listed there.

**Comment by chcosta** [comment]
@ericstj informed me that symbols packages need to be pushed to a different feed, myget doesn't distinguish based on filename.  I'm looking at enabling this.

**Comment by chcosta** [comment]
Fixed with version `2.0.0-preview1-001887-00` and later.

**Comment by eerhardt** [comment]
Confirmed this fixed it. Thanks @chcosta !
