### ISSUE TITLE
Add package installers

### ISSUE THREAD

**Issue by ericstj** [dotnet/core-setup#189]
We need to produce the following in the core-setup repo:
~~1. WixLib for machine wide package folder / fallback packages folder.~~
~~2. MSI for UWP packages~~
3. MSI for .NET core packages.

/cc @MichaelSimons @jhendrixMSFT

**Comment by gkhanna79** [comment]
@ericstj Is this required for 1.1.0? Does not seem like that but want to confirm.

**Comment by jhendrixMSFT** [comment]
@ericstj FYI I'm no longer on the .NET team, can you work with Mark to find the correct owner for this work item?

**Comment by gkhanna79** [comment]
@markwilkie Assigned to you per Joel's comment.

@ericstj What is outstanding here and does that block 1.1.0?

**Comment by gkhanna79** [comment]
@markwilkie Since I have not heard back from you on this, I am moving this out to 1.2.0 as I dont see it blocking 1.1.0.

**Comment by eerhardt** [comment]
Are we going to bump this issue out of 2.0, like we did for 1.1 and 1.2?

**Comment by ericstj** [comment]
Some of this has changed.  1 and 2 are actually done but it was decided to not do it in core-setup but in VS, so that it can be closer in-sync with the templates.
I think 3 is also being done upstack, not sure if there is any desire to move it down.  By the same logic that moved 1 and 2 closer to VS/templates I think 3 should also be closer to VS.  /cc @livarcocc @joeloff

**Comment by joeloff** [comment]
@ericstj These are for the feed/fallback installers, correct? We have a subset of the .NET Core packages in ASP.NET (we agreed to carry them back in 1.0 RC timeframe), not the full set, only what satisfies our closure to support web templates.

**Comment by ericstj** [comment]
Who's building out the VS package with the .NET Core templates?

**Comment by joeloff** [comment]
@srivatsn @jinujoseph might know.

**Comment by ericstj** [comment]
Yep, @jinujoseph picked up 1 & 2.  It probably makes sense to build 3 in the same way.

**Comment by gkhanna79** [comment]
@ericstj Is this actionable in Core-Setup (we are already producing all the installers) or should it be moved to a different repo if it is tracking something else?

**Comment by ericstj** [comment]
I believe it needs to go upstack if still necessary.  I'm pretty sure its on the radar for CLI, but I'll open an issue to be sure.

**Comment by ericstj** [comment]
Opened: https://github.com/dotnet/cli/issues/6636
