### ISSUE TITLE
RID calculation in CoreHost is broken 

### ISSUE THREAD

**Issue by davidfowl** [dotnet/core-setup#1903]
On a debian linux I see the following when enabling `COREHOST_TRACE=1`:

```
HostRID is 8debian.-x64
Falling back to base HostRID: linux-x64
```

Meanwhile dotnet --info shows this:

```
Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
```

This causes RID fallback to fail when the assets don't exactly match the target RID. I ran into this because we moved libuv out of the shared framework (which is the reason we never hit this before). 

## Repro steps

1. Get a machine with docker
2. `docker run -it --rm microsoft/dotnet-nightly:2.0.0-beta-sdk`
3. Run `dotnet --info` confirm the RID is `debian.8-x64`
4. Now make a new console application using `mkdir app && cd app && dotnet new console`
5. Run `dotnet restore && dotnet build`
6. Set COREHOST_TRACE via `export COREHOST_TRACE=1`
7. Run the applicaion and pipe strerr to a file `dotnet bin/Debug/netcoreapp2.0/app.dll 2> out.txt`
8. Execute `cat out.txt | grep HostRID`

## Expected

```
cat out.txt | grep HostRID
HostRID is debian.8-x64
```

## Actual

```
cat out.txt | grep HostRID
HostRID is 8debian.-x64
Falling back to base HostRID: linux-x64
```

/cc @gkhanna79

**Comment by davidfowl** [comment]
This code:

https://github.com/dotnet/core-setup/blob/37849adf87d8eb8c1e4f3fb7b81ac2079ec6950b/src/corehost/common/pal.unix.cpp#L361-L373

seems to assume that the ID will always appear before the VERSION_ID fields in `/etc/os-release`. Here's what that looks like in the container:

```
root@5714f0073f33:/app# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by Petermarcu** [comment]
@gkhanna79, do we have tests that run on different OS's to ensure we have coverage here?

**Comment by gkhanna79** [comment]
We runs tests on all the OS that we support in CI @Petermarcu. Also, this came to light within Docker that is not necessarily the environment in which builds and tests are always run.

**Comment by davidfowl** [comment]
unit tests would be sufficient for this sort of code...
