### ISSUE TITLE
Host should not pass App_Paths and App_Ni_Paths

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#193]
In RC2, the host used to load everything from the app-local unconditionally, which we fixed to load only the assemblies specified in app.deps.json.

However, the host continues to pass app_paths and app_ni_paths to the runtime (https://github.com/dotnet/core-setup/blob/22c97b59b6442eb3454c9a1407b6de91ca11eaa2/src/corehost/cli/hostpolicy.cpp#L70). This means if the application carried additional assemblies, which are not in app.deps.json, then they can get loaded in DefaultContext since the paths are specified while, infact, managed code should be using various Load* methods of AssemblyLoadContext to load such assemblies since only the TPA list corresponds to the "probe" locations for DefaultContext.

CC @jkotas

**Comment by schellap** [comment]
**Note** when fixing this issue, provide adequate compat switches...
