### ISSUE TITLE
Cross-Arch targeting crossgen should not come from AnyCPU location

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#1960]
See https://github.com/dotnet/coreclr/issues/9884#issuecomment-291897875 for details.

CC @ericstj

**Comment by chcosta** [comment]
Fixed with https://github.com/dotnet/core-setup/pull/2244

**Comment by ericstj** [comment]
To fix this we need https://github.com/dotnet/coreclr/issues/9884
