### ISSUE TITLE
dotnet.exe should not be appending the shared framework to the %PATH%

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#1974]
See https://github.com/dotnet/core-setup/issues/1961 for original issue.

## Steps to reproduce
`dotnet run` this:

```C#
        static void Main(string[] args)
        {
            Console.WriteLine(System.Environment.GetEnvironmentVariable("PATH"));
        }
```

## Expected  behavior
The output should match what `echo %PATH%` outputs from the command line where you called `dotnet run`

## Actual behavior
The output has the shared framework appended (twice if you are running on .net core and once if you are using desktop), which doesn't appear in `echo %PATH%`.

## Notes
This happens because of this code:
https://github.com/dotnet/core-setup/blob/d9b42f8cf23a69509d956230ef7fac4c8c0cdc72/src/corehost/common/pal.windows.cpp#L48-L66

/cc @gkhanna79 @ramarag

**Comment by gkhanna79** [comment]
APISets are no longer needed, so this code (and supporting PAL APIs) should all be deleted.
