### ISSUE TITLE
.Net Core 1.0.4 mislabeled 1.0.3

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#1975]
_From @Mattacks on April 6, 2017 12:53_

## Steps to reproduce
Download .Net Core 1.0.4 from main landing page
Install
Accept EULA

## Expected  behavior
UAC control dialog pops up - says it is 1.0.4

## Actual behavior
UAC control dialog pops up - says it is 1.0.3

_Copied from original issue: dotnet/cli#6260_

**Comment by livarcocc** [comment]
Can you provide a link to what you are downloading and installing? I mean, is it  a link to the 1.0.1 SDK or to the 1.0.4 shared framework?

**Comment by livarcocc** [comment]
_From @Mattacks on April 6, 2017 18:44_

It's from here https://www.microsoft.com/net/download/core#/runtime
NET Core 1.0.4 runtime (LTS)
Windows (x64) Installer
.exe download
Copy of download link: https://go.microsoft.com/fwlink/?linkid=843412

If you choose to run as administrator you see the error straight away

**Comment by gkhanna79** [comment]
@rakeshsinghranchi Can you please see if this is applicable to 1.0.5 as well? If so, can we get a fix for it? 

Likwise for 1.1.x and 2.0.0 as well.

**Comment by rakeshsinghranchi** [comment]
Issue doesn't repro any more on 1.0.5 or 1.1.2 or 2.0.0 . Issue occurred in 1.0.4 because in-correct value set for ProductMoniker variable. Moving to new build definition and signing microbuild has resolved the issue.
