### ISSUE TITLE
Windows installer common error codes from corruption

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#1984]
There used to be a list we had that listed common error codes and what to do about them. I dont recall if the burn engine baked a lot of these in but in previous installers, we had implemented retry logic, "fixups", and failure to success mappings. We should try to track that list down and see if it is applicable to our MSI's.

**Comment by Petermarcu** [comment]
@rakeshsinghranchi @robmen

**Comment by rakeshsinghranchi** [comment]
Things to be done here:
1. Determine if Burn supports retry logic
2. Determine the specific set of error codes that are applicable to our MSIs.
3. Implement in burn bundles for .NET Core.

Copied from .NET Desktop setup chainer:

     <CustomError ReturnCode="1603" MSIErrorMessage="1310">
          <Retry Delay="1" Limit="1">
            <ItemRef Name="SetupUtility.exe" />
          </Retry>
        </CustomError>
        <CustomError ReturnCode="1603" MSIErrorMessage="1311">
          <Retry Delay="1" Limit="1">
            <ItemRef Name="SetupUtility.exe" />
          </Retry>
        </CustomError>
        <CustomError ReturnCode="1603" MSIErrorMessage="1312">
          <Retry Delay="1" Limit="1">
            <ItemRef Name="SetupUtility.exe" />
          </Retry>
        </CustomError>
        <CustomError ReturnCode="1603" MSIErrorMessage="1316">
          <Retry Delay="1" Limit="1">
            <ItemRef Name="SetupUtility.exe" />
          </Retry>
        </CustomError>
        <CustomError ReturnCode="1603" MSIErrorMessage="1317">
          <Retry Delay="1" Limit="1">
            <ItemRef Name="SetupUtility.exe" />
          </Retry>
        </CustomError>
        <CustomError ReturnCode="1603" MSIErrorMessage="1321">
          <Retry Delay="1" Limit="1">
            <ItemRef Name="SetupUtility.exe" />
          </Retry>
        </CustomError>
        <CustomError ReturnCode="1603" MSIErrorMessage="1335">
          <Retry Delay="1" Limit="1">
            <ItemRef Name="SetupUtility.exe" />
          </Retry>
        </CustomError>
        <CustomError ReturnCode="1603" MSIErrorMessage="1402">
          <Retry Delay="1" Limit="1">
            <ItemRef Name="SetupUtility.exe" />
          </Retry>
        </CustomError>
        <CustomError ReturnCode="1603" MSIErrorMessage="1406">
          <Retry Delay="1" Limit="1">
            <ItemRef Name="SetupUtility.exe" />
          </Retry>
        </CustomError>
        <CustomError ReturnCode="1603" MSIErrorMessage="1606">
          <Retry Delay="1" Limit="1">
            <ItemRef Name="SetupUtility.exe" />
          </Retry>
        </CustomError>
        <CustomError ReturnCode="1603" MSIErrorMessage="1706">
          <Retry Delay="1" Limit="1">
            <ItemRef Name="SetupUtility.exe" />
          </Retry>
        </CustomError>
        <CustomError ReturnCode="1603" MSIErrorMessage="1719">
          <Retry Delay="1" Limit="1">
            <ItemRef Name="SetupUtility.exe" />
          </Retry>
        </CustomError>
        <CustomError ReturnCode="1603" MSIErrorMessage="1723">
          <Retry Delay="1" Limit="1">
            <ItemRef Name="SetupUtility.exe" />
          </Retry>
        </CustomError>
        <CustomError ReturnCode="1603" MSIErrorMessage="1923">
          <Retry Delay="1" Limit="1">
            <ItemRef Name="SetupUtility.exe" />
          </Retry>
        </CustomError>
        <CustomError ReturnCode="1603" MSIErrorMessage="1931">
          <Retry Delay="1" Limit="1">
            <ItemRef Name="SetupUtility.exe" />
          </Retry>
        </CustomError>
        <CustomError ReturnCode="1603" MSIErrorMessage="2203">
          <Retry Delay="1" Limit="1" />
        </CustomError>
        <CustomError ReturnCode="1603" MSIErrorMessage="2329">
          <Retry Delay="1" Limit="1" />
        </CustomError>

**Comment by Petermarcu** [comment]
Thanks, isn't there another set that was a list of return codes that should be treated as success?

**Comment by robmen** [comment]
There is retry logic supported in Burn. There is a library that tried to capture the knowledge of the time in https://github.com/wixtoolset/wix3/blob/develop/src/libs/balutil/balretry.cpp. That mechanism does not allow running an elevated "fix it" utility but we were interested in adding any "fix its" to the engine directly.

**Comment by Petermarcu** [comment]
Thanks!

**Comment by dagood** [comment]
(Triage): This has changed a lot, and we don't think this will add significant value. Closing for now.
