### ISSUE TITLE
Include ASP.NET's target manifests and runtime package store in setup

### ISSUE THREAD

**Issue by bleroy** [dotnet/core-setup#1993]
This work item is about integrating the output from [ASP.NET/coherence-signed#428](https://github.com/aspnet/Coherence-Signed/issues/428) into the .NET Core setup.

**Comment by Petermarcu** [comment]
This should go in the cli repo as it will be part of the ask, not the core runtime.

**Comment by bleroy** [comment]
Yes, I think this is [CLI#5505: Add ASP.NET "2.0" packages to offline cache when they are available](https://github.com/dotnet/cli/issues/5505)
