### ISSUE TITLE
Add Unsupported Blocker to Runtime Bundle ( Windows Platform only )

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#2016]
@gmeena commented on [Sun Apr 09 2017](https://github.com/dotnet/coreclr/issues/10832)

hosting machine, window server 2008, IIS 7
running dotner --help giving this error. attached in image
![dotnetcore error](https://cloud.githubusercontent.com/assets/8595001/24836743/f46c375c-1d41-11e7-9f52-54a2fe022018.jpg)

After so much googling could not able to find solution so posting here. same is working in local machine.
I guess everything required already installed 
![core soft](https://cloud.githubusercontent.com/assets/8595001/24836843/5f2a1814-1d44-11e7-80c0-16f7c401a023.jpg)
![dotnetcore error](https://cloud.githubusercontent.com/assets/8595001/24851302/c4328cd0-1df0-11e7-80d6-b7e59f0158ff.jpg)

---

@mikedn commented on [Mon Apr 10 2017](https://github.com/dotnet/coreclr/issues/10832#issuecomment-292871669)

Window Server 2008 or Windows Server 2008 R2?

I don't see Window Server 2008 listed in the [Prerequisites](https://docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites) doc.

---

@gmeena commented on [Mon Apr 10 2017](https://github.com/dotnet/coreclr/issues/10832#issuecomment-292874020)

please see updated description with one more screen shot

---

@mikedn commented on [Mon Apr 10 2017](https://github.com/dotnet/coreclr/issues/10832#issuecomment-292879390)

So it is Windows Server 2008, not 2008 R2. It's unfortunate that the installer doesn't block install on 2008 but the documentation doesn't include 2008 as a supported OS.

---

@gmeena commented on [Mon Apr 10 2017](https://github.com/dotnet/coreclr/issues/10832#issuecomment-292883072)

So it will not work on 2008 WS.

---

@jkotas commented on [Mon Apr 10 2017](https://github.com/dotnet/coreclr/issues/10832#issuecomment-293026089)

cc @gkhanna79

**Comment by gkhanna79** [comment]
@rakeshsinghranchi Can you please look into adding such detection for our installers for 2.0? Once that is done, we should look into doing so for future 1.0.x and 1.1.x as well.

**Comment by rakeshsinghranchi** [comment]
Fix is in 1.0.x,1.1.x and 2.0.0 . Closing this now.
