### ISSUE TITLE
Multi level lookup for SDK

### ISSUE THREAD

**Issue by davidfowl** [dotnet/core-setup#2025]
I was just looking at this document to see if we can take advantage of this in our builds (ASP.NET Core and others):

https://github.com/dotnet/core-setup/blob/c0aac4d98d3af034d8b9f8ca54ed49ec766db320/Documentation/design-docs/multilevel-sharedfx-lookup.md

I was looking to see if we could use the user location for the dotnet hive and I noticed there's no mention of the SDK here. The goal of the multi level lookup was to relocate the entire dotnet hive, not just the shared runtime. 

Here's the scenario, today when you build any ASP.NET Core project, we install a custom dotnet hive into `%localappdata%\Micrososft\dotnet` which is a location that is unknown to the muxer. We then generate a `global.json` that specifies the correct version of the SDK that the everything should use. Today, we have to ask all developers and contributors to change their PATH environment variable to make sure that visual studio picks up the right shared runtime (and in the future, the right SDK).

We have this for the shared framework, can we get it for the SDK as well?

**Comment by eerhardt** [comment]
The lookup works for the SDK as well, but there are bugs in the feature.  For example, see https://github.com/dotnet/cli/issues/6298.

Closing as the lookup works as expected.  

Note: the location under `%USERPROFILE%` is:

![image](https://cloud.githubusercontent.com/assets/8291187/24963916/85bab52e-1f65-11e7-9222-c8287757e2a1.png)
