### ISSUE TITLE
Consume prebuilt images from dockerhub registry than building during pipeline build

### ISSUE THREAD

**Issue by rakeshsinghranchi** [dotnet/core-setup#2031]
As of today, docker images are built on the fly during the pipeline build. @gkhanna79  suggested to consume the pre-build docker images from dockerhub registry . This involves pushing all required docker images to dockerhub.

**Comment by gkhanna79** [comment]
CC @MichaelSimons

**Comment by MichaelSimons** [comment]
This is a dup of https://github.com/dotnet/core-setup/issues/1719

**Comment by gkhanna79** [comment]
Closing since it is a dup.
