### ISSUE TITLE
How to identify when a change in corefx/coreclr is available in core-setup

### ISSUE THREAD

**Issue by omajid** [dotnet/core-setup#2033]
I am trying to trace how features go from corefx and coreclr to core-setup (and from core-setup into cli). I see that various PRs (such as https://github.com/dotnet/core-setup/pull/1957) for updating the version of coreclr/corefx in core-setup refer to version strings like "2.0.0-preview1-25205-03". Is there some way to find out which commit/tag these version strings correspond to?

Is there some other way to identify when a fix/change made in corefx/coreclr has made it into core-setup (or a change in core-setup has made it into cli)?

/cc @gkhanna79 @weshaggard based on suggestion from @karelz

**Comment by gkhanna79** [comment]
@ellismg @joperezr What was the command that could be used to get commit SHA out of the binaries we build?

**Comment by joperezr** [comment]
`git rev-parse HEAD`

**Comment by gkhanna79** [comment]
I was asking about the SHA your versioning change embedded within the binaries @joperezr

**Comment by joperezr** [comment]
Oh, you can find that information here: https://github.com/dotnet/corefx/blob/master/Documentation/building/versioning.md#getting-the-version-of-a-native-binary-in-non-windows-platforms

Assuming you are asking for a non-Windows native binary, you call: `strings myNativeNonWindowsBinary.so | grep "@(#)"`
For every other case (IL assembly or Windows native assembly) just right click the assembly -> properties -> Details -> Product Version

**Comment by ellismg** [comment]
It may be obvious but strings also works on IL (and I would assume native windows PE files):

```
matell@matell-ub:~/bin/shared/Microsoft.NETCore.App/1.1.0$ pwd
/home/matell/bin/shared/Microsoft.NETCore.App/1.1.0
matell@matell-ub:~/bin/shared/Microsoft.NETCore.App/1.1.0$ strings System.Globalization.dll | grep "[a-f0-9]\{20\}"
C4.6.24705.01. Commit Hash: 4d1af962ca0fede10beb01d197367c2f90e92c97
```

It helps to filter things such that you only pull out things that look like SHA1 hashes, as I do above with the grep pattern.

**Comment by karelz** [comment]
@wtgodbe are there easy steps, documented how to get the info?
