### ISSUE TITLE
Wrong symlinkEntrypointExecutable define for FreeBSD

### ISSUE THREAD

**Issue by sec** [dotnet/core-setup#204]
Defined in - src/corehost/common/pal.unix.cpp
Under FreeBSD this should be - /proc/curproc/file

The same is for CoreCLR - https://github.com/dotnet/coreclr/issues/6184

**Comment by gkhanna79** [comment]
CC @janvorli

**Comment by janvorli** [comment]
We should not be using procfs on FreeBSD, since it is not turned on by default. We should rather follow the NetBSD way and use the sysctl with KERN_PROC_PATHNAME.
NetBSD build falls back to procfs if the KERN_PROC_PATHNAME is not defined, but I don't know if that's necessary for FreeBSD too.

**Comment by josteink** [comment]
This was actually fixed in the following PR and is now merged to master:

https://github.com/dotnet/core-setup/pull/213

I suggest closing this issue.
