### ISSUE TITLE
Update cli code to reflect the new inteface of coreclr

### ISSUE THREAD

**Issue by mazong1123** [dotnet/core-setup#2050]
## Steps to reproduce
Based on the discuss of [this PR](https://github.com/dotnet/coreclr/pull/10842#issuecomment-293623966), we need to update https://github.com/dotnet/core-setup/blob/master/src/corehost/cli/coreclr.cpp to reflect the changes. Otherwise the nuget would not be aware of the new interface.

## Expected  behavior
New interface can be awared by the nuget.

**Comment by jkotas** [comment]
@gkhanna79 Is https://github.com/dotnet/core-setup/blob/master/src/corehost/cli/coreclr.cpp used with latest CoreCLR only, or does the change need to be done as light up (use the old method if the new one is not there) so that it works on older runtimes too?

**Comment by gkhanna79** [comment]
Yes, that file is used with the latest M.N.App only (see https://github.com/dotnet/core-setup/blob/master/src/corehost/cli/hostpolicy.cpp#L146 where the bind to CoreCLR happens) which is used only by hostpolicy.dll (https://github.com/dotnet/core-setup/blob/master/src/corehost/cli/dll/CMakeLists.txt#L40) that is part of the latest sharedFX.

**Comment by gkhanna79** [comment]
@mazong1123 Please update the file above to correspond to your change as well.

**Comment by gkhanna79** [comment]
CC @ramarag @eerhardt

**Comment by mazong1123** [comment]
@jkotas @gkhanna79 Since [coreclr.cpp](https://github.com/dotnet/core-setup/blob/master/src/corehost/cli/coreclr.cpp) only used by latest CoreCLR based on the comment(https://github.com/dotnet/core-setup/issues/2050#issuecomment-293958400), I guess I can update the signature of [coreclr_shutdown_fn](https://github.com/dotnet/core-setup/blob/master/src/corehost/cli/coreclr.cpp#L22) instead of creating a new `coreclr_shutdown_fn_2`?
