### ISSUE TITLE
Update Microsoft.Net.UWPCoreRuntimeSdk with open CoreCLR artifacts

### ISSUE THREAD

**Issue by zamont** [dotnet/core-setup#2070]
We expect the following artifacts to be built in the open and included in Microsoft.Net.UWPCoreRuntimeSdk:

- UWPShim.exe
- UWPHost.dll
- Microsoft.Net.CoreRuntime Appx FW package

When these are added to Microsoft.Net.UWPCoreRuntimeSdk, we need to do the following

- Port Microsoft.Net.CoreRuntime.targets. This includes updating the paths to the newly included binaries
- Port Microsoft.Net.CoreRuntime.Settings.targets
- Port Microsoft.Build.Net.CoreRuntimeTask.dll
- Port CopyWin32Resources.exe
- Modify build\Microsoft.Net.UWPCoreRuntimeSdk.props to remove `<UseAppLocalCoreCLR>true</UseAppLocalCoreCLR>`
- Modify build\Microsoft.Net.UWPCoreRuntimeSdk.targets to include the Appx FW package in the `<ItemGroup> <AppxPackageRegistration /> </ItemGroup<`

**Comment by gkhanna79** [comment]
@zamont PR https://github.com/dotnet/core-setup/pull/2520 has been merged that generates UWPshim.exe, UWPHost.dll and the appX package. You should now be able to make forward progress on this.

CC @ravimeda @joshfree @danmosemsft

**Comment by danmosemsft** [comment]
@joshfree @karelz as agreed just now, it makes more sense for @zamont to do this.

**Comment by nattress** [comment]
@zamont Is there any remaining work for this issue?  Please close if not

**Comment by zamont** [comment]
Fixed by
 - #2736 
 - #2752 
 - #2772
