### ISSUE TITLE
Win32 exception when using "dotnet run -f netcoreapp2.0" 

### ISSUE THREAD

**Issue by danroth27** [dotnet/core-setup#2130]
## Steps to reproduce
-	Clone https://github.com/aspnet/identityservice
-	build
-	cd samples\WebApplication
-	dotnet run -f netcoreapp2.0

This seems to be a crash in the host itself. This is the command that is causing the crash:

`dotnet exec "E:\git\identityservice\samples\WebApplication\bin\Debug\netcoreapp2.0\WebApplication.dll"`

Also note that if you attach a debugger and hit continue, it will get past the issue and start up the app, which suggests we are hitting some benign assertion somewhere.

## Expected  behavior
Runs

## Actual behavior

![dotnet_win32](https://cloud.githubusercontent.com/assets/1874516/25250074/1004ae38-25c9-11e7-8b8a-1e8212204d6d.jpg)

**Comment by ramarag** [comment]
@danroth27 please give the output of ``dotnet --info``

**Comment by eerhardt** [comment]
Attaching a debugger, I see this callstack:

```
 	KernelBase.dll!DebugBreak() Line 143	C
 	coreclr.dll!Debugger::LaunchDebuggerForUser(Thread * pThread, _EXCEPTION_POINTERS * pExceptionInfo, int useManagedBPForManagedAttach, int explicitUserRequest) Line 6583	C++
 	coreclr.dll!DebugDebugger::Launch() Line 180	C++
 	00007ffc438f08ca()	Unknown
 	coreclr.dll!CallDescrWorkerInternal() Line 101	Unknown
 	coreclr.dll!MethodDescCallSite::CallTargetWorker(const unsigned __int64 * pArguments, unsigned __int64 * pReturnValue, int cbReturnValue) Line 653	C++
 	[Inline Frame] coreclr.dll!MethodDescCallSite::Call(const unsigned __int64 *) Line 433	C++
>	coreclr.dll!RunMain(MethodDesc * pFD, short piRetVal, int * stringArgs, PtrArray * *) Line 1849	C++
 	coreclr.dll!Assembly::ExecuteMainMethod(PtrArray * * stringArgs, int) Line 1944	C++
 	coreclr.dll!CorHost2::ExecuteAssembly(unsigned long dwAppDomainId, const wchar_t * pwzAssemblyPath, int argc, const wchar_t * * argv, unsigned long * pReturnValue) Line 502	C++
 	coreclr.dll!coreclr_execute_assembly(void * hostHandle, unsigned int domainId, int argc, const char * * argv, const char * managedAssemblyPath, unsigned int * exitCode) Line 407	C++
```

Looking at the code: https://github.com/aspnet/IdentityService/blob/25b693cdb40ce35375ed8ef286e7b3e09e2946df/samples/WebApplication/Program.cs#L14

```
        public static void Main(string[] args)
        {
            System.Diagnostics.Debugger.Launch();
            var host = new WebHostBuilder()
```

Seems to be doing what you wanted it to do.

**Comment by danroth27** [comment]
😝
