### ISSUE TITLE
Generate Native (crossgen) PDBs for Profiling for M.N.App

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#2144]
These are required for enabling profiling scenarios. This is for post 5/10.

@eerhardt Can you please file the corresponding issue against @ramarag to enable support for the same in store command as well?

CC @vancem @lt72 @brianrob @Petermarcu

**Comment by eerhardt** [comment]
> @eerhardt Can you please file the corresponding issue against @ramarag to enable support for the same in store command as well?

We already have a work item for it https://github.com/dotnet/sdk/issues/1126.  It is assigned to me and I'm working on it.

**Comment by eerhardt** [comment]
Fixed by #2397.
