### ISSUE TITLE
Update Branding in Mac and Windows Runtime installers

### ISSUE THREAD

**Issue by leecow** [dotnet/core-setup#2155]
**Window title**

* Current: "Install Microsoft .NET Core 2.0.0 - Runtime Preview 1 (x64)"
* Change to: "Microsoft .NET Core 2.0.0 Preview 1 Runtime (x64) Installer"

**Banner**

* Current: "Microsoft .NET Core 2.0.0 - Runtime Preview 1 (x64)"
* Change to: "Microsoft .NET Core 2.0.0 Preview 1 Runtime (x64)"

**Comment by gkhanna79** [comment]
@rakeshsinghranchi @vivmishra Can you PTAL at the earliest into this?

**Comment by rakeshsinghranchi** [comment]
Will take care of this today.

**Comment by rakeshsinghranchi** [comment]
@leecow  , the latest bundle installer branding from master branch ( readme page ) shows the Setup UI as below 
![image](https://cloud.githubusercontent.com/assets/6225949/25361438/eb566ddc-2902-11e7-9203-32e5f7c31694.png)

My assumption is that you picked the package from release/2.0.0 . Please confirm.

Also, what is the package installer path for the issue you mentioned as below ?

Current: "Install Microsoft .NET Core 2.0.0 - Runtime Preview 1 (x64)"
Current: "Microsoft .NET Core 2.0.0 - Runtime Preview 1 (x64)"

**Comment by leecow** [comment]
@rakeshsinghranchi 

Copy/paste error from the SDK installer this comes from whatever branch is populating the daily builds at https://github.com/dotnet/core-setup. 

Updated the post above to account for current Win and Mac differences.

**Comment by gkhanna79** [comment]
Will it be possible to get this change in release/2.0.0 today?

**Comment by rakeshsinghranchi** [comment]
Working on it. Will send the PR soon.Do we want this fix in master branch as well ?

**Comment by gkhanna79** [comment]
Yes, we will want to fix this in master as well.

**Comment by rakeshsinghranchi** [comment]
@leecow 
Current Window title is "Microsoft .NET Core 2.0.0 - Runtime Preview 1 (x64) Setup"
Do you want to replace "Setup" with "Installer" ? 
All burn bundles (.NET Framework setup) have "Setup" in Windows title and is relevant.

Updated Branding string will look as below :
Windows Title will show up as : Microsoft .NET 2.0.0 Preview 1 Runtime (x86) Setup
Banner string : Microsoft .NET 2.0.0 Preview 1 Runtime (x86) 

Please let me know if you still want to change setup to "Installer".

**Comment by rakeshsinghranchi** [comment]
Fix is in release/2.0.0 branch.

**Comment by gkhanna79** [comment]
We should port this to master as well.

**Comment by rakeshsinghranchi** [comment]
@gkhanna79 : I already opened a separate issue : https://github.com/dotnet/core-setup/issues/2216 to track the work for master. Let me know if you are fine with closing this issue.

**Comment by gkhanna79** [comment]
Sounds good.
