### ISSUE TITLE
Flag error when apphost.exe's default hash is not invalidated

### ISSUE THREAD

**Issue by schellap** [dotnet/core-setup#216]
This is about neutering the apphost.exe by default.
## Steps to reproduce

```
dotnet new
# edit to standalone
dotnet restore
dotnet publish
# replace app.exe to use `apphost.exe`
```
## Expected  behavior

The `c3ab8ff13720e8ad9047dd39466b3c8974e592c2fa383d4a3960714caef0c4f2` signature in its resource section should be replaced with another SHA256.

Otherwise the app.dll should not load.
## Actual behavior

Currently, app.dll is loaded even if the hash is not replaced (i.e., the exe is still neutered.)
## Environment data

`dotnet --info` output:

**Comment by schellap** [comment]
https://github.com/dotnet/core-setup/blob/cc564bd08a1f76be06b5d4a9bfc6dc0eb593d613/src/corehost/common/pal.windows.cpp#L348-L349

Change warning to error and return false.

**Comment by gkhanna79** [comment]
Fixed in the associated PR at https://github.com/dotnet/core-setup/pull/711/files#diff-d879441c77c53723780bea5613c6056dR52.
