### ISSUE TITLE
M.N.App Identity package does not have reference to Tizen and ArmEl (Identity?) packages

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#2161]
@weshaggard this is the issue we were looking into on Friday that @eerhardt broughtup. Can you please look into this as we should get this in for Preview1?

CC @ericstj

**Comment by ericstj** [comment]
/cc @Petermarcu 

This shouldn't be a bug.  It's a DCR.  Please provide reasoning for including these along with statement about commitment for support.  That way folks can understand what work is involved.

**Comment by gkhanna79** [comment]
With the work Samsung has been doing, it was always expected that M.N.App Identity package will have a reference to corresponding Armel packages. Samsung's E2E experience will not work if these are missing.

**Comment by gkhanna79** [comment]
Also, https://github.com/dotnet/core-setup/blob/master/pkg/projects/netcoreappRIDs.props#L37 exists but the reference is missing. This is what was identified on Friday - can you please understand why is that?

**Comment by ericstj** [comment]
> the reference is missing

I see, I can help you with that.  

It'd probably be good if a comment was added around that Tizen RID.  It's very unusual for us to emit an arbitrary dangling reference to our build version without producing that package.  Also it might make sense for the version of the tizen package to be authored in some way...

**Comment by ericstj** [comment]
When I build locally I am getting a runtime.json with tizen.  See: https://gist.github.com/ericstj/b0ba7d363c6a9138af7155316a2cf941

It looks like this may be due to the *casing* of OfficialBuildRid in the props file, see 
https://github.com/dotnet/core-setup/blob/671992d3f198082f10820a4075ec421283848359/pkg/projects/netcoreappRIDs.props#L37
Vs
https://github.com/dotnet/core-setup/blob/master/pkg/projects/dir.props#L65

I suspect this is an MSBuild bug that I filed a while back:
https://github.com/Microsoft/msbuild/issues/1751

**Comment by ericstj** [comment]
Confirmed, building with Dev15 msbuild *doesn't repro*.  Build with the MSBuild from the core-setup\pkg\tools folder *does repro*.  Build with latest MSBuild from 2.0 CLI *doesn't repro*.

I can workaround this by fixing up the casing.

**Comment by gkhanna79** [comment]
Thank you @ericstj - this is good to know. Looks like this may not be an issue anymore.

For completeness, @eerhardt, you had mentioned on Friday that you didn't see those references. Was there specific steps that led to it?

**Comment by gkhanna79** [comment]
> I can workaround this by fixing up the casing.

Thank you @ericstj. Can you please get a PR going for master and release/2.0.0 for this?

**Comment by ericstj** [comment]
I'll merge to master.  I'll create a PR for release but you will need to drive getting that in.

**Comment by eerhardt** [comment]
> For completeness, @eerhardt, you had mentioned on Friday that you didn't see those references. Was there specific steps that led to it?

I was removing other RIDs from this list.  See https://github.com/dotnet/core-setup/pull/2146.  When doing that, I was verifying what was actually going into the `runtime.json` file in `Microsoft.NETCore.App` was what we were expecting.  I didn't see these 2 show up in the real packages.
