### ISSUE TITLE
multilevel-sharedfx-lookup.md documents incorrect semver ordering

### ISSUE THREAD

**Issue by poke** [dotnet/core-setup#2169]
Hey, I just read about the [Multi-level SharedFX Lookup](https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/multilevel-sharedfx-lookup.md), when I stumbled across the following part:

> ```
> For instance, a valid Semantic Versioning number sort would be:
> 1.0.0 -> 1.0.1 -> 1.0.1-alpha -> 1.1.0 -> 1.1.1 -> 2.0.0.
> ```

That is incorrect according to Semantic Versioning spec. To quote from [item 9](http://semver.org/#spec-item-9):

> Pre-release versions have a lower precedence than the associated normal version.

In [item 11](http://semver.org/#spec-item-11) there is also an example of how this looks:

> Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

---

So as you can see, according to the specification, `1.0.1-alpha` would go *before* `1.0.1` in the above example. Or the correct version to use in place of that one would be `1.1.0-alpha`.

Is this a deliberate deviation from the semver standard, or is this simply a mistake? Also if it’s a mistake, is it just a documentation error, or is there actually some code in here that enforces this incorrect ordering?

**Comment by gkhanna79** [comment]
I believe this is a documentation mistake - we always prefer the stable over corresponding pre-release.

Do you mind pushing a PR for this?

**Comment by gkhanna79** [comment]
Thanks for catching this.

**Comment by gkhanna79** [comment]
CC @ramarag

**Comment by poke** [comment]
Sure thing, I’ve submitted a PR for this at #2182.
