### ISSUE TITLE
Fix dependency of DotNetHostResolver to resolve to DotNetAppHost

### ISSUE THREAD

**Issue by schellap** [dotnet/core-setup#217]
## Steps to reproduce

dotnet new
dotnet restore
## Expected  behavior

The project.lock.json contains only apphost.exe and not dotnet.exe
## Actual behavior

The project.lock.json contains both the executables
## Environment data

`dotnet --info` output:

Blocked on https://github.com/dotnet/cli/issues/3850

**Comment by schellap** [comment]
Remove https://github.com/dotnet/core-setup/blob/cc564bd08a1f76be06b5d4a9bfc6dc0eb593d613/pkg/projects/Microsoft.NETCore.DotNetHost/Microsoft.NETCore.DotNetHostResolver.pkgproj#L16

**Comment by gkhanna79** [comment]
@ramarag I take it you will use this issue to track the packaging resolution work you are doing, right?

CC @eerhardt @ericstj

**Comment by ramarag** [comment]
will be fixed by https://github.com/dotnet/core-setup/pull/1819
