### ISSUE TITLE
Replace GetWix.ps1 with MSBuild tasks

### ISSUE THREAD

**Issue by chcosta** [dotnet/core-setup#2189]
There's a `src\pkg\packaging\windows\getWix.ps1` powershell script used to obtain the wix tools.  This script appears to be used to download the wix tools and extract them.  This creates a dependency on powershell, also, the extracting part is a dependency on powershell v5.0+.  Jenkins uses powershell v3.x.  I moved the extraction piece into `src\pkg\packaging\package.targets`, but I think this whole ps1 script is unnecessary and could be replaced with MSBuild tasks.

**Comment by gkhanna79** [comment]
@rakeshsinghranchi What are your thoughts on this?

**Comment by eerhardt** [comment]
I don't think this is necessary for 2.0. Does anyone object to moving this to 2.1?

**Comment by rakeshsinghranchi** [comment]
Agreed, moving it to 2.1 .

**Comment by weshaggard** [comment]
@rakeshsinghranchi is this something you plan to do for 2.1 or should it be closed or moved to Future?

**Comment by rakeshsinghranchi** [comment]
Moving to Future

**Comment by dagood** [comment]
Stumbled upon this issue. I happened to do this a while ago, and the WiX acquisition MSBuild code now lives in Microsoft.DotNet.Build.Tasks.SharedFramework.Sdk (Arcade), around [targets/windows/wix.targets](https://github.com/dotnet/arcade/blob/f757dab263c59ffa51717974ec9a5da76a7a3b6e/src/Microsoft.DotNet.Build.Tasks.SharedFramework.Sdk/targets/windows/wix.targets).
