### ISSUE TITLE
Enable portable builds

### ISSUE THREAD

**Issue by chcosta** [dotnet/core-setup#2191]
I wired up the portable builds last night (it was mostly done before the decision to cut over).  The work here is to validate that it's producing properly portable binaries, check the packaging, general cleanup, etc...  I've left the "PortableLinux" leg in the netci.groovy file because it is building clean now.

**Comment by chcosta** [comment]
@eerhardt , can we close this?

**Comment by eerhardt** [comment]
I've checked that we are producing `win-x64, `win-x86`, and `osx-x64` runtime.XXX.Microsoft.NETCore.App packages, which we are.

Also, we are producing `linux-x64` builds, which are working for the CLI on all its platforms: https://github.com/dotnet/cli/pull/6493 (sans the ubuntu deb package issue).

And we are also producing `linux-arm`, `win-arm`, and `win-arm64` builds now as well.

Closing.
