### ISSUE TITLE
Update versions repo during or after finalization

### ISSUE THREAD

**Issue by chcosta** [dotnet/core-setup#2193]
The dotnet/versions repo should be updated after core-setup finalization.  This is a regression from core-setup functionality prior to the buildtools change over.

**Comment by chcosta** [comment]
May be able to reuse this task - https://github.com/dotnet/cli/blob/master/build_projects/dotnet-cli-build/UpdateVersionsRepo.cs

**Comment by karajas** [comment]
This is in now.
