### ISSUE TITLE
Crossgen binaries in flat NETCoreApp package

### ISSUE THREAD

**Issue by chcosta** [dotnet/core-setup#2196]
https://github.com/dotnet/corefx/issues/14595#issuecomment-297149207

This work was started by @ericstj, and needs to be completed in core-setup after the buildtools cut over

**Comment by ericstj** [comment]
I was hoping to get your help with the build infrastructure plumbing.  Do we have a phase where we build native bits and can plug in the crossgen portion of the build, prior to signing, sign, then do the packaging step?

**Comment by chcosta** [comment]
I was hoping to get this done as well, but there are a lot of pieces to validate / complete before the deadline. :(

The native build happens here - https://github.com/dotnet/core-setup/blob/master/src/dir.proj#L16

This happens before signing.  The Windows legs which do signing are still an explosion of steps, just as they previously were - https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=709887

**Comment by ericstj** [comment]
This is a dup of #1550
