### ISSUE TITLE
Infer-runtimes cleanup

### ISSUE THREAD

**Issue by chcosta** [dotnet/core-setup#2198]
There was some work to remove "infer-runtimes" from core-setup builds (it was re-enabled), but that work has likely regressed further after the buildtools change.  

https://github.com/dotnet/core-setup/pull/2059

**Comment by ellismg** [comment]
Since I caused the debt, I'll try to clean this up.

**Comment by eerhardt** [comment]
We are completely off any project.json files now in the repo.  Thus there are no `--infer-runtimes` usages since that is not a valid option with the MSBuild CLI commands.

Closing.
