### ISSUE TITLE
validate signing

### ISSUE THREAD

**Issue by chcosta** [dotnet/core-setup#2199]
Validate signing of all required binaries after core-setup transitions to buildtools

**Comment by chcosta** [comment]
Signtool flagged these failures, this appears to be files which are not authenticode signed.

SignTool Error: No signature found
-	dotnet-hostfxr-win-x86.2.0.0-preview2-25319-02.msi
-	dotnet-hostfxr-win-x64.2.0.0-preview2-25319-02.msi
-	ux\wixstdba.dll
-	dotnet-host-win-x64.2.0.0-preview2-25319-02.ms
-	dotnet-host-win-x86.2.0.0-preview2-25319-02.msi
-	apphost.exe
-	dotnet-sharedframework-win-x64.2.0.0-preview2-25319-02.msi
-	dotnet-sharedframework-win-x86.2.0.0-preview2-25319-02.msi

@gkhanna79 @eerhardt , are these files that we should be concerned about?

**Comment by gkhanna79** [comment]
Apphost is not expected to be signed by design. Don't know about the dll, where is it coming From?

For the msi, they should be signed. Rakesh should chime in.

**Comment by chcosta** [comment]
Hmm... looking at a recent build, it appears they were signed, and published.  It's not clear why they were flagged as not signed.  I'm investigating.

**Comment by eerhardt** [comment]
`ux\wixstdba.dll` what is this?

**Comment by chcosta** [comment]
wixstdba is part of the "Windows Installer Xml" Wix tools.  This file is included in the exe's

**Comment by eerhardt** [comment]
@Petermarcu @robmen - do you guys know about the `wixstdba.dll` assembly?  Is it supposed to be signed?  If yes, by whom?

**Comment by robmen** [comment]
No, it is not signed. It's internal to the bundle. The bundle gets signed.

**Comment by chcosta** [comment]
The msi's we ship appear to be signed, but it appears that we pack an msi into the exe installers, and those ones are not signed.  I presume this is not ok.

**Comment by chcosta** [comment]
I've confirmed that this appears to be a regression

**Comment by chcosta** [comment]
The GenerateBundles step (https://github.com/dotnet/core-setup/blob/master/src/pkg/packaging/windows/package.targets#L87) needs to be run in a separate step in our official builds after the MSI's are signed.  I won't be able to fix this today, but I'll try to have something by Monday

**Comment by robmen** [comment]
If you ship the MSI as part of a Bundle (the .exe installer) then technically speaking the MSI packages do not need to be signed. The Bundle will vouch for them.

**Comment by Petermarcu** [comment]
Correct. The exe (bundle) definitely needs to be signed.

**Comment by chcosta** [comment]
The bundle is signed, the msi is not. Even if it's not technically required, it will probably prevent confusion to have it signed

**Comment by chcosta** [comment]
This issue has been fixed with https://github.com/dotnet/core-setup/pull/2477#issuecomment-303541918
