### ISSUE TITLE
Fix auto-update with Core-Setup on BuildTools

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#2208]
Right now auto-update fails because the update-dependencies script/project isn't where it used to be: https://devdiv.visualstudio.com/DevDiv/_build?buildId=706573.

It's been debated how to solve this--keeping (adding back) the update-dependencies .NET project vs. using BuildTools `UpdateDependenciesAndSubmitPullRequest`. Either way, we'll most likely need to update https://github.com/dotnet/versions/blob/master/Maestro/subscriptions.json to match.

/cc @karajas @chcosta @eerhardt @weshaggard

**Comment by karajas** [comment]
https://github.com/dotnet/versions/pull/153

**Comment by dagood** [comment]
Fixed, we can see this working E2E with this auto-PR: https://github.com/dotnet/core-setup/pull/2340. Thanks, @karajas.
