### ISSUE TITLE
A netcoreapp2.0 version of the dotnet-deb-tool needs to be provided

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#2223]
Cli no longer carries 1.0 runtimes with it and it no longer rolls tool forward across major versions. Which means that a tool that targets 1.0 won't run on 2.0. This is because the runtime itself does not support this roll-forward.

However, this now prevents the CLI from using the current tool, because we don't have a runtime to run it at.

**Comment by gkhanna79** [comment]
@eerhardt ?

**Comment by eerhardt** [comment]
I'm working on this.  I already have the deb-tool ported to netcoreapp2.0 (https://github.com/dotnet/core-setup/pull/2227).  We just aren't publishing anything from `core-setup/master` at the moment.

**Comment by eerhardt** [comment]
We are now generating a `netcoreapp2.0` deb-tool package, but it is not getting pubilshed.

@karajas - are you working on getting this tool published to the `cli-deps` repo?  Can you please let me know either way?  If you aren't working on it, I will.

**Comment by karajas** [comment]
I haven't added the publish back yet.

**Comment by karajas** [comment]
@eerhardt I can work on this now if it's still up for grabs

**Comment by eerhardt** [comment]
Yes - it is still up for grabs.  Please take it.

**Comment by eerhardt** [comment]
This is now fixed.  See https://dotnet.myget.org/feed/cli-deps/package/nuget/dotnet-deb-tool/2.0.0-preview2-25316-09.

Please note that the plan for this tool is to move it to dotnet/buildtools and turn it into an MSBuild target instead of a CLI Tool. This won't happen immediately, but it is the eventual goal.

Closing.
