### ISSUE TITLE
Regression: Remove signing for host binary

### ISSUE THREAD

**Issue by chcosta** [dotnet/core-setup#2231]
Probable regression from buildtools work - From <https://github.com/dotnet/core-setup/commit/6e2d59e2fc3227fe355cf97a4a670d3ccf5b79bf>

**Comment by gkhanna79** [comment]
@ramarag Assigning this to you since you were looking into this? Please close if this is a no-op.

**Comment by ramarag** [comment]
I have verified that as of build 2.0.0-preview2-25303-01, we are signing dotnet.exe .
 apphost.exe  is still unsigned
