### ISSUE TITLE
Core-setup writes build output to .\packages folder

### ISSUE THREAD

**Issue by ericstj** [dotnet/core-setup#2238]
Build core-setup.

Observe built Core.App package is restored to packages/Microsoft.NETCore.App/<version>.

Run clean

Make some change to Core.App.

Build again

Expect: change is observed in tests

Actual: tests still run against old package since it was placed in packages folder and not cleaned.

To fix this we should root out all uses of the packages folder and ensure its only used as a packages folder for build.  For tests that want to restore what was just built, they should use some other temporary packages folder under bin or obj that is deleted by clean.  They can avoid re-download by using the packages folder as a source.  They could avoid an additional copy by using the packages folder as a fallback source.

**Comment by eerhardt** [comment]
Is this required for 2.0?  I think we could get away with moving this to 2.1 since this is the way the repo has worked for a while now.

**Comment by dagood** [comment]
Closing: this is stale, tests have their own directory for this now.
