### ISSUE TITLE
Validate installers

### ISSUE THREAD

**Issue by chcosta** [dotnet/core-setup#2246]
Validate the installers which are produced as part of core-setup on buildtools.  This is above and beyond  what is consumed by the cli.

**Comment by rakeshsinghranchi** [comment]
Waiting for master to build debian installers.

**Comment by rakeshsinghranchi** [comment]
cc @chcosta 
CI produces MSIs with rid in the file name . for e.g. 
dotnet-win7-x86-2.0.0-preview2-25303-9.exe. Official build,however, does not have rid in the package name. 
https://ci.dot.net/job/dotnet_core-setup/job/master/job/debug_windows_nt_x86_prtest/1371/consoleFull

**Comment by chcosta** [comment]
Thanks, i'll address that with some other artifact naming issues i'm fixing today

**Comment by rakeshsinghranchi** [comment]
cc @chcosta 

OS : Mac 
Issue : Package title in Installer UI shows the branding within single quotes (' ' ' )  . for e.g
'Microsoft .NET Core 2.0.0 - Runtime' (x64) Installer . Quotes are not expected.

**Comment by rakeshsinghranchi** [comment]
cc @chcosta 

OS : Mac
All pkg Installers are failing to install . 
Installer master/Installers/2.0.0-preview2-25304-02/dotnet-osx-x64-2.0.0-preview2-25304-02.pkg
 : 
storedownloadd)
May  3 18:53:27 Rakeshs-MacBook-Pro Installer[9756]: ================================================================================
May  3 18:53:27 Rakeshs-MacBook-Pro Installer[9756]: User picked Standard Install
May  3 18:53:27 Rakeshs-MacBook-Pro Installer[9756]: Choices selected for installation:
May  3 18:53:27 Rakeshs-MacBook-Pro Installer[9756]: 	Install: "'Microsoft .NET Core 2.0.0 - Runtime' (x64)"
May  3 18:53:27 --- last message repeated 1 time ---
May  3 18:53:27 Rakeshs-MacBook-Pro Installer[9756]: 		dotnet-osx-x64-2.0.0-preview2-25304-02.pkg#com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.2.0.0-preview2-25304-02.component.osx.x64.pkg : com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.2.0.0-preview2-25304-02.component.osx.x64.pkg : 2.0.0-preview2-25304-02
May  3 18:53:27 Rakeshs-MacBook-Pro Installer[9756]: 	Install: "'Microsoft .NET Core 2.0.0 - Host' (x64)"
May  3 18:53:27 Rakeshs-MacBook-Pro Installer[9756]: 		dotnet-osx-x64-2.0.0-preview2-25304-02.pkg#com.microsoft.dotnet.sharedhost.component.osx.x64.pkg : com.microsoft.dotnet.sharedhost.component.osx.x64.pkg : 2.0.0-preview2-25304-02
May  3 18:53:27 Rakeshs-MacBook-Pro Installer[9756]: 	Install: "'Microsoft .NET Core 2.0.0 - Host FX Resolver' (x64)"
May  3 18:53:27 Rakeshs-MacBook-Pro Installer[9756]: 		dotnet-osx-x64-2.0.0-preview2-25304-02.pkg#com.microsoft.dotnet.hostfxr.2.0.0-preview2-25304-02.component.osx.x64.pkg : com.microsoft.dotnet.hostfxr.2.0.0-preview2-25304-02.component.osx.x64.pkg : 2.0.0-preview2-25304-02
May  3 18:53:27 Rakeshs-MacBook-Pro Installer[9756]: ================================================================================
May  3 18:53:27 Rakeshs-MacBook-Pro Installer[9756]: It took 0.00 seconds to summarize the package selections.
May  3 18:53:27 Rakeshs-MacBook-Pro Installer[9756]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
May  3 18:53:27 Rakeshs-MacBook-Pro Installer[9756]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/var/folders/__/plnj2kds7jsdxtcp6b7lybtr0000gn/T/dotnet-osx-x64-2.0.0-preview2-25304-02.pkg#com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.2.0.0-preview2-25304-02.component.osx.x64.pkg
May  3 18:53:27 Rakeshs-MacBook-Pro Installer[9756]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/var/folders/__/plnj2kds7jsdxtcp6b7lybtr0000gn/T/dotnet-osx-x64-2.0.0-preview2-25304-02.pkg#com.microsoft.dotnet.sharedhost.component.osx.x64.pkg
May  3 18:53:27 Rakeshs-MacBook-Pro Installer[9756]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/var/folders/__/plnj2kds7jsdxtcp6b7lybtr0000gn/T/dotnet-osx-x64-2.0.0-preview2-25304-02.pkg#com.microsoft.dotnet.hostfxr.2.0.0-preview2-25304-02.component.osx.x64.pkg
May  3 18:53:27 Rakeshs-MacBook-Pro Installer[9756]: Set authorization level to root for session
May  3 18:53:32 Rakeshs-MacBook-Pro Installer[9756]: Administrator authorization granted.
May  3 18:53:32 Rakeshs-MacBook-Pro Installer[9756]: Will use PK session
May  3 18:53:32 Rakeshs-MacBook-Pro Installer[9756]: Using authorization level of root for IFPKInstallElement
May  3 18:53:32 Rakeshs-MacBook-Pro Installer[9756]: Starting installation:
May  3 18:53:32 Rakeshs-MacBook-Pro Installer[9756]: Configuring volume "Macintosh HD"
May  3 18:53:32 Rakeshs-MacBook-Pro Installer[9756]: Preparing disk for local booted install.
May  3 18:53:32 Rakeshs-MacBook-Pro Installer[9756]: Free space on "Macintosh HD": 355.87 GB (355869605888 bytes).
May  3 18:53:32 Rakeshs-MacBook-Pro Installer[9756]: Create temporary directory "/var/folders/__/plnj2kds7jsdxtcp6b7lybtr0000gn/T//Install.9756XxyVBy"
May  3 18:53:32 Rakeshs-MacBook-Pro Installer[9756]: IFPKInstallElement (3 packages)
May  3 18:53:32 Rakeshs-MacBook-Pro installd[367]: PackageKit: Adding client PKInstallDaemonClient pid=9756, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
May  3 18:53:32 Rakeshs-MacBook-Pro Installer[9756]: PackageKit: Enqueuing install with framework-specified quality of service (utility)
May  3 18:53:32 Rakeshs-MacBook-Pro installd[367]: PackageKit: ----- Begin install -----
May  3 18:53:32 Rakeshs-MacBook-Pro installd[367]: PackageKit: request=PKInstallRequest <3 packages, destination=/>
May  3 18:53:32 Rakeshs-MacBook-Pro installd[367]: PackageKit: packages=(
	    "PKLeopardPackage <file://localhost/var/folders/__/plnj2kds7jsdxtcp6b7lybtr0000gn/T/dotnet-osx-x64-2.0.0-preview2-25304-02.pkg#com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.2.0.0-preview2-25304-02.component.osx.x64.pkg>",
	    "PKLeopardPackage <file://localhost/var/folders/__/plnj2kds7jsdxtcp6b7lybtr0000gn/T/dotnet-osx-x64-2.0.0-preview2-25304-02.pkg#com.microsoft.dotnet.sharedhost.component.osx.x64.pkg>",
	    "PKLeopardPackage <file://localhost/var/folders/__/plnj2kds7jsdxtcp6b7lybtr0000gn/T/dotnet-osx-x64-2.0.0-preview2-25304-02.pkg#com.microsoft.dotnet.hostfxr.2.0.0-preview2-25304-02.component.osx.x64.pkg>"
	)
May  3 18:53:32 Rakeshs-MacBook-Pro installd[367]: PackageKit: Session UUID file exists - will not overwrite /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/977527C5-04F6-425C-9A70-E594CF9821BD.activeSandbox
May  3 18:53:33 Rakeshs-MacBook-Pro installd[367]: PackageKit: Will do receipt-based obsoleting for package identifier com.microsoft.dotnet.sharedhost.component.osx.x64 (prefix path=usr/local/share/dotnet)
May  3 18:53:33 Rakeshs-MacBook-Pro installd[367]: PackageKit: Extracting file://localhost/var/folders/__/plnj2kds7jsdxtcp6b7lybtr0000gn/T/dotnet-osx-x64-2.0.0-preview2-25304-02.pkg#com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.2.0.0-preview2-25304-02.component.osx.x64.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/977527C5-04F6-425C-9A70-E594CF9821BD.activeSandbox/Root/usr/local/share/dotnet, uid=0)
May  3 18:53:33 Rakeshs-MacBook-Pro installd[367]: PackageKit: Extracting file://localhost/var/folders/__/plnj2kds7jsdxtcp6b7lybtr0000gn/T/dotnet-osx-x64-2.0.0-preview2-25304-02.pkg#com.microsoft.dotnet.sharedhost.component.osx.x64.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/977527C5-04F6-425C-9A70-E594CF9821BD.activeSandbox/Root/usr/local/share/dotnet, uid=0)
May  3 18:53:33 Rakeshs-MacBook-Pro installd[367]: PackageKit: Extracting file://localhost/var/folders/__/plnj2kds7jsdxtcp6b7lybtr0000gn/T/dotnet-osx-x64-2.0.0-preview2-25304-02.pkg#com.microsoft.dotnet.hostfxr.2.0.0-preview2-25304-02.component.osx.x64.pkg (destination=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/977527C5-04F6-425C-9A70-E594CF9821BD.activeSandbox/Root/usr/local/share/dotnet, uid=0)
May  3 18:53:33 Rakeshs-MacBook-Pro installd[367]: PackageKit: prevent user idle system sleep
May  3 18:53:33 Rakeshs-MacBook-Pro installd[367]: PackageKit: suspending backupd
May  3 18:53:33 Rakeshs-MacBook-Pro installd[367]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/977527C5-04F6-425C-9A70-E594CF9821BD.sandboxTrash for sandbox /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/977527C5-04F6-425C-9A70-E594CF9821BD.activeSandbox
May  3 18:53:33 Rakeshs-MacBook-Pro installd[367]: PackageKit: Shoving /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/977527C5-04F6-425C-9A70-E594CF9821BD.activeSandbox/Root (1 items) to /
May  3 18:53:33 Rakeshs-MacBook-Pro install_monitor[10201]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
May  3 18:53:33 Rakeshs-MacBook-Pro installd[367]: PackageKit: Done with sandbox removals
May  3 18:53:33 Rakeshs-MacBook-Pro installd[367]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.2Y2cLY/Scripts/com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.2.0.0-preview2-25304-02.component.osx.x64.7RAI4Q
May  3 18:53:33 Rakeshs-MacBook-Pro installd[367]: PackageKit: *** launch path not accessible
May  3 18:53:33 Rakeshs-MacBook-Pro installd[367]: PackageKit: Failed task attributes: {
	    NSFileCreationDate = "2017-05-04 01:04:55 +0000";
	    NSFileExtensionHidden = 0;
	    NSFileGroupOwnerAccountID = 20;
	    NSFileGroupOwnerAccountName = staff;
	    NSFileHFSCreatorCode = 0;
	    NSFileHFSTypeCode = 0;
	    NSFileModificationDate = "2017-05-04 01:04:55 +0000";
	    NSFileOwnerAccountID = 503;
	    NSFilePosixPermissions = 420;
	    NSFileReferenceCount = 1;
	    NSFileSize = 318;
	    NSFileSystemFileNumber = 7190988;
	    NSFileSystemNumber = 16777220;
	    NSFileType = NSFileTypeRegular;
	}
May  3 18:53:33 Rakeshs-MacBook-Pro install_monitor[10201]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
May  3 18:53:34 Rakeshs-MacBook-Pro installd[367]: PackageKit: releasing backupd
May  3 18:53:34 Rakeshs-MacBook-Pro installd[367]: PackageKit: allow user idle system sleep
May  3 18:53:34 Rakeshs-MacBook-Pro installd[367]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “dotnet-osx-x64-2.0.0-preview2-25304-02.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/var/folders/__/plnj2kds7jsdxtcp6b7lybtr0000gn/T/dotnet-osx-x64-2.0.0-preview2-25304-02.pkg#com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.2.0.0-preview2-25304-02.component.osx.x64.pkg, PKInstallPackageIdentifier=com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.2.0.0-preview2-25304-02.component.osx.x64, NSLocalizedDescription=An error occurred while running scripts from the package “dotnet-osx-x64-2.0.0-preview2-25304-02.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cdotnet-osx-x64-2.0.0-preview2-25304-02.pkg\U201d.";
	    NSURL = "file://localhost/var/folders/__/plnj2kds7jsdxtcp6b7lybtr0000gn/T/dotnet-osx-x64-2.0.0-preview2-25304-02.pkg#com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.2.0.0-preview2-25304-02.component.osx.x64.pkg";
	    PKInstallPackageIdentifier = "com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.2.0.0-preview2-25304-02.component.osx.x64";
	}
May  3 18:53:34 Rakeshs-MacBook-Pro installd[367]: PackageKit: Running idle tasks
May  3 18:53:34 Rakeshs-MacBook-Pro Installer[9756]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “dotnet-osx-x64-2.0.0-preview2-25304-02.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/var/folders/__/plnj2kds7jsdxtcp6b7lybtr0000gn/T/dotnet-osx-x64-2.0.0-preview2-25304-02.pkg#com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.2.0.0-preview2-25304-02.component.osx.x64.pkg, PKInstallPackageIdentifier=com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.2.0.0-preview2-25304-02.component.osx.x64, NSLocalizedDescription=An error occurred while running scripts from the package “dotnet-osx-x64-2.0.0-preview2-25304-02.pkg”.}
May  3 18:53:34 Rakeshs-MacBook-Pro installd[367]: PackageKit: Removing client PKInstallDaemonClient pid=9756, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
May  3 18:53:34 Rakeshs-MacBook-Pro installd[367]: PackageKit: Done with sandbox removals
May  3 18:53:34 Rakeshs-MacBook-Pro Installer[9756]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
May  3 18:53:35 Rakeshs-MacBook-Pro Installer[9756]: IFDInstallController 11020 state = 8
May  3 18:53:35 Rakeshs-MacBook-Pro Installer[9756]: Displaying 'Install Failed' UI.
May  3 18:53:35 Rakeshs-MacBook-Pro Installer[9756]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
May  3 18:53:45 Rakeshs-MacBook-Pro Installer[9756]: Package Removal: Package is not in downloads directory. Not offering removal.
May  3 18:53:45 Rakeshs-MacBook-Pro Installer[9756]: Package Removal: Package cannot be removed.

**Comment by rakeshsinghranchi** [comment]
@karajas  - Please take a look at the osx installer issue. Also, the branding issue of extra single quotes (' ' ) in branding. Let me know if you need more contexts.

**Comment by karajas** [comment]
So it seems like the current theory is that the postinstall scripts don't have executable permissions. Testing this now.

**Comment by karelz** [comment]
@gkhanna79 is it infra or setup? -- only 1 area label is needed to avoid double counting.

**Comment by gkhanna79** [comment]
Fixed as setup.

**Comment by rakeshsinghranchi** [comment]
cc @karajas 

Installer file name for Ubuntu14.04 and Debian packages have regressed. This is causing broken links in readme file for daily builds.

Ubuntu 14.04 : for e.g.
Expected:dotnet-host-ubuntu-x64-*.deb
Actual:dotnet-host-ubuntu.14.04-x64-*.deb

Debian:
Expected:dotnet-host-debian-x64*.deb
Actual:dotnet-host-debian.8-x64*.deb

**Comment by rakeshsinghranchi** [comment]
cc @gkhanna79 , @chcosta

**Comment by chcosta** [comment]
Rakesh, can you update the readme to reflect the debian file names?

**Comment by rakeshsinghranchi** [comment]
sure.
@gkhanna79 , are you fine updating the readme instead of preserving the installer filename format ? Also, as part of readme cleanup , we should get rid of tars and symbol links for Ubuntu and Debian. Please confirm.

**Comment by gkhanna79** [comment]
What is the motivation for installer name change?

CC @eerhardt

**Comment by karajas** [comment]
Following the thread in https://github.com/dotnet/core-setup/pull/2390#issuecomment-301989034

**Comment by rakeshsinghranchi** [comment]
cc @eerhardt  , does this change impact CLI branch consuming debian packages ?

this is a different issue as compared to #2390 . Issue is that Ubuntu 14.04 and Debian packages now have version specified in the package name. 

Ubuntu 14.04 : for e.g.
Expected:dotnet-host-ubuntu-x64-.deb
Actual:dotnet-host-ubuntu.**14.04**-x64-.deb
Debian:
Expected:dotnet-host-debian-x64*.deb
Actual:dotnet-host-debian**.8**-x64*.deb

Commit that takes care of updating the readme file broken link for Ubuntu 14.04 and Debian package :
https://github.com/dotnet/core-setup/commit/c82f3b655e8ce93357c2fad76ce8ceac2963890e

**Comment by eerhardt** [comment]
>  does this change impact CLI branch consuming debian packages ?

Yes, and it has already been fixed in the CLI.  See https://github.com/dotnet/cli/commit/6df51ceb3b26ba984386e98e5077c01b6414c45d

**Comment by gkhanna79** [comment]
Closing since addressed.
