### ISSUE TITLE
Mac OS X 10.11.6 install fails

### ISSUE THREAD

**Issue by Mark92630** [dotnet/core-setup#225]
## Steps to reproduce

https://www.microsoft.com/net/core?wt.mc_id=AID531812_EML_4418735#macos

## Expected  behavior

$ dotnet run
will execute successfully

## Actual behavior

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

## Environment data
`dotnet --info` output:

"Unknown option: --info"

I have attached my project.json file, cat-ed to a new file named x.txt

[x.txt](https://github.com/dotnet/core-setup/files/379386/x.txt)

**Comment by gkhanna79** [comment]
@blackdwarf Have you been able to repro this?

CC @schellap @ramarag

**Comment by blackdwarf** [comment]
@gkhanna79 nope, I haven't seen this. 

@Mark92630 did this continue to repro?

**Comment by Mark92630** [comment]
I am now getting a slightly different error message (see below). Changes:

1. I'm now running macOS Sierra (10.12.1).
2. I uninstalled and reinstalled Homebrew, and then installed openssl. I did get a complaint from Homebrew about having MacPorts on my system.

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-localization-l1-2-0.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   at Interop.mincore.TryGetErrorMessage(Int32 errorCode, StringBuilder sb, String& errorMsg)
   at Interop.mincore.GetMessage(Int32 errorCode)
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Abort trap: 6

**Comment by blackdwarf** [comment]
@Mark92630 which version you are downloading? The latest one from the page you referenced? Does the install from the PKG finish properly?

**Comment by Mark92630** [comment]
![screen shot 2016-10-26 at 09 56 55](https://cloud.githubusercontent.com/assets/8611158/19735968/93d2a928-9b62-11e6-9e9e-e896a7522f2d.png)

**Comment by gkhanna79** [comment]
I installed the SDK installer for OSX from https://www.microsoft.com/net/download#core and did the following:

1) dotnet new
2) dotnet restore
3) dotnet run

I successfully get the template HelloWorld app running.

```
Kumars-MacBook-Pro-2:~ gkhanna$ which dotnet
/usr/local/share/dotnet/dotnet
Kumars-MacBook-Pro-2:~ gkhanna$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-003148)

Product Information:
 Version:            1.0.0-preview2-003148
 Commit SHA-1 hash:  18ca244551

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
Kumars-MacBook-Pro-2:~ gkhanna$ cd Dev/
Kumars-MacBook-Pro-2:Dev gkhanna$ mkdir repro_cs_225
Kumars-MacBook-Pro-2:Dev gkhanna$ cd repro_cs_225/
Kumars-MacBook-Pro-2:repro_cs_225 gkhanna$ dotnet new

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.
Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include commandline arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.
Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 2238 ms
Expanding 100% 3795 ms
Created new C# project in /Users/gkhanna/Dev/repro_cs_225.
Kumars-MacBook-Pro-2:repro_cs_225 gkhanna$ dotnet restore
log  : Restoring packages for /Users/gkhanna/Dev/repro_cs_225/project.json...
log  : Writing lock file to disk. Path: /Users/gkhanna/Dev/repro_cs_225/project.lock.json
log  : /Users/gkhanna/Dev/repro_cs_225/project.json
log  : Restore completed in 826ms.
Kumars-MacBook-Pro-2:repro_cs_225 gkhanna$ dotnet run
Project repro_cs_225 (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling repro_cs_225 for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.1770219
 

Hello World!
Kumars-MacBook-Pro-2:repro_cs_225 gkhanna$ 
```

I looked at your project.json. It appears custom and referencing old and prerelease versions of packages. Here is the one that was generated for me:

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {},
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.1"
        }
      },
      "imports": "dnxcore50"
    }
  }
}

```

Does the problem repro for you if follow the same steps as I did?

**Comment by Mark92630** [comment]
This is further than I have ever gotten before, and a new (to me) error message. To get this far, I found and removed some symbolic links that were in my PATH and referred to old versions, and then installed using the URL you provided. I'm guessing that the remaining error has something to do with openssl, so I'm showing a "which" and a "version" for that at the bottom.

=======================================

Marks-iMac:~ markwallace$ which dotnet
/usr/local/share/dotnet/dotnet
Marks-iMac:~ markwallace$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-003148)

Product Information:
 Version:            1.0.0-preview2-003148
 Commit SHA-1 hash:  18ca244551

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
Marks-iMac:~ markwallace$ mkdir hwapp
Marks-iMac:~ markwallace$ cd hwapp
Marks-iMac:hwapp markwallace$ dotnet new

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.GetRandomBytes(Byte* buf, Int32 num)
   at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetRandomFileName()
   at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Abort trap: 6

====================================

Marks-iMac:hwapp markwallace$ which openssl
/opt/local/bin/openssl
Marks-iMac:hwapp markwallace$ openssl version
OpenSSL 1.0.2j  26 Sep 2016

**Comment by gkhanna79** [comment]
@bartonjs @stephentoub Are you aware of issues with OpenSSL on Sierra?

**Comment by bartonjs** [comment]
Nope.  @Mark92630 do you have the symlinks as described in https://www.microsoft.com/net/core#macos?

Short version:
```sh
$ mkdir /usr/local/lib
$ ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
$ ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
```

We don't use the openssl command line utility, but rather libcrypto.1.0.0 and libssl.1.0.0; and we expect them to be present in /usr/local/lib/.  (If you have symlinks there you can verify them as valid by running something like `otool -L` on them... if it gives an error the symlinks are bad :smile:)

**Comment by Mark92630** [comment]
**@bartonjs** - Once I corrected the symlinks to refer to the actual locations of those dylib files on my system (/opt/local/lib/), I finally got the "dotnet new" command to work. And then the "restore" and "run" commands, as @**gkhanna79** showed above, resulting in the "Hello World!" output.

I got my openssl through MacPorts rather than Homebrew.
