### ISSUE TITLE
Standardize OS detection when updating to build tools 2

### ISSUE THREAD

**Issue by ericstj** [dotnet/core-setup#2252]
Once we have the new build tools in core-setup we need to make the repo consistent about how it detects which OS it is running on and which OS it is packaging for.

The OS it is running on should be RuntimeOS calculated by buildtools unless that property is explicitly passed in.  There are places in the repo that are using OS, OSEnvioronment, OSGroup, and others where they intended RuntimeOS and these should all be replaced.

The primary RID which is being packaged for should be PackageRID and it will be derived from RuntimeOS if not specified.  See how this is done in corefx:
https://github.com/dotnet/corefx/blob/b7153b2f56f1a3dd49a67d4eca7dd78c791e8539/pkg/Microsoft.Private.CoreFx.NETCoreApp/netcoreapp.rids.props#L3-L31
Where _runtimeOsFamily is calculated:
https://github.com/dotnet/corefx/blob/b7153b2f56f1a3dd49a67d4eca7dd78c791e8539/pkg/dir.props#L6-L7
In core-setup this needs to be changed here:
https://github.com/dotnet/core-setup/blob/6887ab556bc8302390782711dcdd75b75e769cf5/src/pkg/projects/netcoreappRIDs.props#L4-L16

/cc @weshaggard @chcosta

**Comment by mellinoe** [comment]
This is just about cleaning up and standardizing the names of properties we are using in some targets files to determine which OS we are running on and building for. It's not critical, and we've already done the validation showing that our current builds are producing the right assets. We can do this for a future release as part of continued clean-up.

**Comment by weshaggard** [comment]
I think this was handled with @eerhardt's PR https://github.com/dotnet/core-setup/pull/3266.
