### ISSUE TITLE
Share source between depprojs that build framework packages

### ISSUE THREAD

**Issue by ericstj** [dotnet/core-setup#2257]
Microsoft.NETCore.App and Microsoft.NETCore.UniversalWindowsPlatform duplicate a lot of targets source.  We should unify this.

**Comment by ericstj** [comment]
Moving this out as it isn't particularly interesting for UWP since its is on a different schedule than CoreApp.

**Comment by dagood** [comment]
UWP is no longer built in core-setup, and tooling is unified in the Arcade SDK.
