### ISSUE TITLE
Need devscripts and debhelper on Jenkins machines

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#2260]
In order to build our installers during CI on Jenkins, we need to install our dependencies on the ubuntu machines.  We need this to ensure we don't break our installer build before checking in.

Before the conversion to buildtools, we did this by running the Ubuntu 14.04 build in a docker container that had the necessary dependencies.  See 

https://github.com/dotnet/core-setup/blob/a2ad2fa31fbbb08c857666b674164cad9c1f5ab0/netci.groovy#L54

and

https://github.com/dotnet/core-setup/blob/6887ab556bc8302390782711dcdd75b75e769cf5/tools-local/scripts/docker/ubuntu.14.04/Dockerfile#L35-L37

/cc @chcosta

**Comment by chcosta** [comment]
ack, i'm working on this. 
/cc @rakeshsinghranchi @vivmishra as an FYI

**Comment by rakeshsinghranchi** [comment]
@chcosta - Will your change replace the docker image build with the pre-built docker image as used during the official build : https://github.com/dotnet/core-setup/blob/master/buildpipeline/pipeline.json#L37 ?

**Comment by chcosta** [comment]
Yes, that is likely the direction this will go.  I'll look into making this change after our official builds have stabilized and proven out the docker images.

**Comment by chcosta** [comment]
https://github.com/dotnet/core-setup/issues/2303
