### ISSUE TITLE
Stop producing distro specific archives

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#2263]
Once the table in the readme is cleaned up, we shouldn't have any links to those archives but we need to make sure the obtain scripts in the CLI repo continue to work.

**Comment by JensNordenbro** [comment]
What happened to the Linux(arm) daily build in the Readme.md?

**Comment by gkhanna79** [comment]
@Petermarcu Shouldn't we be having links to the Distro specific installers that @rakeshsinghranchi is working upon?

**Comment by Petermarcu** [comment]
@gkhanna79 , Yeah, we should.

**Comment by rakeshsinghranchi** [comment]
Master already has distro specific installers for debian and ubuntu consuming portable linux-64. We have stopped producing distro specific archives ,readme has been updated too . 
https://github.com/dotnet/core-setup/commit/2294e8456f7b139eec641576ca3eeaacaf6cbb1f

Not sure, where to look for obtain scripts that CLI uses. 

What is the ask here?

**Comment by gkhanna79** [comment]
@rakeshsinghranchi The ask here is to ensure that links on README.MD for platform specific installers are for the ones your new infrastructure is building and we are no longer doing distro specific builds (which I believe is true per the official build definition of Core-Setup).

CLI installer scripts are being looked at by someone else - @eerhardt do you know who that is?

**Comment by eerhardt** [comment]
@johnbeisner is working on updating the dotnet-install scripts to support our new publish layout and only having the `linux` archives.  @livarcocc told me yesterday he is close to sending out a PR.

**Comment by gkhanna79** [comment]
Closing since completed.
