### ISSUE TITLE
Mark dotnet.exe and apphost.exe as largeaddressaware

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#2266]
Similar to https://github.com/dotnet/coreclr/blob/796cd8bd3c153af929844fcc4b4c950c1f9ad690/CMakeLists.txt#L330.

@ramarag Can you PTAL?

CC @jkotas

**Comment by mellinoe** [comment]
This would help a lot of our test runs in corefx. We've had to change lots of tests because they are using more than 1.5 GB of memory in a 32-bit process.
