### ISSUE TITLE
Investigate setting <Framework> to netcoreapp1.1 on arm64

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#2267]
See https://github.com/dotnet/core-setup/blob/231b561d93e78eb07369d3c9a2428ab2f41bf70c/dir.props#L220

We use this `<Framework>` property to generate the shared framework.  I don't think we should be setting it to `netcoreapp1.1` ever.

/cc @gkhanna79 @chcosta

**Comment by gkhanna79** [comment]
I agree, we should delete that condition for arm64 and make it consistent with other arch since it has not been released.


Thanks,
Gaurav
________________________________

**Comment by gkhanna79** [comment]
Fixed with https://github.com/dotnet/core-setup/pull/2274
