### ISSUE TITLE
Investigate usage of $(HostVersion) properties and other version properties

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#2268]
We have a bunch of places that are using $(HostVersion) incorrectly.

Here's an example https://github.com/dotnet/core-setup/blob/c9154ce462025e2300ec2a685ace08a8b698df34/src/pkg/packaging/osx/package.props#L6

` <HostFxrComponentId>com.microsoft.dotnet.hostfxr.$(HostVersion).component.osx.x64</HostFxrComponentId>`

Here we are building the hostfxr component, but we are using the `$(HostVersion)` property.  This is wrong because these components can and will version independently.

We need to investigate all the version usages - especially HostVersion as it seems to be the popular one to use - and correct the code to use the right version property.

**Comment by gkhanna79** [comment]
@rakeshsinghranchi PTAL.

**Comment by eerhardt** [comment]
FYI - I'm fixing the ones in the shared framework logic now.

**Comment by gkhanna79** [comment]
Will you endup fixing this as well, as part of it?

**Comment by eerhardt** [comment]
No, not the whole thing.  I'm only concentrating on shared framework logic for now.  I wrote this bug so it is addressed wholistically.
