### ISSUE TITLE
Add an explicit dependency on ICU

### ISSUE THREAD

**Issue by chcosta** [dotnet/core-setup#2283]
@ellismg provided some additional changes for core-setup.  We took the layout related changes in https://github.com/dotnet/core-setup/pull/2256, but didn't yet take the libicu related changes.  This issue is to track ensuring that we get the additional changes ported once our debian packages have been created / validated / stabilized.

https://github.com/ellismg/core-setup/commit/16ee3bbd121f95db939576c92b18ee3e8cd0f3ac

/cc @eerhardt @ellismg

**Comment by ellismg** [comment]
Talking with @Petermarcu it sounded like we'd want icu to be installed by default when you install our debs, but we should not block it's removal.  In Debian land, I believe this means adding it as Recommends in the control file.  apt should install Recommends by default, but they could be removed later.

**Comment by eerhardt** [comment]
Assigning to @rakeshsinghranchi per @gkhanna79

**Comment by gkhanna79** [comment]
Has this change made into master @rakeshsinghranchi ? Also, is https://github.com/dotnet/core-setup/issues/2506 same as this?

**Comment by rakeshsinghranchi** [comment]
Commit : https://github.com/dotnet/core-setup/commit/21153046bf35ddf5106928c1fc1233dae21f49a6
Closing this as it is already made into release/2.0.0 branch.
