### ISSUE TITLE
Building on OS X fails

### ISSUE THREAD

**Issue by sokket** [dotnet/core-setup#23]
## Steps to reproduce

1) Have an OS X box without XCode
2) Install dependencies via homebrew
3) Run build.sh
## Expected  behavior

Success!
## Actual behavior

Scanning dependencies of target dotnet
[  2%] Building CXX object cli/CMakeFiles/dotnet.dir/fxr/fx_ver.cpp.o
/Users/jon/Repositories/personal/dotnet/core-setup/src/corehost/cli/fxr/fx_ver.cpp:4:10: fatal error: 'cassert' file not found
# include <cassert>

```
     ^
```

1 error generated.

**Comment by schellap** [comment]
Why is this failing, there was no change in the codebase from CLI repo?

Cc @brthor

**Comment by sokket** [comment]
For the record, this was failing in the CLI repo too...I just always forgot to open an issue :(

**Comment by brthor** [comment]
@sokket has been talking about this for some time @schellap I don't think this is related to the move

**Comment by schellap** [comment]
Yeah I remembered post commenting, that he showed this to me during the build fork meeting. Anyway, the timing of this confused me a bit... I'll look into this. AFAIK, I did not install XCode on my El-Capitan and was able to build before that.

**Comment by gkhanna79** [comment]
Xcode brings in the native tools (clang, etc) that are required to build. How else are you proposing to get the toolset?

**Comment by gkhanna79** [comment]
See https://github.com/dotnet/coreclr/blob/master/Documentation/building/osx-instructions.md - it is applicable for all .NET Core repos that build for OSX.

**Comment by gkhanna79** [comment]
@sokket Does the above help answer your question?

**Comment by sokket** [comment]
Yeah, we can close this issue now. Thanks!
