### ISSUE TITLE
Question: Locating host bits

### ISSUE THREAD

**Issue by wjk** [dotnet/core-setup#230]
I was examining the behavior of core-setup and .NET CLI in regards to publishing an app that references `Microsoft.NETCore.App` as a platform reference. I have observed two different behaviors, neither of which exactly align with my goals for this kind of deployment:
1. If I deploy the app using a `"type": "platform"` reference in the `project.json`, .NET CLI copies only the project DLL into the `bin` directory, It also creates a few JSON files that enable `dotnet.exe` to locate the dependencies for the project. I can then run the project using `dotnet.exe <file>.dll`.
2. If I do not use a `"type": "platform"` reference in the `project.json`, .NET CLI copies every DLL in the `Microsoft.NETCore.App` dependency graph into the `bin` directory. It also copies the CoreCLR runtime DLLs into the `bin` directory, and finally copies `dotnet.exe` into this directory, renaming it so that it matches the name of the project DLL. I can then run the project using this EXE.

My goal for platform-reference deployment is to have the `Microsoft.NETCore.App` dependency graph installed into a shared location (perhaps by using the .NET Core Runtime installer available on Microsoft's website), and have only my project DLLs installed by my installer. I would then use a custom main entry point to launch the application. (I must use a custom main entry point EXE because I am writing a GUI application, and need to use `WinMain` instead of `main`.)

For this to work, I would need a way of locating the .NET Core Runtime directory using a standardized location set by the installer. I know from reading the installer docs that the installer writes Registry values that list the installed versions of the various runtime components (muxer, CoreFX DLLs, development tools, etc.). However, I do not see a formally future-proofed way of getting the root of the install directory, and from there locating the CoreFX DLLs using the Registry information. From simple experimentation I know that the install root for the runtime is `C:\Program Files\dotnet`, and the CoreFX and CoreCLR DLLs can be found in the `shared\Microsoft.NETCore.App\<version>` subfolder. Unfortunately, I have no guarantees that this arrangement would not change in the future. Could anyone here give any pointers on a better way I could detect the location of these files? I would also appreciate notes on how to perform the equivalent operation on Linux.

The main reason I want to do this is because I am planning on writing a substantial number of CoreCLR-based apps, most of which will be installed alongside one another, and I would rather not have to bundle a 71MB runtime with each and every one if I don't have to. (On Mac, I will have to due to the nature of app deployment on that platform, which is why I didn't mention it above.) Thanks for your assistance!

**Comment by mellinoe** [comment]
Related: https://github.com/dotnet/core-setup/issues/196

Is your main motivation behind creating a custom host to avoid creating a console window, or are there additional reasons for that? I.e. is part of you application going to be written with native code, or would the host's only real job be to launch the CLR?

Building a custom host is an option, but I think it's going to be extremely hard to emulate all of the functionality of corehost. It has a lot of complexity around dependency file parsing, path probing, etc. that is hard to get right. As far as I know, portable apps are tightly linked to the application manifests and layout produced by the `dotnet` tooling. I don't think it's trivial to to support that in a custom host, but I could be wrong.

If your use case is simply to host the CLR without a console window, then I think we should just add a +1 vote to https://github.com/dotnet/core-setup/issues/196. I think it's something we should/need to do eventually.

@gkhanna79 , @schellap

**Comment by wjk** [comment]
@mellinoe Yeah, my main motivation is to avoid creating a console window. I do have to use a bit of C++ code to implement my app's features, but as long as I can easily P/Invoke into those DLLs, I don't need any special support in the entry point.

**Comment by gkhanna79** [comment]
Please have a look at my comment in #196 - will that work for your scenario?

**Comment by wjk** [comment]
Sorry to bump this old issue, but I have some further questions.

I previously stated that all I would need in a custom main executable was a `WinMain()` entry point. Unfortunately, I have since realized this won’t be enough. To make my app fully integrate with the Windows environment, I would need to provide, _inter alia_, an icon, a custom version information resource, and a Windows SxS manifest (for Common Control theming support). Since I must specify these myself in my build process, using a renamed “one-size-fits-all” GUI executable won’t be sufficient. I would also need to ensure that C++-based native DLLs can be can be added to the probing path so that they can be P/Invoked into. Depending on the app, custom code inside `WinMain` itself may also be required (to be run before CoreCLR is initialized).

While a Linux main executable does not require all this overhead, I still want to be able to store my app’s managed assemblies in one directory (`/usr/share/my_app/managed`, for example), any required native shared libraries, if any, in another directory (possibly the same one as the one containing the managed assemblies) and the assemblies that are part of `Microsoft.NETCore.App` in a shared location, and still have the entry executable wire all this up.

@gkhanna79 @mellinoe @schellap Can you possibly help me on this? I’m frying my noodle trying to wrap my head around the exact algorithms used by `corehost` to resolve assemblies. Thanks!

**Comment by steveharter** [comment]
Closing; https://github.com/dotnet/core-setup/issues/196 is to address gui app. I'll add information regarding icon, version, SxS manifest manifest

>> I’m frying my noodle trying to wrap my head around the exact algorithms used by corehost to resolve assemblies

You'll need to add native dependencies in the project, which means they will get added to the deps.json. Then the file location will be resolved for these and passed to the coreclr. There is support for `additionalProbingPaths` in runtimeconfig.json and also a command-line `additionalprobingpath` option to help with the file location resolution.
