### ISSUE TITLE
Provide another "hostfxr_main" that calls a c-style callback (instead of Program.Main) for a more custom implementation of .NET Core.

### ISSUE THREAD

**Issue by pauldotknopf** [dotnet/core-setup#2306]
I spoke on slack about a tight C++ integration with .NET Core, and @davidfowl suggested I possibly look into creating a pull-request for my scenario. Before I go creating a pull-request, I want to discuss it first to ensure that it will be accepted.

Some background. I am trying to integrate .NET Core into Qt/Qml, similar to [pyotherside](https://github.com/thp/pyotherside). In order to provide the deep integration, I need more than the ability to invoke ```Program.Main``` using ```hostfxr```. I don't want to copy ```hostpolicy```, which would give me more control, because I think it is too much.

So, I need to extend ```hostfxr_main``` to support 1 more scenario. Calling a c-style callback that I can use to call ```coreclr_create_delegate``` on the coreclr manually. I will use this to pass around data/delegates for my integration.

```c++
// I need the host handle and domain so that I can create delegates and invoke them.
typedef int(*hostfxr_delegate_fn) (coreclr::host_handle_t host_handle, coreclr::domain_id_t domain_id);
// this will be called, instead of hostfxr_main.
SHARED_API int hostfxr_delegate(const int argc, const pal::char_t* argv[])
{
    // etc
}
```
Am I on the right track?

**Comment by steveharter** [comment]
@pauldotknopf do you have a prototype of this yet?

>>  don't want to copy hostpolicy, which would give me more control, because I think it is too much.
Too much of what? hostpolicy does the basic assembly\dll\resource file resolution in order to pass that information to the coreclr when initializing.

**Comment by pauldotknopf** [comment]
No, I choose a different approach. My "Main" is a c# application which loads my native stuff, instead of vice-versa.

**Comment by steveharter** [comment]
OK. I will close this issue then. Thanks
