### ISSUE TITLE
Ensure all project's 'bin' and 'obj' folder goes into the root "bin" folder

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#2322]
See https://github.com/dotnet/core-setup/pull/2275#discussion_r114846764.  Some of our project's bin and obj folders are going in the source tree.

Ex. 

`src\managed\Microsoft.Extensions.DependencyModel`
`src\managed\Microsoft.DotNet.PlatformAbstractions`
`src\sharedFramework\framework`

**Comment by weshaggard** [comment]
Fixed with https://github.com/dotnet/core-setup/pull/3115
