### ISSUE TITLE
update-dependencies.ps1 uses nonexistent CLI channel

### ISSUE THREAD

**Issue by naamunds** [dotnet/core-setup#233]
[update-dependencies.ps1](https://github.com/dotnet/core-setup/blob/master/build_projects/update-dependencies/update-dependencies.ps1) invokes dotnet-install.ps1 from CLI with the "preview" channel:
`& "$RepoRoot\artifacts\dotnet-install.ps1" -Channel preview -Architecture $Architecture -Verbose`

This channel no longer exists, causing this to fail.

In https://github.com/dotnet/core-setup/commit/9d069485fe1f28abe07c5edae4fddd558d873e1a, a fix for this was made to build.ps1; the same fix should be made to update-dependencies.ps1.

Ideally, the code should be shared between these two scripts as much as possible so that fixes like this don't have to be made in both places.

**Comment by gkhanna79** [comment]
@naamunds PTAL and resolve is this is still applicable.

**Comment by naamunds** [comment]
It looks like this was fixed by https://github.com/dotnet/core-setup/pull/403

/cc @dagood
