### ISSUE TITLE
If sdk version specified in global.json is not found, latest sdk is used silently

### ISSUE THREAD

**Issue by nguerrera** [dotnet/core-setup#2334]
## Steps to reproduce

* Use a global.json specifying an SDK that is not installed. 
* Check `dotnet --version` (or more generally, use any cli verb and see which sdk it uses)

```
D:\repro> dir /b "c:\Program Files\dotnet\sdk"
1.0.0
1.0.0-preview2-003121
1.0.0-preview2-003131
1.0.4
2.0.0-preview1-005957

D:\repro> type global.json
{
  "sdk": {
    "version": "1.2.0"
  }
}

D:\repro> dotnet --version
2.0.0-preview1-005957
```

## Expected  behavior
An error is reported indicating that the version specified in global.json is not present

## Actual behavior
It just uses latest SDK instead (effectively ignoring global.json)

## Scenarios
* Typos in global.json can get ignored.
* Teams can't impose a specific sdk version because on machines where that SDK is not installed, it will just use whatever is latest

## Environment data
```
.NET Command Line Tools (2.0.0-preview1-005957)

Product Information:
 Version:            2.0.0-preview1-005957
 Commit SHA-1 hash:  056ac0e9cd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005957\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

@eerhardt @gkhanna79 @livarcocc @johnbeisner @dsplaisted

**Comment by gkhanna79** [comment]
@livarcocc Please triage for milestone and assign to appropriate individual.

**Comment by nguerrera** [comment]
This is higher priority than #2336

**Comment by karelz** [comment]
This is blocking .NET Core 2.0 ZBB on 5/10.
If it is non-trivial I am fine moving it to Post-ZBB, given that it came quite late and close to the ZBB data.

@nguerrera @gkhanna79 any preferences?

**Comment by gkhanna79** [comment]
Livar should chime in.




Thanks,
Gaurav


-------- Original message --------

**Comment by nguerrera** [comment]
It is not trivial enough to be filed on May 9 @ 5 PM and fixed by May 10. ;) Track it however appropriate, but it needs to be fixed. @johnbeisner is working on it.

**Comment by karelz** [comment]
OK, seems non-trivial. Given it came in late, I'm marking it as Post-ZBB.

**Comment by johnbeisner** [comment]
https://github.com/dotnet/core-setup/commit/8a25b2a37ea432bb8a673ee521b42a7afc7486bd

**Comment by johnbeisner** [comment]
cherry-pick the changes to release/2.0.0
