### ISSUE TITLE
Running just 'dotnet' crashes the process 

### ISSUE THREAD

**Issue by kichalla** [dotnet/core-setup#2335]
## Steps to reproduce
- Download CLI from https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview1-005973/dotnet-dev-win-x64.2.0.0-preview1-005973.zip 
- Run `dotnet --info` and it should work fine
- Type `dotnet` and hit enter and you should see it crash

## Expected  behavior
Does not crash

## Actual behavior
Crashes

## Environment data
`dotnet --info`
```
.NET Command Line Tools (2.0.0-preview1-005973)

Product Information:
 Version:            2.0.0-preview1-005973
 Commit SHA-1 hash:  5436217013

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\kichalla\.dotnet\x64\sdk\2.0.0-preview1-005973\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

@gkhanna79 suggested that the regression was introduced over here: https://github.com/dotnet/core-setup/commit/766def1beadb804e4798b87f980e3927f497d182#diff-4a8fd76fdcf481b9ec7e0deeeaea06f9

**Comment by gkhanna79** [comment]
@ramarag Can you PTAL to get this fixed before EOD tomorrow?

**Comment by ramarag** [comment]
@kichalla can you paste the callstack under the debugger, i just tried out the repro and the issue does not occur for me

@gkhanna79 wereyou able to repro the issue ?

**Comment by gkhanna79** [comment]
I didnt try the repro but did look at the callstack in Windbg. Are you not able to use preview1-02111 sharedFX which is where this is supposed to repro?

**Comment by ramarag** [comment]
![image](https://cloud.githubusercontent.com/assets/10203266/25880976/4e3cea8c-34ef-11e7-856f-93fde59906c6.png)

**Comment by gkhanna79** [comment]
Under Windbg, what is the version of hostfxr.dll that is loaded for you @ramarag (output of lm vm hostfxr)?

**Comment by ramarag** [comment]
ok i kind of get it, @kichalla did you update dotnet.exe to the latest version ?
With the latest dotnet.exe hostfxr should not be loaded for invocations without arguments

**Comment by gkhanna79** [comment]
The following is the callstack in the dump:

```
04 (Inline Function) --------`-------- hostfxr!pal::strcasecmp+0x10 [e:\a\_work\612\s\src\corehost\common\pal.h @ 125] 
05 0000005f`6317fc70 00007ff7`db9295a2 hostfxr!fx_muxer_t::execute+0x1d7 [e:\a\_work\612\s\src\corehost\cli\fxr\fx_muxer.cpp @ 1017] 
06 0000005f`6317fe00 00007ff7`db92cc44 dotnet+0x95a2

```

**Comment by eerhardt** [comment]
What version of the host muxer are we using?  I just downloaded https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/2.0.0/dotnet-dev-win-x64.latest.zip and I can't repro the issue.

```
F:\DotNetTest\TestConsole>F:\dotnet\dotnet.exe --info
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   F:\dotnet\sdk\2.0.0-preview1-005977\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983


F:\DotNetTest\TestConsole>F:\dotnet\dotnet.exe

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help            Display help.
  --version         Display version.

path-to-application:
  The path to an application .dll file to execute.
```

**Comment by gkhanna79** [comment]
@kichalla Is this in Antares scenario where you are using older muxer against 2.0 hostfxr/SharedFX?

**Comment by ramarag** [comment]
@eerhardt i think the @kichalla using a 1.0 or 1.1 dotnet.exe

**Comment by kichalla** [comment]
Ah, you are right. Since 1.1 and 1.0 runtimes do not ship along with the latest CLI we install these *after* the CLI is installed and as you mentioned the dotnet.exe is getting overwritten these older versions. Sorry for the false alarm.
