### ISSUE TITLE
multilevel sdk lookup policy does not consider different versions across more than one level

### ISSUE THREAD

**Issue by nguerrera** [dotnet/core-setup#2336]
Once any sdk is found at any level, none of the SDKs at different levels are considered. 

For example, if there's an sdk version at the local location, it will be used irrespective of global.json or if there are newer versions available globally.

## Steps to reproduce

* Install a version of the CLI that you don't already have in the global location to the local location. For example:

Global installs
```
D:\repro>dir /b "c:\Program Files\dotnet\sdk"
1.0.0
1.0.0-preview2-003121
1.0.0-preview2-003131
1.0.4
2.0.0-preview1-005957
```

Local installs
```
D:\repro>dir /b %USERPROFILE%\.dotnet\x64\sdk
1.0.3
```

* Use dotnet --version to check which sdk is used (expecting 2.0.0-preview1-005957)
```
D:\repro>dotnet --version
1.0.3
```

* Put a global.json specifying an sdk version that is in the global location, but not the local location
```
D:\repro>type global.json
{
  "sdk": {
    "version": "1.0.0"
  }
}
```

* Use dotnet --version to check which sdk is used (expecting 1.0.0)
```
D:\repro>dotnet --version
1.0.3
```

## Expected  behavior
Without global.json, it uses the latest version in the global location that is later than the latest version in the local location
With global.json, it uses the version specified that can be found in the global location, but not the local location

## Actual behavior
It uses the latest local version

## Environment data
```
D:\>dotnet --info
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\nicholg\.dotnet\x64\sdk\1.0.3

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

@eerhardt @gkhanna79 @livarcocc @dsplaisted @johnbeisner

**Comment by gkhanna79** [comment]
@livarcocc Please triage for milestone and assign to appropriate individual.

**Comment by nguerrera** [comment]
When there is no global.json involved, the latest version selected should be the latest version across all levels as well.

**Comment by johnbeisner** [comment]
https://github.com/dotnet/core-setup/commit/8a25b2a37ea432bb8a673ee521b42a7afc7486bd

**Comment by johnbeisner** [comment]
cherry-pick the changes to release/2.0.0
