### ISSUE TITLE
Merge core-setup buildtools changes back into buildtools

### ISSUE THREAD

**Issue by chcosta** [dotnet/core-setup#2338]
Core-setup has a tools-override and a tools-local\Microsoft.DotNet.Build.Tasks.Local folder, both of which should be merged back into buildtools.  This issue is tracking that work.

/cc @weshaggard @eerhardt @karajas

**Comment by weshaggard** [comment]
tools-override has been merged back. We should consider removing all the tasks from the tools-local folder as well but we don't need to track that with this old issue.
