### ISSUE TITLE
Bash Build script should download install script

### ISSUE THREAD

**Issue by brthor** [dotnet/core-setup#234]
The build.sh file is using a copied version of the cli install script:
https://github.com/dotnet/core-setup/blob/master/build_projects/dotnet-host-build/build.sh#L97

This was changed here:
https://github.com/dotnet/core-setup/commit/5caaef7647fee38da701f3772aa3e710ddd10ccc#diff-7b84801f06d5633f2cf51f06931e27c8

We should integrate whatever changes went into the install script in cli (not sure what they were) and stop having a copied version here. This could potentially be pulling out of date versions of the cli.

/cc @ellismg @livarcocc

**Comment by brthor** [comment]
Looks like windows and linux are pulling different channels, and getting different CLI binaries.

https://github.com/dotnet/core-setup/blob/master/build_projects/dotnet-host-build/build.ps1#L69

**Comment by gkhanna79** [comment]
@brthor Is this intended to be fixed for 1.1.0?

**Comment by brthor** [comment]
Yes this should be fixed so that the windows and linux builds are running on the same version of cli binaries. 

Otherwise we may see some weird differences between the builds.

**Comment by gkhanna79** [comment]
Who has context on the CLI changes to these scripts and can help bring the changes over?

**Comment by brthor** [comment]
Anyone with some bash knowledge can revert this change:
https://github.com/dotnet/core-setup/commit/5caaef7647fee38da701f3772aa3e710ddd10ccc#diff-7b84801f06d5633f2cf51f06931e27c8R94

The platforms which have been added only to the core setup install script need to also be committed to the official install script in the cli.

**Comment by brthor** [comment]
The powershell scripts are already doing this:
https://github.com/dotnet/core-setup/blob/master/build_projects/dotnet-host-build/build.ps1#L102

**Comment by gkhanna79** [comment]
> The platforms which have been added only to the core setup install script need to also be committed to the official install script in the cli.

Which platforms are you referring to?

**Comment by brthor** [comment]
These ones: https://github.com/dotnet/core-setup/blob/master/scripts/obtain/dotnet-install.sh#L59

cc @mellinoe @ellismg

**Comment by gkhanna79** [comment]
@wtgodbe Can you please work with @brthor  to get this addressed in master (for CLI and Core-Setup) and then port the Core-Setup fix to release/1.1.0?

**Comment by gkhanna79** [comment]
@wtgodbe Do we need to port this to

**Comment by gkhanna79** [comment]
@wtgodbe Please get a fix for https://github.com/dotnet/core-setup/pull/336#issuecomment-251555042 in today so that this change is complete in master.

**Comment by gkhanna79** [comment]
@wtgodbe Can we close this since this is fixed?

**Comment by wtgodbe** [comment]
Yes, I believe this is now fully resolved in all 3 branches. Closing.
