### ISSUE TITLE
Restructure the src/pkg folder so it builds logically top-down

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#2341]
Today we have the following folder structure:

![image](https://cloud.githubusercontent.com/assets/8291187/25902880/6e5f5de2-3560-11e7-88e7-8fc70dc1d3c4.png)

In our builds, the `src/dir.proj` file builds the `src/pkg/dir.proj` file.  But the `src/pkg/dir.proj` file only builds the `src/pkg/projects` directory.  It is up to a separate build file to build the `src/pkg/packaging` folder.

See the [root build.proj](https://github.com/dotnet/core-setup/blob/b38527380102d07ebcd7a0dd972bcc111bdca5ec/build.proj#L31) which needs to know about `src/dir.proj` and `src/pkg/packaging/dir.proj`.

We should structure our builds and folders correctly so these folders logically flow from the top-down.

/cc @chcosta

**Comment by eerhardt** [comment]
Moving to 2.1.  This isn't necessary for 2.0.

**Comment by dagood** [comment]
Closing, fixed/stale. In 3.0+, the projects are no longer in a prescriptive hierarchy, instead they build in parallel and ordering is driven by MSBuild-style project dependencies.
