### ISSUE TITLE
Poison Microsoft.NETCore.App and NETStandard.Library 2 from being used with 1.0 SDK

### ISSUE THREAD

**Issue by ericstj** [dotnet/core-setup#2344]
We know that these packages won't work correctly with 1.0 SDK.  Let's try to get a friendly failure mode rather than some obscure nuget or build error.

/cc @weshaggard @terrajobst @dsplaisted

**Comment by ericstj** [comment]
Currently blocked on https://github.com/dotnet/sdk/issues/534

Related: https://github.com/dotnet/sdk/issues/1194
This is effectively defining a way to do this better in the future.

**Comment by gkhanna79** [comment]
@ericstj Is this still intended for 2.0? If so, do you know when the dependent issue will get resolved?

**Comment by ericstj** [comment]
Yes, still intended for 2.0.  Still blocked on SDK.  /cc @livarcocc

**Comment by Petermarcu** [comment]
@ericstj whats the status here? Its getting pretty late.

**Comment by ericstj** [comment]
We're punting.  I couldn't get consensus from SDK team on how to do this.  I agree its too late to make a change now.
