### ISSUE TITLE
Remove the use of "Run" or fix the issues around it.

### ISSUE THREAD

**Issue by ellismg** [dotnet/core-setup#2349]
Run was designed to simplify argument parsing and share stuff across repositories.  It's not clear that the value we get outweighs the cost of yet another system.  We still end up needing to do some argument parsing in scripts anyway, so we should figure out if we should just fall back to shell scripts and get better hygiene around keeping windows/nix scripts in sync.

This is likely a contentious thing.  I'm filing the issue because I have to do a hack in build.sh and want to mark it with an issue number.

**Comment by Petermarcu** [comment]
@weshaggard is this issue still relevant with all the recent changes?

**Comment by weshaggard** [comment]
This is still relevant as there is still a hope to remove the run tool  but we first need to write some arg parsing scripts we can share and infra to maintain them.

**Comment by wtgodbe** [comment]
@dagood do we plan to get rid of the run tool with the move to Arcade?

**Comment by dagood** [comment]
Completed by the migration to the Arcade SDK.
