### ISSUE TITLE
dotnet.exe does not handle absolute paths with mixed slashes

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/core-setup#2376]
## Steps to reproduce
`dotnet.exe C:\path/to\some/assembly.dll`

## Expected  behavior
Loads assembly.dll for execution

## Actual behavior
> A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in (working directory)

## Environment data
Using: 2.0.0-preview2-25309-07 as bundled in .NET Core CLI 2.0.0-preview2-006065
Windows 10 x64

## Workaround
Convert all forward slashes to backslashes
`dotnet.exe C:\path\to\some\assembly.dll`

**Comment by gkhanna79** [comment]
@eerhardt confirmed that this does not repro with build 2.0.0-preview2-25307-01.  Possible regression from https://github.com/dotnet/core-setup/commit/6186962c2546713d521dcee2afeb481fa589ecd0#diff-29fc8a28403b84f9a93634c7c93329d0 or https://github.com/dotnet/core-setup/commit/3b8111f53a59e846ddcba363c3c5d0c0acfb7a2a#diff-29fc8a28403b84f9a93634c7c93329d0.

@ramarag PTAL.

**Comment by gkhanna79** [comment]
@ramarag PTAL at this when you are back as this appears to be high priority issue.
