### ISSUE TITLE
Automatically create meta-packages when new builds available on dotnet/versions

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#238]
core-setup should produce meta-packages for the latest builds on dotnet/versions.

This probably means kicking off builds with [Maestro](https://github.com/dotnet/versions), to trigger when a new applicable build is finished. Rebuilding isn't enough, though, since core-setup currently uses commit-count versions. To produce uniquely versioned meta-packages, we need to either:
1. Change to use a different versioning scheme where multiple differently versioned builds can be made on the same commit, and dynamically create the meta-package based on the latest versions.
2. Make an upgrade commit in core-setup for every meta-package created. We could commit directly to the repo, but I wonder if those commits might be too much clutter.

/cc @MattGal @livarcocc @gkhanna79 @markwilkie

**Comment by dagood** [comment]
Note after talking with @MattGal: however this goes, the build pipeline should be what's triggered (for telemetry), rather than the current way where each leg has its own GitHub commit trigger. It seems like a good time to make sure this change happens.

**Comment by weshaggard** [comment]
cc @ramarag who will be working on the core-setup engineering.

When we convert this repo to using BuildTools we should switch to the same versioning scheme we use everywhere else we use BuildTools.

**Comment by dagood** [comment]
@weshaggard Are you thinking that this issue should wait until that's complete and use option (1) above? Some more of my thoughts on the options:

Repeatability isn't typical with (1)--listing the versions repo sha used inside the meta-package description would make it possible, but not as straightforward as checking out a commit and building. Since the meta-packages are basically sets of versions, maybe this level of repeatability is ok?

I'm not a fan of (2) because it means core-setup needs a commit for *every* versions repo change that applies to the meta-packages. Very easily repeatable, though, and there's no need for the new versioning scheme.

(There's an implicit third option of having the typical manually-merged auto-PRs. I'm ignoring this because the desire is to have a meta-package for every daily build.)

/cc @joelverhagen

**Comment by weshaggard** [comment]
@dagood yes I think this issue can wait until we get the build in order. Generally for the meta-packages we are very explicit about the versions anyway so we may not even want their dependencies to be fully automated all the time.

**Comment by gkhanna79** [comment]
@dagood We dont intend to make fundamental engineering changes for 1.1.0. Should this be moved to 1.2.0?

**Comment by dagood** [comment]
@gkhanna79 Definitely. Moved.

**Comment by gkhanna79** [comment]
@wtgodbe Will be looking into fixing the commit count problem.

**Comment by dagood** [comment]
To be clear, the plan is to fix it by moving to buildtools (https://github.com/dotnet/core-setup/issues/283) and using its version generator, correct?

**Comment by wtgodbe** [comment]
We can do an intermediate fix by allowing for an officialBuildID to be passed in (similar to what we do in the CoreCLR and CoreFX pipelines), then returning that value from getCommitCount when appropriate (And most likely changing the name of that function to something more appropriate). Do you think it makes more sense to hold off on that until we move core-setup to buildtools/msbuild?

**Comment by dagood** [comment]
We still would need to convert from build id to something that doesn't go above what buildtools would give us so we can have consistently increasing numbers, but if that's doable, that sounds ok.

My understanding, though, is that this would be throwaway work once we get core-setup truly on top of buildtools--and I think using buildtools is more important than not having to do dummy commits. I don't know if those are the real options we have right now.

**Comment by danmosemsft** [comment]
Moved out of 2.0 per discussion with @markwilkie

**Comment by dagood** [comment]
This is no longer the way forward. Core-Setup participates in ProdCon v2, which these long-term plans: https://github.com/dotnet/arcade/blob/master/Documentation/DependenciesFlowPlan.md.
