### ISSUE TITLE
Various fixes for multi-level lookup

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#2398]
We need to do the following:

1) Disable looking up user-profile and only lookup dotnet EXE location and global location.
2) For patch roll forward for SharedFX, pickup the highest version from across all locations.

CC @davidfowl @nguerrera @ramarag @piotrpMSFT @blowdart @morganbr

**Comment by gkhanna79** [comment]
CC @eerhardt

**Comment by gkhanna79** [comment]
@ramarag Do you think we can get this change in today? I would like to have it bake in before Escrow next week.

**Comment by natemcmaster** [comment]
Can I ask what's driving this change? Unfortunately, we updated ASP.NET Core's build system about a month ago to use %USERPROFILE% to keep our command-line builds and VS experience in sync. IIUC we can't do that anymore once this is in as scripts don't have write-permissions to global and VS doesn't look at local.

**Comment by gkhanna79** [comment]
Please follow up offline with @davidfowl to understand the motivation and how the scenario will continue working.

**Comment by gkhanna79** [comment]
Closing since fixed.
