### ISSUE TITLE
ARM: "Did you mean to run dotnet SDK commands?"

### ISSUE THREAD

**Issue by Zuendelmeister** [dotnet/core-setup#2407]
Hi everyone,

I'm struggling with dotnet core on arm.
This is what I did: 

## Steps to reproduce
I downloaded the tar.gz, extracted it and wanted to show the version:
./dotnet --version

## Expected  behavior
I just wanted to test if it's working or not and see the version.

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/14317353/26110000/479c1a60-3a51-11e7-81d2-277404526d19.png)

The link just describes dotnet core installation for AMD64 and not for ARM. What should I do?
Thanks
Best regards,
Zuendelmeister

**Comment by omajid** [comment]
I think you installed just the runtime and are running into the problem where `--version` is part of the SDK. See https://github.com/dotnet/cli/issues/3773 for more on this. Can you try running just `./dotnet`?

**Comment by JensNordenbro** [comment]
try "dotnet --info"

**Comment by Zuendelmeister** [comment]
Hi again, thanks for your answers. Took me a while to get back to you sorry.
@omajid You are correct, I'm missing the CLI. I couldn't find an easy way of installing the CLI though. Do you have an easy way of installing the CLI? Starting a dotnet core dll works now.

**Comment by nzain** [comment]
While you can obtain the full sdk for `linux-x64` (official download from https://www.microsoft.com/net/download/core ) this is not the case for `linux-arm`, where you typically pick a download from https://github.com/dotnet/core-setup which, in turn, redirects to something like this:

https://dotnetcli.blob.core.windows.net/dotnet/Runtime/release/2.0.0/dotnet-runtime-latest-linux-arm.tar.gz

To my limited understanding, this contains a arm-compatible reduced host that does not contain all features (e.g. missing `dotnet new` or `dotnet --version`), but at least runs your apps. I don't think there is a arm-compatible CLI available (unless you compile on your own).

**Comment by Zuendelmeister** [comment]
Hi @nzain,

thanks for this. I will check it out =)

Best regards,
Zuendelmeister

**Comment by steveharter** [comment]
Closing as question resolved
