### ISSUE TITLE
Tizen CI failure

### ISSUE THREAD

**Issue by chcosta** [dotnet/core-setup#2432]
CI is failing the Tizen build leg
```
Tools/crossgen.sh: line 54:   824 Segmentation fault      (core dumped) $__crossgen /Platform_Assemblies_Paths $__sharedFxDir:$__toolsDir /nologo /MissingDependenciesOK /ReadyToRun $__file > /dev/null
```

Also, probably need to add an entry to netci.groovy for “armel” to prevent it failing since tests are being skipped..

https://github.com/dotnet/core-setup/blob/master/netci.groovy#L96-L98

```
	if (!(architecture == 'arm')) {
	Utilities.addMSTestResults(newJob, '**/*-testResults.trx')
	}
```

**Comment by gkhanna79** [comment]
Should be fixed with https://github.com/dotnet/core-setup/pull/2421
