### ISSUE TITLE
Validate installers for servicing scenarios

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#2449]
Assuming we are doing a 2.0 servicing release (e.g. 2.0.1) where hostfxr and dotnet.exe have not changed. Confirm that the installers (including the bundle) produced have the expected names (including version numbers) such that if we do a 2.0.2 servicing release, only the right components are installed.

**Comment by rakeshsinghranchi** [comment]
@gkhanna79 , please share pointers on what needs to change to produce 2.0.1 and 2.0.2 with locked hostfxr and dotnet.exe ? This issue appears to be a servicing readiness validation.

**Comment by Petermarcu** [comment]
@rakeshsinghranchi , have you been able to make any progress here?

**Comment by rakeshsinghranchi** [comment]
cc @eerhardt as he has done some changes related to locked version in the past.
No, I haven't got chance to look at this yet. I had a quick discussion with @gkhanna79 sometime back, need more details on this context.

**Comment by karelz** [comment]
@rakeshsinghranchi it is assigned to you. Can you please work with @eerhardt on who does what and when? I moved it to 2.0 servicing milestone.

**Comment by rakeshsinghranchi** [comment]
@weshaggard , I believe this has already been taken care of by you. can we close this ?

**Comment by weshaggard** [comment]
I've not done anything in particular to validate the installers.

**Comment by rakeshsinghranchi** [comment]
This is not relevant now as we have shipped 2.0.x releases . Looked at the packages statically and looks good to me. Closing this.
