### ISSUE TITLE
Always consider pre-release versions in the fx_ver_t::parse() method.

### ISSUE THREAD

**Issue by johnbeisner** [dotnet/core-setup#2451]
The call to fx_ver_t::parse() contains a bool parameter that controls whether or not to consider pre-release versions - current business logic considers pre-release versions for fx and sdk and probably will in the future.

Remove the bool parameter and always consider pre-release versions in the method.

**Comment by steveharter** [comment]
Doing this would imply roll-forward from pre-release to release. Is that the intent?

**Comment by vitek-karas** [comment]
See #5202 which proposes a new environment variable which would effectively do exactly what this issue proposes. Since there's little detail in this issue, @johnbeisner can you please take a look and confirm that the proposal would solve this?

**Comment by jeffschwMSFT** [comment]
Closing out this issue with https://github.com/dotnet/core-setup/pull/5202
