### ISSUE TITLE
Multi-hive lookup breaks finding the location of dotnet.exe

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/core-setup#2473]
Currently, managed code such as [Microsoft.DotNet.Cli.Utils.Muxer](https://github.com/dotnet/cli/blob/cc80822c16b955a1f664f8a65ed2c76c3c52a824/src/Microsoft.DotNet.Cli.Utils/Muxer.cs#L57-L77) rely on the value of `AppContext.GetData("FX_DEPS_FILE")` to find the "shared/Microsoft.NETCore.App/$version/' folder, and then navigate up the directory structure to  locate the "dotnet.exe" file.

This approach is broken by multi-hive setup because
 - the "dotnet.exe" sitting next to the "shared/" folder may not be the actual "dotnet.exe" filed used to launch the current process
 - the "dotnet.exe" is not required to exist next to the "shared/" folder anymore.

So 2 questions:

1. Is there already a reliable way to find the full path to the muxer that was used to launch the current process?
2. If not, can we add it?

cc @bradwilson - this is the issue you and I discussed a few weeks ago that made it almost impossible to make dotnet-xunit work with multi-hive setups.
cc @eerhardt

**Comment by eerhardt** [comment]
Similar issue here:  https://github.com/dotnet/cli/issues/6298

/cc @livarcocc @gkhanna79 

@natemcmaster - we have been tweaking the multi-hive feature a little in the past couple weeks.  Going forward, we think there will always be **a** muxer two directories up, but it might not necessarily be the exact same host executable that was used to invoke the current process.  Will this be "good enough"?  Or will the exact same host be required?

**Comment by gkhanna79** [comment]
@natemcmaster Do you need the location of the dotnet.exe used to launch the process? Also, if you are in the portable app mode (which is why you are using dotnet.exe location), why can you not use https://msdn.microsoft.com/en-us/library/system.diagnostics.process.mainmodule(v=vs.110).aspx to determine the entrypoint executable?

CC @ramarag

**Comment by natemcmaster** [comment]
> Do you need the location of the dotnet.exe used to launch the process? 

@gkhanna79 Yes, `Process.MainModule` looks like what we need. I'll give it a try. You mentioned this works in portable mode only. What happens in standalone mode?

@eerhardt the exact same host is required. Here are the details on the scenario that broke:

`dotnet-foo.dll`, a 1.1.x portable app that needs to invoke a new process `dotnet msbuild`. If `dotnet-foo.dll` uses the FX_DEPS_FILE approach to find the muxer, this is what happens.

```
C:\my-custom-install\
+ dotnet.exe                     <--- process 1, dotnet-foo.dll launched with this host
- sdk/
  + 1.0.3
  + 2.0.0-preview1-002111-00
- shared/
  - Microsoft.NETCore.App/
    + 2.0.0-preview1-002111-00
    + 1.1.1
    + 1.0.4
%USERPROFILE%/.dotnet/x64
+ dotnet.exe                       <---  process 1 found this dotnet.exe from FX_DEPS_FILE
                            <---- process 2 looks for sdk/ folder here, but it's not found
- shared/
  - Microsoft.NETCore.App/
    + 1.0.5
    + 1.1.2                   <---- process 1 resolves this framework
```

Because FX_DEPS_FILE led to %USERPROFILE%/.dotnet/x64/dotnet.exe, starting `dotnet msbuild` fails to resolve the SDK because it doesn't know how to find the the `C:\my-custom-install\sdk\` folder.

**Comment by eerhardt** [comment]
The "good" thing here is that we are removing `%USERPROFILE%` from the probing path when looking for shared frameworks.

See https://github.com/dotnet/core-setup/issues/2398 and corresponding PR https://github.com/dotnet/core-setup/pull/2481

**Comment by gkhanna79** [comment]
> What happens in standalone mode?

There is no dotnet.exe in standalone. But the above approach will get you the entrypoint EXE even for standalone.

**Comment by natemcmaster** [comment]
Awesome, thanks for the help. `Process.MainModule` appears to be the API we need. Closing as this resolves my issue.

Side note: we should consider using it in Microsoft.DotNet.Cli.Utils.Muxer...

**Comment by bradwilson** [comment]
Bummer, this API isn't available for `netcoreapp1.0`, so I'm stuck assuming that `dotnet` is somewhere on the PATH. ☹️

**Comment by gkhanna79** [comment]
@bradwilson You can PInvoke to it.

**Comment by bradwilson** [comment]
Damn, I didn't delete my comment fast enough. :) It is there, I was just accessing it wrong. :-p
