### ISSUE TITLE
"The system cannot find the path specified" during init-tools

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#2491]
### Steps to reproduce
Delete `Tools`, but leave `packages` containing the BuildTools package. Run any build command.

### Expected  behavior
The BuildTools package isn't restored again, but `Tools` is created again successfully with no error output.

### Actual behavior
The error "The system cannot find the path specified" is output on stderr, which doesn't block anything but sometimes bubbles up as an error. 

### Fix
When init-tools is able to skip BuildTools package restore, it doesn’t create the the BUILD_TOOLS_SEMAPHORE dir. (init-tools.msbuild creates it when being restored.) That means that when init-tools tries later to write the BUILD_TOOLS_SEMAPHORE, it can’t find the dir.

init-tools should create the semaphore dir if necessary to prevent this.

**Comment by dagood** [comment]
This was fixed in CoreCLR by https://github.com/dotnet/coreclr/pull/11912, and it looks like it hasn't happened here (Core-Setup) or CoreFX.

/cc @gkhanna79 @weshaggard

**Comment by gkhanna79** [comment]
Is this required for master only or even 2.0.0?

**Comment by dagood** [comment]
I suspect it's not worth porting for 2.0.0 because it doesn't affect clean builds.

**Comment by weshaggard** [comment]
This was fixed in corefx as well with dotnet/corefx#25737. We really need to get the auto-script updater going (dotnet/buildtools#1709).
