### ISSUE TITLE
[UWP] System.IO.FileNotFoundException: 'Could not load file or assembly 'System.IO.FileSystem.Watcher, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.'

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#2497]
@ericwj commented on [Tue May 23 2017](https://github.com/dotnet/coreclr/issues/11839)

```
System.IO.FileNotFoundException:
'Could not load file or assembly 'System.IO.FileSystem.Watcher,
Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
The system cannot find the file specified.'
```
Referencing `Microsoft.Extensions.FileProviders.Physical (>= 1.1.1)` in a Windows Runtime component.

Should this work with .NET Core UWP 5.3.3?

**Comment by gkhanna79** [comment]
@weshaggard @danmosemsft  Can you please help?

**Comment by steveharter** [comment]
@nattress PTAL

**Comment by eerhardt** [comment]
This issue was moved to dotnet/uwp-setup#86
