### ISSUE TITLE
Microsoft.NETCore.App 2.0 doesn't list netcoreapp1.1 dependencies

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#2512]
## Steps to reproduce
Look at the dependencies listed in the NETCore.App 2.0 package:

https://www.nuget.org/packages/Microsoft.NETCore.App/2.0.0-preview1-002111-00
https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.App/2.0.0-preview2-25324-02

## Expected  behavior
It should list the dependencies for netcoreapp1.0, netcoreapp1.1, and netcoreapp2.0

## Actual behavior
It only lists the dependencies for netcoreapp1.0 and netcoreapp2.0

@weshaggard @ericstj @gkhanna79

**Comment by eerhardt** [comment]
My initial investigation is that we aren't importing the netcoreapp1.1.props file:

https://github.com/dotnet/core-setup/blob/master/src/pkg/projects/Microsoft.NETCore.App/Microsoft.NETCore.App.pkgproj#L27-L40

https://github.com/dotnet/core-setup/blob/6887ab556bc8302390782711dcdd75b75e769cf5/src/pkg/projects/Microsoft.NETCore.App/netcoreapp1.1.props#L4

All the dependencies are defined in that file, but it isn't getting imported.

**Comment by ericstj** [comment]
Yeah, I'll pick this up.  I also want to update the repo to pick up the latest serviced versions per https://github.com/dotnet/standard/issues/354

**Comment by gkhanna79** [comment]
Reopening to track port of this to 2.0.0.
