### ISSUE TITLE
Update Runtime Installer [Mac]

### ISSUE THREAD

**Issue by leecow** [dotnet/core-setup#2513]
Strings and installer steps to be updated. Mac and Windows will receive similar updates and there will be separate issue covering Windows changes. Matching changes will be detailed in another issue for the SDK installer.

## Introduction

<img width="682" alt="1 introduction - runtime" src="https://cloud.githubusercontent.com/assets/2212879/26412512/dca4f6d8-405d-11e7-8ad2-d22e4de53d3f.png">

* [ ] Window title: `Install [productname] - [version] arc`
* [ ] Remove "Welcome to ..." text
* [ ] Update Introduction step content as detailed below.

### Intro step text elements
**.NET Core Runtime**

.NET Core is a development platform that you can use to build command-line applications, microservices and modern websites. It is open source, cross-platform, and supported by Microsoft. We hope you enjoy it! 

**Learn more about .NET Core**
* [Core Documentation](https://aka.ms/dotnet-docs)
* [SDK Documentation](https://aka.ms/dotnet-cli-docs)
* [Privacy Statement](https://aka.ms/dev-privacy)
* [MIT License](https://aka.ms/dotnet-license)

## License
* [ ] Remove License step from the installer. We've moved entirely to the MIT license so this is not longer needed. 

## Destination Select
* [ ] Window title: `Install [productname] - [version] arc`

## Installation Type
* [ ] Window title: `Install [productname] - [version] arc`

## Installation
* [ ] Window title: `Install [productname] - [version] arc`

## Summary

<img width="682" alt="6 success - runtime" src="https://cloud.githubusercontent.com/assets/2212879/26413167/f45748b0-405f-11e7-9169-b61521dd8aeb.png">

* [ ] Window title: `Install [productname] - [version] arc`
* [ ] Add 'success' graphic
* [ ] Include installation location and list of all components installed
* [ ] Update Summary step content as detailed below.

### Summary step text elements

The following were installed at `/usr/local/share/dotnet`
* .NET Core Runtime 2.0.0
* ASP.NET Runtime Package Store

**Resources**
* [Core Documentation](https://aka.ms/dotnet-docs)
* [SDK Documentation](https://aka.ms/dotnet-cli-docs)
* [Release Notes](https://aka.ms/20-p2-rel-notes)
* [Tutorials](https://aka.ms/dotnet-tutorials)
* [.NET Core Telemetry](https://aka.ms/dotnet-cli-telemetry)

/cc @richlander @gkhanna79 @livarcocc

**Comment by rakeshsinghranchi** [comment]
@leecow  I would need the success graphic. Do you have one ?

**Comment by leecow** [comment]
@rakeshsinghranchi I can make it easy enough. Do you just need the green check or also the 'success' text beneath? Do you need a png or jpeg?

**Comment by rakeshsinghranchi** [comment]
@leecow  , can we have both with and without 'success' text beneath. I want us to pick the one that will look better in the UI.

**Comment by rakeshsinghranchi** [comment]
@leecow , do we want to revert the branding text again ? 
We fixed the branding per below , now with the new guidance, it seems to be reverting back to the old branding

https://github.com/dotnet/core-setup/issues/2155

**Comment by rakeshsinghranchi** [comment]
This work is done in master and release/2.0.0 .
