### ISSUE TITLE
Update Runtime Installer [Windows]

### ISSUE THREAD

**Issue by leecow** [dotnet/core-setup#2516]
Strings and installer steps to be updated. Mac and Windows will receive similar updates and there will be separate issue covering Mac changes. Matching changes will be detailed in another issue for the SDK installer.

## Screen 1 (intro)

![runtime-1-new](https://cloud.githubusercontent.com/assets/2212879/26418024/9fcaa1c4-406f-11e7-966f-ddf809f7640f.png)

* [ ] Window title: `[productname] - [version] [arc] Installer`
* [ ] Remove "You just need a shell ..." text
* [ ] Update Introduction step content as detailed below.

### Intro step text elements
**.NET Core Runtime**

.NET Core is a development platform that you can use to build command-line applications, microservices and modern websites. It is open source, cross-platform, and supported by Microsoft. We hope you enjoy it! 

**Learn more about .NET Core**
* [Core Documentation](https://aka.ms/dotnet-docs)
* [SDK Documentation](https://aka.ms/dotnet-cli-docs)
* [Privacy Statement](https://aka.ms/dev-privacy)
* [MIT License](https://aka.ms/dotnet-license)

## Screen 2 (progress)
* [ ] Window title: `[productname] - [version] [arc] Installer`

## Screen 3 (success)

![runtime-3-new](https://cloud.githubusercontent.com/assets/2212879/26418100/dd9bee72-406f-11e7-8975-a4a6e32d07c2.png)

* [ ] Window title: `[productname] - [version] [arc] Installer`
* [ ] Include installation location and list of all components installed
* [ ] Update Summary step content as detailed below.

### Summary step text elements

The following were installed at `C:\Program Files\dotnet`
* .NET Core Runtime 2.0.0
* ASP.NET Runtime Package Store

**Resources**
* [Core Documentation](https://aka.ms/dotnet-docs)
* [SDK Documentation](https://aka.ms/dotnet-cli-docs)
* [Release Notes](https://aka.ms/20-p2-rel-notes)
* [Tutorials](https://aka.ms/dotnet-tutorials)
* [.NET Core Telemetry](https://aka.ms/dotnet-cli-telemetry)

/cc @richlander @gkhanna79 @livarcocc

**Comment by rakeshsinghranchi** [comment]
@leecow  , @gkhanna79 @Petermarcu @vivmishra 
1.  Windows title for Preview builds should have "Preview" branding too , can you please confirm?
2.  Runtime doesn't carry ASP.NET Runtime Package Store.
3.  Links should have fwlinks instead of hardcoded url . can you please provide fwlink url for above resource links?

**Comment by leecow** [comment]
@rakeshsinghranchi 

1. yes, 'preview' is part of the version number so the next round would be * 2.0.0-Preview 1-[buildnumber]
2. Understood
3. Will set these up in a little bit.

**Comment by leecow** [comment]
@rakeshsinghranchi issue updated with aka.ms links

**Comment by rakeshsinghranchi** [comment]
This work is done in master and release/2.0.0
