### ISSUE TITLE
NETCore.App 1.0.7 is missing StackTrace and Compression updates 

### ISSUE THREAD

**Issue by ericstj** [dotnet/core-setup#2519]
I noticed this here: https://github.com/dotnet/core-setup/pull/2515

I see that we produced updates for the following packages, but those updates aren't included in the shared framework:
  - System.Diagnostics.StackTrace
    - Included: 4.0.1
    - Latest serviced: 4.0.2
  - System.IO.Compression
    - Included: 4.1.0
    - Latest serviced: 4.1.1

It's possible this was intentional, but if not please consider addressing in the next servicing release.

**Comment by Petermarcu** [comment]
@ericstj , Can you follow up on this one to see if we should update the packages?

**Comment by ericstj** [comment]
These packages are fine.  The question is should we include the updates in NETCore.App (and the shared framework).  If so, then we should update https://github.com/dotnet/core-setup/blob/release/1.0.0/pkg/projects/Microsoft.NETCore.App/project.json. (note: release/1.0.0 branch)

This is more of a servicing policy decision, so I'll defer to @leecow.

**Comment by leecow** [comment]
What changes are included in the updates?

**Comment by ericstj** [comment]
Primarily packaging related issues for UWP: https://github.com/dotnet/corefx/pull/9783

**Comment by ericstj** [comment]
For stack trace we recompiled with lower versioned dependencies so that shared library wasn't invalidated: https://github.com/dotnet/corefx/pull/9783/commits/cceae704c5028ea6fd487a84ca69d720f050f417

For Compression we updated the native packaging to fix arm RID of clrcompression package https://github.com/dotnet/corefx/issues/7436, without that clrcompression was missing from UWP arm.
https://github.com/dotnet/corefx/pull/9107

Since both of these are UWP specific I think we should probably won't fix them for now.

In the future please make sure that every package we build out of CoreFx gets ingested in core-setup.  In cases like this where the reference is indirect (eg: through the NETStandard.Library package which wasn't being updated) a direct reference needs to be added to NETCore.App in order to realize the update.  That's only an issue for 1.x servicing.

-Eric
