### ISSUE TITLE
Improve the error message displayed when an assembly is missing from runtime store

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/core-setup#2523]
The error message shown today when an assembly appears to be missing from the runtime store should be improved to make it clearer.

## Today's message
```
Error: assembly specified in the dependencies manifest was not found probably due to missing runtime store associated with manifest.win7-x64.xml;manifest.win7-x86.xml;manife
st.osx-x64.xml;manifest.linux-x64.xml -- package: 'Microsoft.AspNetCore', version: '2.0.0-preview1-final', path: 'lib/netcoreapp2.0/Microsoft.AspNetCore.dll'
```

## Suggested message
Changes:
- Revised language
- Includes name of application dependencies manifest (deps file)
- Improves formatting (new lines, indentation)
- Separate message clearly showing name of target manifest used during publish
```
Error: An assembly specified in the application dependencies manifest (RazorPagesWebApplication.deps.json) was not found:
  package: 'Microsoft.AspNetCore', version: '2.0.0-preview1-final'
  path: 'lib/netcoreapp2.0/Microsoft.AspNetCore.dll'

This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
  aspnetcore-store-2.0.0-preview1-final-win7-x64.xml;aspnetcore-store-2.0.0-preview1-final-win7-x86.xml;aspnetcore-store-2.0.0-preview1-final-osx-x64.xml;aspnetcore-store-2.0.0-preview1-final-linux-x64.xml
```

## Rationalizing manifest files to current RID
Any ideas on how we could make it only show the manifest file name for the relevant RID would be great too.

**Comment by gkhanna79** [comment]
CC @eerhardt @ramarag @Petermarcu

**Comment by gkhanna79** [comment]
@steveharter will be driving the fix for this.

**Comment by steveharter** [comment]
@DamianEdwards any objections to collapsing the two separate messages so there are no blank lines? It seems like there are two messages otherwise. Something like this:
```
Error: An assembly specified in the application dependencies manifest (RazorPagesWebApplication.deps.json) was not found:
    package: 'Microsoft.AspNetCore', version: '2.0.0-preview1-final'
    path: 'lib/netcoreapp2.0/Microsoft.AspNetCore.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-preview1-final-win7-x64.xml;aspnetcore-store-2.0.0-preview1-final-win7-x86.xml;aspnetcore-store-2.0.0-preview1-final-osx-x64.xml;aspnetcore-store-2.0.0-preview1-final-linux-x64.xml
```

Also @JunTaoLuo I discussed the manifest file naming in this issue with @eerhardt and he suggest to ping you as to whether asp.net is going to do that? If not, the message will continue to display "manifest.linux-x64.xml" instead of "aspnetcore-store-2.0.0-preview1-final-linux-x64.xml" for example.

**Comment by DamianEdwards** [comment]
Fine to collapse, although perhaps this formatting would work better?:
```
Error:
  An assembly specified in the application dependencies manifest (RazorPagesWebApplication.deps.json) was not found:
    package: 'Microsoft.AspNetCore', version: '2.0.0-preview1-final'
    path: 'lib/netcoreapp2.0/Microsoft.AspNetCore.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-preview1-final-win7-x64.xml;aspnetcore-store-2.0.0-preview1-final-win7-x86.xml;aspnetcore-store-2.0.0-preview1-final-osx-x64.xml;aspnetcore-store-2.0.0-preview1-final-linux-x64.xml
```

For the file naming, I believe the ask was to change the stage property evaluation occurs in the SDK, so that we could set it to the single known RID-based manifest file from our side. It looks like that was been completed already in dotnet/sdk#1164 so we should be unblocked now.

**Comment by steveharter** [comment]
Sure I'll apply that formatting.

To be clear though, is there any additional work for this issue around the file naming? i.e. do we want to determine the single RID?

**Comment by DamianEdwards** [comment]
@steveharter that's tracked on our side via https://github.com/aspnet/MetaPackages/issues/57 now, so I think there's no extra work on your side for that.
