### ISSUE TITLE
When auto-updating, update a single PR when possible

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#253]
This should happen "for free" when changing core-setup to use buildtools. This issue tracks making sure auto-PRs get set up correctly.

**Comment by gkhanna79** [comment]
@ramarag Please sync with @dagood on this.

CC @schellap

**Comment by gkhanna79** [comment]
Assigning to @AlfredoMS since he is working on moving the repo to use build-tools.

**Comment by danmosemsft** [comment]
@gkhanna79 tells me @eerhardt completed this.
