### ISSUE TITLE
Can't get dotnet version on Raspbian Jessie

### ISSUE THREAD

**Issue by melzoghbi** [dotnet/core-setup#2559]
## Steps to reproduce
1) Installed .NET Core dependence:

sudo apt-get install libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev libcurl4-openssl-dev libssl-dev uuid-dev

2) Pulled .net core for armhf build from here:
wget https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/dotnet-runtime-latest-linux-arm.tar.gz

3) Unzipped the contents in dotnet folder:

mkdir dotnet
tar -xvf dotnet-runtime-latest-linux-arm.tar.gz -C /home/pi/dotnet

4) Trying to get the dotnet version:
cd dotnet
dotnet --version

## Expected  behavior

dotnet core version should be displayed 

## Actual behavior

An error:  Segmentation fault

![image](https://cloud.githubusercontent.com/assets/11993393/26601565/582196a0-454e-11e7-8e73-18b62c986b80.png)

## Environment data

Raspbian Jessie - 2017-04-01
Raspberry pi Zero W board

**Comment by fbau3r** [comment]
> Note: **Pi Zero is not supported** because the .NET Core JIT depends on armv7 instructions not available on Pi Zero.

From [.NET Core on Raspberry Pi](https://github.com/dotnet/core/blob/7d4c523/samples/RaspberryPiInstructions.md#net-core-on-raspberry-pi)

**Comment by steveharter** [comment]
Closing per last comment on Pi Zero is not supported yet
