### ISSUE TITLE
Generate and add Changelogs to Debian and RPM packages

### ISSUE THREAD

**Issue by vivmishra** [dotnet/core-setup#2562]
We are currently not adding any meaningful changelogs to Debian and RPM packages for every major milestone that needs to be fixed. (At least for RPM this is a requirement as per the guidelines.) 

For example, what we add to current Host RPM/Debian package comes from following JSON:
https://github.com/dotnet/core-setup/blob/master/src/pkg/packaging/rpm/dotnet-sharedhost-rpm_config.json

One of the options to explore is to add a changelog fwlink in the package that can then point to a master CL page for every major milestone/version.

**Comment by rakeshsinghranchi** [comment]
@leecow  , please share more context to this issue. Also, update the milestone.

**Comment by leecow** [comment]
Currently we include relevant commits in the the release notes (eg [release-notes/1.0/1.0.5.md](https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.5.md)). At a minimum for 2.0, we could point the changelist field at https://github.com/dotnet/core/tree/master/release-notes.

**Comment by omajid** [comment]
FYI, when we do RPMs we generally avoid duplicating the upstream changelog into the RPM changelogs. Often a comment like "Update to version 2.0" is good enough. Links to upstream release notes should also be okay. I don't think there's any point duplicating the notes into the RPM itself.

**Comment by Petermarcu** [comment]
I'm going to move this out of 2.0 at this point. Seems like a nice to have and not a must have.

**Comment by rakeshsinghranchi** [comment]
@leecow , what is the final decision here ?

**Comment by rakeshsinghranchi** [comment]
@leecow , any update ?

**Comment by leecow** [comment]
Let's link to https://github.com/dotnet/core/tree/master/release-notes
