### ISSUE TITLE
Setup RPM package feed

### ISSUE THREAD

**Issue by vivmishra** [dotnet/core-setup#2563]
We need to setup the RPM Package feed to allow easier consumption of RPM packages.

**Comment by rakeshsinghranchi** [comment]
@leecow , are we targeting this for 2.1.0 ?

**Comment by leecow** [comment]
Would like to shoot for 2.0.

**Comment by steveharter** [comment]
@leecow please update Milestone to 2.1 or provide update. Thanks

**Comment by leecow** [comment]
RPM feed is up and getting started guide will be updated today.

**Comment by karelz** [comment]
I'm gonna call it 2.0 servicing (2.0.x) as 2.0.0 is out of the door :)

**Comment by leecow** [comment]
Example - https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.4-download.md
