### ISSUE TITLE
Improvements to error message about unfound SDK version

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/core-setup#2570]
**Steps to reproduce**
Add a global.json file
```json
{
  "sdk": {
    "version": "99.99.99"
  }
}
```
`dotnet --version`

**Output**
```
The specified SDK version [] from global.json [/Users/namc/dev/aspnet/KestrelHttpServer/global.json] not found; install specified SDK version
Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

**Suggestions**
- include the version parsed from the global.json file in the error message
- list available sdk versions

**Environment data**
Using 2.0.0-preview2-006208

cc @johnbeisner

**Comment by johnbeisner** [comment]
Closing: https://github.com/dotnet/core-setup/pull/2621
