### ISSUE TITLE
Fix license in Microsoft-built deb/rpm packages

### ISSUE THREAD

**Issue by omajid** [dotnet/core-setup#2586]
This was originally discussed in https://github.com/dotnet/core-setup/pull/2483#discussion_r118116596. Opening an issue to track that it gets fixed.

@omajid wrote:
> Hey folks. I am a little confused. Over at #676, I was told:
>
> > we license the specific build that MSFT does [as non open source]
>
> The RPMs wrap that build, right? Shouldn't this have the proprietary license of the Microsoft-specific build? Or is that information out of date and the builds/RPMs are now going to be licensed under MIT?

@vivmishra wrote:
> @richlander can you comment on this?
>
> The implementation is similar to what we do .deb packages. The MIT license shows in the copyright file and when we display the rpm package information.

@omajid wrote:
> Thinking a bit more, even if this build is licensed under MIT, it should probably mention all licenses listed under the THIRD-PARTY-NOTICES.TXT and/or resources/ThirdPartyNotices.txt. I know that the License field in RPM based distributions can say things like MIT and BSD (Example) to indicate some parts are licensed under MIT and others under BSD. For .NET Core, I think some components are under Apache (ASL 2.0) as well?

**Comment by vivmishra** [comment]
cc @leecow

**Comment by rakeshsinghranchi** [comment]
@leecow - can you share more details on what is required here ? Also, please update the milestone accordingly.

**Comment by omajid** [comment]
Once https://github.com/dotnet/core-setup/pull/2635 and https://github.com/dotnet/cli/pull/6780 have been merged, most of my concerns in this issue will be resolved.

My only remaining request is updating the `License` field to match the actual licenses. MIT, BSD? Apache? and any other licenses that are getting included should be listed there.

**Comment by leecow** [comment]
@omajid - should the `License` field list all licenses (MIT, BSD, Apache v2, Microsoft) or is it acceptable practice to refer to an external document - thirdpartynotices.txt in this case.

**Comment by omajid** [comment]
@leecow the RPM convention is to list the exact licences as they apply to the RPM using [the short license names](https://fedoraproject.org/wiki/Licensing:Main). For example if part of the RPM is under Apache 2 and part is under MIT, the license field should say `ASL 2.0 and MIT` (meaning you must comply with both the licenses if you distribute the RPM).

The complete details for the license field for Fedora and RHEL RPMs is here: https://fedoraproject.org/wiki/Packaging:LicensingGuidelines

**Comment by leecow** [comment]
Thanks @omajid. 

@rakeshsinghranchi - The License: field for RPM and Deb packages need to updated to `MIT, ASL 2.0, BSD`.

**Comment by omajid** [comment]
Tiny nitpick: it should be `MIT and ASL 2.0 and BSD`. The `and` indicates that some part is under MIT, other parts are under ASL 2.0 and yet other parts are under BSD. So the combined result is limited by all 3.

(The other option would be `MIT or ASL 2.0 or BSD` which indicates that the entire .NET Core product is available under MIT or Apache 2.0 or BSD depending on which license the user prefers. One user can then choose to use/distribute all of .NET Core under MIT and another user can choose to use/distribute all of .NET Core under BSD. I believe is is not what the current license is)

**Comment by leecow** [comment]
Thanks @omajid. I believe 'and' will be the more correct formulation so we'll go with that.

**Comment by omajid** [comment]
No problem. Thanks for fixing this!

**Comment by wli3** [comment]
@leecow @omajid there is a full_text field for license, what it should be in this case?

https://github.com/dotnet/core-setup/blob/53771d8bfc8b19afbd45e5dbdcf727049d4f9231/src/pkg/packaging/rpm/dotnet-sharedhost-rpm_config.json#L31

**Comment by wli3** [comment]
This field will be the LICENSE TEXT in copyright

https://github.com/dotnet/core-setup/blob/6887ab556bc8302390782711dcdd75b75e769cf5/tools-local/setuptools/dotnet-deb-tool/tool/templates/debian/copyright

**Comment by vivmishra** [comment]
For RPM, the template is in its own location: 
https://github.com/dotnet/core-setup/blob/master/src/pkg/packaging/rpm/templates/copyright

**Comment by omajid** [comment]
RPMs don't actually have a full license text field. Any `LICENSE` or `COPYING` (or similar) files get packaged up and installed with the package, but the RPM metadata only includes the short license summary. For example:

    $ rpm -qi firefox | grep -i license
    License     : MPLv1.1 or GPLv2+ or LGPLv2+

In fact, the only license-like tag that RPM knows about packages is `LICENSE`:

    $ rpm --querytags | grep -i license
    LICENSE
    $ rpm -q --queryformat '%{LICENSE}\n' firefox
    MPLv1.1 or GPLv2+ or LGPLv2+
