### ISSUE TITLE
Runtime DEB package names are incorrect for 2.0

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#2588]
https://github.com/dotnet/core-setup/pull/2538/files (and the subsequent porting to release/2.0.0 https://github.com/dotnet/core-setup/pull/2537) changed the names of the DEB packages to include the `RID`.  This is conflicts with the design at https://github.com/dotnet/designs/issues/2.  See the `Linux installers` section, there is no RID in the package name.

We need to change these package names back to the way they were before.

Also - in order to unblock taking a new runtime in the SDK, I needed to change the SDK to accept these "bad" names.  See https://github.com/dotnet/cli/pull/6717/commits/f70959040275aac383d9c6a98df5b595360ab4ce.  That will need to be reverted once this is fixed.

**Comment by omajid** [comment]
That document also says:

>     [product]-[component]-[major].[minor].[patch]-[previewN]-[optional build #]-[rid].[file ext]
>
> Here are examples of this format:
>
>    #Ubuntu file set needed for the SDK
>    dotnet-hostfxr-2.0.4-ubuntu.16.04-x64.deb           # Host policy
>    dotnet-host-2.0.4-ubuntu.16.04-x64.deb              # Host / muxer

Looks like the document itself is ambiguous?

**Comment by eerhardt** [comment]
My reading is that is the name of the file.  We need unique file names for our different deb packages - `debian.8` vs. `ubuntu14`.

But when referencing the package through a package manager, we don't want the RID in the name.

**Comment by leecow** [comment]
Additional details and corrections added to [designs/issues/2](https://github.com/dotnet/designs/issues/2)

**Comment by karajas** [comment]
This is now merged. @eerhardt Do we need to now revert the cli change?
