### ISSUE TITLE
Pull in versioning logic from BuildTools to allow more than one build per-commit in Build Pipeline

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/core-setup#259]
We need to be able to have more than one build of core-setup per commit in the build pipeline - this involves bringing in versioning logic from buildtools.

CC @dagood @gkhanna79 @ramarag

**Comment by ramarag** [comment]
@gkhanna79 i am moving this to future

**Comment by dagood** [comment]
FYI @chcosta

**Comment by chcosta** [comment]
As part of my core-setup transition to BuildTools work, I'm updating the versioning to use the versioning logic from buildtools.  I still need to close on how to embed the MSI version based off of a BuildTools version string, but the rest of the work is largely done.

**Comment by chcosta** [comment]
This is resolved with the transition to buildtools.
