### ISSUE TITLE
Host should not lookup userprofile for resolving sdk

### ISSUE THREAD

**Issue by ramarag** [dotnet/core-setup#2597]
@eerhardt's  comments in https://github.com/dotnet/core-setup/pull/2393#issuecomment-302578638 seems to have fallen through cracks when changes for sdk lookup was made.
 
Sdk lookup probe still considers user profile
https://github.com/dotnet/core-setup/blob/master/src/corehost/cli/fxr/fx_muxer.cpp#L696
https://github.com/dotnet/core-setup/blob/release/2.0.0/src/corehost/cli/fxr/fx_muxer.cpp#L696

**Comment by ramarag** [comment]
cc @gkhanna79 @eerhardt

**Comment by Petermarcu** [comment]
@livarcocc , this needs to be addressed in the next few days.

**Comment by Petermarcu** [comment]
@johnbeisner as well

**Comment by leecow** [comment]
Ping @livarcocc

**Comment by johnbeisner** [comment]
Completed: https://github.com/dotnet/core-setup/pull/2627

**Comment by johnbeisner** [comment]
Duplicate issue of: https://github.com/dotnet/core-setup/issues/2624
