### ISSUE TITLE
[ARM32][PI Zero] Segment Fault - Published app not cli

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#2601]
_From @eByte23 on June 1, 2017 0:25_

## Steps to reproduce
install .net core 2.0 preview or lastest from master
```dotnet new console```
set RuntimeIdentifiers: win7-x64;win-arm;linux-arm

publish using ```dotnet publish -r linux-arm -c Release```
(note also debug has same issue)

copy published app to pi zero and run

## Expected  behavior
The app should output ```Hello World``` to console.

## Actual behavior
Segment Fault

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview2-006127)

Product Information:
 Version:            2.0.0-preview2-006127
 Commit SHA-1 hash:  946ea7980a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006127\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25319-02
  Build    : 7983b575ebcbdc3a825eea4b141ff7fb69d25f9d

_Copied from original issue: dotnet/cli#6726_

**Comment by livarcocc** [comment]
How are you running the app?

@eerhardt since this seems more like a runtime issue.

**Comment by livarcocc** [comment]
_From @eByte23 on June 1, 2017 3:48_

I have followed the steps outline here https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md

Basically just doing ```./HelloWorld```
Then it returns SegmentFault.

I have ran the exact same app on raspberry pi 2 and it runs successfully.

Could it have anything to do with Software Floating Point vs. Hardware Floating Point, as rpi zero is basically rpi 1 hardware

**Comment by livarcocc** [comment]
_From @melzoghbi on June 1, 2017 12:47_

Yes. This is exactly what i am facing as i posted in this thread: https://github.com/dotnet/core/issues/667
Thanks @eByte23 for connecting both issues.

**Comment by livarcocc** [comment]
Moving this issue to core-setup. I think they can triage it better. This seems like an issue in the runtime and not the tooling.

**Comment by Petermarcu** [comment]
Pi Zero is not supported. .net core requires armv7 and Pi Zero is armv6.

**Comment by Petermarcu** [comment]
I'm going to close this for now. At the point where we plan to bring up armv6, Pi Zero will become an option.
