### ISSUE TITLE
As a Core-Setup maintainer, I can merge two PRs within 20 minutes of each other without causing an official build break

### ISSUE THREAD

**Issue by maririos** [dotnet/core-setup#2655]
@dagood commented on [Mon Apr 17 2017](https://github.com/dotnet/core-eng/issues/675)

Currently the CI-triggered builds run in parallel, and the publish step that starts second doesn't wait long enough for the first publish to finish. It fails, instead. Product owners/maintainers/devs shouldn't need to think about this timing.

A few solutions:
 * Extend the "wait for other build to publish" timeout. Not scalable.
 * Have the later build "cancel" the earlier build's publish by communicating (cooperatively) through the storage account. Then, the later build publishes.
 * Only allow one build at a time.
   * We can do this by changing the PipeBuild to use the VSTS CI trigger, and "batch" commits to avoid getting overwhelmed by backlog.
   * We can make Maestro do this, but it would be a significant amount of new logic in the service.

Notes:
 * This only repros if both builds are successful and attempt to publish.
 * CLI doesn't have this problem because it doesn't use PipeBuild.
 * CoreFX/CoreCLR/WCF don't have the problem because they build on a schedule.

---

@dagood commented on [Tue Apr 18 2017](https://github.com/dotnet/core-eng/issues/675#issuecomment-294628355)

Related Core-Setup issues/PRs:
https://github.com/dotnet/core-setup/issues/2081 "Reduce occurences of build publishing race condition"
https://github.com/dotnet/core-setup/pull/2085 "Block build finalization to prevent race conditions"
https://github.com/dotnet/core-setup/pull/2091 "Try longer lease acquisition"

---

@Chrisboh commented on [Thu Apr 20 2017](https://github.com/dotnet/core-eng/issues/675#issuecomment-295892876)

@dagood Could you elaborate more on what the problem is here?  
- Why do two different builds have a problem publishing at the same time?  
- Aren't they different builds? 
- Are they going to the same place and if so why?

---

@dagood commented on [Thu Apr 20 2017](https://github.com/dotnet/core-eng/issues/675#issuecomment-295939936)

 * There is a `Latest` directory (one per channel/branch) that core-setup updates. The finalization step essentially has a mutex over the directory while it copies there. The later build waits on the earlier one to finish, but the publish takes longer to finish than the default mutex lock timeout.
 * Yes, they are different versions. (There is another problem if you merge two PRs even closer together (< 1 minute apart) that *would* result in the same commit being built twice, though, resulting in the same version. This is because both builds would check for the latest commit once they get started, and they would both see the same one. Ideally Maestro would pass in an absolute commit to build to the pipebuild. I don't think I've seen this tracked. I'll create an issue when I get back if nobody else does. I've only seen it once.)
 * This only applies to the blob storage location Latest dir. Other destinations are versioned so they don't need mutex to protect against overlaps.

**Comment by dagood** [comment]
This is fixed in master and release/2.0.0 by the move to buildtools, because Core-Setup now builds on a schedule. (This is effectively the "Only allow one build at a time." solution mentioned above.)

I believe this is still a problem in release/1.1.0 and release/1.0.0, and it might not be reasonable to fix this there.

**Comment by weshaggard** [comment]
Isn't it still a problem in master and release/2.0.0 if someone manually kicks off builds in the same timespan? I think it is still an issue there as well which should be handled.

**Comment by dagood** [comment]
Good point. This is only fixed for the specific scenario in the title, and only because merging PRs doesn't trigger builds.
