### ISSUE TITLE
Cannot find dotnet-runtime in ubuntu 14.04, 16.04 and debian 7 feed

### ISSUE THREAD

**Issue by wli3** [dotnet/core-setup#2657]
CLI/SDK release 2.0.0 current dependency _dotnet-runtime-2.0.0-preview2-25407-01_ cannot be found in the feed, so the install via apt-get for dotnet-sdk is blocked -- actually there is no new build after dotnet-runtime-2.0.0-preview2-25401-02.
https://apt-mo.trafficmanager.net/repos/dotnet/dists/jessie/main/binary-amd64/Packages
https://apt-mo.trafficmanager.net/repos/dotnet/dists/trusty/main/binary-amd64/Packages
https://apt-mo.trafficmanager.net/repos/dotnet/dists/xenial/main/binary-amd64/Packages

However, Ubuntu 16.10 is healthy
https://apt-mo.trafficmanager.net/repos/dotnet/dists/yakkety/main/binary-amd64/Packages

You can open the feed with notepad and search for "Package: dotnet-runtime-2.0.0-preview2-25407-01"

https://github.com/dotnet/cli/issues/6796

**Comment by rakeshsinghranchi** [comment]
cc @karajas

**Comment by karajas** [comment]
Looks like we've hit more feed issues
```
Aptly error. Status code: 500. Error message: undefined.
```

**Comment by livarcocc** [comment]
cc @Petermarcu as this may reset escrow.

**Comment by Petermarcu** [comment]
I would hope we can manually push things to the feeds.

**Comment by livarcocc** [comment]
Any update on this?

**Comment by karajas** [comment]
There's an email thread about Chuan investigating. I can ask him to push these packages manually to unblock you guys.

**Comment by leecow** [comment]
To this point we have always pushed the release packages manually so this should not reset escrow.

**Comment by wli3** [comment]
I do see packages in the feed now 

Package: dotnet-runtime-2.0.0-preview2-25407-01 in 
https://apt-mo.trafficmanager.net/repos/dotnet/dists/jessie/main/binary-amd64/Packages
https://apt-mo.trafficmanager.net/repos/dotnet/dists/trusty/main/binary-amd64/Packages
https://apt-mo.trafficmanager.net/repos/dotnet/dists/xenial/main/binary-amd64/Packages

So I am closing this specific issue
