### ISSUE TITLE
Language pack story for .NET Core apps

### ISSUE THREAD

**Issue by nguerrera** [dotnet/core-setup#2658]
If my .NET Core app is localized and I have satellite assemblies with the translations, I will often want to distribute the satellite assemblies separately from my main implementation assemblies. This saves disk space for users that don't need the other languages.

On .NET Core, this is problematic because my satellite assemblies need to be listed in my .deps.json. If they are on disk, but not listed, then they don't get used. If they are listed, but not on disk, my program fails. This means that unlike .NET Framework apps, a language pack installer cannot just lay down satellite assemblies in the right place, it also needs to update the deps.json somehow (and roll it back on language pack uninstall).

@gkhanna79 @Petermarcu @eerhardt @livarcocc I'm raising this in response to concerns about size-on-disk impact of satellite assemblies in .NET CLI. We likely don't have the runway to build language packs anyhow for 2.0, but with this situation, I'm not even sure how to make them work reliably.

**Comment by gkhanna79** [comment]
CC @steveharter as well.

**Comment by nguerrera** [comment]
Possible solution:

Add locale-specific deps to separate locale-specifc json:

```
MyApp.dll
MyApp.deps.json
   fr\
      MyApp.resources.dll
      MyApp.resources.deps.json
```

**Comment by gkhanna79** [comment]
I think that layout can be made to work if that is how the language installer will deploy and lay them out.

**Comment by gkhanna79** [comment]
Can there be a resources subfolder under which resources exist under IETF code subfolders? In the example above, "fr" would become "resources\fr".

Is that feasible?

**Comment by nguerrera** [comment]
That could work, but it goes against the .NET Framework tradition. I guess the problem is you wouldn't know which subfolders to scan?

**Comment by gkhanna79** [comment]
> I guess the problem is you wouldn't know which subfolders to scan?
Yes - unless we have a list somewhere that is always kept upto date.

**Comment by gkhanna79** [comment]
Can the language pack installer update the app's "runtimeconfig.json" by adding a property (e.g. resourceFolders) that is a delimited list of IETF codes? If so, the host can read that to augment the resource lookup.

**Comment by nguerrera** [comment]
The LP installer should not modify any files, just drop new ones. If you have to replace/edit/rollback files, you have a much more complicated problem on your hands. We should achieve the same experience as .NET Framework where locale dirs can be added and removed with no other steps required.

**Comment by gkhanna79** [comment]
Can the LP installer drop a "runtimeconfig.resources.json" with that information?

**Comment by nguerrera** [comment]
Two different LPs would fight over it. runtimeconfig.resources.[locale].json could work

**Comment by nguerrera** [comment]
But I still really prefer the simple experience of copy the "fr" directory to "fr" to deploy "fr" language pack. It is the same as the decade+-old tradition on .NET Framework. If the main runtimeconfig listed *possible* locales (i.e. it is not an error if locale in config is not present), then main installer could just declare all the LPs. This means I have to update main installer to support new languages, but that's not terrible.

**Comment by nguerrera** [comment]
Another solution: can the host consider the absence of  any assembly designated under "resources" section as optional? This would be the cheapest way to get the desired experience because there would be no changes needed to the tooling to generate config files any differently.

**Comment by gkhanna79** [comment]
Which resources section are you referring to? The one in app.deps.json?

**Comment by nguerrera** [comment]
Yes, that.

**Comment by gkhanna79** [comment]
And do you know all possible locales at the time app.deps.json is published?

**Comment by nguerrera** [comment]
I think that is the most common case. From my own experience at least, LPs are usually built and shipped on the same schedule as the main product. It would definitely work for .NET CLI. It's less versatile than the other solutions discussed, but I'm throwing it out there as something inexpensive that probably solves the problem in >90% of cases.

**Comment by gkhanna79** [comment]
I believe the goal behind the LP installer is to be able to drop resources that may not have been known at publish time of the app, right?

**Comment by nguerrera** [comment]
I believe that is secondary to the main goal is to prevent wasting disk space for languages the user will never use. E.g. The set of LPs for a given version of VS is known when VS ships, but we don't want to install them all on every machine.

**Comment by gkhanna79** [comment]
I think this should be doable for the next release.

**Comment by karelz** [comment]
Looks like blocker for 2.0 for CLI.

**Comment by steveharter** [comment]
Update: working on fix to not fail when a library that is listed in the .deps.json file is not required to be on disk.
