### ISSUE TITLE
dotnet-dev-1.0.4 package fails to install on Ubuntu

### ISSUE THREAD

**Issue by dnataraj** [dotnet/core-setup#2661]
I'm unable to install dotnet-dev-1.0.4 as explained here : https://www.microsoft.com/net/core#linuxubuntu
on Ubuntu 16.04.2.

## Steps to reproduce
sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ yakkety main" > /etc/apt/sources.list.d/dotnetdev.list'
 sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
sudo apt-get update
sudo apt-get install dotnet-dev-1.0.4

## Expected  behavior
dotnet-dev-1.0.4 package installs

## Actual behavior
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-dev-1.0.4 : Depends: libstdc++6 (>= 6) but 5.4.0-6ubuntu1~16.04.4 is to be installed
                    Depends: dotnet-sharedframework-microsoft.netcore.app-1.1.2 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

## Environment data
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

**Comment by dnataraj** [comment]
If I try to install the dependencies separately, I get 

The following packages have unmet dependencies:
 dotnet-dev-1.0.4 : Depends: libstdc++6 (>= 6) but 5.4.0-6ubuntu1~16.04.4 is to be installed
                    Depends: dotnet-sharedframework-microsoft.netcore.app-1.1.2 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

The following packages have unmet dependencies:
 dotnet-sharedframework-microsoft.netcore.app-1.1.2 : Depends: libgssapi-krb5-2 (>= 1.14+dfsg) but 1.13.2+dfsg-5ubuntu2 is to be installed
                                                      Depends: libicu57 (>= 57.1-1~) but it is not installable
                                                      Depends: libstdc++6 (>= 6) but 5.4.0-6ubuntu1~16.04.4 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by livarcocc** [comment]
Dup of https://github.com/dotnet/core-setup/issues/2657 and https://github.com/dotnet/cli/issues/6796.
