### ISSUE TITLE
Homepage referenced in deb metadata is incorrect

### ISSUE THREAD

**Issue by leecow** [dotnet/core-setup#2682]
https://apt-mo.trafficmanager.net/repos/dotnet/dists/jessie/main/binary-amd64/Packages
https://apt-mo.trafficmanager.net/repos/dotnet/dists/trusty/main/binary-amd64/Packages
https://apt-mo.trafficmanager.net/repos/dotnet/dists/xenial/main/binary-amd64/Packages
https://apt-mo.trafficmanager.net/repos/dotnet/dists/yakkety/main/binary-amd64/Packages

All packages have `Homepage: https://dotnet.github.io/core`. 

URL should be `https://dotnet.github.io`

**Comment by rakeshsinghranchi** [comment]
Fixed by this PR : https://github.com/dotnet/core-setup/pull/2683
