### ISSUE TITLE
Uninstalling all versions of .NET Core SDK and runtime leaves files behind

### ISSUE THREAD

**Issue by nguerrera** [dotnet/core-setup#2697]
_From @nguerrera on June 16, 2017 0:19_

I've uninstalled everything and still have the following on disk:

```
C:\Program Files\dotnet\host
C:\Program Files\dotnet\dotnet.exe
C:\Program Files\dotnet\LICENSE.txt
C:\Program Files\dotnet\ThirdPartyNotices.txt
C:\Program Files\dotnet\host\fxr
C:\Program Files\dotnet\host\fxr\1.1.0
C:\Program Files\dotnet\host\fxr\1.1.0\hostfxr.dll
```

I know these are shared between versions, but is there no ref counting system to remove them when the last installation using them is removed?

_Copied from original issue: dotnet/cli#6899_

**Comment by nguerrera** [comment]
_From @livarcocc on June 16, 2017 1:33_

Please, move this to core-setup. These are all host files.

**Comment by rakeshsinghranchi** [comment]
@nguerrera , there was a refcounting bug in 1.1.0 and 1.0.0 that we fixed in 2.0.0 and 1.x servicing branches. Please share MSI logs %temp% to further diagnose the issue.

**Comment by nguerrera** [comment]
I see. Some of the builds I uninstalled were older 1.x. That is probably what bit me here. I'll try to locate the logs.

Can this bug in older 1.x ever bite the other way -- with dotnet.exe being removed even though there are still sdks/runtimes installed? I ask because that would explain an issue that bit @davkean, which I was trying to reproduce when I hit this opposite problem.

**Comment by rakeshsinghranchi** [comment]
yes, 1.x has caused side by side issue with later version of framework as well.

**Comment by dagood** [comment]
Closing as stale: 1.x is no longer supported.
