### ISSUE TITLE
Doing a build-to-build upgrade of Visual Studio, breaks dotnet

### ISSUE THREAD

**Issue by davkean** [dotnet/core-setup#2707]
## Steps to reproduce
1. Install 15.3.0-pre.3.0+26615.5.d15prerel
2. Using build-to-build upgrade, upgrade to 15.3.0-pre.3.0+26618.0.d15prerel
3. Open Visual Studio Command Prompt,
4. Run `dotnet`

## Expected  behavior
For dotnet to run

## Actual behavior
`A fatal error occurred, the required library hostfxr.dll could not be found at C:\Program Files\dotnet`

## Environment data

Make note, other things also appear to be broken such as the Web SDK cannot be found. I'm going to file another bug on that.

Here is the list of files that I have under Program Files\dotnet:
[files.txt](https://github.com/dotnet/core-setup/files/1086644/files.txt)

Please tell me what setup logs you'd like, I can see no setup logs related to .NET Core SDK or anything from the build-to-build upgrade.

**Comment by rakeshsinghranchi** [comment]
@davkean , can you collect & share setup logs using collect tool : https://www.microsoft.com/en-us/download/details.aspx?id=12493

**Comment by davkean** [comment]
I've uploaded the logs on scratch2 under davkean\core-setup\2707.

**Comment by rakeshsinghranchi** [comment]
Fixes have been ported to  1.0. and 1.1
https://github.com/dotnet/core-setup/issues/1645
https://github.com/dotnet/core-setup/issues/1646
