### ISSUE TITLE
Build definition work to disable external publish via orchestrating PipeBuild definition

### ISSUE THREAD

**Issue by MattGal** [dotnet/core-setup#2709]
Related: https://github.com/dotnet/core-eng/issues/626

This was informed by the MSRC work, where being able to selectively disable publish steps for all builds in the composed product was necessary.

I did some work to allow disabling any given Pipebuild leg with the -d arg (e.g. “-d "Regex:^Publish.*"”) but @dagood points out that there’s more to be done there since some repositories do things that need to be disabled in nearly every leg of their build.

This issue tracks doing build definition refactoring work to factor functionality that needs to be optionally turned off out.  There’s probably many ways to actually get this work done, but I’d suggest one of two:

 - Factor the optional behavior into independent pipelines (as defined by the pipelines.json for this repo) and disable them for servicing PIpebuild definitions as noted above
 - Establish Boolean properties that disable all undesirable behavior (publishing to feeds, etc) and set these properties in the -g section of the PipeBuild definition used.

In both cases this work needs to be done in the repository using it, not in Pipebuild or other Engineering Services code.  

In Core-Setup, you can't disable the correct parts of publishing by disabling entire legs. Each leg publishes directly to the output container, and the publish leg also does some blob rearranging (copying to Latest) that downstream products depend on. For Core-Setup to not publish MSRC-compatibly, it needs to use a different storage container and selectively stop publishing packages, installers, and dotnet/versions commits.

**Comment by weshaggard** [comment]
This is enabled in the master branches but still need to enable something similar in the release branches.

**Comment by dagood** [comment]
Closing as stale, no longer applicable to recent builds.
