### ISSUE TITLE
No package dotnet-runtime-2.0.0-preview3-25420-01 in Debian 8 and Ubuntu 16.10 feed

### ISSUE THREAD

**Issue by wli3** [dotnet/core-setup#2715]
in the feed 

https://apt-mo.trafficmanager.net/repos/dotnet/dists/jessie/main/binary-amd64/
https://apt-mo.trafficmanager.net/repos/dotnet/dists/yakkety/main/binary-amd64/

**Comment by wli3** [comment]
Seems the root cause of this has not been resolved https://github.com/dotnet/core-setup/issues/2657

**Comment by rakeshsinghranchi** [comment]
@wli3 are you still blocked on this ?

**Comment by wli3** [comment]
Did you change the upload method? Or do you have stable upload now? You can close it for the specific issue, but i am afraid will be come back again if root cause is not solved, like in CLI repo.

We are using the same way of uploading to apt-cat, and there is a bug for them to download(file is corrupted every now and then) from blob after we send the url of in the blob. So either a check sum mechanism is required or we directly upload the file.

**Comment by weshaggard** [comment]
We no longer plan to publish our dailies to the external package managers.
