### ISSUE TITLE
Re-enable WCF maestro updates once their packages build against the new corefx

### ISSUE THREAD

**Issue by joperezr** [dotnet/core-setup#2743]
per comment https://github.com/dotnet/core-setup/pull/2686#issuecomment-310795492:
>  Seems like System.Private.ServiceModel is now trying to pull in a version of System.Runtime.WindowsRuntime package that doesn't support uap. That is wrong, the new System.Private.ServiceModel shouldn't have a dependency to WindowsRuntime since that now lives on the Corefx private package for uap.

This issue will track the required work of re-enabling the WCF updates once they are building against the new corefx. cc: @zhenlan @shmao @dagood

**Comment by zhenlan** [comment]
The likely reason is that current S.P.SM package carries a harvested UWP binary that was built for netcore50.

@dagood and @StephenBonikowsky are working on building updated S.P.SM package that supports UWP/NS2.0.
