### ISSUE TITLE
Upgrading PlatformAbstractions dependencies causes test error: "Could not load file or assembly 'System.IO.FileSystem..."

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#275]
## Steps to reproduce
 1. Upgrade dependencies in `src\Microsoft.DotNet.PlatformAbstractions\project.json` to above 1.0.0 RTM. (Or check out dagood:repro-update then rebase on release/1.1.0 to avoid unrelated errors.)
 2. Build, running tests.

## Behavior
Get the following error when running `HostActivationTests`:
```
[EXEC       >] [....] [00:04:53.421] C:\git\core-setup\.dotnet_stage0\Windows\x64\dotnet.exe "test" "--configuration" "Debug" "-xml" "HostActivationTests-testResults.xml" "-notrait" "category=failing"
Project Microsoft.DotNet.PlatformAbstractions (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Microsoft.Extensions.DependencyModel (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project TestUtils (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Project HostActivationTests (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.LoadEntryAssemblyContext(IDependencyContextReader reader)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContext.Load(Assembly assembly)
   at Xunit.Runner.DotNet.Program.GetAvailableRunnerReporters()
   at Xunit.Runner.DotNet.Program.Run(String[] args)
   at Xunit.Runner.DotNet.Program.Main(String[] args)
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.
```
Same for `Microsoft.Extensions.DependencyModel.Tests`.

See https://github.com/dotnet/core-setup/pull/267.

## Current understanding
When restoring/building `test` projects, the [Microsoft.Extensions.DependencyModel.Tests project.json](https://github.com/dotnet/core-setup/blob/26b63a4c46f6a3d1ff3bdeeb57e56683a8a4b5e7/test/Microsoft.Extensions.DependencyModel.Tests/project.json#L23)
 contains the dependency chain

 * dotnet-test-xunit
   * Microsoft.Extensions.Testing.Abstractions
      * Microsoft.DotNet.ProjectModel
         * Microsoft.Extensions.DependencyModel
            * Microsoft.DotNet.PlatformAbstractions

Due to [`global.json`](https://github.com/dotnet/core-setup/blob/26b63a4c46f6a3d1ff3bdeeb57e56683a8a4b5e7/global.json), `DependencyModel` and `PlatformAbstractions` are picked up as p2p references in `src`. When the RTM 1.0.0 shared framework is used to start the tests, some dependency resolution logic doesn't work right.

**Comment by gkhanna79** [comment]
As discussed yesterday, I have marked this bug blocking both release and servicing. We need to get a resolution for this at the earliest and consider taking those fixes to release/1.0.0 servicing branch as well. When ready to do so, please coordinate with @wtgodbe and me.

CC @leecow @livarcocc @piotrpMSFT @eerhardt @weshaggard

**Comment by brthor** [comment]
My suspicion here based on conversation yesterday was that the DependencyContextLoader is merging sharedfx and app deps.json incorrectly. 

@livarcocc Said he will take a look at this later today.

**Comment by gkhanna79** [comment]
@brthor @livarcocc Are you tracking fixing this for 1.1.0 RTM and 1.0.2 (upcoming)?

**Comment by gkhanna79** [comment]
@piotrpMSFT @livarcocc Please take a look at this ASAP for 1.1.0.

**Comment by livarcocc** [comment]
Given that your only dependency in the test is to test utils, could you try adding a global.json to it so that it does not look for projects under src, so that the new PlatformAbstraction is not picked up?

**Comment by dagood** [comment]
My understanding is the tests need the P2P reference because the point is to test the `PlatformAbstractions` project: https://github.com/dotnet/core-setup/blob/26b63a4c46f6a3d1ff3bdeeb57e56683a8a4b5e7/test/Microsoft.Extensions.DependencyModel.Tests/project.json#L16-L18.

**Comment by piotrpMSFT** [comment]
Why are we moving PlatformAbstractions to 1.1.0? Is there a new feature dependency?

**Comment by gkhanna79** [comment]
It is less about feature dependency but more about being in current with the set of dependencies that will come with new versions from CoreFX for a given release to test the component works well with them.

**Comment by gkhanna79** [comment]
@piotrpMSFT @livarcocc What are the next steps for this?

**Comment by piotrpMSFT** [comment]
To test the component working with newer dependencies please reference it from a test project which references the newer version. We don't see a benefit to customers or the team for bumping the dependencies of this package.

**Comment by dagood** [comment]
@piotrpMSFT My impression from when this was discussed at the beginning is that we don't necessarily want to upgrade these now, but this potentially DependencyContextLoader bug is being exposed by the upgrade and it prevents us from upgrading the packages' dependencies should we need to at any point in the future.
