### ISSUE TITLE
Cannot run dotnet.exe on Windows 7

### ISSUE THREAD

**Issue by wli3** [dotnet/core-setup#2759]
## Steps to reproduce
VM with clean image en_windows_7_professional_x64_dvd_x15-65805.iso from MSDN

Install the latest CLI build depends on runtime 2.0.0-preview3-25426-01
## Actual behavior
![image](https://user-images.githubusercontent.com/6993335/27707694-15157d10-5ccb-11e7-8a06-4c20857f5358.png)

## Environment data

Looks like an error due to the lack of vcredist_x64.exe however I remember we get rid of the dependency of it
https://stackoverflow.com/questions/33265663/api-ms-win-crt-runtime-l1-1-0-dll-is-missing-when-opening-microsoft-office-file

**Comment by wli3** [comment]
@Petermarcu I remember you talked about this

**Comment by Petermarcu** [comment]
Correct, we shouldn't have a vcredist dependency. @steveharter can you take a look?

**Comment by Petermarcu** [comment]
Ah,. @gkhanna79 can probably help confirm but I believe we do require that the uCRT is installed on Win7 and its delivered through Windows update. 

https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows

I think this is by design.

**Comment by gkhanna79** [comment]
Yes, that is correct.

**Comment by wli3** [comment]
I see, let me update first

**Comment by wli3** [comment]
More to this, the patch for uCRT requires SP1 of Windows 7.

**Comment by steveharter** [comment]
FWIW here's the full list of configurations for uCRT (from the link above):
    Windows Server 2012 R2
    Windows 8.1
    Windows RT 8.1
    Windows Server 2012
    Windows 8
    Windows RT
    Windows Server 2008 R2 Service Pack 1 (SP1)
    Windows 7 SP1
    Windows Server 2008 Service Pack 2 (SP2)
    Windows Vista SP2
