### ISSUE TITLE
Install  .NET Core  failed  

### ISSUE THREAD

**Issue by Innocence** [dotnet/core-setup#276]
Setup Failed

One or more issues caused the setup to fail.Please fix the issues and then retry setup.
For more information see the log file.

**Comment by mellinoe** [comment]
There isn't enough information here for us to help you. Could you provide some of the following?

* Operating system type, version, etc.
* Which installer you used
* What the logs mentioned contain

**Comment by gkhanna79** [comment]
@Innocence Are there more details you can share with any recent builds where this repros?

**Comment by gkhanna79** [comment]
@Innocence For the lack of repro details, I am closing this issue for now. Please feel free to reopen once you have repro details.
