### ISSUE TITLE
"latest.version" should be a semaphore for packages existing on MyGet

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#2765]
ASP.NET depends on this file changing only when packages are on MyGet, but because `FinalizeBuildInAzure` happens before `PublishCoreHostPackagesToFeed` (https://github.com/dotnet/core-setup/blob/bd3f818bad84f1296b4ee53f72ab8837b3caac98/publish/publish.proj#L14) package publishing can fail after the file update. I think those two targets can just be swapped. @chcosta

**Comment by chcosta** [comment]
I don't see any concern with swapping those.

**Comment by dagood** [comment]
Fixed in #2766 (master) #2787 (release/2.0.0)
