### ISSUE TITLE
Builds should publish checksums for artifacts

### ISSUE THREAD

**Issue by naamunds** [dotnet/core-setup#279]
The core-setup builds should be producing SHA hashes for the various artifacts that customers would download on their machine. This will allow them to do checksum verification to ensure MITM has not occurred. 

This is needed for the [.NET Dockerfiles](https://github.com/dotnet/dotnet-docker) as it is part of the criteria for making the .NET images official Docker images.

This issue corresponds to https://github.com/dotnet/cli/issues/3693.

**Comment by gkhanna79** [comment]
@naamunds Are you driving this for 2.0?

**Comment by gkhanna79** [comment]
CC @dleeapho

**Comment by naamunds** [comment]
I had been waiting for core-setup to adopt the MSBuild build infrastructure like CLI, but my understanding is that this work may no longer be needed for Docker (which was the primary driver), which de-prioritized it.

/cc @dleeapho and @MichaelSimons for comment on the current priority of this work.

**Comment by MichaelSimons** [comment]
This is still something we would like to have for our Dockerfiles.  It is part of Docker's [criteria for making official images](https://github.com/docker-library/official-images#security).

**Comment by naamunds** [comment]
@gkhanna79 Who would you like this issue to be assigned to?

**Comment by gkhanna79** [comment]
Is there BuildTools support to generate the checksums and persist them?

**Comment by naamunds** [comment]
@gkhanna79 No; I added this logic directly to CLI in https://github.com/dotnet/cli/pull/4191.

**Comment by gkhanna79** [comment]
But if we are going to move to BuildTools based build, why does not this logic exist there for the repos to consume?

**Comment by naamunds** [comment]
@dleeapho What do you think about moving the checksum generation logic to BuildTools? I think it might make sense, so it could be utilized by multiple dotnet repos.

**Comment by dleeapho** [comment]
Makes sense, we should move the checksum and persistence logic out of CLI into BuildTools to share it across CLI and Core-Setup. Logged the issue [https://github.com/dotnet/core-eng/issues/497](https://github.com/dotnet/core-eng/issues/497)

**Comment by danmosemsft** [comment]
@dleeapho @dagood @chcosta who is the appropriate owner for this one? to drive this for ZBB.
cc @gkhanna79

**Comment by dleeapho** [comment]
@gkhanna79 I don't think @dagood or @chcosta has bandwidth. Anyone from your team?

**Comment by chcosta** [comment]
I'm not an expert in this area, but I can try to pick this up later this week if there are no other resources.  It looks like it's mostly porting work.  It'd be great if @MichaelSimons had a few cycles to validate the docker side of this once it's ready.

**Comment by karajas** [comment]
https://github.com/dotnet/core-setup/pull/2368

**Comment by karajas** [comment]
This is now creating checksums in the new layout.

**Comment by leecow** [comment]
@karajas - I have been hand-rolling checksums to this point for official releases ([see the 2.1 Preview dl page](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-preview1-download.md) and the [checksum file](https://dotnetcli.blob.core.windows.net/dotnet/checksums/2.0.0-preview1-sharedfx-sha.txt)). 

I presume your implementation will drop a single checksum file per artifact?

**Comment by karajas** [comment]
@leecow yes there is one for each installer and tar/zip file

**Comment by karajas** [comment]
These also follow the new layout for core-setup that is similar to how the sdk repo storage is set up

**Comment by eerhardt** [comment]
@karajas - I think the only thing left for this work item is to update the README.  Can you add the checksum links to the REAMDE?

**Comment by karajas** [comment]
@eerhardt Should the link for a latest checksum exist? I don't think we have that in yet. We only have links to each build number.

**Comment by gkhanna79** [comment]
If you are going to fix the README, can you also fix https://github.com/dotnet/core-setup/issues/2262 that is currently assigned to @Petermarcu ?

**Comment by karajas** [comment]
@gkhanna79 Sure, do we want links for 2.0.0-preview1?

**Comment by gkhanna79** [comment]
I think we want links to whatever corresponds to release/2.0.0 (which will be preview2 payload).

**Comment by eerhardt** [comment]
> Should the link for a latest checksum exist? I don't think we have that in yet. We only have links to each build number.

@karajas - You said you would follow up on this here:  https://github.com/dotnet/core-setup/pull/2368#discussion_r116615339

**Comment by gkhanna79** [comment]
Fix in https://github.com/dotnet/core-setup/pull/2471.

@karajas When can the PR be merged?

**Comment by karajas** [comment]
Merged.
