### ISSUE TITLE
Failed to initialize CoreCLR, HRESULT: 0x80004005

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#2808]
_From @Miclebrick on June 27, 2017 5:45_

## Steps to reproduce
1. Install dotnet
2. mkdir test
3. cd test
4. dotnet new mvc
5. dotnet restore
6. dotnet run

## Expected  behavior
Running of something

## Actual behavior
I merely get the error in the title.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.4

_Copied from original issue: dotnet/cli#7007_

**Comment by livarcocc** [comment]
How did you install dotnet? also, can you set COREHOST_TRACE=1 and invoke dotnet run again and share the log file with us.

@karelz This is the host crashing. Can you help take a look?

**Comment by livarcocc** [comment]
@Petermarcu @steveharter can you guys help take a look?

**Comment by livarcocc** [comment]
_From @karelz on June 30, 2017 17:40_

@steveharter is the right person to look at it.

**Comment by livarcocc** [comment]
_From @Petermarcu on June 30, 2017 19:0_

@Miclebrick , how did you install? Did you use the zip or apt-get?

**Comment by livarcocc** [comment]
_From @Miclebrick on July 4, 2017 22:50_

apt-get - Although I ended up just renting a SmarterASP server

**Comment by livarcocc** [comment]
Moving this issue to core-setup for now, if this turns out to be an SDK problem, please re-activate.

**Comment by steveharter** [comment]
I have success on local Ubuntu 16.04 following these instructions: https://www.microsoft.com/net/core#linuxubuntu.

@Miclebrick can you run `dotnet new console` and see if that works (to minimize dependencies). Usually the 0x80004005 is a result of a missing dependency. Thanks

**Comment by araqieldev** [comment]
But when you create a new project with ```dotnet new mvc```, you've got the previous error **Failed to initialize CoreCLR, HRESULT: 0x80004005**.
So, not resolved.

**Comment by steveharter** [comment]
@araqieldev do you also have the same issue?

I'll try with a clean Ubuntu 16.04 image and see if I can repro; previously I had a manually configured Ubuntu 16.04 for dev work and that worked with mvc.

**Comment by araqieldev** [comment]
Exactly the same issue. Sometimes the command `dotnet run` works (once in ten). And when it works if I try to reach the web site, I have a big error stack trace.This morning I uninstalled dotnet 1.0.4 for 2.0.0 preview 2. I haven't this problem in 2.0.0.

**Comment by steveharter** [comment]
Even with a clean install of Ubuntu, I am still unable to repro this. Here's what I did:
1) Using Hyper-V on Windows Server 2012 R2
2) Install new version of Ubuntu 16.04. Added a superuser account via the install wizard
3) Apply all updates
4) From a terminal window run this (required for access via PuTTY): sudo apt-get install openssh-server openssh-client
5) Connect via PuTTY using the user created in step 2
6) Follow the instructions in https://www.microsoft.com/net/core#linuxubuntu for 16.04
7) Follow the original repro steps above 2-6

I tried `dotnet run` a few times, and it was always successful.

@araqieldev how are my steps different from yours? Are you also using SmarterASP server like @Miclebrick?

**Comment by araqieldev** [comment]
I think that's because my server known Ubuntu 14 and 15, now 16.04.
The command `dotnet run` work perfectly for new console project. I think is the Kestrel server has dependencies not work because I haven't a clean installation of Ubuntu.
But in **dotnet 2.0 preview 2** I haven't this problem even MVC project.

**Comment by steveharter** [comment]
I am closing this until I can get a repro. These are likely non-standard \ private distros that perhaps have different versions for some components or missing dependencies. If I can get an actionable repro I will re-open. Thanks.

**Comment by drwigglechin** [comment]
Hey guys, I was running into this same issue and found the problem to be including the package reference 'SharpZipLib.NETStandard' version '0.86.0.1'.

**Comment by redknightlois** [comment]
I had been having this issue too. I removed CoreCLR entirely (also deleted coreclr and nuget cached packages) and was able to repro on a clean install.

Install SDK 2.1.104 (x64)
Run ```dotnet --version``` it should return: ```2.1.104```
Install SDK 2.1.300-preview3-008443
Run ```dotnet --version``` it will fail with ```Failed to initialize CoreCLR, HRESULT: 0x80004005```

**Comment by karelz** [comment]
Given this is ancient issue, I would recommend to create a new tracking bug.
Do you have download links you used? That might speed up things.

**Comment by redknightlois** [comment]
Sure, let me pull them up. Will create a new one

**Comment by bdaniel7** [comment]
Hi,

I'm trying to run a TeamCity agent in a container.
This is environment:

root@teamcity-agent3:/opt/buildagent/work/70bf5e8b1cc61bbe/src# dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.401/

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

When I run the build command

`/opt/buildagent/work/70bf5e8b1cc61bbe/src# /usr/bin/dotnet build trains.sln --framework netcoreapp2.1 --configuration Release --runtime ubuntu-x64`

the build is successful.

However when I run the same command as part of a build step, I get this error:

> Failed to initialize CoreCLR, HRESULT: 0x80004005

**Comment by dohnuts** [comment]
> I am closing this until I can get a repro. These are likely non-standard \ private distros that perhaps have different versions for some components or missing dependencies. If I can get an actionable repro I will re-open. Thanks.

FYI : lower ulimit -l, same error

the requirement are quite high and higher than before

USERDONET hard    as      2097152

is not enough ! to start !
