### ISSUE TITLE
Debian stretch packages?

### ISSUE THREAD

**Issue by jleclanche** [dotnet/core-setup#2811]
Are there packages for debian stretch?

The [official debian instructions](https://www.microsoft.com/net/core#linuxdebian) don't work [because of issues with dependencies](https://github.com/dotnet/cli/issues/2018#issuecomment-239301891) and the packages in this repo can't be installed for similar reasons.

**Comment by atlemagnussen** [comment]
I'm also looking for this.

**Comment by Petermarcu** [comment]
Are you using 1.1 or 2.0? For 2.0, you can use the linux-x64 packages. We'll have to get all the dependencies instructions updated.

**Comment by Petermarcu** [comment]
You can see the correct dependencies in our dockerfile here: https://github.com/dotnet/dotnet-docker/blob/master/2.0/runtime-deps/stretch/Dockerfile

**Comment by Petermarcu** [comment]
@leecow @rakeshsinghranchi have you verified our deb's on stretch?

**Comment by jleclanche** [comment]
The 2.0 debs definitely error on stretch.

**Comment by Petermarcu** [comment]
Yeah, I'm searching for Debian 9 debs on build shared to see if they were ever turned on. @rakeshsinghranchi , can you get a PR  up to enable Debian 9 debs?

**Comment by steveharter** [comment]
@leecow can you provide an update on this please (Cleaning up 2.0.0 issues)? I have reported local success with Buster.

**Comment by leecow** [comment]
The azlinux production feed was signed with the wrong cert. This was fixed yesterday and I've confirmed our feed is working on Deb9. I'll be updating the getting started guides to use the following:

1. `curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg`
1. `sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg`
1. `sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod" > /etc/apt/sources.list.d/dotnetdev.list'`
1. `sudo apt-get update`

`apt search dotnet` if you just want to check that the local package db was update and `sudo apt-get install dotnet-sdk-2.0.0` to install.

**Comment by newton-jose** [comment]
HI people. I'm getting this error after "apt-get update":
 Err:17 https://packages.microsoft.com/debian/9/prod stretch Release
  gnutls_handshake() failed: Public key signature verification has failed.

How solve it? I'm using Debian 9 and follow the instructions from: 
https://www.microsoft.com/net/learn/dotnet/hello-world-tutorial#linuxdebian

Thanks in advance.
