### ISSUE TITLE
Wrong error message when shared framework version is not found

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/core-setup#2845]
## Steps to reproduce
Create a console app for a 2.0.0 runtime that is not installed.
`dotnet myapp.dll`

## Expected  behavior
Show an error message that lists
 1. Which versions of the shared framework are instaleld
 2. Where to install a new shared framework

## Actual behavior
The error message always lists `\` as the place where folder where shared runtimes should be installed.
```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.0.0-xylophone' was not found.
  - Check application dependencies and target a framework version installed at:
      \
  - Alternatively, install the framework version '2.0.0-xylophone'.
```
## Environment data

```
.NET Command Line Tools (2.0.0-preview3-006770)

Product Information:
 Version:            2.0.0-preview3-006770
 Commit SHA-1 hash:  78e7163819

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\namc\.dotnet\x64\sdk\2.0.0-preview3-006770\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25516-01
  Build    : 1b047a04057cec973cfb890fd21f7a639cfcd118
```

cc @glennc

**Comment by steveharter** [comment]
I assume the expected behavior is to output the location of the current dotnet.exe like this:
```
- Check application dependencies and target a framework version installed at:
    c:\Program Files\dotnet\
```

Also from looking at the source code, with `COREHOST_TRACE=1` it should list installed versions but doesn't due to likely bug in fx_muxer.cpp.
