### ISSUE TITLE
What version of dotnet am I running?

### ISSUE THREAD

**Issue by Rovastar** [dotnet/core-setup#2855]
I believe I installed (under windows server 2012r2) the asp.net 1.1.2 runtime correctly. Latest build, never installed previous versions, add remove programs say 1.1.2 and all references under the install direct have 1.0.5 or 1.1.2

However the C:\Program Files\dotnet\dotnet.exe properties do not reflect this at all. The file version there is 1.1.0.1179

What version do I have installed? Is it just a bug and the file info has not been updated or do I misunderstand what the file version is in the exe?

**Comment by omajid** [comment]
See https://github.com/dotnet/cli/issues/3773 and https://stackoverflow.com/documentation/.net-core/9592/components-and-versioning-in-net-core/29628/identifying-versions#t=201707242256041962641

**Comment by steveharter** [comment]
`dotnet --info` will tell you which framework is selected via the dotnet executable.

The C:\Program Files\dotnet\shared locations will tell you which frameworks (should just be Microsoft.NetCore.App) and versions are installed. The settings in an app's <app>.runtimeconfig.json will tell you the framework name and base version that is targeted.
