### ISSUE TITLE
Roll forward on Minor version when exact match isn't present

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#2862]
We need to document the details but in general, we'd like 2.0 applications to attempt to run on 2.1 if 2.0 isn't present. There isn't a 100% guarantee they will run but rather than blocking it, we'd like to let apps try to run potentially with a warning and then if they don't work, they know they have to have exactly 2.0 installed.

Doc here: https://github.com/dotnet/designs/issues/3

**Comment by nzain** [comment]
What is the current state - is a perfect version match required (major.minor.build.rev)? If I remember correctly, I was working with slightly different versions (2.0.0-preview 1..2..3) and they were compatible, but I don't remember the exact version numbers (it worked, I didn't care). In #3072 we experience incompatibility (2.0.0 and 2.0.1) and the error message indicates versioning as a reason.

Furthermore, there is a CLI-version (irrelevant, I guess), a host-version, and sometimes a "product" version. Could you clarify, which one is critical. On linux-arm the `dotnet --info` cmd only returns the host version.

**Comment by steveharter** [comment]
Closing this and combined it with new issue #3469
