### ISSUE TITLE
Invalid uid:guid for instaled binaries

### ISSUE THREAD

**Issue by nick4u** [dotnet/core-setup#2868]
Instalation puts new files in /opt with hard coded uid:gui
## clean install at debian 8 
```
sudo apt-get install curl libunwind8 gettext
curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?linkid=848826
sudo mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet
sudo ln -s /opt/dotnet/dotnet /usr/local/bin

```
## Expected  behavior
owner of /opt/dotnet should be root:staff or something other reasonable?

## Actual behavior
```
# ls -ln /opt/dotnet/
total 172
-rwxr-xr-x 1 1002 27 139184 cze 16  2016 dotnet
drwxr-xr-x 3 1002 27   4096 maj  5 00:51 host
-rw-r--r-- 1 1002 27   9410 kwi 21 00:50 LICENSE.txt
drwxr-xr-x 3 1002 27   4096 maj  5 00:51 sdk
drwxr-xr-x 3 1002 27   4096 maj  5 00:51 shared
-rw-r--r-- 1 1002 27   8103 kwi 21 00:50 ThirdPartyNotices.txt
```
group gid=27 maps to sudo ....

## Environment data
```
# lsb_release -d
Description:	Debian GNU/Linux 8.8 (jessie)
```

**Comment by rakeshsinghranchi** [comment]
cc @leecow , do you have context on this ? This is related to 1.0.4 package.

**Comment by leecow** [comment]
tar install instructions were updated in August so all of the above observations should be resolved. See https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.10-download.md#installation-from-a-binary-archive for the latest.
