### ISSUE TITLE
Core-setup requires Windows SDK to be on the machine

### ISSUE THREAD

**Issue by maririos** [dotnet/core-setup#2876]
@karajas commented on [Tue Jul 18 2017](https://github.com/dotnet/core-eng/issues/1249)

Core-setup now builds the uwpshim and requires onecore.lib which is a part of the Windows SDK.

Our build machines have this dependency installed on them currently. 
/cc @shawnro 

---

@karajas commented on [Tue Jul 18 2017](https://github.com/dotnet/core-eng/issues/1249#issuecomment-316220646)

According to @weshaggard, we should look into removing this dependency as it may no longer be required.

**Comment by steveharter** [comment]
@nattress PTAL

**Comment by nattress** [comment]
This can be closed. We don't build uwpshim in this branch anymore.
