### ISSUE TITLE
Problem on Debian Buster (Testing)

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#2943]
_From @matiux on July 30, 2017 21:11_

When I run `dotnet new console -o hwapp` on Debian Buster (Debian Tetsing) I get this:

```
Getting ready...
Segmentation fault
```

$dotnet --info

.NET Command Line Tools (2.0.0-preview2-006391)

Product Information:
 Version:            2.0.0-preview2-006391
 Commit SHA-1 hash:  ef5d4b47c3

Runtime Environment:
 OS Name:     debian
 OS Version:  
 OS Platform: Linux
 RID:         debian-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview2-006391/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

_Copied from original issue: dotnet/cli#7319_

**Comment by livarcocc** [comment]
_From @matiux on July 30, 2017 21:22_

Same thing with older version:

$ dotnet --info
.NET Command Line Tools (1.0.4)                                                                                                                                                                                                              
                                                                                                                                                                                                                                             
Product Information:                                                                                                                                                                                                                         
 Version:            1.0.4                                                                                                                                                                                                                   
 Commit SHA-1 hash:  af1e6684fd                                                                                                                                                                                                              
                                                                                                                                                                                                                                             
Runtime Environment:                                                                                                                                                                                                                         
 OS Name:     debian                                                                                                                                                                                                                         
 OS Version:                                                                                                                                                                                                                                 
 OS Platform: Linux                                                                                                                                                                                                                          
 RID:         debian.8-x64                                                                                                                                                                                                                   
 Base Path:   /opt/dotnet/sdk/1.0.4

**Comment by livarcocc** [comment]
@steveharter can you investigate first and if this is a CLI issue, please, re-activate the issue there?

**Comment by Petermarcu** [comment]
@janvorli , I would expect that from 1.X but in 2.0, we've tried to be more portable. For the 2.0 attempt, we should try to understand where the seg fault is happening.

**Comment by steveharter** [comment]
Working on repro...

**Comment by steveharter** [comment]
I was unable to repro the crash. Please try my configuration or let me know any differences.
1) Pull ISO from https://cdimage.debian.org/cdimage/daily-builds/daily/arch-latest/multi-arch/iso-cd/
2) Install ISO on Windows Server 2012R2 via Hyper-V
3) Follow docker commands at https://github.com/dotnet/dotnet-docker/blob/master/2.0/sdk/stretch/Dockerfile
4) Run various `dotnet` commands including `new console` and `run` (successful)

```dotnet --info``` output: (note that my SDK\CLI version is higher at 6497 vs. 6391)
```
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     debian
 OS Version:
 OS Platform: Linux
 RID:         debian-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview2-006497/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```

**Comment by animeshb** [comment]
I have debian buster and I have the same thing.

I found this comment [segfault following debian tutorial #649 ](https://github.com/dotnet/core/issues/649#issuecomment-309960268) which mentions renaming `libssl.so.1.0.0` lib to `libssl.so.1.0.0.old`.

Doing this worked, but the moment I do an apt-get update and upgrade, I see the segmentation fault again since the `libssl.so.1.0.0` lib is getting restored.

**Comment by steveharter** [comment]
@animeshb did you do a clean install of buster or did you upgrade?

What does your /etc/apt/sources.list contain. I have:
```
deb http://ftp.us.debian.org/debian/ buster main
deb-src http://ftp.us.debian.org/debian/ buster main

deb http://security.debian.org/debian-security buster/updates main
deb-src http://security.debian.org/debian-security buster/updates main
```

**Comment by steveharter** [comment]
@animeshb also be sure you have libssl1.0.2 installed (that is in the docker scripts I mention earlier). I have:
```
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
/usr/lib/x86_64-linux-gnu/libssl.so.1.1
```

**Comment by animeshb** [comment]
Steve,

I started from Jessie last year and then upgraded to Stretch earlier this year and came up to buster two months back.


This is my sources list:

    deb http://httpredir.debian.org/debian buster main non-free contrib
    # deb-src http://httpredir.debian.org/debian buster main non-free contrib

    deb http://security.debian.org/ buster/updates main contrib non-free
    # deb-src http://security.debian.org/ buster/updates main contrib non-free

    deb http://httpredir.debian.org/debian buster-updates main contrib non-free
    # deb-src http://httpredir.debian.org/debian buster-updates main contrib non-free

    deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    # deb-src [arch=amd64] https://download.docker.com/linux/debian stretch stable


I already had `libssl.so.1.0.2` installed and it is at the latest version:

    libssl1.0.2 is already the newest version (1.0.2l-2).

**Comment by steveharter** [comment]
@animeshb do you know why it is insisting on pulling the `libssl.so.1.0.0` version? Can you `apt-get remove ssl1.0.0` that?

**Comment by animeshb** [comment]
I removed ssl1.0.0 and a bunch other stuff I am sure were not being used.

```
  gstreamer0.10-plugins-bad gstreamer0.10-plugins-base libass5 libcdaudio1 libdirac-encoder0 libgstreamer-plugins-bad0.10-0
  libgstreamer-plugins-base0.10-0 libgstreamer0.10-0 libjasper1 libmimic0 libpng12-0 libschroedinger-1.0-0 libslv2-9 libsoundtouch0
  libssl1.0.0 libvpx1 libwildmidi1
``` 

After this, I was able to run dotnet new console and other project types. 

I will try other things and see if anything else breaks.

Thank you!

**Comment by animeshb** [comment]
I did a upgrade and dist-upgrade and that did not create any trouble. `dotnet new` ran fine after this.

**Comment by steveharter** [comment]
Glad to know it was a configuration problem! Thanks for reporting this as it may help others.

I'm going to close this since @animeshb issue appears fixed and @matiux has not replied in a while. Please re-open if there are additional segfaults with buster.

**Comment by AlexBander** [comment]
I have the same problem.
which configuration problem you mean?

it dont work on default settings

`dotnet new
Wird vorbereitet...
Speicherzugriffsfehler
`

`dotnet --info
.NET-Befehlszeilentools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
`

**Comment by steveharter** [comment]
@AlexBander the configuration problem was an older version of OpenSsl that was being used, and which is not compatible.
