### ISSUE TITLE
Building core-setup on Amazon Linux

### ISSUE THREAD

**Issue by vellozzi** [dotnet/core-setup#2947]
I can't find build instructions in this repo to build on Linux so I want to make sure what I'm doing is correct.

Here's what I did:
1.  clone the core-setup repo to my Amazon Linux 2015 EC2 instance
2.  switch to the release/2.0.0 branch.
3.  run ./build.sh from the root of the repo

"Command execution succeeded."

Is the build.sh script the correct thing to do, even though it's undocumented?
Can you give be any guidance on whether this is the correct procedure for Linux?
Also, does build.sh run the tests for this repo?

**Comment by weshaggard** [comment]
See https://github.com/dotnet/source-build/pull/227 as it will help you build on new distro's.
