### ISSUE TITLE
Fix (or add more diagnostics) to the zypper step of build.sh

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/core-setup#2963]
Currently, the daily builds of the openSUSE builds are failing with exit code 106 from a call to zypper. Unfortunately, there is no more information in the logs.

We should fix the problem, or at least do what the error message suggests, and add a call to `zypper ref -f`, so that next time it fails, we have more information to to assist in tracking down the issue.

**Comment by dagood** [comment]
Closing this stale issue: daily builds no longer have this problem.
