### ISSUE TITLE
Need to generate a Compatibility package from mscorlib-based frameworks to contracts

### ISSUE THREAD

**Issue by joperezr** [dotnet/core-setup#298]
Internally we used to produce the package `Microsoft.NETCore.Portable.Compatibility.nupkg` that worked as a facade between mscorlib based frameworks (like Desktop or Xamarin) and a Contract based world (.Net Core, UWP). We turned the build of that package off internally, so we need to add it into this repo instead, which is what this issue is going to track.

cc: @ericstj @weshaggard @danmosemsft

**Comment by danmosemsft** [comment]
According to @weshaggard we don't need this anymore as we're shipping them directly in netcoreapp.
