### ISSUE TITLE
OpenSSL install location is in /usr/local/ssl and should not be symlinked in /usr/local/lib

### ISSUE THREAD

**Issue by mario-grgic** [dotnet/core-setup#2986]
Current .NET core installer assumes that OpenSSL libraries are available in /usr/local/lib. In fact the installation instructions suggest that users symlink to OpenSSL installed elsewhere in /usr/local/lib. 

However, OpenSSL when built from source installs by default in /usr/local/ssl:

https://wiki.openssl.org/index.php/Compilation_and_Installation#PREFIX_and_OPENSSLDIR

OpenSSL libraries are in /usr/local/ssl/lib, and software compiled from source expects to find OpenSSL libraries in its default install location (/usr/local/ssl). 

This is also the location .NET Core installers should attempt to use first. If the location is not available, users can symlink to OpenSSL installation elsewhere from /usr/local/ssl/lib. Alternatively, .NET Core installed could rely on environment variable that points to the OpenSSL installation location, if users chose to install to non-default location.

In general, it is a very bad idea to symlink OpenSSL libraries from /usr/local/lib, since this means software compiled from source will inadvertently pick up wrong or unexpected libraries even when configure scripts have --withOpenSSL=... option, since /usr/local/lib is usually first in order.

**Comment by rakeshsinghranchi** [comment]
@mario-grgic , can you please share the .NET Core installation instruction that suggests to symlink to OpenSSL ? 
cc @leecow

**Comment by rakeshsinghranchi** [comment]
@leecow , do you have details on this and help propose the next step ?

**Comment by leecow** [comment]
The only instructions I've seen which come close to suggesting such a thing are for homebrew, which is really not supported by us at the moment. We'll need additional clarification from @mario-grgic to decide what, if anything, should be done.

**Comment by mario-grgic** [comment]
It looks like things have changed quite a bit since I posted this. So this issue can be closed.
