### ISSUE TITLE
Running `dotnet --version` outputs full usage help

### ISSUE THREAD

**Issue by naamunds** [dotnet/core-setup#300]
## Steps to reproduce
1.  Install the .NET Core Shared Framework Host.
2.  Run `dotnet --version`.
## Expected  behavior

Just the .NET Core version info is output:

> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 1.0.1
>   Build    : cee57bf6c981237d80aa1631cfe83cb9ba329f12
## Actual behavior

The full usage help is output, like if running `dotnet --help`.

> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 1.0.1
>   Build    : cee57bf6c981237d80aa1631cfe83cb9ba329f12
> 
> Usage: dotnet [common-options] [[options] path-to-application]
> 
> Common Options:
>   --help                           Display .NET Core Shared Framework Host help.
>   --version                        Display .NET Core Shared Framework Host version.
> 
> Options:
>   --fx-version <version>           Version of the installed Shared Framework to use to run the application.
>   --additionalprobingpath <path>   Path containing probing policy and assemblies to probe for.
> 
> Path to Application:
>   The path to a .NET Core managed application, dll or exe file to execute.
> 
> If you are debugging the Shared Framework Host, set 'COREHOST_TRACE' to '1' in your environment.
> 
> To get started on developing applications for .NET Core, install .NET SDK from:
>   http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
## Environment data

`dotnet --info` output:

> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 1.0.1
>   Build    : cee57bf6c981237d80aa1631cfe83cb9ba329f12

**Comment by ramarag** [comment]
the verb that should be used to get this info is --info
