### ISSUE TITLE
Update RPM package version epoch to 1

### ISSUE THREAD

**Issue by leecow** [dotnet/core-setup#3044]
Currently yum/dnf update visibility rules are causing the preview package to hide GA. A test with the azlinux folks has shown that updating the epoch field will resolve the issue. 

This needs to be done in release/2.0.0 and master

cc @wli3

Background: 
* https://www.redhat.com/archives/rpm-list/2000-October/msg00075.html
* http://blog.jasonantman.com/2014/07/how-yum-and-rpm-compare-versions/

**Comment by rakeshsinghranchi** [comment]
@leecow , As I remember, we decided not to do this. Re-activate if this needs to be done.
