### ISSUE TITLE
Clean up Homebrew steps in the Mac installer UI

### ISSUE THREAD

**Issue by leecow** [dotnet/core-setup#3067]
<img width="618" alt="screen shot 2017-08-17 at 2 54 47 pm" src="https://user-images.githubusercontent.com/2212879/29435484-118c0a26-835c-11e7-89a5-d0abd471d858.png">

[ ] Homebrew link is bad
[ ] Change the paragraph into a series of steps

* Install [HomeBrew](https://brew.sh/)
* brew install openssl
* brew link –force openssl

**Comment by karelz** [comment]
Homebrew link was fixed in #3064 - not sure if it fixes also 1.1x though.

**Comment by dagood** [comment]
Closing: this was fixed (to some degree) in https://github.com/dotnet/core-setup/pull/3064 and nobody in triage thinks we need these steps anymore.
