### ISSUE TITLE
Microsoft.VisualStudio.Web.CodeGeneration.Design doesn't install after upgrade to core 2.0

### ISSUE THREAD

**Issue by ozitraveller** [dotnet/core-setup#3077]
## Steps to reproduce
After the upgrade to dotnet core 2.0, I created a dotnet core 1.1 webapi project without docker support. While installing the components for the Scaffold-DbContext I need to install Microsoft.VisualStudio.Web.CodeGeneration.Design version 1.1.1

## Expected  behavior
I expected to be able to still create dotnet core 1.1 solutions

## Actual behavior
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
Package restore failed. Rolling back package changes

## Environment data

VS 2017 15.3.1

**Comment by mrtaunus** [comment]
Any progress on this? I encountered the same error, happens with version 1.1.2 of Microsoft.VisualStudio.Web.CodeGeneration.Design as well.

**Comment by livarcocc** [comment]
This issue was moved to aspnet/websdk#321
