### ISSUE TITLE
Install location is not in Ubuntu path

### ISSUE THREAD

**Issue by wli3** [dotnet/core-setup#3078]
_From @bassebaba on August 22, 2017 16:23_

## Steps to reproduce
1) Follow steps here: https://www.microsoft.com/net/core#linuxubuntu
2) At step (3), you get a "command not found"

## Expected  behavior
dotnet-binary should run

## Actual behavior
Dotnet is installed in /usr/share/dotnet/

Checking the default path-variable for Ubuntu 16.04, theres no /usr/share/... :
```
echo $PATH
/home/bassebaba/bin:/home/bassebaba/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

```
So running "dotnet" from bash won't work

## Solution
The binary should either be installed in, or symlinked, to one of the default locations in $PATH?

Manual solution is:
`sudo ln -s /usr/share/dotnet/dotnet /usr/local/bin/`

But I think this should be done by the installer?

_Copied from original issue: dotnet/cli#7496_

**Comment by wli3** [comment]
_From @omajid on August 22, 2017 16:42_

Maybe @wli3 has an idea? He worked on the packages.

**Comment by wli3** [comment]
Hi @bassebaba
I just tried with a fresh Ubuntu 16.04 on Azure VM that is published by canonical. no repo. There is a symlink from /usr/share/dotnet to /usr/bin/dotnet after installation without extra command.

This package of the executable, dotnet-host, is maintained in core-setup. I'll move it there

**Comment by andremarcondesteixeira** [comment]
I'm having this issue when trying to install dotnet-sdk-2.0.0 for ubuntu 16.04 following the instructions on the official site.

**Comment by Petermarcu** [comment]
@andremarcondesteixeira can you share what is on your path?

`echo $PATH`?

**Comment by andremarcondesteixeira** [comment]
@Petermarcu Sure thing! Here it goes:
/home/andre/bin:/home/andre/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by andremarcondesteixeira** [comment]
@Petermarcu I already reported the issue here: https://github.com/dotnet/core-setup/issues/3278
The solution provided here does not work for me, since my installation is missing the dotnet binary for some reason

**Comment by Petermarcu** [comment]
@andremarcondesteixeira ok, lets make progress on your issue on #3278. 

@bassebaba we aren't able to reproduce your issue. Can you give any more details?

**Comment by bassebaba** [comment]
@Petermarcu The only more details I have is that I have had several of the previous dotnet versions installed, this was not done on a "clean" Ubuntu install...

After removal of the old packages and then followed the 2.0.0 install instructions, everything was "in place", the only thing that was missing was the symlink in /usr/local/bin pointing to the actual dotnet binary location.

I have not been able to reproduce this on a "clean" Ubuntu or Debian install.

**Comment by Petermarcu** [comment]
@rakeshsinghranchi , I wonder if there is some kind of reference counting issue here. The theme I'm seeing with these types of bugs is that people have multiple versions and in one way or another removed an older one.

**Comment by pamanes** [comment]
This happened to me on Fedora 27 but it was working fine, then I did dnf update and reboot and dotnet was gone! this worked for me:
sudo ln -s /usr/share/dotnet/dotnet /usr/local/bin/

thanks

**Comment by rakeshsinghranchi** [comment]
I couldn't repro the issue in Ubuntu. A similar issue was found on RPM package and has been fixed https://github.com/dotnet/core-setup/pull/3578
