### ISSUE TITLE
Core-Setup dev/defaultintf builds are finalizing to master channel

### ISSUE THREAD

**Issue by Chrisboh** [dotnet/core-setup#3079]
@dagood commented on [Wed Aug 09 2017](https://github.com/dotnet/core-eng/issues/1473)

Someone else saw https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/latest.version with `2.1.0-dev-di-25608-01`, and later when I looked at it, it had `2.1.0-preview2-25609-02`.

It looks like [dev/defaultintf dir.props#L21-L22](https://github.com/dotnet/core-setup/blob/7a391b9234369c48fe8d809d549e349259be00e5/dir.props#L21-L22) is configured to publish `dev/defaultintf` (dev-di) to the `master` channel, thrashing with master branch builds.

@dotnet/dnceng 

---

@MattGal commented on [Thu Aug 10 2017](https://github.com/dotnet/core-eng/issues/1473#issuecomment-321604344)

@yizhang82  FYI

---

@Chrisboh commented on [Mon Aug 21 2017](https://github.com/dotnet/core-eng/issues/1473#issuecomment-323896215)

@MattGal or @dagood was this fixed?

---

@dagood commented on [Tue Aug 22 2017](https://github.com/dotnet/core-eng/issues/1473#issuecomment-324045080)

Apparently not: the current latest.version is:

> 7a391b9234369c48fe8d809d549e349259be00e5
> 2.1.0-dev-di-25621-02

**Comment by eerhardt** [comment]
Resolved with https://github.com/dotnet/core-setup/pull/3101
