### ISSUE TITLE
Need to backport #2501 to 1.x of DependencyModel

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#3081]
## Steps to reproduce
See https://github.com/dotnet/sdk/issues/1488 for the issue

Try to build/run an ASP.NET 1.1 MVC app with the 2.0 SDK.

## Expected  behavior
It should work.

## Actual behavior
`InvalidOperationException: Can not find assembly file Microsoft.CSharp.dll at 'C:\Projects\Temp\VS2017Issue\WebApplication1\bin\Debug\net462\refs,C:\Projects\Temp\VS2017Issue\WebApplication1\bin\Debug\net462\`

@Petermarcu @karelz @steveharter @nguerrera

**Comment by karelz** [comment]
I assume we have to service 2.0 for that, right?

**Comment by eerhardt** [comment]
The necessary change is already in 2.0.  The proposed fix here is to backport the change into 1.1.

The issue is that using the 2.0 SDK is breaking 1.1 MVC apps because it is copying files into the `refs` folder, which the 1.1 DependencyModel isn't expecting.

**Comment by karelz** [comment]
I thought we're using 2.0 SDK also for 1.1. Marking as 1.1.x then. Can you please send it to shiproom?

**Comment by DamianEdwards** [comment]
Seems this got dropped somehow? Are we intending to service this in the next 1.1.x patch? I just hit this issue myself trying to make a 1.1.x app targeting .NET Framework 4.6.1, and it's shown up in 2.1 E2E testing as a blocking issue.

@davidfowl @balachir

**Comment by eerhardt** [comment]
Yes, this got dropped. 😞   I'll get a PR for it into 1.1, and send a shiproom email.

**Comment by eerhardt** [comment]
@DamianEdwards - FYI https://github.com/dotnet/core-setup/pull/3954 is the PR to backport the change into 1.1.  Thanks for bringing this issue up.

**Comment by eerhardt** [comment]
Closing as the fix has been ported to 1.1.
