### ISSUE TITLE
SUSE/OpenSUSE installer unable to resolve libcurl dependency 

### ISSUE THREAD

**Issue by leecow** [dotnet/core-setup#3107]
zypper is unable to resolve the libcurl dependency in dotnet-runtime-2.0.0.rpm

```
~> sudo zypper install dotnet-sdk-2.0.0
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libcurl needed by dotnet-runtime-2.0.0-2.0.0-1.x86_64
 Solution 1: do not install dotnet-sdk-2.0.0-2.0.0-1.x86_64
 Solution 2: break dotnet-runtime-2.0.0-2.0.0-1.x86_64 by ignoring some of its dependencies
```

```
~> rpm -qpR dotnet-runtime-2.0.0.rpm
dotnet-hostfxr-2.0.0
openssl-libs
libcurl
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(CompressedFileNames) <= 3.0.4-1
```

libcurl is installed so perhaps the RPM definition needs indicate a min version.
```
~> zypper search libcurl
Loading repository data...
Reading installed packages...

S  | Name                | Summary                                | Type
---+---------------------+----------------------------------------+--------
   | libcurl-devel       | A Tool for Transferring Data from URLs | package
   | libcurl-devel-32bit | A Tool for Transferring Data from URLs | package
i+ | libcurl4            | Version 4 of cURL shared library       | package
   | libcurl4-32bit      | Version 4 of cURL shared library       | package
```

**Comment by pandaparag** [comment]
Looks like it is expected as stated by Microsoft [here](https://www.microsoft.com/net/core#linuxopensuse):
> Note: When installing the SDK, SUSE and OpenSUSE may report that nothing provides libcurl. libcurl should already be installed on supported versions of both distros. Run zypper search libcurl to confirm. The error will present 2 'solutions'. Choose 'Solution 2' to continue installing .NET Core.

**Comment by rakeshsinghranchi** [comment]
Looking at the RPM package authoring, libcurl is hardcoded and thus system package installation will work only on machine where it is available . Looks like OpenSUSE carries libcurl4 and thus the package dependency is not met. The right fix would be to build meta package for system dependencies per distro version and enable runtime packages as version agnostic.

https://github.com/dotnet/core-setup/blob/master/src/pkg/packaging/rpm/dotnet-sharedframework-rpm_config.json#L42
