### ISSUE TITLE
linux-arm runtime store is empty

### ISSUE THREAD

**Issue by nzain** [dotnet/core-setup#3122]
Publishing a shared-framework app for `linux-arm` runtime from win-x64 will trim libraries that do not ship with the [linux-arm 2.0.0 runtime](https://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.0.0/dotnet-runtime-2.0.0-linux-arm.tar.gz). The app won't run on the arm device.

Trimming is explained [here](https://github.com/dotnet/standard/blob/release/2.0.0/Microsoft.Packaging.Tools.Trimming/docs/trimming.md) and the ASP team strongly suggest the use of the [Microsoft.AspNetCore.All](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage) to benefit from trimming.

The error output looks strange to me, as it includes x64 and x86 "stuff", but I can't interpret it. Fun fact: we don't use appication insights (it is realllly difficult to opt-out) and the dll is not required anyways. Known workaround: disable trimming.

## Steps to reproduce
- `dotnet new web -o foo`
- `cd foo`
- `dotnet restore -r linux-arm`
- `dotnet publish -o deploy`
- copy to the linux-arm device
- on linux-arm: `dotnet foo.dll`

## Expected  behavior
The application starts.

## Actual behavior
The app crashes due to missing dlls. Sample output could look like this:

```
Error:
  An assembly specified in the application dependencies manifest (foo.deps.json) was not found:
    package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1'
    path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-linux-x64.xml;aspnetcore-store-2.0.0-osx-x64.xml;aspnetcore-store-2.0.0-win7-x64.xml;aspnetcore-store-2.0.0-win7-x86.xml
```

## Environment data on Developer Machine win10-x64
```
PS> dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

## Environment data on Target Device linux-arm
```
# /opt/dotnet/dotnet --info

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```
This is a cortex-A7, 32bit, hardfloat. Linux selfmade via buildroot.

**Comment by omajid** [comment]
Some workarounds are documented at https://github.com/dotnet/designs/issues/10

**Comment by nzain** [comment]
I see that this is kind of a distribution problem. I thought that the runtime store should be contained with the runtime itself (and thus being an issue of the core-setup, that should bundle it properly). Eventually this store is filled when the dotnet CLI runs the first time? I remember it took a while. However, on linux-arm there is no CLI and the runtime is bare bones, no asp.net.

I have no clue what should happen in my case - but either the runtime store should be filled somehow or the feature should be disabled, when I specify RIDs that are not compatible with the "default runtime store".

**Comment by Petermarcu** [comment]
@Eilon @DamianEdwards @muratg where can someone get the ASP.NET Runtime store to put on their arm32 device? Is there a zip somewhere?

There is also a setting that can be added to your project to opt out of the ASP.NET Runtime Store. I forgot what it is but the same folks should be able to share what that is.

**Comment by muratg** [comment]
I don't believe we have an arm32 version of the store for 2.0. RTM.  (cc @JunTaoLuo) 

To opt-out of assembly trimming with the `Microsoft.AspNetCore.All` metapackage, you can add the following to your .csproj:

```csproj
<PropertyGroup>
  <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
</PropertyGroup
```

**Comment by Petermarcu** [comment]
Thanks @muratg. Can we produce an arm32 runtime store zip easily?

**Comment by josemaia** [comment]
Hello @muratg. I would like to have an "ASP.NET Core" docker image for my Raspberry Pi, and for that I understand I'd need the runtime store. Is this planned at all?

**Comment by Eilon** [comment]
Adding @natemcmaster and @MichaelSimons , the resident Docker experts.

**Comment by natemcmaster** [comment]
`microsoft/dotnet` supports arm32 images, however, they do not include the aspnetcore runtime store. `microsoft/aspnetcore` does _not_ support arm32 images.

**Comment by Petermarcu** [comment]
@natemcmaster what would it take to produce a runtime store for ASP.NET that the community can use? Or should they all add the property to their projects to disable the ASP.NET runtime store?

**Comment by natemcmaster** [comment]
> what would it take to produce a runtime store for ASP.NET that the community can use? 

@Petermarcu dev time. In the meantime, opt-ing out of publish trimming is the best solution for users, as Murat mentioned above. https://github.com/dotnet/core-setup/issues/3122#issuecomment-326040506

I don't think anyone has looked into making an arm32 store for aspnetcore, but I think it should be possible. The only issue I can imagine hitting is with packages that have native assets, e.g. SQLite, SqlClient, libuv. We would need to ensure they include arm32 compatible binaries.

**Comment by Petermarcu** [comment]
I know libuv already has arm32 assets. Even if people opt out of the runtime store, it just means things get copied with the app so hopefully there are assets to copy.

**Comment by natemcmaster** [comment]
Ok. There will likely be half a dozen work items for this. I've opened https://github.com/aspnet/Universe/issues/554 so we can triage and track this work.

**Comment by nzain** [comment]
What happens when I pull aspnetcore.all via Nuget and targeting `-r
linux-arm` ? It ends up running on a 32bit hardfloat architecture with a
32bit runtime host. Those packages _are_ available via nuget, but not in
the shape of that 'runtime store'. This includes libuv. Shouldn't be that
difficult, no? :-)

Am 13.09.2017 18:58 schrieb "Nate McMaster" <notifications@github.com>:

**Comment by natemcmaster** [comment]
> Shouldn't be that difficult, no?

Difficult? hopefully not. It's more a matter of allocating dev time to setting up build infrastructure and testing. At the moment, I don't have cycles for this and won't for a month or so. We'll discuss https://github.com/aspnet/Universe/issues/554 in triage.

**Comment by Petermarcu** [comment]
aspnet/Universe#554 is tracking this work now. Closing this one here.

**Comment by nzain** [comment]
Today I was testing the latest official arm32 dotnet core runtime (2.1.1 as of today) from
https://www.microsoft.com/net/download/linux
but it still does not contain a runtime store. We're not working with docker (the linked issue https://github.com/aspnet/Universe/issues/554 forwards to https://github.com/dotnet/dotnet-docker/issues/480). All related issues are closed by now and I'm somewhat lost, because my problem is not resolved.

There was one link to a generated preview(!) runtime store - but what is the official way to get it in my situation? I thought, it will be contained within the runtime.tar.gz, but it's not.

@natemcmaster could you clarify, how the store is shipped without docker? Thanks!

**Comment by natemcmaster** [comment]
It looks like some of our download pages are wrong. I send https://github.com/dotnet/core/pull/1737 to fix the links. Also, it looks like the marketing site is wrong (it's arm32, not arm64), but this is where you get the ASP.NET Core linux-arm binaries. https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.1-linux-arm64-asp.net-core-runtime-binaries

**Comment by nzain** [comment]
Thanks @natemcmaster ! Using the dotnet-runtime-2.1.1-linux-arm64-asp.net-core (actually 32bit) works perfectly fine on our arm32. This is the first time a "default web app" (with trimming) is running on our device.

What exactly are the benefits of using the pre-built runtime store? Right now, we have one webservice only, so there is no advantage in terms of storage space by sharing the ASP.Net libraries. I can see a difference in update strategy - not relevant for us, because we would update both framework and application, when the device comes back from customers for service. Would you expect performance improvements?

**Comment by natemcmaster** [comment]
Some of the benefits are explained here. https://docs.microsoft.com/en-us/dotnet/core/deploying/. There aren’t any performance benefits, it’s really about disk space and servicing. Since you’re running an app on a device, there isn’t much benefit for you. You might consider a self-contained deployment instead.
