### ISSUE TITLE
Attempting to debug a shipped version of `dotnet.exe` is not possible due to the PDBs missing source information.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/core-setup#3126]
## Steps to reproduce

Attempt to debug a shipped version of `dotnet.exe` (such as the one that comes with the 2.0 SDK)

## Expected  behavior

The PDBs should contain source information so that debugging can occur.

## Actual behavior

The PDBs are missing source information

**Comment by steveharter** [comment]
@dagood can you PTAL?

**Comment by dagood** [comment]
@mikem8361 Do you mind looking at this? I'm wondering if `dotnet.pdb` might have been uploaded before the whitelist was up and needs reuploading, but I don't know if there might be a deeper issue.

**Comment by tannergooding** [comment]
@dagood, it might be worth noting that I was seeing this even with `symweb` in my symbol server list

**Comment by mikem8361** [comment]
For 2.0 the source server info wasn't part of the cli pdbs uploaded. dotnet.pdb was uploaded but it didn't have any source info. We have a plan for all the .NET Core teams to add SourceLink info to their builds for upcoming releases.

**Comment by tannergooding** [comment]
@mikem8361, I'm not even talking about source link here (although that would be ideal). I'm just referring to the fact that the PDBs are stripped (even though they are open source).

I would have expected that I could download the tagged release, debug the PDB, and the dialog asking me to locate the source file popped up (at a minimum).

Perhaps more surprisingly, the internal symbol server didn't even have the full PDB, so I wasn't even able to properly debug the file that way either.

**Comment by mikem8361** [comment]
I'm not sure what is going on.  The dotnet.pdb seems to be a full pdb as far as I can tell (both on http://symweb and http://msdl.microsoft.com/download/symbols according to "symchk" with /pf option:

`"\Program Files\Debugging Tools for Windows (x64)\symchk.exe" /pf dotnet.exe /s SRV*http://msdl.microsoft.com/download/symbols`
`SYMCHK: FAILED files = 0`
`SYMCHK: PASSED + IGNORED files = 1`

or 

`"\Program Files\Debugging Tools for Windows (x64)\symchk.exe" /pf dotnet.pdb`
`SYMCHK: FAILED files = 0`
`SYMCHK: PASSED + IGNORED files = 1`

[dotnet.pdb.zip](https://github.com/dotnet/core-setup/files/1304871/dotnet.pdb.zip)
