### ISSUE TITLE
Assert Failure while trying to load System.Private.CoreLib.resources.dll 

### ISSUE THREAD

**Issue by olivier-spinelli** [dotnet/core-setup#3133]
I'm really sorry to not be able to follow the standard issue rules here (because the project I'm working on is a little bit complicated) but since I found a `Assert Failure` in the core 2.0, I think I should submit it. 
A bit of context: 
- a 2.0 console app 
- with its deps.json merged with class libraries deps.json (in netstandard1.3 and 1.6), using  DependencyContextJsonReader and DependencyContext.Merge).
- and after a LoadFrom of System.Xml.XDocument.dll from a AssemblyResolve event... because its 'normal' load was failing (that, IMO, shows that I'm doing something wrong somewhere). 
- Note that the AssemblyResolve returns null on the System.Private.CoreLib.resources.dll and does nothing.

I can provide the whole stuff (it is OSS, public bitbucket repo) or the merged deps.json or anything else that may help.

Here are the traces of my process:

|  |  - Info: - Info: CurrentDomain.BaseDirectory: C:\Dev\CK-Database-Projects\CK-Database\Tests\SqlCallDemo\SqlCallDemo\bin\Debug\netstandard1.3\publish\
|  |          > Info: Starting CK.StObj.Runner
|  |          |  > Info: Merging deps.json files.
|  |          |  |  - Info: Merging 'CK.Setupable.Engine.deps.json'.
|  |          |  |          Merging 'CK.Setupable.Runtime.deps.json'.
|  |          |  |          Merging 'CK.SqlServer.Setup.Engine.deps.json'.
|  |          |  |          Merging 'CK.SqlServer.Setup.Runtime.deps.json'.
|  |          |  |          Merging 'CK.StObj.Engine.deps.json'.
|  |          |  |          Merging 'CK.StObj.Runtime.deps.json'.
|  |          |  |          Merging 'SqlCallDemo.deps.json'.
|  |          |  |          Saving 'CK.StObj.Runner.deps.json.merged'.
|  |          - Info: CurrentDomain.BaseDirectory: C:\Dev\CK-Database-Projects\CK-Database\Tests\SqlCallDemo\SqlCallDemo\bin\Debug\netstandard1.3\publish\
|  |          > Info: Starting CK.StObj.Runner
|  |          |  - Info: AssemblyResolve (weaken): System.Xml.XDocument, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a ==> 
|  |          |          File 'System.Xml.XDocument.dll' exists in BaseDirectory.
|  |          |          AssemblyResolve (LoadFrom): System.Xml.XDocument, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a ==> System.Xml.XDocument, Version=4.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
|  |          |  > Info: Obtention of the IStObjRuntimeBuilder.
|  |          |  < CK.Core.StObjContextRoot+SimpleStObjRuntimeBuilder, CK.StObj.Model, Version=0.0.0.0, Culture=neutral, PublicKeyToken=731c291b31fb8d27
|  |          |  > Trace: Creating and configuring 2 aspect(s).
|  |          |  |  > Trace: Configuring aspect 'CK.Setup.SetupableAspect'.
|  |          |  |  > Trace: Configuring aspect 'CK.SqlServer.Setup.SqlSetupAspect'.
|  |          |  |  |  - Info: AssemblyResolve (weaken): **System.Private.CoreLib.resources, Version=4.0.0.0, Culture=fr-FR, PublicKeyToken=7cec85d7bea7798e** ==> 
|  |          |  |  |  - Warn: File 'System.Private.CoreLib.resources.dll' does not exist in BaseDirectory.
|  |          |  |  |  - Info: AssemblyResolve (weaken): System.Private.CoreLib.resources, Version=4.0.0.0, Culture=fr-FR, PublicKeyToken=7cec85d7bea7798e ==> 
|  |          |  |  |  - Warn: File 'System.Private.CoreLib.resources.dll' does not exist in BaseDirectory.
**|  |  - Error: Assert Failure
|  |           Expression: [Recursive resource lookup bug]
|  |           Description: Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: ArgumentNull_Generic**
|  |           Stack Trace:
|  |              at System.SR.InternalGetResourceString(String key)
|  |              at System.SR.GetResourceString(String resourceKey, String defaultString)
|  |              at System.ArgumentNullException..ctor(String paramName)
|  |              at System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(Assembly assembly)
|  |              at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
|  |              at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
|  |              at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
|  |              at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
|  |              at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
|  |              at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
|  |              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
|  |              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
|  |              at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
|  |              at System.SR.InternalGetResourceString(String key)
|  |              at System.SR.GetResourceString(String resourceKey, String defaultString)
|  |              at System.ArgumentNullException..ctor(String paramName)
|  |              at System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(Assembly assembly)
|  |              at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
|  |              at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
|  |              at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
|  |              at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
|  |              at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
|  |              at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
|  |              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
|  |              at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
|  |              at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
|  |              at System.SR.InternalGetResourceString(String key)
|  |              at System.SR.GetResourceString(String resourceKey, String defaultString)
|  |              at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
|  |              at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
|  |              at CK.SqlServer.Setup.SqlManagerProvider.CreateManager(Item i)
|  |              at CK.SqlServer.Setup.SqlManagerProvider.FindManagerByName(String name)
|  |              at CK.SqlServer.Setup.SqlSetupAspect.CK.Setup.IStObjEngineAspect.Configure(IActivityMonitor monitor, IStObjEngineConfigureContext context)
|  |              at CK.Setup.StObjEngineConfigureContext.CreateAndConfigureAspects(IReadOnlyList`1 configs, Func`1 onError)
|  |              at CK.Setup.StObjEngine.Run()
|  |              at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
|  |              at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
|  |              at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
|  |              at CK.Core.StObjContextRoot.DoBuild(StObjEngineConfiguration config, Func`1 builderMethod, String stObjRuntimeBuilderFactoryTypeName, String stObjRuntimeBuilderFactoryMethodName, IActivityMonitor monitor) in C:\Dev\CK-Database-Projects\CK-Database\CK.StObj.Model\StObjContextRoot.cs:line 139
|  |              at CK.Core.StObjContextRoot.Build(StObjEngineConfiguration config, Func`1 builderFactoryStaticMethod, IActivityMonitor monitor) in C:\Dev\CK-Database-Projects\CK-Database\CK.StObj.Model\StObjContextRoot.cs:line 102
|  |              at CK.StObj.Runner.Program.Run(IActivityMonitor m)
|  |              at CK.StObj.Runner.Program.Main(String[] args)
|  |           Process returned ExitCode -2146232797.
> Info: Closing Zip archive.
|  > Trace: Cleaning 61 runtime files.

**Comment by olivier-spinelli** [comment]
What I was trying to do actually works. The actual issue is related to https://github.com/dotnet/coreclr/issues/12668.
I close this one.

**Comment by danmosemsft** [comment]
Fix released https://github.com/dotnet/corefx/releases/tag/v2.0.3
