### ISSUE TITLE
Symbols cannot be loaded when debugging MSBuild task run from dotnet.exe

### ISSUE THREAD

**Issue by jonathanbyrne** [dotnet/core-setup#3138]
## Steps to reproduce
1. Extract attached zip file ([MyTask.zip](https://github.com/dotnet/core-setup/files/1272219/MyTask.zip))
2. Open MyTask.sln in Visual Studio 2017
3. Ensure that the Just-In-Time debugger is enabled for Visual Studio 2017
4. Execute "test-with-dotnet-build.bat" or "test-with-dotnet-msbuild.bat"
5. Choose Visual Studio instance with MyTask solution to debug dotnet.exe
<img width="320" alt="dotnet msbuild task debug screenshot 1" src="https://user-images.githubusercontent.com/3814989/29995938-f51680d8-8fc2-11e7-991d-9f88595ffa1a.png">

## Expected behavior
The debugger should load the symbols for MyTask and allow debugging.  Executing "test-with-msbuild.bat" will demonstrated the expected behavior.
<img width="1117" alt="dotnet msbuild task debug screenshot 2" src="https://user-images.githubusercontent.com/3814989/29995969-79f3e638-8fc3-11e7-9406-603a22c331c2.png">

## Actual behavior
Visual Studio does not load the symbols for MyTask.  The modules window states:

> The module did not load at the default load address.
<img width="1117" alt="dotnet msbuild task debug screenshot 3" src="https://user-images.githubusercontent.com/3814989/29996061-6c305ff2-8fc5-11e7-81c3-4041b3916934.png">

When choosing "Symbol Load Information..." from the module context menu, a dialog box states:

> This module is a pre-compiled binary created by the ngen.exe tool. The debugger does not attempt to load symbols for these binaries, but will instead load symbols for original dll/exe when it is loaded by the .NET Runtime.
<img width="501" alt="dotnet msbuild task debug screenshot 4" src="https://user-images.githubusercontent.com/3814989/29996078-c06aefba-8fc5-11e7-9ef8-4a7fd0b2ddde.png">

## Environment data
Visual Studio Professional 15.4.0 Preview 1.0
MSBuild 15.3.409.57025
Dotnet 2.0.0
NuGet 4.3.0.4406

**Comment by steveharter** [comment]
@dagood any comments? Thanks

**Comment by dagood** [comment]
It looks like this is the same issue as https://github.com/dotnet/coreclr/issues/12074: "Debugger.Launch doesn't work correctly on coreclr on Windows"

**Comment by steveharter** [comment]
OK closing as dup
