### ISSUE TITLE
Unify the format of the embedded git commit hash with coreclr and corefx

### ISSUE THREAD

**Issue by janvorli** [dotnet/core-setup#3153]
Core-setup currently uses a different format of git commit hash string embedded in the native binaries than coreclr and corefx. Core-setup just embeds the hash string without anything added. Coreclr and corefx, on the contrary, have both the following format of the string:
`@(#)Version 4.6.25519.02 built by: root-/tmp/tmp83b334114c56469eb397e7dad6617874.exec.cmd: line 2: hostname: command not found. Commit Hash: 36f70fa4be4bd37d4d76d06dd2cc433ff46351bd
`
It would be great to unify this cross our products. The benefit of the coreclr / corefx way is that it can be easily retrieved like this:
```sh
strings libcoreclr.so | grep "@(#)"
```
or on systems that have the `what` tool:
```sh
what libcoreclr.so
```
To create that string, the following static variable needs to be created anywhere in the binary:
static char sccsid[] = "@(#) xxxxxxxxxxxxxxxxxxxxxxxxxxx";
It stemmed from this: https://en.wikipedia.org/wiki/Source_Code_Control_System
The built-by and hostname in the version are quite useless (and the hostname is currently broken, as you can see), so we could remove them from the string and keep just the prefix string, version and commit hash.

**Comment by janvorli** [comment]
CC: @eerhardt (FYI)

**Comment by eerhardt** [comment]
@janvorli - it looks like we are already setting this static variable:

https://github.com/dotnet/core-setup/search?utf8=%E2%9C%93&q=sccsid&type=

**Comment by janvorli** [comment]
@eerhardt neither of the native files contain the string, I've just double checked. Looking at coreclr version of that stuff, the problem is that the variable is not marked with `__attribute__((used))` and so the linker throws it away.
