### ISSUE TITLE
Core 2 Framework error “FileNotFoundException” referencing libaries

### ISSUE THREAD

**Issue by Duefectu** [dotnet/core-setup#3155]
[Core2FrameWork.zip](https://github.com/dotnet/core-setup/files/1286233/Core2FrameWork.zip)

Hello:

I have a Core 2 Framework Project. I use Core 2 for performance and need to use Framework 4.6.1 for accesing hardware (printer, serial ports, etc...), I use 4.6.1 to target Windows 10 Aniversary Update.

The main Project is a Core 2.0 MVC Project (Core2FrameWork in the sample Project) It references a .NET Framework 4.6.1 Library Project (FrameWork461 in the sample Project) FrameWork461 Project references "System.Printer.dll" (I tested with other System.* libraries with the same error result)

When I call a method with "System.Printer" reference I got a "FileNotFoundException: Could not load file or assembly 'System.Printing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado."

Note that the library isn't referenced by the core Project. It's a referenced Project dependency.

The sample Project is available [here](https://1drv.ms/u/s!ArCJF44YRdJrlIRYToKv5qzxXrq-JA) or at the begin of this question.

In this simple project, the Home/Index page calls FrameWork461.Working class, and it Works. 
The home/NoWorking page calls FrameWork461.NoWorking class, and it do not Works.

As a workarround, I applied the solution exposed in this page: [Cannot resolve assembly paths for reference compilation libraries #2981](https://github.com/dotnet/core-setup/issues/2981) (it's included in the sample project).

It happends running in IIS, in StandAlone .exe and publishing.

Sorry for my bad English!
Thanks for your help!

**Comment by Duefectu** [comment]
I really have the problem with ASP.Net Core Framework Project. I'm unable to créate a new Project with Core 2.0 and reference a Framework library that references System.Printing.dll or other libraries.

But @mairaw gave me another way. On a project that works in Core 1.1, updating the libraries Nuget to 2.0, works correctly.

So it looks like a Visual Studio 2017 problem or Core templates.

My concern is to remove this functionality, because it allows to adopt the Core technology in a staggered way with a high code reuse.

**Comment by Petermarcu** [comment]
While referencing .NET Framework libraries is allowed in .NET Core applications, they only work if all of the implementations they depend on are there in .NET Core. In this case, System.Printing is not an assembly that is part of .NET Core. I believe you have two options here:

1. Run ASP.NET Core on top of .NET Framework 4.6.1.
2. Run the code that needs to run on .NET Framework in a different process and call out to it from a .NET Core process.

@Eilon @terrajobst , can you think of any other options?

**Comment by Duefectu** [comment]
Hello @Petermarcu, you're right. With Core there's no way, but not matter. My problema is with ASP.Net Core, but with a new Project referencing Core 2.0 didn't Works.
With a ASP.Net Core 1.1, upgrading from Nuget it Works!

**Comment by Petermarcu** [comment]
In the project you zipped up, it had a target framework of netcoreapp20. In order to do .NET Framework, you would need it to be net461 instead.

**Comment by Duefectu** [comment]
The working project ([CoreTest.zip](https://1drv.ms/u/s!ArCJF44YRdJrlIVAsYzYJQX_MJgyLA) is an ASP.Net Core Framework Project referencing Core 1.1 libraries in the origin and a .NET Framework 4.6.1, and it Works.
I updated with Nuget to Core 2.0 libraries and it still working.
Then it is possible with Core 2.0 (ASP.Net Core) but I didn't find a way to do with a new Project.

I I think it's an important feature that allows you to create a hybrid application that takes advantage of existing work, hardware and software resources that are not available in .net Core or .net Standard.

**Comment by nguerrera** [comment]
I don't see any action item here. Things are working as designed.
