### ISSUE TITLE
dotnet fails with error: api-ms-win-crt-runtime-l1-1-0.dll is missing.

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#3220]
_From @seancpeters on September 14, 2017 18:25_

## Steps to reproduce
Start with a clean machine configured with: Win 8.1 x64 ESN OS
Install CLI 2.0 RTW

## Expected  behavior
dotnet commands execute properly.

## Actual behavior
Running dotnet with any (or no) options fails, pops up an error dialog containing: "The program can not start because api-ms-win-crt-runtime-l1-1-0.dll is missing on the computer. Try reinstalling the program to correct this problem."

![image](https://user-images.githubusercontent.com/20912881/30446835-26e7846a-993f-11e7-9129-127732ccb614.png)

## Environment data
`dotnet --info` output:

N/A - running `dotnet --info` fails with the same error.

_Copied from original issue: dotnet/cli#7654_

**Comment by livarcocc** [comment]
How did you install the CLI on this box?

**Comment by livarcocc** [comment]
_From @steveharter on September 14, 2017 19:36_

Also can you check that you have the [uCRT ](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows)(universal CRT) installed.

**Comment by livarcocc** [comment]
_From @seancpeters on September 14, 2017 19:45_

The CLI was installed from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.0.0/dotnet-sdk-2.0.0-win-x64.exe

I am not certain about the universal CRT.

This bug was reported by our testing team, so my information is unfortunately a bit limited.

**Comment by steveharter** [comment]
On the uCRT, see https://github.com/dotnet/core/blob/851184b864923dd49dfcb099932e30c431856ba7/release-notes/1.0/1.0.0-known-issues.md#universal-c-runtime-dependency-on-windows

**Comment by steveharter** [comment]
Closing as likely UCRT not installed

**Comment by steveharter** [comment]
ptal @rakeshsinghranchi

**Comment by rakeshsinghranchi** [comment]
@Petermarcu , @leecow  - looking at https://github.com/dotnet/core-setup/issues/1842  , uCRT is expected to be the part of runtime.

**Comment by Petermarcu** [comment]
@janvorli @jkotas @jeffschwMSFT

**Comment by jkotas** [comment]
`dotnet.exe` is deployed to a different directory than the runtime. It means that it does not get to use uCRT that is part of the runtime.

**Comment by jkotas** [comment]
This looks like a mismatch in the build scripts:

- The cmake file for dotnet.exe explicitly specifies to link with static CRT: https://github.com/dotnet/core-setup/blob/master/src/corehost/cli/exe/exe.cmake#L6
- The global cmake file overrides this setting to pick up dynamic CRT: https://github.com/dotnet/core-setup/blob/master/src/settings.cmake#L191

**Comment by steveharter** [comment]
Per https://github.com/dotnet/corefx/issues/12858 I think the intent was to statically link to the CRT initialization code (libcmtd.lib, libvcruntime.lib) but dynamically link to the bulk (ucrt.lib)

>> The global cmake file overrides this setting to pick up dynamic CRT: https://github.com/dotnet/core-setup/blob/master/src/settings.cmake#L191

This removes libucrt.lib (static) and adds ucrt.lib (dynamic)

**Comment by steveharter** [comment]
However since ucrtbase.dll (ucrt.lib) is not co-located with dotnet.exe (it's in the netcoreapp runtime folder), Windows doesn't dynamically load it there and thus requires the uCRT to be installed globally (?)

**Comment by jkotas** [comment]
Correct.

The options to deal with this:
1. Require uCRT to be installed globally
2. Co-locate another copy of uCRT next to dotnet.exe
3. Statically link uCRT into dotnet.exe

**Comment by steveharter** [comment]
Does installing ucrtbase.dll and all of the related api-ms-win-core* dlls into netcoreapp folder have any value? (since they are loaded from global crt location). Should we be calling SetDllDirectory?

**Comment by CIPop** [comment]
@steveharter Unfortunately that only uncovers another issue on Win7 POS:

![image](https://user-images.githubusercontent.com/8635911/42909034-8b1c9516-8a97-11e8-8374-18b53f0a5778.png)

The link takes me to a generic .NET SDK download page (broken?).

**Comment by steveharter** [comment]
@CIPop can you clarify what you tried?

**Comment by CIPop** [comment]
I've installed uCRT from the link in this issue then ran dotnet --version in the Win7 POSReady7 VM.
I'm now trying to follow https://github.com/dotnet/cli/issues/3907 .

It would be nice to have all prerequisites in one place (maybe at the link presented by the above error message)?

**Comment by steveharter** [comment]
Are you trying to run an app or use the SDK? Do you have the SDK installed?

`dotnet --version` does require the SDK, since it tries to show the SDK version. `dotnet --info` will work without the SDK (but won't show SDK information of course)

**Comment by steveharter** [comment]
However you should never get the hostfxr.dll error using `dotnet --version` without the SDK - you should get a cleaner message.

**Comment by steveharter** [comment]
Currently installing the uCRT in netcoreapp folder doesn't appear to have any benefit since it's not used. 

So IMO we should either call SetDllDirectory(netcoreapp_dir) or stop installing the uCRT there. If we stop installing it we need to consider whether we still want to keep it for standalone, although it is only required for Windows 8.1\2012R2 and older.

So from @jkotas options above + SetDllDirectory option:
1. Require uCRT to be installed globally
  - The current state due to this issue, except for standalone apps. we propably want to stop installing into netcoreapp folder
2. Co-locate another copy of uCRT next to dotnet.exe
  - Would be pretty ugly, and we should still stop installing into netcoreapp folder
3. Statically link uCRT into dotnet.exe
  - Would make it very large, and unnecessary bloat for Windows10+
4. Call SetDllDirectory
  - Perhaps only on Win 8.1\2012 R2 and earlier to allow the "newest" OS patches to load on Windows 10+. This means we unnecessarily install the uCRT Windows 10+ though; ideally the installer would know whether to install the uCRT based on the version of Windows.

**Comment by jkotas** [comment]
> Would make it very large, and unnecessary bloat for Windows10+

Do you have any data about this? Statically linking CRT is not actually that bad size-wise.

> Call SetDllDirectory

I am not sure how this would work. We need the CRT for the .exe to start. We would probably need to split the dotnet.exe into a tiny CRT-free stub that calls SetDllDirectory and then loads dotnet.dll that would contain what dotnet.exe contains today.

**Comment by CIPop** [comment]
> @CIPop can you clarify what you tried?

I've installed .NET Core SDK from https://dot.net and ran dotnet --version on a [Win7 POSReady](https://www.microsoft.com/en-us/download/details.aspx?id=26558) VM. The Win7 POSReady comes with SP1. I checked: the `hostfxr.dll` file is in the lookup folder - there's some other issue.

Is this a known issue - any workarounds? The fwlink goes nowhere useful.

**Comment by steveharter** [comment]
@leecow can you help @CIPop out here? I will be OOF until Monday. Thanks

**Comment by steveharter** [comment]
@CIPop any update?

**Comment by CIPop** [comment]
@steveharter : @jkotas already answered by referencing #4388 - adding those two KBs worked.
