### ISSUE TITLE
Microsoft.Extensions.DependencyModel should be part of Microsoft.NETCore.App

### ISSUE THREAD

**Issue by davidfowl** [dotnet/core-setup#3232]
It's coupled to the shared host logic, so why isn't it a part of the platform package?

**Comment by weshaggard** [comment]
It could be put into Microsoft.NETCore.App but it isn't something that most applications need or use, it is only interesting for tooling scenarios. So let me flip the question to you why should we include it in the shared framework? We will still need a package for netstandard/desktop support.

**Comment by eerhardt** [comment]
It's not only interesting for tooling scenarios. ASP.NET MVC uses it at runtime to discover assemblies to probe for Controller classes.

However, I don't see the advantage of including it in NETCore.App either. @davidfowl can you elaborate?
