### ISSUE TITLE
Random build/restore/publish errors on docker. (returned a non-zero code: 139)

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#3233]
_From @djsowa on September 25, 2017 20:0_

## Steps to reproduce
```
FROM microsoft/dotnet:2.0-sdk

# Set working dir or docker to /app
WORKDIR /app

RUN dotnet --info
# Restore code dependecies - packages will be downloaded.
RUN dotnet new console -o ./src
RUN dotnet restore ./src --disable-parallel -v diag

# publish application(build included) into /app directory

RUN dotnet build ./src -v diag
RUN dotnet publish ./src --output /app -v diag

# run console application on docker.
ENTRYPOINT ["dotnet"]
```

## Expected  behavior

Build succesfully

## Actual behavior

I'm receiving random errors, some times error occur on restore, sometimes on build and sometime on publish step, now(update) occurred even on dotnet new step.

Restore:
> Service 'NAME' failed to build: The command '/bin/sh -c dotnet restore ./src --disable-parallel -v diag' returned a non-zero code: 139

Build:
> Service 'NAME' failed to build: The command '/bin/sh -c dotnet build ./src' returned a non-zero code: 139

New:

> The command '/bin/sh -c dotnet new console -o /app/src' returned a non-zero code: 139

[Diagnostic logs](https://pastebin.com/QdVH1XnR)

## Environment data
```
RUN dotnet --info
 ---> Running in 6b2d67b6fcd6
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

_Copied from original issue: dotnet/cli#7706_

**Comment by livarcocc** [comment]
@steveharter can you take a look? This is a crash in native code.

**Comment by livarcocc** [comment]
_From @djsowa on September 25, 2017 20:19_

Update: similar errors occurred also on:
microsoft/dotnet:latest
microsoft/dotnet:2.0-sdk-jessie

Addtional log from docker:

> [91m**Segmentation fault (core dumped)**
> [0mService 'NAME' failed to build: The command '/bin/sh -c dotnet new console -o /app/src' returned a non-zero code: 139
> Build step 'Execute shell' marked build as failure

**Comment by livarcocc** [comment]
Move back to the CLI if this turns out to be an issue in the CLI, but the error code indicates a native crash.

**Comment by steveharter** [comment]
So the segfault is from dotnet.exe on either restore, build, or publish?

@djsowa can you debug via gdb (or other debugger) to see what module \ function is being called that is causing the seg fault?

@MichaelSimons does this look familiar? Assuming docker-specific. I will attempt a local repro if others are encountering this.

**Comment by djsowa** [comment]
@steveharter  so far _Segmentation fault (core dumped)_ error appear only once. I try to reproduce and debug tomorrow.

**Comment by MichaelSimons** [comment]
@steveharter - I have not seen or heard of anyone encountering this before in Docker.

**Comment by sshulik** [comment]
got similar issue:
`"/usr/share/dotnet/sdk/2.0.0/Roslyn/RunCsc.sh" exited with code 134.`
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```
twice got `Segmentation fault`. also, few times getting managed exception, may be it will help to debug:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.PostBoxInitialization(IAsyncStateMachine stateMachine, MoveNextRunner runner, Task builtTask)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AwaitUnsafeOnCompleted[TAwaiter,TStateMachine](TAwaiter& awaiter, TStateMachine& stateMachine)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by alexlobanov** [comment]
Hi, 

I also get same issue.
usr/share/dotnet/sdk/2.0.0/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "/usr/share/dotnet/sdk/2.0.0/Roslyn/RunCsc.sh" exited with code 127. [/path/to/project.csproj]

I trying to build and push images to docker registry - using TFS CI/CD pipeline.

**Comment by Lordinaire** [comment]
Hello,

Same issue here when using a VSTS Build with .NET Core tasks (2.* preview).

**Comment by frasdav** [comment]
Same with me on Ubuntu 16.04 LTS doing a `dotnet publish`. It succeeds 1 time in 5 approx.

**Comment by jaredpar** [comment]
Looks like a crash in corefx / coreclr. This is in the runitme helpers, not the generated code (at least that i see)

**Comment by Petermarcu** [comment]
Yup, just saw csc a bunch of times and wanted to make sure you were aware and could correlate if you see other similar issues.

**Comment by Petermarcu** [comment]
@janvorli can you take a look?

**Comment by janvorli** [comment]
@frasdav do you mean that you are hitting the issue issue dotnet 2.0.0 sdk on Ubuntu 16.04 directly or inside the docker image as described in the issue description above?

**Comment by janvorli** [comment]
@djsowa what is your host OS in which you are running docker?

**Comment by janvorli** [comment]
I was asking about the host distro since I've ran dotnet restore inside of the microsoft/dotnet:2.0-sdk image 1000 times in a loop (deleting the ~/.nuget and ~/.dotnet folders before each iteration) and it never failed. My host distro was Ubuntu 14.04.

**Comment by djsowa** [comment]
Host OS was Ubuntu Server 16.04
Because I can't solve the issue I have delete this machine. 
@frasdav can you check for free space on the device used by docker, it could be the problem source on my machine.

**Comment by fbeauche** [comment]
I have similar issues on our build server with docker.
Host OS : Ubuntu 16.04.3 LTS

An interesting note is that we have two build agent. one of them is working fine and the other is failing. 
The microsoft/dotnet:2.0-sdk image on the working agent is 2 week old. 

On the agent that is failing, its the latest one as of today (created 6 hour ago)

**Comment by janvorli** [comment]
@fbeauche could you please check if both of the docker images you are using give you the same result if you run `dotnet --info` in them? 
And one more question - are both the agents running on the same server? If not, do the two servers have different configuration?

**Comment by fbeauche** [comment]
Its the same on both agents : 

`docker  run microsoft/dotnet:2.0-sdk dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d`

Our setup is an Jenkins server provisioning build agents on Azure.  
The agents thats working been provisionned 2 week ago and the one where its fail been provisionned 4 days ago. 

We did not change our Initialization between the two VMs, but we did change the VMs size from " Standard D2 v2" to " Standard D2 v3"

**Comment by frasdav** [comment]
@janvorli Not Docker, straight Ubuntu 16.04.3.

`.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d`

`Filesystem      Size  Used Avail Use% Mounted on
udev            2.0G     0  2.0G   0% /dev
tmpfs           394M   26M  368M   7% /run
/dev/sda1        30G  3.7G   26G  13% /
tmpfs           2.0G   16K  2.0G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/sdb1        20G   44M   19G   1% /mnt
tmpfs           394M     0  394M   0% /run/user/1000`

**Comment by prochan2** [comment]
I have similar same issue on Ubuntu Server 16.04 VM on Azure.

```
dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

```
$ dotnet new console
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /mnt/hwapp/hwapp.csproj...
  Restoring packages for /mnt/hwapp/hwapp.csproj...
  Generating MSBuild file /mnt/hwapp/obj/hwapp.csproj.nuget.g.props.
  Generating MSBuild file /mnt/hwapp/obj/hwapp.csproj.nuget.g.targets.
  Restore completed in 217 ms for /mnt/hwapp/hwapp.csproj.


Restore succeeded.

$ dotnet build
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/2.0.0/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "/usr/share/dotnet/sdk/2.0.0/Roslyn/RunCsc.sh" exited with code 134. [/mnt/hwapp/hwapp.csproj]

Build FAILED.

/usr/share/dotnet/sdk/2.0.0/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "/usr/share/dotnet/sdk/2.0.0/Roslyn/RunCsc.sh" exited with code 134. [/mnt/hwapp/hwapp.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.61
```

**Comment by janvorli** [comment]
Ok, it seems that all of you are hitting in on Ubuntu 16.04 host. I will install Ubuntu 16.04 and attempt to repro.

**Comment by janvorli** [comment]
I have tried to repro it on a local freshly installed Ubuntu 16.04 in Hyper-V VM and I was unable to repro it even after 1000 iterations of running that in a loop. So I am starting to think it has something to do with the Ubuntu 16.04 Azure VMs or the VM configuration. I will try to grab the Azure VM and attempt to repro it over there. @prochan2 what size of the Azure VM do you have (processor count, memory, ...)?

**Comment by prochan2** [comment]
@janvorli it's Standard F8s (8 Cores, 16 GB memory).

I have first installed .NET Core SDK 1.1.4 and then 2.0.0 without uninstalling 1.1.4.

**Comment by janvorli** [comment]
@prochan2  have you installed it using the package manager or from tarballs?

**Comment by prochan2** [comment]
@janvorli package manager

**Comment by fbeauche** [comment]
@janvorli i can confirm that the size of the Auzre VM seems to have an impact on my case.

It fail on "Standard D2 v3" but it work on "Standard D2 v2"

**Comment by cmjchrisjones** [comment]
This might be of help to someone, not quote the same error but I was getting 

> /usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.aspnetcore.mvc.razor.viewcompilation/2.0.0/build/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(60,5): error MSB3073: The command ""/usr/share/dotnet/dotnet" exec --runtimeconfig "/var/www/mycarparks/MyCarparks.Web/bin/Debug/netcoreapp2.0/MyCarparks.Web.runtimeconfig.json" --depsfile "/var/www/mycarparks/MyCarparks.Web/bin/Debug/netcoreapp2.0/MyCarparks.Web.deps.json" "/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.aspnetcore.mvc.razor.viewcompilation/2.0.0/build/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj/Debug/netcoreapp2.0/microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code 137. [/var/www/mycarparks/MyCarparks.Web/MyCarparks.Web.csproj] 

on an Ubuntu-16.04 server with DigitalOcean 512MB/1CPU,  [I googled just the exit code (137) which led me to an out of memory exception](https://www.google.co.uk/search?q=exited+with+code+137&oq=exit&aqs=chrome.1.69i57j69i59j0l4.2200j0j7&sourceid=chrome&ie=UTF-8)

I upgraded to 1GB/1CPU server and retried the build and it worked

**Comment by steveharter** [comment]
Closing as not able to repro. Possible out of memory. Please re-open if there is additional information.

**Comment by zw963** [comment]
This maybe one issue about linux kernel and docker, See:

https://github.com/gliderlabs/docker-alpine/issues/180

**Comment by krippz** [comment]
got same error
running on docker, using `mcr.microsoft.com/dotnet/core/runtime:3.0-bionic` image

during msbuild, publish stage we sometimes get
An error occurred when executing task 'Publish'
.NET Core CLI: Process returned an error (exit code 139)
