### ISSUE TITLE
Unable to compile with VS2017

### ISSUE THREAD

**Issue by steveharter** [dotnet/core-setup#3243]
## Steps to reproduce
Install VS 2017 without VS 2015

## Expected  behavior
Run the build command (master branch), no errors.

## Actual behavior
Run the build, the first error will contain text like:
```
 Calling "C:\git\coresetup\src\corehost\Windows\gen-buildsys-win.bat C:\Users\sharter\source\ vs2017 x64 eb60f0bf20c52b49032953763519d904b134c473 2.1.0-preview1-25719-0 2.1.0-preview1-25719-0.1.0-preview1-25719-0 2.1.0-preview1-25719 -0"
  CMake Error in CMakeLists.txt:
    No CMAKE_CXX_COMPILER could be found.
```

This can be worked around by changing the hard-coded version of VS in src\corehost\Windows\gen-buildsys-win.bat to `_VSString=15 2017` (yes we need a better way to set this for `14 2015` as well)

After this, there are issues with generating a vcxproj. Using the latest CMake 3.9.3 (some earlier versions have different errors):
```
   Project "C:\git\coresetup2\Bin\obj\win-x64.Debug\corehost\CMakeFiles\3.9.3\VCTargetsPath.vcxproj" on node 1 (default targets).
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(354,5): error MSB8013: This project doesn't contain the Configuration and Platform
combination of Debug|Win32. [C:\git\coresetup2\Bin\obj\win-x64.Debug\corehost\CMakeFiles\3.9.3\VCTargetsPath.vcxproj] [C:\git\coresetup2\src\corehost\build.proj]
      Done Building Project "C:\git\coresetup2\Bin\obj\win-x64.Debug\corehost\CMakeFiles\3.9.3\VCTargetsPath.vcxproj" (default targets) -- FAILED.
```

Also, previously building with VS2015 and VS2017 side-by-side resulted in [UWP errors](https://github.com/dotnet/core-setup/issues/3073). I'm not sure if this is addressed yet, as I've been building with just VS2015 installed.

**Comment by steveharter** [comment]
@weshaggard PTAL. Thanks

**Comment by weshaggard** [comment]
@steveharter you need to upgrade your version of CMake (not sure the min version) as the later versions have templates for VS2017.

**Comment by weshaggard** [comment]
I see you say you have 3.9.3 installed. I just checked and I have 3.8.2. Can you do cmake --help to verify if it has the "Visual Studio 15 2017" template?

Also what branch are you hitting this on?

**Comment by weshaggard** [comment]
both master and release/2.0.0 should work with VS2017 but I suspect other branches don't. The change to enable it looks like https://github.com/dotnet/core-setup/pull/2910. Are you building from a normal command prompt or a VS command prompt?

**Comment by steveharter** [comment]
I believe the key here is that I only have VS 2017 (no VS 2015). The code at https://github.com/dotnet/core-setup/blob/master/src/corehost/Windows/gen-buildsys-win.bat#L14 is hard-coding the CMake VS 2015 generator. When that is changed to VS 2017, then I get the errors mentioned earlier.

CMake 3.9.3 has the Visual Studio 15 1017 template. I'll try 3.8.2 and see if that helps.

On master branch.

Building from VS 2017 command prompt.

Having both VS 2015 and VS 2017 side-by-side will work if the UWP issue I mentioned earlier was resolved (which I believe was introduced after #2910), but VS2015 is used for generating projects...

**Comment by steveharter** [comment]
Update. With CMake 3.8.2 and no source changes I get a different compile error:
```
  Calling "C:\git\coresetup2\src\corehost\Windows\gen-buildsys-win.bat C:\Users\sharter\source\ vs2017 x64 6cc1cb9c74b5
  dc80ad40c8cd14136324b2ae4213 2.1.0-preview1-25728-0 2.1.0-preview1-25728-0 2.1.0-preview1-25728-0 2.1.0-preview1-2572
  8-0"
  "Computed RID for native build is win-x64"
  "C:\Program Files\CMake\bin\cmake.exe" C:\git\coresetup2\src\corehost\Windows\..  "-DCLI_CMAKE_RUNTIME_ID:STRING=win-
  x64" "-DCLI_CMAKE_HOST_VER:STRING=2.1.0-preview1-25728-0" "-DCLI_CMAKE_APPHOST_VER:STRING=2.1.0-preview1-25728-0" "-D
  CLI_CMAKE_HOST_FXR_VER:STRING=2.1.0-preview1-25728-0" "-DCLI_CMAKE_HOST_POLICY_VER:STRING=2.1.0-preview1-25728-0" "-D
  CLI_CMAKE_PKG_RID:STRING=win-x64" "-DCLI_CMAKE_COMMIT_HASH:STRING=6cc1cb9c74b5dc80ad40c8cd14136324b2ae4213" "-DCLI_CM
  AKE_PLATFORM_ARCH_AMD64=1" "-DCMAKE_INSTALL_PREFIX=C:/git/coresetup2/src/corehost/../../Bin/win-x64.Debug/corehost" "
  -DCLI_CMAKE_RESOURCE_DIR:STRING=C:\git\coresetup2\src\corehost\..\..\Bin\obj\win-x64.Debug\hostResourceFiles" -G "Vis
  ual Studio 14 2015 Win64"
  -- The C compiler identification is unknown
  -- The CXX compiler identification is unknown
  CMake Error in CMakeLists.txt:
    No CMAKE_C_COMPILER could be found.
```

Apparently it isn't finding the compiler as I look at CMakeError.log:
```
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler:  
Build flags: 
Id flags:  

The output was:
1
```

Note I can build the coreclr repro without issue.

**Comment by steveharter** [comment]
With CMake 3.8.2 the generated CCMakeCCCompilerID.c does reference an old build tools:
```
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```


When I create a new C++\General project within VS, I get this:
```
<Project DefaultTargets="Build" ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```

**Comment by steveharter** [comment]
Success(!) compiling if I remove the `-G` (generator) option in gen-buildsys-win.bat. At least it gets to compiling UWP, and then fails with same error. If I then change UWP's gen-buildsys-win.bat then I can get all the way through. I haven't diff'd the generated project files yet to see the differences.

**Comment by steveharter** [comment]
I switched back to CMake 3.9.3.

Took a peek at the generated vctargetspath.vcxproj diffs with and without -G generator. The one with -G (by CMake) has
```
		<ProjectConfiguration Include="Debug|x64">
```
while the one without -G has
```
		<ProjectConfiguration Include="Debug|Win32">
```
and other "x64"->"Win32" literal changes as well. If I force the Win32 in, it complains it can't find the compiler:
```
CMake Error in CMakeLists.txt:
  No CMAKE_C_COMPILER could be found
```

So when specifying the -G option, it appears CMake is broke with VS2017. It can't find the VS compiler. Without the -G option, CMake finds the VS compiler and works OK.

@weshaggard were you able to repro any of this?

**Comment by weshaggard** [comment]
I can repro the issue I'm going to try and find some time to root cause it and fix it.
