### ISSUE TITLE
Update shared framework to support .NET Standard 2.0

### ISSUE THREAD

**Issue by terrajobst** [dotnet/core-setup#325]
This is meant to be a tracking issue for adding the necessary support in order to support .NET Standard 2.0. We're still working on the details. I'll update this issue once we have the details sketched out.

**Comment by weshaggard** [comment]
This needs to include ValueTyple as well.

**Comment by weshaggard** [comment]
The 2.0 shared framework now has all the .NET Standard 2.0 support. We still have to work out a plan for ValueTuple.

**Comment by weshaggard** [comment]
I believe we have this all sort-out now so I'm closing. We have APICompat verification in corefx to catch any discrepancies.
