### ISSUE TITLE
Re-enable including source files in Microsoft.NETCore.App package during source-build

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#3269]
We are disabling including source files in Microsoft.NETCore.App package during source-build because of long path issues.

See https://github.com/dotnet/source-build/pull/206#issuecomment-334028708

If we start building with a build system that supports long paths, we can enable this again.  Or if the product requirements no longer need source files included in the symbols packages, we can just remove this all together.

/cc @ericstj @weshaggard @dagood

**Comment by dagood** [comment]
Closing: source files are no longer needed, and the transport packages from CoreCLR and CoreFX already don't include them. (We rely on SourceLink instead.)
