### ISSUE TITLE
Path is not added to `.zshrc` during the install of 2.0 (macOS: 10.13 (17A365))

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#3275]
@sushihangover reported this here: https://github.com/dotnet/core/issues/1009

The Install .NET and build your first app on macOS instructions at:

https://www.microsoft.com/net/core#macos
State:

This installer will install the latest stable version of the tools and put them on your PATH so you can run dotnet from the Console.
If you only a .profile and a .zshrc in your home dir, the path is not added during the install of 2.0 to either of these files and you must manually add /usr/local/share/dotnet/ yourself.

OS: macOS: 10.13 (17A365)

**Comment by rakeshsinghranchi** [comment]
As of today, dotnet adds to /etc/paths.d/dotnet
https://github.com/dotnet/core-setup/blob/master/src/pkg/packaging/osx/sharedhost/scripts/postinstall

**Comment by steveharter** [comment]
@rakeshsinghranchi is this fixed? Is so, please close it. Thanks

**Comment by rakeshsinghranchi** [comment]
will work on this for 2.1.0 Release. Moving to Post-ZBB.

**Comment by rakeshsinghranchi** [comment]
@sushihangover , it is assumed that profile owner manages the file on their own. Dotnet installer updates the global PATH variable and this PATH is expected to be exported in profile files.
