### ISSUE TITLE
Facades with references versioned 0.0.0.0 cause lots of issues for RAR

### ISSUE THREAD

**Issue by davidfowl** [dotnet/core-setup#3297]
So I was debugging the performance of msbuild's resolve assembly reference and it turns out that it is doing more work because our facade assemblies reference 0.0.0.0 versions of all their dependencies. What happens is that we give RAR a set of primary assemblies from:

%userprofile%\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0

Some of these assemblies are facades that have reference assemblies of version 0.0.0.0. As an example, here's what System.dll looks like in ILSpy:

![image](https://user-images.githubusercontent.com/95136/31432033-4e1ceaf2-ae2a-11e7-9259-6a3ec9bda5ec.png)

 This causes RAR to think that it's discovering new assemblies and as a result ends up walking the graph 23 times for a new .NET Core console project. This ends up adding 111 new "unresolved references" to the reference table that msbuild then attempts to resolve from various locations. 

Microsoft.NETCore.App is a full closure of assemblies and it should provide that closure to msbuild with the correct versions so that only a single pass in required.

/cc @ericstj @eerhardt @weshaggard @davkean @cdmihai

**Comment by davidfowl** [comment]
After some investigation, it turns out the references for Microsoft.NETCore.App are *not* a complete closure. We should figure out what the best course of action is here.

**Comment by davkean** [comment]
ouch.

**Comment by eerhardt** [comment]
@davidfowl - do you happen to have the list of which things aren't a complete closure?

**Comment by nguerrera** [comment]
IIRC, at one time, certain "design time facade" bits were shared by multiple platforms where the targets of the type forwards could have different versions. E.g. if you have an mscorlib that points to system.runtime 4.0.20.0 then you can't reuse that shim when system.runtime is 4.0.0.0. So mscorlib would be generated pointing everything at 0.0.0.0 but with type forwards to latest (dangling type forwards were considered ok).

I don't know if this reuse is still needed, but I don't think it is. These now ship inside the M.N.CA package, not in a separate portable compat package, right? If we generate facades that are specific to a particular M.NC.A, we can just use the real versions in the refs

**Comment by nguerrera** [comment]
https://github.com/dotnet/buildtools/blob/583046217f68333c04521e119e9cf97eca6f2494/src/GenFacades/GenFacades.Console/Program.cs#L43

**Comment by eerhardt** [comment]
It looks like we are setting that property in corefx:

https://github.com/dotnet/corefx/blob/ca49bfbfd64351fddba56f2141b90841b8561eb7/src/shims/shims.proj#L34

**Comment by weshaggard** [comment]
>After some investigation, it turns out the references for Microsoft.NETCore.App are not a complete closure. We should figure out what the best course of action is here.

The shared framework is closure complete for any implementation but for the facades they do have dangling type forwards (see our list of shims that are excluded from closure verification https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj#L23).  This is by design because we need the shims to be able to point to OOB libraries that we don't want to ship in the shared framework in order to maximize our compatibility with .NET Framework binaries. 

As Nick mentioned we intentionally choose 0.0.0.0 for the assembly version in these facades to enable them to work across different versions. It is potentially possible to update our tooling to use the exact version of the assemblies that ship in the shared framework but we cannot do the same for things that ship as nuget packages so we would still need to pick a minimal version for those. Instead of playing the game of trying to ensure we always have the minimal version we decided to use 0.0.0.0 everywhere by convention as that will enable them to at least try to work everywhere. 

@davidfowl I see you are saying that RAR has to do the closure walk 23 times but what does that look like performance wise? Do you have any performance numbers that shows this being a real issue? If not I think we will continue to stick with our 0.0.0.0 versioning scheme. Also even if we did pick new minimum versions they would only help us for one release and as soon we shipped another OOB at least a set of them would still need to unify.

**Comment by weshaggard** [comment]
I should call out as part of our compat work we are doing currently there is a good chance we are also going to ship update to these facades in a nuget package and in that world it becomes even more interesting to try and find the correct minimal assembly version to use.

**Comment by davkean** [comment]
Yes, RAR is an issue. It's 14% of the build in some situations.

**Comment by weshaggard** [comment]
>Yes, RAR is an issue. It's 14% of the build in some situations.

**Comment by davidfowl** [comment]
> @davidfowl I see you are saying that RAR has to do the closure walk 23 times but what does that look like performance wise? Do you have any performance numbers that shows this being a real issue? If not I think we will continue to stick with our 0.0.0.0 versioning scheme. Also even if we did pick new minimum versions they would only help us for one release and as soon we shipped another OOB at least a set of them would still need to unify.

Here are some results from my machine. Very unscientific:

Today:

```
Task Performance Summary:
        1 ms  GetAssemblyVersion                         1 calls
        2 ms  Delete                                     1 calls
        3 ms  ConvertToAbsolutePath                      1 calls
        3 ms  RemoveDuplicates                           2 calls
        3 ms  CheckForTargetInAssetsFile                 1 calls
        3 ms  Hash                                       2 calls
        3 ms  FindAppConfigFile                          1 calls
        3 ms  AssignCulture                              1 calls
        4 ms  CheckForDuplicateItems                     3 calls
        5 ms  GetFrameworkPath                           1 calls
        5 ms  ReadLinesFromFile                          1 calls
        7 ms  AssignTargetPath                           5 calls
        8 ms  WriteLinesToFile                           2 calls
       12 ms  MSBuild                                    1 calls
       13 ms  MakeDir                                    1 calls
       16 ms  Copy                                       2 calls
       20 ms  Message                                    3 calls
       25 ms  FindUnderPath                              5 calls
       26 ms  ResolvePackageFileConflicts                1 calls
       35 ms  ProduceContentAssets                       1 calls
       42 ms  CheckForImplicitPackageReferenceOverrides   1 calls
       60 ms  Telemetry                                  1 calls
      101 ms  ResolvePackageDependencies                 1 calls
      341 ms  ReportAssetsLogMessages                    1 calls
     1536 ms  ResolveAssemblyReference                   1 calls
```

After a code change to assume everything is unified:

```
Task Performance Summary:
1 ms  GetAssemblyVersion                         1 calls
2 ms  AssignTargetPath                           5 calls
2 ms  RemoveDuplicates                           2 calls
2 ms  FindAppConfigFile                          1 calls
2 ms  AssignCulture                              1 calls
3 ms  CheckForTargetInAssetsFile                 1 calls
4 ms  Delete                                     1 calls
4 ms  ReadLinesFromFile                          1 calls
4 ms  CheckForDuplicateItems                     3 calls
6 ms  WriteLinesToFile                           2 calls
7 ms  ConvertToAbsolutePath                      1 calls
8 ms  GetFrameworkPath                           1 calls
9 ms  MakeDir                                    1 calls
11 ms  Hash                                       2 calls
11 ms  MSBuild                                    1 calls
13 ms  Copy                                       2 calls
14 ms  Message                                    3 calls
21 ms  FindUnderPath                              5 calls
25 ms  ResolvePackageFileConflicts                1 calls
38 ms  ProduceContentAssets                       1 calls
39 ms  CheckForImplicitPackageReferenceOverrides   1 calls
49 ms  Telemetry                                  1 calls
109 ms  ResolvePackageDependencies                 1 calls
352 ms  ReportAssetsLogMessages                    1 calls
826 ms  ResolveAssemblyReference                   1 calls
```

**Comment by weshaggard** [comment]
>After a code change to assume everything is unified:

What assumptions did you make to unify these? There will definitely still require some amount of unification.

If I produce you a set of shims with matching versions of stuff in .NET Core 2.0 would you be able to run your experiment again?

**Comment by davidfowl** [comment]
> What assumptions did you make to unify these? There will definitely still require some amount of unification.

Why would they require unification in the default case if we have a complete closure (Assuming no dangling references).

> If I produce you a set of shims with matching versions of stuff in .NET Core 2.0 would you be able to run your experiment again?

Yes.

**Comment by davidfowl** [comment]
I should make it more clear what I did, the algorithm to expand the dependency closure in RAR keeps going until it has found no more dependencies. I changed it to ignore dependencies that aren't in the original set. I didn't skip conflict resolution or assembly unification.

**Comment by davkean** [comment]
WIth: https://github.com/Microsoft/msbuild/issues/1276 now in, ResolveAssemblyReference is officially the slowest target by far followed closely behind by _HandlePackageFileConflicts.

**Comment by dagood** [comment]
Closing: this issue looks stale. I believe the netcoreapp packages provide files that contain information making this faster in more recent versions of .NET Core.
