### ISSUE TITLE
Add tests for the Host

### ISSUE THREAD

**Issue by brthor** [dotnet/core-setup#33]
cc @schellap Let's figure out the base set of activations

**Comment by schellap** [comment]
I will take a look at this, this week.

**Comment by schellap** [comment]
@brthor, could you please comment on what all exists in the CLI repo and can be ported over?

## Primary tests
### Activation Tests
1. Published Standalone app activation
2. Published Portable app activation
3. Dotnet run activation of standalone app
4. Dotnet run activation of portable app
5. Dotnet test of standalone app
6. Dotnet test of portable app
7. Dotnet extension activation

Portable and Standalone apps should have native and culture resources

### Real World tests
Kestrel Server x (Standalone + Portable + XUnit + dotnet run)

### Seconday tests
#### SDK Selection

#### FX selection
--fx-version
runtimeconfig.json

#### Runtime Configuration Tests

**Comment by brthor** [comment]
@schellap for 1,2,3,4 we could copy over a standalone and portable test asset.

If we restore these against the built Microsoft.NETCore.App package, then this will also encompass #34 

Well need to manually copy over an sdk directory from the downloaded cli and patch together a stage2 like directory with the currently built host + sharedfx. 

for 5,6 I think we should create new, targetted projects. We don't have any specific tests for these scenarios that I know of. 

for 7, we can port the dotnet-hello test from dotnet.Tests in cli, but there is an additional setup step to dotnet pack it before testing activation. In the cli we do this in the build, but if possible we should actually do this in the individual test so it doesn't have a dependency on the build.

**Comment by schellap** [comment]
Really appreciate. I will sync with you in an hour. We might have to do it before we freeze, so we can divvy up.

**Comment by brthor** [comment]
#97 covers all cases except point 7 above.

**Comment by brthor** [comment]
Leaving this open to track additional tests which should be added.

**Comment by jeffschwMSFT** [comment]
Closing this issue.  We have other mechanisms tracking the need for better tests in the host area.
