### ISSUE TITLE
RuntimeEnvironment.GetRuntimeIdentifier returns invalid RID on High Sierra.

### ISSUE THREAD

**Issue by sbomer** [dotnet/core-setup#3301]
On OSX High Sierra, the api [RuntimeEnvironment.GetRuntimeIdentifier](https://github.com/dotnet/core-setup/blob/9dff3ce12574699e6d4d31722047f775d92d05fd/src/managed/Microsoft.DotNet.PlatformAbstractions/RuntimeEnvironment.cs#L30) returns "osx.10.13-x64", a RID that doesn't exist (see [runtime.json](https://github.com/dotnet/corefx/blob/529a6ce5bf086986dc421c6ddf5532fab2c8c3ad/pkg/Microsoft.NETCore.Platforms/runtime.json)).

I was using this API to determine the current platform, in order to automate testing of self-contained apps. In practice it appears that using "osx.10.12-x64" works for High Sierra, but we should figure out what the desired behavior is - either this API needs to return osx.10.12-x64 on High Sierra, or we need to introduce the RID osx.10.13-x64.

**Comment by Petermarcu** [comment]
The right thing to use for your self contained application is actually osx-x64. We've moved away from specific rids for the general case.

That said, the rid graph is getting out of date and should be updated to list all the supported OS's.

**Comment by steveharter** [comment]
Closing as not actionable

**Comment by nguerrera** [comment]
I think this should be reopened. The API should not return RIDs that aren't valid.

**Comment by eerhardt** [comment]
`osx.10.13` was added in https://github.com/dotnet/corefx/pull/26439.

For futurizing RIDs, @ericstj has opened https://github.com/NuGet/Home/issues/5862 which is not getting any traction.

Closing as this specific issue is resolved.
