### ISSUE TITLE
Consider using Assembly.CodeBase instead of Assembly.Location when looking for deps file

### ISSUE THREAD

**Issue by pranavkm** [dotnet/core-setup#3308]
Original issue for context: https://github.com/aspnet/Mvc/issues/6613

With shadow copy enabled, `Assembly.Location` doesn't point to the path containing the deps file. Consequently `DependencyContextLoader` can no longer discover the deps file: https://github.com/dotnet/core-setup/blob/master/src/managed/Microsoft.Extensions.DependencyModel/DependencyContextLoader.cs#L118. Using `Assembly.CodeBase` should reliably discover files in this case.

**Comment by eerhardt** [comment]
@pranavkm - is this something that needs to be fixed for .NET Core 2.1?

Can the issue be resolved with just adding another check for `Assembly.CodeBase` after the check for `Assembly.Location` fails?

**Comment by pranavkm** [comment]
> is this something that needs to be fixed for .NET Core 2.1?

We've been recommending disabling shadow copying any time you need to work with deps file (e.g. test runners), but it's not happy path with a non trivial way to figure out why it went wrong. 

> Can the issue be resolved with just adding another check for Assembly.CodeBase after the check for Assembly.Location fails?

That seems like a reasonable idea.

**Comment by drauch** [comment]
> We've been recommending disabling shadow copying any time you need to work with deps file (e.g. test runners), but it's not happy path with a non trivial way to figure out why it went wrong.

Aaaand...there's the argument that whenever you work with test runners you actually benefit a lot from shadow copying and recommending to disable it isn't such a great thing :-)
