### ISSUE TITLE
%PROGRAMFILES%\dotnet\store is used even when DOTNET_MULTILEVEL_LOOKUP is off

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#3315]
## Steps to reproduce
Install .NET Core SDK 2.0 preview1 (which has a runtime store with Newtonsoft.Json v9.0.1in it).
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.0.0-preview1-005977/dotnet-dev-win-x64.2.0.0-preview1-005977.exe
Run `Muxer_Activation_With_Templated_AdditionalProbingPath_Succeeds` test in the `release/2.0.0` branch.

## Expected  behavior
The test should pass no matter what is installed on the machine.

## Actual behavior
The test fails because it expects Newtonsoft to be loaded from the local store directory that was created during the test.  However, it is being loaded from %PROGRAMFILES%, which breaks the test since it is testing the loading is working correctly.

## Notes
Even if I add

`.EnvironmentVariable("DOTNET_MULTILEVEL_LOOKUP", "0")`

to the test, it still fails.  This is because the product is not respecting this setting when resolving `store` locations.

We need to fix the product to respect this setting and fix the test to disable multilevel lookup.

@steveharter

**Comment by steveharter** [comment]
Is CI not running?

**Comment by eerhardt** [comment]
CI is running.  But they don't have .NET Core SDK 2.0 installed on the machines.

**Comment by steveharter** [comment]
@eerhardt the repro steps need to be extended I am still unable to repro.

However I can repro if I manually create a `C:\Program Files\dotnet\store\x64\netcoreapp2.1` directory with the newtonsoft. My repository where I am running tests is a 2.1 preview and thus it is looking only in the store's 2.1 location (not 2.0).

I believe this issue is a subset of https://github.com/dotnet/core-setup/issues/1553 where we want to fix up tests to ignore other global locations as well including servicing location.

Without adding a C:\Program Files\dotnet\store\x64\netcoreapp2.1 directory this is what I get:
```
c:\git\coresetup\Bin\obj\win-x64.Debug\sharedFrameworkPublish\dotnet.exe exec --additionalprobingpath "C:\git\coresetup\Bin\tests\win-x64.Debug\20\PortableApp\store/|arch|/|tfm|" C:\git\coresetup\Bin\tests\win-x64.Debug\20\PortableApp\bin\PortableApp.dll
```
with output
```
Deps file: 
Additional probe dir: C:\git\coresetup\Bin\tests\win-x64.Debug\20\PortableApp\store\x64\netcoreapp2.1
-- arguments_t: own_path='C:\git\coresetup\Bin\obj\win-x64.Debug\sharedFrameworkPublish\dotnet.exe' app_dir='C:\git\coresetup\Bin\tests\win-x64.Debug\20\PortableApp\bin\' deps='C:\git\coresetup\Bin\tests\win-x64.Debug\20\PortableApp\bin\PortableApp.deps.json' core_svc='C:\Program Files (x86)\coreservicing' mgd_app='C:\git\coresetup\Bin\tests\win-x64.Debug\20\PortableApp\bin\PortableApp.dll'
-- arguments_t: probe dir: 'C:\git\coresetup\Bin\tests\win-x64.Debug\20\PortableApp\store\x64\netcoreapp2.1'
-- arguments_t: dotnet shared store: 'C:\git\coresetup\Bin\obj\win-x64.Debug\sharedFrameworkPublish\store\x64\netcoreapp2.1'
-- arguments_t: global shared store: 'C:\Program Files\dotnet\store\x64\netcoreapp2.1'
Using C:\git\coresetup\Bin\obj\win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-preview1-25816-0\Microsoft.NETCore.App.deps.json FX deps file
Using C:\git\coresetup\Bin\tests\win-x64.Debug\20\PortableApp\bin\PortableApp.deps.json deps file

...

Processing TPA for deps entry [Newtonsoft.Json, 9.0.1, lib/netstandard1.0/Newtonsoft.Json.dll]
  Considering entry [Newtonsoft.Json/9.0.1/lib/netstandard1.0/Newtonsoft.Json.dll] and probe dir [C:\git\coresetup\Bin\obj\win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-preview1-25816-0]
    Skipping... probe in deps json failed
    Skipping... not found in probe dir 'C:\git\coresetup\Bin\obj\win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-preview1-25816-0'
  Considering entry [Newtonsoft.Json/9.0.1/lib/netstandard1.0/Newtonsoft.Json.dll] and probe dir []
    Local path query did not exist C:\git\coresetup\Bin\tests\win-x64.Debug\20\PortableApp\bin\Newtonsoft.Json.dll
    Skipping... probe in deps dir 'C:\git\coresetup\Bin\tests\win-x64.Debug\20\PortableApp\bin\' failed
    Skipping... not found in probe dir ''
  Considering entry [Newtonsoft.Json/9.0.1/lib/netstandard1.0/Newtonsoft.Json.dll] and probe dir [C:\git\coresetup\Bin\tests\win-x64.Debug\20\PortableApp\store\x64\netcoreapp2.1]
    Relative path query exists C:\git\coresetup\Bin\tests\win-x64.Debug\20\PortableApp\store\x64\netcoreapp2.1\newtonsoft.json\9.0.1\lib\netstandard1.0\Newtonsoft.Json.dll
    Probed package dir and matched 'C:\git\coresetup\Bin\tests\win-x64.Debug\20\PortableApp\store\x64\netcoreapp2.1\newtonsoft.json\9.0.1\lib\netstandard1.0\Newtonsoft.Json.dll'
Adding tpa entry: C:\git\coresetup\Bin\tests\win-x64.Debug\20\PortableApp\store\x64\netcoreapp2.1\newtonsoft.json\9.0.1\lib\netstandard1.0\Newtonsoft.Json.dll
```

**Comment by eerhardt** [comment]
Good point.  I'm working in the `release/2.0.0` branch.  Updated the repro steps.
