### ISSUE TITLE
[Proposal] : Enable building distro agnostic Debs and RPMs for Dotnet Runtime and upstream packages

### ISSUE THREAD

**Issue by rakeshsinghranchi** [dotnet/core-setup#3325]
**Problem :**
Building native installer for a new distro ( and/or version ) is extremely difficult as it requires changes in all the repos where Dotnet installers are produced ( Runtime|Aspnetcore|SDK ).

**Description:**
As of today , .NET Core builds Distro and Version specific Debs (Ubuntu 14.04, 16.04, & 17.04, Debian 8 & 9 ) and RPMs for Runtime, SDK and Aspnetcore . Dotnet Core Runtime , SDK and Aspnetcore packages are built in their respective repo. SDK package exhibits dependency on Runtime and Aspnetcore packages. Runtime package carries portable payload and exhibits system dependencies.These system dependencies ( or packages ) are Distro/version dependent ( for .e.g libss1.0.2 in Debian.9 and libssl1.0.0 in debian.8) .  Thus, it is the forcing factor to build distro and version specific runtime deb packages and thus, upstream packages. 

**Currently :** 
dotnet-host **-->**  libc6 
dotnet-hostfxr **-->** depends on dotnet-host  and libc6
dotnet-runtime **-->** depends on dotnet-hostfxr and [ distro and version specific system packages including libicuxx and libssl1.x.x] 
dotnet-sdk **-->** dotnet-runtime, aspnetcore-store

**Proposal :** 
**[new]** dotnet-runtime-deps **-->** depends on system packages [distro specific system packages like libicuxx and libssl1.x.x]
dotnet-host **-->** depends on dotnet-runtime-deps
dotnet-hostfxr --> depends on dotnet-host
dotnet-runtime --> depends on dotnet-hostfxr 
dotnet-sdk --> depends on dotnet-runtime,aspnet-store

**Solution:**
Build dotnet-runtime-deps package for each Distro & Version . Package name should be Distro/Version diagnostic . Dotnet Runtime ( dotnet-host package specifically ) exhibits dependency on this package and rest all upstream packages are built only once for each package type ( one deb and one rpm ) .

This will enable us to add new distro installer by just building the corresponding dotnet-runtime-deps package and there would be no change required in the upstream branches. During package upload to distro repo feeds, common Runtime and upstream packages will be uploaded along with matching dotnet-runtime-deps package. 

**Feed upload to a distro would include for e.g ubuntu14.04 :**

**Runtime:**
1. dotnet-runtime-deps ( corresponding to matching distro & version ) . for e.g. dotnet-runtime-deps-2.2.0-ubuntu.14.04-x64.deb
2. dotnet-host-2.2.0-x64.deb
3. dotnet-hostfxr-2.2.0-x64.deb
4. dotnet-runtime-2.2.0-x64.deb
**SDK:**
5. dotnet-sdk-2.2.0-x64.deb
**ASPNetCore:**
6. aspnetcore-store-2.2.0-x64.deb

**Comment by rakeshsinghranchi** [comment]
cc @Petermarcu  @leecow @eerhardt @wli3

**Comment by leecow** [comment]
cc @omajid @tmds

**Comment by leecow** [comment]
> built only once for each package type ( one deb and one rpm )

We may need to be more granular than one per 'platform' but that requirement needs to be investigated. IE for RPMs, is the system dependency list the same for CentOS, Fedora OpenSUSE and SLES? I know we have something wrong in our RPM authoring today that misbehaves on SUSE (https://github.com/dotnet/core-setup/issues/3107).

**Comment by rakeshsinghranchi** [comment]
System dependency list will be different for distro and version. That is why per proposal , a new runtime-deps package will install system dependencies for each distro & version. Thus, runtime and upstream packages will be distro and version agnostic. Users will need to install matching runtime-deps package for their distro/version and then Dotnet Core packages.  

I have already commented on the issue and its resolution for SUSE #3107

**Comment by Petermarcu** [comment]
@rakeshsinghranchi how is this going ? I'm also considering whether we can backport this to 2.0.X so we can get to a consistent story with shared deps across all these versions.

**Comment by rakeshsinghranchi** [comment]
As of today, we are building standalone deps packages in master branch for Ubuntu and Debian . @leecow and I have decided to move ahead with the current proposal and start implementing it. Will start working on this sometime this week or early next week.

**Comment by Petermarcu** [comment]
Great. This came up in a conversation yesterday about build times because we have to spin up so many containers. This should allow us to do far less right?

**Comment by rakeshsinghranchi** [comment]
>Great. This came up in a conversation yesterday about build times because we have to spin up so many containers. This should allow us to do far less right?
Yes, will be based on single docker image . As of today, It takes 17mins to build & publish all debian installers. With the proposed change, it will reduce to 6:30mins. This doesn't account for portable building binaries. PR: https://github.com/dotnet/core-setup/pull/3487

**Comment by rakeshsinghranchi** [comment]
@leecow , is there anything pending for this issue ? we have distro agnostic runtime packages for debs and rpms now. Let me know if it's fine to close this issue . Thanks.

**Comment by leecow** [comment]
The only thing I see that should be adjusted are the linux mint packages. Currently building `linuxmint.7` and `linuxmint.8`. Version numbers should be 17 and 18.

**Comment by rakeshsinghranchi** [comment]
Do we need this package at all ? I thought we wanted to re-purpose matching ubuntu feeds for Linux Mint.  Sent a PR for release/2.1 ( https://github.com/dotnet/core-setup/pull/3979 ) . Merged a PR for master branch though.

**Comment by Petermarcu** [comment]
I was going to ask the same thing. I don't see why we need mint packages.

**Comment by rakeshsinghranchi** [comment]
@leecow , are we fine closing this issue now ? PR : https://github.com/dotnet/core-setup/pull/3981 takes care of stop building Linux Mint packages.

**Comment by leecow** [comment]
Yes, thanks.
