### ISSUE TITLE
Bad help "--version"

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#3332]
_From @HarelM on October 21, 2017 21:17_

## Steps to reproduce
run `dotnet` from command line.
this outputs:
Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help            Display help.
  --version         Display version.

path-to-application:
  The path to an application .dll file to execute.

Then run `dotnet --version`
To receive:
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

## Expected  behavior
Either --version will work or -- version will not appear in the help.

## Actual behavior
Irrelevant error message - turn out I needed to use --info instead of --version

## Environment data
`dotnet --info` output:
Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

_Copied from original issue: dotnet/cli#7881_

**Comment by livarcocc** [comment]
@steveharter This help is displayed by the host. I am moving this issue to core-setup.

**Comment by steveharter** [comment]
With 2.1, current help is now:
```
  -h|--help         Display help.
  --version         Display the current SDK version.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.
```

`--version` will still fail when there is no SDK

`--info` is not shown (but should be)

Also see https://github.com/dotnet/core-setup/issues/3502

**Comment by steveharter** [comment]
Along with fixing the help for --info we should fix the help so that --list-runtimes and --list-sdks do not appear twice when the SDK is installed (in Options: and host-options:)
