### ISSUE TITLE
Handling of DOTNET_MULTILEVEL_LOOKUP is inconsistent

### ISSUE THREAD

**Issue by noahfalk** [dotnet/core-setup#3360]
## Steps to reproduce

install a private version of dotnet (such as with Install-Dotnet.ps1) and delete its store
set DOTNET_SHARED_STORE to a non-existent directory (this simulates a dev making a mistake setting up their environment)
set DOTNET_MULTILEVEL_LOOKUP=0
Run a dotnet app

## Expected  behavior

Running the app will fail to load assemblies at runtime, or they will load from IL images in the privately installed dotnet folder

## Actual behavior

Running the app loads images from the machine global store

## Environment data
dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   F:\github\JitBench\.dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

# Comments

I noticed this while reading the code when I was debugging another issue. I did legitimately set DOTNET_SHARED_STORE incorrectly and then noticed that not only was the private dotnet install store on the probing path but the global store was also on the path. The purpose of DOTNET_MULTILEVEL_LOOKUP is to avoid doing these fallbacks into the global directory, but the policy for the store is not consistent with the policy for other lookups. I note the difference between:

https://github.com/dotnet/core-setup/blob/master/src/corehost/common/utils.cpp#L292
and
https://github.com/dotnet/core-setup/blob/master/src/corehost/cli/fxr/fx_muxer.cpp#L598

I can't see any reason these accesses would deserve different policy. The harder it is to prevent unwanted global resolutions, the more difficult it is to create highly reproducible scenarios for development, testing, and bug reporting.

**Comment by steveharter** [comment]
This should be fixed in 2.1 via https://github.com/dotnet/core-setup/issues/3315

I am considering porting the fix to a 2.0.x patch release, although in some edge cases it could break an existing app that is taking a dependency on that behavior. Thoughts?

**Comment by noahfalk** [comment]
Personally I'm happy knowing that its fixed in 2.1. Until then its not a blocker for me, just something we have to be careful about. Feel free to close this issue unless you believe there are other scenarios that would really benefit from this in the 2.0.0 timeframe. Thanks!

**Comment by steveharter** [comment]
Closing this; currently no plans to port to 2.0.x due to potential to break existing apps
