### ISSUE TITLE
What to depend on when distributing debian package for .net core app?

### ISSUE THREAD

**Issue by LHCGreg** [dotnet/core-setup#3362]
If I want to distribute a Debian package for a framework-dependent (not self-contained) .net core app, I could have the package depend on the dotnet-runtime-2.0.0 package. But what happens when .net core 2.1.0 comes out? Will that be a new dotnet-runtime-2.1.0 package even if there are no breaking changes? If that is the case, what would happen if someone who has 2.1.0 installed tried to install my package (that came out before 2.1.0)? It would try to install 2.0.0 on their system that already has 2.1.0, wouldn't it? Is that even possible?

Is there any official guidance on distributing .net core applications yet?

**Comment by Petermarcu** [comment]
.NET Core 2.0 and 2.1 will install side by side. That means people that install your package would still get 2.0 which is what you want. Even if there are no intentional breaking changes, it is preferable to run your application on the framework that you tested it on. If in the future, you want to move your app forward and depend on a newer version, that is fine too.

**Comment by LHCGreg** [comment]
So if someone has the 2.0 and the hypothetical future 2.1 debian packages installed at once, there's still just one /usr/bin/dotnet and whether 2.0 or 2.1 was installed first, it knows to use the 2.0 runtime and libraries for apps compiled against 2.0 (and earlier?) and the 2.1 runtime and libraries for apps compiled against 2.1. Am I understanding that correctly?

**Comment by Petermarcu** [comment]
That's right.

**Comment by LHCGreg** [comment]
Cools, thanks. 👍

**Comment by Petermarcu** [comment]
I think this could definitely be doc'd better. If you have thoughts of where you would have looked to find this information, we can open an issue to make sure we get something written up.

**Comment by LHCGreg** [comment]
https://www.microsoft.com/net/learn/get-started/linuxdebian or https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x would be good places I think.
