### ISSUE TITLE
RHEL 6 official builds don't work with crossgen enabled

### ISSUE THREAD

**Issue by janvorli** [dotnet/core-setup#3377]
For some reason, when using Core-Setup-Linux-BT in the official build instead of the Core-Setup-Linux-Arm-BT as the related "Name" element, the build fails when trying crossgen some files. The issue is that it tries to use crossgen from transport.runtime.linux-x64.microsoft.netcore.runtime.coreclr instead of the one from the rhel.6-x64 package.
We need to investigate and fix that.

**Comment by steveharter** [comment]
Is this causing the current build failures in master?
```
/root/coresetup/src/pkg/projects/Microsoft.NETCore.App/src/Microsoft.NETCore.App.depproj(262,5): error MSB3073: The command "/root/coresetup/packages/transport.runtime.linux-x64.microsoft.netcore.runtime.coreclr/2.1.0-preview1-25901-01/tools/crossgen @/root/coresetup/Bin/obj/linux-x64.Release/Microsoft.NETCore.App/linux-x64/linux-x64/crossgen/Microsoft.CSharp.rsp" exited with code 1.
```

**Comment by steveharter** [comment]
@janvorli is this still an active issue?
