### ISSUE TITLE
Maintaining nuget packages to build core-setup, coreclr and corefx

### ISSUE THREAD

**Issue by hqueue** [dotnet/core-setup#3396]
We are publishing nuget packages at https://tizen.myget.org/gallery/dotnet-core to build core-setup, coreclr and corefx for Tizen from master and 2.0.0 branch.

And each package has a lot of versions and number of version is ever increasing.
For example, we have more than 100 versions for 2.1.0-preview2 for
https://tizen.myget.org/feed/dotnet-core/package/nuget/runtime.tizen.4.0.0-armel.Microsoft.NETCore.App package.

Becuase they are consuming our myget storage, we want to keep only
necessary versions and remove unnecessary versions if possible.

AFAIK we don't need all of them and only need recent versions
to build master and 2.0.0 branch of core-setup, coreclr and corefx, right ?

One possible candidate was to maintain only fixed # of versions for master and 2.0.0 branch.
But we are not sure about this.

Does anybody have idea how to maintain necessary packages ?

Any suggestion or comment will be appreciated. Thanks!

**Comment by hqueue** [comment]
@eerhardt Do you have any idea? I'm asking this to you, because it is related to build infra (including CI) in core-setup, coreclr and corefx for Tizen.
Or can you ping someone who may know this issue?

**Comment by eerhardt** [comment]
Microsoft keeps all of our previous builds, and yes it takes up a lot of space.

I think it would be fine to purge extremely old builds.  For example, 1.0.0-preview/servicing and 1.1.0-preview/servicing builds shouldn't ever be needed anymore.  But I'd have a way to ensure you can mark a build as "keep forever" so it doesn't get purged.  For example, publicly released preview/RC builds - you'd want to keep those.

@weshaggard @markwilkie - any thoughts?

**Comment by hqueue** [comment]
Thanks for the information :)

> I think it would be fine to purge extremely old builds. For example, 1.0.0-preview/servicing and 1.1.0-preview/servicing builds shouldn't ever be needed anymore. But I'd have a way to ensure you can mark a build as "keep forever" so it doesn't get purged. For example, publicly released preview/RC builds - you'd want to keep those.

I see.  We are going to "pin" those packages required to build stable and pre-released versions.

@eerhardt One difficulties here is how to figure out required packages from source code of core-setup, coreclr and corefx. Is there any way to do this ?

**Comment by eerhardt** [comment]
I'm not sure I know of a good way.  My first start would be to ensure all the released builds were pinned.  For that, I'd look through the [release notes](https://github.com/dotnet/core/tree/master/release-notes) and through:

* https://github.com/dotnet/core-setup/releases
* https://github.com/dotnet/core-setup/tags

for each repo.

**Comment by weshaggard** [comment]
>One difficulties here is how to figure out required packages from source code of core-setup, coreclr and corefx. Is there any way to do this ?

**Comment by hqueue** [comment]
> I'm not sure I know of a good way. My first start would be to ensure all the released builds were pinned. For that, I'd look through the release notes and through:

@eerhardt Thanks for the suggestion. We will try to keep those versions and required packages.

> There isn't a good way. The best you can really do is look at download stats but even that isn't great. Also for servicing releases which don't build often you don't know what they are using in all cases.

@weshaggard Thank you for the opinion. We will consider download stats too. Thanks.

One idea we are going to try is
- (1) build a specific `version X`  which we will keep forever
- (2) and track all `nupkg` restored from our (Tizen) myget, i.e. https://tizen.myget.org/gallery/dotnet-core
- (3) And then keep above `nupkg`forever :)

By doing this, we hope we can build important `version X` without problem afterward.
What do you think of it ?

We also are looking  into [dependencies.props](https://github.com/dotnet/core-setup/blob/master/dependencies.props) to figure out required version, but not successful by now.

**Comment by weshaggard** [comment]
>We also are looking into dependencies.props to figure out required version, but not successful by now.

Yeah that changes overtime so different branches have different versions as well does different repos. That isn't the best way to figure this out.

One strategy we are considering is to look at the last download time and if it hasn't been downloaded in certain time, say one month, then we pull it from the feed and just put it in an archive location in case we need to restore it. We can keep it in the archive location for some amount of time, perhaps a year, and then purge it if we didn't need to restore it to the feed. This is sort of a layered caching strategy.

**Comment by hqueue** [comment]
> One strategy we are considering is to look at the last download time and if it hasn't been downloaded in certain time, say one month, then we pull it from the feed and just put it in an archive location in case we need to restore it. We can keep it in the archive location for some amount of time, perhaps a year, and then purge it if we didn't need to restore it to the feed. This is sort of a layered caching strategy.

It can be also a candidate approach for us too. We will take into account this approach too. Thanks!

**Comment by hqueue** [comment]
Closing this issue, because there seems to be no perfect solution and several alternative approaches were suggested, and it seems to be enough by now.

Thank you all for the feedback!
