### ISSUE TITLE
Cannot find compilation library location for package

### ISSUE THREAD

**Issue by ndeen86** [dotnet/core-setup#3397]
I have created some of the business layer, which is created in Core 1.1 .
Now I installed Core 2.0.2 SDK
Steps to reproduce:
1. Create dotnet new mvc
2. Referenced the Businesslayer dll which built on Core 1.1
3. Invoke the business layer from my new Core 2.0.2 mvc controller.
When I Debug, It returns the result as expected from business layer. But when I ran the application with "dotnet run", then it says the above error.

I am expecting it should render default view

I am Using Visual studio code for my development

https://github.com/dotnet/core-setup/issues/2981 It says, in 2.0.2 the issue got fixed., But I have 2.0.2 and issue still exists.

Below is my issue:

> System.InvalidOperationException: Cannot find compilation library location for package 'DataAccess'
>    at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
>    at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
>    at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.<>c.<GetReferencePaths>b__8_0(CompilationLibrary library)

**Comment by Petermarcu** [comment]
When they said 2.0.2, they meant the 2.0.2 runtime that didn't end up shipping. I believe it skipped to 2.0.3 and will ship soon. 

If you want to pick up the servicing dev build to try it you can add this myget feed: https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

And reference this package in your project. Note the version is 2.0.3-servicing-25831-01

https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.Extensions.DependencyModel/2.0.3-servicing-25831-01

**Comment by Petermarcu** [comment]
I'm going to close this now after getting a thumbs up on the last response. Let us know if the official release that will come out soon doesn't have what you need.
