### ISSUE TITLE
Debian Failed to initialize CoreCLR, HRESULT: 0x80131500

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#3399]
_From @Frank591 on November 9, 2017 12:5_

##  Actual behavior
publish on Windows machine: **dotnet publish --runtime debian.8-x64 --configuration Release**

Starting on debian 9 machine:
**dotnet my.dll** 
failed with error **Failed to initialize CoreCLR, HRESULT: 0x80131500**
##  Expected behavior
dotnet apps should work on debian 9.  

Are there some fixes or workarounds for this problem?

## Environment data
developer@debian:~/monitoring_deploy$ dotnet --info

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**deploy$ sudo strace -o logfile dotnet my.dll output:**
[logfile.txt](https://github.com/dotnet/cli/files/1457508/logfile.txt)

_Copied from original issue: dotnet/cli#7989_

**Comment by livarcocc** [comment]
I don't think you can publish to debian.8 and run it on debian.9. I think in this case you might have more success publishing to linux-x64, our generic linux version.

In any case, I am moving this bug over to core-setup

**Comment by Petermarcu** [comment]
Two questions.

1. What is the location of the files you are copying over to the Debian 9 machine? Was it from under the debian.8-x64 publish folder or somewhere else?
2. Can you try publishing for `linux-x64` and copying the assets from the linux-x64 publish folder?

**Comment by Frank591** [comment]
1. project folder\bin\Release\netcoreapp1.1\debian.8-x64
2. I tried to publish for linux-x64
`dotnet publish --runtime linux-x64 --configuration Release`
and got error 

> A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/developer/monitoring_deploy/'.
when tried to start dotnet on Debian.

**Comment by Petermarcu** [comment]
That looks like you are using .NET Core 1.1. .NET Core 1.1 didn't support Debian9. 

When you run that command, it should put things in a folder like this:

\bin\Release\netcoreapp2.0\linux-x86\publish\

You also have to copy binaries from a "publish" folder. Can you confirm you are doing that?

**Comment by Frank591** [comment]
`You also have to copy binaries from a "publish" folder. Can you confirm you are doing that?`
Sorry, yes i copied files from publish folder. And my project has target framework=netcoreapp1.1. 
If i will switch target framework to .NET Core 2.0 should it fix problem? And one more question: what runtime i should use for publish app to Debian 9? 
PS Sorry for my bad English

**Comment by Petermarcu** [comment]
You need `netcoreapp2.0` in your project instead of `netcoreapp1.1` and you need to publish with this command. 

`dotnet publish -r linux-x64 --configuration Release`

**Comment by Frank591** [comment]
I switched to netcoreapp2.0 and used command 
`dotnet publish -r linux-x64 --configuration Release`
Now i have error 
`A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/developer/monitoring_deploy/'.
`

**Comment by Frank591** [comment]
When i changed 
`<TargetFramework>netcoreapp1.1</TargetFramework>` to
`<TargetFramework>netcoreapp2.0</TargetFramework>` 
 i forgot to change 
`<RuntimeFrameworkVersion>1.1.2.</RuntimeFrameworkVersion>` to 
`<RuntimeFrameworkVersion>2.0.0</RuntimeFrameworkVersion>`  .
When i fixed that app started. My problem solved. Thanks for help!

**Comment by Petermarcu** [comment]
You should be able to just delete `<RuntimeFrameworkVersion>2.0.0</RuntimeFrameworkVersion>`. Its inferred and is only need if you want to mismatch for some reason.

I'll close this issue now. Glad you are up and running!
