### ISSUE TITLE
libhostfxr.dylib could not be found

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#3400]
@Marksion08 commented on [Thu Nov 09 2017](https://github.com/dotnet/core/issues/1072)

# libhostfxr.dylib could not be found

$ hello> dotnet new
## _A fatal error occurred, the required library libhostfxr.dylib could not be found at /usr/local/bin/_

# Info
So happy to heart that .netcore support macOS sierra, but while I have tried that's still a big disappointment!

---

@Petermarcu commented on [Thu Nov 09 2017](https://github.com/dotnet/core/issues/1072#issuecomment-343219799)

Can you describe how you installed .NET Core?

**Comment by Marksion08** [comment]
# More Installation details:
Follow as Official site: [macOS install guide](https://docs.microsoft.com/zh-cn/dotnet/core/macos-prerequisites)

Step1:
----------------
````
brew update
brew install openssl
mkdir -p /usr/local/lib
ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/

brew link --force openssl

````
Step2:
-------------------
[Download .NET Core 2.x](https://www.microsoft.com/net/download/core) and Setup.

Step3:
-----------------

`````
$ mkdir hello
$ cd hello
$ dotnet new
 A fatal error occurred, the required library libhostfxr.dylib could not be found at /usr/local/bin/

````

**Comment by Marksion08** [comment]
hi Peter,

I have updated it, pls refer to https://github.com/dotnet/core-setup/issues/3400, thank you!

__

Regards,
Marksion

At 2017-11-10 01:13:21, "Peter Marcu" <notifications@github.com> wrote:


@Marksion08 commented on Thu Nov 09 2017

libhostfxr.dylib could not be found

$ hello> dotnet new

A fatal error occurred, the required library libhostfxr.dylib could not be found at /usr/local/bin/
Info

So happy to heart that .netcore support macOS sierra, but while I have tried that's still a big disappointment!

@Petermarcu commented on Thu Nov 09 2017

Can you describe how you installed .NET Core?

**Comment by Petermarcu** [comment]
@steveharter any ideas?

**Comment by steveharter** [comment]
Some troubleshooting recommendations:
**1)** Verify the dotnet executable location - type `which dotnet`.

For you it appears that it is going to be `/usr/local/bin/`. However the default install location (and on my mac) is `/usr/local/share/dotnet/`

Do you happen to have an old install at `/usr/local/bin/` that is in the path? Normally `/usr/local/bin` is going to be in the path before `/usr/local/share/dotnet` (verify via `echo $PATH`)

**2)** Fom the dotnet executable location there should be a subfolder called `host/fxr/2.0.0` with the libhostfxr.dylib file

**3)** Try setting `export COREHOST_TRACE=1` and then run `dotnet new` again to get any further diagnostics

**Comment by Marksion08** [comment]
@steveharter 
Thank you very much your advises!

It seems to be the Permission problem at last after tried many times, it showed "Permission Denied".
But *** it worked fine once time *** if  export the `/usr/local/share/dotnet` to `$path` and `ln -s source` correctly, close it and try again all was gone, `which dotnet` was none too.

Summary up, not permission enough to execute the application, although tried update right as 'sudo chown -R user_xxx /usr/local/share/dotnet' or 'sudo chmod -R 7xx /usr/local/bin/dotnet'.

Regards & Thanks!
MKH

**Comment by Petermarcu** [comment]
Great! I'll go ahead and close this issue now.
