### ISSUE TITLE
Executing portable mode while missing appname.runtimeconfig.json fails (is it a bug or documentation misunderstanding?)

### ISSUE THREAD

**Issue by izaruba** [dotnet/core-setup#3407]
## Steps to reproduce
Referring [Runtime Configuration Files documentation](https://github.com/dotnet/cli/blob/master/Documentation/specs/runtime-configuration-file.md)

> MyApp.runtimeconfig.json - An optional configuration file containing runtime configuration settings.

> The .runtimeconfig.json file is completely optional

the following actions should not end up with an error.

`> dotnet new console -n MyApp`
`> cd MyApp`
`> dotnet publish`
`> cd bin\Debug\netcoreapp2.0\publish`
`> del MyApp.runtimeconfig.json`
`> dotnet MyApp.dll`
`A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\MyApp\bin\Debug\netcoreapp2.0\publish\'.`

## Expected  behavior
Apparently, the latest framework version (or the one supposed to be the default version) is selected and hostpolicy.dll is resolved.

## Actual behavior
As [this code](https://github.com/dotnet/core-setup/blob/master/src/corehost/cli/runtime_config.cpp#L117) states, non-existing file is not an error. However, a return at this point keeps [m_portable](https://github.com/dotnet/core-setup/blob/master/src/corehost/cli/runtime_config.cpp#L17) initialized with a default value `false`.
Then, it looks like the execution proceeds as if it was a standalone app - [fx_muxer.cpp:442](https://github.com/dotnet/core-setup/blob/master/src/corehost/cli/fxr/fx_muxer.cpp#L442), considering `hostpolicy.dll` is in the same directory as `app_candidate`, which in turns comes to this output (if we enable tracing)
`The expected hostpolicy directory is [C:\MyApp\bin\Debug\netcoreapp2.0\publish\]`
`The hostpolicy.dll was not found in [C:\MyApp\bin\Debug\netcoreapp2.0\publish\]`
`A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\MyApp\bin\Debug\netcoreapp2.0\publish\'.`
## Environment data
`dotnet --version`
2.0.2

**Comment by Petermarcu** [comment]
@steveharter

**Comment by steveharter** [comment]
The doc was recently updated:
>MyApp.runtimeconfig.json - An optional configuration file containing runtime configuration settings. This file is required for portable applications, but not for self-contained apps.

Also in the master branch (2.1), there is now an additional error message (https://github.com/dotnet/core-setup/issues/3193) shown when attempting to run as a portable app and the runtimeconfig is missing, or is missing the framework information.

Your analysis is correct - the lack of a runtimeconfig file will treat the app as standalone, which will then cause an error if hostpolicy.dll is not in the same directory as app_candidate (the app dll).

Is the presence of the runtimeconfig an issue in some way for you, other than doc and code comment inconsistencies?

>>Expected behavior
Apparently, the latest framework version (or the one supposed to be the default version) is selected and hostpolicy.dll is resolved.

There is no "default" framework and selecting the latest framework version is not the current policy. For compat, we always want to run on the same framework the app originally targeted, unless there is a higher version by patch version only (which is the third segment in a version number) in which case we will "roll-forward" to that patch version. So for this policy to work, we at least need a "base" version of the framework name and framework version the app originally targeted. There are knobs to roll-forward on non-patch versions when the original framework is not available, but currently those are off by default.

**Comment by izaruba** [comment]
@steveharter Thanks for breaking it down. Everything is reasonable.
