### ISSUE TITLE
.NET Core SDK 2.0.3 has hard-coded version string in bundle UI

### ISSUE THREAD

**Issue by barnson** [dotnet/core-setup#3427]
## Steps to reproduce

* Install dotnet-sdk-2.0.3-win-x64.exe, downloaded from https://www.microsoft.com/net/download/windows.

## Expected  behavior

The `Success` page tells me I installed version 2.0.3.

## Actual behavior

![image](https://user-images.githubusercontent.com/916265/32928786-c04e0ae8-cb21-11e7-9f4e-1093c96eed3a.png)

The loc string `FirstTimeWelcomeMessage` used on the `Success` page in the bundle has hard-coded `2.0.0` strings.

## Environment data

n/a

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8042](https://github.com/dotnet/cli/issues/8042) via [**ZenHub**](https://www.zenhub.com/)
