### ISSUE TITLE
Publishing step in official build need to be refactored

### ISSUE THREAD

**Issue by weshaggard** [dotnet/core-setup#3428]
As part of our orchestrated build work I created a publish-type.proj that forks the publishing into two pieces, see https://github.com/dotnet/core-setup/pull/3404. We need to finishing refactoring all the publish steps to be configurable and not duplicated into multiple publish workflows.

**Comment by weshaggard** [comment]
individual legs seem to still publish to myget directly see https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1173516. Looks like https://github.com/dotnet/core-setup/blob/fa0062baae260c1591a7d71c45f7c241634b8bec/publish/publish.proj#L282.

**Comment by weshaggard** [comment]
After some discussion with others we have decided to remove the deb publish steps so we should do that as part of the publish clean-up in this issue.

**Comment by weshaggard** [comment]
As part of separating the steps we should consider doing the symbol publishing in a parallel definition to try and reduce the time we index.

**Comment by mikem8361** [comment]
@weshaggard, can I go ahead and commit this PR as is? Or should I turn off the pdb conversion?

**Comment by weshaggard** [comment]
>@weshaggard, can I go ahead and commit this PR as is? Or should I turn off the pdb conversion?

Move forward and commit your PR turning on the pdb conversion.

**Comment by weshaggard** [comment]
bumping to post 2.0

**Comment by weshaggard** [comment]
As part of this we also need to ensure that we are using a build id specific storage account for gathering the assets. Right now if we do a stable build it ends up overwriting older builds. cc @mmitche

**Comment by dagood** [comment]
Closing, this has changed a lot (for the better) since the last activity, especially with the migration to Arcade.
