### ISSUE TITLE
Couldn't build from sources on windows

### ISSUE THREAD

**Issue by mfilippov** [dotnet/core-setup#3429]
Couldn't build from sources on windows:
## Steps to reproduce
Clone project into disk D:\ root and run build.cmd
## Expected  behaviour
Project built

## Actual behaviour
D:\core-setup>build.cmd
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.4.4
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
Installing dotnet cli...
Restoring BuildTools version 2.0.0-prerelease-02215-01...
Initializing BuildTools...
Done initializing tools.
Running: D:\core-setup\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false /p:OSGroup=Windows_NT /p:TargetArchitecture=x64  /flp:v=normal  build.proj
MSBUILD : error MSB1009: Project file does not exist.
Switch: build.proj
Command execution failed with exit code 1.

## Environment data
Visual Studio 15.4.4
Windows 10

**Comment by danmosemsft** [comment]
This works for me on a clean clone to c:\git\core-setup, so I wonder if d: is the issue. Could something be changing the drive to c:? Perhaps if you "set _echo=1" and try again you may get a clue.

**Comment by weshaggard** [comment]
I've seem some similar issues in other repos. I susect this is because https://github.com/dotnet/core-setup/blob/master/run.cmd#L17 is changing the directory. We likely need some changes similar to https://github.com/dotnet/corefx/pull/18700

**Comment by mfilippov** [comment]
@danmosemsft 
```
D:\Work\core-setup>set _echo=1

D:\Work\core-setup>build.cmd
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.4.4
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

C:\Users\mikha\source>setlocal

C:\Users\mikha\source>set INIT_TOOLS_LOG=D:\Work\core-setup\init-tools.log

C:\Users\mikha\source>if [] == [] set PACKAGES_DIR=D:\Work\core-setup\packages\

C:\Users\mikha\source>if [] == [] set TOOLRUNTIME_DIR=D:\Work\core-setup\Tools

C:\Users\mikha\source>set DOTNET_PATH=D:\Work\core-setup\Tools\dotnetcli\

C:\Users\mikha\source>if [] == [] set DOTNET_CMD=D:\Work\core-setup\Tools\dotnetcli\dotnet.exe

C:\Users\mikha\source>if [] == [] set BUILDTOOLS_SOURCE=https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json

C:\Users\mikha\source>set /P BUILDTOOLS_VERSION= 0<"D:\Work\core-setup\BuildToolsVersion.txt"

C:\Users\mikha\source>set BUILD_TOOLS_PATH=D:\Work\core-setup\packages\Microsoft.DotNet.BuildTools\2.1.0-prerelease-02220-02\lib\

C:\Users\mikha\source>set INIT_TOOLS_RESTORE_PROJECT=D:\Work\core-setup\init-tools.msbuild

C:\Users\mikha\source>set BUILD_TOOLS_SEMAPHORE=D:\Work\core-setup\Tools\2.1.0-prerelease-02220-02\init-tools.completed

C:\Users\mikha\source>if [] == [force] (
if exist "D:\Work\core-setup\Tools" rmdir /S /Q "D:\Work\core-setup\Tools"
 if exist "D:\Work\core-setup\packages\Microsoft.DotNet.BuildTools" rmdir /S /Q "D:\Work\core-setup\packages\Microsoft.DotNet.BuildTools"
)

C:\Users\mikha\source>if exist "D:\Work\core-setup\Tools\2.1.0-prerelease-02220-02\init-tools.completed" (
echo Tools are already initialized.
 goto :EOF
)
Tools are already initialized.
Running: D:\Work\core-setup\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false /p:OSGroup=Windows_NT /p:TargetArchitecture=x64  /flp:v=normal  build.proj
MSBUILD : error MSB1009: Project file does not exist.
Switch: build.proj
Command execution failed with exit code 1.
```

**Comment by 4creators** [comment]
```
D:\Work\core-setup>build.cmd
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.4.4
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

C:\Users\mikha\source>setlocal
```
Build starts in `D:\Work\core-setup` and after executing VsDevCmd.bat switches to `C:\Users\mikha\source>` what causes the error. Similar to other repos` problems with VsDevCmd.bat call.

**Comment by 4creators** [comment]
@weshaggard @danmosemsft 
Seems to be general error prone pattern in scripts - I could screen it in repos and fix if necessary - anyway I need it for myself to get it fixed.

**Comment by 4creators** [comment]
@mfilippov 
I managed to repro your problem while building from windows command line. Temporary workaround until the problem is fixed is to use Visual Studio 2017 developer command prompt to build repo.
```
e:\src\ms\dotnet\core-setup>build
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.4.4
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
Installing dotnet cli...
Restoring BuildTools version 2.1.0-prerelease-02220-02...
Initializing BuildTools...
Done initializing tools.
Running: E:\src\ms\dotnet\core-setup\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false /p:OSGroup=Windows_NT /p:TargetArchitecture=x64  /flp:v=normal  build.proj
MSBUILD : error MSB1009: Project file does not exist.
Switch: build.proj
Command execution failed with exit code 1.
```

**Comment by mfilippov** [comment]
@4creators Ok, thanks for the workaround, it worked.

**Comment by weshaggard** [comment]
>Seems to be general error prone pattern in scripts - I could screen it in repos and fix if necessary - anyway I need it for myself to get it fixed.

That would be awesome @4creators if you wanted to tackle that problem.

**Comment by steveharter** [comment]
VS 2017 and 2015 are now supported
