### ISSUE TITLE
Cannot download runtime from 'Release/1.1.X' channel using dotnet-install.ps1

### ISSUE THREAD

**Issue by johnbeisner** [dotnet/core-setup#3430]
_From @hubuk on November 17, 2017 7:14_

## Steps to reproduce
1. Download `dotnet-install.ps1` from https://dot.net/v1/dotnet-install.ps1
2. Run command: `./dotnet-install.ps1 -sharedRuntime -version 1.1.5-servicing-001649-00`

## Expected  behavior
After checking:
Downloading link: `https://dotnetcli.azureedge.net/dotnet/Runtime/1.1.5-servicing-001649-00/dotnet-runtime-1.1.5-servicing-001649-00-win-x64.zip`
Downloading legacy link: `https://dotnetcli.azureedge.net/dotnet/Runtime/1.1.5-servicing-001649-00/dotnet-win-x64.1.1.5-servicing-001649-00.zip`
script should also check location:
`https://dotnetcli.azureedge.net/dotnet/release/1.1.0/Binaries/1.1.5-servicing-001649-00/dotnet-win-x64.1.1.5-servicing-001649-00.zip`

## Actual behavior
`release/1.1.0/Binaries` location is not being considered by the script.

## Environment data
```ps1
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.19
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.19
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

_Copied from original issue: dotnet/cli#8043_

**Comment by johnbeisner** [comment]
@hubuk 
'release/1.1.0/Binaries' is not a supported path
Please use the parameters:
"-sharedRuntime -channel 1.1" or "-sharedRuntime -version 1.1.5"

This will install the latest 1.1 release of the runtime.

**Comment by johnbeisner** [comment]
_From @hubuk on November 17, 2017 19:17_

@johnbeisner: Maybe this is not a most common use case but I just realized that there are some builds not available to download via dotnet-install scripts. One of them is the latest daily build listed on https://github.com/dotnet/core-setup#daily-builds page for Release/1.1.X which is `1.1.5-servicing-001649-00`. There are more. Probably all 1.1.X servicing builds which versions are listed on this [myget](https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.App/1.1.5-servicing-001649-00) page.
Is there any reason why these builds are not available on 'dotnet/Runtime' path?

**Comment by johnbeisner** [comment]
@hubuk 
You are correct in the observation that not all the Runtimes are available to install via the dotnet-install scripts. I think this would be a question for the Runtime folks. I will move the issue to the proper place.

**Comment by johnbeisner** [comment]
Why are some of the Runtimes not available at the standardized install location: https://dotnetcli.blob.core.windows.net/dotnet/Runtime/

**Comment by Petermarcu** [comment]
@weshaggard can you look into why we're not putting runtimes in a place where the install scripts can find them? Ideally all the builds we produce can be consumed via the script.

**Comment by weshaggard** [comment]
Our 1.0.x and 1.1.x daily builds don't publish to the dotnet/Runtime folder and never have as best I can tell. I think we do publish the final stable builds to dotnet/Runtime folder as part of the release process but not every daily build. Unless there is a good reason I would like to avoid making this change in our servicing branches and keep the current approach.

**Comment by Petermarcu** [comment]
Alternatively, should the scripts be updated to point to the blob locations where we do push them?

**Comment by weshaggard** [comment]
@eerhardt do you have any history here? Did the install scripts ever support daily builds from the 1.x releases?

**Comment by eerhardt** [comment]
You need to set the `-Channel` parameter in order to use the `-SharedRuntime` for versions `1.0` and `1.1`.

```
dotnet-install.[sh/ps1] -channel release/1.1.0 -sharedRuntime -version 1.1.5-servicing-001649-00
```

This was a limitation of the publish structure in `1.0` and `1.1` of the shared runtime.  We've fixed this limitation in `2.0` and beyond by moving to the same publish structure as the SDK has been using.

However, for `1.0` and `1.1`, we require the extra `-channel` parameter.

**Comment by hubuk** [comment]
@eerhardt 
Why close? This is not working.
-channel and -version parameters for dotnet-install.ps1 script are almost mutually exclusive and are used in one function only:
```PS
function Get-Specific-Version-From-Version([string]$AzureFeed, [string]$Channel, [string]$Version) {
    Say-Invocation $MyInvocation

    switch ($Version.ToLower()) {
        { $_ -eq "latest" } {
            $LatestVersionInfo = Get-Latest-Version-Info -AzureFeed $AzureFeed -Channel $Channel -Coherent $False
            return $LatestVersionInfo.Version
        }
        { $_ -eq "coherent" } {
            $LatestVersionInfo = Get-Latest-Version-Info -AzureFeed $AzureFeed -Channel $Channel -Coherent $True
            return $LatestVersionInfo.Version
        }
        default { return $Version }
    }
}
```
`Channel` is being considered only when version is set to `latest` or `coherent`. This is the result of the command you provided:
```PS
.\dotnet-install.ps1 -channel release/1.1.0 -sharedRuntime -version 1.1.5-servicing-001649-00
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Runtime/1.1.5-servicing-001649-00/dotnet-runtime-1.1.5-servicing-001649-00-win-x64.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Runtime/1.1.5-servicing-001649-00/dotnet-runtime-1.1.5-servicing-001649-00-win-x64.zip
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Runtime/1.1.5-servicing-001649-00/dotnet-win-x64.1.1.5-servicing-001649-00.zip
Exception calling "Invoke" with "0" argument(s): "Failed to download https://dotnetcli.azureedge.net/dotnet/Runtime/1.1
.5-servicing-001649-00/dotnet-win-x64.1.1.5-servicing-001649-00.zip.  StatusCode: 404, ReasonPhrase: 'Not Found', Versi
on: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  x-ms-request-id: 83fded6f-001e-0062-7f09-68ef13000000
  x-ms-version: 2009-09-19
  Date: Tue, 28 Nov 2017 05:25:55 GMT
  Server: Windows-Azure-Blob/1.0
  Server: Microsoft-HTTPAPI/2.0
  Content-Length: 215
  Content-Type: application/xml
}"
At D:\Downloads\dotnet-install.ps1:110 char:20
+             return $ScriptBlock.Invoke()
+                    ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RuntimeException
```

**Comment by eerhardt** [comment]
Sorry - I missed the part about using `https://dot.net/v1/dotnet-install.ps1`.

In order to work with the daily builds of `1.0` and `1.1` of the `-SharedRuntime`, you are going to need an older version of the script.  You can use `https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/dotnet-install.ps1`.

@johnbeisner - I can't remember, was this a conscious decision of the `dotnet-install` scripts to not support the old `-SharedRuntime` layout?  I know we consciously decided that we weren't going to update `1.0` and `1.1` branches to publish in the new layout.  But I can't remember if we said that the scripts should support it or not.

**Comment by johnbeisner** [comment]
@eerhardt 
The install scripts were to support a standardized location for both SDK and runtime installations. The follow-up actions were to: 1) move or copy all the versions in a non-standard location to the standard location 2) SDK and runtime were to publish to the standard location

**Comment by hubuk** [comment]
@eerhardt @johnbeisner 
Thanks for clarification. Dedicated dotnet-install scripts for 1.x line of dotnet are sufficient for my usecase.
