### ISSUE TITLE
Can't install .Net Core 2.0.2 in Ubuntu 17.10

### ISSUE THREAD

**Issue by MaximoTrinidad** [dotnet/core-setup#3435]
Using the .NET Core installation instructions: https://www.microsoft.com/net/learn/get-started/linuxubuntu 

## Steps to reproduce
```
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg

sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-artful-prod artful main" > /etc/apt/sources.list.d/dotnetdev.list'

sudo apt-get update
sudo apt-get install dotnet-sdk-2.0.2
```
## Expected  behavior
To complete successfully.

## Actual behavior
```
maxt@mars:~$ sudo apt-get install dotnet-sdk-2.0.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.0.2 : Depends: dotnet-runtime-2.0.0 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
maxt@mars:~$ 
```
## Environment data
This is clean installation with no prior .NET Core files.
```
maxt@mars:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"
maxt@mars:~$ 
```

**Comment by danmosemsft** [comment]
@steveharter will have to help with this, but meanwhile does 2.0.3 help? It was released: https://blogs.msdn.microsoft.com/dotnet/2017/11/14/net-core-november-2017-update/

**Comment by Petermarcu** [comment]
@rakeshsinghranchi

**Comment by Petermarcu** [comment]
@wli3

**Comment by steveharter** [comment]
Can you try installing the runtime directly instead of the SDK? You may get a better error message about which components are missing (such as libicu; see https://github.com/dotnet/cli/issues/7640)

**Comment by rakeshsinghranchi** [comment]
Also, this could be a case of 'partial-upgrade'. Please run "sudo apt-get clean && sudo apt-get update" before installing the runtime package.

**Comment by MaximoTrinidad** [comment]
HI All!  Either way, everything I've tried keeps telling the same message: "_**..Depends: dotnet-runtime-2.0.0 but it is not going to be installed**_".

I tried the "sudo apt install -f" but didn't work.

I will try running the clean and update again. 

:)

**Comment by MaximoTrinidad** [comment]
@rakeshsinghranchi 

No luck!  Did the "sudo apt clear" and "sudo apt update", then reran the whole the steps to install .NET Core 2.0: https://www.microsoft.com/net/learn/get-started/linuxubuntu 

I got the same error:
```
maxt@mars:~$ sudo apt-get install dotnet-sdk-2.0.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.0.2 : Depends: dotnet-runtime-2.0.0 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
maxt@mars:~$ 
```

**Comment by MaximoTrinidad** [comment]
@danmosemsft 

I even try with .NET Core 2.0.3.  I got a similar error message:
```
maxt@mars:~$ sudo apt-get install dotnet-sdk-2.0.3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.0.3 : Depends: dotnet-runtime-2.0.3 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
maxt@mars:~$ 
```

**Comment by steveharter** [comment]
@DanielRosenwasser have you tried to install just the runtime (the SDK installs both the SDK + runtime):
`sudo apt-get install dotnet-runtime-2.0.3`

**Comment by MaximoTrinidad** [comment]
Hi @steveharter,

Yes! I have trying as, in a way, is what the message is suggesting to do.  But, here's the other message is popping out:
```
maxt@mars:~$ sudo apt-get install dotnet-runtime-2.0.3
[sudo] password for maxt: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-2.0.3 : Depends: libicu55 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by steveharter** [comment]
It looks like you have the missing libicu as mentioned in dotnet/cli#7640

On my installation I have libicu57 installed; you can give this a try:
` sudo apt-get install libicu57`

**Comment by MaximoTrinidad** [comment]
@steveharter ,

I tried that also! Here's the message:
```
maxt@mars:~$ sudo apt-get install libicu57
[sudo] password for maxt: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libicu57 is already the newest version (57.1-6ubuntu0.2).
libicu57 set to manually installed.
The following packages were automatically installed and are no longer required:
  libnih-dbus1 linux-image-4.10.0-19-generic linux-image-extra-4.10.0-19-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```
This is on Ubuntu 17.10 which is a different animal than 16.04.  In 16.40 it loads without any issues.

Thanks for helping me... Greatly Appreciated!

:)

**Comment by rakeshsinghranchi** [comment]
@MaximoTrinidad  ,  did you try on a clean machine ? I am unable to repro the issue on ubuntu:17.10 docker image.
can you please try _apt-get upgrade_  and then follow the steps.

**Comment by MaximoTrinidad** [comment]
Hi @rakeshsinghranchi,

This is fresh clean installation on a wmware VM (not on a container). I build it from scratch. And, I have tried multiple times following the steps.

I will build download another Ubuntu 17.10 ISO (just in case) and build another VM.  Let see if it was something with the Ubuntu Distro.  

:)

**Comment by nihanth007** [comment]
same issue for me.
on vmware for a fresh install of ubuntu 17.10

```
sudo apt-get install dotnet-sdk-2.0.3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.0.3 : Depends: dotnet-runtime-2.0.3 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

And when i try to install dotnet runtime

```
user@coumpter:~$ sudo apt-get install dotnet-runtime-2.0.3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-2.0.3 : Depends: libicu55 but it is not installable
E: Unable to correct problems, you have held broken packages.

```

but libicu57 is already installed

**Comment by MaximoTrinidad** [comment]
Thanks @nihanth007 for confirming that is happening!
:)

**Comment by SirMossi** [comment]
same problem here with an kde neon distribution
DISTRIB_ID=neon
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="KDE neon User Edition 5.11"

libicu55 is installed, but dotnet needs libicu57, which is not available for this distribution. In this case it could depend on the special distribution, but perhaps it's possible to not use a fixed version dependency.

**Comment by MaximoTrinidad** [comment]
OK!!  So, installation instructions seems change, proceeded to install **.NET Core 2.0.3**. 

Everything works as expected:
1. Download link:
https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.0.3-linux-x64-binaries
```
mkdir -p $HOME/dotnet

cd Downloads

tar zxf dotnet-sdk-2.0.3-linux-x64.tar.gz -C $HOME/dotnet

export PATH=$PATH:$HOME/dotnet
```
 2. Verify installation:
```
maxt@mars:~$ dotnet --version
2.0.3
```
I'm closing this issue.

**Comment by CumpsD** [comment]
Just got this error to while following the installation documentation at https://www.microsoft.com/net/learn/get-started/linuxubuntu

Maybe you guys need to update that documentation page when closing this issue?

**Comment by CumpsD** [comment]
Also, the above still needs this on Ubuntu:

`apt-get install libunwind8`

**Comment by clperez** [comment]
In my case, I installed libicu52 downloading it from 

http://security.ubuntu.com/ubuntu/pool/main/i/icu/

Then i was able to install everything without any issue.

**Comment by cpmcgrath** [comment]
Hi,
The instructions above worked for me, but I don't know why this issue has been closed. 
There are instructions on https://www.microsoft.com/net/learn/get-started/linuxubuntu and the instructions do not work. Until, the instructions have been updated, this issue should remain open.

**Comment by danmosemsft** [comment]
@Petermarcu does it surprise you that folks above needed to install libunwind8 and libicu52 on Ubuntu? 

Who owns the instructions on https://www.microsoft.com/net/learn/get-started/linuxubuntu is it @leecow ?

**Comment by Petermarcu** [comment]
Yes, when installing through a package manager, all the dependencies should be installed. Sounds like a bug.

**Comment by leecow** [comment]
Not sure how the dependency range would be handled in a single package since libicu updates are different package names rather than just a version bump. (eg libicu55 versus libicu57). @rakeshsinghranchi ?

`Depends: libc6 (>= 2.14), libcurl3 (>= 7.16.2), libgcc1 (>= 1:3.0), libgssapi-krb5-2 (>= 1.14+dfsg), liblttng-ust0 (>= 2.5.0), libstdc++6 (>= 4.8), libunwind8, libuuid1 (>= 2.16), zlib1g (>= 1:1.1.4), dotnet-hostfxr-2.0.3, libicu57, libssl1.0.0`

The situation is somewhat dealt with by the runtime-deps installers for 2.1 but those will also need to keep up. For example, there is a 17.10 installer which properly references libicu57 but this will fail on 18.04 which has libicu60 by default.

**Comment by MaximoTrinidad** [comment]
Updated with one correction
**Ubuntu 17.10**

Everything works:

1. Download link:
https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.4-linux-x64-binaries
```
mkdir -p $HOME/dotnet

~$ cd Downloads

~/Downloads$ tar zxf dotnet-sdk-2.1.4-linux-x64.tar.gz -C $HOME/dotnet
```
2. Open vim to add the following line into ~/.bashrc: (correction)
```
~$ sudo vim ~/.bashrc
i
export PATH=$PATH:$HOME/dotnet
:qw
~$
```
3. Verify installation:
```
~$ dotnet --version
2.1.4
```

Works for me on Ubuntu 17.10
:)

**Comment by danmosemsft** [comment]
@MaximoTrinidad the instructions say to do `export PATH=$PATH:$HOME/dotnet` .. didn't that work also?

**Comment by MaximoTrinidad** [comment]
Hi @danmosemsft,

I just had to get rid of (move to trash) my previous dotnet 2.0.3 and try the instructions on the page without any luck.

I just did the manual steps, it works for me.

Of course, I had to add the "export PATH=$PATH:$HOME/dotnet" at the end of my ~/.bashrc  to make it work.

Interesting enough, on my Ubuntu 16.04, I'm not using the export line. 
You got to love working with systems.

:)

**Comment by CoderJason123** [comment]
I also have this issue, on a brand new 16.04 ubuntu box.  i also can not install libicu52 by itself, or any previous runtime.

This is very discouraging.  I need to get this working today, can someone who has figured this out exactly please let me know?  Thank you.

**Comment by Petermarcu** [comment]
Did you try through the package manager?

`sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list'`
`sudo apt-get install apt-transport-https`
`sudo apt-get update`
`sudo apt-get install dotnet-sdk-2.1.4`

**Comment by CoderJason123** [comment]
Um, wow.  i'm wondering if i was unable to read.  the path i had copied down from the site was 
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main" > /etc/apt/sources.list.d/dotnetdev.list'

This seems like it will work.  Are these instructions lightly different than on the main web site, like a work around?  Thanks a million for your help.

**Comment by CoderJason123** [comment]
Man, twice in 1 week, a bonehead maneuver on my part.  I used the 14.04 package manager path....sorry about that.  Thanks a million, sorry for my stupidity :)

**Comment by danmosemsft** [comment]
@CoderJason123 that's totally fine, we're just glad you're trying out our platform.

**Comment by rakeshsinghranchi** [comment]
> Not sure how the dependency range would be handled in a single package since libicu updates are different package names rather than just a version bump. (eg libicu55 versus libicu57). @rakeshsinghranchi ?
 Depends: libc6 (>= 2.14), libcurl3 (>= 7.16.2), libgcc1 (>= 1:3.0), libgssapi-krb5-2 (>= 1.14+dfsg), liblttng-ust0 (>= 2.5.0), libstdc++6 (>= 4.8), libunwind8, libuuid1 (>= 2.16), zlib1g (>= 1:1.1.4), dotnet-hostfxr-2.0.3, libicu57, libssl1.0.0
The situation is somewhat dealt with by the runtime-deps installers for 2.1 but those will also need to keep up. For example, there is a 17.10 installer which properly references libicu57 but this will fail on 18.04 which has libicu60 by default.

@leecow , .NET 2.0.x ubuntu17.04 and Ubuntu 17.10 runtime deb package exhibits system dependencies on libicu57 . Ubuntu16.04 exhibits dependency on libicu55.   I tried to repro on Ubuntu 17.10.1 iso from https://www.ubuntu.com/download/desktop/contribute/?version=17.10.1&architecture=amd64 and couldn't repro the issue following the repro steps mentioned at the top of the issue.

Also, looking at the system package dependencies on Ubuntu 17.10 , dotnet-runtime-2.x packages exhibits dependency on libicu57 which is expected.

**apt-cache rdepends libicu57 | grep dotnet- && lsb_release -a**
  dotnet-runtime-2.0.5
  dotnet-runtime-2.0.4
  dotnet-runtime-2.0.3
  dotnet-runtime-2.0.0
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

cc @MaximoTrinidad @cpmcgrath .

**Comment by leecow** [comment]
Tested current instructions on https://www.microsoft.com/net/download/linux-package-manager/ubuntu17-10/sdk-current with a fresh 17.10 VM and things are working as expected. Closing this issue.

**Comment by Jofairden** [comment]
You can close this, but im still having this same issue on Debian 9 and dont know how to fix it

**Comment by natke** [comment]
I have the same issue with the instructions for Ubuntu 16.04: https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-current

Output
```
$ sudo apt-get install dotnet-sdk-2.0.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.0.0 : Depends: dotnet-runtime-2.0.0 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by Atastor** [comment]
Metoo on Debian-9 troubles, where dependencies are on libicu52 and libssl1.0.0 (the latter one being a bigger issue in my view, cause it might prevent necessary security updates).

**Comment by danmosemsft** [comment]
What is the output when you try to install the dependencies?

**Comment by Atastor** [comment]
Sometimes the act of complaining itself aparently opens up completely new brain areas ... *FACEPALM* ... 
```
> cat /etc/apt/sources.list.d/dotnetdev.list
deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-jessie-prod jessie main
```
I fixed it and afterwards it installed without a hitch.

Jofairden may have completely different problems, but I am slightly embarassed but content problemwise.

**Comment by danmosemsft** [comment]
Awesome. Let's take each of you in turn and get you sorted out.

**Comment by danmosemsft** [comment]
@Jofairden can you share more details?

@eerhardt can you help troubleshoot @natke?

**Comment by eerhardt** [comment]
I think it would help to open separate issues for different OSs.  It is confusing trying to follow multiple issues on one page.

**Comment by eerhardt** [comment]
@natke - the `2.0.0` SDK is out of date.  We've had security patches to these binaries. You should be installing

`sudo apt-get install dotnet-sdk-2.1.4`

Which comes with the latest security patched runtime.

**Comment by danmosemsft** [comment]
I agree. Let's freeze this issue -- folks please do open new separate issues, we will make every effort to get you unblocked.
