### ISSUE TITLE
Core-Setup: Missing publish output from all legs of the build

### ISSUE THREAD

**Issue by jcagme** [dotnet/core-setup#3446]
@dotnet-mc-bot commented on [Tue Nov 21 2017](https://github.com/dotnet/core-eng/issues/2150)

Opened on behalf of @jcagme

Warnings: 0
Status Message: failed

Build : Master - 20171120.06 (Product Build)
Failing configurations:
- Windows
  - Publish-x64
[Mission Control Build Info](https://mc.dot.net/#/product/netcore/master/source/official~2Fcore-setup~2Fmaster~2F/type/build~2Fproduct~2F/build/20171120.06/workItem/Orchestration/analysis/external/Visual%20Studio%20Build%20Information)

**Comment by jcagme** [comment]
Several builds have failed with:

2017-11-21T00:25:27.8479397Z ##[error]core-setup\publish\dir.targets(114,5): Error : Missing publish output from all legs of the build. Missing blobs are 'sharedfx_ubuntu.17.10-x64_Release_version_badge.svg'

https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1160377

**Comment by weshaggard** [comment]
This is transient generally one one of the legs of the official build fails.
