### ISSUE TITLE
Dotnet-Host RPM package upgrade removes symbolic link

### ISSUE THREAD

**Issue by rakeshsinghranchi** [dotnet/core-setup#3455]
## Steps to reproduce
Install dotnet-host-2.0.0 rpm package
Install dotnet-host-2.0.x rpm package

## Expected  behavior
dotnet-host payload should be upgraded
dotnet-host symbolic link should be preserved

## Actual behavior
dotnet-host symbolic link is removed as part of dotnet-host-2.0.0 uninstall step.

## Environment data

**Comment by CRCinAU** [comment]
Duplicating my comment from the referenced issue for how we handle this issue when using a .spec file to build the RPM:

Hrrrm - in the .spec world, you'd do something like this:
```
%preun
if [ $1 = 0 ]; then
   unlink /usr/bin/dotnet
fi
```
This roughly translates to: If we're uninstalling (hence %preun), and we don't have any newer version installed, run the script.

Running a complete script file in what I assume is the %post or %preun sections of the RPM installation - I'm not sure there is an easy way to achieve the same - unless you can pass the same $1 to the script and evaluate it in said script...
