### ISSUE TITLE
Add support for multiple frameworks \ platforms

### ISSUE THREAD

**Issue by steveharter** [dotnet/core-setup#3457]
This is the main feature issue to support layered frameworks in core-setup which affects hostfxr.dll, hostpolicy.dll and apphost.exe.

Currently a single framework is supported, identified by name and base version in the runtimeconfig.json section:
```
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.1.0"
    }
```

In order for ASP.NET (and others tbd) to obtain the same benefit of roll-forward semantics and a self-contained directory structure, the following design has been prototyped and approved:

1) Multiple framework through "layering" (a single inheritance hierarchy)
2) The existing runtimeconfig.json and deps.json schema remains
2a) Each new framework has its own runtimeconfig.json which will reference the next (lower-level) framework. E.g. ASP.NET's runtimeconfig.json will reference Microsoft.NETCore.App
2b) Settings in the runtimeconfig.json will carry forward to the next lower level, although the exact semantics differ depending on the setting - some override, while others are additive

Additional design information is located at https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/multilevel-sharedfx-lookup.md, and additional information regarding runtimeconfig.json settings will be added soon.

Known constraints:
A) `--fx-framework <version>` only applies to the first framework
B) The RID graph must be located in the lowest level framework's deps.json (Microsoft.NETCore.App)
C) hostpolicy.dll must be located in the lowest level framework's directory (Microsoft.NETCore.App)
D) The store functionality remains as-is for now
E) The FX_DEPS_FILE property variable passed to the CLR only refers to the root (last) framework's deps file
F) The tfm is defined by the apps' runtimeconfig.json (it can't be changed in fx runtimeconfig.json)

**Comment by jkotalik** [comment]
cc/ @JunTaoLuo

**Comment by muratg** [comment]
Thanks @steveharter!
