### ISSUE TITLE
Expose method to return the full path of a given dll name

### ISSUE THREAD

**Issue by jkotalik** [dotnet/core-setup#3458]
I need the ability to locate a native dll which will be in the runtime store before loading dotnet or the coreclr. The method could either return the full path of the specific dll or a property bag of all of the dlls locations.
```c++
PropertyBag GetDllLocations() {

}
or 
string GetDllLocation(string dllName) {

}
```

@steveharter and I discussed offline too. The method would need to be externally exposed on hostfxr.

**Comment by steveharter** [comment]
See also main feature https://github.com/dotnet/core-setup/issues/3457

**Comment by steveharter** [comment]
@jkotalik after thinking about this for a bit, would a synchronous callback function work instead? The callback would be invoked after all information is received and before the the coreclr initialzed and pass in information we agree on.

The advantage is that the extra loop through the entire hostfx->hostpolicy chain will be avoided.

e.g. something like this:
hostfxr_main_with_callback(const int argc, const pal::char_t* argv[], callback_fn* callback_fn)

**Comment by jkotalik** [comment]
That sounds fine to me. What would the signature of the callback_fn be? The specific dll or the property bag?

**Comment by steveharter** [comment]
> What would the signature of the callback_fn be? The specific dll or the property bag?

We'll need to work this out. I understand you don't want things to change if the coreclr interface changes. Currently the coreclr is initialized with "trusted platform assemblies" which is a simple semi-colon (windows) or colon (unix) delimited list.

**Comment by jkotalik** [comment]
> Currently the coreclr is initialized with "trusted platform assemblies" which is a simple semi-colon (windows) or colon (unix) delimited list.
If you return the semicolon delimited string, we can parse that for the specific assembly we need. Seems to be the most stable solution.

**Comment by jkotalik** [comment]
Actually, is it possible to return a vector<string> of the dll locations?

**Comment by steveharter** [comment]
The "trusted platform assemblies" include all known dlls (from the deps files). So see for yourself what the proposed callback will provide, set `COREHOST_TRACE=1`, run your app, and then look for `TRUSTED_PLATFORM_ASSEMBLIES` - you should see a long list of assemblies, each with a full path.

**Comment by steveharter** [comment]
@jkotalik actually the callback should only pass primitive types across the dll boundary - strings, ints, etc to avoid potential issues with having different memory layouts caused by different version\implementation of std:: classes, struct alignment compiler flags, etc. So not a vector.

**Comment by steveharter** [comment]
Based on prototype, the current code returns semicolon-delimited list (for Windows)

**Comment by jkotalik** [comment]
@steveharter the next time we consume down stack dependencies, I will try to use this new API. Thank you!
