### ISSUE TITLE
Cant install .net core on Ubuntu Server 16.04.1 LTS

### ISSUE THREAD

**Issue by xrkolovos** [dotnet/core-setup#347]
## Steps to reproduce
I just make a clean installation of Ubuntu Server 16.04.1 LTS.
i followed this guide -> [https://www.microsoft.com/net/core#ubuntu](https://www.microsoft.com/net/core#ubuntu)
and when i am running  sudo apt-get update
i get this error
N: Ignoring file 'dotnetdev.listsudo' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
W: http://repo.ajenti.org/debian/dists/main/InRelease: Signature by key 425E018E23944B4B42814EE0BDC3FBAA53029759 uses weak digest algorithm (SHA1)

so after this failure "sudo apt-get install dotnet-dev-1.0.0-preview2-003131" is not working and i get 
E: Unable to locate package dotnet-dev-1.0.0-preview2-003131

**Comment by gkhanna79** [comment]
@mellinoe Can you PTAL?

**Comment by mellinoe** [comment]
I just tried the steps on a VM here and they worked fine for me. @brthor or @blackdwarf might know more about the Debian installers specifically.

Here's the output I saw:

```
eric@eric-VirtualBox:~$ sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
eric@eric-VirtualBox:~$ sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
Executing: /tmp/tmp.IZxktzZ646/gpg.1.sh --keyserver
apt-mo.trafficmanager.net
--recv-keys
417A0893
gpg: requesting key 417A0893 from hkp server apt-mo.trafficmanager.net
gpg: key 417A0893: public key "MS Open Tech <interop@microsoft.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
eric@eric-VirtualBox:~$ sudo apt-get update
0% [Working]
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease      
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]
Hit:4 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease                
Get:5 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial InRelease [2,836 B]
Get:6 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main amd64 Packages [2,344 B]
Fetched 99.6 kB in 1s (82.9 kB/s)     
Reading package lists... Done
eric@eric-VirtualBox:~$ apt search dotnet
Sorting... Done
Full Text Search... Done
dotnet-dev-1.0.0-preview2-003121/xenial 1.0.0-preview2-003121-1 amd64
  Microsoft .NET Core 1.0.0 - SDK Preview 2
```

**Comment by blackdwarf** [comment]
@xrkolovos this line:

> N: Ignoring file 'dotnetdev.listsudo' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension

Indicates to mi like you've got an invalid list file. rename dotnetdev.listsudo to just dotnetdev.list and see if that fixes it.

**Comment by gkhanna79** [comment]
@piotrpMSFT @livarcocc @brthor This looks like dup of https://github.com/dotnet/cli/issues/4365

**Comment by brthor** [comment]
> N: Ignoring file 'dotnetdev.listsudo' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension

This definitely looks like the issue

**Comment by gkhanna79** [comment]
@piotrpMSFT Should this issue move to CLI repo for 1.1.0?

**Comment by piotrpMSFT** [comment]
This issue was identified as being an invalid file name, per @blackdwarf and @brthor above.
