### ISSUE TITLE
What is the link to the pdb zips for the shared framework?

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#3470]

**Comment by Petermarcu** [comment]
https://github.com/dotnet/core/issues/1112#issuecomment-347931813

**Comment by Petermarcu** [comment]
I think this is the right example that points to the latest. We just need to translate that to a concrete versioned link for the release notes and download pages.

https://dotnetcli.blob.core.windows.net/dotnet/Runtime/release/2.0.0/dotnet-runtime-symbols-latest-win-x64.zip

**Comment by steveharter** [comment]
@leecow PTAL. Thanks

**Comment by leecow** [comment]
Links to symbols, as packaged by @dagood, are provided on each download page:

- [1.0.9](https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.9-download.md)
- [1.1.6](https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.6-download.md)
- [2.0.5](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.5-download.md)

**Comment by livarcocc** [comment]
I am closing this issue since I am not sure what it is still tracking. If there is value in keeping it open, just re-activate.
