### ISSUE TITLE
Conflicting installation instructions for Linux

### ISSUE THREAD

**Issue by leopignataro** [dotnet/core-setup#3499]
Right now, there are two sets of very different instructions on how to install the .NET Core SDK on Linux:

1. https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites
2. https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.0.3-linux-x64-binaries

[1] contains installation instructions with apt-get, while [2] directs users to a completely different procedure consisting of downloading a .tar.gz file and extracting it to the $HOME directory.

As a member of the user community, this is very confusing, specially when trying to write installation documentations for our products which involve installing the .NET Core *Runtime* (for which I simply cannot find instructions).

The instructions on the Microsoft site used to be with apt-get, only recently have they changed to this tar.gz-on-home method. Is this the new official recommendation? How does this apply to globally installing the .NET Core Runtime?

**Comment by rakeshsinghranchi** [comment]
@leecow , PTAL

**Comment by leecow** [comment]
@leopignataro - thanks for the feedback. It's on my plate to iron out these inconsistencies and missing guidance like the runtime in the short term. 

The preferred option would be to use the package managers to install the runtime. Detailed instructions registering the feeds for supported distros can be found at https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites. If the app does not need ASP.NET Core features, you only need to install `dotnet-runtime-2.0.4` (the current latest release). If the app does need ASP features then also install `aspnetcore-store-2.0.3`.

Let me know if there are any questions.

**Comment by leopignataro** [comment]
Thank you for the information, @leecow !

That is more or less what we're going with right now, with one main difference when it comes to adding the packages feed.

For instance, on Ubuntu 16.04, instead of

```sh
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
```

We're instructing users to do

```sh
wget -qO - https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
```

Or, on CentOS / Oracle Linux, instead of

```sh
sudo sh -c 'echo -e "[packages-microsoft-com-prod]\nname=packages-microsoft-com-prod \nbaseurl=https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/dotnetdev.repo'
```

We're using:

```sh
curl https://packages.microsoft.com/config/rhel/7/prod.repo | sudo tee /etc/yum.repos.d/microsoft.repo
```

Apart from subtle differences on the actual commands used (we're favoring `tee` instead of the cumbersome combination of `sudo+sh+echo`), the big difference which I'm referring to here is that we are using the files available on https://packages.microsoft.com/config which make for simpler instructions. TBH I don't even remember how we found out about those, since there's so many different instructions about this from Microsoft.

My question is: Is this a valid approach? Will these files on `/config` be maintained? Which approach would be preferable?

PS: if you're interested on our use case you can view our setup instructions on https://docs.lacunasoftware.com/en-us/articles/pki-express/setup/

**Comment by leopignataro** [comment]
@leecow , sorry to bother you even further, but we actually have one other question:

What's the story with the version suffix on the package names?

* dotnet-runtime-**2.0.3**
* dotnet-runtime-**2.0.4**
* dotnet-runtime-**2.0.5**

I guess this means an `apt-get upgrade` won't update the .NET Core Runtime. Is this by design? We're worried about having outdated runtimes on our clients' servers, specially when it comes to security updates. Shouldn't there be a `dotnet-runtime-2` package which contains the latest 2.x version? (or maybe a `dotnet-runtime-2.0` package containing the latest 2.0.x version, depending on how MS is planning future breaking changes)

Thank you again for your attention!

**Comment by leecow** [comment]
Hi @leopignataro - I like your approach to repo registration and after looking into it, may well 'borrow' what you've done to update our instructions. Another option I've been thinking of is to include registration in the runtime and sdk packages so you download and run locally once, then everything is set up. 

With respect to the version suffix, that's an artifact of us not quite getting thing right. Fixing it so that apt-get upgrade/update work correctly moves to the top of my list after this week. You're idea about a dotnet-runtime-2 (or -2.0) are in line with the direction I'm heading.

**Comment by leopignataro** [comment]
> With respect to the version suffix, that's an artifact of us not quite getting thing right. Fixing it so that apt-get upgrade/update work correctly moves to the top of my list after this week. You're idea about a dotnet-runtime-2 (or -2.0) are in line with the direction I'm heading.

That is great news, @leecow ! We'll stay tuned!

As for the usage of `tee`, we like it because it allows us to avoid the problems involved in using `>` together with `sudo`, which end up leading to mixing single and double quotes, which in turn can be troublesome because the interpretation of double quotes tend to vary between distros and shells. I should say, however, that we are not sure that the `tee` command is available on all distros supported by .NET Core (it is on the ones we support, i.e. Ubuntu, RHEL and Oracle/CentOS).

Thank you very much for your clarifications. Our understanding of the .NET Core Runtime installation is much better now.

**Comment by leecow** [comment]
@leopignataro - I've made revisions to the instruction on [2.0.5-download](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.5-download.md). Have a look if you get a chance to check my work :-)

Regarding `tee`, I went with `mv` where the manual route was needed. Otherwise, I'm using the `packages-microsoft-prod.deb` or `packages-microsoft-prod.rpm` where provided.

**Comment by leopignataro** [comment]
@leecow , I finally got a chance to check the link you sent. The approach of having a `.deb` to add the GPG key and product feed is interesting, we had never seen it before. Here are some notes:

1. Given that the *packages-microsoft-prod.deb* package installs both the package feed and the GPG key and that installing it without first manually adding the key does not raise any warnings (tested on Ubuntu 16.04), is it really necessary to manually add the key before installing the package?

2. I believe some of your `curl` commands are missing the `-O` flag (the ones that are meant to save the file on the current directory).

**Comment by livarcocc** [comment]
@leecow are the instructions now up to date so that we can close this issue?
