### ISSUE TITLE
debian packages install to the wrong location

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#3506]
@Spongman commented on [Fri Dec 08 2017](https://github.com/dotnet/core/issues/1141)

according to https://wiki.debian.org/FilesystemHierarchyStandard the `/opt` directory is for "Pre-compiled, non ".deb" binary distribution".

the dotnet packages _are_ .deb packages, and so therefore should not go into `/opt`. Also, the `dotnet` symlink should go into `/usr/bin` _not_ `/usr/local/bin`. `/usr/local` is reserved for use by the system administrator.

---

@richlander commented on [Sat Dec 09 2017](https://github.com/dotnet/core/issues/1141#issuecomment-350486410)

PTAL @leecow

**Comment by leecow** [comment]
I think the locations mentioned by @Spongman are from earlier 1.0.x instructions and should match the FHS guidelines beginning with 1.0.7.
