### ISSUE TITLE
`System.Private.CoreLib` doesn't always line up with the CoreFX assemblies

### ISSUE THREAD

**Issue by tannergooding** [dotnet/core-setup#3516]
`v2.2.0-preview1-007460` of the CLI includes `v2.1.0-preview1-25825-07` of core-setup.

That particular build of core-setup has an inconsistency between an API exposed by `System.Private.CoreLib` and one of the APIs consumed by `System.IO.Compression`.

More specifically, ``System.IO.Compression.Deflater.SetInput(ReadOnlyMemory`1 inputBuffer)`` (in `System.IO.Compression`) is consuming `MemoryHandle.get_PinnedPointer()` while `System.Private.CoreLib` is exporting `MemoryHandle.get_Pointer()`. This particular rename happened here: https://github.com/dotnet/coreclr/commit/df095c07496879a2e833bc55f97e7ab228bcf5ed#diff-85416a04988097d977f6df3d0144b2c0

The issue appears to be resolved in the latest builds of core-setup, but I was not able to find any explicit fixes addressing this. As such, I believe there may exists a more fundamental issue with how builds of CoreFX and CoreCLR are paired/pulled into core-setup and it may be worth further investigation.

**Comment by tannergooding** [comment]
CC. @safern

**Comment by safern** [comment]
Assigning myself to investigate.

**Comment by tannergooding** [comment]
This currently has a `needs more info` tag.

What additional info is required?

**Comment by rakeshsinghranchi** [comment]
@safern , do you have an update on this ?

**Comment by safern** [comment]
Not yet. I was OOF for the past month, haven't being able to take a look at it. 

cc: @wtgodbe which is the owner of servicing branches now, should you take this one now?

**Comment by dagood** [comment]
Closing: consolidation obviates this issue, coreclr and corefx can't get mismatched anymore.
