### ISSUE TITLE
Server GC is not activated with latest runtime/sdk

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#3528]
_From @sebastienros on December 14, 2017 0:37_

We migrated an app to use a very recent runtime. Since then the server GC is not active anymore.

I forced it in the csproj:

```xml
  <PropertyGroup>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>
```

And I can see this runtimeconfig file generated when the app is published:

```json
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.1.0-preview1-26008-01"
    },
    "configProperties": {
      "System.GC.Server": true
    }
  }
```

The SDK is ` 2.2.0-preview1-007796`

Then at runtime we display whether the server GC is enabled or not:

```csharp
Console.WriteLine($"Server GC is currently {(GCSettings.IsServerGC ? "ENABLED" : "DISABLED")}");
```

Which displays

```
Server GC is currently DISABLED
```

_Copied from original issue: dotnet/cli#8237_

**Comment by livarcocc** [comment]
This needs to be honored by the runtime, given that it is present in the runtimeconfig. I am moving this issue to core-setup.

**Comment by pakrym** [comment]
@swgillespie I think you've observed a similar issue when trying to repro GC bug. Can you please look at this?

**Comment by swgillespie** [comment]
It looks like the host is not passing us the `System.GC.Server` property key. These are the only ones that get passed to `coreclr_initialize` on startup:

```
0:000> ?? propertyCount
int 0n9
0:000> ?? propertyKeys[0]
char * 0x00007ff9`4e8fb280
 "TRUSTED_PLATFORM_ASSEMBLIES"
0:000> ?? propertyKeys[1]
char * 0x00007ff9`4e8fb2a0
 "NATIVE_DLL_SEARCH_DIRECTORIES"
0:000> ?? propertyKeys[2]
char * 0x00007ff9`4e8fb2c0
 "PLATFORM_RESOURCE_ROOTS"
0:000> ?? propertyKeys[3]
char * 0x00007ff9`4e8fb2d8
 "AppDomainCompatSwitch"
0:000> ?? propertyKeys[4]
char * 0x00007ff9`4e8fb2f0
 "APP_CONTEXT_BASE_DIRECTORY"
0:000> ?? propertyKeys[5]
char * 0x00007ff9`4e8fb310
 "APP_CONTEXT_DEPS_FILES"
0:000> ?? propertyKeys[6]
char * 0x00007ff9`4e8fb328
 "FX_DEPS_FILE"
0:000> ?? propertyKeys[7]
char * 0x00007ff9`4e8fb338
 "PROBING_DIRECTORIES"
0:000> ?? propertyKeys[8]
char * 0x00007ff9`4e8fb378
 "JIT_PATH"
```

**Comment by pakrym** [comment]
Looks like https://github.com/dotnet/core-setup/pull/3512

**Comment by steveharter** [comment]
Closing this as dup of #3512
