### ISSUE TITLE
Support "framework wins over app" or "lower layer wins" during major\minor roll-forward

### ISSUE THREAD

**Issue by steveharter** [dotnet/core-setup#3546]
This is a core-setup feature to address https://github.com/dotnet/corefx/issues/24090 in a generalized way by supporting a lower layer (e.g. NetCoreApp) to win \ be selected when there is already a copy of that assembly in a higher layer (e.g. the app's folder). In 2.0, the higher layer always wins.

The issue [24090](https://github.com/dotnet/corefx/issues/24090) was addressed for 2.1 preview 1 by duplicating and renaming the assembly. However, it does not solve the issue generally, so this core-setup issue was created to track that. The issue can occur again, including with frameworks other than NetCoreApp such as upcoming Asp.Net framework support which will use the recent multi-layer framework support.

For example, with the new multi-layer framework support the following layers could exist:
- App (the highest layer)
- ASP.NET
- NetCoreApp (the lowest layer)

The three scenarios\outcomes determining which layer should win when a given assembly exists in more than one layer:
**i.** Lower layer should win. This is the scenario as described in [24090](https://github.com/dotnet/corefx/issues/24090) repro steps where an assembly was added to framework package is newer than the app's
**ii.** Higher layer should win. For example, the app wants to bring in a newer OOB assembly like System.Collections.Immutable. This could change into scenario (i) when an app's copy of an OOB assembly becomes older than the current framework's assembly during a roll-forward scenario.
**iii.** Unknown who should win. For example, the app has locally build framework assemblies (not package references).

Currently (in 2.0) the only rule for when a given assembly exists in more than one layer:
**1.** The highest layer wins

The proposed supplementary rule for 2.1:
**2.** If a [major] or [minor] roll-forward occurs for a given framework, that framework wins over any other higher layer(s)

Note this rule does not apply to just patch roll-forward as patches are not supposed to add\remove assemblies and because the higher layer likely has a higher versioned assembly (by major\minor).

The rationale for rule 2 is because the given assembly will likely be newer than the layers above, since the layers above likely shipped at an earlier time and its copy of the assembly is likely older. In addition, it is likely the given assembly is new to that lower layer, and the higher layers could not yet be updated to remove their copy of that assembly.

Because these two rules do not work in all cases, the following can be used as workarounds by the person trying to run the app:
a) Install the targeted framework. No [major][minor] roll-forwards occur unless the targeted framework does not exist.
b) If the app has a newer version that targets the newer framework (that was rolled-forwared to) then install that new version of the app, or if you own the app then re-target to the newer framework.
c) If an app (or higher framework) knows the lower-level framework does not work in a roll-forward case, it can mitigate the issue by adding `rollForwardOnNoCandidateFx = 0` to the app's (or higher framework's) deps.json file. This will force option (a) above, but still allows for patch roll-forward.

However, these workarounds are not sufficient in all cases.

Rules 1 and 2 will not work when you have an app that wants to support older frameworks, and thus wants to be both backwards- and forward-compatible. For example, if an app is created at around the 2.5 timeframe but targets 2.0 (because it wants to support 2.0 - 2.4) and contains an OOB assembly that is the same as the framework's 2.5, it would want to use the app's newer OOB for 2.0 - 2.4, but use the framework's copy of the OOB for versions 2.6-2.9+ because it will likely be newer. However, with rule 2, running on 2.1 will cause the 2.1 framework's older OOB to be used because a role-forward occurred from 2.0 (the version the app targeted) to 2.1 and rule 2 states to use the framework's copy.

Because of this we need a more assembly-version-based approach. This would add another rule:
**3.** If a [major] or [minor] roll-forward occurs and metadata exists for the given duplicate assemblies, pick the highest version. This rule has precedence over rule 2.

Note that assembly version could be used instead, but file version appears better because it should be more representative of the actual chronological age of a file as assembly version is not always changed. File metadata will likely consist adding the file versions to every deps.json (the app's and each framework). If metadata does not exist in deps.json, we need to determine if we want to inspect the physical file at run-time which is cheap on Windows (since the file version is part of the PE header) but expensive on Unix\OSX because the file will need to be "cracked" to obtain the AssemblyFileVersion attribute.

Finally, if rule 3 is implemented fully with a fallback to gathering the file version information at run-time if the deps.json metadata is not present, and this is back-ported to 2.0.x, then rule 2 probably isn't necessary.

So this issue tracks proposed solution for rules 2 and 3.

UPDATE: we are assuming adding rule 3 only; rule 2 should not be necessary.

**Comment by Petermarcu** [comment]
Are we going to scope this to Minor version roll forward only? That was the original thinking. Basically, if an application is running on the framework it targeted when it was built and still has a lower or equal version of an assembly, we can assume that they want that assembly in the app to be the one chosen. I could see this happening if people fork source to apply a bug fix for example. This feature is more for the scenario where in a future minor update of a shared framework an version of an assembly that may have been app local is now in a shared framework.

**Comment by steveharter** [comment]
Yes framework wins will occur only during roll-forward of minor. I will add clarification above. Thanks
