### ISSUE TITLE
Windows zips don't extract correctly on non-Windows platforms

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/core-setup#3577]
## Steps to reproduce
Download https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/dotnet-runtime-latest-win-x64.zip
Extract on macOS using Finder. (Issue also happens with zip utilities on Linux)

## Expected  behavior
Correct directory structure.

## Actual behavior
File names contain backslashes.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/2696087/34690845-8d1785ba-f46f-11e7-95b9-2a4f0087cf48.png">

cc @weshaggard

**Comment by weshaggard** [comment]
I expect we are hitting https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/mitigation-ziparchiveentry-fullname-path-separator when using our zip task.

**Comment by dagood** [comment]
Closing, this issue is stale and we couldn't determine a customer need in triage.
