### ISSUE TITLE
Cleanup readme instruction on how to install from `Debian daily feed`

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/core-setup#3598]
The repo's [README.md](https://github.com/dotnet/core-setup/tree/master#debian-daily-feed) has instructions on how to install from the `Debian daily feed`.  It is my understanding that daily builds are no longer being pushed to a Debian feed.  Looking at the http://apt-mo.trafficmanager.net/repos/dotnet/ feed aligns with this as the latest drops are old.  The instructions in the readme for how to install from the `Debian daily feed` should get cleaned up.

**Comment by steveharter** [comment]
cc @rakeshsinghranchi

**Comment by rakeshsinghranchi** [comment]
Fixed in https://github.com/dotnet/core-setup/pull/3617
