### ISSUE TITLE
Consider generating PackageConflictOverrides in Microsoft.NETCore.App

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#3607]
The .NET Core SDK implemented a performance enhancement with https://github.com/dotnet/sdk/pull/1805 that allows the conflict resolution tasks to not need to load assemblies in the common case.  This works by using a bit of MSBuild metadata called PackageConflictOverrides.  These items tell conflict resolution that if it sees a conflict between two NuGet packages, with certain versions, it can immediately resolve the conflict without loading assemblies.

Since Microsoft.NETCore.App and NETStandard.Library 2.0.0 had already shipped, we couldn't add this metadata into the packages.

However, going forward we could consider generating this metadata in new Microsoft.NETCore.App and NETStandard.Library packages, if more package overrides are created and we see a performance degradation again.  See https://github.com/dotnet/sdk/pull/1805#discussion_r156185225.

/cc @ericstj @nguerrera @weshaggard

**Comment by dagood** [comment]
> However, going forward we could consider generating this metadata in new Microsoft.NETCore.App and NETStandard.Library packages, if more package overrides are created and we see a performance degradation again.

Is this something that can happen in 3.0? Will the move away from "real" NuGet packages to packs make generation not useful?

If the override list won't change at all in the future, maybe we can close this issue.

**Comment by eerhardt** [comment]
I think this issue can now be closed with #6507. The only thing listed here that wasn't explicitly covered is generating the overridden packages and versions, but I'm not sure that is worth the effort. If we find maintaining that the .txt file manually is too cumbersome, we can re-open this issue, or just create a new one at that time.
