### ISSUE TITLE
PKG postinall script for the host needs to create /etc/paths.d

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/core-setup#361]
On macOS Sierra, users have been unable to get `dotnet` on the path. After gracious help from @the-darkvoid, the root cause was narrowed down to the fact that on a clean install of Sierra, the `/etc/paths.d` path does not exist, and thus the `/etc/paths.d/dotnet` file cannot be created. 

The installer should include this step in the post-install script via `mkdir -p`.

**Comment by gkhanna79** [comment]
Closing since this is fixed.
