### ISSUE TITLE
prodcon/core-setup:  error NU1202: Package Microsoft.Private.CoreFx.UAP 4.6.0-preview1-26119-05 is not compatible with uap10.0.15138

### ISSUE THREAD

**Issue by MattGal** [dotnet/core-setup#3610]
@dotnet-mc-bot commented on [Fri Jan 19 2018](https://github.com/dotnet/core-eng/issues/2447)

Opened on behalf of @jcagme

Warnings: 3
Status Message: failed

Build : Prod Con - 20180119.02 (Product Build)
Failing configurations:
- Windows
  - PortableBuild-x86
  - PortableBuild-x64
  - PortableBuild-arm
- OSX
  - PortableBuild-x64
- Ubuntu 14.04
  - PortableBuild-arm
- Alpine3.6
  - x64
- RedHat6
  - x64
- RedHat 7
  - PortableBuild-x64
[Mission Control Build Info](https://mc.dot.net/#/product/netcore/prodcon/source/prodcon~2Fcore-setup~2Fmaster~2F/type/build~2Fproduct~2F/build/20180119.02/workItem/Orchestration/analysis/external/Link)

**Comment by steveharter** [comment]
cc @weshaggard

**Comment by weshaggard** [comment]
This was fixed with https://github.com/dotnet/core-setup/commit/403a916d7103e777c76fb9a9ca188a844880509a
