### ISSUE TITLE
Remove "Fetch symbol signing tooling" and related steps from Publish definition

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#3615]
This step should no longer be needed because we are now using `Microsoft.SymbolUploader.Build.Task` acquired during init-tools.

Specifically, the steps are "Clone tools”, "Fetch symbol signing tooling",  "Cleanup previous tools source if present".

**Comment by weshaggard** [comment]
We should be able to remove the tool embedindex from the repo as well.

**Comment by wtgodbe** [comment]
This is done with the move to Azure DevOps
