### ISSUE TITLE
Shared Framework and HostFxr x64 MSIs write only to 32-bit hive

### ISSUE THREAD

**Issue by rakeshsinghranchi** [dotnet/core-setup#3671]
MSIs are marked to _not_ install on win64 hive. 
https://github.com/dotnet/core-setup/blob/master/src/pkg/packaging/windows/hostfxr/registrykeys.wxs#L6
https://github.com/dotnet/core-setup/blame/master/src/pkg/packaging/windows/sharedframework/registrykeys.wxs#L6

**Comment by steveharter** [comment]
@rakeshsinghranchi is this a 2.1 issue?

**Comment by rakeshsinghranchi** [comment]
This is by design : https://github.com/dotnet/cli/commit/9142ad79bb845aa4b065aa034d71c9e865696ac0#diff-3b7392fa2639937bbc3db122ddaf03b7
