### ISSUE TITLE
Microsoft.Extensions.DependencyModel should target netstandard2.0

### ISSUE THREAD

**Issue by ericstj** [dotnet/core-setup#3680]
We should have at least a dependency group for ns2.0 so that we don't bring down unnecessary dependencies.

**Comment by steveharter** [comment]
cc @eerhardt for triage

**Comment by eerhardt** [comment]
@ericstj - I assume the same applies for https://www.nuget.org/packages/Microsoft.Extensions.PlatformAbstractions/, since DependencyModel depends on it.

**Comment by ericstj** [comment]
Yes.

**Comment by tom-corwin** [comment]
Is there an ETA on this by chance?

**Comment by eerhardt** [comment]
@tom-corwin - thanks for the reminder. I just put a PR for this that should solve it for 3.0.

**Comment by tom-corwin** [comment]
Thanks for the update @eerhardt
