### ISSUE TITLE
Update Readme to provide installer links to newly added distro support

### ISSUE THREAD

**Issue by rakeshsinghranchi** [dotnet/core-setup#3709]

**Comment by rakeshsinghranchi** [comment]
@leecow , core-setup has been producing native installers for all Linux x64 distros.However, these are not yet in the readme page. Do you have plans on updating readme layout on simplifying it ?

**Comment by leecow** [comment]
Yes, just need to carve out the time to do so :-)

**Comment by danmosemsft** [comment]
@leecow do you expect to have this done by 3/30 (our ZBB) 😼

**Comment by leecow** [comment]
Updated with key distros. Page is in need of redesign but that will be a separate task.
