### ISSUE TITLE
Mark UWP packages as NonShipping=true (product construction)

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#3734]
In orchestrated builds, `Microsoft.Net.UWPCoreRuntimeSdk` and `Microsoft.NETCore.UniversalWindowsPlatform` (and the corresponding `runtime` packages) should be marked `NonShipping="true"` because they're not meant to be published to the NuGet Gallery.

Example manifest without NonShipping:

https://github.com/dotnet/versions/blob/beb08dc78641604883b17ee3010e602378b1c361/build-info/dotnet/product/cli/release/2.1/build.xml#L317

We will start to rely on this attribute with automated pushes: https://github.com/dotnet/core-eng/issues/2334.

/cc @weshaggard

**Comment by weshaggard** [comment]
We have removed these from master already so once we integrate changes into the release/2.1 branch this should no longer be an issue.

**Comment by eerhardt** [comment]
UWP assets are no longer in this repo.  The changes have been merged to `release/2.1`. Closing.
