### ISSUE TITLE
An assembly specified in the application dependencies manifest has already been found

### ISSUE THREAD

**Issue by pranavkm** [dotnet/core-setup#3762]
## Steps to reproduce
MvcPrecompilation tool (https://github.com/aspnet/MvcPrecompilation) runs the tool binary in the context of the app's deps file. Something along the lines of

```
dotnet exec --runtimeconfig App.runtimeconfig.json --depsfile App.deps.json Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll --some-arguments
```

Since upgrading to 2.1.0-preview2-26225-03 of the runtime, running the tool fails with

```
An assembly specified in the application dependencies manifest (App.deps.json) has already been found but with a different file extension:
      package: 'Microsoft.AspNetCore.Mvc.Razor', version: '2.1.0-preview2-30220'
      path: 'lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.dll'
      previously found assembly: 'Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll'
```

Renaming the tool to have a different file name fixes the issue i.e. if I rename the file to `Microsoft.AspNetCore.Mvc.RazorExtraStuff.ViewCompilation.dll`, it works. Looks like the extension matching introduced as part of https://github.com/dotnet/core-setup/commit/348572725673b54aca474974a6ea4f05a2d479b3#diff-e94bade1ef46d04f2589e7f27ca52501R447 is incorrect

**Comment by natemcmaster** [comment]
What's in the deps.json file?

**Comment by pranavkm** [comment]
https://gist.github.com/pranavkm/55dd426ee77b07776ff688a171562f2b

**Comment by steveharter** [comment]
@pranavkm please try a later build. There was an issue but fixed with https://github.com/dotnet/core-setup/pull/3737

**Comment by pranavkm** [comment]
Yup, tried build 2.1.0-preview2-26228-04 of the runtime and this issue is fixed. cc @sebastienros who was also seeing this issue

**Comment by pranavkm** [comment]
cc @ryanbrandenburg who's investigating this on our CI

**Comment by sacreo** [comment]
Uninstall it, that will fix the problem
