### ISSUE TITLE
Request https://dotnetcli.blob.core.windows.net/dotnet?restype=container&comp=list failed with status Forbidden

### ISSUE THREAD

**Issue by jcagme** [dotnet/core-setup#3764]
@jcagme commented on [Fri Mar 02 2018](https://github.com/dotnet/core-eng/issues/2809)

This has hit the last build attempts in Core-Setup and affects all the build legs. This might related to an expired token given the nature of the error.

**Comment by jcagme** [comment]
As per @MattGal this is caused by using an expired token. Secrets in Key Vault were cycled so you'll need to use the newest in Key Vault

**Comment by MattGal** [comment]
The secrets core-setup-connection-string and core-setup-azure-access-token are duplicates of dotnetcli-storage-key and shouldn't exist.  I'm not sure who to work with to get this cleaned up. 

My recommendation:  Delete the incorrectly named dupes, replace their usage with dotnetcli-storage-key.

**Comment by MattGal** [comment]
* I've disabled those two secrets for now;  @weshaggard will update any remaining builds which fail.

**Comment by weshaggard** [comment]
I updated the strings in the core-setup release/1.0.0, release/1.1.0, and release/2.0.0 definitions so those should work. 

The MSRC definitions need to be updated to use keyvault which I just pinged @chcosta about and once that happens then those should be fixed as sell.

**Comment by weshaggard** [comment]
fyi @wtgodbe in case you hit issues building core-setup release branches.

**Comment by steveharter** [comment]
Does anyone have an update on this? @weshaggard @chcosta

**Comment by weshaggard** [comment]
@steveharter this should be fixed in master branches already. There was a related yet separate one https://github.com/dotnet/core-eng/issues/2814 this morning which has been addressed as well.

**Comment by steveharter** [comment]
Looks like we just got a good build: https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1442700&_a=summary
