### ISSUE TITLE
Installing a final version of an SDK should remove preview versions

### ISSUE THREAD

**Issue by onovotny** [dotnet/core-setup#3770]
See this thread:

https://twitter.com/DamianEdwards/status/969762795926429696

Issue is that after a while, users wind up with tons of preview SDK's (either due to direct install or by being chained into a VS Preview channel update). They never get uninstalled.

Installing the final version of an SDK should remove the corresponding preview versions as it's very unlikely that a user would intend on having the older previews alongside.

/cc @nickcraver

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8720](https://github.com/dotnet/cli/issues/8720) via [**ZenHub**](https://www.zenhub.com/)
