### ISSUE TITLE
Add tests to verify hostfxr with older hostpolicy

### ISSUE THREAD

**Issue by steveharter** [dotnet/core-setup#3777]
This issue is to add automated tests to verify a newer version of hostfxr running against older versions of hostpolicy.

This can break because of incorrect "contract" semantics, or because of unix\osx symbol-based export and merging (https://github.com/dotnet/corefx/issues/27571).

**Comment by pakrym** [comment]
I would also add a set of tests that verify old dotnet.exe with new hostfxr and old runtime. I know we don't think that anything can break between dotnet and hostfxr but better safe then sorry.

**Comment by karelz** [comment]
Test work item which didn't fit due to other high-pri features - marking as Post-ZBB

**Comment by steveharter** [comment]
Planning to port this to 2.1.x when the 2.2 tests are ready
