### ISSUE TITLE
Ubuntu.18.04 libcurl3 dependency is out of date.

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/core-setup#3791]
The [Ubuntu 18.04 debian package](https://github.com/dotnet/core-setup/blob/master/src/pkg/packaging/deb/dotnet-runtime-deps-debian_config_ubuntu.17.10-x64.json) lists libcurl3 as a dependency.  libcurl3 is no longer the most recent and has compatibility issues with Curl.  Curl recently changed it's libcurl depencency - see http://changelogs.ubuntu.com/changelogs/pool/main/c/curl/curl_7.58.0-2ubuntu2/changelog.

>  curl (7.58.0-2ubuntu2) bionic; urgency=medium
> 
>   * Build-depend on libssl-dev instead of libssl1.0-dev.
>   * Rename libcurl3 to libcurl4, because libcurl exposes an SSL_CTX via
>     CURLOPT_SSL_CTX_FUNCTION, and this object changes incompatibly between
>     openssl 1.0 and openssl 1.1.
>   * debian/patches/03_keep_symbols_compat.patch: drop, since we are no longer
>     claiming compatibility.
>   * debian/patches/90_gnutls.patch: Retain symbol versioning compatibility for
>     non-OpenSSL builds.  Closes: #858398.
> 
>  -- Steve Langasek <steve.langasek@canonical.com>  Wed, 21 Feb 2018 08:21:31 -0800

Has the runtime been tested with libcurl4 on Ubuntu.18.04?  Is libcurl4 known to work with the runtime?

**Comment by MichaelSimons** [comment]
@rakeshsinghranchi - did you followup to ensure the runtime is testing with libcurl4 on ubuntu 18.04?

**Comment by rakeshsinghranchi** [comment]
@leecow helps getting the test coverage. @leecow , Do we have test coverage for Ubuntu 18.04 ?

**Comment by MichaelSimons** [comment]
We are already testing on Ubuntu 18.04.  When I looked at a repo machine last week it had libcurl3 on it.  I would suggest working with @MattGal on upgrading to libcurl4.

**Comment by leecow** [comment]
As Michael mentions, 18.04 infrastructure and testing for repos are either up or on the way.

**Comment by salaros** [comment]
Ubuntu 18.04 is going to be the next LTS and will be release in about one month.
PHP 7.2 and other packages already rely on libcurl4, so on my setup .NET Core is the only package blocking me from upgrading to libcurl4

**Comment by Petermarcu** [comment]
In .NET Core 2.1 there will be no libcurl dependency so that is the most likely time for us to be able to remove the libcurl3 dependency.

**Comment by scottstensland** [comment]
Any update on this ?   folks are chomping at the bit https://askubuntu.com/questions/1030584/cant-install-sql-server-on-ubuntu-18-4-due-to-openssl

**Comment by Spongman** [comment]
please fix this ASAP. upgrading to `libcurl4` *uninstalls* the dotnet framework & sdk.
