### ISSUE TITLE
Cannot seem to install .net core on debian stretch ("Couldn't find any package")

### ISSUE THREAD

**Issue by Jofairden** [dotnet/core-setup#3799]
Cannot seem to install .net core on debian stretch
Tried everything listed in the previous issue ( #3435 )
## Steps to reproduce
Attempt to install .net core on linux debian stretch (9) arch64:

- Follow instructions on official page: https://www.microsoft.com/net/download/linux-package-manager/debian9/sdk-current (all instructions followed and executed without problems, until the last command `apt-get install`)

## Expected  behavior

- .net core install without a hitch, like it did about a year ago

## Actual behavior

```
sudo apt-get install dotnet-sdk-2.1.4
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.1.4
E: Couldn't find any package by glob 'dotnet-sdk-2.1.4'
E: Couldn't find any package by regex 'dotnet-sdk-2.1.4'
```
`apt search dotnet-sdk` yields:
```
apt search dotnet-sdk
Sorting... Done
Full Text Search... Done
dotnet-sdk-2.0.0/stretch 2.0.0-1 amd64
  Microsoft .NET Core SDK - 2.0.0

dotnet-sdk-2.0.0-preview2-006497/xenial 2.0.0-preview2-006497-1 amd64
  Microsoft .NET Core SDK 2.0.0 Preview 2

dotnet-sdk-2.0.2/stretch 2.0.2-1 amd64
  Microsoft .NET Core SDK - 2.0.2

dotnet-sdk-2.0.3/stretch 2.0.3-1 amd64
  Microsoft .NET Core SDK - 2.0.3

dotnet-sdk-2.1.2/stretch 2.1.2-1 amd64
  Microsoft .NET Core SDK - 2.1.2

dotnet-sdk-2.1.3/stretch 2.1.3-1 amd64
  Microsoft .NET Core SDK - 2.1.3

dotnet-sdk-2.1.300-preview1-008174/stretch,xenial 2.1.300-preview1-008174-1 amd64
  Microsoft .NET Core SDK 2.1.300 - Preview

dotnet-sdk-2.1.4/stretch 2.1.4-1 amd64
  Microsoft .NET Core SDK - 2.1.4
```

## Environment data

`Linux scw-5bbbaa 4.9.23-std-1 #1 SMP Mon Apr 24 13:18:14 UTC 2017 aarch64 GNU/Linux`
Debian 9 "Stretch"

**Comment by eerhardt** [comment]
@leecow @rakeshsinghranchi @wli3 - any ideas?

**Comment by omajid** [comment]
> aarch64

That's an ARM 64 box. Do we have any builds for this platform?

**Comment by Jofairden** [comment]
Yep it's ARM64, I had a friend tell me he was also running it on ARM64 with the normal install instructions. (it's not an issue, right?)

**Comment by Petermarcu** [comment]
I don't think we have an SDK for ARM at all, just a runtime for ARM32. I don't know of an ARM64 build that is consumable although I know we are building the core parts of the runtime for arm64 https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_debug_small_page_size_innerloop_prtest/1552/ .

It isn't being built full stack and made into an something installable.

**Comment by eerhardt** [comment]
Oh I missed the `arch64` part... my bad.

The .NET Core SDK `2.1.4` doesn't support ARM32 or ARM64 on Linux.  You can see the supported platforms here:  https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md.

There are some instructions on how to get the .NET Core runtime running on ARM32 here: https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md

**Comment by Petermarcu** [comment]
One note, I have seen people running 32bit OS's on ARM64 chips and being successful using the runtime (not the SDK).

**Comment by eerhardt** [comment]
Closing this issue, since this isn't a supported scenario.

@Petermarcu - do you have a link to the tracking issue for `ARM64` support on Linux?

**Comment by Petermarcu** [comment]
Looks like @sdmaclea is working on adding it to the builds right now. https://github.com/dotnet/coreclr/pull/16707

**Comment by sdmaclea** [comment]
> One note, I have seen people running 32bit OS's on ARM64 chips and being successful using the runtime 

Arm32 support is optional on Arm64.  Arm32 Dotnet Core can be run on 32 or 64 bit OS if aarch32 is supported.

**Comment by Jofairden** [comment]
So, I guess I'm forced to get a x64 server for this? Darn...

**Comment by Petermarcu** [comment]
Or install and arm32 OS.

**Comment by omajid** [comment]
See also https://github.com/dotnet/cli/issues/1854
