### ISSUE TITLE
Extend SDK version entry in global.json

### ISSUE THREAD

**Issue by jaredpar** [dotnet/core-setup#3807]
This is a feature request. Would really like to see an extension to the global.json SDK entry that allows me to specify that the SDK must match **exactly** what is in global.json. 

The ability to specify a sdk version in global.json is only useful if it can guarantee that I have an SDK of **at least** the version specified. The behavior today allows for SDKs with a lower version to be chosen even when a higher SDK is available. This means that I cannot use global.json to ensure that I'm using an sdk which has the bug fixes necessary to build my repository. 

The current behavior leads to issues like #3805 which will be closed as "By Design". There are bug fixes our repository absolutely depends on. Yet even though I have specified the correct minimum SDK, and have SDKS on the machine of a higher version, `dotnet` inexplicably silently picks a lower one. Instead of a polite error message about missing SDKs I have to close my console window because there are so many errors that even Ctrl-C is ineffective. 

I'm guessing this is a compat problem at this point. Hence I recommend extending the entry something like the following:

``` json
{
  "sdk": {
    "version": "2.1.300-preview1-008174",
    "enforceVersion": "true"
  }
}

**Comment by nguerrera** [comment]
cc @KathleenDollard I think there's overlap with this and other things being discussed.

**Comment by nguerrera** [comment]
I reopened #3805. My quick reading of "enforceVersion" was that it should never pick anything but exact version (this has been on the table before), but #3805 shows a case where a roll-backward occured and that shouldn't happen regardless of flags.

**Comment by vitek-karas** [comment]
Proposed design which should include this feature request is discussed here: https://github.com/dotnet/designs/pull/71

There's also ongoing implementation in https://github.com/dotnet/core-setup/pull/6953

**Comment by nguerrera** [comment]
Done by #6953
