### ISSUE TITLE
Need to remove libcurl, libunwind, and libuuid from dependencies in 2.1

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#3814]
As soon as the feature to use the Sockets handler by default gets in and the runtime with the removed libuuid dependency, we need the deps packages to remove libcurl and libuuid for 2.1. By default .net core won't require libcurl or libuuid.

**Comment by Petermarcu** [comment]
@karelz  can you give an eta for when this change can go in?

**Comment by Petermarcu** [comment]
Good call on libuuid. I'll update this issue to track both.

**Comment by karelz** [comment]
It should happen this week (@caesar1995) - it is tracked by https://github.com/dotnet/corefx/issues/27783, so anyone can subscribe to notifications there.

Note: There is a chance that we may need to revert back the default decision and we might need to bring back the dependency post-Preview2 for final release (depends on feedback we will get). I would recommend to track all related PRs, so if it happens, we can easily revert the changes.

**Comment by karelz** [comment]
We need to make sure we keep dependency on MIT Kerberos library. Previously, libcurl had the dependency, now we will depend on it directly - @geoffkizer @stephentoub @wfurt can you please share details about the library name/version/etc. we depend on? Thanks!

**Comment by rakeshsinghranchi** [comment]
https://github.com/dotnet/core-setup/tree/master/src/pkg/packaging/deb and https://github.com/dotnet/core-setup/tree/master/src/pkg/packaging/rpm has installer config files for distro & version specific runtime-deps . @janvorli  and @karelz  can you review those as well ? I would suggest opening an issue like this one for any update to the dependency list going forward. Thanks.

**Comment by kasper3** [comment]
@Petermarcu, now libunwind has also joined this group since https://github.com/dotnet/coreclr/pull/17094 😄

**Comment by rakeshsinghranchi** [comment]
@karelz , @janvorli  - can you confirm if it is okay to remove libcurl and libunwind from runtime-deps packages ? Also, let me know if there is any new package dependency added as the result of these system package dependency removal.

**Comment by karelz** [comment]
PR should be up shortly. It was delayed due to lack of clarity that all depending changes are already in and master->release/2.1 intergation schedule - moving to Post-ZBB.

**Comment by janvorli** [comment]
@rakeshsinghranchi libunwind dependency is not needed anymore.

**Comment by rakeshsinghranchi** [comment]
Fixed by https://github.com/dotnet/core-setup/pull/3966

**Comment by karelz** [comment]
@rakeshsinghranchi did you make the changes also in master branch? I don't see PR linked ...

**Comment by rakeshsinghranchi** [comment]
PR for master: https://github.com/dotnet/core-setup/pull/3967

**Comment by kasper3** [comment]
Looks incomplete. I can still find libunwind, libuuid and libcurl in master:

```sh
core-setup# find . -type f -print0 | xargs -0 grep -l "libcurl"
./src/pkg/packaging/snaps/dotnet-runtime-20/snap/snapcraft.yaml
./src/pkg/packaging/snaps/dotnet-sdk/snap/snapcraft.yaml
./src/pkg/packaging/snaps/dotnet-hosting-20/snap/snapcraft.yaml
./src/pkg/packaging/snaps/dotnet-runtime-11/snap/snapcraft.yaml
./cross/armel/tizen-fetch.sh
./cross/build-rootfs.sh
./tools-local/scripts/docker/fedora.24/Dockerfile
./tools-local/scripts/docker/opensuse.42.1/Dockerfile
./tools-local/scripts/docker/centos.7/Dockerfile

core-setup# find . -type f -print0 | xargs -0 grep -l "libunwind"
./src/pkg/packaging/snaps/dotnet-runtime-20/snap/snapcraft.yaml
./src/pkg/packaging/snaps/dotnet-sdk/snap/snapcraft.yaml
./src/pkg/packaging/snaps/dotnet-hosting-20/snap/snapcraft.yaml
./src/pkg/packaging/snaps/dotnet-runtime-11/snap/snapcraft.yaml
./cross/armel/tizen-fetch.sh
./cross/armel/tizen-build-rootfs.sh
./cross/build-rootfs.sh
./tools-local/scripts/docker/ubuntu.16.10/Dockerfile
./tools-local/scripts/docker/fedora.24/Dockerfile
./tools-local/scripts/docker/ubuntu.16.04/Dockerfile
./tools-local/scripts/docker/opensuse.42.1/Dockerfile
./tools-local/scripts/docker/debian.8/Dockerfile
./tools-local/scripts/docker/ubuntu.14.04/Dockerfile
./tools-local/scripts/docker/centos.7/Dockerfile

core-setup# find . -type f -print0 | xargs -0 grep -l "libuuid"
./cross/armel/tizen-fetch.sh
./tools-local/scripts/docker/ubuntu.16.10/Dockerfile
./tools-local/scripts/docker/fedora.24/Dockerfile
./tools-local/scripts/docker/ubuntu.16.04/Dockerfile
./tools-local/scripts/docker/opensuse.42.1/Dockerfile
./tools-local/scripts/docker/debian.8/Dockerfile
./tools-local/scripts/docker/ubuntu.14.04/Dockerfile
```
