### ISSUE TITLE
Please End the Version Confusion

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#3816]
@laktak commented on [Fri Mar 09 2018](https://github.com/dotnet/core/issues/1328)

I just encountered a bug that appears to be fixed in 2.1 - I only wanted to verify what version of dotnet core I'm using and to check what's the latest version.

My `dotnet --version` says `2.1.4` but then I found your incredibly confusing [release notes](https://github.com/dotnet/core/blob/master/release-notes/download-archive.md):

```
.NET Core 2.1
Release Date 	Description 	Release Notes 	
2018/02/27 	2.0.1-Preview1 with SDK 2.0.1-Preview1 	release notes 	download
.NET Core 2.0
Release Date 	Description 	Release Notes 	
2018/01/09 	2.0.5 with SDK 2.1.4 	release notes 	download
```

So `2.0.1-Preview1` comes after `2.0.5`? And SDK `2.0.1-Preview1` comes after `2.1.4`? So I probably have `2.0.5`?

You said you wanted to simplify this (but that was a few months ago) - so here are some suggestions:

- use semver
- please drop the preview labels
- use even/odd version numbers for release/beta versions
- align core and sdk versions
- make it easier to find out what's installed

---

@svick commented on [Fri Mar 09 2018](https://github.com/dotnet/core/issues/1328#issuecomment-371784747)

Some of this is being changed for upcoming versions of .Net Core, see https://github.com/dotnet/designs/pull/29 and specifically [this document](https://github.com/dotnet/designs/blob/9a84136/proposals/sdk-version-scheme.md).

---

@Petermarcu commented on [Sat Mar 10 2018](https://github.com/dotnet/core/issues/1328#issuecomment-372040172)

We have done the alignment of SDK and Core and done work to enable enumeration of whats installed and in view of the SDK and runtime. @laktak, do you have any feedback based on the planned results [here](https://github.com/dotnet/designs/blob/9a84136/proposals/sdk-version-scheme.md)? If not, we can probably close this issue because this is already and area that is tracked in other issues.

---

@laktak commented on [Sun Mar 11 2018](https://github.com/dotnet/core/issues/1328#issuecomment-372112052)

@Petermarcu the document does not mention it but the preview labels are gone? How are beta's versioned?

Will `dotnet --version` give me both the SDK and Runtime version (or how do I find out the runtime version)?

Do you know when will this be implemented?

---

@Petermarcu commented on [Sun Mar 11 2018](https://github.com/dotnet/core/issues/1328#issuecomment-372127816)

This is all being implemented in the .NET Core 2.1.300 SDK. `dotnet --version` will only give you the sdk version because thats why it was added initially and people use it expecting a single value that is the sdk version. There were discussions about deprecating that switch and providing things like `dotnet --version sdk` so you can request a specific version. I'm going to move this issue to the core-setup repo where @steveharter can comment more on exact details of the changes and when they will be merged in.

**Comment by steveharter** [comment]
As for listing the runtimes and SDKs, the 2.1.0 host (including the current Preview1) adds `--list-runtimes` and `--list-sdks`. This information is also added to `--info` in the latest builds of 2.1.0 preview, in addition to displaying the current SDK as it previously did. So `--info` is a quick way to list all sdks, the current sdk, and all runtimes.

For 2.1.0 we are planning to leave `--version` as-is although in the future we may modify it to change the global SDK version.

**Comment by steveharter** [comment]
cc @KathleenDollard @livarcocc

**Comment by KathleenDollard** [comment]
@laktak 

The page  in your original message has typos. That is unfortunate and I am very glad you asked about it so we can get that fixed. 

When you type `dotnet` there is no explicit tie to a runtime. You may have several on your machine. Thus we are switching to a list of all runtimes. An easy way to get that will be `dotnet --info` but that is not yet working in Preview 1. For now, you can use `dotnet --list-runtimes`.

The problem with semantic versioning is that we are releasing two things that need to be on different cadences. We tried to separately version them, which just confused people. The new plan leaves the first two positions in sync, so you can see what works together. These first two positions will be the .NET Core Runtime major/minor, basically semantic versioning. The .NET Core Runtime will also contain a patch in the third position. 

The .NET Core SDK will use the third position to display both the current release (similar to a minor version) and the patch. Thus a new SDK version number might be 2.1.300. 

You can see more at the document @svick sent.

**Comment by laktak** [comment]
@KathleenDollard thanks, the new versioning looks a lot better. Will this be used for 2.1?

What the document does not mention is if there will still be "preview" versions and how they are versioned.

**Comment by KathleenDollard** [comment]
Yes, this will be used for 2.1. And yes on preview. 

The current preview is [sdk-2.1.300-preview1](https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-preview1)

**Comment by KathleenDollard** [comment]
Oh, and 100 and 200 got lost I the transition :-(

**Comment by livarcocc** [comment]
It seems to me like this has been addressed already and therefore I am going to close this issue. If I misunderstood that, just comment and I can re-activate the issue.
