### ISSUE TITLE
Illegal instruction on ARM Cortex-A5

### ISSUE THREAD

**Issue by lags** [dotnet/core-setup#3819]
I have an embedded system with ARM Cortex-A5 (armhf, 32bit).
I have compile console example with target argument "linux-arm" from windows64bit but when i run in board (armhf 32bit) the result is only:
<code>"Illegal Instruction"</code>

How to solve? Anyone use core with Cortex-A5?

My configuration:

Kernel version (tested): 4.15
Rootfs (tested): Jessie, Stretch, Ubuntu 16.04.

with all require package found at [link](https://docs.microsoft.com/it-it/dotnet/core/linux-prerequisites?tabs=netcore2x)

**Comment by steveharter** [comment]
Issue moved to [dotnet/coreclr #17043](https://github.com/dotnet/coreclr/issues/17043) via [**ZenHub**](https://www.zenhub.com/)
