### ISSUE TITLE
Add the ability to dotnet.exe to download the actual runtime

### ISSUE THREAD

**Issue by redknightlois** [dotnet/core-setup#3837]
Probably it does exist, but I couldn't find it. 

I have been working lately with bleeding edge runtimes because I have been prototyping with hardware intrinsics. I figured out that I could use the moniker with * to force the newer runtimes, but restore is not downloading and installing the proper runtime (which can be done with xcopy).

I propose to have a ```--download-runtime ``` to ```dotnet restore``` so that it will download the appropriate daily build or even something like ```dotnet install-runtime 2.1.0-preview2-26314-02``` to download specific ones.

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/cli #8801](https://github.com/dotnet/cli/issues/8801) via [**ZenHub**](https://www.zenhub.com/)
