### ISSUE TITLE
[release/1.1.0] Microsoft.NETCore.App being published for netcoreapp1.0

### ISSUE THREAD

**Issue by mellinoe** [dotnet/core-setup#385]
It looks like the shared framework is still being published for netcoreapp1.0, even in the release/1.1.0 branch. [This variable here](https://github.com/dotnet/core-setup/blob/release/1.1.0/build_projects/dotnet-host-build/PrepareTargets.cs#L55) seems to control the TFM we use for publishing it. I also see that the deps.json file in the shared framework lists `NETCoreApp,Version=v1.0` as the runtime target, which seems wrong.

Anyone know if there's an exhaustive list of things we need to change to correct this? There's also various other references to `netcoreapp1.0` throughout the repo, but it's not clear which ones we should be changing; for example, `init-tools` seems fine to be publishing for `netcoreapp1.0`, but I don't know about some of the other stuff.

@gkhanna79 , @brthor , @ianhays

**Comment by gkhanna79** [comment]
@weshaggard Would know about how the metapackage was composed and all the places we need to fix. Clearly, this needs to make today to get into Escrow.

CC @leecow

**Comment by gkhanna79** [comment]
@mellinoe I thought this was fixed. If so, can you please close this issue?
