### ISSUE TITLE
Package name / versioning for CentOS packages

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#3850]
@CRCinAU commented on [Thu Feb 01 2018](https://github.com/dotnet/core/issues/1248)

The package names for RPM distributions seem to be a bit whack. As things stand, you can't do point release upgrades on the system without manual intervention - which seems to be somewhat limiting.

For example, the latest runtime package is: dotnet-runtime-2.0.5-2.0.5-1.x86_64

This breaks down to:
* package name = dotnet-runtime-2.0.5
* version = 2.0.5
* revision = 1
* arch = x86_64

This means when you release 2.0.6 for example, it will be a manual upgrade to 2.0.6 as the actual package name will be dotnet-runtime-2.0.6 with version 2.0.6

Unless there is some abuse going on with the Obsoletes / Provides tags in the .spec file used to generate the RPM, I can't see how this fits in with proper practice for packaging on *nix based systems.

Generally, the package name would be set as 'dotnet-runtime', with a *version* of 2.0.5 - or even if it is a dotnet limitation, have 'dotnet-runtime-2.0' - which can then have a version of 2.0.5, 2.0.6, 2.0.7 etc etc delivered seamlessly as a package upgrade via the distro package manager.

---

@crozone commented on [Thu Feb 01 2018](https://github.com/dotnet/core/issues/1248#issuecomment-362454919)

Definitely noticed this. The CentOS package name is `dotnet-host-2.0.5-1.x86_64` which corresponds to this build:

```
Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

From what I understand, different versions of dotnet can be installed simultaneously, and are automatically selected by the sdk and host when it is used to compile a project or run an executable.

~~AFAIK patch versions only include non-breaking security and bug fixes, so it doesn't make sense to me why the actual package name includes the patch version, since it seems to imply that every patch version will get its own separate side-by-side package. This should be entirely unnecessary since patches are meant to be non-breaking anyway. It also makes updating to the latest patch version a manual process, and in turn makes it more difficult to deploying critical security updates.~~

Separate patch names make sense for development, when you want to build against a specific runtime version. Perhaps the solution to this is to instead host a metapackage for `dotnet-host-2.0.x86_64` that follows the version number of the framework host, and references the latest specific package as a dependency.

---

@Petermarcu commented on [Thu Feb 01 2018](https://github.com/dotnet/core/issues/1248#issuecomment-362456854)

@leecow 

I believe we have an issue tracking this somewhere and it is on the list of things @leecow was going to drive getting fixed.

---

@CRCinAU commented on [Tue Feb 20 2018](https://github.com/dotnet/core/issues/1248#issuecomment-367183351)

Just wanted to poke this for comment... The more we deploy this, the more difficult it will be as time goes by to shift things to whatever method is chosen in the long run....

---

@Petermarcu commented on [Tue Feb 20 2018](https://github.com/dotnet/core/issues/1248#issuecomment-367183833)

@leecow you said you had made some progress here on a spec. Is there a link?

---

@CRCinAU commented on [Tue Feb 20 2018](https://github.com/dotnet/core/issues/1248#issuecomment-367184560)

Plus, I've been packaging stuff targeting RHEL/CentOS environments for 10+ years - so happy to provide input - or even contribute - but that assumes knowing what the plan is :)

---

@leecow commented on [Wed Feb 21 2018](https://github.com/dotnet/core/issues/1248#issuecomment-367401142)

Ideas are coming together at https://gist.github.com/leecow/afc1cda5262a702c05978f5a149e2fdc. Will be moving to the designs repo soon. Feel free to comment @CRCinAU !

**Comment by leecow** [comment]
@CRCinAU - We're working to possible of the new package structure enabled for Preview 2 (eg dotnet-runtime2.1-preview.2.deb/rpm). Are you aware of accepted practices around upgrading from pre-release -> stable? IOW, will it be alright for apt-get/dnf update to pull you from a Preview release to Final?

**Comment by CRCinAU** [comment]
@leecow I did look through the documentation. The majority of it I agree with. 

IMHO, preview should auto-upgrade to final releases - however a final release should never be upgraded to a preview of any type.

This means (plucking version numbers at random) that 2.1.0-preview1 will update to 2.1.0-preview2, then 2.1.0, then 2.1.1 etc etc

However, 2.1.1 should never upgrade to 2.2.0-preview or 2.2.0 final.

Of course, this assumes that compatibility is not guaranteed between 2.1.x and 2.2.x. If there is guaranteed compatibility, it would be acceptable to go 2.1.2 -> 2.2.0 but skipping the preview releases.

This would allow automatic deployments in most cases of security updates of point releases, but not end up with preview releases on production systems.

**Comment by crozone** [comment]
IMHO all testing should be in a separate, dedicated testing repository. If you want testing packages, they should be released in a separate stream that needs to be explicitly set up as a separate repository - similar to the `unstable` or `sid` package sources in Debian. Then, the version can always update linearly - you can let `2.1.1` upgrade to `2.2.0-preview` without fear of breaking the world. The stable repository only ever gets release branches so you never have to worry about `2.1.1` upgrading to `2.2.0-preview` (you never get an npm situation).

As for package naming, I'm only experienced with the way naming is handled on Debian, CentOS convention might be different. Packages like `python` use a major version metapackage that points to a new minor version package upon each minor release. This allows for automatic upgrades of minor versions, but keeps the old versions installed in parallel until they're cleaned up with `autoremove`. They can be safely autoremove'd because they're tagged as "automatically installed" when added as a dependency of the metapackage.

Under this system you'd have:

`dotnet2-runtime` - `2.1.1` <- metapackage
 +- `dotnet2.1-runtime` - `2.1.1` <- current package in metapackage dependency ("Requires" in CentOS).
 o- `dotnet2.1-runtime` - `2.0.5` <- old package no longer referenced waiting to be autoremoved.

Apparently `yum autoremove` is a somewhat recent addition. @CRCinAU thoughts?

**Comment by rakeshsinghranchi** [comment]
Related to https://github.com/dotnet/core-setup/issues/3850

**Comment by rakeshsinghranchi** [comment]
cc @leecow 

Reading about debian package semantic versioning , 
The tilde ('~') character is defined to be smaller than an emtpy string. for e.g. 1.0~1 will precede 1.0, and 1.0~rc1-1 can be used prior to the release of 1.0-1 . 

https://books.google.com/books?id=CLC36PmPVtAC&pg=PA217&lpg=PA217&dq=package+version+sorting+algorithms+in+debian&source=bl&ots=oweqE3MNL-&sig=lmQEq--Wo6DHEE54Rz7BGHVpLJI&hl=en&sa=X&ved=0ahUKEwjShsqxm5DaAhUM_WMKHfbOBcsQ6AEINjAC#v=onepage&q=package%20version%20sorting%20algorithms%20in%20debian&f=false

Here is what I would like to propose  to align with rest of the linux packages : 

major.minor.patch~<prereleaselable>-[buildnumber]-[iteration] for e.g.

For e.g.
Preview 2 package version : 2.1.0**~**preview2-3456-1
Preview 3 package version : 2.1.0**~**preview3-4567-1
Release version :                   2.1.0-1 
Post Release :                        2.1.1-1

2.1.0~preview2-3456-1 < 2.1.0~preview3-4567-1 < 2.1.0-1


dpkg --compare-versions 2.1.0~preview2-3456-1 lt 2.1.0~preview3-4567-1 && echo yes
yes
dpkg --compare-versions 2.1.0~preview2-3456-1 lt 2.1.0-1 && echo yes
yes
dpkg --compare-versions 2.1.0~preview3-4567-1 lt 2.1.0-1 && echo yes
yes

**Comment by leecow** [comment]
Sounds reasonable. We should also understand if anything is needed for the `autoremove` behavior described by @crozone 

/cc @omajid

**Comment by omajid** [comment]
I thought we had worked through all the issues here: https://github.com/dotnet/docs/pull/4538. Are there any additional concerns that are not address by that doc?

@rakeshsinghranchi Yes, most package systems have *some* way of marking pre-release packages that are lower in priority than "final" release packages. But they differ from one tool to another. `dpkg` uses `~`, but rpm likes to use a `release` of `0.something`, for example look for `beta` in https://fedoraproject.org/wiki/Package_Versioning_Examples.

**Comment by omajid** [comment]
cc @tmds who wrote up https://docs.microsoft.com/en-us/dotnet/core/build/distribution-packaging

**Comment by rakeshsinghranchi** [comment]
Thanks @omajid for sharing the  details. 

@tannergooding @leecow  - https://docs.microsoft.com/en-us/dotnet/core/build/distribution-packaging is missing the example package name and **versions** for Pre-release, Release and Post-Release packages. 

Also, noticed that proposed package name for dotnet-hostfxr ( currently ) is to rename as dotnet-host-fxr. Please confirm if this rename is expected.

**Comment by rakeshsinghranchi** [comment]
@crozone , Thanks for sharing the details around metapackage. One of the goal for dotnet-runtime packages is to support major upgrade via package managers for e.g. if machine has dotnet-runtime-2.1.0 and dotnet-runtime- 2.1.1 is uploaded to the feed, user via apt-get update should be able to acquire the latest version. What it means is that the package name should be same ( dotnet-runtime-2.1 ) to meet the package upgrade requirement. Do you think it is possible to achieve with suggested metapackage ? 

cc @leecow

**Comment by crozone** [comment]
@rakeshsinghranchi Yes, if I understand correctly, that will work. A major version meta-package would depend on the minor version package. Every minor version update is an update to the major meta-package, and a totally new minor version package. Every patch version is a direct update to the minor version package itself.

Under that metapackage system, incrementing the patch version would update and *replace* the current dotnet package of the same minor version (e.g. 2.1.1 would replace 2.1.0).

However, minor patches behave differently. When the minor version is updated, the meta-package is updated to depend on the new minor version package. This means that minor versions can be installed side-by-side.

Under this system, major versions are never automatically installed, they must be manually installed as a separate package.

Using Debian's `apt-get` as the example:

`apt-get upgrade` updates every installed package to its latest patch version. `apt-get upgrade` never removes or installs new packages. In this way, minor dotnet versions would never be automatically installed using `apt-get upgrade`, they would only be updated to the latest patch version.

`apt-get dist-upgrade` automatically installs dependencies. In this way, minor dotnet versions would be automatically installed side-by-side any previous versions. An `apt-get autoremove` would be required to remove the older "autoinstalled" minor packages.

**Comment by crozone** [comment]
Just to add some urgency to this issue, please see this issue that was created yesterday: https://github.com/dotnet/core-setup/issues/4007

```
$ dotnet --version
Failed to resolve library symbol hostfxr_main_startupinfo, error: /usr/share/dotnet/host/fxr/2.0.5/libhostfxr.so: undefined symbol: hostfxr_main_startupinfo
2.1.4
```

Again, out CentOS servers were given a broken, non-backwards compatible preview package as a minor upgrade. Luckily we caught this before it caused any real mayhem, but it drives home the point that preview packages need to be released on a separate feed.

```
$ rpm -qa | grep dotnet | sort

dotnet-host-2.1.0_preview2_26406_04-1.x86_64
dotnet-hostfxr-2.0.5-2.0.5-1.x86_64
dotnet-runtime-2.0.5-2.0.5-1.x86_64
dotnet-runtime-deps-2.1.0-preview2-26406-04-2.1.0_preview2_26406_04-1.x86_64
dotnet-sdk-2.1.4-2.1.4-1.x86_64
```

Cc: @CRCinAU

**Comment by tmds** [comment]
Adopting https://docs.microsoft.com/en-us/dotnet/core/build/distribution-packaging should fix this issue.

> Just to add some urgency to this issue, please see this issue that was created yesterday: #4007

The host (https://github.com/dotnet/core-setup/issues/4007) is a special case since it shared by all versions. There is a trade-off. On one hand we want preview releases to bring in the preview host so it gets 'tested' on the other hand we don't want it to break anything.

Preview releases for the host aren't described in the packaging doc. We need to figure out the best way to do this.

> https://docs.microsoft.com/en-us/dotnet/core/build/distribution-packaging is missing the example package name and versions for Pre-release, Release and Post-Release packages.

@rakeshsinghranchi you can improve the doc :)

**Comment by rakeshsinghranchi** [comment]
@leecow  will be driving the effort of getting this in release. 
PR : https://github.com/dotnet/core-setup/pull/4020 is taking care of the approach we have settled on for now. This enables the following scenario : 

1. Upgradeable package for all dotnet core installers ( runtime,sdk,aspnetcore).
2. Package managers can be used to pull the latest major.minor packages . for .e.g apt-get update dotnet-runtime-2.1 should update all the runtime packages. It will take care of upgrading from Prerelease to RTM to Post Release versions.

**Comment by leecow** [comment]
Porting to release/2.1 branch - https://github.com/dotnet/core-setup/pull/4104
