### ISSUE TITLE
Enable building native installer for Opensuse in 2.0.x branch

### ISSUE THREAD

**Issue by rakeshsinghranchi** [dotnet/core-setup#3881]
Fixes https://github.com/dotnet/core-setup/issues/3107 .

**Comment by rakeshsinghranchi** [comment]
@leecow , can we accommodate this for the upcoming release ?

**Comment by rakeshsinghranchi** [comment]
Issue manifested here as well : https://github.com/dotnet/dotnet-docker/issues/441

**Comment by leecow** [comment]
Potentially. @wtgodbe @weshaggard - this would be a new package coming from core-setup. What would re-spinning core-setup disrupt?

**Comment by wtgodbe** [comment]
I'm fine with re-spinning Core-Setup if we're OK waiting for a fix for this to go in first. From my end, I can re-spin a core-setup build whenever desired.

**Comment by leecow** [comment]
Thanks. Rakesh is exploring a surgical update for this release, then we'll add it for real in the next. Decision soon.

**Comment by richlander** [comment]
Any update on this given that we have some waiting on it?

**Comment by rakeshsinghranchi** [comment]
I have planned to work on this tomorrow. @leecow , this means building opensuse specific runtime packages and pushing them to it's own opensuse feed.
