### ISSUE TITLE
The Dependency resolver should select the most compatible [Patch] version instead of only the exact 'requested' version

### ISSUE THREAD

**Issue by clguimanMSFT** [dotnet/core-setup#3889]
## Steps to reproduce
Starting with netcore 2.1 runtime the logic to find deps files has changed. The runtime will only search for the deps file in a folder matching with the app's requested framework version. Previously it would just use whatever folder it found.

The changed was done in this PR: https://github.com/dotnet/core-setup/pull/3743/files 

## Expected  behavior

The runtime should still look in the requested version folder, but if it can't find it, it should fallback and search in the <fx major version>.<fx minor version> folder.

This is useful for scenarios where assemblies are loaded at runtime from a previously deployed folder structure (without having control over the app's targeted framework version). With the new behavior, users will need to deploy the new folder structure each time a new patch version is released. My proposal would limit the folder structure release only when a minor framework version is released.

## Environment data

**Comment by steveharter** [comment]
That 2.1 PR mentioned above reverted behavior to the 2.0 behavior which is to use the "requested" version, not the "found" version. So this issue existed in 2.0 as well AFAIK

**Comment by clguimanMSFT** [comment]
I don't know what the intended behavior was in 2.0, but it was enough to just have one folder ("2.0") and this one was always picked up when searching for the deps file. It's possible some other logic that decides what fx version to use might have changed in the 2.1 runtime

**Comment by steveharter** [comment]
Perhaps a 2.0 runtimeconfig.json specified "2.0", and not "2.0.0" for the framework version? I'll check when I have time.

**Comment by clguimanMSFT** [comment]
this is the app's runtimeconfig.json:
`{
  "runtimeOptions": {
    "tfm": "netcoreapp2.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.0.0"
    },
    "configProperties": {
      "System.GC.Server": true
    }
  }
}`

**Comment by steveharter** [comment]
Whether it's the same or not I suppose is not a concern, because we want a "reverse roll forward"-like approach which is different than "requested" vs. "found". Based on the offline discussion today, we'll need to clarify the requirements.

**Comment by karelz** [comment]
The is late design change request, which needs solid design first, adding Post-ZBB

**Comment by steveharter** [comment]
Adding link to [design doc](https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/additional-deps.md) which is still a work-in-progress

**Comment by karelz** [comment]
Fixed in release/2.1 in PR #4094.
