### ISSUE TITLE
sosdocsunit.txt should not have execute permission set

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/core-setup#3890]
_From @jeremymeng on January 17, 2018 0:14_

## Steps to reproduce
```
dotnet new console
dotnet public -r linux-x64 -o pub2
ll pub2/*.txt
```

## Actual behavior
Note that `sosdocsunit.txt` has execution permission which doesn't seem right.

In fact many *.dll and *.so under the published folder all have the `-rwxrw-rw-`.  They can just use `-rw-rw-rw-`

```
-rwxrw-rw- 1 azureuser azureuser 65869 Jul 20 19:16 pub2/sosdocsunix.txt*
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.2/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

_Copied from original issue: dotnet/coreclr#15892_

**Comment by RussKeldorph** [comment]
@janvorli Still 2.1?

**Comment by RussKeldorph** [comment]
_From @janvorli on March 23, 2018 1:43_

It is not critical, we can move it. Actually, it seems it is not a coreclr issue, but either a nuget or cli issue. The file produced in the coreclr doesn't have executable permissions.
```
-rw-r--r-- 1 janvorli janvorli 65814 bře  8 16:31 bin/Product/Linux.x64.Debug/sosdocsunix.txt
```

**Comment by eerhardt** [comment]
See https://github.com/NuGet/NuGet.Client/pull/1346.  NuGet will set this permission when extracting files.

It doesn't pack, nor respect, the permissions of files when packing and extracting .nupkgs.

If this is an issue, please open it in the NuGet/Home repo.

**Comment by peterhuene** [comment]
I created an issue that covers this: https://github.com/NuGet/Home/issues/6778
