### ISSUE TITLE
Multiple ARP entries for 1.0.1

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#390]
## Steps to reproduce
Install builds before and after the 1.0.1 fix for the VC Redist and notice there are two entries in add remove programs for 1.0.1 Runtime

## Expected  behavior
Only one entry

## Actual behavior
Two entries

## Environment data
`dotnet --info` output:

**Comment by gkhanna79** [comment]
Closing per discussion as there is no action required. This was a consequence of generating two different builds, from installer perspective, but with same display string.
