### ISSUE TITLE
[Ubuntu 18.04] Required dependencies/libs for .NET Core Runtime installations

### ISSUE THREAD

**Issue by whoxami** [dotnet/core-setup#3907]
Based on this
https://www.microsoft.com/net/download/linux-package-manager/ubuntu17-10/runtime-current
I am trying to install .NET Core Runtime and SDK. Registering key and feed - fine.

## Steps to reproduce
.NET Core SDK requires dotnet-runtime-2.0.6 - that's ok. But .NET Core Runtime 2.0.6. requires 

````
- libcurl3 but it can not be installed 
```` 
(I install with apt-get install libcurl3)

````
 - libicu57 but it can not be installed 
```` 
(no installation candidate)

````
- dotnet-hostfxr-2.0.6 but will not be installed
Failure to fix problems, damaged packages stopped.
````

Tried
````
apt-get dotnet-hostfxr-2.0.6
```` 

but this requires 
```
dotnet-runtime-deps-2.1.0-preview1-26216-03 (>= 2.1.0-preview1-26216-03)  but will not be installed
````
etc.

How to fix that?

## Environment data
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu Bionic Beaver (development branch)"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by theacid** [comment]
Okay, I found this

````
Ubuntu 18.04

We do not have 18.04 product feeds available yet, there is an option for installing the .NET 2.1 Preview using the Linux binary tar.gz.
````

**More:** https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.0-preview1-download.md

In that case, is it possible to install dotnet runtime? Probably each version causes the same problem on Ubuntu 18.04.

**Comment by eerhardt** [comment]
@rakeshsinghranchi added support for `.NET Core 2.1` in the master branch.

@leecow @Petermarcu - do we want/need to backport Ubuntu 18 support for `.NET Core 2.0.x`?

**Comment by leecow** [comment]
Yes, we'll port to 2.0 once the April Update is done and out of the way.

**Comment by ntellos13** [comment]
A temporary solution ( working for me ) is to use [equivs](https://eric.lubow.org/2010/creating-dummy-packages-on-debian/) to fake dotnet-runtime-deps-2.1.0-preview1-26216-03 package. This means you have to install dependencies one by one, instead of dotnet-runtime-deps do it for you.

**Comment by damageboy** [comment]
Are there any updates on this?
18.04 is coming out in two days, and I've just migrated to it...

Would be great to apt-get dotnet-sdk-2.1.105 over here...

**Comment by theacid** [comment]
@damageboy I think we have to wait some time after official release 18.04

**Comment by atonamy** [comment]
Same issue cannot install dotnet-sdk-2.1.105 on Ubuntu 18.04

>  dotnet-sdk-2.1.105 : Depends: dotnet-runtime-2.0.7 but it is not going to be installed

**Comment by atonamy** [comment]
btw why this [guideline](https://dev.to/carlos487/installing-dotnet-core-in-ubuntu-1804-7lp) is not [here](https://www.microsoft.com/net/learn/get-started/linux/ubuntu18-04)?

**Comment by EdiWang** [comment]
@atonamy the guideline works for me, thanks!

**Comment by gomg** [comment]
**@atonamy** yes this worked, thanks! [https://dev.to/carlos487/installing-dotnet-core-in-ubuntu-1804-7lp](url)

**Comment by dagood** [comment]
This has been fixed in newer versions of .NET Core, closing as a stale issue.
