### ISSUE TITLE
Update TFM for NETCoreApp for 1.2.0

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#392]
Update needs to be done at https://github.com/dotnet/core-setup/blob/05ce78fa94159446cb814e5fac1fa193455e7452/build_projects/dotnet-host-build/PrepareTargets.cs#L55

**Comment by weshaggard** [comment]
@ericstj I believe you have completed this work task but I will leave it to you to close.

**Comment by ericstj** [comment]
Yep. https://github.com/dotnet/core-setup/commit/01157c5c52a726919bbdb8079ee78edc5707b231
