### ISSUE TITLE
 An assembly specified in the application dependencies manifest (VMH.MediaPortal.deps.json) was not found:

### ISSUE THREAD

**Issue by ruant** [dotnet/core-setup#3940]
## Steps to reproduce
Follow steps for Ubuntu 16.04 on https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/runtime-current

## Expected  behavior
Be able to run applications

## Actual behavior
Fails due to to dependencies. Getting A LOT of these.
```
 An assembly specified in the application dependencies manifest (project.deps.json) was not found:
    package: 'Microsoft.AspNetCore.Antiforgery', version: '2.0.2'
    path: 'lib/netstandard2.0/Microsoft.AspNetCore.Antiforgery.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.6.xml
```

## Environment data
```
Linux test-server 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
dotnet --info

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

```
dotnet --list-runtimes
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

```
apt list --installed | grep dotnet

dotnet-host/xenial,now 2.1.0-preview1-26216-03-1 amd64 [installed,automatic]
dotnet-hostfxr-2.0.6/xenial,now 2.0.6-1 amd64 [installed,automatic]
dotnet-runtime-2.0.6/xenial,now 2.0.6-1 amd64 [installed]
dotnet-runtime-deps-2.1.0-preview1-26216-03/xenial,now 2.1.0-preview1-26216-03-1 amd64 [installed,automatic]
```

**Comment by steveharter** [comment]
Is your app targeting 2.1.0-preview or 2.0.x?

If you are targeting 2.0.x then it should work.

If you are targeting 2.1.0-preview then there are likely issues because there is not a 2.1.0-preview version of hostfxr. There's also not a 2.1.0-preview version of dotnet executable, but that should be OK since it hasn't changed much.

**Comment by ruant** [comment]
Not at the computer where I did all this at the moment, but I got it working.
I think what I did was to install `dotnet-hosting-2.0.6` (which in return probably installed `dotnet-hostfxr-2.0.6` and some other 2.0.6 stuff)
I can vaguely remember that when following the installation doc, it did install preview packages.

I'll get back with exactly what I installed when I get home to the computer where I had the issue.

csproj:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
  <!-- New Meta Package has SpaServices in It -->
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.6" />
    <PackageReference Include="NETStandard.Library" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="2.3.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.1" />
  </ItemGroup>    
```

**Comment by ruant** [comment]
Yeah, the one "extra" package I installed was `dotnet-hosting.2.0.6`

```
apt list --installed | grep dotnet
dotnet-host/xenial,now 2.1.0-preview1-26216-03-1 amd64 [installed,automatic]
dotnet-hostfxr-2.0.6/xenial,now 2.0.6-1 amd64 [installed,automatic]
dotnet-hosting-2.0.6/xenial,now 2.0.6-1 amd64 [installed]
dotnet-runtime-2.0.6/xenial,now 2.0.6-1 amd64 [installed]
dotnet-runtime-deps-2.1.0-preview1-26216-03/xenial,now 2.1.0-preview1-26216-03-1 amd64 [installed,automatic]
```

So `dotnet-runtime-2.0.6` depends on `dotnet-host` which points to the preview?

**Comment by steveharter** [comment]
`dotnet-runtime-2.0.6` should not depend on `dotnet-host` preview. 

Can you check your application's `runtimeconfig.json` file and see what version of the framework you are targeting (e.g. 2.0.0 or 2.1.0-preview*).

cc @weshaggard

**Comment by ruant** [comment]
I'll check the `runtimeconfig.json` tonight.

But why does `apt-get install dotnet-runtime-2.0.6` install `dotnet-host` as a dependency?
That has nothing to do with my application...

**Comment by ruant** [comment]
My `runtimeconfig.json` looks like this
```
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.0.0"
    },
    "configProperties": {
      "System.GC.Server": true
    }
  }
}
```

**Comment by steveharter** [comment]
A quick repro on my side showed that installing the runtime does not install the store, which is causing the errors you have. The SDK will install the store, but I assume you don't want to install the SDK.

@natemcmaster what is the process for installing the store (without the SDK)?

**Comment by natemcmaster** [comment]
Try this `apt-get install aspnetcore-store-2.0.6`.

**Comment by steveharter** [comment]
@ruant I am closing this issue. It appears a manual install of the store is currently required if the SDK isn't installed.

**Comment by ruant** [comment]
Yeah.
Maybe it should be mentioned on the howto, or included in the runtime?

**Comment by steveharter** [comment]
@leecow - PTA:L. Whether we should make changes to the doc for installing the runtime for ASP.NET without the SDK

**Comment by leecow** [comment]
Yes, we should document runtime without the SDK. The way to do this in one step would be `apt-get install `dotnet-hosting-2.0.6`. This is a meta-package with dependencies on `dotnetcore-runtime` and `aspnetcore-runtime`. 

Beginning with 2.1 RC1, the meta-package is not needed as the dotnet-core dependency has been moved to aspnetcore-runtime.

**Comment by ccidral** [comment]
I'm having the same problem in a Docker container.  Below is my Dockerfile.

```
FROM microsoft/dotnet:2.0.5-sdk-2.1.4 AS build-env

COPY . /app
WORKDIR /app/src
RUN dotnet restore --ignore-failed-sources
RUN dotnet publish My.Web.Api -c Release -o /app/out

FROM microsoft/aspnetcore:2.0.5-stretch
COPY --from=build-env /app/out /app
WORKDIR /app
ENTRYPOINT ["dotnet", "My.Web.Api.dll"]
```

Setting `PublishWithAspNetCoreTargetManifest` to `false` on the csproj file fixed it, but I guess this is not the appropriate solution.

**Comment by niico100** [comment]
I wasn't using antiforgery and had the same error. I just installed the NuGet package and it fixed it - seems like a good workaround.
