### ISSUE TITLE
An assembly specified in the application dependencies manifest was not found

### ISSUE THREAD

**Issue by divega** [dotnet/core-setup#3965]
_From @livarcocc on March 21, 2018 7:10_

_From @wh1t3cAt1k on March 20, 2018 18:38_

## Steps to reproduce

- Unpack the following project in VS Code: [CoreRestaurants.zip](https://github.com/dotnet/cli/files/1830653/CoreRestaurants.zip)
- `cd` into the directory
- `dotnet build`
- `dotnet ef dbcontext list`

## Expected  behavior

I see the dbcontexts list or a meaningful error.

## Actual behavior

I see an obscure error
```
Error:
  An assembly specified in the application dependencies manifest (CoreRestaurants.deps.json) was not found:
    package: 'CoreRestaurants', version: '1.0.0'
    path: 'CoreRestaurants.dll'
```
## Workaround

It took me 2 days to figure out that the problem might be in access rights, and running the above stuff with `sudo` fixes the issue.

In hindsight it is surprising how I didn't guess it from the outset, but hey, everything is obvious in hindsight.

My point is that the error could be more descriptive so that people spend less time figuring out what went wrong. Perhaps there should be additional explicit checks made by the tool.

*Note*: the same issue with `dotnet ef migrations list`.

## Environment data

I into the `~/Projects/CoreRestaurants` folder.

I run Mac OS 10.13.2 (17C88).

`dotnet --info` output:

```
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.101/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

_Copied from original issue: dotnet/cli#8851_

_Copied from original issue: aspnet/EntityFrameworkCore#11367_

**Comment by divega** [comment]
_From @livarcocc on March 21, 2018 7:10_

It is not clear to me if this is coming from EF trying to load the assemblies in the deps.json or if this is the host trying to load assemblies from the deps.json. If the latter, please, move the issue to core-setup.

Assuming it is the former, I am moving this to EF.

**Comment by divega** [comment]
_From @bricelam on March 21, 2018 22:40_

Similar to #11320. I suspect the error occurs before any EF code gets invoked..

**Comment by divega** [comment]
Moving per @livarcocc's request at https://github.com/dotnet/core-setup/issues/3965#issuecomment-378090171.

**Comment by steveharter** [comment]
@divega I was unable to reproduce the issue locally on my mac. Using your attached repro, the ef commands work fine for my user account without sudo.

That error is likely coming from the host (dotnet) when it is trying to determine where each assembly in the deps.json file is located. Either the actual file (CoreRestaurants.dll) doesn't exist or it doesn't have permission to read that directory\file.

After you do a non-sudo build, does CoreRestaurants.dll exist in your `bin/Debug/netcoreapp*` folder?

Also can you try running `export COREHOST_TRACE=1` and then running the ef commands? This may shed some light on the issue.

**Comment by divega** [comment]
Thanks @steveharter. Please direct your questions to @wh1t3cAt1k, who reported the issue. I only moved the issue from another repo.

**Comment by steveharter** [comment]
Setting this as future milestone for now, as this does not appear to be a critical 2.1 issue

**Comment by codechavez** [comment]
It's happening to me on a window machine. 
I have a C# project which is for an Azure Function. Tried to run 
` Scaffold-DbContext "Server=localhost;Database=Sales;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -Tables Orders,OrderItems,OrderItemOptions`

I get as result
![image](https://user-images.githubusercontent.com/6989623/48565385-4a663a80-e8ad-11e8-85a9-b6af7fdaa371.png)

Using 
C#
EF CORE 2,1
Azure Function
Visual Studio 2017

**Comment by steveharter** [comment]
cc @jeffschwMSFT @vitek-karas

**Comment by jeffschwMSFT** [comment]
@codechavez can you share the COREHOST_TRACE=1 logs and a repro?  Thanks

**Comment by jaxidian** [comment]
It's happening to me, too, on a Windows machine. I'm running VS2017 v15.9.1 with everything else relevant fully up-to-date. I have a brand new Functions project (v2 preview, HTTP Trigger at setup) where I've added EFCore resources.

```
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.4" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.24" />
  </ItemGroup>
```

In my scenario, I'm trying to run `dotnet efcore dbcontext scaffold "connstrgoeshere" Microsoft.EntityFrameworkCore.SqlServer -o Database` and I get that error.

To answer some earlier questions:

> After you do a non-sudo build, does CoreRestaurants.dll exist in your bin/Debug/netcoreapp* folder?

Not exactly. The DLL is in the `bin/Debug/netcoreapp2.1/bin` folder for me.

> can you share the COREHOST_TRACE=1 logs

I'm having trouble figuring out how to pipe these to a file with my somewhat complex command. This isn't getting it done. If somebody can tell me how to do this, I'll gladly share the log:

```
SET COREHOST_TRACE=1
dotnet efcore dbcontext scaffold "connstrgoeshere" Microsoft.EntityFrameworkCore.SqlServer -o Database > corehost.log
SET COREHOST_TRACE=0
```

**Comment by jaxidian** [comment]
Okay, I've figured out how to get one step further but with COREHOST_TRACE=1 set (`2>corehost.log`), it seems to freeze here:

```
--- Begin breadcrumb write
Number of breadcrumb files to write is 122
Breadcrumb thread write callback...Breadcrumbs will be written using a background thread
```

I had it freeze here yesterday as well, not piping it to a file, and it didn't finish even after hours of waiting.

**Comment by vitek-karas** [comment]
I tried to repro this, but no luck so far.
@214169 can you please try to set the `COREHOST_TRACE=1` and run the command again with `2>corehost.log` to redirect the stderr. And then share the log file (if you're comfortable doing so, it will contain local paths on your machine and also probably the DB password, feel free to scrub the DB password in the file)

Anybody who can repro this, can you share the project on which this reproes? And the version of sdk (`dotnet --info`) and the version of EF tools you're using?

Thank you very much for reporting the problem!

**Comment by 214169** [comment]
[EFScaffold.zip](https://github.com/dotnet/core-setup/files/2646604/EFScaffold.zip)

Run following cmd in attached project, you will be able to see error : dotnet ef dbcontext scaffold "Server=.\sqlexpress;Database=xyz;Trusted_Connection=True;"  Microsoft.EntityFrameworkCore.SqlServer -o Model

**Comment by vitek-karas** [comment]
Thanks a lot - reproes - I'll look into it

**Comment by vitek-karas** [comment]
The hang if `COREHOST_TRACE=1` is set is caused by a bug in the Azure functions SDK. See Azure/azure-functions-vs-build-sdk#264.

I'll see if I can somehow workaround it to get to the actual failure.

**Comment by vitek-karas** [comment]
Turns out to be a known issue with Azure Functions: Azure/azure-functions-host#2408
There's possible workaround mentioned in here: aspnet/EntityFrameworkCore#14084

**Comment by vitek-karas** [comment]
The hang when tracing is on has a solution in 3.0 (it's possible to redirect tracing to a file). We're considering to port this change back to 2.2 as well.
