### ISSUE TITLE
Fix Package names for LinuxMint (master)

### ISSUE THREAD

**Issue by rakeshsinghranchi** [dotnet/core-setup#3977]
Linux Mint installers have incorrect version in their package names. 
Actual: dotnet-runtime-deps-2.1.0-preview2-26403-06-linuxmint.7-x64.deb
Expected:dotnet-runtime-deps-2.1.0-preview2-26403-06-linuxmint.**1**7-x64.deb

Actual: dotnet-runtime-deps-2.1.0-preview2-26403-06-linuxmint.8-x64.deb
Expected:dotnet-runtime-deps-2.1.0-preview2-26403-06-linuxmint.**1**8-x64.deb

**Comment by rakeshsinghranchi** [comment]
@leecow , can you confirm if we need this in release/2.1 ? My understanding is that plan is to consume matching Ubuntu feeds for Linux Mint.

**Comment by weshaggard** [comment]
I do expect we will need this in release/2.1 branch.
