### ISSUE TITLE
Microsoft.NETCore.App should be including `tools/x64_arm64/crossgen`

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#3987]
## Steps to reproduce
Inspect the latest package at:
https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.linux-arm.Microsoft.NETCore.App

## Expected  behavior
The package should have both

`tools/crossgen`
`tools/x64_arm64/crossgen`

## Actual behavior
The package only contains `tools/crossgen`

## Notes

See the conversation at: https://github.com/dotnet/cli/pull/8896#issuecomment-378781465

We should change 
https://github.com/dotnet/core-setup/blob/e132169c6bd78f58a488cbd0de412433296f642b/src/pkg/projects/Microsoft.NETCore.App/src/Microsoft.NETCore.App.depproj#L149-L152
to recursively include all the folders under `tools` as well.

/cc @weshaggard @ericstj

**Comment by weshaggard** [comment]
@eerhardt is this something you plan to tackle? Also is it something we want/need for 2.1?

**Comment by eerhardt** [comment]
> is it something we want/need for 2.1?

I think we will need this if we want to crossgen the SDK (and possibly ASP.NET) for arm.  /cc @Petermarcu @livarcocc - is this something we want for 2.1?

> is this something you plan to tackle?

Sorry, but I'm a bit booked now and can't tackle this in the next few weeks.

**Comment by sdmaclea** [comment]
We also need the native libclrjit.so

**Comment by kasper3** [comment]
@sdmaclea, seems like in addition to changing `<FilesToPackage Include="$(_runtimePackagePath)/tools/*.*"> ` to `<FilesToPackage Include="$(_runtimePackagePath)/tools/**/*.*"> `, for ` libclrjit.so`, we would need to change _jitPath as well:

https://github.com/dotnet/core-setup/blob/e132169c6bd78f58a488cbd0de412433296f642b/src/pkg/projects/Microsoft.NETCore.App/src/Microsoft.NETCore.App.depproj#L88
