### ISSUE TITLE
Runtime-deps package dependency should be exhibited by dotnet-runtime package and not dotnet-host

### ISSUE THREAD

**Issue by rakeshsinghranchi** [dotnet/core-setup#4009]
Installing dotnet-sdk-2.1.104 also ends up installing the dotnet-runtime-deps-2.1.0-preview2-26406-04 package.

I don't think you should be publishing preview packages on the same feed as the release packages.

**Comment by rakeshsinghranchi** [comment]
https://github.com/dotnet/core-setup/issues/4007

**Comment by rakeshsinghranchi** [comment]
PR PR : #4020 also takes care of moving runtime-deps dependency from dotnet-host to dotnet-runtime package.

**Comment by Petermarcu** [comment]
I believe specifically this commit is what fixes this bug. https://github.com/dotnet/core-setup/pull/4020/commits/798da4c5daeba5939ef806b0640afeb3d076c620

**Comment by leecow** [comment]
Port to release/2.1 - https://github.com/dotnet/core-setup/pull/4104
