### ISSUE TITLE
Windows builds should always be portable

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/core-setup#4026]
See dotnet/coreclr#17533.

**Comment by kasper3** [comment]
Would it impact https://github.com/dotnet/core-setup/blob/e236a4252fada1f4e83d59e26ded2597026fcee0/src/corehost/Windows/gen-buildsys-win.bat#L19-L22

**Comment by steveharter** [comment]
ptal @weshaggard

**Comment by weshaggard** [comment]
@kasper3 yes we would need to update those if we do this.

@eerhardt @ericstj do you guys think we should do this in core-setup?? If so we probably need to do it for corefx as well.

**Comment by eerhardt** [comment]
My opinion is that all 3 core* repos should be consistent.  We weren't consistent before because `-portable false` in coreclr produced `win7` assets on a Windows 10 machine, and corefx produced `win10` assets on that same machine.

**Comment by steveharter** [comment]
Moving to 2.2 as 2.1 is not likely at this point

**Comment by dagood** [comment]
Closing: in triage, we weren't able to understand the need for this change, and it doesn't seem like it applies to dotnet/runtime after consolidation (because this will naturally be consistent).
