### ISSUE TITLE
Enable Windows subsystem EXEs to avoid console creation

### ISSUE THREAD

**Issue by richlander** [dotnet/core-setup#4034]
We need a first class experience for selecting among a set of hosts (or host characteristics) to use for a given application.

See: https://github.com/dotnet/core/issues/1452

**Comment by dasMulli** [comment]
Likely a duplicate of https://github.com/dotnet/core-setup/issues/196?

**Comment by steveharter** [comment]
Closing as dup.

@richlander can you add to https://github.com/dotnet/core/issues/1452 if you have additional thoughts. Thanks
