### ISSUE TITLE
Package dotnet-runtime-2.0.7-rhel.7-x64.rpm is not signed

### ISSUE THREAD

**Issue by deepumi** [dotnet/core-setup#4039]
## Environment - LINUX / CENT OS

I am getting following error while installing dotnet core runtime on CENT OS.

### "Package dotnet-runtime-2.0.7-rhel.7-x64.rpm is not signed"

1) sudo yum update
2) sudo yum install libunwind libicu
3) sudo yum install dotnet-runtime-2.0.7  (https://www.microsoft.com/net/download/linux-package-manager/centos/runtime-current)

![image](https://user-images.githubusercontent.com/554039/38939669-746b7d0c-42f6-11e8-8527-77907baf0c1b.png)

NOTE : Currently I have a dotnet 1.0.1 version installed on the same machine.

**Comment by leecow** [comment]
Sorry about that - correctly signed package uploaded to the feed and tested good.
