### ISSUE TITLE
Host behavior on roll-forward when app-local assembly + file version match framework should be to prefer the shared framework.

### ISSUE THREAD

**Issue by ericstj** [dotnet/core-setup#4047]
When rolling an application forward to a new shared framework and examining versions of assemblies we need to prefer the framework over the app if all other things are equal.

This will make things consistent with the way that 1.x behaved when you referenced a package of the same exact version (prefer the shared framework) as well as 2.x behavior: where conflict resolution prefers the shared framework when all else is the same.

The shared framework copy of the dll is *better* since its been cross-gen'ed and is shareable between multiple apps running on the shared framework.

**Comment by ahsonkhan** [comment]
Is this blocking release just like https://github.com/dotnet/corefx/issues/29218? Should we tag it as such?

cc @karelz

**Comment by karelz** [comment]
@ahsonkhan sure, the label won't hurt, although I don't think anyone is paying attention to it just yet.

cc @steveharter

**Comment by steveharter** [comment]
This is really a performance issue, should not be "blocking release" IMO. Not to say we shouldn't fix it for 2.1, however.

This requires a tweak to the existing code, as the default behavior is app wins with everything else being equal.

**Comment by karelz** [comment]
BTW: blocking-release != blocking-RC1
It just means must-have for 2.1 RTW

**Comment by steveharter** [comment]
Note that this issue is essentially "rule # 2" in the original design\proposal at https://github.com/dotnet/core-setup/issues/3546:

_2. If a [major] or [minor] roll-forward occurs for a given framework, that framework wins over any other higher layer(s)_

but was not implemented as it was deemed not necessary at the time because we were implementing rule # 3 which uses the assembly\file version metadata in the deps.json.

**Comment by ericstj** [comment]
No this is not that rule.  I'm not saying that the framework always wins.  I'm further specifying the versioning rule such that it matches the behavior of the in-build conflict resolution.  Simply: If the versions are equal on a roll-forward, framework should win.

**Comment by steveharter** [comment]
The matrix of metadata vs. non-metadata, assuming minor\major roll-forward:
a) No metadata on either side. Currently app\higher layer wins
b) Metadata on one side. Currently the side with metadata wins
c) Metadata on both sides. Currently the app\higher layer wins in a tie (assemblyVersion and fileVersion are the same)

For (c) we favor the lower layer in a tie.

For (a) do we want to do also favor a lower layer in a tie? Note that this will be unlikely as we should have metadata for 2.1+

**Comment by Petermarcu** [comment]
Is this critical for RC?

**Comment by steveharter** [comment]
>> Is this critical for RC

No, I don't believe so since it appears Eric's other change (https://github.com/dotnet/corefx/issues/29218) was merged into 2.1.

**Comment by steveharter** [comment]
Reopen to merge into 2.1 (pending shiproom approval)
