### ISSUE TITLE
Remove duplicate private CRT 

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#4052]
@jkotas said: 

I think there is actually opportunity to remove some unnecessary fat from the netcoreapp package because we have an app-local copy of CRT as well. We only need one of app-local copy of CRT and statically linked CRT. We do not need both.

pointing to ucrtbase.dll in the netcoreapp shared framework.

**Comment by Petermarcu** [comment]
No, I don't think so. I think its product and when the file disappears, it should be gone from the installers too.

**Comment by steveharter** [comment]
What does "app-local copy" refer to?

Currently netcoreapp includes ucrtbase.dll, which is also installed into a standalone app.

However at run-time ucrtbase.dll is actually loaded from Windows\System32 (on Windows 10 anyway).

Misc links:
https://github.com/dotnet/corefx/issues/12858
https://msdn.microsoft.com/en-us/library/abx4dbyh.aspx

**Comment by jkotas** [comment]
Ignore this. coreclr.dll is not statically linking the CRT in Release build. I have looked at debug build by accident that is setup differently.

For reference, the logic responsible for that is here: https://github.com/dotnet/coreclr/blob/745f362a946d9831b46f54589cf2d6d64d908604/CMakeLists.txt#L385
