### ISSUE TITLE
Taskbar progress in Windows installer doesn't indicate completion well

### ISSUE THREAD

**Issue by svick** [dotnet/core-setup#4058]
I think that the most important function of the progress indicator for an operation in the Windows taskbar is finding out whether the operation is still in progress or whether it's completed. The current implementation in the .Net Core SDK installer doesn't do that well. Specifically, it's impossible to distinguish between "99.9 % done" and "actually done" cases.

## Steps to reproduce

Run the Windows installer for the .Net Core SDK and observe the progress indicator in the taskbar.

## Expected  behavior

The progress indicator clearly shows when the installation is complete.

## Actual behavior

The "99.9 % done" case is indistinguishable from the "actually done" case. (The installer window images are just for illustration, it's the taskbar images that are important.)

99.9 % done:

![](https://user-images.githubusercontent.com/287848/39085097-61f65838-457e-11e8-91d6-0df3311045fd.png)
![](https://user-images.githubusercontent.com/287848/39085085-3d831950-457e-11e8-9de9-4eed320b3521.png)

actually done:

![](https://user-images.githubusercontent.com/287848/39085145-c3883242-457e-11e8-8424-497afe35f0bc.png)
![](https://user-images.githubusercontent.com/287848/39085133-b09ea396-457e-11e8-89e9-faf51d2b9aa9.png)

**Comment by rakeshsinghranchi** [comment]
@livarcocc , @wli3 
 Issue reported is related to SDK installer. However, it looks like underlying issue with Burn chainer.

**Comment by robmen** [comment]
What suggestions do you have for improving the progress bar in this case? 99% is going to look a lot like 100%.

**Comment by svick** [comment]
@robmen I believe some other progress indicators (like the download progress indicator in Firefox) just disable the progress indicator after reaching 100 %. I think that approach could work here.

**Comment by robmen** [comment]
@svick so are you saying the task button should go back to normal when the install is successful and go red if there is an error?

**Comment by svick** [comment]
@robmen Yes, exactly.

**Comment by dagood** [comment]
Closing: this isn't something that it looks like we have control over when building an installer. This looks like a feature request for the burn bundle engine.
