### ISSUE TITLE
Build failures in 'official/core-setup/release/1.1.0/' - '20180424.08'

### ISSUE THREAD

**Issue by jcagme** [dotnet/core-setup#4068]
@dotnet-mc-bot commented on [Tue Apr 24 2018](https://github.com/dotnet/core-eng/issues/3359)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1625890
  - **Agent:** DDVSOLINUXAGE013
  - **Error log:** [39;49mBuild failed: System.AggregateException: One or more errors occurred. (The type initializer for 'Crypto' threw an exception.) ---> System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1625891
  - **Agent:** DDVSOLINUXAGE016
  - **Error log:** [39;49mBuild failed: System.AggregateException: One or more errors occurred. (The type initializer for 'Crypto' threw an exception.) ---> System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1625893
  - **Agent:** DDVSOLINUXAGE025
  - **Error log:** [39;49mBuild failed: System.AggregateException: One or more errors occurred. (The type initializer for 'Crypto' threw an exception.) ---> System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1625900
  - **Agent:** DDVSOLINUXAGE029
  - **Error log:** dpkg-shlibdeps: warning: debian/dotnet-hostfxr-1.1.9-servicing-001724-00/usr/share/dotnet/host/fxr/1.1.9-servicing-001724-00/libhostfxr.so contains an unresolvable reference to symbol dlerror: it's probably a plugin...

@jcagme, @markwilkie

**Comment by steveharter** [comment]
@weshaggard @rakeshsinghranchi @ianhays any thoughts on these 1.1 issues? Some Crypto (OpenSsl?) issues as well as a hostfxr issue.

**Comment by weshaggard** [comment]
cc @wtgodbe @bartonjs 

They don't look familiar to me I have to wonder if some image was update which broken openssl.

**Comment by ianhays** [comment]
These breaks are familiar. Note that they're only present on the new distros that are in the process of being added for rel/1.1.

I believe the issue with the ssl version is that the tools restoration for the packaging/publishing step is getting an older version of its crypto binaries.

The problem I'm having right now is that I have no way of reproing the issue locally, because to do so requires access to the azure secrets used in the build pipeline. That also prevents me from kicking off private builds, so any attempted fixes have to go directly into the rel/1.1.0 official branch.

**Comment by weshaggard** [comment]
@ianhays work with @wtgodbe to spin private builds if you need to.

**Comment by ianhays** [comment]
@jcagme I submitted that build since the results from the previous pipebuild expired.

These will consistently fail until the root cause is resolved, so there's no need to keep an eye on them.
