### ISSUE TITLE
Remove all but latest TFM from Microsoft.NETCore.App dependencies

### ISSUE THREAD

**Issue by weshaggard** [dotnet/core-setup#4071]
After https://github.com/dotnet/core-setup/pull/4060 moved to netcoreapp2.2 we should make it explicit that we no longer support the older TFMs with the latest package so we should remove netcoreapp1.0/1.1/2.0 dependencies from the package.

**Comment by ericstj** [comment]
We missed https://github.com/dotnet/core-setup/blob/7362f3bc1dca0ad537871f4f33e4bfce66c9ed19/src/pkg/projects/Microsoft.NETCore.App/Microsoft.NETCore.App.pkgproj#L33-L37

**Comment by weshaggard** [comment]
I agree we should remove that as well. Out of curiosity how did you find this? Did it cause some issue somewhere?

**Comment by ericstj** [comment]
@livarcocc was updating the SDK and compile was failing.  They hadn’t retargeted.

**Comment by weshaggard** [comment]
Fixed the last issue with #4167
