### ISSUE TITLE
RuntimeEnvironment.RuntimeArchitecture on ARM64 says "x64" instead of "arm64"

### ISSUE THREAD

**Issue by steveharter** [dotnet/core-setup#4081]
The current code assumes if running in 64-bit environment, then it is "x64".

See https://github.com/dotnet/cli/issues/9118

At a minimum this displays incorrect information via `dotnet --info`

**Comment by wli3** [comment]
https://github.com/dotnet/core-setup/issues/4083

**Comment by Petermarcu** [comment]
We need to get this fixed. Its important that information and data coming from these machines is accurate. It will greatly assist long term diagnosability.

**Comment by Petermarcu** [comment]
https://github.com/dotnet/core-setup/blob/9dff3ce12574699e6d4d31722047f775d92d05fd/src/managed/Microsoft.DotNet.PlatformAbstractions/RuntimeEnvironment.cs#L26

**Comment by Petermarcu** [comment]
This is fixed in master and 2.1 now.
