### ISSUE TITLE
Port changes for upgradable Linux packages to release/2.1

### ISSUE THREAD

**Issue by leecow** [dotnet/core-setup#4097]
Changes for the creation of upgradable Linux installations have been in Master and verified for a few weeks. ASP and CLI are aware of the changes coming and have corresponding issues open to re-target their respective dependencies on the new runtime package identity. 

- [x] Port https://github.com/dotnet/core-setup/pull/4020/commits/60cd2843d741f8674a6064cbc2b1cfe257fcf211 to release/2.1
- [x] ASP makes change to target the runtime-2.1 package (rather than 2.1.0) and drop the patch version from their package identity.
- [x] CLI makes the same changes once ASP submits PR to insert the updated ASP packages.

cc @rakeshsinghranchi, @livarcocc @JunTaoLuo

**Comment by rakeshsinghranchi** [comment]
Runtime related port work is taken care by https://github.com/dotnet/core-setup/pull/4104 .

@leecow , @JunTaoLuo , @livarcocc  - Is SDK and ASPNET related work already available in their respective master branch ? 

@livarcocc , @JunTaoLuo  - PTAL at runtime package name and version changes for debs and RPMs.

**Comment by Petermarcu** [comment]
This is merged into core-setup https://github.com/dotnet/core-setup/pull/4104

**Comment by JunTaoLuo** [comment]
Working on the second piece in https://github.com/aspnet/Universe/issues/1116. PR is out https://github.com/aspnet/Universe/pull/1140.

**Comment by JunTaoLuo** [comment]
FYI the aspnet changes are in.

**Comment by Petermarcu** [comment]
This can be closed now.
