### ISSUE TITLE
Move to stable versions in the host

### ISSUE THREAD

**Issue by schellap** [dotnet/core-setup#41]
As we RTM, make sure the versioning of host conforms to the runtime -- coreclr, corefx versioning schemes.

**Comment by gkhanna79** [comment]
Coordinating with @ericstj

**Comment by schellap** [comment]
WIP PR #128

**Comment by gkhanna79** [comment]
@schellap Please coordinate with @ericstj on this as it is expected to happen today or tomorrow.

**Comment by gkhanna79** [comment]
@schellap @ericstj Is this on track as part of @ericstj change for stable versions?

**Comment by gkhanna79** [comment]
Is this fixed?

**Comment by schellap** [comment]
Closing...

**Comment by schellap** [comment]
Fixed by above #128
