### ISSUE TITLE
Host tests create "x64" directory at root of repo

### ISSUE THREAD

**Issue by steveharter** [dotnet/core-setup#4100]
## Steps to reproduce
Build core-setup

## Expected  behavior
Clean \bin directory

## Actual behavior
A \bin directory but the unexpected x64 directory

**Comment by steveharter** [comment]
Apparently this directory is created by the initial CMAKE command

**Comment by dagood** [comment]
I no longer see this, in particular not in the consolidated dotnet/runtime repo. Closing as resolved.
