### ISSUE TITLE
Stabilize 2.1 versioning and branding for release

### ISSUE THREAD

**Issue by leecow** [dotnet/core-setup#4113]
Placeholder for this work to be done closer to final release time. 

- installer UI
- built assets

cc @Petermarcu @weshaggard

**Comment by weshaggard** [comment]
@leecow do you know what all needs to be updated? Do we just need to empty out https://github.com/dotnet/core-setup/blob/master/BranchInfo.props#L15? If so I'd like to do this based on our stable package build parameter so we don't need to make a commit to switch these.

**Comment by leecow** [comment]
No, I don't know the details of how this is done. cc @rakeshsinghranchi in case he's listening.

**Comment by rakeshsinghranchi** [comment]
Yes, just empty out the ReleaseBrandSuffix property for installer UI.

**Comment by weshaggard** [comment]
Support fixed with https://github.com/dotnet/core-setup/pull/4145.
