### ISSUE TITLE
Typo in "descriptions.json" file

### ISSUE THREAD

**Issue by ticoopso** [dotnet/core-setup#4139]
In the "core-setup/src/pkg/projects/descriptions.json" file, there is a typo in the description for "Microsoft.NETCore.App":

"A set of .NET API's that are included in the default .NET Core application model."

The apostrophe in "API's" is not required - it should be "APIs".

**Comment by danmosemsft** [comment]
Do you want to offer a PR?

**Comment by dagood** [comment]
Fixed by @bokobza with https://github.com/dotnet/core-setup/pull/4971. Thanks!
