### ISSUE TITLE
A fatal error occurred, the required library hostfxr.dll could not be found at C:\Program Files\dotnet\

### ISSUE THREAD

**Issue by karelz** [dotnet/core-setup#4143]
_From @HowardEdidin on May 11, 2018 14:43_

D:\>dotnet new -i Microsoft.Azure.IoT.Edge.Function
A fatal error occurred, the required library hostfxr.dll could not be found at C:\Program Files\dotnet\

D:\>dotnet new aziotedgefunction -n FilterFunction -r <your container registry address>/filterfunction
The system cannot find the file specified.

D:\>dotnet new aziotedgefunction -n FilterFunction -r hl7fhir.azurecr.io/filterfunction
A fatal error occurred, the required library hostfxr.dll could not be found at C:\Program Files\dotnet\

D:\>A

_Copied from original issue: dotnet/corefx#29659_

**Comment by karelz** [comment]
@HowardEdidin it looks like incomplete installation. Are you able to create other project types? Did you try it on clean machine, with just .NET Core freshly installed?
Which version of .NET Core do you use?

**Comment by karelz** [comment]
That is SDK version: [2.1.200](https://github.com/dotnet/core/blob/master/release-notes/2.0/2.1.200-sdk.md)
Do you get the same behavior on clean VM? Did you try to create console app project?

**Comment by HowardEdidin** [comment]
I have been trying to get https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-deploy-function to work

**Comment by steveharter** [comment]
Try setting `COREHOST_TRACE=1` and re-try your steps to see where it is finding the runtime

**Comment by vitek-karas** [comment]
We need more information to be able to diagnose this issue. Closing for now. If it's still a problem please reopen with additional information.
