### ISSUE TITLE
Ubuntu 16.04 download link for 2.1 does not work

### ISSUE THREAD

**Issue by gregolsky** [dotnet/core-setup#4158]
Download link does not work for some reason:
![image](https://user-images.githubusercontent.com/1541805/40347029-0a4ae368-5d9f-11e8-80ed-aa49be7fc50b.png)

https://dotnetcli.blob.core.windows.net/dotnet/Runtime/release/2.1/dotnet-runtime-latest-ubuntu.16.04-x64.deb

```xml
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:ee12719f-c01e-007a-739a-f1c286000000 Time:2018-05-22T07:00:47.9956787Z
</Message>
</Error>
```

Similarly for 14.04.

**Comment by steveharter** [comment]
cc @weshaggard

**Comment by weshaggard** [comment]
Thanks for reporting @gregolsky we no longer produce a 16.04 specific package. Instead we just use the default https://dotnetcli.blob.core.windows.net/dotnet/Runtime/release/2.1/dotnet-runtime-latest-x64.deb.

I will try to find some time to update the readme.

**Comment by gregolsky** [comment]
Yeah, that's what I thought and we used just that. Just wanted to let you
know about the link.

wt., 22 maj 2018, 19:36 użytkownik Wes Haggard <notifications@github.com>
napisał:

**Comment by weshaggard** [comment]
@wtgodbe please take a look.
