### ISSUE TITLE
[1.1] Enable Debian9 build

### ISSUE THREAD

**Issue by ianhays** [dotnet/core-setup#4173]
Much of the plumbing has already been added to enable a Debian9 build of core-setup in https://github.com/dotnet/core-setup/pull/4043, but it was removed in https://github.com/dotnet/core-setup/pull/4132 and https://github.com/dotnet/core-setup/pull/4170 because of an issue in the package publishing step that I didn't get a chance to resolve.

We should re-enable Debian9 builds and resolve any issues.

**Comment by eerhardt** [comment]
Working on this now.

**Comment by eerhardt** [comment]
This has been taken care of with #4351
