### ISSUE TITLE
Publishing build failures in 'official/core-setup/release/1.1.0/' - '20180530.01'

### ISSUE THREAD

**Issue by jcagme** [dotnet/core-setup#4175]
@dotnet-mc-bot commented on [Tue May 29 2018](https://github.com/dotnet/core-eng/issues/3555)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1729338
  - **Agent:** DDVSOLINUXAGE004
  - **Error log:** error: Response status code does not indicate success: 409 (The package could not be uploaded. The package "runtime.win7-x64.Microsoft.NETCore.DotNetHostPolicy 1.1.9-servicing-001739-00" already exists. Overwriting existing packages is forbidden according to the package retention settings for this feed.).

@mmitche, @weshaggard

**Comment by weshaggard** [comment]
@ianhays I assume you are the one spinning these builds?

**Comment by ianhays** [comment]
Sure am. I'm working on getting them fixed now.

**Comment by ianhays** [comment]
Done. The latest build successfully completed.
