### ISSUE TITLE
Installing dotnet-sdk-2.1 installs dotnet-host 2.1.0-rc1-1

### ISSUE THREAD

**Issue by bording** [dotnet/core-setup#4177]
When installing the .NET Core 2.1 SDK on Ubuntu, it's pulling in the RC `dotnet-host` package instead of the released version.

## Steps to reproduce
sudo apt install dotnet-sdk-2.1

## Expected  behavior
`dotnet-host` 2.1.0-1 is installed

## Actual behavior
`dotnet-host` 2.1.0-rc1-1 is installed

## Environment data

Ubuntu 18.04 WSL

`apt-cache madison dotnet-host` output:
```
dotnet-host | 2.1.0-rc1-1 | https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
dotnet-host |    2.1.0-1 | https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
dotnet-host |    2.0.7-1 | https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
```

**Comment by steveharter** [comment]
cc @leecow

**Comment by leecow** [comment]
https://github.com/dotnet/core/issues/1620

**Comment by steveharter** [comment]
Closing this as duplicate
