### ISSUE TITLE
aspnetcore module is not installed by 2.1 sdk installer

### ISSUE THREAD

**Issue by usego** [dotnet/core-setup#4181]
Sorry if I'm missing something obvious, but I'm trying to figure out how to install aspnetcore module to IIS with 2.1 sdk installer. Download page says Hosting Bundle Installer is included into SDK installation, but I still do not see module in the list.

**Comment by steveharter** [comment]
ptal @leecow @natemcmaster

**Comment by natemcmaster** [comment]
@usego I'm assuming you are looking at this download page, right? https://www.microsoft.com/net/download/windows 

<img src="https://user-images.githubusercontent.com/2696087/40940828-db3275d2-67fd-11e8-808f-30abaa6e5035.png" width="400" />

The ASP.NET Core Module is not included with SDK installers. We should have the website team update this (cc @shirhatti @leecow @rowanmiller).

In the meantime, you can get the Hosting Bundle installer here: https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.0-download.md#server-hosting

**Comment by rowanmiller** [comment]
We're working on a further refinement of this page to improve some of the confusion with the hosting bundle. In the meantime I will make a change to remove the "included in..." message for the hosting bundle.

**Comment by usego** [comment]
>@usego I'm assuming you are looking at this download page, right? https://www.microsoft.com/net/download/windows

@natemcmaster right, this one page

**Comment by dagood** [comment]
Closing: looks like this was solved a while ago.
