### ISSUE TITLE
Feature request: provide way to acquire latest, stable 2.1 Windows/macOS bits

### ISSUE THREAD

**Issue by leecow** [dotnet/core-setup#4187]
@natemcmaster commented on [Fri Jun 01 2018](https://github.com/dotnet/core/issues/1649)

**Is your feature request related to a problem? Please describe.**
Starting in .NET Core 2.1, the .deb/.rpm acquisition experience changed. Linux users can now reference `dotnet-sdk-2.1` and `dotnet-runtime-2.1`. This makes it easy to upgrade by just running `apt upgrade`. There is no way to get the equivalent behavior on Windows and macOS

**Describe the solution you'd like**
I'd like a way to be able to get the latest, stable `2.1` runtime and SDK. I'm not concerned about floating the patch version.

**Describe alternatives you've considered**
* Update `dotnet-install.ps1` to support a "2.1" stable channel.
* Use a stable link that I can curl/wget from such as `https://aka.ms/dotnet/2.1/dotnet-runtime-2.1-win-x64.{exe,zip}`

**Additional context**
https://github.com/travis-ci/travis-build/pull/1397#issuecomment-393988234

---

@leecow commented on [Fri Jun 01 2018](https://github.com/dotnet/core/issues/1649#issuecomment-394021475)

Moving to core-setup

**Comment by steveharter** [comment]
ptal @leecow @rakeshsinghranchi

**Comment by rakeshsinghranchi** [comment]
@johnbeisner  , PTAL .

**Comment by johnbeisner** [comment]
@rakeshsinghranchi 
The dotnet-install.ps1/sh scripts support an "LTS" and "Current" channels as well as a "2.1" channel. The "Current" channel and the "2.1" channel  both download "2.1.300"

./dotnet-install.ps1 -channel 2.1
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.300/dotnet-sdk-2.1.300-win-x64.zip

./dotnet-install.ps1 -channel Current
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.300/dotnet-sdk-2.1.300-win-x64.zip

**Comment by rakeshsinghranchi** [comment]
Thanks @johnbeisner .  Does dotnet-install support macOS ?

**Comment by johnbeisner** [comment]
@rakeshsinghranchi
dotnet-install.sh supports macOS

**Comment by rakeshsinghranchi** [comment]
@johnbeisner looks like dotnet-install acquires SDK . Does it have capability to install just the runtime ?

**Comment by ErikSchierboom** [comment]
It appears there is some issue with using `dotnet-install.sh` to install the 2.1 SDK on MacOS:

Running `./dotnet-install.sh --version 2.1` outputs:

<pre>
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1/dotnet-sdk-2.1-osx-x64.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1/dotnet-sdk-2.1-osx-x64.tar.gz
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1/dotnet-dev-osx-x64.2.1.tar.gz
curl: (22) The requested URL returned error: 404
</pre>

Specifying the channel using `./dotnet-install.sh --version 2.1 --channel 2.1` also doesn't help. It appears that the MacOS files are not there. Any idea if this can be fixed?

**Comment by natemcmaster** [comment]
@ErikSchierboom try just `./dotnet-install.sh --channel 2.1`.

@johnbeisner I've seen lots of users trying to combine `--version` and `--channel`. Maybe we should update the script to issue a warning that these parameters can't be used together. Adding `--version` means the value of `--channel` is completely ignored.

**Comment by ErikSchierboom** [comment]
@natemcmaster It now works, but `./dotnet-install.sh --channel 2.1` resolves to exactly the same link as `./dotnet-install.sh --version 2.1.300` as far as I can tell. Apparently it was an Azure account issue: https://twitter.com/lbcoward/status/1008727610430328832

**Comment by natemcmaster** [comment]
That's expected. The latest stable 2.1 SDK release is 2.1.300.

**Comment by dagood** [comment]
Closing: it looks to me like the request/question is fulfilled by `dotnet-install.sh/ps1`.

In general, any issues with `dotnet-install` should be filed in https://github.com/dotnet/cli. There might be something to do in core-setup to support downloading a runtime *without* an SDK, but it doesn't seem like there's a specific need for that right now. (If so, I think it'd make sense to drive that by requesting the feature in the `dotnet-install` script in the CLI repo.)
