### ISSUE TITLE
Port framework-dependent apphost fix to 2.1.x

### ISSUE THREAD

**Issue by steveharter** [dotnet/core-setup#4192]
Port commit https://github.com/dotnet/core-setup/commit/6ff3b8f91e2b5fb34e834bb64f421fdb50d6d72d to 2.1.x.

This is important once the SDK supports creating a framework-dependent apphost as it is likely users will encounter the issue (if they run the app out of the same folder as the exe). Currently the framework-dependent apphost (added in 2.1.0) is only used by global tools which doesn't encounter the bug.

See original issue https://github.com/dotnet/core-setup/issues/4169

**Comment by nguerrera** [comment]
Was this ported to 2.1.x?

**Comment by nguerrera** [comment]
cc @peterhuene

**Comment by steveharter** [comment]
I'll create the PR today

**Comment by danmosemsft** [comment]
@steveharter can this be closed now? If not we will need shiproom info for 2.1.

**Comment by steveharter** [comment]
Closing. The fix is not necessary.

**Comment by steveharter** [comment]
This is necessary for 2.1.x.

@danmosemsft will the next round of 2.1.x fixes make it into 2.2 automatically, or is an explicit port required? Thanks

**Comment by danmosemsft** [comment]
@steveharter all 2.1.x fixes are automatically ported to 2.2

**Comment by livarcocc** [comment]
@peterhuene for awareness.

I am confused. From the title of this bug, it seems like we have changes from 2.2 that we wanted ported back to 2.1, not the other way around.

Also, I believe we are missing a change in 2.1 that would allow framework dependent exes to work for 2.1. I would like that bug to be considered for 2.1 still. Is this the bug to track that or should we file a new one?

**Comment by steveharter** [comment]
> I am confused. From the title of this bug, it seems like we have changes from 2.2 that we wanted ported back to 2.1, not the other way around.

We are porting a fix from master \ 3.0 to 2.1.x. That 2.1.x will then be automatically ported to 2.2.

**Comment by steveharter** [comment]
| Also, I believe we are missing a change in 2.1 that would allow framework dependent exes to work for 2.1. I would like that bug to be considered for 2.1 still. Is this the bug to track that or should we file a new one?

From the host side, this is the only issue preventing a framework dependent exe from working in all cases.
