### ISSUE TITLE
The core_setup README.md has broken "version" links

### ISSUE THREAD

**Issue by steveharter** [dotnet/core-setup#4200]
The 2.x “version” links are broken on https://github.com/dotnet/core-setup#daily-builds

For example, for Windows (x64) when I click on the “version” for the winx64 it tries to go to https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/latest.sharedfx.win.x64.version which is broke \ missing blob.

Expect: it used to go to the build information I believe, or at least provide more information on the version (e.g. hash).

Did the blob names change or the .version file stop being generated? I don't see any recent README.md changes that that would affect this.

**Comment by steveharter** [comment]
cc @weshaggard

**Comment by weshaggard** [comment]
@wtgodbe could you please make a pass over the readme file and update the links to where things live in the storage accounts?
