### ISSUE TITLE
Installing of dotnet-hosting remove .Net Core SDK

### ISSUE THREAD

**Issue by alfeg** [dotnet/core-setup#4217]
I have a problem. As soon as I install `dotnet-hosting-2.1.0-win.exe` - I loose access to .Net Core SDK. Visual Studio stop opening .net core projects untill I uninstall all `dotnet core` related applicationsa and reinstall SDK.

Right now I cannot host asp.net core application in IIS and develop it on single machine

## Steps to reproduce

My steps:

1. Install SDK only. No asp.net core iis module available
```
PS C:\WINDOWS\system32> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

2. Install  `dotnet-hosting-2.1.0-win.exe`  
```
PS C:\WINDOWS\system32> dotnet --info

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

## Expected  behavior
I can install SDK and `dotnet-hosting-2.1.0`
I can host asp.net core app on same machine I develop on.

## Actual behavior
Installing of `dotnet-hosting-2.1.0` remove SDK functionality

## Environment data
```
PS C:\WINDOWS\system32> [System.Environment]::OSVersion.Version.ToString()
10.0.17134.0
```

**Comment by jeffschwMSFT** [comment]
@leecow

**Comment by leecow** [comment]
@joeloff @livarcocc

**Comment by joeloff** [comment]
It shouldn't remove the SDK, but it would remove a previous runtime that the hosting bundle installed. The hosting bundle was marked as upgrade for 2.1 instead of SxS, so when it upgrades, it will uninstall the previous runtime it shipped

**Comment by alfeg** [comment]
Used another PC. Cleaned all `Core` related apps.
Installed `dotnet-sdk-2.1.300-win-x64.exe` and then  `dotnet-hosting-2.1.0-win.exe`. Everything seems to be OK =( I don't need .net core on my home pc, I need it on my PC at work.
But I have different windows build here 
```
 OS Name:     Windows
 OS Version:  10.0.17672
```

Tried to cleanup temp folder on Work PC. Still same problem. SDK seems to be inplace. Physically there is sdk folder in program files with all needed files.

Attaching installation logs
[dotnet.core.installation.logs.zip](https://github.com/dotnet/core-setup/files/2091251/dotnet.core.installation.logs.zip)

**Comment by alfeg** [comment]
Ok.
I figured this out.

```
c:\Program Files\dotnet> where dotnet.exe
c:\Program Files\dotnet\dotnet.exe
C:\Program Files (x86)\dotnet\dotnet.exe
```

After installing `dotnet-hosting-2.1.0-win.exe` I have two dotnet installations

Also there is seems to be some kind of bug when call `dotnet.exe --info`
```
.NET Core SDKs installed:
  2.1.300 [c:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
```
Point to same SDK but different casing.

**Comment by alfeg** [comment]
@jeffschwMSFT I will close ticket.

**Comment by anandmurali** [comment]
In my case, both the .NET core run time for (x64) and (x84) were installed. After uninstalling Microsoft .NET Core Runtime x.x.x (x84) through control panel, everything started working again for me.
