### ISSUE TITLE
Need to remove more "ToLowerInvariant" workarounds in DependencyModel

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#423]
There are some additional ToLowerInvariant() workarounds in the DependencyModel that we need to remove:

https://github.com/dotnet/core-setup/blob/release/1.1.0/src/Microsoft.Extensions.DependencyModel/Resolution/ResolverUtils.cs#L16-L17

https://github.com/dotnet/core-setup/blob/release/1.1.0/src/Microsoft.Extensions.DependencyModel/Resolution/PackageCacheCompilationAssemblyResolver.cs#L55

Instead of calling ToLower to build up the path, this code should use the new "path" and "hashPath" properties introduced in the DependencyContext Libraries.

This will break ASP.NET apps on case-sensitive file systems.

@joelverhagen @gkhanna79 

/cc @pranavkm

**Comment by gkhanna79** [comment]
Isn't this required for 1.1.0 Preview?

**Comment by eerhardt** [comment]
> Isn't this required for 1.1.0 Preview?

Yes, but there is no 1.1.0 Preview milestone.  1.1.0 is the closest that I see.

**Comment by gkhanna79** [comment]
Just send email to shiproom once the PR is ready.

**Comment by eerhardt** [comment]
Reopening to port to 1.1.0.

**Comment by eerhardt** [comment]
This has been ported to release/1.1.0.
