### ISSUE TITLE
Package version for v2.1.0

### ISSUE THREAD

**Issue by gbalykov** [dotnet/core-setup#4232]
dotnet/versions for core-setup was updated to `stable`
(see https://github.com/dotnet/versions/blob/master/build-info/dotnet/core-setup/release/2.1/Latest.txt), however, the default value of `StabilizePackageVersion` in `./BranchInfo.props` for `v2.1.0` is still false, which leads to include of prerelease label in package version. Should `StabilizePackageVersion` also be updated?

cc @alpencolt @Dmitri-Botcharnikov

**Comment by gbalykov** [comment]
cc @weshaggard

**Comment by weshaggard** [comment]
We no longer make a commit to stabilize packages we just kick off our stable build by setting the properties correctly. `/p:StabilizePackageVersion=true /p:PackageVersionStamp=`

**Comment by gbalykov** [comment]
@weshaggard thank you!
