### ISSUE TITLE
Daily build links are all broken

### ISSUE THREAD

**Issue by cocowalla** [dotnet/core-setup#4245]
All the daily build links in this repo's main readme.md file are broken.

For example, the Windows x64 installer [link](https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/dotnet-runtime-latest-win-x64.exe) gives `ResourceNotFound`.

**Comment by leecow** [comment]
Something was messed up with the azure account for the storage. Should be good to go now.

**Comment by steveharter** [comment]
Dupe of https://github.com/dotnet/core-setup/issues/4200
