### ISSUE TITLE
C++ dependency

### ISSUE THREAD

**Issue by kasper3** [dotnet/core-setup#4293]
CoreFX has been fully independent of libstdc++. There is no C++ code left in the repo's current master.

Although the primary requirement for writing CoreFX native parts in C emerged to support Mono, it was also realized that using C++ code means an additional dependency on libstdc++ which is an OK dependency if we have a huge code base relying on C++ features like CoreCLR, but probably not a good idea to carry this bulky dependency for convenience sake in every compilable unit in .NET Core. See https://github.com/dotnet/corert/issues/3564 for the main idea. On a hindsight, this makes your lib compatible on places like old or OS like Solaris, where C++11+ compiler isn't readily available, which is the primary reason Mono native parts are all written in C instead of C++.

Looking at the codebase of core-setup, besides few usages of try/catch `Exception` objects (which I am not sure if this article can be used as reference http://www.on-time.com/ddj0011.htm), it is possible to convert C++ files to C to reduce the dependencies and code size.

@jkotas, do you see there is a potential in doing this work, what would be the right way to deal with exception in core-setup?

**Comment by jkotas** [comment]
core-setup native part always comes together with CoreCLR that has heavy dependency on C++. I do see what we would gain by rewriting the core-setup native part in C. It would be rewrite for the sake of rewrite.

**Comment by kasper3** [comment]
> core-steup native part always come together with CoreCLR

Agree, but shouldn't there be a balance, for example, is it a good justification for every single .so/.dylib/.dll in .NET Core installation directory can depend on libstdc++, because few of them actually need?

```
ldd /usr/sbin/dotnet/host/fxr/2.1.0/libhostfxr.so
        linux-vdso.so.1 (0x00007fff129a5000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0d07f82000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0d07be4000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0d079cc000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0d075db000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0d085b8000)
```

Should there be general preference to reduce amount of dependencies per compilable unit (.so, .a), like we are removing dead code, unused usings etc.? I think cutting off one dependency off of ldd's list weights more than removing dead code. Also it reduces the code side, as mentioned by the article i linked about exception handling:

![image](https://user-images.githubusercontent.com/33230602/41748939-a99c675e-75bc-11e8-9b62-b1a79979d811.png)

**Comment by jkotas** [comment]
The corefx shims were pretty much written in C already. It was not a big deal to convert them to C. It looks and works pretty much the same as before. And the Mono project needs were a good justification for it.

It is not the case for core-setup native parts. The core-setup native parts have heavy dependency on C++. It is not just the few places where it is using exceptions. There are dependencies on `std::vector` or `std::array` that do not have 1:1 equivalents in C++. There is a dependency on external json parser - https://github.com/dotnet/core-setup/tree/master/src/corehost/cli/json/casablanca/include/cpprest. We do not want to be in the business of having and testing our own implementation of json parser. 

If you are looking for good candidates to rewrite in C you can take a look at https://github.com/dotnet/coreclr/tree/master/src/corefx/System.Globalization.Native . It is a shim very similar to the corefx ones.

Another improvement in similar category would be finishing https://github.com/dotnet/coreclr/pull/14725 . It should result into much smaller libcoreclr.so.
