### ISSUE TITLE
Native library dependencies can't be in different NuGet packages

### ISSUE THREAD

**Issue by bricelam** [dotnet/core-setup#4303]
I was trying to package up some native libraries to redistribute on NuGet (similar to the runtime.* packages). It looks like they all need to be in the same NuGet package to make it work.

I had hoped to create two packages: one for zlib and one for libxml2 (which depends on zlib), and use PInvoke to call into libxml2, but because of the way `LoadLibraryEx` is invoked, it will only look for dependencies as siblings to libxml2.dll or in the app directory.

The workaround, of course, is to create one package containing the closure of native libraries. This isn't ideal, however since two NuGet package may end up containing different versions of a common dependency (like zlib).

**Comment by bricelam** [comment]
Random thought: Could call `AddDllDirectory()` or modify the PATH/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH environment variable for all NuGet package directories containing native assets for the current runtime.

**Comment by omajid** [comment]
@natemcmaster had an idea about how to implement this for ASP.NET Core packages. Is that something that could be generalized?

**Comment by natemcmaster** [comment]
@omajid I think this is lower level than package structure. IIUC the problem right, a solution would may require changes to the way corehost/coreclr flow additional probing paths into the dlopen/LoadLibraryEx calls. I'm not sure such a mechanism exists today.

**Comment by bricelam** [comment]
Correct. I'm proposing adding that mechanism (via `AddDllDirectory()` or the `PATH`/`LD_LIBRARY_PATH`/`DYLD_LIBRARY_PATH` environment variable). I thought I found the code related to that somewhere in this repo, but now I can't find it...

**Comment by jeffschwMSFT** [comment]
Thanks for the feedback @bricelam, we have an existing dotnet/coreclr bug https://github.com/dotnet/coreclr/issues/12707 tracking a similar bug. (well there are a couple, but this is the main discussion).  Can you add any specific requirements to that thread?
