### ISSUE TITLE
Remove api-ms-win-core-xstate-l2-1-0.dll baseline after RS5

### ISSUE THREAD

**Issue by mmitche** [dotnet/core-setup#4309]
This file was only catalog signed, which means we fail the signing check currently.  This will be fixed in RS5.  When this happens, remove baseline.

**Comment by wtgodbe** [comment]
@mmitche are we able to remove the baseline now?

**Comment by mmitche** [comment]
Yes, we can remove it.  It may actually already be gone.

**Comment by wtgodbe** [comment]
Where should I check for its existence? M.NC.App?

**Comment by mmitche** [comment]
https://github.com/dotnet/core-setup/commit/a80efce493fd91553d33d0689cbad2af49b93b70

Already done.
