### ISSUE TITLE
Host should respect application manifests defined in assembly

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/core-setup#4314]
## Steps to reproduce
Create an assembly that expects RegFree COM via a app.manifest
The host binary does not respect the app manifest defined in the assembly
COM activation fails since the host's manifest does not reflect the dependent assembly

This is not limited to to just RegFree COM, but to anything placed in the assembly manifest.

See [sdk#1899](https://github.com/dotnet/sdk/issues/1899)

## Expected  behavior
RegFree COM activation should succeed

## Actual behavior
COM activation fails

cc @jeffschwMSFT @luqunl @ericstj

**Comment by ericstj** [comment]
Thanks for opening this @AaronRobinsonMSFT.  I think its important to consider this for both self-contained application which can ship a specialized copy of the host EXE as well as for shared-framework applications which don't contain a specialized host.  In the later case we can't rely on host specialization to embed the windows manifest.

We may be able to have the host call [activation context APIs](https://docs.microsoft.com/en-us/windows/desktop/SbsCs/activation-contexts).  It seems like these would allow the host to create a context for the application that uses the manifest file from the managed DLL and then that would flow normally as threads are created throughout the application.

**Comment by AaronRobinsonMSFT** [comment]
@ericstj Yep. I found the activation context API after we chatted. I am currently looking at testing out this scenario in the [CoreRun project](https://github.com/dotnet/coreclr/tree/master/src/coreclr/hosts/corerun) to determine feasibility.

**Comment by ericstj** [comment]
Cool.  That's a good testing ground as a fix for the host. /cc @steveharter 

I bet you could even call that from individual test cases if you were interested in using it for interop tests of CoreCLR.  I could imagine something like `ActivationHelper.RunWithManifest(() => myTest(), myManifestFile);`

**Comment by luqunl** [comment]
> I bet you could even call that from individual test cases if you were interested in using it for interop tests of CoreCLR.

AFAIK CoreCLR testcase also use CoreRun,  if Aaron change Corerun to support application manfiest, then these testcase should just work, why need `ActivationHelper.RunWithManife`?

**Comment by ericstj** [comment]
It was just an idea if you wanted each test case within an application to define its own manifest file, in case you didn't want to spin up a new process every time you wanted to test with different COM registration.

**Comment by AaronRobinsonMSFT** [comment]
@ericstj I like that idea and @jkotas and I chatted about that as an approach forward as well. Based on the simplicity of the solution and since the API was designed to solve this exact problem I am going forward with modifying the host and see what comments I get.

**Comment by AaronRobinsonMSFT** [comment]
@ericstj The change to `CoreRun` to start consuming the embedded manifest is now being used in tests with dotnet/coreclr#18843. If you have any tests for coreclr or prototypes using `CoreRun` as a test bed for this approach would be appreciated 😸

**Comment by ericstj** [comment]
A couple interesting things to test would be: what happens with other manifest settings like `supportedOs` and `dpiAware`?  Do the application context APIs hook these as well?  That's particularly interesting for the portable app that needs to use the host and wants hi-DPI or wants specific os-version-shim behavior.

Other interesting tests I can imagine are around how `sticky` the context setting is.  Think about ways to try break the activation context stack: new threads created in the same process by various means that may not result from the thread directly being created by user code on the main thread.  Will those still have the activation context applied by the host?

All my prototypes are real apps that I've ported to core.  These are a bit messy and not directly shareable due to the hacked-up nature of the prototypes.  Come talk to me offline if you're interested.

**Comment by AaronRobinsonMSFT** [comment]
@vitek-karas @jkoritzinsky Have we had a chance to understand how users will be able to embed a custom application manifest in their app? If we don't provide something, then RegFree COM from a .NET Core application will not be possible without some hackery on the user's part.

cc @jeffschwMSFT

**Comment by vitek-karas** [comment]
This should already work for apps with "apphost" (Which is the default now). It won't work for muxer as we don't have a way to modify the resources.
The apphost should get all the native resources compiled into the managed .dll. Including manifest and whatever else.

**Comment by AaronRobinsonMSFT** [comment]
@vitek-karas Sounds good. I will verify this works as expected and hopefully close this issue.

**Comment by AaronRobinsonMSFT** [comment]
I have been able to verify this scenarios. Thanks!
