### ISSUE TITLE
MAX_PATH issues breaking package restore due to incomplete file cleanup

### ISSUE THREAD

**Issue by MattGal** [dotnet/core-setup#4328]
@dotnet-mc-bot commented on [Tue Jul 03 2018](https://github.com/dotnet/core-eng/issues/3823)

Opened on behalf of @MattGal

Build is failing due to incomplete cleanup, owing from > 260 character paths on Windows like :

E:\A\_work\3426\s\core-setup\packages\runtime.linux-arm.microsoft.private.corefx.netcoreapp\4.5.0-servicing-26703-02\sources\bin\obj\AnyOS.AnyCPU.Release\System.Runtime.InteropServices.WindowsRuntime\netcoreapp\System.Runtime.InteropServices.WindowsRuntime.notsupported.cs

This breaks restore later on.

Warnings: 27
Status Message: failed

Build : Master - 20180703.03 (Product Build)
Failing configurations:
- Windows
  - PortableBuild-x86
[Mission Control Build Info](https://mc.dot.net/#/product/netcore/master/source/official~2Fcore-setup~2Fmaster~2F/type/build~2Fproduct~2F/build/20180703.03/workItem/Orchestration/analysis/external/Link)

---

@MattGal commented on [Tue Jul 03 2018](https://github.com/dotnet/core-eng/issues/3823#issuecomment-402252873)

Oops meant to make this in core-setup.

**Comment by MattGal** [comment]
Note that addressing this issue is urgent, since if the workspace in question gets reused the max_path problem will persist.

**Comment by MattGal** [comment]
@weshaggard FYI.

**Comment by weshaggard** [comment]
@MattGal is this a new issue? If not do you have any ideas of what triggered it?

**Comment by MattGal** [comment]
I have no idea when this actually started, but the inclusion of the sources directory looks like a likely candidate for what started it.  The paths that VSTS is using for source directories have not changed.  

We need to keep an eye on this because it could break restore any time a workspace is reused.

**Comment by weshaggard** [comment]
@wtgodbe could you please have a look? 

@dagood @ericstj correct me if I'm wrong but IIRC we made a call to stop putting the source code in the normal packages given we have moved to sourcelink so the best option is to stop producing packages with the source code in them.

**Comment by dagood** [comment]
Yeah, that was discussed in https://github.com/dotnet/corefx/issues/19781. (Issue is still open.)

**Comment by wtgodbe** [comment]
I can take a look. Do we want to remove Source files from all 3 Core repos?

**Comment by weshaggard** [comment]
Yes

**Comment by wtgodbe** [comment]
Closing as resolved
