### ISSUE TITLE
Add an export to apphost.exe to be able to locate hostfxr.dll

### ISSUE THREAD

**Issue by pakrym** [dotnet/core-setup#4330]
Currently ANCM has hardcoded logic to be able to resolve dotnet and hostfxr location and subsequently host coreclr.

`apphost.exe` also has similar logic but it's not exposed. It would be nice to get rid of duplication.

## Proposal:

Export `size_t get_hostfxr_location(wchar_t* buffer, size_t size)` method that would discover `hostfxr.dll` location and write it to the `buffer` parameter without starting the app.

**Comment by jeffschwMSFT** [comment]
This scenario has growing importance for other scenarios.  We are going to explore how to cover as many of them as possible.

**Comment by muratg** [comment]
@jeffschwMSFT Do you know what preview this would go in?

cc @vitek-karas

**Comment by jeffschwMSFT** [comment]
@muratg we do not have it aligned yet with a preview.  Once we have those details we will let you know.

**Comment by muratg** [comment]
@jeffschwMSFT Sounds good, thanks. We'll need to align our change with this, so looking forward to hearing your plans.

**Comment by muratg** [comment]
@jeffschwMSFT **ping** 

Where are you guys with this? We'd like to get https://github.com/aspnet/AspNetCore/issues/3839 done in Preview3, which is blocked on this.

**Comment by jeffschwMSFT** [comment]
@murtag we just discussed the priority for this scenario and it does not look like preview 3 is in scope.  We can work together to ensure you remain unblocked as we work through our priorities.

**Comment by muratg** [comment]
@jeffschwMSFT We'll need some time to react when you get this in. What preview do you expect to get this in, so that we can get our plan in order? Thanks.

**Comment by jeffschwMSFT** [comment]
We should discuss now to ensure we have the right shape of what you are looking for.  To get a preview of the direction you can check out the .NET COM server work that is inflight.  This work will come in closer to the summer.

**Comment by jeffschwMSFT** [comment]
Can you elaborate on what scenario is blocked?  And in what way?

**Comment by muratg** [comment]
@pakrym can more clearly elaborate the blocked scenario here.

**Comment by vitek-karas** [comment]
One thing which is probable broken without this is non-default installs of .NET Core using registry. In 3.0 it's possible to install the SDK and runtimes into a custom location and then in Windows registry specify that this location is to be used as the "global" location (just like Program Files is used today).

If we don't provide this export, or ASP.NET doesn't implement lookup in the registry the new functionality would be broken.

**Comment by jeffschwMSFT** [comment]
> Not sure how COM server work is applicable here

The way COM activation works is by 'in essence' providing a hostfxr (really apphost) that is renamed as the COM assembly to handle all the logic on loading the runtime.  There is an analogous case here where you need something to contain that logic.  That is why I recommended taking a look.  We have plans on providing this more general mechanism so that people do not need to mirror this lookup logic, etc.

**Comment by pakrym** [comment]
@vitek-karas another example of why this feature is important is semver 2.0 work (https://github.com/dotnet/core-setup/issues/4795) we would have to copy the implementation then it goes in.

**Comment by vitek-karas** [comment]
Please take a look at #5336 which introduces `nethost` and the `nethost_get_hostfxr_path` which should do basically exactly what this issue is asking for. I'm not sure we should also expose something similar on `apphost` directly as it would not work all apps (apps are not guaranteed to have `apphost`).

**Comment by jeffschwMSFT** [comment]
cc @elinor-fung

**Comment by sdmaclea** [comment]
The `nethost.dll` is the accepted design.
