### ISSUE TITLE
Error "Cannot get required symbol CRYPTO_add_lock from libssl"

### ISSUE THREAD

**Issue by ied206** [dotnet/core-setup#4334]
## Steps to reproduce

Type `dotnet run` in Ubuntu 16.04's $HOME` directory.

## Expected behavior

When I run .Net Core 2.1 on my Linux Mint 18.3 machine, it runs fine.
```
$ dotnet run
Couldn't find a project to run. Ensure a project exists in /home/joveler, or pass the path to the project using --project.
```

## Actual behavior

In faulty Ubuntu 16.04, .Net Core 2.1 fails to run.
```
$ dotnet run
Cannot get required symbol CRYPTO_add_lock from libssl
Aborted
```

I have never experienced this kind of issue before on any Ubuntu 16.04 installation, only one machine has this issue.

## Cause

function `CRYPTO_add_lock` does not exist in `libcrypto.so.1.1`, but only in `libcrypto.so.1.0.0`.
But by unknown reason, dotnet ubuntu binary load `libcrypto.so.1.1` instead of `libcrypto.so.1.0.0`.
```
$ readelf --dyn-syms /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 | grep CRYPTO_add_lock
  2483: 00000000000628b0    90 FUNC    GLOBAL DEFAULT   13 CRYPTO_add_lock@@OPENSSL_1.0.0
```
```
$ readelf --dyn-syms /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 | grep CRYPTO_add_lock
```

I tried using `LD_PRELOAD` variables with openssl 1.0.2 built from source, but .Net Core does not reference libcrypto.so directly so no luck.
```
$ ldd /usr/bin/dotnet
	linux-vdso.so.1 =>  (0x00007ffcf97e5000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f38064c5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f38062a8000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3805f26000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3805c1d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3805a07000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f380563d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f38066c9000)
```

#### apt list --installed | grep ssl
```
libcurl4-openssl-dev/xenial-updates,xenial-security,now 7.47.0-1ubuntu2.8 amd64 [installed]
libgnutls-openssl27/xenial-updates,now 3.4.10-4ubuntu1.4 amd64 [installed]
libio-socket-ssl-perl/xenial,xenial,now 2.024-1 all [installed,automatic]
libnet-smtp-ssl-perl/xenial,xenial,now 1.03-1 all [installed,automatic]
libnet-ssleay-perl/xenial,now 1.72-1build1 amd64 [installed,automatic]
libssl-dev/xenial,now 1.1.0h-2.0+ubuntu16.04.1+deb.sury.org+1 amd64 [installed]
libssl-doc/now 1.1.0h-2+ubuntu16.04.1+deb.sury.org+2 all [installed,upgradable to: 1.1.0h-2.0+ubuntu16.04.1+deb.sury.org+1]
libssl1.0.0/now 1.0.2k-1+deb.sury.org~xenial+1 amd64 [installed,local]
libssl1.1/xenial,now 1.1.0h-2.0+ubuntu16.04.1+deb.sury.org+1 amd64 [installed]
openssl/xenial,now 1.1.0h-2.0+ubuntu16.04.1+deb.sury.org+1 amd64 [installed]
python-backports.ssl-match-hostname/xenial,xenial,now 3.4.0.2-1 all [installed,automatic]
python-openssl/xenial,xenial,now 17.3.0-1~0+ubuntu16.04.1+certbot+1 all [installed,automatic]
python3-openssl/xenial,xenial,now 17.3.0-1~0+ubuntu16.04.1+certbot+1 all [installed,automatic]
```

#### Part of loaded sharedlibrary in runtime (through gdb)
```
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
```

#### apt list --installed | grep ssl
```
libcurl4-openssl-dev/xenial-updates,xenial-security,now 7.47.0-1ubuntu2.8 amd64 [installed]
libgnutls-openssl27/xenial-updates,now 3.4.10-4ubuntu1.4 amd64 [installed]
libio-socket-ssl-perl/xenial,xenial,now 2.024-1 all [installed]
libnet-smtp-ssl-perl/xenial,xenial,now 1.03-1 all [installed]
libnet-ssleay-perl/xenial,now 1.72-1build1 amd64 [installed]
libssl-dev/xenial-updates,xenial-security,now 1.0.2g-1ubuntu4.13 amd64 [installed]
libssl1.0.0/xenial-updates,xenial-security,now 1.0.2g-1ubuntu4.13 amd64 [installed]
libxmlsec1-openssl/xenial,now 1.2.20-2ubuntu4 amd64 [installed,automatic]
openssl/xenial-updates,xenial-security,now 1.0.2g-1ubuntu4.13 amd64 [installed]
python-openssl/xenial,xenial,now 0.15.1-2build1 all [installed]
ssl-cert/xenial,xenial,now 1.0.37 all [installed]
```

#### Part of loaded sharedlibrary in runtime (through gdb)
```
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
```

### Ubuntu 18.04
- apt list --installed | grep ssl
```
libgnutls-openssl27/bionic,now 3.5.18-1ubuntu1 amd64 [installed]
libio-socket-ssl-perl/bionic,bionic,now 2.056-1 all [installed,automatic]
libnet-smtp-ssl-perl/bionic,bionic,now 1.04-1 all [installed,automatic]
libnet-ssleay-perl/bionic,now 1.84-1build1 amd64 [installed,automatic]
libssl1.0.0/bionic-updates,bionic-security,now 1.0.2n-1ubuntu5.1 amd64 [installed]
libssl1.1/bionic-updates,bionic-security,now 1.1.0g-2ubuntu4.1 amd64 [installed,automatic]
libxmlsec1-openssl/bionic,now 1.2.25-1build1 amd64 [installed,automatic]
openssl/bionic-updates,bionic-security,now 1.1.0g-2ubuntu4.1 amd64 [installed]
perl-openssl-defaults/bionic,now 3build1 amd64 [installed,automatic]
python3-openssl/bionic,bionic,now 17.5.0-1ubuntu1 all [installed,automatic]
ssl-cert/bionic,bionic,now 1.0.39 all [installed,automatic]
```

#### Part of loaded sharedlibrary in runtime (through gdb)
```
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
```

**Comment by jeffschwMSFT** [comment]
@leecow

**Comment by leecow** [comment]
We use 16.04 for quite a bit of testing and haven't encountered this so will need to figure out how your 16.04 got into a bad state. I just did a quicky verification on my main 16.04 box and all is well there with l.

Can you share the setup flow for the 16.04 machine? I do notice that your 16.04 libssl is not coming from the Ubuntu archives. Maybe a clue?

> libssl1.0.0/now 1.0.2k-1+deb.sury.org~xenial+1 amd64 [installed,local]

@rakeshsinghranchi and @bartonjs for possible assistance.

**Comment by bartonjs** [comment]
In a portable build we seem to not directly load libcrypto, but let it get cascade loaded from libssl (because libssl has its own copy of the exports).

Since libssl has the SONAME bound in its loader I don't see how things got into a weird state:

```
$ ldd /lib/x86_64-linux-gnu/libssl.so.1.0.0
        linux-vdso.so.1 =>  (0x00007fff0bbeb000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007faa7d01f000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007faa7cc55000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007faa7ca51000)
        /lib64/ld-linux-x86-64.so.2 (0x00007faa7d6cc000)
```

But, as Lee said, your libssl seems to be from somewhere other than the expected source:

```
$ apt list -a libssl1.0.0
Listing... Done
libssl1.0.0/xenial-updates,xenial-security,now 1.0.2g-1ubuntu4.13 amd64 [installed]
libssl1.0.0/xenial 1.0.2g-1ubuntu4 amd64
```

So the error seems to be in whatever package you have for libssl1.0.0.

**Comment by ied206** [comment]
Thanks for your kind reply. 

> But, as Lee said, your libssl seems to be from somewhere other than the expected source:

Since I learned .Net Core is not the cause but the custom openssl package is, I will contact system maintainer to workaround this issue. 

> In a portable build we seem to not directly load libcrypto, but let it get cascade loaded from libssl (because libssl has its own copy of the exports).

Meanwhile, are there any way to force `dotnet` to use custom `libssl.so` exist, aside from `LD_PRELOAD`? 
The system having the issue is a shared server and I cannot touch about system packages.

**Comment by bartonjs** [comment]
Since you're loading `libssl.so.1.0.2` which is the name that Debian used (but not Ubuntu) you might have luck with setting `CLR_OPENSSL_VERSION_OVERRIDE=1.0.0`, that'll make us try `libssl.so.1.0.0` before the normal probing order.

**Comment by ied206** [comment]
```
$ export CLR_OPENSSL_VERSION_OVERRIDE=1.0.0
```
Thanks! .Net Core runs well after setting `CLR_OPENSSL_VERSION_OVERRIDE` as instructed.
