### ISSUE TITLE
Native host API tests should run on non-Windows

### ISSUE THREAD

**Issue by nguerrera** [dotnet/core-setup#4344]
See this comment:

https://github.com/dotnet/core-setup/blob/6a89975a97472a52725b343bc17bb6bef7845d16/src/test/HostActivationTests/GivenThatICareAboutNativeHostApis.cs#L25-L26

I'm adding more tests of hostfxr native API, and therefore adding more debt. For the new tests, it won't be true that the API is only called on Windows. VS for Mac and VS Code use the msbuild SDK resolver that calls these API cross-platform.

**Comment by nguerrera** [comment]
@steveharter Would it work to just copy libhostfxr.so next to the Host API invoker?

**Comment by steveharter** [comment]
@nguerrera you can give that a try. I don't recall if I tried that. I don't think I added the native file to the deps.json, which may be required for the clr to look locally.

**Comment by nguerrera** [comment]
It seems to work. I'll be pushing a commit onto #4301 shortly that should fix this.

**Comment by sdmaclea** [comment]
@nguerrera Looks like #4301 merged and fixed this.  Can it be closed?
