### ISSUE TITLE
"No SDKs were found" after install "dotnet-hosting-2.1.2-win.exe"

### ISSUE THREAD

**Issue by EdiWang** [dotnet/core-setup#4350]
## Steps to reproduce
1. Uninstall All .NET Core related packages (SDK, Runtime, Hosting Bundles, etc..)
2. Install .NET Core SDK 2.1.302
3. Install .NET Core Hosting Bundle (dotnet-hosting-2.1.2-win.exe) * before install this, use "dotnet --info" will correctly list the SDK version.

## Expected  behavior
"dotnet --info" should list the SDK version of 2.1.302

## Actual behavior
Get "No SDKs were found" in CLI. 
![image](https://user-images.githubusercontent.com/3304703/42549565-672c5bd4-84ff-11e8-9c12-d3cdd9c2b67a.png)

VS2017 can't find the SDK also, but the "PATH" is correct.
![image](https://user-images.githubusercontent.com/3304703/42549591-85cf3494-84ff-11e8-91c5-8af77d587b2d.png)

## Environment data
Windows 10 Build 17134.165
I tried on 2 machines, the issue can be reproduced.

**Comment by EdiWang** [comment]
A quick fix will be uninstall everything .NET Core related (SDK, Runtime, Hosting Bundle), and reinstall SDK *only*, now the "dotnet --info" can show the SDK version correctly.
However without Hosting Bundle, I can't deploy my ASP.NET Core app to local IIS in my development time, some IIS related scenarios can not be tested on Dev environment.

**Comment by steveharter** [comment]
@EdiWang I see you are installing the x86 version. There is issue https://github.com/dotnet/core-setup/issues/4236 where depending on the version of dotnet.exe being executed the --info won't list the other side (e.g. running x64 dotnet.exe won't show x86 runtimes\sdks).

Can you verify that the `C:\Program Files (x86)` folder contains the specified runtime folders that you expect? If so, then this is a duplicate of https://github.com/dotnet/core-setup/issues/4236

**Comment by EdiWang** [comment]
@steveharter I was intended to install x64 runtime and SDK only. But after I install the "Hosting Bundle", it installed both x86 and x64 runtimes on to my machine.

![image](https://user-images.githubusercontent.com/3304703/42613301-e34b3770-85d2-11e8-854d-1b081a5c396e.png)

It is said to be included in the SDK, but after I installed SDK, there's no AspNetCoreModule in IIS, this is why I will install Hosting Bundle every time with a new .NET Core release.

As my second screenshot shows, I have both C:\Program Files (x86)\dotnet and C:\Program Files\dotnet folders in my PATH. The SDK disappears from the "dotnet --info" command. It didn't happen in previous version like 2.1.1.

The major impact is that not only does the SDK disappear from .NET Core CLI, it also disappears from Visual Studio 2017, so I can't build projects targeting .NET Core 2.1.

The only fix now is NOT to install "Hosting Bundle" after install SDK v 2.1.302. But this is blocking me from testing my application with IIS.

**Comment by EdiWang** [comment]
I tried on a new Windows 10 VM, the issue isn't happening, seems to be something related to old .NET Core files not being uninstalled correctly.

**Comment by EdiWang** [comment]
Here comes the ultimate fix:

1. If you have VS2017 installed, modify the install and uncheck ".NET Core cross-platform Development" workload, and uncheck ".NET Core runtime" in Individual Components tab.
2. Uninstall All .NET Core related packages, including Hosting Bundle, Runtime and SDK
3. Manually delete "dotnet" folder under "C:\Program Files" and  "C:\Program Files (x86)"
4. Manually delete "C:\Users\{yourusername}\.dotnet" folder
5. Run "cleanmgr" and clean up system files
6. Restart the machine
7. Install SDK 2.1.302 (x64)
8. Install Hosting Bundle 2.1.2 (till this step, 2 of my 3 machines are good to go with correct listing of SDK by "dotnet --info", one of my machine still not working, please follow the next step)
9. If the problem still exists, uninstall "Microsoft .NET Core Runtime - 2.1.2 (x86)" **ONLY**
![image](https://user-images.githubusercontent.com/3304703/42617662-11919e5a-85e5-11e8-8055-21c676089285.png)
10. Run "dotnet --info", the SDK should be listed correctly, and AspNetCoreModule should be listed in IIS correctly. 
![image](https://user-images.githubusercontent.com/3304703/42617699-29b5f85a-85e5-11e8-96c6-87cb24bf5b9c.png)

I will close the issue now, and leave this to anyone who may encounter this problem in the future for reference.

**Comment by steveharter** [comment]
I ran the repro steps and did not get the "No SDKs were found" as you did.

However, I think the default `dotnet.exe` that you were running must have been the x86 version (first in %PATH% probing order) because I can get "No SDKs were found" when I manually run the x86 dotnet because of  #4236.

Here's my output with x86:
```
C:\>"C:\Program Files (x86)\dotnet\dotnet.exe" --info

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
```

and my output from x64 dotnet.exe (which did find the SDK):

```
C:\>"C:\Program Files\dotnet\dotnet.exe" --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by smariussorin** [comment]
@EdiWang 
Thanks, but I needed to do one more thing:
I installed the x86 version also of the SDK.
All works, no previous version garbage

**Comment by technificentConsulting** [comment]
The fix for me was simply uninstall "Microsoft .NET Core Runtime - 2.1.2 (x86)" ONLY

**Comment by netcore-jroger** [comment]
@steveharter maybe some problem points can be found from the system environment variables.
I found that Path contains `C:\Program Files(x86)\dotnet\` and `C:\Program Files\dotnet\`. And `C:\Program Files(x86)\dotnet\` is in front of `C:\Program Files\dotnet\`.
So the dot net command is always executed inside `C:\Program Files(x86)\dotnet\dotnet.exe`.
So just delete `C:\Program Files(x86)\dotnet\`.

**Comment by PavloPaitak** [comment]
I just deleted SDK, Runtime x86, and then install SDK x64

**Comment by btflying** [comment]
> @steveharter maybe some problem points can be found from the system environment variables.
> I found that Path contains `C:\Program Files(x86)\dotnet\` and `C:\Program Files\dotnet\`. And `C:\Program Files(x86)\dotnet\` is in front of `C:\Program Files\dotnet\`.
> So the dot net command is always executed inside `C:\Program Files(x86)\dotnet\dotnet.exe`.
> So just delete `C:\Program Files(x86)\dotnet\`.

Yep. It works for me. Just delete `C:\Program Files(x86)\dotnet\`. Thansk.

**Comment by ArkarMoe93** [comment]
> **EdiWang**'s Here comes the ultimate fix: works for me.... Thanks a lots. ;D

**Comment by ddregalo** [comment]
I had success with using _'Add or remove programs'_ and Uninstalling all dotnet references to (x86) 32-bit...after it switched back to 64 bit and worked fine
