### ISSUE TITLE
Network build failures in 'official/core-setup/release/1.1.0/' - '20180712.01'

### ISSUE THREAD

**Issue by MattGal** [dotnet/core-setup#4361]
@dotnet-mc-bot commented on [Wed Jul 11 2018](https://github.com/dotnet/core-eng/issues/3866)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1852461
  - **Agent:** DDVSOWINAGE062
  - **Error log:** error: Response status code does not indicate success: 409 (The package could not be uploaded. The package "Microsoft.DotNet.PlatformAbstractions 1.1.9" already exists. Overwriting existing packages is forbidden according to the p...

@jcagme, @markwilkie

**Comment by MattGal** [comment]
Moved here to track this issue with spinning the same stable build repeatedly;  most likely recourse is to just delete the package in place if this is intentional.

**Comment by wtgodbe** [comment]
This is just an unfortuante consequence of having to re-run stable 1.x builds. When this happens to me I generally just delete the pre-existing package from blob storage before re-running the build. Closing since this probably isn't worth fixing before EOL in June
