### ISSUE TITLE
Port fix for custom host to 2.2

### ISSUE THREAD

**Issue by steveharter** [dotnet/core-setup#4366]
Port commit from master https://github.com/dotnet/core-setup/commit/84fa44f892b42ad9235e4ecb756975d8c8f46f1f to the 2.2 branch.

Per issue https://github.com/dotnet/core-setup/issues/4315

@pakrym can you please verify the issue is fixed in master once a new build is available?

**Comment by pakrym** [comment]
The issue doesn't reproduce with `3.0.0-preview1-26810-04` hostpolicy.

**Comment by steveharter** [comment]
@pakrym should I target 2.1.x instead of 2.2? The 2.1.x fix will make it into 2.2 automatically.

**Comment by pakrym** [comment]
The feature we use hosted CLR in only ships in 2.2 so 2.2 is enough for us.

**Comment by pakrym** [comment]
Recently we reenabled tests that we causing AV in hostpolicy and started running them with AppVerifier on. We see ocasional AppVerifier failures in the same area.

Recent dump: `\\pkrymets\exchange\hostpolicy\iisexpress.exe.5292.dmp.cab`

**Comment by muratg** [comment]
@jeffschwMSFT will this be assigned to someone on your side now?

**Comment by jeffschwMSFT** [comment]
@muratg can we open a new issue for this appverifier related issue?  Please assign to @sdmaclea

**Comment by muratg** [comment]
@pakrym could you please do the needful?

**Comment by pakrym** [comment]
After running tests a bit longer we found that crashes still occur even if appverifier is not running.

So it's the same issue as being fixed here it just happens a bit more infrequently.

**Comment by pakrym** [comment]
Opened https://github.com/dotnet/core-setup/issues/4646
