### ISSUE TITLE
No package dotnet-runtime-2.1.2 available

### ISSUE THREAD

**Issue by ramnov** [dotnet/core-setup#4378]
According to the documentation here : https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.2-download.md#net-core-runtime-only-installation

To install a specific dotnet-runtime version (major-minor-patch), we can just use dotnet-runtime-2.1.2 in package manager. But it fails with the message : "No package dotnet-runtime-2.1.2 available"

```
>yum install dotnet-runtime-2.1.2
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
No package dotnet-runtime-2.1.2 available.
Error: Nothing to do
```

The correct way would be to use : 
```
yum install dotnet-runtime-2.1-2.1.2
```

Is the above statement right ? or am I missing something ? 

## Steps to reproduce
```
rpm --import https://packages.microsoft.com/keys/microsoft.asc
sh -c 'echo -e "[packages-microsoft-com-prod]\nname=packages-microsoft-com-prod" > /etc/yum.repos.d/dotnetdev.repo'
sh -c 'echo -e "baseurl=https://packages.microsoft.com/rhel/7/prod\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" >> /etc/yum.repos.d/dotnetdev.repo'
yum install dotnet-runtime-2.1.2
```

## Expected  behavior
successful installation of dotnet-runtime-2.1.2

## Actual behavior
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
No package dotnet-runtime-2.1.2 available.

## Environment data
centos 7

**Comment by steveharter** [comment]
ptal @leecow

**Comment by leecow** [comment]
You can see available versions with 

```
$dnf --showduplicates list dotnet-runtime-2.1
Last metadata expiration check: 0:02:47 ago on Mon 23 Jul 2018 12:14:23 PM PDT.
Available Packages
dotnet-runtime-2.1.x86_64                                               2.1.0-1                                                packages-microsoft-com-prod
dotnet-runtime-2.1.x86_64                                               2.1.1-1                                                packages-microsoft-com-prod
dotnet-runtime-2.1.x86_64                                               2.1.2-1                                                packages-microsoft-com-prod
```

`dnf install dotnet-sdk-2.1` will install the latest available. To install a particular version, you need to reference both the package identity and the version. eg, `sudo dnf install dotnet-runtime-2.1-2.1.1-1`

**Comment by ramnov** [comment]
Thanks @leecow. Understood. Would recommend updating the documentation to be more precise.
