### ISSUE TITLE
Installer metadata in ARP uses HTTP URLs instead of HTTPS

### ISSUE THREAD

**Issue by Eilon** [dotnet/core-setup#4379]
## Steps to reproduce

Install latest .NET Core SDK for Windows installer from: https://www.microsoft.com/net/download/windows
I used https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.302-windows-x64-installer

Note: I'm not sure if this is the right repo because I couldn't find these URLs specified in the code here.

## Expected  behavior

ARP entries should use HTTPS URLs to https://dotnet.github.io/ (or perhaps they should really link to https://dot.net/ or https://www.microsoft.com/net).

## Actual behavior

HTTP URLs are used:

![image](https://user-images.githubusercontent.com/202643/42911644-b9b6f714-8aa0-11e8-9bfc-e755039f397e.png)

## Environment data

N/A

**Comment by steveharter** [comment]
ptal @rakeshsinghranchi @leecow

**Comment by leecow** [comment]
Is that in the SDK installer? @wli3

**Comment by rakeshsinghranchi** [comment]
Runtime bundle has correct url : https://github.com/dotnet/core-setup/blob/master/src/pkg/packaging/windows/sharedframework/bundle.wxs#L10

@wli3, looks like github.com/dotnet/cli master branch doesn't produce the windows installers.

**Comment by rakeshsinghranchi** [comment]
cc @livarcocc  . This issue exists in CLI only.

**Comment by rakeshsinghranchi** [comment]
This issue was moved to dotnet/core-sdk#42
