### ISSUE TITLE
VSCODE setup from Ubuntu Xenial: Error: E: Unable to locate package dotnet-dev-1.0.0-preview2-003121

### ISSUE THREAD

**Issue by algosig** [dotnet/core-setup#438]
## Steps to reproduce
I'm following this wiki for dotnet core installation:[dotnet core setup in ubuntu](https://www.microsoft.com/net/core#ubuntu)

## Expected  behavior
command used: `sudo apt-get install dotnet-dev-1.0.0-preview2-003121`
This should actually install dotnet-dev-1.0.0-preview2-003121.

## Actual behavior
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-dev-1.0.0-preview2-003121
E: Couldn't find any package by glob 'dotnet-dev-1.0.0-preview2-003121'
E: Couldn't find any package by regex 'dotnet-dev-1.0.0-preview2-003121'
```

## Environment data
`dotnet --info` output:
Since I'm having problem in installation the output is: "**command not found**.

**Comment by gkhanna79** [comment]
@piotrpMSFT @brthor @livarcocc PTAL.

**Comment by algosig** [comment]
@piotrpMSFT @gkhanna79 

- Shouldn't the issue also be labeled something as issue on  **setup**. Because I couldn't even download the packages during installation.

**Comment by gkhanna79** [comment]
@algosig The "dev" setups are not generated in Core-Setup repo but in http://github.com/dotnet/cli repo.

**Comment by gkhanna79** [comment]
@algosig Can you please file this bug in the CLI repo and close this one so that it be tracked correctly?

**Comment by brthor** [comment]
@algosig Did you accidently add the ubuntu 14 feed? I've seen this happen a few times.

**Comment by algosig** [comment]
@brthor I'm trying to setup vscode on **Xenial Xerus Ubuntu 16.04 LTS**.
Above is the output from my terminal.

**Comment by brthor** [comment]
can you show the output of `cat /etc/apt/sources.list.d/dotnetdev.list`

**Comment by algosig** [comment]
@brthor 
`deb [arch=i386] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main
`

**Comment by brthor** [comment]
@algosig There is no `arch=i386` debian package currently available, are you able to use the `arch=amd64` version?

**Comment by algosig** [comment]
@brthor How can I use amd64 when I have i686 arch.
uname -a : `Linux xenial 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:41:41 UTC 2016 i686 i686 i686 GNU/Linux`

Even though I change the arch=i686 to arch=amd64
the error is same:
```
sudo apt-get install dotnet-dev-1.0.0-preview2-003131
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-dev-1.0.0-preview2-003131
E: Couldn't find any package by glob 'dotnet-dev-1.0.0-preview2-003131'
E: Couldn't find any package by regex 'dotnet-dev-1.0.0-preview2-003131'
```



Are there any ways to tweak the arch?
@piotrpMSFT  @gkhanna79

**Comment by gkhanna79** [comment]
@piotrpMSFT Is this on for 1.1.0?

**Comment by piotrpMSFT** [comment]
We don't currently support 32-bit CPU architectures on Linux. This is true across the board [CLI, CoreFx, CLR]. We should first have an issue opened regarding adding support for this platform into the product. Once that is added to the roadmap we will look at scheduling for related ancillary work like CLI builds.
