### ISSUE TITLE
runtime-deps files for SLES reference krb5-mini, should be krb5

### ISSUE THREAD

**Issue by leecow** [dotnet/core-setup#4384]
Output from SLES 12 SP3 system.

```
sudo zypper install dotnet-runtime-2.1
Refreshing service 'cloud_update'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides krb5-mini needed by dotnet-runtime-deps-2.1-2.1.2-1.x86_64
 Solution 1: do not install dotnet-runtime-2.1-2.1.2-1.x86_64
 Solution 2: break dotnet-runtime-deps-2.1-2.1.2-1.x86_64 by ignoring some of its dependencies
```

krb dependency for the following needs to be updated to `krb5` from `krb5-mini` and the appropriate change made in the the build code

* https://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.1.0/dotnet-runtime-deps-2.1.0-sles.12-x64-upgrade.rpm
* https://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.1.1/dotnet-runtime-deps-2.1.1-sles.12-x64.rpm
* https://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.1.2/dotnet-runtime-deps-2.1.2-sles.12-x64.rpm

**Comment by rakeshsinghranchi** [comment]
@leecow , you should have updated packages to replace. Closing this now.

**Comment by ramnov** [comment]
Hello @leecow and @rakeshsinghranchi 

I just tried installing dotnet-runtime-2.1 in SLES 12 SP3 and got the following error : 

```
zypper install dotnet-runtime-2.1

Problem: dotnet-runtime-2.1-2.1.2-1.x86_64 requires dotnet-runtime-deps-2.1 >= 2.1.2, but this requirement cannot be provided
  uninstallable providers: dotnet-runtime-deps-2.1-2.1.2-1.x86_64[packages-microsoft-com-prod]
 Solution 1: Following actions will be done:
  downgrade of krb5-client-1.12.5-40.23.2.x86_64 to krb5-client-1.10.2-10.2.1.x86_64
  install krb5-client-1.10.2-10.2.1.x86_64 (with vendor change)
    SUSE LLC <https://www.suse.com/>  -->  openSUSE
  downgrade of krb5-1.12.5-40.23.2.x86_64 to krb5-1.10.2-10.2.1.x86_64
  install krb5-1.10.2-10.2.1.x86_64 (with vendor change)
    SUSE LLC <https://www.suse.com/>  -->  openSUSE
 Solution 2: do not install dotnet-runtime-2.1-2.1.2-1.x86_64
 Solution 3: break dotnet-runtime-2.1-2.1.2-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/3/c] (c): 
```

Not sure what is the right approach here. I would like to automate installation in a script as well using zypper -n flag.

**Comment by leecow** [comment]
Hi @ramnov - the updated runtime-deps for SLES has need yet been uploaded to the repo. The files had not come back from the signing team Friday so hopefully this morning.

**Comment by ramnov** [comment]
@leecow Thanks for your reply. Please let me know once the files have been uploaded to the repo.

**Comment by leecow** [comment]
@ramnov, 2.1.0, 2.1.1 and 2.1.2 runtime-deps packages have been updated and tested for the correct krb5 dependency. Should be good to go now.
