### ISSUE TITLE
dotnet-sdk-2.1.3 installs dotnet-runtime-2.0.4

### ISSUE THREAD

**Issue by ianjirka** [dotnet/core-setup#4386]
[edit - emphasis]

## Steps to reproduce
$ apt list --installed | grep dotnet

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

$ sudo apt-get install dotnet-sdk-2.1.3
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  dotnet-host dotnet-hostfxr-2.0.4 dotnet-runtime-2.0.4
The following NEW packages will be installed:
  dotnet-host **dotnet-hostfxr-2.0.4 dotnet-runtime-2.0.4** dotnet-sdk-2.1.3

[...]

$ dotnet build
Microsoft (R) Build Engine version 15.5.179.9764 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/2.1.3/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1. 
[...]

$ apt list --installed | grep dotnet

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

dotnet-host/xenial,xenial,now 2.1.2-1 amd64 [installed,automatic]
dotnet-hostfxr-2.0.4/xenial,xenial,now 2.0.4-1 amd64 [installed,automatic]
dotnet-runtime-2.0.4/xenial,xenial,now 2.0.4-1 amd64 [installed,automatic]
dotnet-sdk-2.1.3/xenial,xenial,now 2.1.3-1 amd64 [installed]

## Expected  behavior
Can build applications targeting .netcore 2.1

## Actual behavior
Cannot.

## Environment data
$ uname -a
Linux ianjirka-dev 4.4.0-17134-Microsoft #137-Microsoft Thu Jun 14 18:46:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

**Comment by steveharter** [comment]
@leecow @rakeshsinghranchi @nguerrera

**Comment by nguerrera** [comment]
It's confusing for any sdk earlier than 2.1.300 because the sdk version didn't tell you anything about the bundled runtime version. Starting with 2.1.300, the first two parts of the sdk version match the first two parts of the bundled runtime version. You need sdk 2.1.300 or greater to target .net core 2.1.

**Comment by leecow** [comment]
@ianjirka - to install (or update) the latest 2.1, use `apt-get install dotnet-sdk-2.1`.

**Comment by ianjirka** [comment]
rookie mistake on my part - thanks@leecow.  That works great.
