### ISSUE TITLE
Document Windows7 prerequisites

### ISSUE THREAD

**Issue by jkotas** [dotnet/core-setup#4388]
Installing .NET Core on vanilla Windows7 does not work (see https://github.com/dotnet/core-setup/issues/3220#issuecomment-406029568).

We have identified that the following KB needs to be installed on Win7 to .NET Core to work:

- KB3118401 https://support.microsoft.com/en-us/help/3118401/update-for-universal-c-runtime-in-windows 
- KB2533623 https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot

**Comment by joshfree** [comment]
@mairaw @richlander can you help route this?

**Comment by mairaw** [comment]
@jkotas can you open an issue at https://github.com/dotnet/docs? We can update the topic https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites to call those KBs out as well. 
We already mention a few at [this section](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites#net-core-dependencies).

**Comment by jkotas** [comment]
Actually, the two mentioned there are the same as the two I have found (the KB numbers are different, but I do not think it matters). So this is documented already.
