### ISSUE TITLE
Failed to load the dll from [C:\Program Files\dotnet\host\fxr\2.0.9\hostfxr.dll] , HRESULT: 0x7D4A8

### ISSUE THREAD

**Issue by nguerrera** [dotnet/core-setup#4390]
_From @mindtech2014 on July 22, 2018 15:16_

Getting Error when running dotnet --help or other dotnet command
Failed to load the dll from [C:\Program Files\dotnet\host\fxr\2.0.9\hostfxr.dll]
, HRESULT: 0x7D4A8
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\h
ost\fxr\2.0.9\hostfxr.dll failed

Environment: 
OS: Windows 7 Ultimate SP1  (32 bit)

Following things installed 

dotnet-sdk-2.1.202-win-x86
KB2999226
KB2533623
Microsoft Visual C++ 2015 Redistributable Update 3

_Copied from original issue: dotnet/cli#9717_

**Comment by steveharter** [comment]
This is likely due to a missing runtime dependency.

Can you see if installing the [uCRT ](https://github.com/dotnet/core/blob/851184b864923dd49dfcb099932e30c431856ba7/release-notes/1.0/1.0.0-known-issues.md#universal-c-runtime-dependency-on-windows)helps? Thanks

**Comment by nguerrera** [comment]
Shouldn't the runtime installer chain in its dependencies?

**Comment by steveharter** [comment]
The shared runtime has the uCRT next to it, but the host (dotnet.exe) doesn't. See https://github.com/dotnet/core-setup/issues/3220

**Comment by steveharter** [comment]
Closing this as by design. See also https://github.com/dotnet/core-setup/issues/4388
