### ISSUE TITLE
Runtime resolution to more recent for FDD published apps broken in some circumstances (e.g. 2.1.0-preview2 -> 2.1.1)

### ISSUE THREAD

**Issue by nguerrera** [dotnet/core-setup#4391]
_From @mirkogeffken on July 22, 2018 21:37_

## Steps to reproduce
1) Make sure no runtimes/sdks/shared frameworks are installed (in my case I had a 1.0.0 installed still, but that I did not expect to be used)
2) Install 2.1.0-preview2 SDK Install on Win x64 in my case (URL: https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.300-preview2-windows-x64-installer) (<-- others may fail too, but 2.1.1 e.g. -> 2.1.2 does not)
3) Create a new console app with "dotnet new console" in a folder called myapp
4) Publish an FDD version with "dotnet publish"
5) Confirm this runs by doing "dotnet bin/Debug/netcoreapp2.1/publish/myapp.dll" (You should see "Hello World"
6) Uninstall SDK just installed from add/remove programs
7) Install 2.1.1 (2.1.301 SDK) from https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.301-windows-x64-installer (2.1.2 will also have the same issue)
8) run "dotnet --info" and confirm that 2.1.1 is the only one installed (remove (if necessary) shared frameworks from Program Files\dotnet\shared\{folders}\version (as listed by info other than 2.1.1 (or 2.1.2 if you chose that in step 7
9) go back to myapp folder and run "dotnet bin/Debug/netcoreapp2.1/publish/myapp.dll"

## Expected  behavior
See "Hello World" as in step 5 as 2.1.1 is clearly a more recent (more supported and more secure) version than 2.1.0-preview2

I have been unable to find any statement anywhere that preview versions (while unsupported) would not support resolution to a more recent version.

## Actual behavior
(To be clear I had 1.0.0 installed also despite my steps, which is why it is listed below and used 2.1.2 in this case, but have tried without 1.0.0 and tried with 2.1.1 from preview2 also)

Error Output:
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0-preview2-26406-04' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      1.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  1.0.0-preview2-003121 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 1.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

_Copied from original issue: dotnet/cli#9718_

**Comment by nguerrera** [comment]
Currently, there is no roll forward from preview to RTM runtimes. This is deliberate in the code and not an unknown bug. I and several others have argued that it should be changed, but there has been also some pushback to keep it this way too.

@richlander @Petermarcu @steveharter @dsplaisted

**Comment by nguerrera** [comment]
See "Preview releases and roll-forward" here: https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/

**Comment by steveharter** [comment]
>> Is there a way to opt into more aggressive roll-forward

There are knobs available for most settings, but not for preview-to-release.

The only more aggressive setting is to roll-forward on Major via [roll-forward-on-no-candidate-fx](https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/roll-forward-on-no-candidate-fx.md)

However, input is welcome here. There is a slider from high compat to "just try the lastest and hope it works" and we have been receptive to change. We changed to less restrictive settings in the 2.1 timeframe: we now roll-forward on Minor, and from release-to-preview, which we did not do in 2.0 and prior releases.

**Comment by mirkogeffken** [comment]
@steveharter Thank you so much for pointing me at that as I have not found that on my own and am not sure I would have. I think my personal opinion is that I would prefer the default to be roll-forward (even to major) if no candidate is available (Azure App Service where we are not in control of what is installed comes to mind), but I am pretty sure you ask 2 people and get 4 answers :). For completeness sake did I understand you correctly that there is also an option available to force latest Fx (even if a closer patch is present)? (Meaning if runtimeconfig.json states 1.0.1 and both 1.0.2 and 9.0.0 are installed I would like it to pick 9.0.0 if this flag is set). If you have this is there a way to say pick latest minor vs pick latest major akin to the roll-forward-on-no-candidate-fx?  Regardless you can close this as this is clearly not a defect or issue but a conscientious design decision.

**Comment by steveharter** [comment]
@mirkogeffken there is not an option to force a newer framework when there are "more compatible" versions available. For compatibility, we always pick the same or closest version (going forward). The default for this is Minor, which means we pick the closest version my Minor or Patch. After we pick the closest version, then by default we "apply patches" which means we install the latest patch version (keeping Major and Minor the same).

In order to change to a later framework, you have the options:
1) Re-target your application using a newer SDK\runtime. This will re-publish your application and update the version information in your runtimeconfig.json as well as re-generate your deps.json. This is the safest option as you get a chance to test your application on the newest version.
2) Uninstall the older versions you don't want. Make sure your roll-forward options are compatible with the version(s) remaining.
3) Specify `--fx-version` as a argument for dotnet.exe. This will look for that exact version.

What kind of managed code is the Azure App Service running that it can risk running on a much newer framework? I assume it is not ASP.NET for example. The more information we can get on these types of scenarios the better we can accommodate them. Thanks

**Comment by jeffschwMSFT** [comment]
Closing as resolved.  Let us know if you have further questions.
