### ISSUE TITLE
Temporarily Disable Tizen CI leg

### ISSUE THREAD

**Issue by joshfree** [dotnet/core-setup#4408]
Currently the Tizen build leg is failing in the core-setup repo due to an infrastructure issue (not product related).  CoreCLR and CoreFX branches have already temporarily disabled this failing leg, with https://github.com/dotnet/corefx/issues/28901 tracking the re-enabling of the leg once the Tizen infra is fixed.

To keep core-setup CI green, we can also temporarily disable the failing leg here, and update https://github.com/dotnet/corefx/issues/28901 with the PR so that it can be rolled back as part of fixing https://github.com/dotnet/corefx/issues/28901.

**Comment by dagood** [comment]
This seems doable just by removing Tizen from the list of platforms:

https://github.com/dotnet/core-setup/blob/2087318225cab45e8f51bd1afea8db99f2adbb2e/netci.groovy#L13

The netci.groovy files are pretty different between CoreFX and Core-Setup, but for reference, CoreFX has a change to a condition to skip Tizen: https://github.com/dotnet/corefx/pull/30715 changed https://github.com/dotnet/corefx/blob/f391820c4808bcb02c7b3dd88b684f36a0a98b6a/netci.groovy#L332

@MattGal or @mmitche should be able to give more specific guidance if needed, or review a PR.

**Comment by weshaggard** [comment]
@alpencolt, @gbalykov could you guys have a look?

**Comment by alpencolt** [comment]
@weshaggard we will check
