### ISSUE TITLE
Microsoft.AspNetCore.App metapackage does not support full framework

### ISSUE THREAD

**Issue by shake82** [dotnet/core-setup#4428]
## Steps to reproduce
1. Change the target framework version to net472
> <TargetFramework>net472</TargetFramework>
2. run **dotnet restore**
## Expected  behavior
Nuget packages should be restored

## Actual behavior
Error is thrown **Package Microsoft.AspNetCore.App 2.1.0 is not compatible with net472 (.NETFramework,Version=v4.7.2)**

Since all the packages that are referred to by **Microsoft.AspNetCore.App** support **netstandard2.0**, there is no reason for this package to only support **netcoreapp2.1**.

**Comment by steveharter** [comment]
ptal @natemcmaster @leecow

**Comment by natemcmaster** [comment]
This is by design. See discussion on this subject here: https://github.com/aspnet/MetaPackages/issues/255#issuecomment-394136977
