### ISSUE TITLE
1.0.x host is removed when installing 1.1 preview

### ISSUE THREAD

**Issue by leecow** [dotnet/core-setup#444]
/host/fxr/1.0.1 is removed when installing a 1.1.0 preview Shared FX. Previous versions of the host should remain installed side-by-side. 
1. Removed /usr/local/share/dotnet
2. Installed dotnet-osx-x64.1.0.1.pkg
3. Verified /host/fxr/1.0.1
4. Installed dotnet-osx-x64.1.1.0-preview1-001100-00
5. host/fxr/ now only contains 1.1.0-preview1-001100-00 

cc/ @gkhanna79

**Comment by gkhanna79** [comment]
I chatted with @schellap and he is going to take a look at this asap.

**Comment by gkhanna79** [comment]
@schellap Do you have an update on what is going on here?

**Comment by gkhanna79** [comment]
@schellap Please prepare a fix for release/1.0.0 branch as well for the next LTS release.

**Comment by gkhanna79** [comment]
@schellap Moving this to 1.0.x milestone to track getting this in for it.

**Comment by gkhanna79** [comment]
Assigning this to you @rakeshsinghranchi and @vivmishra

**Comment by gkhanna79** [comment]
@vivmishra Was this fixed with https://github.com/dotnet/core-setup/pull/1838? If so, please close the issue.

**Comment by vivmishra** [comment]
This is related to OSx so not fixed by #1838

**Comment by gkhanna79** [comment]
Is the fix for this issue understood?

**Comment by rakeshsinghranchi** [comment]
Not yet, will try to repro the issue later today.

**Comment by rakeshsinghranchi** [comment]
Issue does not repro against latest build daily build of 1.0.5 and 1.1.2. 

├── LICENSE.txt
├── ThirdPartyNotices.txt
├── dotnet
├── host
│   └── fxr
│       ├── 1.0.1
│       ├── 1.1.0
│       └── 2.0.0-beta-001611-00
└── shared
    └── Microsoft.NETCore.App
        ├── 1.0.5-servicing-004885-00
        ├── 1.1.2-servicing-001491-00
        └── 2.0.0-beta-001611-00

Below PRs should have fixed the issue:
https://github.com/dotnet/core-setup/pull/453
https://github.com/dotnet/core-setup/pull/452
