### ISSUE TITLE
Cannot get required symbol TLSv1_1_method from libssl

### ISSUE THREAD

**Issue by jpramos123** [dotnet/core-setup#4460]
## Steps to reproduce

dotnet new webapi -o TodoApi
## Expected  behavior

Expect the cli to create a project named TodoApi
## Actual behavior
Throwing the error:
Cannot get required symbol TLSv1_1_method from libssl
[1]    8060 abort (core dumped)  dotnet new webapi -o TodoApi

## Environment data
Fedora 27
kernel: 4.17.12-100.fc27.x86_64
Lenovo T460s

**Comment by omajid** [comment]
Can you do an `rpm -qa | grep ssl`?

**Comment by jpramos123** [comment]
@omajid Follow below my output.
`
openssl-libs-1.1.0h-3.fc27.x86_64
openssl-devel-1.1.0h-3.fc27.x86_64
xmlsec1-openssl-1.2.23-4.fc27.x86_64
openssl-1.1.0h-3.fc27.x86_64
rubygem-openssl-2.0.7-89.fc27.x86_64
openssl-lib-compat-1.0.0i-1.fc27.x86_64
texlive-sslides-svn32293.0-36.fc27.5.noarch
compat-openssl10-1.0.2o-1.fc27.x86_64
python-backports-ssl_match_hostname-3.5.0.1-5.fc27.noarch
`

**Comment by omajid** [comment]
Hm. You have the compat openssl 1.0 lib installed. That was my first suspect. Can you run an `strace`? `dotnet -fo strace.log dotnet new webapi -o TodoApi` and upload the strace.log file? Please look over it and remove any confidential information if it appears there. That should give us a better idea of what dotnet is looking for.

**Comment by jpramos123** [comment]
Hello, 
@omajid follow the uploaded file.

[strace.log](https://github.com/dotnet/core-setup/files/2291942/strace.log)

**Comment by omajid** [comment]
There is strange. The openssl 1.0 package is ` compat-openssl10-1.0.2o-1.fc27.x86_64` Where did you get the other `openssl-lib-compat-1.0.0i-1.fc27.x86_64` package? Is that an official Fedora 27 package? It seems to be placing a library at `/lib64/libssl.so.1.0.0` which does not provide TLSv1 and that library is getting picked up and causing `dotnet` issues. What happens if you `dnf remove openssl-lib-compat` it and try again?

**Comment by jpramos123** [comment]
Yeah, it worked!
Just removed the `openssl-lib-compat-1.0.0i-1.fc27.x86_64` from `bt0dotninja-openssl-lib-compat` repository.

Output after running `dotnet new webapi -o TodoApi`:
------------------------------------------------------------------------------
ASP.NET Core
------------
Successfully installed the ASP.NET Core HTTPS Development Certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other platforms refer to the platform specific documentation.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
Getting ready...
The template "ASP.NET Core Web API" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on TodoApi/TodoApi.csproj...
  Restoring packages for /home/jramos/Documents/dev/dotnetcore/web-api/TodoApi/TodoApi.csproj...
  Generating MSBuild file /home/jramos/Documents/dev/dotnetcore/web-api/TodoApi/obj/TodoApi.csproj.nuget.g.props.
  Generating MSBuild file /home/jramos/Documents/dev/dotnetcore/web-api/TodoApi/obj/TodoApi.csproj.nuget.g.targets.
  Restore completed in 1.7 sec for /home/jramos/Documents/dev/dotnetcore/web-api/TodoApi/TodoApi.csproj.

Restore succeeded.
-------------------------------------------------------------------------------


Thanks!

**Comment by dagood** [comment]
Closing as resolved, issue with installed dependencies. Please let me know if I'm mistaken. 🙂
