### ISSUE TITLE
windows.winmd should not be included in netcoreapp distro

### ISSUE THREAD

**Issue by jkotas** [dotnet/core-setup#4472]
## Steps to reproduce

Download https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/dotnet-runtime-latest-win-x64.zip 

## Expected  behavior

Windows.winmd is not in package

## Actual behavior

Windows.winmd is in the package

**Comment by jkotas** [comment]
cc @luqunl

**Comment by luqunl** [comment]
I am working on
