### ISSUE TITLE
After install of new version sdk 2.1.4 dotnet cli still uses old 2.1.105 version

### ISSUE THREAD

**Issue by halcwb** [dotnet/core-setup#4506]
## Steps to reproduce

Follow the installation guidelines for installation of the dotnet sdk:

```
wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb

sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-2.1.4

```

Installation runs without any warnings or errors. Rerun of the commands shows:

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> dotnet-sdk-2.1.4 is already the newest version (2.1.4-1).
> 0 to upgrade, 0 to newly install, 0 to remove and 127 not to upgrade.

run `dotnet --info`

## Expected  behavior

Get the correct dotnet version, i.e. 2.1.4  

## Actual behavior

The version still shows the old 2.1.105 version.

## Environment data

> Welcome to Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-21-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> New release '18.04.1 LTS' available.
> Run 'do-release-upgrade' to upgrade to it.

**Comment by halcwb** [comment]
Ok, stupid, I had to just say 2.1 and omit the minor version.

So, `sudo apt-get install dotnet-sdk-2.1`. That fixed it.

**Comment by omajid** [comment]
Hey, in case it was not obvious, 2.1.4 is version that comes before 2.1.105. Instead of treating it as decimals, compare each number one-by-bone. `.4` < `.104` < `.400`. So what you wanted was `dotnet-sdk-2.1.400`, not `dotnet-sdk-2.1.4`. That said, `dotnet-sdk-2.1` is the best because it refers to the latest version (currently `2.1.401`).
