### ISSUE TITLE
Add hostfxr method to return APP_PATHS/APP_NI_PATHS for given app.

### ISSUE THREAD

**Issue by pauldotknopf** [dotnet/core-setup#4517]
I am trying to self-host a .NET application. I was referred to ```hostfxr_main``` by this: https://github.com/dotnet/coreclr/issues/19734

This method creates the runtime, invokes assembly, and disposes of the runtime. I need to manage the runtime myself and invoke custom delegates using the ```coreclrhost.h``` ([here](https://github.com/dotnet/coreclr/blob/master/src/coreclr/hosts/inc/coreclrhost.h)).

I need all the info to call ```coreclr_initialize``` myself, computed from .deps.json and .runtimeconfig.json.

I can get ```NATIVE_DLL_SEARCH_DIRECTORIES``` myself from ```hostfxr_get_native_search_directories```, but there is no way to get ```APP_PATHS```  or  ```APP_NI_PATHS```.

Side question, instead, what do you think about having a hostfxr method that returns a ```hostHandle```/```domainId``` pair that can be further managed with ```coreclrhost.h``` ?

**Comment by pauldotknopf** [comment]
Update, I think it is the ```TRUSTED_PLATFORM_ASSEMBLIES``` that I need. I just checked, and it is what contains the NuGet referenced assemblies.

I'm not sure how important the ```APP_PATHS``` or ```APP_NI_PATHS``` is, but I def need a way to get the ```TRUSTED_PLATFORM_ASSEMBLIES``` assemblies.

**Comment by pauldotknopf** [comment]
This could probably be closed, since I think this would be addressed in #4530.

**Comment by jeffschwMSFT** [comment]
Closing in favor of https://github.com/dotnet/core-setup/issues/4530
