### ISSUE TITLE
dotnet Abort Trap: 6

### ISSUE THREAD

**Issue by SpiraMira** [dotnet/core-setup#455]
## Steps to reproduce

On macOS Sierra build (16B2548a)
mac pro 3,1

Step 1: brew install openssl (add to $path and fix rpath etc...)
Step 2: install .NET Core using [https://www.microsoft.com/net/core#macos]
Step 3: any dotnet command results in ...

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.InternalAbstractions.RuntimeEnvironment' threw an exception. ---> System.PlatformNotSupportedException: Error reading Darwin Kernel Version ---> System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E) at Microsoft.DotNet.InternalAbstractions.Native.NativeMethods.Darwin.sysctl(Int32\* name, UInt32 namelen, Byte\* oldp, UInt32\* oldlenp, IntPtr newp, UInt32 newlen) at Microsoft.DotNet.InternalAbstractions.Native.NativeMethods.Darwin.GetKernelRelease() --- End of inner exception stack trace --- at Microsoft.DotNet.InternalAbstractions.Native.NativeMethods.Darwin.GetKernelRelease() at Microsoft.DotNet.InternalAbstractions.Native.PlatformApis.GetDarwinVersion() at Microsoft.DotNet.InternalAbstractions.Native.PlatformApis.GetOSVersion() at Microsoft.DotNet.InternalAbstractions.RuntimeEnvironment..cctor() --- End of inner exception stack trace --- at Microsoft.DotNet.InternalAbstractions.RuntimeEnvironment.GetRuntimeIdentifier() at Microsoft.DotNet.Cli.MulticoreJitProfilePathCalculator.CalculateProfileRootPath() at Microsoft.DotNet.Cli.MulticoreJitActivator.StartCliProfileOptimization() at Microsoft.DotNet.Cli.MulticoreJitActivator.TryActivateMulticoreJit() at Microsoft.DotNet.Cli.Program.Main(String[] args) Abort trap: 6
## Expected  behavior

not to crash
## Environment data

`dotnet --info` output: crashes

**Comment by SpiraMira** [comment]
The exception is thrown here GetKernelRelease() in core-setup->NativeMethods.Darwin.cs

```
                public unsafe static string GetKernelRelease()
                {
                    const uint BUFFER_LENGTH = 32;


                    var name = stackalloc int[2];
                    name[0] = CTL_KERN;
                    name[1] = KERN_OSRELEASE;


                    var buf = stackalloc byte[(int)BUFFER_LENGTH];
                    var len = stackalloc uint[1];
                    *len = BUFFER_LENGTH;


                    try
                    {
                        // If the buffer isn't big enough, it seems sysctl still returns 0 and just sets len to the
                        // necessary buffer size. This appears to be contrary to the man page, but it's easy to detect
                        // by simply checking len against the buffer length.
                        if (sysctl(name, 2, buf, len, IntPtr.Zero, 0) == 0 && *len < BUFFER_LENGTH)
                        {
                            return Marshal.PtrToStringAnsi((IntPtr)buf, (int)*len);
                        }
                    }
                    catch (Exception ex)
                    {
                        throw new PlatformNotSupportedException("Error reading Darwin Kernel Version", ex);
                    }
                    throw new PlatformNotSupportedException("Unknown error reading Darwin Kernel Version");
                }


                [DllImport("libc")]

```
My equivalent test

```
#include <sys/param.h>
#include <sys/sysctl.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

int main()
{
    int mib[] = {CTL_KERN, KERN_OSRELEASE};
    size_t len;
    sysctl(mib, sizeof mib / sizeof(int), NULL, &len, NULL, 0);

    char* kernelVersion = malloc(len);
    sysctl(mib, sizeof mib / sizeof(int), kernelVersion, &len, NULL, 0);

    printf("Kernel version is %s\n", kernelVersion);
    free(kernelVersion);
}
```
which returns

```
Kernel version is 16.1.0
Program ended with exit code: 0
```

Any ideas why this is crashing...

**Comment by gkhanna79** [comment]
@eerhardt @piotrpMSFT PTAL.

**Comment by SpiraMira** [comment]
closed related cli #4409

**Comment by SpiraMira** [comment]
Some clues from my man 3 sysctl

```
SYNOPSIS
     11      #include <sys/types.h>
     12      #include <sys/sysctl.h>
     13
     14      int
     15      sysctl(int *name, u_int namelen, void *oldp, size_t *oldlenp, void *newp, size_t newlen)

```
and...

```
The information is copied into the buffer specified by oldp.  The size of the buffer is given by the location specified by oldlenp before the call, and that location gives the amount of data copied after a successful call and after a call that returns with the error code ENOMEM.  If the amount of data available is greater than the size of the buffer supplied, the call supplies as much data as fits in the buffer provided and returns with the error code ENOMEM.  If the old value is not desired, oldp and oldlenp should be set to NULL.

The size of the available data can be determined by calling sysctl() with the NULL argument for oldp.  The size of the available data will be returned in the location pointed to by oldlenp. For some operations, the amount of space may change often.  For these operations, the system attempts to round up so that the returned size is large enough for a call to return the data shortly thereafter.

To set a new value, newp is set to point to a buffer of length newlen from which the requested value is to be taken.  If a new value is not to be set, newp should be set to NULL and newlen set to 0.

```

Hence, my two calls to sysctl.  First to get the length of the desired result buffer in oldp. Second to actually get the data.

Hope this helps...

**Comment by eerhardt** [comment]
@gkhanna79 and @piotrpMSFT - I'm going on leave from now until the end of the year.  I won't be able to get to this before January.

**Comment by gkhanna79** [comment]
CC @livarcocc

**Comment by gkhanna79** [comment]
@piotrpMSFT Should this go into CLI repo for 1.1.0?

**Comment by piotrpMSFT** [comment]
@gkhanna79 @SpiraMira we [CLI team] develops on Mac OS Sierra day to day and we're not hitting this issue. I just explicitly followed the steps enumerated by @SpiraMira to be sure and found no repro. I wonder if the installed version of openssl is the same as recommended in the installation instructions. Let's hold off on addressing this until we can get a repro to diagnose.

**Comment by eerhardt** [comment]
@SpiraMira - can you provide more information about your environment?  What version of .NET Core did you install?  Where did you install it from?  What does your Apple -> "About this Mac" say?

**Comment by gkhanna79** [comment]
Closing until we have more specific repro steps. Please reopen when you have the details.
