### ISSUE TITLE
Port startup hook to release/2.2

### ISSUE THREAD

**Issue by sbomer** [dotnet/core-setup#4573]
The startup hook (described in https://github.com/dotnet/core-setup/pull/4421) should be ported to 2.2 to enable Service Fabric to use the feature. The core-setup change is here: https://github.com/dotnet/core-setup/pull/4465.

**Comment by vitek-karas** [comment]
@sbomer Can this be closed since the code has already been ported?

**Comment by sbomer** [comment]
Yup! Thanks.
