### ISSUE TITLE
Question: rebuild PlatformAbstractions for Sierra

### ISSUE THREAD

**Issue by SpiraMira** [dotnet/core-setup#458]
Hi - I need some guidance on how to build a new dotnet that can address #455 myself. Just need some guidance on navigating this project on macOS Sierra.

I would like to explore some possible changes in Dotnet.PlatformAbstractions/Native/PlatformApis.cs
-If I rebuild core-setup with my patches, will it generate the new native libraries?
-If so, how do I set up my project so that a new build of cli will pick up my local changes?
-Is this generally the way to test local patches? Or am I way off base...
-Is there a resource describing this entire workflow?  The developer guide(s) address cli, fx etc...but I fail to understand how to propagate changes to native libraries since those projects pull nuget packages/dlls down. I'm sure the docs exist, just point me in the right direction.

I would like to contribute and eventually propose a push.

A little guidance is appreciated.  Thanks.
## Environment data

`dotnet --info` output:

**Comment by gkhanna79** [comment]
@piotrpMSFT @eerhardt @brthor Can you please help?

**Comment by SpiraMira** [comment]
Hi again, I temporarily addressed some of my issues by resetting my DYDL_FALLBACK_LIBRARY_PATH so that GetKernelRelease() can find my dylibs (libc). It was set in support of another project and dotnet couldn't dynamically bind to /usr/lib/libc.dylib anymore.
Also had to set DOTNET_RUNTIME_ID to osx.10.11-x64 to let the build progress.  Seems like a temporary fix at best to build on Sierra. It's all documented here cli issue #4413.

So I'm left with just two simple questions/issues:

- when will dotnet support Sierra properly?  The cli developer guide seems to indicate a current lack of Sierra support (what does /p:SkipInvalidConfigurations=true actually do...) But we can download and use the sdk though. How was that built?

- Going forward, what is the proper workflow to rebuild my own dotnet environment correctly. For example if I customize core-setup functionality. Do I rebuild cli,fx,clr ?  I've read all relevant docs such as the installation-scenarios and developer guides.  Is there a master project to rebuild all the relevant bits and deploy locally.

Thanks in advance,  Patrice

**Comment by eerhardt** [comment]
@gkhanna79 and @piotrpMSFT - I'm going on leave from now until the end of the year.  I won't be able to get to this before January.

**Comment by gkhanna79** [comment]
CC @livarcocc

**Comment by gkhanna79** [comment]
CC @eerhardt

**Comment by gkhanna79** [comment]
Bringing this back to your attention @piotrpMSFT @eerhardt

**Comment by eerhardt** [comment]
We've asked @SpiraMira for more information on the issue in #455, but haven't heard back.  I would suggest closing this and #455 until we can get more info on how to reproduce the error.
