### ISSUE TITLE
linux build of release/2.0.0 branch failing

### ISSUE THREAD

**Issue by vellozzi** [dotnet/core-setup#4587]
## Steps to reproduce
clone the core-setup repo
checkout release/2.0.0 branch
./build.sh -release

## Expected  behavior
No errors

## Actual behavior
/build/core-setup/src/pkg/projects/Microsoft.NETCore.App/src/Microsoft.NETCore.App.depproj : error NU1603: Microsoft.NETCore.App depends on Microsoft.Private.CoreFx.NETCoreApp (>= 4.4.4-servicing-26810-02) but Microsoft.Private.CoreFx.NETCoreApp 4.4.4-servicing-26810-02 was not found. An approximate best match of Microsoft.Private.CoreFx.NETCoreApp 4.5.0-dev-di-25909-02 was resolved.
/build/core-setup/src/pkg/projects/Microsoft.NETCore.App/src/Microsoft.NETCore.App.depproj : error NU1603: Microsoft.NETCore.App depends on transport.Microsoft.NETCore.Runtime.CoreCLR (>= 2.0.9-servicing-26807-01) but transport.Microsoft.NETCore.Runtime.CoreCLR 2.0.9-servicing-26807-01 was not found. An approximate best match of transport.Microsoft.NETCore.Runtime.CoreCLR 2.1.0-b-uwp6-25707-02 was resolved.
/build/core-setup/src/pkg/projects/Microsoft.NETCore.App/src/Microsoft.NETCore.App.depproj : error NU1202: Package Microsoft.Private.CoreFx.NETCoreApp 4.5.0-dev-di-25909-02 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Private.CoreFx.NETCoreApp 4.5.0-dev-di-25909-02 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)
/build/core-setup/Tools/packageresolve.targets(47,5): error MSB3073: The command ""/build/core-setup/Tools/dotnetcli/dotnet" restore --packages "/build/core-setup/packages" --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json --source https://dotnet.myget.org/F/cli-deps/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://www.myget.org/F/nugetbuild/api/v3/index.json --source https://api.nuget.org/v3/index.json --source https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json /build/core-setup/src/pkg/projects/Microsoft.NETCore.App/src/Microsoft.NETCore.App.depproj /p:TargetGroup= /p:ConfigurationGroup=Release /p:ArchGroup= /p:OSGroup=Linux /p:TargetFramework=netcoreapp2.0  /p:HasRuntimePackages=false /p:IntermediateOutputPath=/build/core-setup/Bin/obj/linux-x64.Release/Microsoft.NETCore.App/" exited with code 1. [/build/core-setup/src/pkg/projects/Microsoft.NETCore.App/src/Microsoft.NETCore.App.depproj]
/build/core-setup/src/pkg/projects/Microsoft.NETCore.App/src/Microsoft.NETCore.App.depproj : error NU1603: Microsoft.NETCore.App depends on Microsoft.Private.CoreFx.NETCoreApp (>= 4.4.4-servicing-26810-02) but Microsoft.Private.CoreFx.NETCoreApp 4.4.4-servicing-26810-02 was not found. An approximate best match of Microsoft.Private.CoreFx.NETCoreApp 4.5.0-dev-di-25909-02 was resolved.
/build/core-setup/src/pkg/projects/Microsoft.NETCore.App/src/Microsoft.NETCore.App.depproj : error NU1603: Microsoft.NETCore.App depends on transport.Microsoft.NETCore.Runtime.CoreCLR (>= 2.0.9-servicing-26807-01) but transport.Microsoft.NETCore.Runtime.CoreCLR 2.0.9-servicing-26807-01 was not found. An approximate best match of transport.Microsoft.NETCore.Runtime.CoreCLR 2.1.0-b-uwp6-25707-02 was resolved.
/build/core-setup/src/pkg/projects/Microsoft.NETCore.App/src/Microsoft.NETCore.App.depproj : error NU1202: Package Microsoft.Private.CoreFx.NETCoreApp 4.5.0-dev-di-25909-02 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Private.CoreFx.NETCoreApp 4.5.0-dev-di-25909-02 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)
/build/core-setup/src/pkg/projects/Microsoft.NETCore.App/src/Microsoft.NETCore.App.depproj : error NU1202: Package Microsoft.Private.CoreFx.NETCoreApp 4.5.0-dev-di-25909-02 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0) / linux-x64. Package Microsoft.Private.CoreFx.NETCoreApp 4.5.0-dev-di-25909-02 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)
/build/core-setup/Tools/packageresolve.targets(47,5): error MSB3073: The command ""/build/core-setup/Tools/dotnetcli/dotnet" restore --packages "/build/core-setup/packages" --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json --source https://dotnet.myget.org/F/cli-deps/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://www.myget.org/F/nugetbuild/api/v3/index.json --source https://api.nuget.org/v3/index.json --source https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json /build/core-setup/src/pkg/projects/Microsoft.NETCore.App/src/Microsoft.NETCore.App.depproj /p:TargetGroup= /p:ConfigurationGroup=Release /p:ArchGroup= /p:OSGroup=Linux /p:TargetFramework=netcoreapp2.0 -r linux-x64 /p:HasRuntimePackages=false /p:IntermediateOutputPath=/build/core-setup/Bin/obj/linux-x64.Release/Microsoft.NETCore.App/linux-x64/linux-x64" exited with code 1. [/build/core-setup/src/pkg/projects/Microsoft.NETCore.App/src/Microsoft.NETCore.App.depproj]
    6 Warning(s)
    9 Error(s)

## Environment data
running on Amazon Linux in a docker container

**Comment by vellozzi** [comment]
This build is still failing.  We need to make sure the branch builds cleanly so we can build it if/when the next patch of .NET Core 2.0 is released.
Please take a look.

**Comment by omajid** [comment]
For what it's worth, .NET Core 2.0 is set to be End-of-Life'ed on October 1, 2018. There's no plans for a next patch of 2.0.

**Comment by wtgodbe** [comment]
Closing as 2.0.0 is EOL
