### ISSUE TITLE
AV and AppVerifier failure when exception is being thrown in main 

### ISSUE THREAD

**Issue by pakrym** [dotnet/core-setup#4646]
We still observe https://github.com/dotnet/core-setup/issues/4315 in addition we see app verifier failures in the same area:

![image](https://user-images.githubusercontent.com/1697911/45309292-40ecda80-b4d8-11e8-9c15-e43ec0f7d649.png)

Recent dump: `\\pkrymets\exchange\hostpolicy\iisexpress.exe.5292.dmp.cab`

Assigning @sdmaclea as per https://github.com/dotnet/core-setup/issues/4366#issuecomment-422918909

**Comment by sdmaclea** [comment]
Took a look at the dmp. Looks like issue is in breadcrumb_writer. Other than that the dump was not particularly useful.

The test which was triggering this was removed in aspnet/AspNetCore#8727.

I suspect the correct fix will be to revise the resource management to make sure they are properly shared between the threads by using smart pointers.  I suspect the change will be too large to justify porting back to 2.2.

**Comment by sdmaclea** [comment]
@steveharter's design for #4315 explicitly stated `/EHa` was required in the host

Looking at the IIS host source the exception method seems to be set to /EHs.  The destructors are not guaranteed to be called in this case and #4315 will have no affect.

**Comment by sdmaclea** [comment]
/cc @jkotalik 

#6766 should make setting the non-recommended setting `/EHa` unnecessary for 3.0.

**Comment by jkotalik** [comment]
👏
