### ISSUE TITLE
Can't install ASP.NET Core on macOS 10.4

### ISSUE THREAD

**Issue by ronengil** [dotnet/core-setup#4657]
I'm trying to install Visual Studio for mac and the ASP.NET Core will not install.

## Steps to reproduce
Tried from within the VS install...
Tried from VS update...
Downloaded https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.403-macos-x64-installer
Downloaded https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.5-macos-x64-installer

## Actual behavior
But non of them instal! they al fail...

## Environment data
I'm on an iMac Retina 5K 2017 with macOS 10.4 Mojave

<img width="584" alt="screen shot 2018-10-11 at 13 01 52" src="https://user-images.githubusercontent.com/44055553/46796951-86f6c180-cd56-11e8-9127-0bf1a77d4b11.png">
<img width="585" alt="screen shot 2018-10-11 at 13 02 28" src="https://user-images.githubusercontent.com/44055553/46796952-86f6c180-cd56-11e8-9209-c88a7ef6f78a.png">
<img width="622" alt="screen shot 2018-10-11 at 13 05 04" src="https://user-images.githubusercontent.com/44055553/46796953-86f6c180-cd56-11e8-9719-c4c3a21fa82f.png">

**Comment by jeffschwMSFT** [comment]
cc @leecow

**Comment by leecow** [comment]
@rakeshsinghranchi and @wli3

**Comment by rakeshsinghranchi** [comment]
@wli3 , this is SDK installation issue. Will you be looking into this ? Also, feel free to move  this issue to SDK repo. Thanks.

**Comment by leecow** [comment]
Updated my MacBook to 10.14 and successfully installed the 2.1.403 SDK, built and ran an MVC application. 

@ronengil, you indicate that you have tried from VS Install and Update. I presume this is the latest VS for Mac? I don't believe they have integrated 2.1.5/2.1.403 yet. Have you tried install outside of VS (ie, just running the SDK pkg that you downloaded)?

**Comment by ronengil** [comment]
> Updated my MacBook to 10.14 and successfully installed the 2.1.403 SDK, built and ran an MVC application.
> 
> @ronengil, you indicate that you have tried from VS Install and Update. I presume this is the latest VS for Mac? I don't believe they have integrated 2.1.5/2.1.403 yet. Have you tried install outside of VS (ie, just running the SDK pkg that you downloaded)?

Yes, I did try to install it in 4 different ways - and it still doesn't install - not from the SDK, not from the RunTime only, not from VS Install and not from VS update...

**Comment by rakeshsinghranchi** [comment]
@ronengil , can you please share /var/log/install.log pertaining to Dotnet installer to further diagnose the issue?

**Comment by DaveIlsley** [comment]
I'm not sure if this is the same problem as I am getting a different error message, however I also can't install .NET core in any of the ways described above on Mojave either. The error message suggests I don't have admin privileges, but my user is an admin and this fails when running with sudo as well.
[install.log](https://github.com/dotnet/core-setup/files/2588752/install.log)

**Comment by dleeapho** [comment]
Closing since we need more info per @rakeshsinghranchi . Feel free to reopen if you have the info @ronengil .
