### ISSUE TITLE
Compatibility with CLI preview2 deps.json with library path null

### ISSUE THREAD

**Issue by schellap** [dotnet/core-setup#467]
## Steps to reproduce
https://github.com/dotnet/core-setup/blob/master/src/corehost/cli/deps_format.cpp#L34
Make it null resilient for all string values.

If we use an old CLI and compile an app targeting NETCore.App 1.1.0, the `path` property is null in `libraries` section. This throws a JSON parsing exception.

The null value for the string could be interpreted as empty.

1. Install the latest shared framework: .\dotnet-install.ps1 -InstallDir . -Architecture x64 -SharedRuntime -Channel release/1.1.0
2. Install an older version of the CLI: .\dotnet-install.ps1 -InstallDir . -Architecture x64 -Version 1.0.0-preview3-003546
3. Create a hello world app and target the latest shared framework. (Don't forget a nuget.config that points at the right feed).
4. Dotnet restore, dotnet build, dotnet run.

## Expected  behavior
Works fine.

## Actual behavior
Incompatible with old CLI due to the exception

## Environment data
`dotnet --info` output:

**Comment by brianrob** [comment]
@schellap, added repro steps.

**Comment by gkhanna79** [comment]
This is a regression from https://github.com/dotnet/core-setup/commit/690e5cfabd74098fc3d5f57dad91e8726caa4c11#diff-ff424df9de64563880ba20413b435710. 

@joelverhagen PTAL at this at the earliest. I am marking it as release blocking.

**Comment by joelverhagen** [comment]
@schellap, step 2 is failing:
```
> ..\dotnet-install.ps1 -InstallDir . -Architecture x64 -Version 1.0.0-preview2-003546
dotnet-install: Downloading https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview2-003546/dotnet-dev-win-x64.1.0.0-preview2-003546.zip
Failed to download https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview2-003546/dotnet-dev-win-x64.1.0.0-preview2-003546.zip.
```

**Comment by gkhanna79** [comment]
@livarcocc @mellinoe Are you aware of this failure?

**Comment by brianrob** [comment]
@joelverhagen, sorry, I got the version string wrong.  It's preview3 not preview2.  I've updated the repro steps.

**Comment by joelverhagen** [comment]
@brianrob, I tried this with latest preview3 (1.0.0-preview3-003892) and the null path property is not written out. How did you pick that specific old version?

**Comment by joelverhagen** [comment]
Back in August, I made a fix to `DependencyContextWriter` to not write out the `path` or `hashPath` properties if they are null:
https://github.com/dotnet/core-setup/commit/d7bf2e9f13c297043772935e75fce7cec52b860a

**Comment by joelverhagen** [comment]
Resolved offline. Not an issue for preview2 and already resolved in preview3.
