### ISSUE TITLE
.NET Core 2.1 fails to install on clean Ubuntu 18.04.1 LTS ( Bionic Beaver )

### ISSUE THREAD

**Issue by rakeshsinghranchi** [dotnet/core-setup#4703]
## Steps to reproduce
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
sudo apt-get install apt-transport-https
sudo apt-get install dotnet-sdk-2.1
sudo apt-get update
sudo apt-get install dotnet-sdk-2.1

## Expected  behavior
dotnet-sdk-2.1 installs successfully

## Actual behavior
The following packages have unmet dependencies:
dotnet-sdk-2.1 : Depends: dotnet-runtime-2.1 (>= 2.1.5) but it is not going to be installed
                  Depends: aspnetcore-runtime-2.1 (>= 2.1.5) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

sudo apt-get install dotnet-runtime-deps-2.1
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
dotnet-runtime-deps-2.1 : Depends: liblttng-ust0 but it is not installable
E: Unable to correct problems, you have held broken packages.

## Environment data
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by rakeshsinghranchi** [comment]
Reason for the failure : 
Ubuntu 18.04.1 by default does not configure Universe repository. dotnet-sdk-2.1 depends on dotnet-runtime-2.1 that requires liblttng-ust0 and is available in Universe repository. 

Resolution : 
sudo add-apt-repository universe
sudo apt-get update

**Comment by rakeshsinghranchi** [comment]
cc @leecow

**Comment by leecow** [comment]
Added to setup doc with https://github.com/dotnet/core/commit/adc8888f3ab2586466ab67f759a3c81e9dd1007c#diff-c7479b374b5e8f02c43c2ae0afef7726

**Comment by rakeshsinghranchi** [comment]
@leecow , can add the resolution in https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/sdk-current page as well ?

**Comment by jerryno6** [comment]
I Found the solultion: I had installed libicu55, and after that, it worked well

sudo add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main"
sudo apt-get update
sudo apt-get install libicu55
