### ISSUE TITLE
Core SDK Installition fails on ubuntu 18.04.1

### ISSUE THREAD

**Issue by rakeshsinghranchi** [dotnet/core-setup#4707]
_From @huzeyfecoskun on October 26, 2018 14:6_

# Issue Title

Core SDK Installition fails on ubuntu 18.04.1

# General

Core SDK installition fails on ubuntu

![issue](https://user-images.githubusercontent.com/673053/47571548-78f19500-d941-11e8-879e-3b3456d1d0bf.png)

_Copied from original issue: dotnet/core#2024_

**Comment by rakeshsinghranchi** [comment]
_From @karelz on October 27, 2018 0:9_

@rakeshsinghranchi @dleeapho @livarcocc can you advise where to route this issue?

**Comment by rakeshsinghranchi** [comment]
@huzeyfecoskun  Thanks for reporting the issue.  Can you please confirm if you have followed steps
for register Microsoft key and feed from https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/sdk-current

```
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb

sudo dpkg -i packages-microsoft-prod.deb
```

**Comment by gcastre** [comment]
I have the same issue (both the SDK and the runtime), didn't have the issue when I followed the instruction in late August.

Yes i registered the microsoft keys.

**Comment by rakeshsinghranchi** [comment]
Can you please share the output of the following commands from the repro machine to further diagnose the issue ?
 
```
List the feeds runtime package is configured.
apt-cache policy dotnet-runtime-2.1

OS details
cat /etc/os-release

```
There is a known  DotNet core setup issue on Bionic Beaver https://github.com/dotnet/core-setup/issues/4703 .

**Comment by gcastre** [comment]
![image](https://user-images.githubusercontent.com/5219776/47797884-833bd680-dd27-11e8-981c-d1576d72ca26.png)

**Comment by rakeshsinghranchi** [comment]
Thanks. Looks like Microsoft Azure feed is not registered correctly. Please run below command and check if packages.microsoft.com is listed . 
```
grep ^[^#] /etc/apt/sources.list /etc/apt/sources.list.d/*
```

Expected output should have a line as below : 
```
/etc/apt/sources.list.d/microsoft-prod.list:deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main
```

**Comment by gcastre** [comment]
Still don't work:

![image](https://user-images.githubusercontent.com/5219776/47805897-b9358680-dd38-11e8-8ffd-793f7e10e4a1.png)

**Comment by rakeshsinghranchi** [comment]
cc @leecow 
Thanks for trying this. Can you follow below commands to resolve the signature issue and try apt-get update

```
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
```

**Comment by gcastre** [comment]
Hello,

It worked.

Thanks.

**Comment by rakeshsinghranchi** [comment]
Thanks for confirming @gcastre .
