### ISSUE TITLE
Tizen Build Failures in CI

### ISSUE THREAD

**Issue by joshfree** [dotnet/core-setup#4716]
@alpencolt, @gbalykov

Tracking issue for Tizen build failure in core-setup CI: 

https://github.com/dotnet/core-setup/pull/4711

https://ci.dot.net/job/dotnet_core-setup/job/master/job/release_tizen_armel_prtest/132/consoleFull#-8536224876a086b3e-df04-41d2-bc4d-43e8f9406d07

> /src/core-setup/src/pkg/projects/Microsoft.NETCore.App/src/Microsoft.NETCore.App.depproj : error NU1603: Microsoft.Private.CoreFx.NETCoreApp 4.6.0-preview1.18530.5 depends on runtime.tizen.5.0.0-armel.Microsoft.Private.CoreFx.NETCoreApp (>= 4.6.0-preview1.18530.5) but runtime.tizen.5.0.0-armel.Microsoft.Private.CoreFx.NETCoreApp 4.6.0-preview1.18530.5 was not found. An approximate best match of runtime.tizen.5.0.0-armel.Microsoft.Private.CoreFx.NETCoreApp 4.6.0-preview1-26815-04 was resolved.

**Comment by gbalykov** [comment]
Has version naming changed recently?

We build `4.6.0-preview1-26815-04`, but `4.6.0-preview1.18530.5` is searched for

**Comment by gbalykov** [comment]
Where can I find nuget builds, that publish packages to `dotnet.myget.org/feed/dotnet-core/`?

**Comment by bartonjs** [comment]
The meta-problem here seems to be that our version numbers went to a new scheme.

* https://github.com/dotnet/coreclr/pull/20720 changed coreclr from "preview1" to "preview".
* https://github.com/dotnet/corefx/pull/32921 changed corefx significantly (e.g. 4.7.0-preview1-26502-03 -> 4.7.0-preview.18527.2)

**Comment by gbalykov** [comment]
@bartonjs I'm working on fixing this for Tizen. Could you, please, clarify, how `preview.18527.2` version is generated? I have not found info on this yet

**Comment by bartonjs** [comment]
@weshaggard Can you explain/point out how corefx's version numbers are generated now?

**Comment by weshaggard** [comment]
That version number is generated from some targets in arcade repo. Presumably if you guys haven't forked much from corefx the versions would just get pulled in. For more info you can see the versioning doc at https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Versioning.md and if you want to see the targets they are at https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.targets.

**Comment by gbalykov** [comment]
@weshaggard thanks! we need to generate `OfficialBuildId` from CoreFX version (e.g. `preview.18527.2`), and I was wondering how to do it with the new versioning scheme

**Comment by wtgodbe** [comment]
@gbalykov can we close this issue?

**Comment by dagood** [comment]
We no longer have a Tizen CI leg in this repo, closing for now.
