### ISSUE TITLE
Drop building  ubuntu.17.10 and fedora.26 dep packages (master )

### ISSUE THREAD

**Issue by vivmishra** [dotnet/core-setup#4722]
We should drop building the following files since they are out of support. 

https://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.1.5/dotnet-runtime-deps-2.1.5-fedora.26-x64.rpm 
https://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.1.5/dotnet-runtime-deps-2.1.5-ubuntu.17.10-x64.deb

Cc @leecow

**Comment by rakeshsinghranchi** [comment]
cc @leecow

**Comment by rakeshsinghranchi** [comment]
PR : https://github.com/dotnet/core-setup/pull/4734
