### ISSUE TITLE
Error 'The following packages have unmet dependencies' while setting up .net core on Ubuntu SERVER bionic 18.04.1 LTS

### ISSUE THREAD

**Issue by jerryno6** [dotnet/core-setup#4724]
## Steps to reproduce
1. Create a VM running Ubuntu Server 18.04 LTS
2. Install docker + docker compose for ubuntu following this pages
https://docs.docker.com/install/linux/docker-ce/ubuntu/
https://docs.docker.com/compose/install/#prerequisites
3. Install .net core following these steps from Microsoft's tutorial to install .net core
https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/sdk-current

## Expected  behavior
net core must be installed successfully and can run dotnet --version

## Actual behavior
displays error: 
vule@userver:~$ sudo apt-get install dotnet-sdk-2.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.1 : Depends: dotnet-runtime-2.1 (>= 2.1.5) but it is not going to be installed
                  Depends: aspnetcore-runtime-2.1 (>= 2.1.5) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

## Environment data
 all Steps I Did are displayed below

> vule@userver:~$ wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
> vule@userver:~$ ls
> hello-world  packages-microsoft-prod.deb  setup.sh
> vule@userver:~$ sudo dpkg -i packages-microsoft-prod.deb
> (Reading database ... 102425 files and directories currently installed.)
> Preparing to unpack packages-microsoft-prod.deb ...
> Unpacking packages-microsoft-prod (1.0-3) over (1.0-3) ...
> Setting up packages-microsoft-prod (1.0-3) ...
> vule@userver:~$ ls
> hello-world  packages-microsoft-prod.deb  setup.sh
> vule@userver:~$ sudo apt-get install apt-transport-https
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Note, selecting 'apt' instead of 'apt-transport-https'
> apt is already the newest version (1.6.6).
> 0 upgraded, 0 newly installed, 0 to remove and 90 not upgraded.
> vule@userver:~$ sudo apt-get update
> Hit:1 https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease
> Hit:2 https://download.docker.com/linux/ubuntu bionic InRelease                                                               
> Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease                         
> Get:4 http://archive.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]
> Hit:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
> Fetched 83.2 kB in 2s (39.0 kB/s)
> Reading package lists... Done
> vule@userver:~$ sudo apt-get install dotnet-sdk-2.1
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  dotnet-sdk-2.1 : Depends: dotnet-runtime-2.1 (>= 2.1.5) but it is not going to be installed
>                   Depends: aspnetcore-runtime-2.1 (>= 2.1.5) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.
> vule@userver:~$ lbs_release -a
> 
> Command 'lbs_release' not found, did you mean:
> 
>   command 'lsb_release' from deb lsb-release
> 
> Try: sudo apt install <deb name>
> 
> vule@userver:~$ sudo lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.1 LTS
> Release:	18.04
> Codename:	bionic
> vule@userver:~$

**Comment by rakeshsinghranchi** [comment]
Please follow related issue for the resolution : https://github.com/dotnet/core-setup/issues/4703

**Comment by jerryno6** [comment]
I Found the solultion: I had installed libicu55, and after that, it worked well

sudo add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main"
sudo apt-get update
sudo apt-get install libicu55

**Comment by kartas39** [comment]
> I Found the solultion: I had installed libicu55, and after that, it worked well

Thanks for workaround! I assume proper solution would be to change dependency to proper libicu**60** (on Ubuntu 18.04)

**Comment by rakeshsinghranchi** [comment]
@jerryno6  , can you please share out for following : 
```
apt-cache policy dotnet-runtime-2.1 
```

On Ubuntu 18.04, dotnet-runtime-deps-2.1 is expected to bring down libicu60.

**Comment by jerryno6** [comment]
I had tried libicu60, but it didn't work. When I had tried the dot-net-runtime, It said something related to libicu55, so I installed libicu55, and it worked like a charm

**Comment by rakeshsinghranchi** [comment]
Thanks @jerryno6 for sharing the output. Machine is misconfigured to pull xenial packages instead of bionic and thus, its pulling down dotnet-runtime-deps-2.1 package for xenial where libicu55 is required. 
Please remove the feed and follow steps to setup feed for bionic https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/sdk-current

**Comment by jerryno6** [comment]
I create a new VM running Ubuntu server 18.01
Created a file setup.sh containing these command

```
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get install apt-transport-https -y
sudo apt-get update
sudo apt-get install dotnet-sdk-2.1 -y
```

It gave me an error

> The following packages have unmet dependencies:
>  dotnet-sdk-2.1 : Depends: dotnet-runtime-2.1 (>= 2.1.5) but it is not going to be installed
>                   Depends: aspnetcore-runtime-2.1 (>= 2.1.5) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

**Comment by MaximoTrinidad** [comment]
Just an FYI

The issue also exist with WSL - Ubuntu 18.04.

```
maxt@sapien01:~$ sudo apt-get install dotnet-sdk-2.1
[sudo] password for maxt:
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.1
E: Couldn't find any package by glob 'dotnet-sdk-2.1'
E: Couldn't find any package by regex 'dotnet-sdk-2.1'
```

![wsl_ubuntu1804_netcore_issue_2018-11-13_14-40-15](https://user-images.githubusercontent.com/19892435/48439362-1cb9ae00-e754-11e8-8ae3-f6877130179a.jpg)

**Comment by jerryno6** [comment]
I've just created a new VM running ubuntu 18.04
And followed these steps. https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/sdk-current
Everything worked well.

**Comment by leecow** [comment]
This is an interesting problem. When a customer sets up a distro for dotnet packages, the package repo registration will be version specific - 16.04/Xenial in this case. When the machine undergoes a major update (Ubuntu 16.04 -> 18.04), the dotnet core package repo definition is still pointing to the previous repo. 

The ultimate solution will be have .NET Core be present in the Canonical archives but that's a little ways off yet. Another option would be to install .NET Core using the available Snap rather than the package manager. This will set up automatic maintenance of the .NET Core installation through the Snap subsystem and should not be perturbed by an underlying OS update.

/cc @dagood @dleeapho
