### ISSUE TITLE
Update Runtime dependency on openssl1.1 

### ISSUE THREAD

**Issue by rakeshsinghranchi** [dotnet/core-setup#4731]
Related changes in corefx : 
https://github.com/dotnet/corefx/pull/32006
https://github.com/dotnet/corefx/commit/901ff58aee521984e8791f9f7d51fabfd31f910e

For 3.0 .NET Core OpenSSL prerequisites from OpenSSL 1.0 to OpenSSL 1.1 (Runtime will work with whichever is found ).

**Comment by dagood** [comment]
OpenSSL 1.1 availability in the default repositories depends on distro. DistroWatch has nice summaries that include the version of this package, so I went through each package we produce and checked the page:

* deb
  * [Debian](https://distrowatch.com/table.php?distribution=debian)
    * `debian.8` ✖️
    * `debian.9` ✔️
  * [Ubuntu](https://distrowatch.com/table.php?distribution=ubuntu)
    * `ubuntu.14.04` ✖️
    * `ubuntu.16.04` ✖️
    * `ubuntu.18.04` ✔️ 
* rpm
  * [CentOS](https://distrowatch.com/table.php?distribution=centos)
    * `centos.7` ✖️
  * [Fedora](https://distrowatch.com/table.php?distribution=fedora)
    * `fedora.27` ✔️ 
  * [openSUSE](https://distrowatch.com/table.php?distribution=opensuse)
    * `opensuse.42` ✖️
  * [Oracle Linux](https://distrowatch.com/table.php?distribution=oracle)
    * `oraclelinux.7` ✖️ 
  * [Red Hat](https://distrowatch.com/table.php?distribution=redhat)
    * `rhel.7` ✖️
  * [SUSE Linux Enterprise](https://distrowatch.com/table.php?distribution=sle)
    * `sles.12` ✖️

I'm going to try upgrading the ones with a ✔️ (where it looks like openssl 1.1 is available in the default repositories for that distro/version).

/cc @leecow

**Comment by omajid** [comment]
Just as an FYI, we are working on adding OpenSSL 1.1 support to 2.1 and 2.2 as well: https://github.com/dotnet/corefx/pull/34443. Not sure if that means any changes to 2.1 are needed (or even wanted).

**Comment by dagood** [comment]
Thanks for the link! Submitted PR https://github.com/dotnet/core-setup/pull/5046 to make this change in `master` and filed https://github.com/dotnet/core-setup/issues/5047 for 2.1/2.2.

**Comment by dagood** [comment]
Closing this, based on the principle from https://github.com/dotnet/core-setup/pull/5046 that this is being done for new distros and where necessary, but there is no pressing need to make this change to established packages.
