### ISSUE TITLE
Cannot install dotnet-sdk-2.1 on Ubuntu 18.04.1

### ISSUE THREAD

**Issue by rakeshsinghranchi** [dotnet/core-setup#4732]
_From @JerryBian on July 28, 2018 2:54_

# fail to install latest dotnet-sdk on Ubuntu 18.04.1

I just tried to install latest dotnet SDK 2.1 on fresh clean Ubuntu 18.04.1, well, it fails and I didn't find solution yet.

# Details

I followed the official tutorial https://www.microsoft.com/net/learn/get-started-with-dotnet-tutorial, under Ubuntu 18.04 section.

<img width="901" alt="jietu20180728-104449" src="https://user-images.githubusercontent.com/1439095/43352325-8455b464-9254-11e8-91c7-16d5e27ced99.png">
<img width="1173" alt="jietu20180728-104725" src="https://user-images.githubusercontent.com/1439095/43352328-8e28c166-9254-11e8-8770-2c1e0b685d38.png">

Any idea?

_Copied from original issue: dotnet/core#1822_

**Comment by rakeshsinghranchi** [comment]
_From @mateti on July 29, 2018 22:17_

I'm getting this error on 18.04.1:

ngadmin@pocvm4:/tmp$ sudo dpkg -i packages-microsoft-prod.deb
[sudo] password for ngadmin:
(Reading database ... 208777 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-ubuntu18.04.1) over (1.0-ubuntu18.04.1) ...
Setting up packages-microsoft-prod (1.0-ubuntu18.04.1) ...

ngadmin@pocvm4:/tmp$ sudo apt-get install apt-transport-https
Reading package lists... Done
Building dependency tree
Reading state information... Done
apt-transport-https is already the newest version (1.6.3).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
ngadmin@pocvm4:/tmp$ sudo apt-get install apt-transport-https
Reading package lists... Done
Building dependency tree
Reading state information... Done
apt-transport-https is already the newest version (1.6.3).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

ngadmin@pocvm4:/tmp$ sudo apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:5 http://ppa.launchpad.net/nginx/stable/ubuntu bionic InRelease
Reading package lists... Done

ngadmin@pocvm4:/tmp$ sudo apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://ppa.launchpad.net/nginx/stable/ubuntu bionic InRelease
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists... Done

ngadmin@pocvm4:/tmp$ sudo apt-get install aspnetcore-runtime-2.1
Reading package lists... Done
Building dependency tree
Reading state information... Done
**E: Unable to locate package aspnetcore-runtime-2.1
E: Couldn't find any package by glob 'aspnetcore-runtime-2.1'
E: Couldn't find any package by regex 'aspnetcore-runtime-2.1'**

**Comment by rakeshsinghranchi** [comment]
_From @leecow on July 30, 2018 17:46_

Hm, everything is definitely on the repo and working. From a quick test ...

```
leecow@lbc-1804:~$ cat /etc/apt/sources.list.d/microsoft-prod.list 
deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main

leecow@lbc-1804:~$ sudo apt install dotnet-sdk-2.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  aspnetcore-runtime-2.1 dotnet-host dotnet-hostfxr-2.1 dotnet-runtime-2.1 dotnet-runtime-deps-2.1
  liblttng-ust-ctl4 liblttng-ust0 liburcu6
The following NEW packages will be installed:
  aspnetcore-runtime-2.1 dotnet-host dotnet-hostfxr-2.1 dotnet-runtime-2.1 dotnet-runtime-deps-2.1 dotnet-sdk-2.1
  liblttng-ust-ctl4 liblttng-ust0 liburcu6
0 upgraded, 9 newly installed, 0 to remove and 18 not upgraded.
Need to get 128 MB of archives.
After this operation, 375 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
```
@mateti - your `apt-get update` output is suspicious as `package.microsoft.com` is not listed among the hits. 

@JerryBian - do you have any preview versions installed? There was an issue with previous packages getting in the way of dependency resolution. You can check this with `apt search dotnet | grep installed`

**Comment by rakeshsinghranchi** [comment]
_From @JerryBian on July 31, 2018 0:49_

@leecow thanks for you reply, but it seems something is still wrong.
```
jerry@ubuntu-server-0:~$ apt search dotnet | grep installed

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

jerry@ubuntu-server-0:~$ cat /etc/apt/sources.list.d/microsoft-prod.list
deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main
jerry@ubuntu-server-0:~$ sudo apt install dotnet-sdk-2.1
[sudo] password for jerry:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.1 : Depends: dotnet-runtime-2.1 (>= 2.1.2) but it is not going to be installed
                  Depends: aspnetcore-runtime-2.1 (>= 2.1.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
It should not has any previous version installed, since I downloaded latest version of Ubuntu from their portal and then followed your tutorial installing dotnet SDK then, nothing else did.

Do you need anything I check for you besides above?

**Comment by rakeshsinghranchi** [comment]
@JerryBian , can you please try installing dotnet-runtime-deps-2.1 and dotnet-runtime-2.1 package separately and share the log here?

**Comment by rakeshsinghranchi** [comment]
_From @JerryBian on July 31, 2018 10:7_

@rakeshsinghranchi please see following:
``` sh
jerry@ubuntu-server-0:~$ sudo apt install dotnet-runtime-deps-2.1
[sudo] password for jerry:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-deps-2.1 : Depends: liblttng-ust0 but it is not installable
E: Unable to correct problems, you have held broken packages.
jerry@ubuntu-server-0:~$ sudo apt install dontnet-runtime-2.1
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dontnet-runtime-2.1
E: Couldn't find any package by glob 'dontnet-runtime-2.1'
E: Couldn't find any package by regex 'dontnet-runtime-2.1'
```

**Comment by rakeshsinghranchi** [comment]
_From @leecow on July 31, 2018 17:31_

This is strange - what happens with `apt search liblttng-ust0`. My 18.04.1 output is 

```
leecow@lbc-1804:~$ apt search liblttng-ust0
Sorting... Done
Full Text Search... Done
liblttng-ust0/bionic,now 2.10.1-1 amd64 [installed,automatic]
  LTTng 2.0 Userspace Tracer (tracing libraries)
```

**Comment by rakeshsinghranchi** [comment]
Please share output of the following commands to help further diagnose the issue : 
apt-cache policy dotnet-runtime-deps-2.1
apt-cache policy dotnet-runtime-2.1

**Comment by rakeshsinghranchi** [comment]
_From @JerryBian on July 31, 2018 21:26_

@leecow 
```bash
jerry@ubuntu-server-0:~$ apt search liblttng-ust0
Sorting... Done
Full Text Search... Done
```
@rakeshsinghranchi 
```bash
jerry@ubuntu-server-0:~$ apt-cache policy dotnet-runtime-deps-2.1
dotnet-runtime-deps-2.1:
  Installed: (none)
  Candidate: 2.1.2-1
  Version table:
     2.1.2-1 500
        500 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
     2.1.1-1 500
        500 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
     2.1.0-1 500
        500 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
jerry@ubuntu-server-0:~$ apt-cache policy dotnet-runtime-2.1
dotnet-runtime-2.1:
  Installed: (none)
  Candidate: 2.1.2-1
  Version table:
     2.1.2-1 500
        500 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
     2.1.1-1 500
        500 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
     2.1.0-1 500
        500 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
```
P.S. my Ubuntu is server version, instead of desktop(GUI), though I couldn't see what's difference might be.

**Comment by rakeshsinghranchi** [comment]
_From @leecow on July 31, 2018 22:59_

So the fact that liblttng-us0 is not being presented to you is the problem. Looks like the package is probably in [universe amd 64](https://packages.ubuntu.com/search?keywords=liblttng&searchon=names&suite=bionic&section=all) which I don't see in your apt-get "Get" list. Here's the archive list I have on a pretty clean box with the default ubuntu repos active in /etc/apt/sources.list.

```
sudo apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
Get:3 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]          
Get:5 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]                   
Get:6 http://us.archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages [247 kB] 
Get:7 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [268 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 DEP-11 Metadata [138 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu bionic-updates/main DEP-11 48x48 Icons [31.4 kB]
Get:10 http://us.archive.ubuntu.com/ubuntu bionic-updates/main DEP-11 64x64 Icons [53.7 kB]
Get:11 http://us.archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [153 kB]    
Get:12 http://security.ubuntu.com/ubuntu bionic-security/main amd64 DEP-11 Metadata [204 B]
Get:13 http://us.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [152 kB]        
Get:14 http://us.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 DEP-11 Metadata [149 kB]
Get:15 http://us.archive.ubuntu.com/ubuntu bionic-updates/universe DEP-11 48x48 Icons [153 kB]
Get:16 http://us.archive.ubuntu.com/ubuntu bionic-updates/universe DEP-11 64x64 Icons [263 kB]
Get:17 http://us.archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 DEP-11 Metadata [2,464 B]
Get:18 http://us.archive.ubuntu.com/ubuntu bionic-backports/universe amd64 DEP-11 Metadata [5,100 B]
Get:19 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 DEP-11 Metadata [4,448 B]
Fetched 1,867 kB in 1s (1,748 kB/s)                                     
Reading package lists... Done
```

**Comment by rakeshsinghranchi** [comment]
_From @JerryBian on August 1, 2018 13:31_

Thanks very much, after I enabled `universe` repository everything is good.

**Comment by dagood** [comment]
Closing. The fix for the original report is complete:

> should `sudo add-apt-repository universe` be added to the install instructions (or as a comment) for Ubuntu 18.04?

(It is now. 😄)

The other issue reported on this thread about the wrong package feed being set isn't related, but also has some workaround steps on the download page now to fix up after a distro release upgrade.
