### ISSUE TITLE
Offer to uninstall older unsupported .NET Core SDK versions when installing a newer version

### ISSUE THREAD

**Issue by danroth27** [dotnet/core-setup#4755]
.NET Core SDK versions tend to accumulate over time since they all install side by side. Uninstalling all of the older unsupported versions is pretty tedious. It would be nice if the installer at least offered an option to do this for you. That way when you install the latest patch it could also clean out the unpatched versions. I would be worth considering doing this by default and then having an option that you could uncheck to leave older versions around.

**Comment by vitek-karas** [comment]
@livarcocc

**Comment by nguerrera** [comment]
In-progress: Patches will be auto-upgraded by default beginning in an upcoming 3.0 preview.

https://github.com/dotnet/core-sdk/pull/530

**Comment by nguerrera** [comment]
cc @dagood as the runtime bundle will also be doing this.

**Comment by nguerrera** [comment]
Are we using different issue(s) to track this work?

**Comment by dagood** [comment]
Yeah, closing this in favor of https://github.com/dotnet/core-setup/issues/4188. It's from earlier, and its title matches the plan more directly.
