### ISSUE TITLE
Flipping the GUI subsystem bit on apphost causes runtime startup diagnostics to be lost

### ISSUE THREAD

**Issue by jkotas** [dotnet/core-setup#4768]
_From @nguerrera on October 30, 2018 22:11_

Filing this here for now, but I think a fix may require changes to the apphost code itself. 

cc @vitek-karas @sbomer @jeffschwMSFT @peterhuene 

## Repro steps
1. `mkdir wpf`
2. `cd wpf `
3. `dotnet new wpf`
4. Temporarily rename c:\Program Files\dotnet\shared to shared_ (so apphost cannot find runtime)
5. bin\Debug\netcoreapp3.0\wpf.exe
6. Rename shared folder back

## Expected result

An error message like the following for a console app is visible somehow
```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.DesktopUI.App', version '3.0.0-alpha-27026-2' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
```

## Actual result

* App prints nothing to the console, nor displays any UI and returns 0.

_Copied from original issue: dotnet/sdk#2634_

**Comment by 0xd4d** [comment]
I see this when there's not even a dotnet dir:

> A fatal error occurred, the required library hostfxr.dll could not be found.
> If this is a self-contained application, that library should exist in [C:\test\wpf\bin\Release\netcoreapp3.0\publish\].
> If this is a framework-dependent application, install the runtime in the default location [C:\Program Files (x86)\dotnet] or use the DOTNET_ROOT(x86) environment variable to specify the runtime location.

I expect a message box to be shown (it's a UI app) and perhaps a friendlier message so normal users understand it. Eg. not having .NET Core 3.0 installed (or the wrong version) is probably the most common error so it should be shown first. A link to some MS site could be used to show more advanced info (for developers).

**Comment by vitek-karas** [comment]
This is fixed by #4844. `dotnet.exe` will not run into this as it's not GUI enabled. This only affects `apphost` which has this fixed in #4844.

**Comment by wjk** [comment]
In which .NET Core version has/will this fix ship in? I just had to debug this problem myself; it wasn't fun. `dotnet --info` output is below. Thanks!

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-009812
 Commit:    e3abf6e935

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-009812\

Host (useful for support):
  Version: 3.0.0-preview-27122-01
  Commit:  00c5c8bc40

.NET Core SDKs installed:
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009648 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-009812 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-18579-0056 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27122-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-alpha-27128-4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by peterhuene** [comment]
@vitek-karas it looks like it will ship in the next preview for 3.0.
