### ISSUE TITLE
Targeting Pack: netcoreapp nuget

### ISSUE THREAD

**Issue by dleeapho** [dotnet/core-setup#4771]
@dagood checklist:

* [x] Package ID `Microsoft.NETCore.App.Ref`
* [x] Move files into `data/`
* [x] Incorporate commit comments from https://github.com/dotnet/core-setup/compare/master...dagood:3bc8219
* [x] Set PackageType to `Data`

**Comment by dagood** [comment]
Closing as done.

These are now being created by official builds: https://github.com/dotnet/core-setup/pull/5085#issuecomment-461069685. I'll file any problems using the package as bugs.
