### ISSUE TITLE
Targeting Pack: netcoreapp MSI, installers

### ISSUE THREAD

**Issue by dleeapho** [dotnet/core-setup#4772]

**Comment by dagood** [comment]
MSI is complete and building in official builds. I filed:
* https://github.com/dotnet/core-setup/issues/5174 to track a standalone Windows installer (the MSI is not friendly enough for this)
* https://github.com/dotnet/core-setup/issues/5175 for linux packages
* https://github.com/dotnet/core-setup/issues/5176 for MacOS installer
