### ISSUE TITLE
Targeting Pack common infrastructure

### ISSUE THREAD

**Issue by dleeapho** [dotnet/core-setup#4773]
[dagood] https://github.com/dotnet/core-setup/pull/5085#discussion_r253991314 has some thoughts on handling packs similar to `runtime.<rid>.<package id>` packages using the `.builds` infra. Fewer dirs and files that way, maybe more maintainable and easily usable in other repos. (Or replace the infra completely with something simpler.)

List of refactoring ideas from earlier PRs to improve this:

https://github.com/dotnet/core-setup/pull/5114

* Remove `generatemsi.ps1` powershell scripts, use msbuild projects with shared targets.
  * Peek at wixproj, but likely stick with `Exec`s for now.
* Consider unifying targeting pack installer creation with targeting pack pkgproj. This could make the targeting pack creation entry point cleaner.
  * I also want to look into merging `Microsoft.NETCore.App.Ref.pkgproj` into `Microsoft.NETCore.App.pkgproj`, and using it to drive other packs (Runtime, AppHost) as well. Same goal: cleaner entry point.
* Share WiX project files to avoid boilerplate.
* > Another thing to consider is inserting a layout phase between collecting assets and pack. That way the content of the pack can be defined by the layout instead of vice-versa.

**Comment by dagood** [comment]
Closing: this was made common enough that we were able to split off dotnet/windowsdesktop for 5.0. Making an improved version (to make it more reasonable to onboard new repos) is tracked at https://github.com/dotnet/arcade/issues/2704.
