### ISSUE TITLE
Localized runtime installers and packages

### ISSUE THREAD

**Issue by dleeapho** [dotnet/core-setup#4781]

**Comment by dagood** [comment]
Closing: at a basic level, translated WXL files are in. We plan to run more validation (e.g. layout clipping), and I'll open new more specific issues with what needs fixing.

I'll leave the epic (https://github.com/dotnet/core-setup/issues/4783) open, though, until we're satisfied with the state for 3.0.

(From the title, this issue may have also been tracking transporting e.g. WinForms resource DLLs through to the install location and downstream repos. That has already been done.)
