### ISSUE TITLE
API-MS-Win-core-xstate-l2-1-0.dll is missing authenticode signatures in daily builds in win-x86 builds

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/core-setup#4797]
## Steps to reproduce
Run [signcheck](https://github.com/dotnet/arcade/tree/master/src/SignCheck) against http://dotnetcli.blob.core.windows.net/dotnet/Runtime/3.0.0-preview-27117-01/dotnet-runtime-3.0.0-preview-27117-01-win-x86.zip.
```
microsoft.dotnet.signcheck.exe --recursive -i dotnet-runtime-3.0.0-preview-27117-01-win-x86.zip
```

## Expected  behavior
All files should be code signed.

## Actual behavior
Signcheck fails with.

```
[File] 39d497240d18b355fa777f74fa5fb768.dll, Signed: False, Full Name: shared/Microsoft.NETCore.App/3.0.0-preview-27117-01/API-MS-Win-core-xstate-l2-1-0.dll [Error] HRESULT: 800b0100 (No signature was present in the subject)

```

**Comment by dagood** [comment]
Related: https://github.com/dotnet/core-setup/issues/5254 for adding signing validation to Core-Setup's build.

**Comment by dleeapho** [comment]
@dagood please check with a current build and follow up with @natemcmaster .

**Comment by dagood** [comment]
Works on a recent build:

```
#> C:\tools\SignCheck\Microsoft.DotNet.SignCheck.exe --recursive -i .\dotnet-runtime-3.0.0-preview6-27701-05-win-x86.zip
Starting execution of SignCheck.

Results

[File] dotnet-runtime-3.0.0-preview6-27701-05-win-x86.zip, Skipped (unsupported file type), Signed: N/A

All files are signed.
Total Time: 00:00:06.2890326
Total Files: 226, Signed: 221, Unsigned: 0, Skipped: 5, Excluded: 0, Skipped & Excluded: 0
```

We could mimic dev usage of SignCheck in our build. (Just download the nupkg, extract, and use it.) Adding that to #5254.
