### ISSUE TITLE
ADDITIONAL_DEPS failure reported in .NetCore 2.1

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/core-setup#4811]
Moved from https://github.com/aspnet/AspNetCore/issues/3523

Reported by @tobyash86:
"My project is injecting an external library as a dependency for the CoreCLR profiler. It uses ADDITIONAL_DEPS environment variable to achieve that. Everything works well as long as ASP.NET Core 2.0 web application is profiled, but if I use exactly the same workflow with ASP.NET Core 2.1 my library is not found by the application."

@pkruk2 please add the repro steps here to repro the issue using dotnet console application. Thanks.

**Comment by pkruk2** [comment]
### Attaching files:
1. Hooks.zip - a simple .net framework 2.0 project. After compilation it will produce Hooks.dll that should be used in ADDITIONAL_DEPS. (The project was simply created with VS 2017 template and contains only default "Class1.cs" file)
2. NetCoreConsoleApp.zip - a simple .net core 2.1 console application, consisting of 3 projects, and printing "hello" to console. It contains 2 publish profiles too. 
3. scripts.zip - a simple scripts for running the application without ADDITIONAL_DEPS (the *_Vanillla.bat) and with it (the others)

As you can see everything is "simple" ;)
 
### How to repro:

1. Unpack Hooks.zip somewhere, compile it
2. Unpack NetCoreConsoleApp.zip, open it with VS 2017, 
- compile it normally
- publish NetCoreConsoleApp using both profiles (you may need to update Target Location)
3. Unpack scripts zip somewhere, update paths in the files:
- hooks.deps.json: path to Hooks.dll
- all *.bat files: path to NetCoreConsoleApp
- *_Vanilla.bat files: path to hooks.deps.json
4. Run the bat scripts

### Actual results on my machine

1. Running without ADDITIONAL_DEPS works without problems - the application prints to console:

`
D:\dv\coverage\repro>run_DeveloperBuild_Vanilla.bat
D:\dv\coverage\repro>set DOTNET_ADDITIONAL_DEPS=
D:\dv\coverage\repro>dotnet.exe "C:\Users\pkruk\Documents\Visual Studio 2017\Projects\NetCoreConsoleApp\NetCoreConsoleApp\bin\Debug\netcoreapp2.1\NetCoreConsoleApp.dll"
Hello World!
HEllo from Net Core Library
Hello from net standard library

D:\dv\coverage\repro>run_FrameworkDependentPortable_Vanilla.bat
D:\dv\coverage\repro>set DOTNET_ADDITIONAL_DEPS=
D:\dv\coverage\repro>dotnet.exe "C:\Users\pkruk\Documents\Visual Studio 2017\Projects\NetCoreConsoleApp\publish\bin\Debug\netcoreapp2.1\publish-framework_dependent-portable\NetCoreConsoleApp.dll"
Hello World!
HEllo from Net Core Library
Hello from net standard library

D:\dv\coverage\repro>run_SelfContainedWinX86_Vanilla.bat
D:\dv\coverage\repro>set DOTNET_ADDITIONAL_DEPS=
D:\dv\coverage\repro>"C:\Users\pkruk\Documents\Visual Studio 2017\Projects\NetCoreConsoleApp\publish\bin\Debug\netcoreapp2.1\publish-self_contained-win_x86\NetCoreConsoleApp.exe"
Hello World!
HEllo from Net Core Library
Hello from net standard library
`

2. Running with ADDITIONAL_DEPS does not work for published Framework Dependent:

`
D:\dv\coverage\repro>run_DeveloperBuild_AdditionalDeps.bat
D:\dv\coverage\repro>set DOTNET_ADDITIONAL_DEPS=D:\dv\coverage\repro\hooks.deps.json
D:\dv\coverage\repro>dotnet.exe "C:\Users\pkruk\Documents\Visual Studio 2017\Projects\NetCoreConsoleApp\NetCoreConsoleApp\bin\Debug\netcoreapp2.1\NetCoreConsoleApp.dll"
Hello World!
HEllo from Net Core Library
Hello from net standard library

**D:\dv\coverage\repro>run_FrameworkDependentPortable_AdditionalDeps.bat
D:\dv\coverage\repro>set DOTNET_ADDITIONAL_DEPS=D:\dv\coverage\repro\hooks.deps.json
D:\dv\coverage\repro>dotnet.exe "C:\Users\pkruk\Documents\Visual Studio 2017\Projects\NetCoreConsoleApp\publish\bin\Debug\netcoreapp2.1\publish-framework_dependent-portable\NetCoreConsoleApp.dll"
Error:
  An assembly specified in the application dependencies manifest (hooks.deps.json) was not found:
    package: 'Hooks', version: '1.0.0.0'
    path: 'C:/Users/pkruk/Documents/Visual Studio 2017/Projects/Hooks/Hooks/bin/Debug/Hooks.dll'**

D:\dv\coverage\repro>run_SelfContainedWinX86_AdditionalDeps.bat
D:\dv\coverage\repro>set DOTNET_ADDITIONAL_DEPS=D:\dv\coverage\repro\hooks.deps.json
D:\dv\coverage\repro>"C:\Users\pkruk\Documents\Visual Studio 2017\Projects\NetCoreConsoleApp\publish\bin\Debug\netcoreapp2.1\publish-self_contained-win_x86\NetCoreConsoleApp.exe"
Hello World!
HEllo from Net Core Library
Hello from net standard library
`

The Hooks.dll of course exists:
`
D:\dv\coverage\repro>dir "C:/Users/pkruk/Documents/Visual Studio 2017/Projects/Hooks/Hooks/bin/Debug/"
 Directory of C:\Users\pkruk\Documents\Visual Studio 2017\Projects\Hooks\Hooks\bin\Debug
2018-11-30  12:05    <DIR>          .
2018-11-30  12:05    <DIR>          ..
2018-11-30  12:05             4 096 Hooks.dll
2018-11-30  12:05             9 728 Hooks.pdb
               2 File(s)         13 824 bytes
               2 Dir(s)  48 490 582 016 bytes free
`

Also, I noticed following:

`
D:\dv\coverage\repro>dotnet --version
Error:
  An assembly specified in the application dependencies manifest (hooks.deps.json) was not found:
    package: 'Hooks', version: '1.0.0.0'
    path: 'C:/Users/pkruk/Documents/Visual Studio 2017/Projects/Hooks/Hooks/bin/Debug/Hooks.dll'
`
### My setup

Installed SDKs and runtimes may have impact here:

`
D:\dv\coverage\repro>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
`

Please tell me if you need more info.

### Finally

In https://github.com/aspnet/AspNetCore/issues/3523#issuecomment-441602443 I wrote

> I have checked and the same problem happens with normal .net core console application which is published.
> 
>     * When it's published with Deployment Mode "Framework Dependent" and Target Runtime "Portable", you can workaround it by putting hooks.dll in the Target Location
> 
>     * When it's published with Deployment Mode "Self-contained" and Target Runtime "win-x86", the workaround does not work

But when I prepared this repro, it worked when publishing in Self-contained/win-x86 (while still not working when publishing for Framework Dependent/Portable). I do not know why there is such difference. But maybe it is not important right now, and investigating the Self-contained case will also resolve the Framework Dependent case.

**Comment by swaroop-sridhar** [comment]
Thanks for the detailed instructions, @pkruk2.
I don't see the attachments.

**Comment by pkruk2** [comment]
@swaroop-sridhar I am sorry, it seems I forgot to attach the most important part of the repro ;)
Attaching now.

[Hooks.zip](https://github.com/dotnet/core-setup/files/2638856/Hooks.zip)
[NetCoreConsoleApp.zip](https://github.com/dotnet/core-setup/files/2638855/NetCoreConsoleApp.zip)
[scripts.zip](https://github.com/dotnet/core-setup/files/2638854/scripts.zip)

**Comment by swaroop-sridhar** [comment]
@pkruk2  I was not able repro a failure in your test case.
One issue with your test case is that your scripts set `ADDITIONAL_DEPS` but not `additionalprobingpaths`, which caused failures loading `hooks.dll`.

```
> dotnet --additional-deps Hooks\hooks.deps.json NetCoreConsoleApp\NetCoreConsoleApp\bin\Debug\netcoreapp2.1\publish\NetCoreConsoleApp.dll
Error:
  An assembly specified in the application dependencies manifest (hooks.deps.json) was not found:
    package: 'Hooks', version: '1.0.0.0'
```

However, if I specify the additional probing paths, then the test works OK:

```
> dotnet --additional-deps Hooks\hooks.deps.json  --additionalprobingpath  Hooks\Hooks\bin\Debug\Hooks.dll NetCoreConsoleApp\NetCoreConsoleApp\bin\Debug\netcoreapp2.1\publish\NetCoreConsoleApp.dll
```

Also, if `Hooks.dll` is in the same path as `NetCoreConsoleApp.dll` we don't need the probing-path specification:

```
> copy Hooks\Hooks\bin\Debug\Hooks.dll  NetCoreConsoleApp\NetCoreConsoleApp\bin\Debug\netcoreapp2.1\publish\
        1 file(s) copied.

> dotnet --additional-deps Hooks\hooks.deps.json NetCoreConsoleApp\NetCoreConsoleApp\bin\Debug\netcoreapp2.1\publish\NetCoreConsoleApp.dll
Hello World!
HEllo from Net Core Library
Hello from net standard library
```

Similarly for self-contained published app:

```
NetCoreConsoleApp\NetCoreConsoleApp\bin\Debug\netcoreapp2.1\win10-x64\publish\NetCoreConsoleApp.exe --additional-deps Hooks\hooks.deps.json
Hello World!
HEllo from Net Core Library
Hello from net standard library
```

```
> copy Hooks\Hooks\bin\Debug\Hooks.dll  NetCoreConsoleApp\NetCoreConsoleApp\bin\Debug\netcoreapp2.1\win10-x64\publish\
        1 file(s) copied.

> NetCoreConsoleApp\NetCoreConsoleApp\bin\Debug\netcoreapp2.1\win10-x64\publish\NetCoreConsoleApp.exe --additional-deps Hooks\hooks.deps.json
Hello World!
HEllo from Net Core Library
Hello from net standard library
```

**Comment by swaroop-sridhar** [comment]
I moved the issue out of .3.0 for now, because there is no actionable repro.
@tobyash86: Is this still a problem for you? on ASP net 2.1?  Thanks.

**Comment by swaroop-sridhar** [comment]
In the original bug from which this issue was spin-off, 
@tobyash86  has reported that setting additional probing paths resolves the load issue.
Therefore closing this issue, since there is nothing actionable remaining.

**Comment by tobyash86** [comment]
--additionalprobingpath solves error which was printed on a console but does not solve my primary requirement regarding dynamic assembly injection as --additionalprobingpath has to be specified as dotnet.exe argument or in a runtime config file. I will create a separate issue as a feature request to specify additional probing paths as an environment variable.
