### ISSUE TITLE
build is modifying the path and/or NuGet.Config is being changed

### ISSUE THREAD

**Issue by robertborr** [dotnet/core-setup#4828]
## Steps to reproduce
in build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2248008

12/2/2018 4:59 AM (UTC) : Contents of \\DDVSOWINAGE022\C$\Users\dlab14\AppData\Roaming\NuGet\NuGet.Config changed from <?xml version="1.0" encoding="utf-8"?>

## Expected  behavior
do not modify NuGet.Config or system path

## Actual behavior
NuGet.Config is changed

## Environment data

**Comment by nguerrera** [comment]
That build cannot be found. Do you have repro steps or another build?

I'll close this for now. If you have another build or repro steps, I can reopen. This is almost certainly not the right repo, though, so I'll open it at the right place when I have more details.
