### ISSUE TITLE
 .NET Core 3 Preview 1 installation wrong wording

### ISSUE THREAD

**Issue by OliaG** [dotnet/core-setup#4830]
We should update text in the installer to say .NET Core 3.0 instead of 2.2 and update recommended VS to 2019 Preview 1

![1](https://user-images.githubusercontent.com/31997351/49479179-f2996000-f7d6-11e8-9724-bce7c4472f83.jpg)

**Comment by terrajobst** [comment]
Was fixed in 90d7ea73d7a8a9c3fe7c4aff40cfe4721ca3d7a0.
