### ISSUE TITLE
Make .NET Core 3 installer HDPI aware

### ISSUE THREAD

**Issue by OliaG** [dotnet/core-setup#4840]
Right now the installer window is blurry on >100% display settings. We should make it HDPI aware. 
![image](https://user-images.githubusercontent.com/31997351/49608305-24343780-f94d-11e8-8f74-6a8ce614a027.png)

**Comment by rakeshsinghranchi** [comment]
Related : https://github.com/dotnet/core-setup/issues/3049

**Comment by dleeapho** [comment]
Dupe of #3049
