### ISSUE TITLE
The url of `.NET Core prerequisites` is never point to the right page

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/core-setup#4868]
## Steps to reproduce
I hit the same issue as #3521, #4388, and etc when install netcore.

And found that currently error message
```
//Copy from #3521, maybe not extra the same

Failed to load the dll from [?O], HRESULT: 0x8007007E
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\2.0.3\hostfxr.dll failed
  - Installing .NET Core prerequisites might help resolve this problem.
    http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

https://github.com/dotnet/core-setup/blob/9a776be820ff4ae83476c7e9e97514ecd8f3ae1d/src/corehost/corehost.cpp#L263-L269

is still point to  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409 , which then jump to https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial.(It's only an helloworld.)

## Expected  behavior
Give some urls to the really docs about `.NET Core prerequisites`.
https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x
https://docs.microsoft.com/en-us/dotnet/core/macos-prerequisites?tabs=netcore2x
https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x

## Actual behavior
The page say nothing about `.NET Core prerequisites`

## Environment data

**Comment by vitek-karas** [comment]
Thanks a lot for reporting this. I'm looking into it.

**Comment by rakeshsinghranchi** [comment]
cc @vivmishra , @leecow as it is related to fwlink.

**Comment by vitek-karas** [comment]
This will have to wait till Jan, people needed to make this change are on holidays.
