### ISSUE TITLE
.net core 2.2 sdk install failed on windows 7 sp1

### ISSUE THREAD

**Issue by OpenGDBX** [dotnet/core-setup#4900]
# Issue Title

.net core 2.2 sdk install failed on windows 7 sp1

# General

 the cabinet file sfx_x64.cab has an invalid digital signature

**Comment by rakeshsinghranchi** [comment]
This issue was moved to dotnet/core-sdk#234

**Comment by Uchiha-Peng** [comment]
I encountered the same problem, but it was solved. Because your computer needs to connect to Microsoft to register a signature when installing the .NET Core environment, you must ensure that your computer is connected to the external network, otherwise this error will occur.
