### ISSUE TITLE
Servicing -- Arcade usage of SemVer 2.0.0 may require dotnet.exe servicing 

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/core-setup#4952]
# Background

Arcade is switching to using SemVer 2.0.0 versioning.  See 
https://semver.org/spec/v2.0.0.html

Which uses the form

```
<major>.<minor>.<patch>{-<prerelease}{+<build_metadata>}
```

Labels have previously taken the form of the following representative sample of recent version labels.  The `<prerelease>` labels are fully sorted by an ascii sort.

```
2.2.0
2.2.0-dependencies
2.2.0-preview1
2.2.0-preview2
2.2.0-preview3
2.2.0-preview3-dependencies
3.0.0-preview-27122-01
```

## Expected behavior

A full SemVer 2.0.0 implementation would sort the following version labels in the order below.
```
1.2.3-1
1.2.3-1.1
1.2.3-1.A
1.2.3-9
1.2.3-10
1.2.3-1A
1.2.3
```

## Actual behavior

Dotnet.exe assumes the `<prerelease>` field can use a simple ASCII sort.  this results in the following order.

```
1.2.3-1
1.2.3-1.1
1.2.3-1.A
1.2.3-10
1.2.3-1A
1.2.3-9
1.2.3
```

### Service dotnet.exe

Add full support for SemVer 2.0.0 to hostfxr and dotnet.exe.  **Service dotnet.exe**.

### Constrain arcade version numbers for hostfxr

If we constrain the hostfxr version number such that their `<prerelease>` tags are sorted correctly by an ascii sort.  

#### Maintain only SemVer 2.0.0 parser

Add full support for SemVer 2.0.0 to hostfxr and dotnet.exe.  **Do not service dotnet.exe**.

#### Maintain old and new parser

Add full support for SemVer 2.0.0 to hostfxr.
Use existing parser for dotnet.exe.  **Do not service dotnet.exe**.

### Constrain arcade version numbers for hostfxr and all runtimes.

If we constrain hostfxrand runtime version number such that their `<prerelease>` tags are sorted correctly by an ascii sort.  

Use existing parser for hostfxr and dotnet.exe.  **Do not service dotnet.exe**.

**Comment by sdmaclea** [comment]
/cc @dleeapho @livarcocc @vitek-karas @jkotas @nguerrera @jeffschwMSFT @terrajobst 

Per earlier API review discussions, this should be marked `api-work-needed`, but the label does not yet exist in this repo.  I am happy to add the label if it is helpful.

**Comment by nguerrera** [comment]
I think we should leave the versioning scheme for runtime, hostfxr, and sdk alone for 3.0. Every time something has adopted arcade and changed to semver v2 mid-cycle, there has been fallout from versioning numbers appearing to go backwards. I think we should wait until a future release to switch and switch in a coordinated way at the very beginning of the release.

Note that there is also C# code ported from fxver_t in the msbuild sdk resolver that will also have to change for this.

**Comment by danmosemsft** [comment]
Removed `servicing-consider` - that label is only to put on a servicing PR to ask shiproom to merge it ...

**Comment by sdmaclea** [comment]
@danmosemsft Thanks.  During API discussion, we were asked to treat all dotnet.exe the same as service changes, because they would effectively change all runtimes since only one dotnet.exe would be used.  Not sure how to tag this....

**Comment by danmosemsft** [comment]
That makes sense. You can use some new label or set the milestone to 2.2.x or anything else that works for you but servicing-consider has a specific meaning which is "shiproom please look at this PR today"

**Comment by sdmaclea** [comment]
> Note that there is also C# code ported from fxver_t in the msbuild sdk resolver that will also have to change for this.

I could not find the related code.  I guessed it was moved into `Microsoft.Build.NuGetSdkResolver` by @rainersigwald, but still couldn't find it...

**Comment by sdmaclea** [comment]
> I think we should leave the versioning scheme for runtime, hostfxr, and sdk alone for 3.0

Seems safest.

**Comment by jeffschwMSFT** [comment]
>>I think we should leave the versioning scheme for runtime, hostfxr, and sdk alone for 3.0

> Seems safest.

+@markwilkie for visibility.  One challenge we have is that some of our components have already started to adopt Semv2 (ones that do not require host modification).  Are we going to be able to ship a consistent product in that world?

cc @livarcocc

**Comment by nguerrera** [comment]
> I could not find the related code

It's in the resolver plugin to msbuild produced in the cli repo:

https://github.com/dotnet/cli/blob/f38d1472d05573158f52ec30f5163fe0316ede7b/src/Microsoft.DotNet.MSBuildSdkResolver/FXVersion.cs#L9

**Comment by sdmaclea** [comment]
>> I think we should leave the versioning scheme for runtime, hostfxr, and sdk alone for 3.0

> Seems safest.

Jeff just commented that @nguerrera's comment might not have been obvious to all readers and that my comment seemed to indicate the discussion was closed.

For an example of what can and has gone wrong.  @jeffschwMSFT showed https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Runtime.WindowsRuntime.
The most recent build 1/14/2019 has the label `4.6.0-preview.19064.1`.  The most recent build per SemVer 2.0.0 rules is `4.6.0-preview1-27018-01` which was built 10/2018 the last build before switching to SemVer2.0.0 numbering.  Unfortunately, when the switch happened the `<major>.<minor>.<patch>` all stayed the same and the `{-<prerelease}` suffix was not carefully selected to have the correct ordering.

Since we have a `3.0.0` prerelease using SemVer1.0 version,  it is safest to not also ship a `3.0.0` prerelease with SemVer 2.0.0 numbering.  We could release as `3.0.1`, `3.1.0`, or `4.0.0`.

There are two separate issues
1. When do we switch versioning of runtime, hostfxr, sdk, and framework to SemVer 2.0.0
2. When do we add support for SemVer 2.0.0 to hostfxr and dotnet

The current plan is to add support for hostfxr and dotnet in the near term, so that we are ready to switch versioning of runtime, hostfxr, sdk, and framework at the next opportune time.
