### ISSUE TITLE
Waiting for v2.1.7-dependencies tag

### ISSUE THREAD

**Issue by vellozzi** [dotnet/core-setup#4962]
We're waiting on the v2.1.7-dependencies tag so we can build 2.1.7.
Are you still following the "-dependencies" convention for this repo?  Can you give an ETA?

**Comment by dagood** [comment]
@leecow @wtgodbe are you the right people to ask about status?

It looks like dependency update PRs are merged, but `v2.1.7-dependencies` tags aren't pushed to any of the core repos.

**Comment by wtgodbe** [comment]
Hey, was waiting to hear back from @mmitche on a couple questions before I pushed the tags, but the questions are lateral enough that I can just push them now.

**Comment by wtgodbe** [comment]
Tags are up, closing. Sorry for the delay!
