### ISSUE TITLE
Unable to embed compatibility section of application manifest in .exe generated by .NET Core 3.0.100-preview-009817

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#4963]
@SteveL-MSFT commented on [Thu Jan 10 2019](https://github.com/dotnet/core-sdk/issues/267)

For PowerShell Core 6.0, we embed an application manifest to enable .NET Core compatibility settings.  This works for our exe built against .NET Core 2.1, but fails for the same code retargeting netcoreapp30:

This is the exe built as netcoreapp30:
```output
c:\Program Files (x86)\Windows Kits\10\bin\x64>mt -manifest C:\Users\slee\repos\PowerShell\assets\pwsh.manifest -updateresource:C:\Users\slee\repos\PowerShell\src\powershell-win-core\bin\Release\netcoreapp3.0\win7-x64\publish\pwsh.exe;#1
Microsoft (R) Manifest Tool
Copyright (c) Microsoft Corporation.
All rights reserved.

mt : general error c101008d: Failed to write the updated manifest to the resource of file "C:\Users\slee\repos\PowerShell\src\powershell-win-core\bin\Release\netcoreapp3.0\win7-x64\publish\pwsh.exe". The parameter is incorrect.
```

Using same manifest for same exe built as netcoreapp21:
```output
c:\Program Files (x86)\Windows Kits\10\bin\x64>mt -manifest C:\Users\slee\repos\PowerShell\assets\pwsh.manifest -updateresource:C:\Users\slee\desktop\pwsh.exe;#1
Microsoft (R) Manifest Tool
Copyright (c) Microsoft Corporation.
All rights reserved.
```

sigcheck from sysinternals confirms the application manifest is embedded correctly in the second case.  The [manifest file](https://github.com/PowerShell/PowerShell/blob/master/assets/pwsh.manifest) is from our repo.  The `trustInfo` section is able to be embedded, just not the `compatibility` section.

---

@livarcocc commented on [Fri Jan 11 2019](https://github.com/dotnet/core-sdk/issues/267#issuecomment-453652483)

@jeffschwMSFT can you take a look at this? I am not sure the SDK is playing a role here.

---

@jeffschwMSFT commented on [Fri Jan 11 2019](https://github.com/dotnet/core-sdk/issues/267#issuecomment-453653137)

@livarcocc can you help move this issue to core-setup?  I do not have sufficient write permissions in this repo.

**Comment by vitek-karas** [comment]
Thanks @SteveL-MSFT somebody on our side will have to take a look and try to repro this.

**Comment by vitek-karas** [comment]
I tried this using your branch (netcore3.0):
* Using `-crossgen` doesn't work for me, it complains that "Jit Compiler has wrong version identifier" - not sure if this is an issue with the 3.0 preview package or something else. I ran it without `-crossgen`.
* As is it produces binary which has the "default" manifest without the `compatiblity` section.
* I added this to the `powershell-win-core.csproj` `PropertyGroup` section:
``` xml
<ApplicationManifest>..\..\assets\pwsh.manifest</ApplicationManifest>
```
Rebuilt and now the binary `pwsh.exe` has the "full" manifest with the `compatibility` section.

Can you please try this on your end to see if this works as well. Let me know if this would work for you then.

Note: I also could not run `sigcheck` as it complained it can't find the tool - not sure if it's part of the repo or I need it installed from something else.

**Comment by SteveL-MSFT** [comment]
@vitek-karas thanks for looking into this.  I tried moving the `<ApplicationManfest>` element from PowerShell.Common.Props which is imported by powershell-win-core.csproj and it still didn't work for me.  What version of the .Net Core 3.0 SDK are you using?  Don't worry about crossgen, it's not necessary for the repro.  [sigcheck](https://docs.microsoft.com/en-us/sysinternals/downloads/sigcheck) is a SysInternals tool.  You can just start the built pwsh (run: `&(get-psoutput)` assuming you're using `build.psm1`) and use `[Environment]::OSVersion` to see if it reports 10.0 or 6.2 (expecting 10.0 due to compatibility flags).  If you're using a fork, can you share that branch so I can try building yours?

**Comment by vitek-karas** [comment]
I have a branch with the fix here: [FixWinManifest](https://github.com/vitek-karas/PowerShell/tree/FixWinManifest)
(it's a fork from the netcore3.0 PR branch).

I verified that it works with the `sigcheck` as described above.

Per `dotnet --info` which I run from the powershel directory it says it's using:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-009817
 Commit:    79838fe30c
```
I do have a slightly older 3.0 preview installed in the global location, but that should not have any effect really as the SDK above should be used for the build.

**Comment by vitek-karas** [comment]
Glad to help... 
The difference does look like a BOM, but it should not make a difference. The OS should be reading this with a conformant XML parser and it should  be able to handle the BOM just fine (sigcheck won't since it displays it as text I assume).

**Comment by vitek-karas** [comment]
Seems resolved as far as I can tell. Please reopen if this is still an issue.
