### ISSUE TITLE
Tizen Core-Setup nuget package version for master in dotnet/version

### ISSUE THREAD

**Issue by gbalykov** [dotnet/core-setup#4987]
## Steps to reproduce

We build nuget packages for CoreCLR/CoreFX/Core-Setup based on the updates of `dotnet/version` repo (specifically, https://github.com/dotnet/versions/tree/master/build-info/dotnet/core-setup/master for core-setup master). 

For Core-Setup the last update of `master` was on 29th of December with version `preview-27218-01`, however, both CoreCLR and CoreFX version have been updated regularly since then. 

Now, CoreFX `preview.19065.1` requires Core-Setup `preview-27218-01`, but we have not built it, as there were no changes in `dotnet/versions`.

Has the version update process changed?

cc @alpencolt

**Comment by gbalykov** [comment]
cc @jkotas

**Comment by dleeapho** [comment]
@gbalykov is this for Tizen build triggering?

**Comment by gbalykov** [comment]
@dleeapho yes, forgot to add info

**Comment by dleeapho** [comment]
@dagood per our discussion we can either reinstate the dotnet/version info or look at how maestro++/BAR infrastructure can provide this info. /cc @markwilkie

**Comment by dagood** [comment]
Filed https://github.com/dotnet/arcade/issues/1818 to see how this will work with BAR. I'm taking this issue to turn on dotnet/versions publishing again (if there isn't a quick and easy answer to how to use BAR).

**Comment by gbalykov** [comment]
@dagood `Latest.txt` doesn't seem to be updated now for core-setup master

**Comment by dagood** [comment]
I worked around the issue I was seeing with PR https://github.com/dotnet/core-setup/pull/5069, and we're starting to get dotnet/versions commits again: https://github.com/dotnet/versions/commits/master/build-info/dotnet/core-setup/master 🎉 

@gbalykov Can you check if those commits are good and will let you get your infra running again?

**Comment by gbalykov** [comment]
@dagood thank you! I see that versions for core-setup are updated now. Same issue seems to be with CoreCLR, as `https://github.com/dotnet/versions/tree/master/build-info/dotnet/coreclr/master` are not updated. Is the reason the same as for core-setup?

**Comment by dagood** [comment]
Sweet, thanks for checking.

Yeah, CoreCLR also hasn't been publishing to dotnet/versions in their yaml builds. Filed https://github.com/dotnet/coreclr/issues/22398 to implement that.
