### ISSUE TITLE
Publish Microsoft.Dotnet.PlatformAbstractions and Microsoft.Extensions.DependencyModel

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#499]
These packages are built in the repo but dont get published to Azure blob (though, they are published to myget).

@wtgodbe Can you please look into fixing this for 1.1.0? And also for 1.0.0 (assuming the issue is present there)?

**Comment by wtgodbe** [comment]
I spoke with Davis, and it sounds like the reason we weren't doing this is that we _only_ want to publish the signed, Windows versions of these packages to myget, so if we were publishing them to Azure from every build, we would wind up with unsigned packages on MyGet. I put up a PR here https://github.com/dotnet/core-setup/pull/500/ that should publish these to Azure, only if we're building & signing on Windows. I'll have to make a couple changes to the build definitions after that goes in as well.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/core-setup/pull/500 solved this in Master, and is already merged. https://github.com/dotnet/core-setup/pull/504 and https://github.com/dotnet/core-setup/pull/503 are up for 1.0.0 and 1.1.0 respectively, and can be merged pending Shiproom approval (once https://github.com/dotnet/core-setup/pull/504 goes in, I'll need to make a change to the 1.0.0 build definitions in MSEng).
