### ISSUE TITLE
The processing message in the CLI 3.0 installer needs to be updated to 3.0 Preview 2.

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/core-setup#5021]
_From @v-lawu on January 22, 2019 8:23_

Install the .NET Core 3.0 Preview 2, the message in processing still shows 3.0.0 Preview 1, it needs to be updated to 3.0 Preview 2.

Screen:
![image](https://user-images.githubusercontent.com/12129698/51521353-5c41fc00-1e61-11e9-800b-9255eb658b7a.png)

_Copied from original issue: dotnet/core-sdk#319_

**Comment by vitek-karas** [comment]
_From @johnbeisner on January 22, 2019 17:56_

The SDK and CLI installers both use: "preview" without a number.

**Comment by dagood** [comment]
Thanks for moving this issue. I submitted PR https://github.com/dotnet/core-setup/pull/5025 to change `Preview 1` to `Preview` in the core-setup installer branding. (Our package prerelease version had this change already, but not the installer branding.)

**Comment by dagood** [comment]
Answered in email, summary: the fix is merged, I'm working on getting a core-setup build complete so core-sdk uptakes an installer with the fix.
