### ISSUE TITLE
RRF_SUBKEY_WOW6432KEY used in SDK lookup implementation only supported on Windows 10

### ISSUE THREAD

**Issue by pakrym** [dotnet/core-setup#5028]
https://github.com/dotnet/core-setup/blob/2f528e5f158aa41789f7967cf8e8b868a8173d95/src/corehost/common/pal.windows.cpp#L243-L247

@vitek-karas @johnbeisner

Added in https://github.com/dotnet/core-setup/pull/4857

**Comment by vitek-karas** [comment]
Thanks for filing a separate issue for this @pakrym.
I'm looking into this (Trying to get a repro to see what happens and also how we can cover this in tests).

**Comment by vitek-karas** [comment]
I verified that this is indeed broken on Windows Server 2012 R2.
Working on adding a test (since we have none even if the tests would run on Windows Server 2012 R2, which they don't - see #5040 for that) and then an actual fix.
