### ISSUE TITLE
Upload symbols to public Msft symbol server and internal server

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#5056]
Some information about expectations is here: https://github.com/dotnet/core-eng/issues/3382.

---

Currently, symbols are published *only* to the public symbol server, and have 365 day retention. To align with expectations:

* [ ] Publish to both the internal and public symbol servers.
* [ ] Retain for 180 days. (If the build is released, this gets extended to 10,950 days.)

**Comment by leecow** [comment]
Add specific todo to this issue.

**Comment by dagood** [comment]
3.0 milestone intended: this blocks daily build validation that requires symbols.
