### ISSUE TITLE
`apphost` doesn't consider registred SDK location to look for hostfxr

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/core-setup#5064]
Make sure that there are not 3.0 versions of .NET core installed in Program Files. (2.* are OK)

Install 3.0 SDK into a custom location - make sure that the `HKLM\Software\dotnet\Setup\InstalledVersion\x64\InstallLocation` points to the installation. (Note that it has to be the 32bit node in the registry, so in registry editor the path should look like `HKLM\Software\WOW6432Node\dotnet\Setup\InstalledVersion\x64\InstallLocation`)

Using this dotnet (either by specifying the full path or using PATH variable)
```
mkdir apphostrepro
cd apphostrepro
dotnet new console
dotnet build
bin\debug\netcoreapp3.0\apphostrepro.exe
```

Expected behavior:
The app runs without issues.

Actual behavior:
The app fails because it either fails to find hosfxr or it loads the hostfxr from Program Files which is the old one. In any case it won't find any available 3.0 framework.

**Comment by sdmaclea** [comment]
@vitek-karas @johnbeisner I thought we agreed the latest `hostfxr` would be in program files.  Apphost should not need to change if it can always find the latest hostfxr in the same place.

**Comment by sdmaclea** [comment]
> it loads the hostfxr from Program Files which is the old one

Seems this is the bug.

**Comment by johnbeisner** [comment]
I cannot reproduce the "Actual behavior" with a customer installation scenario:

Preconditions:
No SDK installed
Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Users\jbeisner\AppData\Local\Microsoft\WindowsApps;

Step 1:
Install: dotnet-sdk-3.0.100-preview-010217-win-x64.exe to "D:\dotnet\x64"
dotnet-sdk-3.0.100-preview-010217-win-x64.exe /install DOTNETHOME_X64="D:\dotnet\x64" DOTNETHOME_X86="D:\dotnet\x86"

Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;D:\dotnet\x64\;C:\Users\jbeisner\AppData\Local\Microsoft\WindowsApps;

C:\Users\jbeisner>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010217
 Commit:    664049fc49

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\dotnet\x64\sdk\3.0.100-preview-010217\

Host (useful for support):
  Version: 3.0.0-preview-27403-4
  Commit:  60e1a64c45

.NET Core SDKs installed:
  3.0.100-preview-010217 [D:\dotnet\x64\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview-19102-04 [D:\dotnet\x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27403-4 [D:\dotnet\x64\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27402-9 [D:\dotnet\x64\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

Step 2:
Install: dotnet-sdk-2.1.500-win-x64.exe
dotnet-sdk-2.1.500-win-x64.exe /install

Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;D:\dotnet\x64\;C:\Program Files\dotnet\;C:\Users\jbeisner\AppData\Local\Microsoft\WindowsApps;

C:\Users\jbeisner>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010217
 Commit:    664049fc49

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\dotnet\x64\sdk\3.0.100-preview-010217\

Host (useful for support):
  Version: 3.0.0-preview-27403-4
  Commit:  60e1a64c45

.NET Core SDKs installed:
  2.1.500 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010217 [D:\dotnet\x64\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19102-04 [D:\dotnet\x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27403-4 [D:\dotnet\x64\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27402-9 [D:\dotnet\x64\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by johnbeisner** [comment]
When I swap the installation order; dotnet-sdk-2.1.500-win-x64.exe & dotnet-sdk-3.0.100-preview-010217-win-x64.exe both install to 'Program Files' as per design. 

@vitek-karas 
What are the steps to reproduce the error state?

**Comment by vitek-karas** [comment]
The problem is not with `dotnet.exe` - that one will work due to the `PATH` order.
This issue is about `apphost.exe`. In 3.0 we build an app with an `.exe` by default. This is a copy of a binary which we call `apphost`. `apphost` is similar to `dotnet.exe` in that it acts as the main entry point and it also performs similar functionality (find hostfxr, call into it).
The difference is, that `apphost.exe` is part of the app, so if the app is framework dependent it must be able to find `hostfxr` in the global location.

So the repro is to `dotnet new console` and `dotnet build` it. Then go to it bin folder and run the `.exe` there.

**Comment by johnbeisner** [comment]
@vitek-karas 
Thank you for clarifying.

**Comment by nguerrera** [comment]
It is generally a problem that apphost does not respect the same locations as dotnet on PATH. 

See https://github.com/aspnet/AspNetCore-Internal/issues/1552#issuecomment-449125365

For example, you used to be able to redirect VS to a given dotnet using only PATH, but now F5 executes apphost.

I know this has received a lot of pushback before, but I think we should reconsider one last time if apphost can use PATH.

**Comment by vitek-karas** [comment]
There's a competing proposal (sort of) in #4915 which is to make both `apphost` and `dotnet` respect the `DOTNET_ROOT` variable. Currently only `apphost` respects that. It's not as "nice" as the `PATH` since it's not initialized by the installer though.

Personally I'm a bit hesitant to rely solely on `PATH`, but it could be just my bias against that variable.

**Comment by vitek-karas** [comment]
@sdmaclea found another case which is really hard to fix unfortunately. If the machine has only 3.0 installed into a custom location and there's a 2.2 app with framework dependency apphost which has roll forward set to allow major, the app won't run. But if the 3.0 is installed in the Program Files the exact same app would run.
There's really nothing we can do about this one (other then let the setup set the `DOTNET_ROOT` variable for good) since we have no ability to "patch" the apphost in the app.

This probably also means that we should backport whatever fix we make here to 2.2 so that it's possible to build a 2.2 app (with new SDK and framework dependent apphost) which would work in this case. That said, I'm not sure how important is to fix this relatively corner case scenario.

**Comment by vitek-karas** [comment]
There's yet another proposal which has also been discussed. That is to make the installer for 3.0 always install `hostfxr` into the Program Files, regardless of the actual install location (second copy would go to the custom location). Such action should not add any new requirements on the installer (needs admin rights, but that is already the case, will not cause a reboot).
It would make the story for us a bit more predictable as it would guarantee that all `dotnet` invocations would always run on the latest `hostfxr`.

**Comment by vitek-karas** [comment]
The decision is to rely on the registry to locate the shared install.
`apphost.exe` will be changed in 3.0 to also look into registry. Similarly to how `hostfxr` looks for shared frameworks and SDKs.
The same change will be effective for `comhost` as well (/cc @AaronRobinsonMSFT).

There's one known scenario which doesn't work:
Machine with only 3.0 in a custom location. 2.2 framework dependent app with apphost.exe, which has `rollForwardOnNoCandidateFx=2` (that is roll forward to Major). Such application will not run on the machine because it will not find any shared framework as it doesn't know how to find the custom location. If the 3.0 would be installed into Program Files the app would run.
Note that framework dependent apphost is new in 2.2 and requires non-default options to produce. The roll forward to Major setting is also non-default and requires either custom modifications to `runtimeconfig.json` or command line/env. variable. As such it's likely very uncommon. The experience will be an error about missing shared framework and a link to install 2.2. Which is acceptable.
