### ISSUE TITLE
Building with VS 2019 fails native compilation (corehost)

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#5082]
https://github.com/dotnet/corefx/issues/34613 is similar, for corefx.

> (https://github.com/dotnet/corefx/issues/34613#issuecomment-454887287) ~Cmake is rolling out a 3.14.0 in February from what I saw that contains support for VS2019 with a new project generator that might help, but I'm still trying to workaround it.~ [New cmake is out! See comment below.]

---

There are workarounds that let you keep VS 2019 installed:

> (https://github.com/dotnet/corefx/issues/34613#issuecomment-454886707) I would suggest to use the Dev Command Prompt VS2017 when building from root for now until we have a fix.

Removing `-prerelease` from this line also works (this is what I did before I saw the corefx issue, and it doesn't require me to use a dev command prompt):

https://github.com/dotnet/core-setup/blob/e34acdb8b64dc054a22242dd5cbcfceae8e8a5b9/run.cmd#L8

**Comment by safern** [comment]
CMake 3.14-rc1 is out so this shouldn't be a blocker.

https://github.com/dotnet/corefx/pull/35197

**Comment by vitek-karas** [comment]
Resolved by #5378
