### ISSUE TITLE
Cannot silent uninstall old HostingBundles/Runtimes/FX

### ISSUE THREAD

**Issue by sdecker** [dotnet/core-setup#5101]
## Steps to reproduce
Have a system where hosting bundle 2.0.0, 2.1.0, 2.1.5 and 2.1.6 have been installed. Run a vulnerability scanner like Nessus and note multiple vulnerabilities. 
Try to uninstall all of these versions with silent switches before installing 2.1.7
$version = '2.1.7'
$oldHostingBundles = Get-ChildItem -Path 'c:\ProgramData\Package Cache' -Recurse -Include dotnet-hosting-*-win.exe | Where-Object Name -notlike "*-$version-*"
$oldHostingBundles | Foreach-Object {
    $PSItem.Name | Write-Host
    Start-Process -FilePath $PSItem.FullName -ArgumentList "/uninstall /quiet" -Wait
}

$oldDotNetCoreInstalls = Get-WmiObject -Class win32_product | Where-Object Name -like '*.Net Core*' | Where-Object Name -notlike "* $version *" | Sort-Object -Property Version,Name
Write-Host "Uninstalling old version of .Net Core"
$oldDotNetCoreInstalls | Foreach-Object {
    $PSItem.Name | Write-Host

    Push-Location $env:SYSTEMROOT\System32
    #$PSItem.Uninstall()
    Start-Process msiexec -wait -ArgumentList "/x $($PSItem.IdentifyingNumber) /qn /l* c:\temp\$($PSItem.IdentifyingNumber).txt"
}

## Expected  behavior
All old components/versions removed. 

## Actual behavior
Following remain 
Microsoft ASP.NET Core Module
Microsoft .NET Core Host - 2.1.5 (x86)
Microsoft .NET Core Host FX Resolver - 2.1.5 (x86)
Microsoft .NET Core Runtime - 2.1.5 (x86)
Microsoft ASP.NET Core 2.0.0 Runtime Package Store (x64)
Microsoft ASP.NET Core 2.0.0 Runtime Package Store (x86)

Logs show a required interactive dialog box
If you continue with this uninstall, 1 or more products may stop working properly. Do you want to continue with this uninstall anyway?
CustomAction WixDependencyCheck returned actual error code 259 (note this may not be 100% accurate if translation happened inside sandbox)

## Environment data
[{2CB3AB1F-A415-4004-BA1F-05FA8155B28B}.txt](https://github.com/dotnet/core-setup/files/2838171/2CB3AB1F-A415-4004-BA1F-05FA8155B28B.txt)
[{53F12DF1-23C7-3C4B-92AB-FCE8A6ABC3AB}.txt](https://github.com/dotnet/core-setup/files/2838172/53F12DF1-23C7-3C4B-92AB-FCE8A6ABC3AB.txt)
[{56EAB21A-796F-4878-8CB5-40E969E8268A}.txt](https://github.com/dotnet/core-setup/files/2838173/56EAB21A-796F-4878-8CB5-40E969E8268A.txt)
[{1106D55C-932B-33A5-B5A2-40DC793C2396}.txt](https://github.com/dotnet/core-setup/files/2838174/1106D55C-932B-33A5-B5A2-40DC793C2396.txt)
[{0AEBACE9-8E9F-4124-9A7D-ABE47D1E784C}.txt](https://github.com/dotnet/core-setup/files/2838175/0AEBACE9-8E9F-4124-9A7D-ABE47D1E784C.txt)
[{1A801778-59CE-481C-A168-E4E124332F74}.txt](https://github.com/dotnet/core-setup/files/2838176/1A801778-59CE-481C-A168-E4E124332F74.txt)

**Comment by sdecker** [comment]
WARNING: Issue found with \Program Files\dotnet\store\x64\netcoreapp2.0\microsoft.aspnetcore.server.kestrel.core\2.0.0\lib\netstandard2.0\Microsoft.AspNetCore.Server.Kestrel.Core.dll
WARNING: Expected 2.0.4 but found 2.0.0.17205
WARNING: Issue found with \Program Files\dotnet\store\x64\netcoreapp2.0\microsoft.aspnetcore.identity\2.0.0\lib\netstandard2.0\Microsoft.AspNetCore.Identity.dll
WARNING: Expected 2.0.4 but found 2.0.0.17205
WARNING: Issue found with \Program Files\dotnet\store\x64\netcoreapp2.0\microsoft.aspnetcore.server.kestrel.core\2.0.0\lib\netstandard2.0\Microsoft.AspNetCore.Server.Kestrel.Core.dll
WARNING: Expected 2.0.2 but found 2.0.0.17205
WARNING: Issue found with \Program Files\dotnet\store\x64\netcoreapp2.0\microsoft.aspnetcore.httpoverrides\2.0.0\lib\netstandard2.0\Microsoft.AspNetCore.HttpOverrides.dll
WARNING: Expected 2.0.2 but found 2.0.0.17205

**Comment by sdecker** [comment]
We were able to find a solution https://serverfault.com/questions/935061/troubleshoot-msiexec-removing-dotnet-core

**Comment by leecow** [comment]
@joeloff for hosting bundle question.

**Comment by joeloff** [comment]
The remaining items you listed are actually the underlying MSIS. The dialog box you saw is related to the MSI being shared by multiple bundles (EXEs). When an MSI has a reference count greater than 1, you have to remove all the bundles that reference it. The last bundle you uninstall with a reference will actually remove the MSI. The hosting bundle shares a number of items with the other bundles, e.g. asp.net package store ships in the SDK bundle as well.

If you want to force the uninstall at the MSI level, then you'll need to pass IGNOREDEPENDENCIES=ALL to MSIEXEC as mentioned in the linked post earlier in the thread.

**Comment by dagood** [comment]
Based on joeloff's reply, it sounds like this is expected behavior.

I think .NET Core SDK, .NET Core Shared Framework, and ASP.NET Core Shared Framework bundle installers are the most likely to be taking these extra dependencies on those MSIs.

Closing, but let me know if there's something wrong here. (E.g. if these machines are known to be pristine other than the host bundles, or there's a way to repro.) I believe https://github.com/aspnet/AspNetCore is the right place for followup issues if it's specific to the hosting bundle.
