### ISSUE TITLE
Add supportedOS manifest resource to dotnet.exe on windows builds

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#5106]
@powercode commented on [Thu Feb 07 2019](https://github.com/dotnet/cli/issues/10723)

## Steps to reproduce
Running tests using dotnet.exe will load the assembly under test into the dotnet.exe process. Without a manifest, System.Environment.OSVersion will return compatibility values, and not the values of the actual operating system.

By adding a manifest as a resource in the executable, we can explicitly say that we support Windows 10.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
    <description>.NET Core Host</description>
    <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
        <security>
            <requestedPrivileges>
                <requestedExecutionLevel
                    level="asInvoker"
                    uiAccess="false"
                />	
            </requestedPrivileges>
        </security>
    </trustInfo>
    <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> 
        <application> 
            <!-- Windows 10 --> 
            <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
            <!-- Windows 8.1 -->
            <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
            <!-- Windows 8 -->
            <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
            <!-- Windows 7 -->
            <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
        </application> 
    </compatibility>
</assembly>
```

The manifest can be specified with the `/win32manifest:file` option to the compiler, and the msbuild property is `Win32Manifest`.

## Environment data
`dotnet --info` output:
```output
.NET Core SDK (reflecting any global.json):
 Version:   2.1.503
 Commit:    4c506e0f35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.503\

Host (useful for support):
  Version: 2.1.7
  Commit:  cca5d72d48
```

**Comment by vitek-karas** [comment]
This has been fixed in 3.0.
Using `3.0.100-preview-010184` and printing out the `System.Environment.OSVersion` the real version `10.0...` is shown.
Please note that in 3.0 the app will get a native `.exe` built by default. This exe, also by default, will not have the manifest with supported OS versions. So just doing `dotnet run` will show the compatibility version. Running the app via `dotnet app.dll` will work.
The native `app.exe` built into the app will have whatever manifest is specified in the project, so just add `<ApplicationManifest>app.manifest</ApplicationManifest>` to the project file and specify the right manifest, it will be built into the `.exe`.

**Comment by powercode** [comment]
@vitek-karas That seem like the right way to do it, IMHO.
Thx

**Comment by vitek-karas** [comment]
Not sure I understand your comment right... I just wanted to say that if you try any recent .NET Core 3.0 SDK this manifest in app.exe already works, so you can at least try it out.

**Comment by powercode** [comment]
@vitek-karas Sorry, I was not clear. I tried to say that it was the right choice to have a manifest on the dotnet executable, but leave it to the app to determine it's compatibility manifest. 
I just have to wait for the project I'm working on to adopt a newer version.

**Comment by vitek-karas** [comment]
@powercode - glad it will work for you.
