### ISSUE TITLE
Add "internal implementation package" warning to Microsoft.NETCore.App.Ref

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#5107]
The package will be used, but not via `PackageReference`s.

**Comment by natemcmaster** [comment]
Add to description, or some other way, like via build assets with an MSBuild `<Warning>`?

**Comment by dagood** [comment]
This just tracks the description. I don't think we currently plan on doing more than setting the package type (and maybe min nuget version) to prevent actual usage.
