### ISSUE TITLE
Runtime libraries are not being populated for DependencyContext

### ISSUE THREAD

**Issue by seesharper** [dotnet/core-setup#5130]
We have discovered a possible problem with the `DepenencyContextJsonReader` in the latest version of `Microsoft.Extensions.DependencyModel (3.0.0-preview-27324-5)`.

We are using the `DependencyContextJsonReader` in [dotnet-script](https://github.com/filipw/dotnet-script) to determine the runtime dependencies for a script. 

Without going into too much detail, we discovered that when moving to the latest preview package of `Microsoft.Extensions.DependencyModel`, we could no longer get the runtime libraries from the `project.assets.json` file using the `DependencyContextJsonReader`

https://github.com/filipw/dotnet-script/blob/acd312d3f789089330699b418a22cbe8da43d184/src/Dotnet.Script.DependencyModel/Context/ScriptDependencyInfoProvider.cs#L54

## Steps to reproduce
Clone the https://github.com/seesharper/dependencymodel-demo repo

This is a simple .Net Core 2.1 console app using the Microsoft.Extension.DependencyModel package.

## Expected  behavior

The expected and current behaviour in 2.1.0 is that we will get a complete list of runtime libraries.

This is the result of running the demo app with version 2.1.0 of the `Microsoft.Extensions.DependencyModel` package. 

```
Microsoft.CSharp
Microsoft.DotNet.PlatformAbstractions
Microsoft.Extensions.DependencyModel
Microsoft.NETCore.App
Microsoft.NETCore.DotNetAppHost
Microsoft.NETCore.DotNetHostPolicy
Microsoft.NETCore.DotNetHostResolver
Microsoft.NETCore.Platforms
Microsoft.NETCore.Targets
NETStandard.Library
Newtonsoft.Json
runtime.native.System
System.AppContext
System.Collections
System.Diagnostics.Debug
System.Diagnostics.Tools
System.Dynamic.Runtime
System.Globalization
System.IO
System.IO.FileSystem
System.IO.FileSystem.Primitives
System.Linq
System.Linq.Expressions
System.ObjectModel
System.Reflection
System.Reflection.Emit
System.Reflection.Emit.ILGeneration
System.Reflection.Emit.Lightweight
System.Reflection.Extensions
System.Reflection.Primitives
System.Reflection.TypeExtensions
System.Resources.ResourceManager
System.Runtime
System.Runtime.Extensions
System.Runtime.Handles
System.Runtime.InteropServices
System.Runtime.InteropServices.RuntimeInformation
System.Runtime.Serialization.Primitives
System.Text.Encoding
System.Text.Encoding.Extensions
System.Text.RegularExpressions
System.Threading
System.Threading.Tasks
System.Threading.Tasks.Extensions
System.Xml.ReaderWriter
System.Xml.XDocument

```

## Actual behavior

When using the latest preview (3.0.0-preview-27324-5) this does to seem to work anymore. 

Results from running with the latest preview

```
Microsoft.DotNet.PlatformAbstractions
Microsoft.Extensions.DependencyModel
Microsoft.NETCore.App
Microsoft.NETCore.DotNetAppHost
Microsoft.NETCore.DotNetHostPolicy
Microsoft.NETCore.DotNetHostResolver
Microsoft.NETCore.Platforms
Microsoft.NETCore.Targets
NETStandard.Library
Newtonsoft.Json
```

## Environment data

```
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview-010184/

Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

.NET Core SDKs installed:
  2.1.301 [/usr/local/share/dotnet/sdk]
  2.1.402 [/usr/local/share/dotnet/sdk]
  2.2.100 [/usr/local/share/dotnet/sdk]
  3.0.100-preview-010184 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by filipw** [comment]
please note that this worked with the previous .NET Core 3.0 preview SDK - `3.0.100-preview-009812` (with host `3.0.0-preview-27122-01`)

**Comment by seesharper** [comment]
@jeffschwMSFT  We have just tried this with the latest version ("3.0.0-preview3-27503-5) and the problem is still the same. I've also updated the repro project (https://github.com/seesharper/dependencymodel-demo) with the latest package.

**Comment by jeffschwMSFT** [comment]
cc @eerhardt

**Comment by eerhardt** [comment]
The first thing I need to ask/get clarification on:

> we could no longer get the runtime libraries from the project.assets.json file using the DependencyContextJsonReader

The `DependencyContextJsonReader` doesn't read `project.assets.json` files (which are design-time assets - like `.csproj` or `.resx` files, they are only used by the design-time tooling). Instead `DependencyContextJsonReader` reads `.deps.json` files, which are runtime assets - they are produced by the build and consumed when you run your application.

If this scenario happened to work in the past, it was unintended and shouldn't have. It may just have worked because the JSON schema was so close to each other that a parser for one worked on another one.

If your intent is to read/parse/consume `project.assets.json` files, you shouldn't use `DependencyContextJsonReader`, but instead use the `NuGet.ProjectModel` library which has a `LockFile` class that can be used to read a `project.assets.json` file. This is what the [.NET Core SDK uses](https://github.com/dotnet/sdk/blob/b73819e683af64bd19c961973c77b2239cd20e5d/src/Tasks/Microsoft.NET.Build.Tasks/LockFileCache.cs#L81) to read these files.

**Comment by seesharper** [comment]
@eerhardt Thanks a lot for the clarification. The `LockFile` class looks like the one we need for this purpose. This is somewhat besides the issue here, but do you know if it is possible to do an "in-process" restore using the NuGet libraries. Today we call out to `dotnet restore` which also requires us to have the dotnet cli installed. So given a `csproj` file, is is possible to do the restore without calling out to `dotnet restore`?

**Comment by eerhardt** [comment]
I don't know of a better public/supported way of restoring a project other than calling `dotnet restore` on a `.csproj`.

This is actually what the .NET Core SDK itself does when you call `dotnet tool install` to install a global tool.

Create a temp project and call `_projectRestorer.Restore`:
https://github.com/dotnet/cli/blob/39bcd0282e95f345a20c505661b86df6257c99cb/src/dotnet/ToolPackage/ToolPackageInstaller.cs#L56-L71

Implementation of `_projectRestorer.Restore`:
https://github.com/dotnet/cli/blob/6f18d86bb6e50cef42bbc4a227084f062c0c8d92/src/dotnet/commands/dotnet-tool/install/ProjectRestorer.cs#L58-L59

**Comment by eerhardt** [comment]
Closing this issue. If you are parsing a `project.assets.json` file, using the NuGet libraries is the appropriate approach. `DependencyContext` is for parsing `deps.json` files.

**Comment by seesharper** [comment]
Thanks a lot @eerhardt for valuable information. We have successfully switched to the `LockFile` and everything works as expected.
