### ISSUE TITLE
Review calling convention for all native APIs in hosting layer

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/core-setup#5135]
We're probably missing specifying calling convention (for x86) in some cases in the hosting layer. This applies to both exports as well as function pointers used in the ABI.
We should review these and fix those which we still can (.NET Core 3.0 new).

In all cases we should explicitly state the used calling convention to make the code clearer and more robust.

**Comment by elinor-fung** [comment]
Addressed with #6641
