### ISSUE TITLE
Clarify call to action in message when no roll-forward

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/core-setup#5182]
## Steps to reproduce
Machine has only .NET Core 3.0 Previews

```
dotnet tool install --global dotnet-format --version 3.0.0
```

## Expected  behavior

The message should be quite clear that the user needs to install the runtime. The information is there, but it requires more reading and thought to figure out the right solution.

**Comment by KathleenDollard** [comment]
@livarcocc @KathleenDollard @jeffschwMSFT @leecow

**Comment by jeffschwMSFT** [comment]
cc @sdmaclea

**Comment by sdmaclea** [comment]
@vitek-karas has been focusing on roll forward behavior.  

While this is about the user message, it is not clear to me why it is occurring in this situation.

SemVer 2.0.0 would say the preview satisfies the 3.0.0 requirement.  It is logically ordered before the release.  However a preview is not `forward` of a release version the the same X.Y.Z prefix.

Relative to 3.0.0:
+ `3.0.0-preview` preview roll backward.  
+ `3.0.1-preview` patch roll forward.
+ `3.1.0-preview` minor roll forward.
+ `4.0.0-preview` major roll forward.

Per SemVer 2.0.0 `3.0.0-preview` should satisfy 3.0.0 request.  We can of course have a different policy, but I'm not sure why we would.

Of course message should be fixed....

**Comment by vitek-karas** [comment]
@KathleenDollard can you please do this one the machine in question:
```
set COREHOST_TRACE=1
set COREHOST_TRACEFILE=t.log
dotnet tool install --global dotnet-format --version 3.0.0
```

And then share the `t.log` file this creates.
I've tried to repro this locally (using `DOTNET_MULTILEVEL_LOOKUP=0`) but for me the tool installs just fine.
As a side note the installed tool doesn't work - the path it looks for doesn't match what's on the disk.

@sdmaclea The `--version 3.0.0` is not about FX versions. It's about the global tool and what version to install. So while I would expect that SemVer rules would apply, the discussed roll-forward changes won't do anything to this scenario (I think the versions here are resolved by NuGet).

**Comment by jeffschwMSFT** [comment]
The scenario here is if you run a netcoreapp2.0 on a machine with only 3.0.

**Comment by vitek-karas** [comment]
@jeffschwMSFT I'm not so sure about that. For me the install works, but running the tool fails due to an error which says nothing about 2.0 versus 3.0. It looks for a file which is not there.

**Comment by jeffschwMSFT** [comment]
Full disclosure, @KathleenDollard did not have a machine with this configuration, @livarcocc induced it on a box with multiple by constraining it to a preview that was not installed.  The intention is to get a good error message when any app (not just global tools) are run on a machine that only has a major version roll forward candidate present.  @livarcocc can you add the text that Kathleen was looking to adjust?

**Comment by KathleenDollard** [comment]
Oh my. Sorry for the poor issue description. I was sloppy. I edited the description above for clarity. 

You are correct, the failure is on run. It will happen with any framework dependent dll or exe, regardless of how it got onto the machine.

When this occurs, I think we should be clear that the probable best solution is installing the requested runtime.

**Comment by KathleenDollard** [comment]
Actually, I am going to close this and reopen when I have specific text. Our conversation is just about the confusion.
