### ISSUE TITLE
How to register ASpnetcoremodule in IIS after dotnetcore installation ?

### ISSUE THREAD

**Issue by xBorus** [dotnet/core-setup#5199]
## Steps to reproduce
1. Have a windows server without IIS installed
2. Install dotnet-hosting-2.2.1
3. Install IIS via windows features

## Expected  behavior
In .NET framework we had aspnet_regiis utility.
I would expect an utility to register aspnetcore after iis is installed

## Actual behavior
In order to get the plugin, one need to :
- Install IIS via windows features
- Reinstall dotnet core

**Comment by vitek-karas** [comment]
This issue was moved to aspnet/AspNetCore#7701
