### ISSUE TITLE
Gather Microsoft.WindowsDesktop.App (WPF, WinForms) in Core-Setup, not DotNet-Trusted

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#5219]
DotNet-Trusted currently gathers WPF and WinForms bits and produces Microsoft.WindowsDesktop.App and its runtime packages. We should produce the WindowsDesktop packages in Core-Setup to centralize gathering and take advantage of the shared infrastructure.

Core-Setup has a lot of existing infrastructure similar to DotNet-Trusted's for Microsoft.NETCore.App. We will save infra work by sharing this infra in one repo: Core-Setup already runs crossgen to make Microsoft.NETCore.App runtime packages, and Targeting and Runtime pack creation is being added.

Also, when we do this, the DotNet-Trusted repo (with some WPF caveats) would no longer be in the build graph and could be deleted.

I started looking at this for https://github.com/dotnet/core-setup/pull/5214, but there are some WPF bits that are only built in DotNet-Trusted that we need to work out how to transport first.

/cc @zsd4yr @ericstj

**Comment by zsd4yr** [comment]
@vatsan-madhavan for wpf visability

**Comment by zsd4yr** [comment]
related to https://github.com/dotnet/winforms/issues/471

**Comment by Lee02** [comment]
but this sdk don't windowsDesktop .don't run Linux

**Comment by dagood** [comment]
@Lee02 That's correct, WPF (https://github.com/dotnet/wpf) and WinForms (https://github.com/dotnet/winforms) only run on Windows.

**Comment by dagood** [comment]
To gather status here, I merged [PR 168307](https://devdiv.visualstudio.com/DevDiv/_git/DotNet-Trusted/pullrequest/168307) today to add Microsoft.Private.WindowsDesktop.App transport packages to DotNet-Trusted. [The official build](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2485956) produced `Microsoft.Private.WindowsDesktop.App` `3.0.0-preview4-27511-40` (and runtime packages).

Next step is get Core-Setup able to consume `Microsoft.Private.WindowsDesktop.App` to produce `Microsoft.WindowsDesktop.App` packages, with crossgen. We'll synchronize turning that package on in Core-Setup and off in DotNet-Trusted once the Core-Setup changes are ready.

**Comment by vatsan-madhavan** [comment]
@dagood, Now that dotnet-trusted doesn't do any source builds of its own (i.e., it only serves as a place for _assembling_ transport packages from WinForms and WPF into `Microsoft.Private.WindowsDesktop.App`), would it possible to move the production of `Microsoft.Private.WindowsDesktop.App` over to core-setup and decommission dotnet-trusted?

**Comment by dagood** [comment]
Yes, looking back, it's actually what the issue targets, but it's not what I'm currently working on. That's my bad for not decomposing the issue once our plan got more solid.

I've filed https://github.com/dotnet/core-setup/issues/5675 for the subset I'm working on and I'm moving this issue back to the backlog.

**Comment by vatsan-madhavan** [comment]
We have had two goals for Preview 5. (i) Crossgen and (ii) decommissioning dotnet-trusted. It looks like we'd want to complete both #5219 and #5675 to get there. Do you think they are both acheviable in this timeframe? Or do you now think that #5675 is where you'd want to focus for preview 5? 

/cc @zsd4yr, @merriemcgaw

**Comment by dagood** [comment]
Yeah, I'm planning on #5219 and #5675 fitting in Preview 5 but not DotNet-Trusted removal.

Sorry if I'm forgetting, but what are the reason to remove DotNet-Trusted? The repo causes extra maintenance work and makes build flow slower and more complicated, but does it directly block anything?

**Comment by vatsan-madhavan** [comment]
We've had an organization goal to move everything to DncEng and not keep anything on DevDiv VSO infra. We've (both WPF & WinForms, and also core-set, /cc @livarcocc ) said multiple times that we'll decommission dotnet-trusted.

**Comment by dagood** [comment]
I don't want to keep it, I'm just looking for an accounting of the reasons to make sure it's prioritized correctly. Thanks for the DevDiv vs. dnceng point. I don't remember if I've heard that called out specifically before.

**Comment by dagood** [comment]
Adding as status (it doesn't affect when I plan to do this):

@zsd4yr let me know offline that after https://github.com/dotnet/core-sdk/pull/1196 was merged, WPF and WinForms should be all the way out of dotnet-trusted, so this work shouldn't be blocked from the dependency side of things.

**Comment by dagood** [comment]
FYI, I'm working on this right now.

An interesting difference is that the Core-Setup infra picks up the intellisense XML for the CoreFX bits to put in the WindowsDesktop targeting pack--these weren't in the DN-T package. I expect that's a good thing, but let me know. 😄
