### ISSUE TITLE
PackageCompilationAssemblyResolver::TryResolveAssemblyPaths not working on linux

### ISSUE THREAD

**Issue by aceldam** [dotnet/core-setup#5234]
https://github.com/dotnet/core-setup/blob/2f91bd28d0c77eb72275f46ddd7cfc9f10196ba7/src/managed/Microsoft.Extensions.DependencyModel/Resolution/ResolverUtils.cs#L15

This will not work when library name has mixed casing and a project using PackageCompilationAssemblyResolver::TryResolveAssemblyPaths is run on linux.
My solution was to do ToLowerCase on library name, but seemed like a bit of a hack.

**Comment by jeffschwMSFT** [comment]
cc @eerhardt

**Comment by eerhardt** [comment]
@aceldam - what version of .NET Core SDK are you using to generate the `.deps.json` file?

The reason this works on Linux is the line above the line you posted above (line 12 below):

https://github.com/dotnet/core-setup/blob/f9965e5a7eeb851ffd864f13915bea6c31a6fa72/src/managed/Microsoft.Extensions.DependencyModel/Resolution/ResolverUtils.cs#L10-L16

`var path = library.Path;`

This line of code is getting the `path` property in the `.deps.json` file for the package, which will have the correct casing (i.e. "lower" casing).

For example:

```json
    "NETStandard.Library/2.0.3": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-st47PosZSHrjECdjeIzZQbzivYBJFv6P2nv4cj2ypdI204DO+vZ7l5raGMiX4eXMJ53RfOIg+/s4DHVZ54Nu2A==",
      "path": "netstandard.library/2.0.3",
      "hashPath": "netstandard.library.2.0.3.nupkg.sha512"
    },
```

Notice here the library's name is using capital letters: `NETStandard.Library`, but the `path` property has it all lowered case: `"path": "netstandard.library/2.0.3",`.

If you are using a `1.0` .NET Core SDK to generate the `.deps.json` file, it won't contain this `path` property. However, we added this `path` property to the `.deps.json` file in .NET Core 1.1. So if you are using a `1.1` SDK or later, this is fixed.

**Comment by eerhardt** [comment]
Closing as there has been no response to the above questions. Please re-open if my comments above don't address your concerns.

**Comment by shvez** [comment]
hi, there

I had the same issue. After reading this topic I found out that I do not pass Path during the creation of CompilationLibrary object. that was the reason for an issue in my case.

best,
ilya
