### ISSUE TITLE
Microsoft.NETCore.App contains unsigned binaries (again)

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/core-setup#5244]
```
[File] 0833626f316b72011de3acb878c4b3bb.dll, Signed: False, Full Name: content/shared/Microsoft.NETCore.App/3.0.0-preview4-27424-1/comhost.dll [Error] HRESULT: 800b0100 (No signature was present in the subject)
```

aspnet builds started failing after updating to latest versions because we run signcheck on our output. Microsoft.NETCore.App contains an unsigned binary.

This is like the 3rd or 4th time this has happened recently. Can we create a more resilient way for this repo to ensure everything in Microsoft.NETCore.App is signed before passing of bits to other teams?

cc @dougbu  @Eilon

**Comment by natemcmaster** [comment]
cc @pakrym @AaronRobinsonMSFT

**Comment by pakrym** [comment]
Dup https://github.com/dotnet/core-setup/issues/5253

**Comment by AaronRobinsonMSFT** [comment]
> aspnet builds started failing after updating to latest versions because we run signcheck on our output.

@natemcmaster Agreed we should have some mechanism to stop this from happening. Does your team do an insertion/validation CI build prior to updating to a new package? I would assume that would have caught this issue.

cc @vitek-karas

**Comment by natemcmaster** [comment]
> Does your team do an insertion/validation CI build prior to updating to a new package?

I think we might start doing that if this continues to be a regular problem, but no, we don't currently have this check as a part of our criteria for updating dependency versions.

**Comment by AaronRobinsonMSFT** [comment]
@natemcmaster Okay. We need to address this in our repo, but if this has happened before and there is a possibility of a build break in the AspNet repo then that repo should also have a way to validate this invariant.

**Comment by dougbu** [comment]
This is blocking our release/3.0-preview3 builds as well as master builds.

/cc @mmitche

**Comment by mmitche** [comment]
@wtgodbe We need to take care of this for preview3.

**Comment by wtgodbe** [comment]
Looking

**Comment by wtgodbe** [comment]
I downloaded `Microsoft.NETCore.App/3.0.0-preview4-27424-1` and don't see a file named `comhost.dll`, am I looking at the wrong package?

**Comment by dagood** [comment]
We had signing validation until the change to yaml defs, presumably there wasn't enough time to port it and/or the hope was to hold out and use the Arcade SDK validation.

@wtgodbe you'll find it in the zip, not familiar with it so not sure why it's not in the runtime package:
https://dotnetcli.blob.core.windows.net/dotnet/Runtime/3.0.0-preview4-27424-1/dotnet-runtime-3.0.0-preview4-27424-1-win-x64.zip

**Comment by dougbu** [comment]
Which of this issue and https://github.com/dotnet/core-setup/issues/5253 describe what we're thinking of to fix this problem? That is, is this a packaging issue or a missed signing requirement?

**Comment by AaronRobinsonMSFT** [comment]
> is this a packaging issue or a missed signing requirement?

This is a packaging issue.

@jkoritzinsky has found the issue in core-setup. We will push out a PR shortly with the fix.

**Comment by dougbu** [comment]
And that PR will target release/3.0-preview3 ?

**Comment by dagood** [comment]
Closing as a side effect of #5253 that will be fixed there. Opened #5254 for the infra work to add validation.
