### ISSUE TITLE
Microsoft.NETCore.App shared runtime contains comhost.dll

### ISSUE THREAD

**Issue by pakrym** [dotnet/core-setup#5253]
Version:
3.0.0-preview4-27426-2

Considering https://github.com/dotnet/sdk/pull/2814 is there a reason comhost.dll should be bundled with the runtime?

@vitek-karas @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
@pakrym I think I am not fully understanding your question. The `comhost.dll` binary should ship with the `apphost.exe` binary, there is no need for it to be shipped with the `coreclr.dll` binary. Does "bundled with runtime" mean ship with `coreclr.dll`?

**Comment by jkoritzinsky** [comment]
@pakrym dotnet/sdk#2814 requires `comhost.dll` to be in the `Microsoft.NETCore.DotNetAppHost` package alongside `apphost.exe`. Is it also showing up in the `Microsoft.NETCore.App` package?

**Comment by pakrym** [comment]
> Is it also showing up in the `Microsoft.NETCore.App` package?

Yes

**Comment by pakrym** [comment]
Sorry, I'm not sure about the `Microsoft.NETCore.App` package but it is showing up in latest runtime zip (https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/dotnet-runtime-latest-win-x64.zip)

**Comment by AaronRobinsonMSFT** [comment]
Okay. This seems like some kind of issue with packaging. Sorry, this was definitely not intentional.

**Comment by jkoritzinsky** [comment]
After some investigation, it looks like the apphost has some extra logic to avoid being copied during publish. I'll add that to the sdk PR. In the meantime, I'll add an exclusion in core-setup like was done when apphost.exe was in the process of being added.
