### ISSUE TITLE
dotnet.exe win32 manifest should opt in to long paths

### ISSUE THREAD

**Issue by nguerrera** [dotnet/core-setup#5262]
See https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/

Although managed file system API on .NET Core can support long paths without this manifest, setting this will allow P/Invokes straight to the OS to get long path support.

Currently MSBuild does a lot of P/Invoking and is still hitting max path issues on .NET Core.

**Comment by AaronRobinsonMSFT** [comment]
cc @elinor-fung
