### ISSUE TITLE
dotnet command not found on Fedora 29 after installation

### ISSUE THREAD

**Issue by Mebus** [dotnet/core-setup#5303]
After performing the installation as described here on Fedora 29:

https://developer.fedoraproject.org/tech/languages/dotnet/about.html

I get the error:

```
mebus@box:~$ dotnet
bash: dotnet: command not found
mebus@box:~$ 
```

:unamused: 

How can I run dotnet?

**Comment by omajid** [comment]
Sorry about that. That was entirely my fault. I am going to kick off a fix for this. A `dnf upgrade` in a few hours should get you the new version with this fixed. In the meantime you can manually `dnf install dotnet-runtime-2.2` to get the fix.

Please note that the Fedora packages on `@dotnet-sig/dotnet` copr repo are supported by us [Fedora .NET SIG](https://fedoraproject.org/wiki/SIGs/DotNet) folks. We hang out here on github too, but you can also reach us directly via the methods listed here: https://fedoraproject.org/wiki/SIGs/DotNet#Contact

**Comment by omajid** [comment]
A `dnf clean all && dnf upgrade` should fix it now: it should offer to install `dotnet-runtime-2.2` as a dependency.

**Comment by Mebus** [comment]
Great! It works now :smile: Thanks! 

```
mebus@box:~$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     fedora
 OS Version:  29
 OS Platform: Linux
 RID:         fedora.29-x64
 Base Path:   /usr/lib64/dotnet/sdk/2.2.104/

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.2.104 [/usr/lib64/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.2 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
Mebus
