### ISSUE TITLE
The source code mismatch warning for ‘Native Symbols’

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/core-setup#5329]
## Steps to reproduce
1. Download PerfView from https://github.com/Microsoft/perfview/blob/master/documentation/Downloading.md (this only needs to be done once).
2. Start data collection by running.  It will ask for elevation (grant it) It should bring up a dialog box that shows that it is collecting data. 
 
        PerfView /merge:false collect
 
3. In the razor directory you built previously ( in the above scenario # 28) run  the application by running
 
        dotnet bin\Debug\netcoreapp3.0\razor.dll 
    It should give some text and the indicate that to stop it Press Control C.   Go ahead and press Control C.
 
4. Stop PerfView collection by hitting the ‘stop collection’ button in PerfView. 
5. It will have created a ‘PerfView.etl file that shows in the PerfVIew’s window.   Double click on it to open
6. Double click on the ‘CPU Stacks’ view this brings up a dialog box with every process running during the collection.
7. Select the ‘dotnet’ executable that was running ‘razor.dll’ (The program args are there if needed).    This brings up a viewer. 
8. The view will have nodes that look like <microsoft.aspnetcore.hosting!?>> that have ? in them (meaning it does not have symbols  Select the <microsoft.aspnetcore.hosting!?>> and press Alt-S (lookup symbols).   Do this for the following DLLs
 microsoft.aspnetcore.hosting
system.private.corelib
system.linq
 
   Each time you hit ‘Alt-S’ it should resolve the symbols (it may seem like it disappeared because that one node turns into many (which get displayed in sorted order).    If the node does NOT change, then that is an error report it.
    For each of these find one of the resolved nodes (you can use the ‘Find’ box at the top to search for it).   Select the node (which should now have a complete method name in it) and type Alt-D (lookup definition).   It SHOULD open a source code window.  If it does not that is a bug.

Note: It needs to set the path to PerfView at first.
![image](https://user-images.githubusercontent.com/33921754/53795759-9aa4fd80-3f6d-11e9-957c-773190d87b4f.png)

## Expected  behavior
a. microsoft.aspnetcore.hosting
b. system.private.corelib
c. system.linq
Symbols can be getting resolved and source can be reached without warnings for them.

## Actual behavior
The source code mismatch warning. 
![image](https://user-images.githubusercontent.com/33921754/53795994-2159da80-3f6e-11e9-892e-8b214bafd954.png)

For more info, please view the complete log:
[PerfViewLogFile.1.txt](https://github.com/dotnet/core-setup/files/2930265/PerfViewLogFile.1.txt)

## Environment data
D16.0stg/28704.105 (16.0.0 preview 4.1) + CLI\SDK: 3.0.100-preview3-010431
![image](https://user-images.githubusercontent.com/33921754/53796088-523a0f80-3f6e-11e9-9587-82acfb4149b8.png)

**Comment by dagood** [comment]
Unable to reproduce the problem on `3.0.0-preview8-28405-07`. (Note that the issue was filed for `3.0.0-preview3-27504-2`.) I'm not sure exactly which `system.private.corelib` row caused this, but I tried a bunch of the ones I see and none had this issue.
