### ISSUE TITLE
Provide installer links in the readme to the latest bits

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#544]
We need to make the links to the installers that come out of this build more obvious to get. Always pointing to the latest but with an explanation on how to get older ones assuming they are still around.

**Comment by gkhanna79** [comment]
@wtgodbe PTAL.

Cc @schellap

**Comment by Petermarcu** [comment]
I'm going to reopen this one to track the changes I made in the comments of https://github.com/dotnet/core-setup/pull/566
