### ISSUE TITLE
Investigate ARM64 support in WIX 3

### ISSUE THREAD

**Issue by dleeapho** [dotnet/core-setup#5456]
What is the level of support for ARM64 in Wix 3? Significant bugs? If not supported, what is it for Wix 4?

**Comment by dagood** [comment]
Doesn't look supported for WiX 3 or 4.

* https://github.com/wixtoolset/issues/issues/5558 "WiX + Arm64"
* https://github.com/wixtoolset/issues/issues/5892 "Guidance for building arm MSIs for Windows"

I looked around in the latest WiX 4 code, and ARM (not 64) seems supported based on it being listed as an `-arch` option, and there's a decent amount of ARM-specific code through the repo. ARM64 doesn't show up even once.

**Comment by dleeapho** [comment]
Closing since we have enough info for now.
