### ISSUE TITLE
ARM32 3.0.100-preview3 SDK includes x86-64 "apphost" binary

### ISSUE THREAD

**Issue by ShonkyCH** [dotnet/core-setup#5458]
```/sdk/3.0.100-preview3-010431/AppHostTemplate/apphost```

is an x86-64 binary:

```ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=94bfae5d6580d203c7d9b4aa776ff09954453fff, stripped```

**Comment by dagood** [comment]
I can repro by downloading the ARM SDK from https://dotnet.microsoft.com/download/dotnet-core/3.0, then running `file` on the `apphost` inside.

Downloading the [runtime.linux-arm.Microsoft.NETCore.DotNetAppHost/3.0.0-preview3-27503-5](https://www.nuget.org/packages/runtime.linux-arm.Microsoft.NETCore.DotNetAppHost/3.0.0-preview3-27503-5) package Core-Setup produced, I see arm:

```
#> file apphost
apphost: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically
linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32,
BuildID[sha1]=d5b39d5d3f8fbee48b739d60a68b9b47fbe450b2, stripped
```

It seems something went wrong with when Core-SDK consumed this package. Moving this issue there. (Unfortunately I don't have admin powers for the smooth GitHub-supported move.)

**Comment by dagood** [comment]
Issue moved to [dotnet/core-sdk #999](https://github.com/dotnet/core-sdk/issues/999) via [**ZenHub**](https://www.zenhub.com/)
