### ISSUE TITLE
Document hostfxr/hostpolicy API

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/core-setup#5481]
There is no documentation for the `hostfxr` or `hostpolicy` API surface area.

See https://github.com/dotnet/coreclr/pull/23249 for issues related to this lack of validation and documentation.

**Comment by elinor-fung** [comment]
We now have a doc for [hosting layer APIs](https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/hosting-layer-apis.md).
