### ISSUE TITLE
ijwhost should be signed

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/core-setup#5485]
Even though both `comhost` and `ijwhost` will be copied into customer apps, those binaries are not going to be modified (unlike `apphost`) and thus should be signed by Microsoft in official releases.

**Comment by vitek-karas** [comment]
@AaronRobinsonMSFT @jkoritzinsky

**Comment by jeffschwMSFT** [comment]
Don't we embbed a clsid to class map into comhost?  I agree with ijwhost we are not modifying, but is there a particular reason to break with the consistency of not signing them all (eg. all or nothing)?

**Comment by jkoritzinsky** [comment]
Comhost will be modified as part of the build so it cannot be signed. The IJW host can be signed though.

**Comment by vitek-karas** [comment]
Sorry - didn't realize we do modify the `comhost`
