### ISSUE TITLE
Bogus runtime.json in targeting pack

### ISSUE THREAD

**Issue by nguerrera** [dotnet/core-setup#5511]
As of 3.0.0-preview4-27519-01, microsoft.windowsdesktop.app has a bogus runtime.json, referencing non-existent packages. It should not have a runtime.json at all as it should always have zero dependencies.

```
"win-x64": {
      "Microsoft.WindowsDesktop.App.Ref": {
        "runtime.win-x64.Microsoft.WindowsDesktop.App.Ref": "3.0.0-preview4-27519-01"
      }
    },
    "win-x86": {
      "Microsoft.WindowsDesktop.App.Ref": {
        "runtime.win-x86.Microsoft.WindowsDesktop.App.Ref": "3.0.0-preview4-27519-01"
      }
    }
```
This will lead to `error NU1101: Unable to find package runtime.win-x64.Microsoft.WindowsDesktop.App.Ref` for any scenario using the targeting pack via nuget and having RuntimeIdentifier(s) set.

I suspect microsoft.netcore.app.ref may have the same problem, but it is delivered into the packs/ folder already which hides this.

cc @dagood

**Comment by nguerrera** [comment]
https://github.com/dotnet/core-sdk/pull/1062 should mask this, but the runtime.json still needs to be removed.

**Comment by dagood** [comment]
Yep, looks like my refactor caused this. Working on a fix.
