### ISSUE TITLE
AppDomain.GetData returns a string terminated by the path separator character in .Net 3.0 Preview 3

### ISSUE THREAD

**Issue by joproulx** [dotnet/core-setup#5553]
In .Net Core 3.0 Preview 3, AppDomain.GetData method returns a string terminated by the path separator character ';'. This was not the case in .Net Core 2.2.

When splitting the string `appDomainData.Split(Path.PathSeparator)` would result in an array with last item being an empty string which can cause issue if not handled correctly (as seen here: [https://github.com/Particular/NServiceBus/issues/5348](https://github.com/Particular/NServiceBus/issues/5348))

Not sure if this should be considered a bug or we should expect this case when splitting the string and just discard the empty string with the split option `StringSplitOptions.RemoveEmptyEntries`.

**Comment by jkotas** [comment]
Repro:
```csharp
static void Main(string[] args)
{
    Console.WriteLine(AppDomain.CurrentDomain.GetData("TRUSTED_PLATFORM_ASSEMBLIES"));
}
```

**Comment by vitek-karas** [comment]
The `hostpolicy` adds the trailing separator till 2.0, so the change must have come somewhere in the runtime. Not that it matters, we can easily just omit the trailing separator in `hostpolicy`.

**Comment by jkotas** [comment]
> somewhere in the runtime

You are right. It was done here: https://github.com/dotnet/coreclr/blob/release/2.1/src/mscorlib/src/System/AppDomain.cs#L654 . I have deleted this pre-processing for 3.0.

**Comment by vitek-karas** [comment]
I'll fix it in the `hostpolicy` - it's cleaner that way.

**Comment by bording** [comment]
@vitek-karas Since the fix for this was merged to `master`, what release should we expect to see this change in? Preview 4?

**Comment by vitek-karas** [comment]
Not sure - but I think Preview 4 is likely.
