### ISSUE TITLE
Allow specifying AssemblyName rather than full dll path for Startup Hook

### ISSUE THREAD

**Issue by jkotalik** [dotnet/core-setup#5556]
I am trying to use a Startup Hook to specify a first chance exception handler for a scenario in ASP.NET Core. However, I don't necessarily know where the dll location, it could be part of the app (current directory), part of the shared framework (or a nuget package), or a different folder entirely. As we don't know the exact location, we can't use the feature to specify a startup hook.

If we could instead specify the assembly name, that would allow us to work around this issue. 

cc @vitek-karas @sdmaclea

**Comment by sdmaclea** [comment]
We would need a well defined algorithm for finding the assembly.  

Usually when we resolve by AssemblyName, we have the *.deps.json contained in the app path to help us identify the paths to search.  We may be able to use the same algorithm as the App, but it certainly doesn't  satisfy your arbitrary folder requirement `a different folder entirely`

Any particular reason there needs to be more than one of these?  Why can' a single startup hook always be deployed with asp.net?

**Comment by jkotalik** [comment]
> but it certainly doesn't satisfy your arbitrary folder requirement a different folder entirely

Let me be clear, the dll path will be in the `*.deps.json` file. My ask is to use that for loading the startup hook.

> Why can't a single startup hook always be deployed with asp.net?

If you are a native hoster that want's to run hostfxr in the same process and you want a startup hook, you will need to know where a) hostfxr is and b) the user dll that contains Main(). We want to add a startup hook to ASP.NET, which will live in a dll that is part of the shared framework. By requiring a full path, this suddenly puts a 3rd requirement on hosters to find the dll that contains the startup hook. It could either be in the same directory as your app, inside of the shared framework, etc. Finding the dll shouldn't be a responsibility of the shared hoster.

**Comment by sbomer** [comment]
Closing this as a dup of https://github.com/dotnet/coreclr/issues/23343. Let's continue the discussion there.
