### ISSUE TITLE
(Question) How to build a Microsoft.NETCore.App package against private builds of Coreclr & Corefx

### ISSUE THREAD

**Issue by bretambrose** [dotnet/core-setup#565]
It seems like core-setup is the project that actually constructs the Microsoft.NETCore.App package as an artifact but I haven't had any luck finding a way to create this package using internal builds of Coreclr/Corefx.  There don't seem to be any additional build instructions and I haven't found anything so far going through the top-level build shell scripts (haven't looked into project files yet though).  Is this possible (in particular, at the v1.0.0 tag)?  If so, do you have any pointers or documentation that would help?

**Comment by gkhanna79** [comment]
@ellismg Should be able to help as he has been looking into an effort to achieve this goal.

**Comment by ellismg** [comment]
@bretambrose Can you help me understand exactly why you want to build a new Microsoft.NETCore.App package?  Are you trying to get a version of the package with some hot fixes, trying to add a new supported RID to the package, something else?

**Comment by bretambrose** [comment]
This is probably going to be one those "How do we do X?" questions that turn into "X is totally unnecessary, do Y instead", so apologies for that.  Here's our situation:

We are building a .NET execution platform -- using Microsoft.NETCore.App as the baseline -- for several closely-related flavors of rhel7.  For reasons of security policy and glibc versioning we aren't able to use Microsoft rhel7 builds (but we reuse the rhel7 runtime id in our builds); what we deploy must be built by our own network-isolated processes.  We have most of the artifacts building, but as a sanity and correctness check, we'd like to put those artifacts through the package construction process.

At an absolute minimum though, we need a Microsoft.NETCore.App.deps.json that matches our artifacts well enough that all the assembly loading and resolution works as expected for the NETCore artifacts.  The .deps.json file includes signatures and sha512 values of various subpackages and assemblies and my concern is that doing a simple, dumb copy-edit of the .deps.json file in the official rhel7 package would be insufficient to give us correct assembly resolution (ie, are the signature or sha512 values checked).  My (blind) guess was that the NETCore packaging build process generated that file and thus my original interest in trying generate the package with our own builds.

**Comment by ellismg** [comment]
Sorry for the delay in replying.

I assume you're building CoreCLR and CoreFX from the release branches, so the packages that are produced have the correct version numbers to match what Core-Setup is expecting.

In that case, I would suggest you do the following:

0. Copy the nupkg's produced by the CoreCLR and CoreFX builds to some local folder.
1. Edit https://github.com/dotnet/core-setup/blob/master/NuGet.Config and https://github.com/dotnet/core-setup/blob/master/pkg/pack.sh to add your local package source before the existing sources.
2.  `./build.sh --configuration Release --targets Init,Compile,Package`

That should build you a version of Microsoft.NETCore.App (and the tgz of a shared framework).

Do you plan to try to ship a standalone Microsoft.NETCore.App package for your platform (that folks can pull down with NuGet and deploy app localy) or are you just trying to build a shared framework that you'll package yourself and have present so folks can do `dotnet run` or whatever on portable apps?

**Comment by wtgodbe** [comment]
Closing as stale

**Comment by Fasjeit** [comment]
Hi.

Sorry for resurrecting the issue, but I have the same question.

We have a complete fork of corefx with slightly changed cryptography and would like to build sdk and redist for it. So we need somehow to build installer using local corefx build.

I've tried to add local package source (\corefx\artifacts\packages\Debug) to [dir.props](https://github.com/dotnet/core-setup/blob/master/dir.props) and [NuGet.config](https://github.com/dotnet/core-setup/blob/master/NuGet.config), but after I run `build -SkipTests=true` the following happens:

```
C:\_self\git\core-setup\Tools\dotnetcli\sdk\2.1.401\NuGet.targets(114,5): error : The local source 'C:\_self\git\core-setup\tools-local\tasks\https:\dotnetfeed.blob.core.windows.net\dotnet-core\index.json' doesn't exist. [C:\_self\git\core-setup\tools-local\tasks\core-setup.tasks.csproj] [C:\_self\git\core-setup\build.proj]
C:\_self\git\core-setup\build.proj(60,5): error MSB3073: The command ""C:\_self\git\core-setup\Tools/dotnetcli/dotnet.exe" restore --packages "C:\_self\git\core-setup\packages" --source C:\_self\git\corefx\artifacts\packages\Debug --source https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json --source https://dotnetfeed.blob.core.windows.net/dotnet-coreclr/index.json --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://www.myget.org/F/nugetbuild/api/v3/index.json --source https://api.nuget.org/v3/index.json --source https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json --source C:\_self\git\corefx\artifacts\packages\Debug --source https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json --source https://dotnetfeed.blob.core.windows.net/dotnet-coreclr/index.json --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://www.myget.org/F/nugetbuild/api/v3/index.json --source https://api.nuget.org/v3/index.json --source https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json "C:\_self\git\core-setup\tools-local\tasks\core-setup.tasks.csproj" /p:OSGroup=Windows_NT /p:PortableBuild=true /p:TargetArchitecture=x64 /p:ConfigurationGroup=Debug /p:VersionSuffix=preview-27503-0 /p:OutputRid=win-x64" exited with code 1.
```

Looks like nuget get part of online source path as local path. Is there any solution to this or other correct way of building from local corefx?
