### ISSUE TITLE
Platform manifest incorrectly lists version '0.0.0.0' for some assemblies

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#5665]
This causes downstream repos (ASP.NET Core in particular) to fail in some cases.

This appears to be caused by crossgen stripping out versions, then the manifest generation using those versions.

A workaround is to use the original version from the packages being crossgen'd + redistributed.

(More info in an email thread, this issue is mainly for tracking purposes.)

**Comment by dougbu** [comment]
@Eilon what labels would you like to see on this issue?

**Comment by dagood** [comment]
Adding `blocking-partner`, I've it seen used for issues blocking ASP.NET Core uptake before.

**Comment by dougbu** [comment]
@dagood should this be closed now that @davidwrighton got dotnet/coreclr@283cab341daacc in?

Or, should this become a test issue i.e. cover avoiding similar problems in the future?

**Comment by dagood** [comment]
This isn't fixed until Core-Setup uptakes a new CoreCLR build. The auto-update PR https://github.com/dotnet/core-setup/pull/5657 doesn't have one yet, but I think that's subscribed daily. I'll check if there's a new CoreCLR build and get an update through if so.

**Comment by dagood** [comment]
There hasn't been a build yet. The newest CoreCLR build is hitting https://github.com/dotnet/core-eng/issues/5745: https://dev.azure.com/dnceng/internal/_build/results?buildId=142802.

**Comment by dagood** [comment]
New builds ongoing with the crossgen fix:
https://dev.azure.com/dnceng/internal/_build/results?buildId=143031
https://dev.azure.com/dnceng/internal/_build/results?buildId=143167

**Comment by dougbu** [comment]
Doesn't https://dev.azure.com/dnceng/internal/_build/results?buildId=143167 look like it will complete successfully?

To double-check: the "Update dependencies from https://github.com/dotnet/coreclr build 20190404.73" commit includes both of the fixes ASP.NET Core needs?
- dotnet/coreclr@283cab341daacc
- dotnet/corefx@53c0bae174088c3

**Comment by dougbu** [comment]
Oh, I see https://dev.azure.com/dnceng/internal/_build/results?buildId=143167 won't get agents to do the final push

**Comment by dougbu** [comment]
My second question relates to https://dev.azure.com/dnceng/internal/_build/results?buildId=143256

**Comment by dagood** [comment]
(For context, I was wrong with the original builds I posted here--I saw a build running a corefx update and mistook it for the coreclr one. https://dev.azure.com/dnceng/internal/_build/results?buildId=143256 is right.)

The commit does depend on a CoreFX commit with the fix:

https://github.com/dotnet/core-setup/blob/681b17c84947aea293b7cc09373a9292c34c4f37/eng/Version.Details.xml#L4-L6

https://github.com/dotnet/corefx/commits/a4fe9d1599d3ba16534b19b92657cfaac80a65dd

I confirmed with a local build that the CoreCLR update that https://dev.azure.com/dnceng/internal/_build/results?buildId=143256 is running on produces a fixed platform manifest.

**Comment by dagood** [comment]
The build is done! Should come through as `20190404.05`, package version `3.0.0-preview4-27604-05`.

**Comment by dagood** [comment]
PR to add sanity check preventing this from happening again: https://github.com/dotnet/core-setup/pull/5682.
