### ISSUE TITLE
Create WindowsDesktop shared framework in Core-Setup

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#5675]
Create the WindowsDesktop shared framework (packages and MSIs) in Core-Setup. This is based on transport packages produced by DotNet-Trusted.

A primary goal of this work is to enable WindowsDesktop shared framework crossgen: https://github.com/dotnet/core-setup/issues/5580.

This is an initial step towards https://github.com/dotnet/core-setup/issues/5219 "Gather Microsoft.WindowsDesktop.App (WPF, WinForms) in Core-Setup, not DotNet-Trusted".

**Comment by dagood** [comment]
I'm starting to think through what it'll take to switch over. Here's a way I think we could do this without hard-breaking Core-SDK auto-update at any point.

`Msft.WD.App` = `Microsoft.WindowsDesktop.App`
`Msft.CoreSetup.WD.App` = `Microsoft.CoreSetup.WindowsDesktop.App`

1. Change PR https://github.com/dotnet/core-setup/pull/5741 to create `Msft.CoreSetup.WD.App`, not `Msft.WD.App`. Merge.
   * I think two repos producing the same ID would confuse the Core-SDK subscription, so avoid it.
   * **Is this nonstandard sfx package naming a problem a problem in Core-SDK?** Does this cause enough extra throwaway work to tip the scales?
2. In Core-SDK, depend on `Msft.CoreSetup.WD.App`
   * Can also remove DN-T dependency at this point.
3. In DN-T, stop building `Msft.WD.App`.
4. In Core-Setup, build `Msft.WD.App`.
5. In Core-SDK, depend on `Msft.WD.App` again.
6. In Core-Setup, stop building `Msft.CoreSetup.WD.App`.

More breaking, fewer steps, quicker:

1. In DN-T, stop building `Msft.WD.App`, and in Core-Setup, start building it. (Async.)
2. Wait until official builds are ready with the removal and the addition.
   * We might be able to power forward with only the Core-Setup build. My concern would be Maestro++ maybe doing strange updates until the DN-T build goes through.
2. In Core-SDK, take the updates quickly to unblock auto-updates.
   * There is work to do here to use the new Core-Setup-produced MSI, since it gets placed in a different place from `dotnet-extensions-...` and has a different name (`windowsdesktop-runtime-...`). This work should be simple, but it becomes something that blocks auto-updates.

When writing it out, the first one seems a little ridiculously convoluted, but I'm not sure how bad the break could get. I like not breaking people. 😄

@johnbeisner @nguerrera @zsd4yr @vatsan-madhavan @ericstj @mmitche Thoughts? (How about :+1: for non-breaking, in case it's unanimous and I'm overthinking?)

**Comment by vatsan-madhavan** [comment]
> I think two repos producing the same ID would confuse the Core-SDK subscription, 

Are you worried that the two repos (`core-setup `and `dotnet-trusted`) would be concurrently producing packages with the same ID (`Microsoft.WindowsDesktop.App`) in the steady state ? 

`or` 

Would the two repos be producing the same ID for a small interval of time during switchover? 

`or`

Would `dotnet-trusted` stop producing that ID, then core-setup starts producing the same ID (i.e., stop one, then start another); but regardless of that fact, `core-sdk` receives two concurrent updates from each of `dotnet-trusted `and core-setup with the same ID. 

Which of these are you worried about? 

<hr/>

When we moved `Microsoft.NET.Sdk.WindowsDesktop` from `dotnet-trusted` to `dotnet-wpf-int`, and then moved it again to `dotnet/wpf`. In each case, `dotnet/toolset` seemed to adapt to the change fine. 

Likewise, when we moved `Microsoft.Dotnet.Wpf.ProjectTemplates` from `dotnet-trusted` to `dotnet/wpf`, and `Microsoft.DotNET.Winforms.ProjectTemplates` from `DotNET-trusted` to `DotNET/winforms`, `core-sdk` seemed to adapt to it fine.

**Comment by dagood** [comment]
If we did a non-breaking approach, producing the sfx in both Core-Setup and DN-T for a time, then the first one: building the same ID in multiple repos in steady state.

For the breaking approach, the second and third apply, but that's not what concerns me about it. The bigger concern for me is that there are changes needed in Core-SDK to consume from Core-Setup rather than DN-T, since not just NuGet packages are moving over but also MSIs. As soon as the switchover happens, auto-updates from Core-Setup => Core-SDK are blocked until that fix happens. If any Core-Setup fixes are needed, that extends the delay even more.

(I recently experienced a hard break from CoreCLR => Core-Setup that was in the way of preview4, maybe that's making me particularly sensitive to this. 🙂)

**Comment by dagood** [comment]
Chatted with @johnbeisner offline, there aren't any concerns on the Core-SDK side with the break. I'll prep a DN-T PR to stop producing the sfx. Once both PRs are ready to merge, I'll ping @johnbeisner for a final go-ahead and merge both.

If things go really badly, we can revert both PRs to go back.

**Comment by johnbeisner** [comment]
@dotnet/dotnet-cli 
When the auto-generated PR with the new version of core-setup appears in core-SDK, I'm expecting that PR to fail because it can't find these renamed assets [MSI & ZIP]. We should be able to make the ~3-line change for core-SDK in that PR.

**Comment by zsd4yr** [comment]
> `Microsoft.DotNET.Winforms.ProjectTemplates` from `DotNET-trusted` to `DotNET/winforms`, `core-sdk` seemed to adapt to it fine.

Actually... I think @mmitche and I saw an issue where there was a collision in BAR

**Comment by mmitche** [comment]
@zsd4yr It will be fine as long as they don't produce them at the same time.

**Comment by dagood** [comment]
I just merged both PRs, and I'm keeping an eye on the official builds:
DotNet-Trusted: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2582898
Core-Setup: https://dev.azure.com/dnceng/internal/_build/results?buildId=153305

**Comment by dagood** [comment]
I missed making zips in Core-Setup, submitted https://github.com/dotnet/core-setup/pull/5816 to add those.

**Comment by dagood** [comment]
Forgot to mention, this went though and @johnbeisner picked it up with https://github.com/dotnet/core-sdk/pull/1447. 🎉
