### ISSUE TITLE
dotnet host should provide clearer error messages when app content is missing

### ISSUE THREAD

**Issue by TheRealPiotrP** [dotnet/core-setup#570]
## Steps to reproduce
`dotnet new; dotnet build; cp bin/Debug/netcoreapp1.0/hello.dll . dotnet hello.dll`

## Expected  behavior
Error message stating that `runtimeconfig.json` is missing, or something describing the artifact that is preventing the app from launching.

## Actual behavior
`library 'libhostpolicy.dylib' required to execute the application was not found`

Granted, running an app that wasn't published is not a designed-for scenario. However, since we're printing an error message that points to some symptom, it would be great to specify a more actionable symptom.

This issue is a digest of https://github.com/dotnet/cli/issues/4268 from @kumpera.

**Comment by gkhanna79** [comment]
@ramarag PTAL.

CC @schellap

**Comment by schellap** [comment]
If runtimeconfig is missing, we default to running a standalone app with dotnet. The next step is to find hostpolicy.dll which is missing.

We could probably detect that this is a standalone invocation using dotnet.exe and print a slightly different message.

But I don't think we should go through the pains of detecting such an invocation just for flagging. We should just modify the error message to say: "Additionally, check if you are `doing bad thing`."

**Comment by schellap** [comment]
Also, the error message is actually accurate, but it can be more helpful. The artifact that is missing is hostpolicy. Missing runtimeconfig is still a valid app and is also an implementation detail that users should not need to know about.

**Comment by alexanderuv** [comment]
I found this issue today as well, is there any solution? Why do we need the runtime json file?

**Comment by gkhanna79** [comment]
Runtimeconfig.json is required to when building apps that run against Shared FX (i.e. Microsoft.NETCore.App FX). If it is missing, then we expect the app to be standalone and go down that path for activation and any missing components will be raised (as in the message above).

To attempt to run the app, as in the example above, is a user-error since that is not a supported publish/activation model.

**Comment by ramarag** [comment]
@gkhanna79 what is the error message that we should be giving ?

**Comment by gkhanna79** [comment]
@ramarag Why don't you suggest an appropriate solution for this :) ?

**Comment by FailMelon** [comment]
Can there not be an option in build settings and in back-end to check for it as an embedded resource since it is a required file?

**Comment by gkhanna79** [comment]
This file is not an embedded resource but a metadata option.

**Comment by FailMelon** [comment]
When building either through just a debug build or a published build runtimeconfig is required for the dll  to run, should there not be a way to embed a required config file into the app itself? It seems a bit silly to require a config file outside of the app for it to even work.

**Comment by gkhanna79** [comment]
The metadata will be inserted in <app>.deps.json, which is a build time artifact that is required and generated by the build all the time.

**Comment by FailMelon** [comment]
Think you've misunderstood what I've mean i have moved it over to here #1964 since its kind of off topic sorry .

**Comment by pcgeek86** [comment]
I downloaded an older version of the .NET Core SDK on Mac, because I need to support `project.json`, but I'm getting this error:

```
A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in <path>
```

How can I work around this?

**Comment by steveharter** [comment]
Closing this as dup of https://github.com/dotnet/core-setup/pull/3382

That added the following to the existing error message:
```Failed to run as a standalone app because there is no '<dir>\<app>.runtimeconfig.json' file. If this should be a portable app instead, add that file specifying the appropriate framework.```
