### ISSUE TITLE
Uninstalling 1.1.0-preview1 runtime breaks 1.0.1 runtime - Fix in 2.0.x

### ISSUE THREAD

**Issue by shirhatti** [dotnet/core-setup#572]
## Steps to reproduce

1. Install [1.0.1 runtime](https://go.microsoft.com/fwlink/?LinkID=827515)
(I see that the `C:\Program Files\dotnet\host\fxr\1.0.1` directory gets created)
2. Install [1.1.0-preview1 runtime](https://go.microsoft.com/fwlink/?LinkID=831444)
3. Uninstall 1.1.0-preview1 runtime
(There is no longer a `C:\Program Files\dotnet\host` directory)
## Expected  behavior
```
$ dotnet

Microsoft .NET Core Shared Framework Host

  Version  : 1.0.1
  Build    : cee57bf6c981237d80aa1631cfe83cb9ba329f12

Usage: dotnet [common-options] [[options] path-to-application]

Common Options:
  --help                           Display .NET Core Shared Framework Host help.
  --version                        Display .NET Core Shared Framework Host version.

Options:
  --fx-version <version>           Version of the installed Shared Framework to use to run the application.
  --additionalprobingpath <path>   Path containing probing policy and assemblies to probe for.

Path to Application:
  The path to a .NET Core managed application, dll or exe file to execute.

If you are debugging the Shared Framework Host, set 'COREHOST_TRACE' to '1' in your environment.

To get started on developing applications for .NET Core, install .NET SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

## Actual behavior
```
$ dotnet
A fatal error occured, the required library hostfxr.dll could not be found at C:\Program Files\dotnet
```

## Environment data
`dotnet --info` output:
```
A fatal error occured, the required library hostfxr.dll could not be found at C:\Program Files\dotnet
```

cc @joeloff @jhkimnew

**Comment by gkhanna79** [comment]
I believe @schellap has this fixed in 1.1.0 final builds. @schellap can you confirm and if so, close this issue.

**Comment by VikSab** [comment]
is there any workaround or fix for this issue

my system is hosed currently with the same problem

**Comment by gkhanna79** [comment]
Have you tried to reinstall the 1.0.1 SharedFW again?

**Comment by schellap** [comment]
@gkhanna79, this issue has different repro steps. Will take a look.

**Comment by VikSab** [comment]
@schellap Yes i have done that as well - but it doesnt work... the only way it to roll forward it seems

**Comment by nswali** [comment]
@shirhatti  Workaround in windows: if you repair the previous 1.0.1 install seems, you get your expected behavior.

**Comment by Ponant** [comment]
I just ran into this issue after I installed and uninstalled the .NET Core SDK 2.0. Is there a workaround?

**Comment by joeloff** [comment]
@Ponant If the 1.x runtime is installed you can try repairing that.

**Comment by Ponant** [comment]
@joeloff , I am reparing VS 2017 RC4 at the moment, I expect it to work.

**Comment by gkhanna79** [comment]
Assigning this to you @rakeshsinghranchi and @vivmishra

**Comment by rakeshsinghranchi** [comment]
This issue is fixed in 2.0.0 . https://github.com/dotnet/core-setup/pull/1571#pullrequestreview-23143709

**Comment by gkhanna79** [comment]
@rakeshsinghranchi Do you have the 1.1.x and 1.0.x version of the issue filed? If so, please close this.

**Comment by rakeshsinghranchi** [comment]
@gkhanna79  Yes. 
1.0.x : https://github.com/dotnet/core-setup/issues/1574
1.1.x:https://github.com/dotnet/core-setup/issues/1575

**Comment by Ramprits** [comment]
Thanks It's working now.
