### ISSUE TITLE
.deps.json RID asset resolution should be per asset type

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/core-setup#5728]
Currently `hostpolicy` resolves RID specific assets in `runtimeTargets` section by doing this:
* Find the most specific compatible RID which has at least one asset in the `runtimeTargets` section
* Filter the assets in that section to only those with that specific RID, throw all the rest away

This means that package can't have for example:
* managed assembly for RIDs: `win` and `Linux`
* native library for RIDs: `win-x86`, `win-x64`, `linux-x64` and `linux-arm`

For example let's take such package on `win10-x64` platform.
* The most specific RID which has at least some asset will be `win-x64` (the native library is available for that)
* All assets which are not exactly `win-x64` will be filtered out, this includes all managed assembly assents (since those are either `win` or `linux` but no `win-x64`)

The end result is that such an app would probably fail to run, as it would missing the managed assembly completely.

An example of this issue is with recent builds of the `System.Device.Gpio` package which has `linux` managed assembly and `linux-arm` native library. So running it on a `linux-arm` RID fails.

The correct behavior is to follow what NuGet does here. It should be the same result building the app as portable (thus having the above mentioned `runtimeTargets` section with RID specific assets) and running it (in which case `hostpolicy` performs the asset selection), or publishing the app for a specific RID only (in which case NuGet performs the asset selection).

NuGet behavior translates to:
* Group the assets in the `runtimeTargets` section by their `assetType` (`runtime`, `native`, …)
* For each group:
  * Determine the most specific compatible RID with asset in the group
  * Filter the group to only assets with the selected RID

With this behavior the above example would work, since the managed assembly is in a different group (`runtime`) from the native library (`native`) and thus it would resolve as `win` managed assembly and `win-x64` native library.

**Comment by raffaeler** [comment]
Can you suggest any workaround in the meanwhile?
Running the app with `dotnet run -r linux-arm` is not an option because it takes roughly 30 seconds to run.
You may want instead run directly the app `./bin/debug/netcoreapp3.0/test1' but you can't specify the `-r linux-arm` on the command line, therefore the app execution will fail.

Suggestions?

**Comment by raffaeler** [comment]
Ok, I added the RID in the PropertyGroup but this isn't a great workaround. I am eager to know if any other option exists. TIA.

**Comment by vitek-karas** [comment]
You should be able to publish the app for the platform, so `dotnet publish -r linux-arm` and then run it directly from the publish folder.
`dotnet run` is slow because it's basically msbuild + run.

Note: I haven't tried this as I don't have an easy access to Linux+ARM device right now.

**Comment by raffaeler** [comment]
Thank you, can you share which preview will **likely** contain the bug fix?

**Comment by vitek-karas** [comment]
It's basically the next thing on my TODO list... so hopefully Preview 6 (Preview 5 is basically done), but no promises yet.

**Comment by vitek-karas** [comment]
@raffaeler  Took longer than I expected... the fix is in master, so you should be able to pick up a daily build tomorrow with it. And it will be in Preview 7.
