### ISSUE TITLE
Move WindowsDesktop shared framework generation into another repo

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#5732]
https://github.com/dotnet/core-setup/issues/5219 tracks moving WindowsDesktop gathering into Core-Setup, but it's mostly for pragmatic reasons. Targeting pack, runtime pack, and shared framework tooling exists in Core-Setup today and is not easily shareable, and using Core-Setup allows us to dissolve DotNet-Trusted in a reasonable timeframe.

Once tooling is shareable (#4773, #4776, ...?) the WindowsDesktop shared framework should be built in a different repo. Broadly speaking, this is similar to how the ASP.NET Core shared framework builds in a different repo.

This specifically allows testing against the current netcoreapp shared framework in WinForms and WPF. Both shared frameworks being built by one repo introduces a testing cycle, so the dependency has to be some N-1 (or N-x). If WPF and WinForms feed into a separate repo, this breaks the cycle:

```
+-> wpf +------------+
|                    v
+-> winforms +--> core-setup +
|                    ^       |
+-> corefx +---------+       |
|                            |
+-----netcore-sfx------------+


corefx +--> core-setup +--> wpf +----+-> windowsdesktop
  ^                    |             |
  +---netcore-sfx------+--> winforms +
```

(Right now it's a bit worse than the diagram: WPF and WinForms test on the netcoreapp in the CLI output, which is normally even older.)

The most impactful aspect of this is how it will help the WPF and WinForms tests. Thanks @ericstj for pointing this out.

/cc @zsd4yr @vatsan-madhavan

**Comment by dagood** [comment]
It turns out this also helps with branching... https://github.com/dotnet/core-setup/issues/7343.

**Comment by vatsan-madhavan** [comment]
Is the plan to refactor and expose the tooling through the Arcade SDK?

**Comment by dagood** [comment]
Yep, https://github.com/dotnet/core-setup/issues/4787 tracks that. I'm hoping we can get past the point where splitting a repo means duplicating all the infra inside it (like CLI => Core-Setup all that time ago).

**Comment by dagood** [comment]
@vatsan-madhavan, @zsd4yr, and I chatted about this offline, **dotnet/windowsdesktop** seems like a reasonable new repo name.

This also unlocks some other improvements that can be made over time: there's some code that would be much better off moved to dotnet/windowsdesktop, like project templates and the windowsdesktop SDK. (Hence no `-setup` suffix!)

**Comment by dagood** [comment]
Complete: WindowsDesktop is now removed from Core-Setup and built in https://github.com/dotnet/windowsdesktop.
