### ISSUE TITLE
After preview4, upgrade Microsoft.DotNet.Feed.Task to 2.2.0-beta.19208.9 on release/3.0 branch

### ISSUE THREAD

**Issue by jcagme** [dotnet/core-setup#5753]
For reference see description and conversation on: https://github.com/dotnet/core-setup/pull/5749

This change has been applied to `master` but we decided to hold of changing this on `release/3.0` to avoid risks close to stabilization. So we need to make it once preview4 has shipped.

The new version **has** to be `2.2.0-beta.19208.9` since it has the `Nuget.Common` version that works well with other references in `core-setup`.

/cc @dagood @mmitche

**Comment by dagood** [comment]
This should get picked up automatically by merges from `master` => `release/3.0` when the branch opens post Preview 4. (No reason not to track it though IMO.) /cc @wtgodbe

**Comment by dagood** [comment]
Version updated a while ago, and is now far past `2.2.0-beta.19208.9`.

https://github.com/dotnet/core-setup/blob/33656b4bd015e62836fb3ee52a914b73c40052e9/eng/Versions.props#L39
