### ISSUE TITLE
Package dotnet-host-2.2.4-x64.rpm is not signed

### ISSUE THREAD

**Issue by lbosnjak** [dotnet/core-setup#5759]
## Steps to reproduce
dnf update dotnet-host

## Expected  behavior
successful update of the package to version 2.2.4-1

## Actual behavior
```
Package                           Architecture                 Version                       Repository                                         Size

Upgrading:
 dotnet-host                       x86_64                       2.2.4-1                       packages-microsoft-com-prod                        44 k

Transaction Summary

Upgrade  1 Package

Total download size: 44 k
Is this ok [y/N]: y
Downloading Packages:
dotnet-host-2.2.4-x64.rpm                                                                                              81 kB/s |  44 kB     00:00    
--
Total                                                                                                                  80 kB/s |  44 kB     00:00     
Package dotnet-host-2.2.4-x64.rpm is not signed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
```
## Environment data
fedora 29

## Additional notes
I get the same error when trying to install dotnet-sdk-2.2

**Comment by dagood** [comment]
@leecow are you aware of this?

**Comment by leecow** [comment]
Yep, @vivmishra is in the process of correcting.

**Comment by leecow** [comment]
@lbosnjak - Which distro and version are you using?

**Comment by dagood** [comment]
@vivmishra can you please update this issue with status? How long will it take to resolve this?

> lbosnjak - Which distro and version are you using?

I hope nothing's waiting on a response to this--the issue mentions Fedora 29, and based on the back-ref dotnet/core issues this affects other RPM packages too.

**Comment by dagood** [comment]
Fedora 28 is confirmed good, @leecow will confirm for Fedora 29. CentOS is still down.

**Comment by zhouyongtao** [comment]
me too

**Comment by emonhaider** [comment]
Any update on the fix for CentOS?

**Comment by vivmishra** [comment]
Update: 2.1 is working ok but 2.2 is still being investigated.

**Comment by vivmishra** [comment]
Even 2.2 is working now.  Plz give it a try.

**Comment by cjsmith26** [comment]
2.2 is still failing for me

**Comment by leecow** [comment]
@cjsmith26 - what specifically are you seeing? 

I just re-confirmed good install of dotnet-sdk-2.1 and dotnet-sdk-2.2 on a clean centos 7 image. One thing you may try is cleaning out the yum cache with `yum clean all`. An even bigger hammer is to delete the package cache `rm -rf /var/cache/yum/` then run `yum update` again.

**Comment by cjsmith26** [comment]
@leecow I had to run both `yum clean all` and `rm -rf /var/cache/yum/` with `yum update` and then try again. Thank you

**Comment by leecow** [comment]
@cjsmith26 - just to make sure ... you're up and running now?

**Comment by cjsmith26** [comment]
@leecow Yes, all resolved

**Comment by AeonLucid** [comment]
Can confirm this is fixed for me as well on CentOS 7.
All I had to run was `yum --enablerepo=packages-microsoft-com-prod clean metadata`, the commands above were not necessary.

**Comment by vivmishra** [comment]
Thanks all, closing the issue.
