### ISSUE TITLE
libicu55 dependencies conflicts with libcicu60 used by others

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#5780]
@jaykrell commented on [Wed Apr 10 2019](https://github.com/dotnet/core/issues/2567)

Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current#ubuntu18-04-issue
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

---

@karelz commented on [Wed Apr 10 2019](https://github.com/dotnet/core/issues/2567#issuecomment-481743218)

Looks similar to #1822 -- @dagood?
cc @omajid @tmds @tarekgh 

---

@dagood commented on [Wed Apr 10 2019](https://github.com/dotnet/core/issues/2567#issuecomment-481750308)

No, this looks related to the unfortunate version-specific `libicuXX` dependency in our Debian packages.

The Ubuntu 18.04 `dotnet-runtime-deps-2.2` package *should* depend on `libicu60`, so this conflict doesn't make sense. I have a writeup of this issue at https://github.com/dotnet/core-setup/issues/4247#issuecomment-480553725 for some more info how how this could be caused. (Basically: unclean system.)

@jaykrell, can you provide logs of what's going wrong, and run these steps to diagnose?

```sh
# Shows the repositories you have configured. Source: https://askubuntu.com/a/741948
grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
# Show what version of libicu you have available to you.
apt search libicu
# Show your distro version.
cat /etc/os-release
# This install command will show exactly which dependency can't be met.
sudo apt-get install dotnet-runtime-deps-2.2
```

---

@karelz commented on [Wed Apr 10 2019](https://github.com/dotnet/core/issues/2567#issuecomment-481753369)

@dagood should we move it to core-setup? Or is it too early?

---

@dagood commented on [Wed Apr 10 2019](https://github.com/dotnet/core/issues/2567#issuecomment-481761407)

Good point, moving.

**Comment by jaykrell** [comment]
Some additional commands moved the dependency up fro icu55 to icu60.

**Comment by dagood** [comment]
Good to hear, thanks for getting back to us. 😄 Closing as resolved.
