### ISSUE TITLE
Readme official build links

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#579]
It looks like we're missing links to the official builds of a few distro's that we're providing binaries for. The build status should also just me moved inline with the other table.

**Comment by gkhanna79** [comment]
Looks like you are already on cleaning this space up @Petermarcu :)

**Comment by Petermarcu** [comment]
@gkhanna79 , Is there an official build for Win ARM32?

**Comment by gkhanna79** [comment]
Yes, that is how packages are published that get linked here.



Thanks,
Gaurav


-------- Original message --------

**Comment by Petermarcu** [comment]
Ah, I missed the "show more" in the official builds list.

**Comment by Petermarcu** [comment]
@gkhanna79, we have 3 trains, 1.0.X, 1.1.X, and master. We're only tracking two so far and I only see pairs in the official definitions. Is it correct that release.1.0.0 is 1.0.X and master is master. That means we don't have anything for 1.1.X?

**Comment by gkhanna79** [comment]
Yes, that is correct. I didnt know if we wanted to call out unreleased binaries (given that they are in Escrow) ahead of the release.
