### ISSUE TITLE
Assertion framework-version-resolution spec error

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/core-setup#5813]
This part of the [framework-version-resolution spec](https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/framework-version-resolution.md) is completely wrong

+ `Minor` - if the exact `major.minor` is found, then the equal or lowest higher patch version is used. Otherwise the lowest higher minor is found and the lowest patch is used.
+ `Major` - if the exact `major` is found, the rules for `Minor` above are followed. Otherwise the lowest higher `major.minor.patch` is selected (so lowest patch available for a given `major.minor`).

Is should be
+ `Minor` - `applyPatches=false`, option ignored.  Behavior `Minor` behavior is unchanged.
+ `Major` - `applyPatches=false`, option ignored., Behavior `Major` behavior is unchanged.

**Comment by sdmaclea** [comment]
@vitek-karas said in https://github.com/dotnet/core-setup/pull/5691#discussion_r274874534
`applyPatches` is a modifier - at least that's how it worked in 2.* and it exists in the code solely for backward compatibility reasons. I tried hard to not change the behavior for 2.* in any way. I was only partially successful:
* For release versions, the behavior is almost identical as before (one special case where it used to fail and now it works, and then the better retry logic)
* For pre-release versions the changes are much bigger. That said pre-release backward compat is sort of moot
  * Apps which use 2.* pre-release versions should be very rare by now
  * New apps which will use 3.0 pre-release will get the new behavior and should be perfectly fine with it.
  * Potential new apps which target 3.0 pre-release and use old-style `rollForwardOnNoCandidateFx` or `applyPatches` should be even rarer and the behavior there is different but still reasonable.

To keep the 2.* release to work as close to previous as possible, the code needs to keep `applyPatches` separate from `rollForward` exactly because the `applyPatches` acts as a modifier. It basically says: Once you're done picking version using the `rollForward` rules, normally you should then roll forward to latest patch of that version, but `applyPatches` may disable that behavior.
In theory it could be incorporated into the `rollForward` setting the way @elinor-fung  suggested, but also as she suggested, it introduces rather weird unification rules. Please note, that the unification rules are from the 2.* implementation so we don't have freedom in changing them (well unless we would be OK with breaking changes).

**Comment by sdmaclea** [comment]
@sdmaclea said in https://github.com/dotnet/core-setup/pull/5691#discussion_r274972761 and https://github.com/dotnet/core-setup/pull/5691#discussion_r274977632

> It basically says: Once you're done picking version using the rollForward rules, normally you should then roll forward to latest patch of that version, but applyPatches may disable that behavior.

This makes no sense.  In no way could the App predict that it would allow rolling forward `major` or `minor`, but applying patches wouldn't be acceptable. We certainly shouldn't treat it that way in 3.*.  If we do it is a major & minor 😁  new bug we are introducing.

This part of the spec is completely wrong

+ `Minor` - if the exact `major.minor` is found, then the equal or lowest higher patch version is used. Otherwise the lowest higher minor is found and the lowest patch is used.
+ `Major` - if the exact `major` is found, the rules for `Minor` above are followed. Otherwise the lowest higher `major.minor.patch` is selected (so lowest patch available for a given `major.minor`).

Is should be
+ `Minor` - `applyPatches=false`, Behavior `Minor` behavior is unchanged.
+ `Major` - `applyPatches=false`, Behavior `Major` behavior is unchanged.

**Comment by sdmaclea** [comment]
Another argument.
3.0 is introducing roll-forward `Major`, this will affect existing `2.x` apps.  This is a bigger breaking change than ignoring `applyPatch=false` on `Minor` or `Major` rollforward.

**Comment by elinor-fung** [comment]
I definitely dislike the way `applyPatches` exists / is treated now, but I can see the backwards compat argument.

> Please note, that the unification rules are from the 2.* implementation so we don't have freedom in changing them (well unless we would be OK with breaking changes).

To @sdmaclea's point about already introducing breaking changes, I think if we were to change the unification rules, it would be relaxing the merged constraints so it would not hit 'used to work' -> 'now fails'?

> We certainly shouldn't treat it that way in 3.*. If we do it is a major & minor 😁 new bug we are introducing.

Aren't we already treating it that way in 2.*? (pick version based on `rollForwardOnNoCandidateFx`, roll to latest patch of that unless `applyPatches=false`)

> 3.0 is introducing roll-forward `Major`

I thought `Major` already existed in the form of `rollForwardOnNoCandidateFx=2`?

**Comment by sdmaclea** [comment]
Vitek and I discussed this at some length. 

My bried summary.  My statement "3.0 is introducing roll-forward `Major`" was erroneous. The feature existed but the implemntatiuon was changing it.

What actually seemed to be happening was 3.0 `Major` rollforward was a superset of the new `LatestMinor` behavior.  This was an overlooked breaking change which will be fixed. `Major` will now be a superset of `Minor`, `LatestMajor` will now be a superset of `LatestMinor`.  We will not introduce MajorLatestMinor`

The problem is broken down into two pieces:
* How to describe a `framework version constraint`
* How to merge `framework version constraint`s to get the more restrictive behavior.

`applyPatch` will move into the `framework version constraint` so it will no loinger impact the implementation significantly.

We should consider whether we need more flexibility in the design of the `framework version constraint`
