### ISSUE TITLE
Problem encountered on installation of DotNet on Linux Fedora 29 - x64

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#5832]
@HenrikBach1 commented on [Sat Apr 13 2019](https://github.com/dotnet/core/issues/2583)

Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Fedora 28 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I followed your above installation guide.

When I tested my `dotnet` installation in a new terminal, I got the below result:

```
[sad@localhost ~]$ dotnet
bash: dotnet: command not found
[sad@localhost ~]$ echo $PATH 
/home/sad/.local/bin:/home/sad/bin:/home/sad/.local/bin:/home/sad/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin
```

However, my Operating System is: `Linux Fedora 29 - x64`

/Henrik

---

@dagood commented on [Sat Apr 13 2019](https://github.com/dotnet/core/issues/2583#issuecomment-482854032)

Moving to Core-Setup, this could be a problem with the `dotnet-host` package.

**Comment by dagood** [comment]
Thanks for the report, @HenrikBach1. A few initial things to confirm:

The RPM packages should have installed a `dotnet` symlink at `/usr/bin/dotnet`. That's how it should normally be showing up in `PATH`. Your `PATH` does have `/usr/bin`, so it *seems* the symlink isn't there. Can you verify with `ls -l /usr/bin/dotnet`?

Can you provide the contents of `/var/log/dnf.log` around the time of install?

Do you know if you installed an update to your dotnet packages, or is this a fresh install? Does this repro on a fresh machine (or VM, or Docker container)?

---

For some background, Fedora 29 is supported and I'd expect the Fedora 28 instructions to work fine for you, the dropdown is just out of date.

I did recently change the way the symlink is installed to be more conventional, which may be related, but I'm not sure how yet: https://github.com/dotnet/core-setup/issues/5221.

**Comment by HenrikBach1** [comment]
Hi @dagood ,

With respect to your comments and troubleshooting:

* `ls -l /usr/bin/dotnet` is:
```
[sad@localhost ~]$ ls -l /usr/bin/dotnet
ls: cannot access '/usr/bin/dotnet': No such file or directory
[sad@localhost ~]$ sudo ls -l /usr/bin/dotnet
[sudo] password for sad: 
ls: cannot access '/usr/bin/dotnet': No such file or directory
```
* I cannot find any evidence for the time of install in the log. So, it has probably some thing to do with an error 40 :-( Thus, I tried a new install and verification with success :-)

Issue may be closed.

Thank you for your quick response.

/Henrik

**Comment by vitek-karas** [comment]
Thanks a lot @HenrikBach1 for trying again and letting us know it works.
