### ISSUE TITLE
Shared Host InstalledVersions registry key is outside WOW6432Node, unlike others

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#5872]
Most of the time, installing the .NET Core runtime puts registry keys under WOW6432Node. However, the 3.0.0-preview3-27503-5 x64 sharedhost key can be found outside (and I see 3.0.0-preview4-27610-12 outside as well). What determines this, what is expected?

**Comment by dagood** [comment]
Based on https://github.com/dotnet/cli/issues/2588, it is intended for the keys to always be installed under `WOW6432Node` so that 32-bit installers can access them to determine what 64 bit versions are installed.

It appears `Win64="no"` controls this, and it's missing for the host installer:

https://github.com/dotnet/core-setup/blob/39abaa2bd2ecb4cbd0a6e6ca37f16a23e3bc532b/src/pkg/packaging/windows/sharedframework/registrykeys.wxs#L6-L7

https://github.com/dotnet/core-setup/blob/39abaa2bd2ecb4cbd0a6e6ca37f16a23e3bc532b/src/pkg/packaging/windows/host/host.wxs#L38-L40

Seems like a bug.

**Comment by dagood** [comment]
@vitek-karas @swaroop-sridhar are you aware of any specific reason the host MSI in particular is supposed to put `SOFTWARE\dotnet\Setup\InstalledVersions\$(var.Platform)\sharedhost` in the 64-bit registry, or agree it's a setup bug?

**Comment by vitek-karas** [comment]
Nope - no idea. I think it should be a bug.
@johnbeisner might know?

**Comment by dagood** [comment]
@johnbeisner @joeloff Is this a bug (that should be fixed for 3.0)?

The affected code lives over here now:

https://github.com/dotnet/core-setup/blob/a307f0df21061400efeaf50b267f032a09146fee/src/pkg/projects/Microsoft.NETCore.DotNetHost/host.wxs#L23-L27

(`RegistryKey` missing `Win64="no"`.)

**Comment by johnbeisner** [comment]
The risk of moving this key is that a consumer of this key will not be able to find it going forward. I'm not aware of anything that uses this key - doesn't mean that it doesn't exist.

**Comment by dagood** [comment]
I believe I ran into this initially when someone asked me where it was, because they couldn't find it. But you're right, there are likely others who managed to find the key and now depend on it as it is now, and would be broken if we moved it.

Closing, unless I hear otherwise.
