### ISSUE TITLE
Sentinel and cache files not removed when uninstalling .NET Core SDK

### ISSUE THREAD

**Issue by scottaddie** [dotnet/core-setup#5946]
## Steps to reproduce
1. Uninstall the .NET Core SDK via Win10's Control Panel:

![image](https://user-images.githubusercontent.com/10702007/56444142-2a540080-62bd-11e9-8cf6-d151044d78b8.png)

2. Navigate to the _%USERPROFILE%/.dotnet_ directory. Notice that _sentinel_ and _*.dotnetUserLevelCache_ files are left behind. The following screenshot shows the files are left behind after uninstalling .NET Core SDK 2.2.104:

![image](https://user-images.githubusercontent.com/10702007/56444039-b3b70300-62bc-11e9-937b-727badeaf062.png)

## Expected  behavior
The version-specific files depicted in the screenshot above should be deleted.

## Actual behavior
The version-specific files depicted in the screenshot above aren't deleted.

## Environment data
Win10 v1809

**Comment by dagood** [comment]
The SDK installer is created in https://github.com/dotnet/core-sdk, but these files look to me like they're created during SDK usage (or first run) rather than placed directly by the installer. Moving to https://github.com/dotnet/cli with that in mind.

**Comment by dagood** [comment]
Issue moved to [dotnet/cli #11214](https://github.com/dotnet/cli/issues/11214) via [**ZenHub**](https://www.zenhub.com/)
