### ISSUE TITLE
Add switch in source to stop publishing symbol packages to MyGet

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#595]
For release branches, we need to stop publishing symbol packages to MyGet. We need to continue publishing them for other branches.

This can be implemented with filters in https://github.com/dotnet/core-setup/blob/master/build_projects/dotnet-host-build/PublishTargets.cs checking the end of the files for `.symbols.nupkg` based on the `BRANCH_NAME` or `CHANNEL` in https://github.com/dotnet/core-setup/blob/master/branchinfo.txt (as flowed through the build context).

I think it should be based off the current branch specified in that file because it's the most likely thing I can think of to be kept up to date.

Not a large task, but tracking it in an issue in case someone else needs to pick it up.

**Comment by gkhanna79** [comment]
@leecow @Petermarcu Should this be done for 1.1.0? Doing so would require respinning and I would suggest we do this for 1.1.x.

CC @schellap @wtgodbe

**Comment by dagood** [comment]
The alternative is to remove the package from the MyGet feed manually, and if we can't do that by normal means we can ask MyGet to help. I'll test this out this afternoon on a test feed to see if we can remove it ourselves.

We can also overwrite what's there with a blank symbol package, although that's a bit misleading.

**Comment by dagood** [comment]
I didn't find any endpoint to delete the symbol package directly, but if you delete the package, the symbol package gets deleted too. So, to remove the symbol package we can just delete and reupload the library package.
