### ISSUE TITLE
Should crossgen run on WindowsDesktop resource DLLs for the shared framework?

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#5975]
From https://github.com/dotnet/core-setup/pull/5942#pullrequestreview-228845935:

> [@dagood] I'm actually not sure why I assume resource DLLs shouldn't be crossgenned. Let me know if these should be, or if there are concrete reasons either way. I'll merge this PR without crossgenning them if I don't hear otherwise.

> [@zsd4yr] isn't crossgening resource dll's sort of a no-op? Because they contain no logical code?

> [@dagood] That would make sense, but crossgenning reduces the size of e.g. `de/PresentationCore.resources.dll` from 103 KB to 94 KB. 😕

> [@vatsan-madhavan] /cc @fadimounir

> [@dagood] GitHub won't let me attach the input/output to help compare, but this RSP will do it in the repro dir I shared via email:
> 
> ```
> -readytorun
> -in wd\de\PresentationCore.resources.dll
> -out wd-out/PresentationCore.resources.dll
> -platform_assemblies_paths wd\;corefx\;coreclr\
> -Platform_Winmd_Paths winmd
> -JITPath jit\clrjit.dll
> ```

**Comment by vatsan-madhavan** [comment]
See https://github.com/dotnet/wpf/pull/596#issuecomment-483776249

**Comment by dagood** [comment]
Thanks for finding that, closing as "no" until we get info otherwise.
