### ISSUE TITLE
Update copyright date in 19.04 runtime-deps

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#5996]
https://github.com/dotnet/core-setup/blob/03e6fda1ab2ddb7317f735bc68cdd739f0865d9a/src/pkg/packaging/deb/dotnet-runtime-deps-debian_config_ubuntu.19.04-x64.json#L25-L28

@rakeshsinghranchi mentioned this in https://github.com/dotnet/core-setup/commit/03e6fda1ab2ddb7317f735bc68cdd739f0865d9a#r33267316.

Should this just be based on the build date? Is there a reason to pin it at the file creation date?

@leecow @dleeapho

**Comment by leecow** [comment]
I'm not aware of any requirement to pin to creation date.
