### ISSUE TITLE
Fix Unix build to add  `-Weverything` and  `-Werror` (as the CoreFX PAL does)

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/core-setup#6051]
Right now it has neither.

https://github.com/dotnet/core-setup/issues/6050

**Comment by danmosemsft** [comment]
cc @eerhardt

**Comment by eerhardt** [comment]
cc @vitek-karas @jeffschwMSFT

**Comment by omajid** [comment]
I would recommend against adding `-Weverything`:

> For context, I'm a Clang developer working at Google....
>
> `-Weverything`: This is an insane group that literally enables every warning in Clang. Don't use this on your code. It is intended strictly for Clang developers or for exploring what warnings exist.

Source: https://softwareengineering.stackexchange.com/questions/122608/clang-warning-flags-for-objective-c-development/124574#124574

Additional comments on that: https://quuxplusone.github.io/blog/2018/12/06/dont-use-weverything/

**Comment by danmosemsft** [comment]
I mentioned `-Weverything` because it's what's [used in CoreFX](https://github.com/dotnet/corefx/search?q=-weverything&unscoped_q=-weverything). Didn't look at CoreCLR.

**Comment by danmosemsft** [comment]
@jkotas does the VM already build with the most appropriate warning level?

**Comment by jkotas** [comment]
@janvorli and other folks have done passes to enable as much warnings as reasonably possible for CoreCLR some time ago.

Building with the verbose warning levels puts us on a treadmill to keep up with new versions of the C/C++ compilers (like https://github.com/dotnet/coreclr/pull/24288 that I have just merged). It is rare for these warnings to find actual product bugs. It always makes me wonder about the cost/benefit ratio of these verbose warning levels.

**Comment by danmosemsft** [comment]
Fair enough.
