### ISSUE TITLE
Native hosting end to end

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/core-setup#6084]
This is for tracking additional work necessary for the various native hosting scenarios:
* [x] Consider support for entry point with command line parsing capabilities - #6388 
* [x] Define and implement behavior of new native hosting APIs when used with single-file bundles
* [x] Tracking - ASP.NET SDK should block building single-file apps with IIS in-proc hosting - aspnet/AspNetCore#10344
* [x] SDK Support - currently classlib projects don't produce any `.runtimeconfig.json`. In order to use components through the native hosting API, there should be a way to build a classlib project with `.runtimeconfig.json`. Also should by default setup the roll-forward correctly (probably `LatestMinor`)
* [x] Validate debugger - make sure that debugging .NET Core code which is hosted through the various new routes works as expected. Also needs to define expectations around these scenarios (Attach only, or works from launch, …)
* [x] Validate profiler - same as for the debugger but profiling scenarios this time
* [x] VS experience - specifically for the Windows only scenarios (COM, WinRT, IJW) validate the experience when creating and consuming these from VS
* [x] Validate generated `.runtimeconfig.json` for component projects (COM, WinRT, custom components)

**Comment by vitek-karas** [comment]
Command line parsing entry point added in #6548

**Comment by elinor-fung** [comment]
Single-file bundle behaviour matches the muxer - fails, error message is not the most helpful (fails to find hostpolicy)

**Comment by elinor-fung** [comment]
VS debugging experience (matches the existing experience for custom hosts):
- Attach Native and/or Managed (CoreCLR) works as expected
- Launching directly from the native project does not work with .NET Core debugging. Options:
  - Configure launch settings for a .NET Core project to launch the host (and enable mixed mode - `"nativeDebugging": true` - if desired).
  - Open the built custom host as an exe project and select Managed (CoreCLR) or Mixed (CoreCLR) as the debugger type
- Existing limitation with mixed mode where runtime needs to be loaded before native breakpoints are hit

**Comment by elinor-fung** [comment]
PR for SDK support: dotnet/sdk#3305

**Comment by vitek-karas** [comment]
I validated that for COM server and component projects get `.runtimeconfig.json` with the correct content by default.

**Comment by elinor-fung** [comment]
VS experience (VS 16.3 + .NET Core Preview 7) looks fine for COM scenarios. Project system support is not yet ready for IJW.

**Comment by vitek-karas** [comment]
I think this is done - we've validated most of the scenarios (IJW is the long pole, but it works from the host's point of view).
