### ISSUE TITLE
Flaky test: Running_AppHost_with_GUI_Reports_Errors_In_Window

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#6117]
https://dev.azure.com/dnceng/internal/_build/results?buildId=170609

```
  [xUnit.net 00:01:47.5846677]     Microsoft.DotNet.CoreSetup.Test.HostActivation.StandaloneAppActivation.Running_AppHost_with_GUI_Reports_Errors_In_Window [FAIL]
  Failed   Microsoft.DotNet.CoreSetup.Test.HostActivation.StandaloneAppActivation.Running_AppHost_with_GUI_Reports_Errors_In_Window
  Error Message:
   Assert.NotEqual() Failure
  Expected: Not 0
  Actual:   0
  Stack Trace:
     at Microsoft.DotNet.CoreSetup.Test.HostActivation.StandaloneAppActivation.Running_AppHost_with_GUI_Reports_Errors_In_Window() in F:\workspace\_work\1\s\src\test\HostActivationTests\StandaloneAppActivation.cs:line 263
```

This sometimes fails my PR validation too. I don't think it's flaky to the point of being critical (it's not too common, and hitting retry has always worked in my experience) but of course we don't want stuff like this to build up or delay release blockers.

Based on the name of the test alone (`Running_AppHost_with_GUI_Reports_Errors_In_Window`) I wouldn't doubt this being a machine issue, but I'm not familiar with what can go wrong with this kind of dialogue box test.

/cc @vitek-karas

**Comment by vitek-karas** [comment]
The test triggers an operation which should popup a dialog (and that is the feature being tested unfortunately). It then waits for the dialog window to appear. Currently the timeout is 5 seconds.

Maybe we should extend the timeout. The tested operation should be very fast... but who knows, maybe disk IO or antivirus make it really slow.

(This is the first time I see this fail... so I wasn't aware of it being an issue)

**Comment by dagood** [comment]
Extending the timeout sounds good to me. Who knows what goes on with these build machines. 😄

(Yeah... wish we had better tracking of these. All I know is I've had failures caused by it a handful of times in PRs and other builds I've followed.)

**Comment by vitek-karas** [comment]
@dagood Is there a way to get to the full test results? The .trx file would be really nice :-)

**Comment by dagood** [comment]
Not that I know of... might want to try using the official task, make it even show up in the tests tab: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml. Including those with build logs would be fine to me too though, I think.
