### ISSUE TITLE
Remove DependencyModel RuntimeLibrary hacks for xunit

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/core-setup#617]
https://github.com/dotnet/cli/pull/1932 will introduce some small hacks to DependencyModel in order to allow coreclr.xunit to run. Once that's in, fix xunit and remove the hacks

Moved from https://github.com/dotnet/cli/issues/1998 on behalf of @anurse.

**Comment by gkhanna79** [comment]
It is not clear what is this for. Can someone elaborate on it, who should it be assigned to and why it needs to be in Core-Setup?

CC @schellap

**Comment by anurse** [comment]
I don't think this is relevant after MSBuild conversion

**Comment by muratg** [comment]
Assigning to @gkhanna79 and @eerhardt based on our discussion last week.

@gkhanna79 Ideally the following two methods would be removed in 2.0.0:

https://github.com/dotnet/core-setup/blob/master/src/Microsoft.Extensions.DependencyModel/RuntimeLibrary.cs#L76-L77
