### ISSUE TITLE
packages-microsoft-prod.deb for Ubuntu 19.04 contains wrong component

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/core-setup#6175]
## Steps to reproduce

```bash
wget https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
```

## Expected  behavior

Line in `/etc/apt/sources.list.d/microsoft-prod.list` should read:

```text
deb [arch=amd64] https://packages.microsoft.com/ubuntu/19.04/prod disco main
```

## Actual behavior

Line in `/etc/apt/sources.list.d/microsoft-prod.list` is actually:

```text
deb [arch=amd64] https://packages.microsoft.com/ubuntu/19.04/prod xenial main
```

The distribution identifier ist wrong. It's `xenial` instead of `disco`.

## Environment data

Ubuntu 19.04

**Comment by dagood** [comment]
Issue moved to [dotnet/core #2657](https://github.com/dotnet/core/issues/2657) via [**ZenHub**](https://www.zenhub.com/)
