### ISSUE TITLE
Include crossgen in the shared framework.

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/core-setup#618]
Moving from https://github.com/dotnet/cli/issues/2013 on behalf of @ellismg and @brianrob 

-----

@brianrob Would like us to include crossgen as part of the shared framework so that during profiling it's possible to generate symbols for NGEN and R2R images, which requires the matching version of crossgen.

**Comment by gkhanna79** [comment]
@brianrob Is this scenario still applicable as there are no current plans to crossgen standalone apps?

**Comment by brianrob** [comment]
Yes, this is still applicable.

**Comment by gkhanna79** [comment]
@brianrob How are you enabling the profiling experience? I would expect that when you profile the app, you will need to determine the M.N.App the app targets, as opposed to what is present on the machine, to generate the PDBs. As a result, shouldn't the profiling infrastructure take care of pulling down the right CoreCLR nuget package and extracting crossgen from it?

**Comment by gkhanna79** [comment]
@brianrob any thoughts on this?

**Comment by ellismg** [comment]
Roslyn and CoreFX/CoreCLR and other repositories would actually use this if it was present to crossgen tools we restore as part of the build.  The current strategy is to manually restore a CoreCLR package, figure out how to find crossgen and then use it.  Having it in the shared framework would be a big win.

**Comment by brianrob** [comment]
@gkhanna79, having crossgen next to the coreclr in both the shared framework and in standalone apps would be useful for tracing.  The tracing infra is designed to not have a dependency on things like Nuget or other managed code so that it can function when the runtime is not working properly.

**Comment by gkhanna79** [comment]
@brianrob I can under crossgen be part of SharedFX installation but not in standalone apps where we are trying it to be as small as possible (and pay for play). Also, can you please help with my question above (https://github.com/dotnet/core-setup/issues/618#issuecomment-260392521)?

@ellismg Do you expect to find x86/x64 hosted cross targeting crossgen as well (e.g. for arm32 and arm64 scenarios)?

**Comment by brianrob** [comment]
@gkhanna79, the act of profiling is a machine-wide operation.  We have a script called perfcollect (http://aks.ms/perfcollect) that does much of the heavy lifting - similar to PerfView on Windows.  When it comes to generating symbols for NGEN or R2R images, we'll look at where the runtime was loaded from (this is in the trace), and use this to determine what tools (e.g. crossgen) to use.  This is why having crossgen next to libcoreclr.so is useful.

I see your point for standalone.  We'd likely need to come up with a way to get at crossgen that doesn't require a Nuget client.

**Comment by ellismg** [comment]
> Do you expect to find x86/x64 hosted cross targeting crossgen as well (e.g. for arm32 and arm64 scenarios)?

For CoreFX and Roslyn, no.  The use case is we restore a bunch of stuff that makes up a toolset we are going to build with and then we want to crossgen it.  In this case, we are doing the crossgen for the host architecture, even if we were cross compiling for some reason.

Core-Setup (and CLI) sort of want this (because they want to crossgen the shared framework for the target at build time) and usually in these cases we cross compile instead of building on the target.  In that case we would need a way to get at an x64 hosted crossgen that targets ARM32/ARM64 (we could continue the manual process we use today of restoring a runtime package and then groveling around in it.

**Comment by gkhanna79** [comment]
Fixed with https://github.com/dotnet/core-setup/pull/1425 from @ericstj

**Comment by ellismg** [comment]
From my reading, #1425 was about the fact that `crossgen` was not in the `tools` folder of `Microsoft.NETCore.App`.

The ask here is to ensure that `crossgen` is in the shared framework directory (i.e. included in the `shared/Microsoft.NETCore.App/2.0.0` folder) so folks don't need to restore and poke instead a nupkg to get the tool.

**Comment by ericstj** [comment]
If that's the case we need to decide if that happens in the Microsoft.NETCore.Runtime.CoreCLR package and just flows downstream or if we want to remap it to that folder during the build of Microsoft.NETCore.App.  @gkhanna79 I'd like your opinion on this.

**Comment by gkhanna79** [comment]
> The current strategy is to manually restore a CoreCLR package, figure out how to find crossgen and then use it. Having it in the shared framework would be a big win.

@ellismg even if crossgen is part of sharedFX, you would still need to do something like https://github.com/dotnet/core-setup/blob/e82cf3aef2537ba95aa5a0d258b1daf60d2a2dca/build_projects/shared-build-targets-utils/Utils/Crossgen.cs#L38 to pickup the appropriate crossgen. Doesn't this mean that the additional work being done is simply to restore the CoreCLR package?

> We'd likely need to come up with a way to get at crossgen that doesn't require a Nuget client.
This leads me to another question for @brianrob - Is this production time profiling and are you going to need to do it for standalone apps as well? I would assume the answer is yes and if so, given that we are striving hard to reduce on disk footprint for apps, would you still not have your script extract crossgen from CoreCLR package?

**Comment by ellismg** [comment]
> @ellismg even if crossgen is part of sharedFX, you would still need to do something like https://github.com/dotnet/core-setup/blob/e82cf3aef2537ba95aa5a0d258b1daf60d2a2dca/build_projects/shared-build-targets-utils/Utils/Crossgen.cs#L38 to pickup the appropriate crossgen. Doesn't this mean that the additional work being done is simply to restore the CoreCLR package?

I don't understand why that's the case.  If it is part of the shared framework, I know there's "crossgen" in `$DOTNET_ROOT/shared/<version>` and I can just invoke that.

Look at [crossgen.sh](https://github.com/dotnet/corefx/blob/master/Tools-Override/crossgen.sh) in CoreFX.   It does the restore dance and copy just to get stuff in the shared framework folder.  It has to do all this goofy fallback stuff (see around L75).  If it was just part of the shared framework, we wouldn't have to do anything.

**Comment by gkhanna79** [comment]
@ellismg For cross-targeted SharedFX (e.g. M.N.App for WinArm32), which crossgen should be in SharedFX - the one that runs natively on Arm32 (in which case you can only crossgen on Arm32 machine) or the one that is x86 hosted targeting Arm32 (in which case you can crossgen without Arm32 machine) or both?

What is your crossgen scenario?

**Comment by ellismg** [comment]
> which crossgen should be in SharedFX - the one that runs natively on Arm32 (in which case you can only crossgen on Arm32 machine) or the one that is x86 hosted targeting Arm32 (in which case you can crossgen without Arm32 machine) or both?

I would assume the one present would be the the Arm32 version, just like all the other native stuff in there.

> What is your crossgen scenario?

Basically what crossgen.sh is doing in CoreFX.  There we want to crossgen a bunch of IL images we restored and published from other packages to speed things up.  When @mellinoe added crossgen.sh we found it speed up the CoreFX build considerably.

**Comment by gkhanna79** [comment]
> I would assume the one present would be the the Arm32 version, just like all the other native stuff in there.

So, to confirm, you will run crossgen to generate R2R version of FX assemblies on an Arm32 machine - is that correct? Other native stuff being Arm32 does not matter until you decide to execute it.

**Comment by ellismg** [comment]
> So, to confirm, you will run crossgen to generate R2R version of FX assemblies on an Arm32 machine

Yes.

**Comment by gkhanna79** [comment]
Thanks @ellismg.

@brianrob Can you comment on the question above as well?

**Comment by gkhanna79** [comment]
> This leads me to another question for @brianrob - Is this production time profiling and are you going to need to do it for standalone apps as well? I would assume the answer is yes and if so, given that we are striving hard to reduce on disk footprint for apps, would you still not have your script extract crossgen from CoreCLR package?

@brianrob Can you please help with the above question?

**Comment by brianrob** [comment]
We'd use crossgen for profiling at all times, production included.  We will likely need to support standalone apps as well.  I think the key is that we don't want to have our tooling depend on the runtime or Nuget (which has a runtime dependency) to download crossgen.  If there was a nice way for us to get crossgen (perhaps via the symsrv protocol) then that would be fine as well.

**Comment by gkhanna79** [comment]
> (perhaps via the symsrv protocol)

I dont believe this would work for non-Windows scenarios. How does your script work today?

**Comment by brianrob** [comment]
Today, the script assumes that crossgen is present next to libcoreclr.so.  We've not implemented any automation around deploying crossgen.

With respect to symsrv - there is work being done at this time to support a cross-platform symbol story, which would allow us to pull symbol files, etc. in a manner similar to symsrv.

**Comment by gkhanna79** [comment]
Who is doing that work and what is its ETA? Will that work result in automatically indexing (or enabling capability) binaries we build as that should enable your script to pull down crossgen from this "symsrv" equivalent for both Shared and Standalone scenarios?

**Comment by brianrob** [comment]
@noahfalk and @markwilkie should be able to provide more details on the work and timeline.

Yes, this work would potentially allow us to index crossgen (and other binaries/symbols as required) to be downloaded by using a lookup key that can be derived from information on the box in both standalone and shared framework scenarios.

The bigger picture for this work is that if you have a crash dump or performance trace, you should be able to get binaries and symbols without having to be on the box where the data was collected and without having to figure out which nuget packages the binaries came from and then find the matching symbol packages.  The fact that we can index arbitrary files makes it such that we can index "supplemental" binaries like crossgen.

**Comment by gkhanna79** [comment]
In that case, @brianrob, I think your dependency should be on the work @noahfalk and @markwilkie are driving as that will also alleviate the need to have crossgen in standalone apps and make your scenario work in an independent manner.

**Comment by brianrob** [comment]
That seems reasonable to me.  This issue (or the CLI version of it) pre-dates the symbols work, so that was not an option at the time.

**Comment by gkhanna79** [comment]
@ellismg Did you get a chance to think more about this post our discussion few weeks ago?

**Comment by Petermarcu** [comment]
Id really like to push towards a world where components are crossgening themselves when they build and we don't have to include tools in the runtime. Seems fine to carry crossgeb with the toolset.

**Comment by ellismg** [comment]
Given that going forward we'll have small number of rid specific packages (e.g linux, osx, windows) and crossgen is now in Microsoft.NETCore.App in the tools folder, it will be easy enough for my scenarios to pull down the right cross-gen, so I'm happy to punt this.

Do you have a plan for how you would package cross-arch crossgen.  e.g. the crossgen that runs on x64 but targets arm64, how would be distribute that?

**Comment by gkhanna79** [comment]
> Do you have a plan for how you would package cross-arch crossgen

When we need to expose crossgen for any reason for public use, I expect that both (regular and cross-arch) crossgen implementations will be part of the toolset (or be pulled in by it).

**Comment by eerhardt** [comment]
There is a "Microsoft.NET.CrossGen.targets" that ships in the .NET Core SDK.  See https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.CrossGen.targets.

It would be great, IMO, if we could start using that more broadly.

**Comment by gkhanna79** [comment]
Closing this as there is no action required for now.
