### ISSUE TITLE
dotnet run passing ` --additionalprobingpath` to standalone app

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/core-setup#619]
Moving from https://github.com/dotnet/cli/issues/2127 on behalf of @pakrym 

----

## Steps to reproduce

dotnet run standalone app
## Expected  behavior

It get executed only with arguments passed to `dotnet run` command
## Actual behavior

`--additionalprobingpath` gets passed to standalone app

```
xiaota-mac:Microsoft.AspNetCore.Server.Kestrel.GeneratedCode asplab$ ~/.dotnet/dotnet -v run
Project Microsoft.AspNetCore.Server.Kestrel.GeneratedCode (.NETStandardApp,Version=v1.5) was previously compiled. Skipping compilation.
Running /Users/asplab/Documents/buildAgent/work/169923259d6dcfec/Universe/KestrelHttpServer/tools/Microsoft.AspNetCore.Server.Kestrel.GeneratedCode/bin/Debug/netstandardapp1.5/osx.10.10x64/Microsoft.AspNetCore.Server.Kestrel.GeneratedCode --additionalprobingpath /Users/asplab/.nuget/packages
Process ID: 82740
Could not resolve SDK directory from [/Users/asplab/Documents/buildAgent/work/169923259d6dcfec/Universe/KestrelHttpServer/tools/Microsoft.AspNetCore.Server.Kestrel.GeneratedCode/bin/Debg/netstandardapp1.5/osx.10.10-x64]
```
## Environment data

`dotnet --version` output:

```
~/.dotnet/dotnet --version
1.0.0-beta-002113
```

**Comment by gkhanna79** [comment]
@pakrym I installed CLI from yesterday and created a repro similar to what you have above and I am unable to repro the issue when passing `--additionalprobingpath` to an unpublished standalone app. Do you have a repro you can share?

However, when I do `dotnet run --verbose`, I see the following:

```
E:\Bugs\cs_619>dotnet run --verbose
Newtonsoft.Json.Linq.JObject
Hello World!
Arg: --verbose
```

@piotrpMSFT @livarcocc Shouldn't --verbose be stripped out before the application is executed? Also, unlike the output above that @pakrym shared, I don't see `--verbose` doing anything verbose. Is that expected?

**Comment by piotrpMSFT** [comment]
From `dotnet run --help`:

```
Options:
  -h|--help                   Show help information
  -c|--configuration          Configuration to use for building the project. Default for most projects is "Debug".
  -f|--framework <FRAMEWORK>  Build and run the app using the specified framework. The framework has to be specified in the project file.
  -p|--project                The path to the project file to run (defaults to the current directory if there is only one project).
```

--verbose is not a supported option for the run command.

**Comment by gkhanna79** [comment]
@piotrpMSFT If that is the case, then what is equivalent of `dotnet -v run` that @pakrym has in his output above?

**Comment by piotrpMSFT** [comment]
@gkhanna79 @pakrym is on `1.0.0-beta-002113` which is a VERY old build. I suspect the equivalent today will be `dotnet -d run`.

**Comment by gkhanna79** [comment]
Thanks @piotrpMSFT. @pakrym I am unable to repro this issue even with `-d`:
```

E:\Bugs\cs_619>dotnet -d run
Telemetry is: Enabled
Running E:\Bugs\cs_619\bin\Debug\netcoreapp1.0\cs_228.exe
Process ID: 14668
Hello World!
```

Please share a repro if you have one.

**Comment by pakrym** [comment]
I tries it too, this is fixed with a new sdk
