### ISSUE TITLE
Audit the list of Ubuntu runtime dependencies - currently 44

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/core-setup#620]
Moving from https://github.com/dotnet/cli/issues/2308 on behalf of @jeffschwMSFT. CLI's pre-req's all come from the shared framework.

----

We should audit the list of 44 libs required to run on Ubuntu with the goal of reducing the list to a more manageable set (eg. Windows has 1, Mac has 1, and Centos has 9).

Current list of dependencies for Ubuntu:
libc6
libedit2
libffi6
libgcc1
libicu52
liblldb-3.6
libllvm3.6
liblttng-ust0
liblzma5
libncurses5
libpython2.7
libstdc++6
libtinfo5
libunwind8
liburcu1
libuuid1
zlib1g
libasn1-8-heimdal
libcomerr2
libcurl3
libgcrypt11
libgnutls26
libgpg-error0
libgssapi3-heimdal
libgssapi-krb5-2
libhcrypto4-heimdal
libheimbase1-heimdal
libheimntlm0-heimdal
libhx509-5-heimdal
libidn11
libk5crypto3
libkeyutils1
libkrb5-26-heimdal
libkrb5-3
libkrb5support0
libldap-2.4-2
libp11-kit0
libroken18-heimdal
librtmp0
libsasl2-2
libsqlite3-0
libssl1.0.0
libtasn1-6
libwind0-heimdal

**Comment by mellinoe** [comment]
I don't think there's anything to do here, at least not anything that is specific to Ubuntu. All of our platforms have the same prerequisites, at a high level. The list here is just a raw list of all packages that are transitively linked to by corefx and coreclr, so it's not really very interesting.

**Comment by danmosemsft** [comment]
@mellinoe since you say nothing to do, we're closing this.
