### ISSUE TITLE
Add "Profile" classification to WindowsDesktop FrameworkList.xml

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#6210]
The files in WindowsDesktop are for WPF and WinForms (and integration), but at design time, seeing all of these in intellisense causes a poor experience. See https://github.com/dotnet/cli/issues/10536 for more details.

To help solve this, the WD targeting pack `FrameworkList.xml` should classify each DLL so they can be filtered. Add a `Profiles` attribute, see https://github.com/dotnet/cli/issues/10536#issuecomment-488871926 for values.

The list makes more sense to maintain in Core-Setup because it's where the packages are combined, rather than listing all the files somewhere deeper in the SDK.

@ericstj did a pass of manual classification and got these results:

WindowsDesktop File | Classification
-- | --
Accessibility.dll |  
DirectWriteForwarder.dll | WPF
Microsoft.Win32.Registry.dll |  
Microsoft.Win32.SystemEvents.dll |  
PenImc_cor3.dll | WPF
PresentationCore-CommonResources.dll | WPF
PresentationCore.dll | WPF
PresentationFramework-SystemCore.dll | WPF
PresentationFramework-SystemData.dll | WPF
PresentationFramework-SystemDrawing.dll | WPF
PresentationFramework-SystemXml.dll | WPF
PresentationFramework-SystemXmlLinq.dll | WPF
PresentationFramework.Aero.dll | WPF
PresentationFramework.Aero2.dll | WPF
PresentationFramework.AeroLite.dll | WPF
PresentationFramework.Classic.dll | WPF
PresentationFramework.dll | WPF
PresentationFramework.Luna.dll | WPF
PresentationFramework.Royale.dll | WPF
PresentationNative_cor3.dll | WPF
PresentationUI.dll | WPF
ReachFramework.dll | WPF
System.CodeDom.dll |  
System.Configuration.ConfigurationManager.dll |  
System.Design.dll | WindowsForms
System.Diagnostics.EventLog.dll |  
System.DirectoryServices.dll |  
System.Drawing.Common.dll | WindowsForms
System.Drawing.Design.dll | WindowsForms
System.Drawing.Design.Primitives.dll | WindowsForms
System.IO.FileSystem.AccessControl.dll |  
System.Media.SoundPlayer.dll |  
System.Printing.dll | WPF
System.Security.AccessControl.dll |  
System.Security.Cryptography.Cng.dll |  
System.Security.Cryptography.Pkcs.dll |  
System.Security.Cryptography.ProtectedData.dll |  
System.Security.Cryptography.Xml.dll |  
System.Security.Permissions.dll |  
System.Security.Principal.Windows.dll |  
System.Threading.AccessControl.dll |  
System.Windows.Controls.Ribbon.dll | WPF
System.Windows.Extensions.dll |  
System.Windows.Forms.Design.dll | WindowsForms
System.Windows.Forms.Design.Editors.dll | WindowsForms
System.Windows.Forms.dll | WindowsForms
System.Windows.Input.Manipulations.dll | WPF
System.Windows.Presentation.dll | WPF
System.Xaml.dll | WPF
UIAutomationClient.dll | WPF
UIAutomationClientSideProviders.dll | WPF
UIAutomationProvider.dll | WPF
UIAutomationTypes.dll | WPF
WindowsBase.dll | WPF
WindowsFormsIntegration.dll | Integration
WPFgfx_cor3.dll | WPF

**Comment by dsplaisted** [comment]
Nick and I discussed how the profiles would be represented in framework references, and ended up with a tweak to how the profiles are represented in the framework list.  Details are here: https://github.com/dotnet/cli/issues/10536#issuecomment-488871926

**Comment by dagood** [comment]
Implemented in https://github.com/dotnet/core-setup/pull/6573, which merged before preview 6 snap.
