### ISSUE TITLE
DependencyModel uses wrong package cache environment variable name

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/core-setup#622]
Moved from https://github.com/dotnet/cli/issues/3034 for @pakrym. 

I verified the issue still exists, though the code has moved:
https://github.com/dotnet/core-setup/blob/master/src/Microsoft.Extensions.DependencyModel/Resolution/PackageCacheCompilationAssemblyResolver.cs#L75

----

In PR https://github.com/dotnet/cli/pull/2156 `DOTNET_PACKAGES_CACHE` variable name was changes to `DOTNET_HOSTING_OPTIMIZATION_CACHE`
https://github.com/dotnet/cli/pull/2156/files#diff-76ff25fcb7bb5726c0738b88686cf16dR111

But DependencyModel usage (https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.Extensions.DependencyModel/Resolution/PackageCacheCompilationAssemblyResolver.cs#L71) was not updated, so MVC Razor compiler won't use package cache for view compilation when only `DOTNET_HOSTING_OPTIMIZATION_CACHE` is set.

@schellap @muratg

**Comment by gkhanna79** [comment]
@piotrpMSFT @muratg @pakrym Who owns DependencyModel that lives in Core-Setup so that this issue can be routed to them?

**Comment by muratg** [comment]
Assigning to @gkhanna79 and @eerhardt based on our discussion last week.

**Comment by eerhardt** [comment]
To follow up here, this environment variable completely went away in 2.0, thus the whole resolver is now deleted.

The new support for resolving assemblies from the `dotnet cache` locations will be completed by https://github.com/dotnet/core-setup/issues/624#issuecomment-288245699
