### ISSUE TITLE
Support nuget's "fallback package target" feature in DependencyContext

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/core-setup#624]
Moving from https://github.com/dotnet/cli/issues/3569 on behalf of @muratg.

NuGet now supports a secondary package target to improve `dotnet restore` performance. The idea is to populate the secondary folder for Azure Web Sites to improve kudu restore performance.

This WI is to complete the work and add the support for this secondary package folder in DependencyContext as well. This would fix the `dotnet run` scenario for MVC runtime view compilation as well as `dotnet test` scenarios. 

This can be done for CLI preview3. We have punted the work from CLI preview2 in the core war today.

cc @piotrpMSFT @Petermarcu  @Eilon @davidfowl

**Comment by gkhanna79** [comment]
Who is the owner for DependencyContext to whom this bug should be routed?

CC @schellap

**Comment by muratg** [comment]
@piotrpMSFT @Petermarcu  is there someone on your teams that can take this on? @pakrym can do a code review, but he'll be busy with ASP.NET tasks.

**Comment by gkhanna79** [comment]
@muratg Historically, @piotrpMSFT 's team and folks in ASP.NET have been involved in design and implementation of this component, IIRC. Will @pakrym not be able to bring this up for 1.2.0 Preview next year?

**Comment by muratg** [comment]
Assigning to @gkhanna79 and @eerhardt based on our discussion last week.

@gkhanna79 This is one of the bugs that we need in 2.0.0.

**Comment by eerhardt** [comment]
Assigning to @ramarag to fix along with https://github.com/dotnet/sdk/issues/1002, which is basically the same issue.

@ramarag - the high-level plan here is that if the native dotnet host knows how to load assemblies from a given place, then DependencyModel should be able to load assemblies from that place as well.  So in my mind, the work necessary is:

1. The dotnet host will pass all `additional-probing-paths` it knows about into managed code, probably through the `AppContext.GetData` API where it already passes information to managed code.
2. DependencyModel has the ability to look at these additional probing paths, and resolve compilation assemblies from them, just like it does for `NUGET_PACKAGES` and `%USERPROFILE%\.nuget\packages` today.
3. The locations of any `dotnet cache` locations should be passed to managed code as well, so DependencyModel can probe those locations.
4. (may be a separate issue should be logged for this one?) We should also be passing in any "light up" deps.json files to managed code as well, so DependencyModel and other managed components can get access to this information.  Maybe these could be added to the `AppContext.GetData("APP_CONTEXT_DEPS_FILES")` list?

Using the above information, DependencyModel will be able to resolve compilation assemblies from wherever the native host is able to load assemblies from.

Again, the high-level strategy here is: if the native dotnet host can resolve an assembly from a location, then managed code should be able to know about that location as well.

Reach out to me or @gkhanna79 if you have any questions.
