### ISSUE TITLE
Rename consolidated runtime-deps: remove RID

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#6269]
Right now, the runtime deps Deb is:

[`dotnet-runtime-deps-3.0.0-preview6-27703-05-ubuntu.14.04-x64.deb`](https://dotnetcli.blob.core.windows.net/dotnet/Runtime/3.0.0-preview6-27703-05/dotnet-runtime-deps-3.0.0-preview6-27703-05-ubuntu.14.04-x64.deb)

It should probably not have a specific RID to avoid confusion:

`dotnet-runtime-deps-3.0.0-preview6-27703-05-x64.deb`

This doesn't matter once it's in a package repository, but Core-SDK downloads it, and individual devs/customers might be trying to use it directly.

The readme should also be updated.

/cc @dleeapho @leecow

**Comment by leecow** [comment]
Customers shouldn't be using the deps package directly so not worried about that and the only installer which should depend on this is the Host.

**Comment by dagood** [comment]
One Deb, but still many RPMs.

"Or" dependencies are *possible* for both. For RPM, though, they're a recent addition, so it isn't practical to use there. More info at https://github.com/dotnet/core-setup/issues/5812#issuecomment-485992929.

I believe Core-SDK downloads the Deb package for testing. If we don't remove the RID (which I agree seems fine from an end-product perspective), I think Core-SDK will need a hard-coded reference to `ubuntu.14.04` to find the Deb. In Core-Setup, we'd have to artificially pin the output to `ubuntu.14.04` or Core-SDK suffers maintenance cost.  /cc @johnbeisner

**Comment by dagood** [comment]
I think we should do it so we can fix Core-SDK uptake in the best way. It's a simple change I submitted https://github.com/dotnet/core-setup/pull/6276 for.

**Comment by dleeapho** [comment]
+1 We should do it for the sake of core-sdk uptake.

**Comment by mohag** [comment]
The links in here: https://github.com/dotnet/core-setup/blob/master/README.md still need updating... (Using the runtime-deps linked for there results in an old version, which fails the dependency checks, likely as a result of this change)

**Comment by dagood** [comment]
@mohag thanks, filed https://github.com/dotnet/core-setup/issues/6865 to update the 3.0 column.
