### ISSUE TITLE
ComRegisterFunctionAttribute doesn't work with regsvr32

### ISSUE THREAD

**Issue by saschanaz** [dotnet/core-setup#6286]
## Steps to reproduce

(From https://stackoverflow.com/questions/55980553/is-it-possible-to-execute-arbitrary-c-sharp-code-when-registering-com-dll)

```cs
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace MyNamespace
{
    [ComVisible(true)]
    [Guid("c60bcc75-8876-4e31-9e4c-a8e82712d8ca")]
    public class Code
    {
        [ComRegisterFunction]
        static void Temp()
        {
            Debug.Assert(false);
        }
    }
}
```

1. Build the above in debug mode with `<TargetFramework>netcoreapp3.0</TargetFramework>` and `<UseComHost>true</UseComHost>`. (.NET Core 3.0 Preview 4)
2. Register the resulting `*.comhost.dll` through `regsvr32`.

## Expected  behavior

Debug message box should appear

## Actual behavior

Nothing happens

## Environment data

Using VS2019 stable version. Would installing preview one help?

**Comment by jeffschwMSFT** [comment]
Moved to https://github.com/dotnet/coreclr/issues/24394
