### ISSUE TITLE
Failed to resolve library symbol hostfxr_main, error: dotnet: undefined symbol: hostfxr_main using 1.0.0-preview2-003121 on Fedora 23

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/core-setup#634]
Moved from https://github.com/dotnet/cli/issues/4010 on behalf of @dcorns.

----

## Steps to reproduce

run dotnet with any option on Fedora 23 64x and the error above will be displayed
## Expected  behavior

dotnet commands should work
## Actual behavior

Failed to resolve library symbol hostfxr_main, error: dotnet: undefined symbol: hostfxr_main is returned to the console
## Environment data

`dotnet --info` output: this command also returns the same error

**Comment by gkhanna79** [comment]
@dcorns Can you confirm if you can repro this issue using https://go.microsoft.com/fwlink/?LinkID=836297, which is the latest CLI we have corresponding to preview build you mentioned above?

**Comment by dcorns** [comment]
Unable to comply. I am now operating on fedora 25. fyi: this build does not work on fedora 25. Get Failed to initialize CoreCLR, HRESULT: 0x80131500. (Both libunwind and libicu installed.)

**Comment by gkhanna79** [comment]
@dcorns Can you repro the issue (of CoreCLR initialization) using Fedora 24 version of .NET Core (which you can download from https://dotnetcli.blob.core.windows.net/dotnet/master/Binaries/Latest/dotnet-fedora.24-x64.latest.tar.gz) on Fedora 25?

**Comment by gkhanna79** [comment]
@dcorns Please feel free to reopen the issue if you are able to repro the problem per https://github.com/dotnet/core-setup/issues/634#issuecomment-280980697 above.
