### ISSUE TITLE
realpath errors when installing from Snap

### ISSUE THREAD

**Issue by leecow** [dotnet/core-setup#6341]
This is a regression from 2.x and Preview 4.

Install Preview 5 using the snap installer on Fedora (I used 28)
```
sudo dnf install snapd
sudo snap install dotnet-sdk --channel=beta --classic
export SSL_CERT_FILE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
export SSL_CERT_DIR=/dev/null
```

New console app and run
```
dotnet-sdk.dotnet new console -o test
cd test
dotnet-sdk.dotnet run
```

Resulting error: `realpath: /snap/dotnet-sdk/37/../..//current/shared/Microsoft.NETCore.App: No such file or directory
/home/leecow/test/bin/Debug/netcoreapp3.0/test: relocation error: /lib64/libc.so.6: symbol _dl_starting_up version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference`

**Comment by jeffschwMSFT** [comment]
cc @vitek-karas @sdmaclea @elinor-fung

**Comment by dagood** [comment]
The `..` and `//` in the path strikes me as interesting, given what this script is doing:

https://github.com/dotnet/core-setup/blob/d1127c8c0ef5acca3eb9aa83f60fe1fe8e5f197a/src/pkg/packaging/snaps/dotnet-sdk/dotnet-runtime#L3-L7

I'd expect some `$snap` value between `//` in `/snap/dotnet-sdk/37/../..//current/shared/...`. I don't know how this all works, just an observation--maybe this is actually completely normal.

**Comment by leecow** [comment]
Ah, that looks interesting Davis. Will have a look.

**Comment by leecow** [comment]
Removed the runtime wrapper for now. Will revisit if it's determined the original scenario (multiple runtimes installed via snap) is needed.
