### ISSUE TITLE
WindowDesktop Runtime archives [zips] are not rooted @ 'shared'

### ISSUE THREAD

**Issue by johnbeisner** [dotnet/core-setup#6370]
windowsdesktop-runtime-[version]-win-x86.zip
windowsdesktop-runtime-[version]-win-x64.zip
windowsdesktop-runtime-[version]-win-arm.zip
windowsdesktop-runtime-[version]-win-arm64.zip

When unzipping a WindowDesktop Runtime archive, it unzips to a "Microsoft.WidowsDesktop.App" folder instead of the expected "shared\Microsoft.WidowsDesktop.App" folder as do the SDK, Runtime, Asp.Net Runtime archives.

This should be standardized before the install scripts [install-dotnet.ps1] introduce support for installations of the WindowDesktop Runtime: https://github.com/dotnet/cli/issues/11115

Related: https://github.com/dotnet/cli/pull/11298

**Comment by johnbeisner** [comment]
@dagood what is the status of this work - we have a dependent issue.

**Comment by dagood** [comment]
It's in the backlog. Should be an easy change, but since Core-SDK isn't taking 5.0 and Core repos don't branch for previews, it will take a while for it to be able to flow.

**Comment by dagood** [comment]
Actually, with https://github.com/dotnet/core-sdk/pull/3741 coming in soon, 5.0 will be flowing to the SDK shortly. I went ahead and submitted https://github.com/dotnet/core-setup/pull/7581 to make this change.

**Comment by dagood** [comment]
Done with https://github.com/dotnet/core-setup/pull/7581 and ported to 3.0 with https://github.com/dotnet/core-setup/pull/7584.
