### ISSUE TITLE
Add file manifest to runtime packs

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/core-setup#6409]
Similar to #5074, the runtime packs should have a manifest listing the assets, what type the assets are (managed or native), and the file and assembly versions.

Suggestions for the format:

Package name: `<SharedFrameworkName>.Runtime.<RID>`, e.g. `Microsoft.NETCore.App.Runtime.win-x64`

Manifest path: `data/RuntimeList.xml`

Manifest format:

```xml
<FileList Name=".NET Core 3.0" TargetFrameworkIdentifier=".NETCore" TargetFrameworkVersion="3.0" FrameworkName="Microsoft.NETCore.App" RuntimeIdentifier="...">
  <File Type="Managed" Path="runtimes/win-x64/lib/netcoreapp3.0/Microsoft.CSharp.dll" AssemblyVersion="..." FileVersion="..." />
  <File Type="Native" Path="runtimes/win-x64/native/clrjit.dll" FileVersion="..." />
  <!-- etc. -->
</FileList>
```

Notes:

- Each file would have a `Type` attribute specifying whether it is managed or native.
- Managed files should have attributes for the assembly and file versions, native assets should only have a file version attribute.
- The folders the assets go into would follow the existing NuGet conventions.  However, the code that reads the file list would not rely on that convention.  Rather, it would simply use the `Path` attribute on each `File` element.

**Comment by natemcmaster** [comment]
Is this file required _in addition to_, or _as a replacement for_ the data/PlatformManifest.txt file?

**Comment by nguerrera** [comment]
``` diff
-TargetFrameworkIdentifier=".NETCore" 
+TargetFrameworkIdentifier=".NETCoreApp" 
```

**Comment by nguerrera** [comment]
> Is this file required in addition to, or as a replacement for the data/PlatformManifest.txt file?

I would say in addition to, at least at this time. We read platform manifest form targeting pack, and this describes runtime pack. The framework list in the targeting pack is also not a suitable replacement.

**Comment by livarcocc** [comment]
hey @dagood do you have an idea of when this would be available?

**Comment by dagood** [comment]
It'll be efficient for me to do this at the same time as https://github.com/dotnet/core-setup/issues/6210, which I plan to have for Preview 6. If nothing goes wrong (and this is pretty straightforward), I'd say mid next week.

**Comment by dagood** [comment]
Implemented in https://github.com/dotnet/core-setup/pull/6573, which merged before preview 6 snap.
