### ISSUE TITLE
Add platform manifest to runtime pack

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/core-setup#6509]
We should add the same platform manifest (`data/PlatformManifest.txt`) that is in the targeting pack to the runtime packs.

This will help optimize conflict resolution for self-contained apps.

@dagood

**Comment by dsplaisted** [comment]
Hold off on this one for now

**Comment by dagood** [comment]
You mentioned in a more recent email we probably want this, is that right? (After the Arcade SDK migration the infra difficulties I was having with this should be gone.)

**Comment by dagood** [comment]
This has been done in `master`, planning to port to `release/3.0` as well.
