### ISSUE TITLE
Microsoft.WindowsDesktop.App framework should specify rollForward=LatestPatch

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/core-setup#6552]
The `Microsoft.WindowsDesktop.App` framework should correctly specify the compatibility version range for its dependency on `Microsoft.NETCore.App` framework. The expectation is that the same `major.minor` version will be used (with roll forward to latest patch applied). Currently the framework doesn't specify anything other than the minimum version. That means the defaults are used which are that any version with the same `major` is compatible. So for example 3.0.0 WindowsDesktop currently declares it's compatible with 3.1.0 NETCore.App.

As discussed offline that is not the intent. The framework should be changed to specify that it expects the same `major.minor`. To do that the `.runtimeconfig.json` of the framework should specify `rollForward: "LatestPatch"` - which means only the same `major.minor` version is compatible.

See dotnet/core-setup#5870 (comment) for discussion of potential impact and what are the scenarios (component hosting being the major one).

**Comment by vitek-karas** [comment]
@dagood

**Comment by dagood** [comment]
To be concrete, with a current runtimeconfig like this:

```json
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.0.0-preview6-27710-01"
    }
  }
}
```

the expected change is this?

```json
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.0.0-preview6-27710-01",
      "rollForward": "LatestPatch"
    }
  }
}
```

Should be a one-line change here:

https://github.com/dotnet/core-setup/blob/1ac29fa4fed3f5658864593e9b649238f52f3748/src/pkg/packaging-tools/sharedFramework/sharedFramework.csproj#L94-L97
