### ISSUE TITLE
Long test asset file path breaks Windows clones under longer than usual base paths

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#6610]
This file is intentionally super long for testing:

https://github.com/dotnet/core-setup/blob/master/src/test/Assets/TestProjects/AppWithSubDirs/Sentence/This%20is%20a%20really%2C%20really%2C%20really%2C%20really%2C%20really%2C%20really%2C%20really%2C%20really%2C%20really%2C%20really%2C%20really%2C%20really%2C%20really%2C%20really%20long%20file%20name%20for%20punctuation/word

But infra is pretty fragile when MAX_PATH is exceeded... most recently https://github.com/dotnet/core-setup/pull/6609, earlier source-build. 

@vitek-karas, @swaroop-sridhar, is it possible to generate this file while testing?
I believe that would significantly reduce the impact, because I'm pretty sure all the Windows infra that's having issues doesn't run tests.

/cc @wtgodbe @crummel

**Comment by swaroop-sridhar** [comment]
We can generate the test file during the test, but it is not typical for the host tests.  The test assets are currently self-sufficient and can be built/run separate from the actual tests if necessary -- which will not be true if we generate part of the input at run-time.

Why is this a problem on only some machines? The machines tests are running in the lab regularly. 
The file path is about 150 chars, well below the MAX_PATH limit.  What is the base-path where core-setup repo exists on the failing machine? We typically try to keep the paths short. 

Thanks.

**Comment by dagood** [comment]
@wtgodbe can you give some info about the branch merge infra's setup?

Source-build is a bit unique because it has to clone many repos, so the structure is more nested than usual. @crummel can you give an example?

My count is the path is 209 chars long, rather than ~150:
`src\test\Assets\TestProjects\AppWithSubDirs\Sentence\This is a really, really, really, really, really, really, really, really, really, really, really, really, really, really long file name for punctuation\word`

The Core-Setup official build clones to a fairly shallow location, something like `F:\workspace\_work\1\s`.

The VS default clone location goes up to 249 (with my relatively short username):
`C:\Users\dagood\Source\Repos\core-setup\src\test\Assets\TestProjects\AppWithSubDirs\Sentence\This is a really, really, really, really, really, really, really, really, really, really, really, really, really, really long file name for punctuation\word`

---

Interesting point about the assets being self-sufficient. Would it make sense to add an MSBuild target to the app's csproj to generate and use the long files to stay buildable without running tests?

**Comment by wtgodbe** [comment]
The code merge is done with this powershell script: https://github.com/dotnet/arcade/blob/master/scripts/GitHubMergeBranches.ps1

The failure is here: https://dnceng.visualstudio.com/internal/_build/results?buildId=207447

> fatal: cannot create directory at 'src/test/Assets/TestProjects/StandaloneAppWithSubDirs/Sentence/This is a really, really, really, really, really, really, really, really, really, really, really, really, really, really long file name for punctuation': Filename too long

I believe this is due to the default git settings in powershell. We should be able to workaround it with `git config --system core.longpaths true` - I just didn't get around to doing that before preview6.

**Comment by swaroop-sridhar** [comment]
Thanks @wtgodbe. Given the explanation, I've assigned the issue to you.

**Comment by wtgodbe** [comment]
Should be resolved by https://github.com/dotnet/arcade/pull/3083

**Comment by dagood** [comment]
@crummel, let us know if it would be useful to have a core-setup change to help with the source-build issue, otherwise this will be closed with @wtgodbe's arcade-script-side fix.

**Comment by crummel** [comment]
I've fixed this in the uberclone, so we don't need a core-setup change.  Thanks!
