### ISSUE TITLE
Windows builds sometimes fail with "light.exe : error LGHT0001: The process cannot access the file because it is being used by another process."

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#6651]
Sometimes, building on Windows fails because `light` is unable to move a file locked by antivirus. With light's verbose mode on, it shows like this:

```
Moving file 'C:\git\core-setup\bin\obj\win-x64.Release\WixTools.3.10.4\wix_temp\0u4m2y3a\dotnet-runtime-3.0.0-preview7-27803-0-win-x64.exe' to 'C:\git\core-setup\bin\win-x64.Release\packages\dotnet-runtime-3.0.0-preview7-27803-0-win-x64.exe'.
light.exe : error LGHT0001: The process cannot access the file because it is being used by another process. [C:\git\core-setup\src\pkg\packaging\dir.proj]

  Exception Type: System.IO.IOException

  Stack Trace:
     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
     at System.IO.__Error.WinIOError()
     at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
     at Microsoft.Tools.WindowsInstallerXml.BinderFileManager.MoveFile(String source, String destination)
     at Microsoft.Tools.WindowsInstallerXml.WixBinder.LayoutMedia(ArrayList fileTransfers, Boolean suppressAclReset)
     at Microsoft.Tools.WindowsInstallerXml.Binder.BindBundle(Output bundle, String bundleFile)
     at Microsoft.Tools.WindowsInstallerXml.Binder.Bind(Output output, String file)
     at Microsoft.Tools.WindowsInstallerXml.Tools.Light.Run(String[] args)
  Binder temporary directory located at 'C:\git\core-setup\bin\obj\win-x64.Release\WixTools.3.10.4\wix_temp\0u4m2y3a'.
  Light failed with exit code 1.
```

I confirmed with procmon this is MsSense.exe (Windows Defender threat detection) locking the file (despite setting an exclusion 🙄).

This file is written by light in the temp location, then moved by light to the final location, so there's nothing we can do from the outside to add retries or wait until the file's open.

https://github.com/dotnet/core-setup/pull/6562 added a one-second sleep before running light, and I believe the reason that helped is it lets the antivirus "catch up" to what's going on and process the file quickly enough to avoid the conflict.

I looked at the WiX code in the callstack, and it doesn't look very robust. It doesn't appear to retry at all in this case:
https://github.com/wixtoolset/wix3/blob/e4d1aab946a1df20f01cbc1c40bee68ffe93e8bf/src/tools/wix/WixBinder.cs#L351-L380. There doesn't seem to be any interest in changing this, based on https://github.com/wixtoolset/issues/issues/5942, instead the recommendation is to fix the build machine.

---

@joeloff, do you happen to know any ways around this?

**Comment by joeloff** [comment]
only way I can think of retrying it to manually call light from a custom target and then retry based on the exit code. You can capture that if you invoke light directly using <Exec Command> but that seems like overkill, unless this is happening regularly

**Comment by vitek-karas** [comment]
#6562 also sets `WIX_TEMP` to make it use location in the binaries folder. The assumption is that dev/build machines have antivirus disabled for binaries folders (but not for general temp). Doing that helped a little bit. It's possible that `light.exe` writes more than one file and the env. variable only affects some of the files. I looked through WIX code and the way it figures out temp folder location is rather complicated and not always customizable.

We might try to fix this by changing the `TMP` env. variable before running `light` as that should "fix" more locations in the code.

**Comment by dagood** [comment]
Heh, didn't consider retrying light as a whole... the code's in a powershell file at the moment, would be easy to add that logic. I like that: it wouldn't slow down official builds or anywhere else firewall exclusions are working, and dev builds where exclusions don't seem to work could succeed without manual retries.

@vitek-karas When I was checking on this with procmon, there are definitely still tons of things light does in `%temp%`, but I only ever hit file locks for this specific exe file in the custom `wix_temp` dir. Since an antivirus exclusion didn't do anything in my case to help with the exe, I'm skeptical moving other temp files that I haven't seen causing problems will help. (Maybe the code handles *those* temp files more robustly than the `wix_temp` files?) No objection to it as a matter of cleanliness, though, for anyone whose exclusions do work!

Soon I'm going to have to add more bundles/exes, so I'm expecting this to show up even more... I'll make sure we retry light.

**Comment by dagood** [comment]
Ah. I'm apparently using Windows Defender ATP, which [doesn't use Windows Defender exclusion rules](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-extension-file-exclusions-windows-defender-antivirus).
