### ISSUE TITLE
File path is not localized on runtime installation wizard with Japanese language

### ISSUE THREAD

**Issue by AriNuer** [dotnet/core-setup#6678]
## Steps to reproduce

1. Open the runtime installation (.NET core runtime-3.0.0-preview6-27804-01) in Japanese OS.
2. Observe the UI after the installation is complete.

## Expected  behavior
File path "C:\Program Files\dotnet" should be localized.

## Actual behavior
File path "C:\Program Files\dotnet" is not localized.

![222](https://user-images.githubusercontent.com/42136111/58933800-011eff00-879b-11e9-9523-aab1a183d7b0.png)

## Environment data
win10-x64 with Japanese

**Comment by dagood** [comment]
I don't know how to fix this. This string is defined here, which simply uses the value of `DOTNETHOME`:

https://github.com/dotnet/core-setup/blob/d1bbd70e6f50ba0759fa84d616ab9b46f1e1edf8/src/pkg/projects/netcoreapp/sfx/theme/1041/bundle.wxl#L65

According to https://stackoverflow.com/a/7314690, this is a difference in how the separator is displayed, not what it actually is. So it would seem that for some reason the burn bundle is displaying it differently from Windows Explorer.

@joeloff, is this something you're aware of?

(It looks like this is the case for the SDK bundle as well.)

/cc @dleeapho @johnbeisner

**Comment by joeloff** [comment]
yeah, I think the bundle will just map it back to the neutral locale. The strings are passed through the Engine's formatter to resolve variable references. I can dig a bit more, but I suspect you can't fix this. It's just how the text is displayed, I don't think anything should be broken

**Comment by dagood** [comment]
> It's just how the text is displayed, I don't think anything should be broken

Well, this is a loc issue about the text being displayed in a broken way. 😄 It is good that the files are still expected to end up in the right place, though. (And we do see in the screenshot that they indeed end up in the right place.)

Moving out of 3.0: with this probably having to do with the burn bundle internals (something about which codepoint it uses to display?), this is in a different league than the simple loc issues that we are fixing for 3.0.

**Comment by dagood** [comment]
Closing: obviated by the 3.1 installer plans. We don't think we can fix it for 3.0.
