### ISSUE TITLE
Hotkey conflict on the runtime installation wizard with Turkish 

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/core-setup#6687]
## Steps to reproduce
1.Open the runtime installation (.NET core runtime-[3.0.0-preview6-27804-01](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdotnetcli.blob.core.windows.net%2Fdotnet%2FRuntime%2Frelease%2F3.0%2Fdotnet-runtime-latest-win-x64.exe&data=02%7C01%7Cv-yunwei%40microsoft.com%7C2074437f22144735d02208d6e9392843%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636952829055574888&sdata=4pd3nSCUhKBt4zhAHtDIiVtgIMgKVJxUoZ9dHyjheGE%3D&reserved=0))
2.Tap "Alt" key to observe the hotkey on installation wizard

## Expected  behavior
Hotkeys work fine on the installation wizard

## Actual behavior
Hotkey "k" is conflicted on the installation wizard
![image](https://user-images.githubusercontent.com/33921754/58927697-34a15f80-8782-11e9-9540-09eacd1f3f6a.png)

## Environment data
win10-x64 with Turkish

**Comment by dleeapho** [comment]
Might have been fixed in master with the latest loc updates. Please verify.

**Comment by YunWeiaa** [comment]
Yes, no repro in master with the latest loc updates.
![image](https://user-images.githubusercontent.com/33921754/59016273-7827c680-8873-11e9-81c7-04b96533b06b.png).
One more thing, this issue wouldn’t be fixed in Release/3.0.1XX(3.0.100-preview6-xxxxx), only fixed in master(3.0.100-preview7-xxxxx or higher version), right?

**Comment by dagood** [comment]
In Core-Setup it's just `release/3.0` (`3.0.0-preview6-...`), but yes, it's been merged into `master` but not `release/3.0`. Thanks for taking a look!
