### ISSUE TITLE
WPF has removed PresentationCore-CommonResources from the product

### ISSUE THREAD

**Issue by rladuca** [dotnet/core-setup#6694]
Related to #6210 , we need updates to remove PresentationCore-CommonResources from the WindowsDesktop framework list (and any other associated files).

This binary was removed in https://github.com/dotnet/wpf/pull/794 and will be flowing up.

**Comment by rladuca** [comment]
@dagood I can't apply any labels here, if you could tag this with your upstream tag, that would be good : - )

**Comment by dagood** [comment]
Didn't cause a break because https://github.com/dotnet/core-setup/pull/6698 wasn't merged yet--I've incorporated the change in that PR.
