### ISSUE TITLE
Expose an API in the host that returns all the shared frameworks available next to it

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#675]
We could use that with tools, for instance.

@schellap @piotrpMSFT

**Comment by steveharter** [comment]
@livarcocc would an option to include stores also be useful (in addition to shared)?

Also by API, do you mean a dotnet.exe command line option, or something lower level?

**Comment by Petermarcu** [comment]
I'd leave stores as a separate thing for now. @livarcocc in essence, would this be a `dotnet --list-runtimes` switch on the host?

**Comment by livarcocc** [comment]
In all honesty, I don't remember exactly what the context for this was, but I imagine the command switch, as suggested above would make sense here. Also, should we consider a similar one for SDKs?

**Comment by Petermarcu** [comment]
Probably should have an SDK's list as well so people know what to put in the global.json when they go that route.

**Comment by omajid** [comment]
Some context to the request for available shared farmework versions is here: https://github.com/dotnet/cli/issues/3773#issuecomment-263732705

**Comment by steveharter** [comment]
Options
1) Extend --info. It would list shared frameworks, and then SDKs.
2) Add --list-runtimes and --list-sdks
3) Add --list-versions (for both)

I think option 1 is straightforward and prevents another one or two new commands. However, for options 1 and 3, any tooling that would want this information would have to parse the output to get the appropriate information.

Also linking this related issue https://github.com/dotnet/core-setup/issues/2845

**Comment by Petermarcu** [comment]
Take a look here: https://github.com/faniereynders/dotnet-sdk-helpers . Seems like a good user experience.

The host should have an API for returning the list of SDK's and runtimes. The SDK should then have the command in it to set and manage active SDK's.

The runtime should have a `--runtimes` verb that will list the available runtimes that could be passed to `--fx-version`. The --list-sdk's command should be left to the SDK to implement on top based on the host API's.

**Comment by steveharter** [comment]
Proposal for dotnet.exe host additions:
```
--runtimes      (list all runtime versions)
--versions      (list all SDK versions; --version is already there for current version)
```

Optional addition (not required, but may be useful):
```
--runtime-version  (same as `dotnet --info` shows under "Microsoft .NET Core Shared Framework Host")
``` 

These are just the host additions; the SDK can then later be extended to add first-class support such as `sdk <new version>`

**Comment by eerhardt** [comment]
I'm not sure the naming `--runtimes` and `--versions` makes complete sense to me.  Specifically I think `--versions` meaning the 'sdk versions' is confusing.  I know it aligns with the existing `--version` option, which is the SDK version, but I still find it confusing.

How about:

```
--runtime-versions      (list all runtime versions)
--sdk-versions      (list all SDK versions; --version is already there for current version)
```

or possibly inserting `list` into the option name:

```
--list-runtime-versions      (list all runtime versions)
--list-sdk-versions      (list all SDK versions; --version is already there for current version)
```

As the name would align with the `dotnet list` command in the CLI.

another option:

```
--list-runtimes (list all runtime versions)
--list-sdks      (list all SDK versions; --version is already there for current version)
```

/cc @kathleendollard

**Comment by steveharter** [comment]
There are tradeoffs for terseness vs understandability, and also consistency with the existing `--version`...

I think this is a good compromise:
```
--list-runtimes
--list-sdks
```

This is terse enough and also extensible to provide other information than just the version, such as the directory name, if we choose to in the future.

I do agree that the original `--version` is too ambiguous as to whether it is the runtime or SDK. so I think we should consider changing it to `--current-sdk` but still keep `--version` around for backwards compat. The help would not show `--version`; it would only show `--current-sdk`. In addition, ``--current-sdk` could be modified in the future to accept a parameter to change it as well.

**Comment by steveharter** [comment]
The current PR has `--list-runtimes` and `--list-sdks` naming so please send any feedback asap.

Sample output for  --list-sdks :
```
C:\git\repros\dotnet>dotnet --list-sdks
2.0.0 [C:\git\repros\dotnet\sdk]
2.0.0 [C:\Program Files\dotnet\sdk]
2.1.13 [C:\Program Files\dotnet\sdk]
```


Sample output for  --list-runtimes :
```
C:\git\repros\Standalone\bin\Debug\netcoreapp2.0\win10-x64\publish>dotnet --list-runtimes
Extension.Example 1.2.3 [C:\git\repros\Standalone\bin\Debug\netcoreapp2.0\win10-x64\publish\shared]
Microsoft.NETCore.App 2.0.0 [C:\git\repros\Standalone\bin\Debug\netcoreapp2.0\win10-x64\publish\shared]
Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared]
```
