### ISSUE TITLE
Proprietary license

### ISSUE THREAD

**Issue by omajid** [dotnet/core-setup#676]
The main repository contains the MIT license in the https://github.com/dotnet/core-setup/blob/master/LICENSE file. But the packaging dir contains a proprietary license file: https://github.com/dotnet/core-setup/blob/master/packaging/LICENSE.txt.

Specifically, this other license file says:

> You may not
>  * work around any technical limitations in the software;
>  * reverse engineer, decompile or disassemble the software, except and only to the extent that applicable law expressly permits, despite this limitation;
>  * publish the software for others to copy;

There are other copies of this license too:
- https://github.com/dotnet/core-setup/blob/master/resources/LICENSE.txt
- https://github.com/dotnet/core-setup/blob/master/packaging/osx/sharedframework/resources/zh-hans.lproj/eula.rtf (and various variants)

I believe this license file ends up in dotnet.tar.gz that's availalbe from: https://www.microsoft.com/net/core

Could you please replace this with the LICENSE file in the main dir?

**Comment by ellismg** [comment]
/cc @richlander.

Rich, what's the strategy here?  I know other MSFT open source products have MIT licenses, but we license the specific build that MSFT does differently.  What's the plan here for third parties that want to build .NET?

**Comment by richlander** [comment]
This is what should happen:

- Arbitrary person clones and builds the product in the comfort of their own home or business. They should end up with the MIT license in their built assets by default.
- A person or business with specific goals (Microsoft comes to mind) around .NET Core can optionally put their own license in the package. They should include a 3rd party notice in their distribution to clarify the heritage/pedigree of the .NET Core source code. This is common practice, although consulting a legal professional (I am not that person) is still a good idea to make sure you are doing it right.

Does that satisfy the need?

**Comment by omajid** [comment]
Yes, I think a solution where a license is used by default but there's a way to add a different license, satisfies everyone's need. I am mostly concerned with the open source aspect of .NET Core, so MIT by default would be fantastic. It would address any confusion from anyone who might build .NET Coreand be surprised by the unexpected license of the built product.

IANAL, and this is mostly for my own curiosity, but wouldn't the second option - apply a different license to a piece of code - only apply to someone who owns the copyright on the code? That would be the .NET Foundation, right?

**Comment by richlander** [comment]
IANAL either. Three points:

- The MIT license basically says "do whatever you want" including sublicense. It is GPL that is prescriptive on outgoing licenses, not MIT.
- We include 3rd party notice files in distributions to account for dependencies. The new experience we are discussing needs to include a 3rd party notice for the .NET Core repos with the copyright holder being .NET Foundation, if it doesn't already. This is what accounts for the copyright holder, as you suggest.
- The MSFT license include text like you cannot use the Microsoft tradework. That's orthogonal to open source and about the particular distribution and its packaging.

**Comment by omajid** [comment]
Thanks for the clarifications!

**Comment by richlander** [comment]
Linking to the PR: https://github.com/dotnet/core-setup/pull/855

**Comment by danmosemsft** [comment]
@richlander @ellismg where are we at with this one? going through all the core-setup issues with @gkhanna79 for ZBB...

**Comment by gkhanna79** [comment]
@richlander @ellismg What are the next steps for this?

**Comment by gkhanna79** [comment]
CC @leecow who will chat with @richlander about this.

**Comment by gkhanna79** [comment]
@leecow @richlander Can you please do the needful for this by EOW?

**Comment by Petermarcu** [comment]
Is this addressed now or is there more to do?

**Comment by ellismg** [comment]
We need to port a change from CLI master into release/2.0.0.  I will do this tomorrow.

**Comment by Petermarcu** [comment]
@ellismg , is this done?

**Comment by ellismg** [comment]
Should be resolved in the next CLI build (and for 2.0.0)

**Comment by BooRar** [comment]
thanks danmosemsft
