### ISSUE TITLE
Source-build patch removal for core-setup

### ISSUE THREAD

**Issue by crummel** [dotnet/core-setup#6762]
Source-build has some patches that we are currently applying to your repo.  This issue tracks removing the patches.  These patches can be found at https://github.com/dotnet/source-build/tree/release/3.0/patches/core-setup.

Patches that have the responsibility "Repo" and the Disposition "Incorporate" are patches that we believe are valid source-build fixes that should be moved into your repo.  Please let us know if these don't seem like good patches.  Any changes with the responsibility "source-build" is something that we plan to keep going forward or integrate in another way - please also let us know if you think there may be problems with those patches.

Patch name | Type | Disposition | Responsibility | Notes
-- | -- | -- | -- | --
core-setup/0001-Copy-run.cmd-changes-from-corefx.patch | Build | Remove | Repo | This will go away once core-setup switches   to Arcade.
core-setup/0002-Disable-licenseUrl-warning.patch | ToolCompat | Remove | source-build |  
core-setup/0003-Disable-overriding-CentOS-as-RHEL.patch | Bug | Incorporate | Repo | Believe this was fixed upstream already.
core-setup/0003-Import-dependencies-props-after-eng-Versions-props.patch | Flow | Incorporate | Repo | May also go away with the Arcade switch.

**Comment by dagood** [comment]
Done by https://github.com/dotnet/core-setup/pull/7346 for preview 8. (Missed closing this issue earlier.)
