### ISSUE TITLE
Rename FrameworkList.xml to RuntimeList.xml in runtime packs

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#6764]
Request from @dsplaisted, seems reasonable to me. It's a simple rename around here:

https://github.com/dotnet/core-setup/blob/5c89dd7c0a3a83e4c122268f061e0eda81150799/src/pkg/projects/dir.targets#L247-L272

But it would be nice to also update the naming in the infra to avoid making this confusing afterwards.

**Comment by dagood** [comment]
@dsplaisted I'm assuming there's a specific reason to have the names different between targeting and runtime packs, like helping downstream code know what it's looking at if it doesn't know the package id at that point? (Otherwise, it seems better to find a single name that fits both types.)

Also, what should this be called for the AppHost pack, or do we not care about this list in that case?

**Comment by dsplaisted** [comment]
We consider them different files.  A "Framework List" has in the past been associated with a targeting pack, so it doesn't apply to the runtime pack.

I kind of doubt that we will ever need to programmatically use the name of the file to figure out what type of manifest it is.  The difference in names is more for humans than computers.  It makes it easier to document and refer to these files.

**Comment by dagood** [comment]
I see, so far the implementation has been essentially the same for both, but I can see how it helps for docs.

Thoughts on the AppHost pack question?

**Comment by dsplaisted** [comment]
I don't think we need to use the FrameworkList file from the AppHost pack.  We only look for a single file in the AppHost pack, and we calculate the path to that file.

In fact, the existing FrameworkList.xml in the AppHost pack looks like it's empty.  So I would say unless we have a scenario where we'd want to use a manifest in the AppHost pack, that we should just not include any XML manifest at all.
