### ISSUE TITLE
Add locale information to resource DLLs in runtime pack manifest

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/core-setup#6768]
The runtime pack manifest (currently named FrameworkList.xml, to be changed to RuntimeList.xml per #6764) includes the resource assemblies.  However, it doesn't specify which locale they belong to.

To continue to support handling the resource assemblies correctly (see https://github.com/dotnet/sdk/issues/3068) while using the runtime pack manifest, we need the locale metadata to be specified in there.

I would suggest doing this via adding a Culture attribute (ie `Culture="cs"`) to the `File` elements.  We might also want to change the `Type` from `Managed` to `Resource`, though I'm not really sure about that one.  @nguerrera @peterhuene thoughts?

Here is what the resource files currently look like in the manifest:

```xml
  <File Type="Managed" Path="runtimes/win-x86/lib/netcoreapp3.0/cs/PresentationCore.resources.dll" AssemblyName="PresentationCore.resources" PublicKeyToken="31bf3856ad364e35" AssemblyVersion="4.0.0.0" FileVersion="4.800.19.30805" />
  <File Type="Managed" Path="runtimes/win-x86/lib/netcoreapp3.0/cs/PresentationFramework.resources.dll" AssemblyName="PresentationFramework.resources" PublicKeyToken="31bf3856ad364e35" AssemblyVersion="4.0.0.0" FileVersion="4.800.19.30805" />
  <!-- (snip) -->
  <File Type="Managed" Path="runtimes/win-x86/lib/netcoreapp3.0/de/PresentationCore.resources.dll" AssemblyName="PresentationCore.resources" PublicKeyToken="31bf3856ad364e35" AssemblyVersion="4.0.0.0" FileVersion="4.800.19.30805" />
  <File Type="Managed" Path="runtimes/win-x86/lib/netcoreapp3.0/de/PresentationFramework.resources.dll" AssemblyName="PresentationFramework.resources" PublicKeyToken="31bf3856ad364e35" AssemblyVersion="4.0.0.0" FileVersion="4.800.19.30805" />
```

**Comment by peterhuene** [comment]
I think adding a `Locale` (or `Culture` to match the SDK metadata) makes sense.

Regarding the type, I have no strong opinion as to whether it should be marked by a new "Resource" type or if a "Managed" file that has a locale/culture is inherently a resource file.

**Comment by dsplaisted** [comment]
If we're already using `Culture` elsewhere, then let's try to align the runtime pack manifest to that.

**Comment by nguerrera** [comment]
Culture is the .net term for this.

**Comment by dagood** [comment]
I'll go with `Culture="cs"` and leave type as `Managed` unless something comes up.

**Comment by dsplaisted** [comment]
@dagood Digging into this a bit more, I think the `Type` should be `Resources` or similar.  We treat the resource DLLs differently- they don't get written to the deps.json file for example.  Our current convention-based code is [using `resources`](https://github.com/dotnet/sdk/blob/cb95988d8aba8f6a383feb2a7dc9890e5bce550c/src/Tasks/Microsoft.NET.Build.Tasks/ResolveRuntimePackAssets.cs#L156) for the asset type.

**Comment by dagood** [comment]
`Satellite` seems like it might make sense too, or maybe it's too specific? Up to you. For now I'll plan to go with `Resources` when I get to this.

**Comment by dsplaisted** [comment]
Since it's called "resources" elsewhere, that's what I'd go with here, similar to locale vs culture.

It may be worth noting that "Managed" actually have an asset type of "runtime" in the SDK, and in the deps.json.  I don't feel strongly about changing that though.
