### ISSUE TITLE
WPF has removed PresentationUI ref assembly

### ISSUE THREAD

**Issue by miguep** [dotnet/core-setup#6782]
Related to #6210 , WPF has removed PresentationUI ref assembly, the lib assembly still exists. 
This binary was removed in https://github.com/dotnet/wpf/issues/918 and will be flowing up.

@vatsan-madhavan @rladuca @dagood

**Comment by dagood** [comment]
After fixing the Profile classification mismatch, this causes a ref assembly closure verification error in https://github.com/dotnet/core-setup/pull/6792:

```
D:\a\1\s\src\pkg\packaging-tools\framework.packaging.targets(446,5):
  Assembly 'PresentationFramework' is missing dependency 'PresentationUI'
  [D:\a\1\s\src\pkg\projects\windowsdesktop\pkg\Microsoft.WindowsDesktop.App.pkgproj]
```

https://dev.azure.com/dnceng/public/_build/results?buildId=221973&view=logs, win-x64 `pkg.binlog` to see the error in context.



/cc @ericstj

**Comment by miguep** [comment]
@dagood thanks for the info, we took a look and it seems that our ref assembly generation for PresentationFramework is not entirely correct, we're planning on switching to GenAPI in the near future, until that we'll back out the PresentationUI change.

**Comment by dagood** [comment]
Thanks! I closed the current update PR that had my adjustment--once the removal is reverted, the next PR will work.

**Comment by dagood** [comment]
Closing: this was unblocked a while ago, and mopped up recently with https://github.com/dotnet/core-setup/issues/6901.
