### ISSUE TITLE
Fix runtime pack RuntimeList: missing native files

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#6786]
It looks like files built in Core-Setup (`hostfxr.dll`, `hostpolicy.dll`) don't have the `IsNative` metadata, causing them to be ignored. (Looking at an old win-x64 build.)

Looking at a recent build, there's a lot more missing now.

**Comment by dsplaisted** [comment]
Consider adding a test that all files in the `runtimes/<RID>/native` folder are included in the manifest, in order to catch this type of issue in the future.

**Comment by dagood** [comment]
There's at least one txt documentation file that doesn't make sense to me to include. But adding a redundant check that uses different criteria would make sense.

**Comment by dagood** [comment]
I thought I had an issue for setup testing, but I couldn't find it, so I filed https://github.com/dotnet/core-setup/issues/6793.

**Comment by dagood** [comment]
I'm not able to find a package from an official build that has more than just the host files missing from the manifest (which is an easy fix). @dsplaisted, what version are you seeing this with?

I thought I saw more files missing when I looked at this originally, but maybe I made a mistake trying to examine it too quickly.
