### ISSUE TITLE
Switch Core-Setup packages to SemVer v2

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#6825]
The 3.0 host has support for semantic versioning 2.0.0, per https://github.com/dotnet/core-setup/issues/4795.

At the next reasonable opportunity, we should switch to SemVer v2, which is the Arcade SDK default. This could be done before producing a prerelease for a new patch (3.0.1), minor (3.1.0), or major (4.0.0). Tentatively putting this on the 3.1 milestone.

For 3.0.0 previews, we need to continue using SemVer v1 because we have already released 3.0.0 packages with SemVer v1 style versions. (https://github.com/dotnet/core-setup/issues/4952#issuecomment-454163938)

**Comment by jeffschwMSFT** [comment]
Thanks @dagood for opening this issue... this is also on my radar to ensure it happens.

cc @sdmaclea

**Comment by sdmaclea** [comment]
This should probably be done immediately when main becomes the 3.1 branch. Before the first nuget package is published for 3.1 anywhere.

**Comment by dagood** [comment]
I realized (working on Arcade switchover) that I can condition it on the version so this happens without intervention:

```xml
<!-- Disable SemVer v2 until after 3.0. -->
<SemanticVersioningV1 Condition="'$(MajorVersion).$(MinorVersion)' == '3.0'">true</SemanticVersioningV1>
```

Then we can delete those lines later to clean up (if we get around to it). I'll keep this change in my Arcade branch for now unless it seems like a bad idea. 😄

**Comment by sdmaclea** [comment]
Seems like a good idea.
You could even include the patch if you wanted 3.0 maintenance to fix this...

**Comment by sdmaclea** [comment]
If arcade gets backported to 2.2 et. al.  This will have to be checked.  Maybe a better comparison than '==' would be more backportable....

**Comment by dagood** [comment]
True, not sure how to get MSBuild smart enough to do a nice version comparison, but throwing another clause on seems reasonable:

```xml
<!-- Disable SemVer v2 until after 3.0.0. -->
<SemanticVersioningV1 Condition="
  $(MajorVersion) &lt; 3 or
  '$(MajorVersion).$(MinorVersion).$(PatchVersion)' == '3.0.0'">true</SemanticVersioningV1>
```

**Comment by sdmaclea** [comment]
That is what I was thinking.

**Comment by dleeapho** [comment]
Per discussion with @leecow we should make an announcement (dotnet/announcement) about the change to semver v2. Also we need to ensure the release pipelines are changed.

**Comment by dagood** [comment]
There's discussion in an email thread about the need to do this before building any 5.0 prerelease versions. It would be a shame to get locked in with semver v1. (Although I believe we'd only be locked in for one prerelease.)

A complication is that the Arcade migration work isn’t merged yet, and I don’t know how well the pre-Arcade tooling works with semver v2. A workaround would be to use a temporary prerelease that’s very early in the sort order and doesn't match the rest of the product yet, then switch to a matching prerelease once we're able to move to semver v2.

**Comment by dagood** [comment]
I tried to rig it up, submitted this PR: https://github.com/dotnet/core-setup/pull/7222. But I expect if it works we'd put it in https://github.com/dotnet/core-setup/pull/7221 to merge at the same time as moving to 5.0.

**Comment by dagood** [comment]
The logic worked! The 3.1 and 5.0 builds produce artifacts with semver v2 versions.
