### ISSUE TITLE
Remove IgnoredDuplicateType once cleaned up in WPF

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#6838]
https://github.com/dotnet/core-setup/pull/6817#issuecomment-502840829

https://github.com/dotnet/core-setup/blob/f40e2ca284dab1abf2a33b6ae7c19c52e372500c/src/pkg/projects/windowsdesktop/pkg/Microsoft.WindowsDesktop.App.pkgproj#L30-L43

**Comment by ojhad** [comment]
Types have been removed from WPF as part of this DARC PR: https://github.com/dotnet/wpf/pull/1000

**Comment by dagood** [comment]
Complete: master https://github.com/dotnet/core-setup/pull/7868, 3.0 https://github.com/dotnet/core-setup/pull/7970.
