### ISSUE TITLE
Help and error messages from the host (dotnet.exe) need to be localized

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/core-setup#685]
## Steps to reproduce
Run `dotnet` while having your machine locale set to French. 

## Expected  behavior
See the help text in French. 

## Actual behavior
See the help text in English. 

All of the errors and help texts need to be localized. 

/cc @schellap @gkhanna79

**Comment by gkhanna79** [comment]
@schellap @ramarag PTAL

**Comment by gkhanna79** [comment]
@blackdwarf What all OS platforms is this for?

**Comment by blackdwarf** [comment]
@gkhanna79 this is for all the platforms we support.

**Comment by gkhanna79** [comment]
@richlander Is this actionable post our discussion yesterday about localization?

CC @Petermarcu

**Comment by gkhanna79** [comment]
@ramarag Is this issue being used to track moving host help pieces CLI for localization?

CC @livarcocc

**Comment by ramarag** [comment]
This will be tracked by https://github.com/dotnet/cli/issues/6255
