### ISSUE TITLE
apphost has no symbols when analyzed by Watson

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/core-setup#6858]
The problem is that we build the `apphost.exe` in the lab, and it gets the PDB path pointing to `some/path/apphost.pdb`. Then when its used by SDK it gets renamed to `myapp.exe`, but the PDB path in it still points to `some/path/apphost.pdb`.

When debugging, the debugger will not find the symbols because it gets confused by the name mismatch. Note that it will work if the exact path to PDB matches, so it works when developing in the core-setup repo locally.

This is specifically a problem for dumps and even more so for Watson. In those cases the debugger will not find the symbols.

There should be a way to do this which is supported by the debuggers. The trick is to change the PDB path in the executable to not include the full path, but just the filename `apphost.pdb`. With that the debugger should use that to look it up on symbol servers regardless of the name of the executable.

**Comment by elinor-fung** [comment]
Maybe I'm missing something, but the debugger should still be able find `apphost.pdb` on the symbol servers? It should look next to the .exe, then at the the path embedded in the binary, and then at the configured symbol cache and paths (which should not use the path, just the name and GUID).

I was able to pull down `apphost` symbols from the public symbol server for a dump of a project I built with the released 3.0 preview 6. Or is this specific to dumps from Watson somehow?

**Comment by vitek-karas** [comment]
I admit I didn't actually try this - we had it show up in Watson in WPF apps. And I discussed this with @cshung , he proposed the solution of dropping the path from the PDB field.

**Comment by leculver** [comment]
I am taking a closer look today/tomorrow.

**Comment by leculver** [comment]
I have fully validated that the renamed `apphost.exe` has the proper PDB information in it, that this PDB is on our symbol servers, the debugger correctly loads it, and that the debugger can correctly symbolize stack frames and globals in the executable.
