### ISSUE TITLE
source-build: Remove Newtonsoft.Json prebuilt

### ISSUE THREAD

**Issue by adaggarwal** [dotnet/core-setup#6881]
Newtonsoft.Json | 9.0.1
-- | --

https://github.com/dotnet/source-build/issues/885

**Comment by dagood** [comment]
Based on some prebuilt report lines you gave me, this appears to be ref-only.

Version is hard-coded when building DependencyModel (I don't think has to change for ref-only (?)):

https://github.com/dotnet/core-setup/blob/8d023a6fea7824648ea860f6ba05d236a1641d54/src/managed/Microsoft.Extensions.DependencyModel/Microsoft.Extensions.DependencyModel.csproj#L45

The local build task reference seems to be transitive rather than direct.

**Comment by adaggarwal** [comment]
I'm not sure about this. 

@crummel, any comments?

This is what I saw in project annotated-usage:

```
<AnnotatedUsage Id="Newtonsoft.Json" Version="9.0.1" File="bin/src/core-setup.61f30f5a23af498908cadd9cc282d4d67d71f522/bin/obj/rhel.7-x64.Debug/core-setup.tasks/project.assets.json" Project="bin/src/core-setup.61f30f5a23af498908cadd9cc282d4d67d71f522/" SourceBuildPackageIdCreator="newtonsoft-json NewtonsoftJsonPackageVersion/12.0.2" />

  <AnnotatedUsage Id="Newtonsoft.Json" Version="9.0.1" File="bin/src/core-setup.61f30f5a23af498908cadd9cc282d4d67d71f522/bin/obj/rhel.7-x64.Release/Microsoft.Extensions.DependencyModel/project.assets.json" IsDirectDependency="true" Project="bin/src/core-setup.61f30f5a23af498908cadd9cc282d4d67d71f522/" SourceBuildPackageIdCreator="newtonsoft-json NewtonsoftJsonPackageVersion/12.0.2" />

  <AnnotatedUsage Id="Newtonsoft.Json" Version="9.0.1" File="bin/src/core-setup.61f30f5a23af498908cadd9cc282d4d67d71f522/bin/obj/rhel.7-x64.Release/core-setup.tasks/project.assets.json" Project="bin/src/core-setup.61f30f5a23af498908cadd9cc282d4d67d71f522/" SourceBuildPackageIdCreator="newtonsoft-json NewtonsoftJsonPackageVersion/12.0.2" />
```

**Comment by crummel** [comment]
Yeah, what Davis says seems accurate.  @dseefeld - would we do ref-only Newtonsoft.Json packages?  Otherwise from the comment in DependencyModel.csproj it sounds like core-setup could upgrade after the SDK does?

**Comment by dseefeld** [comment]
We can add Newtonsoft.Json 9.0.1 as a ref pkg, but it needs to be ref-only for all usages of that package.

**Comment by crummel** [comment]
So we can't do it yet, but once NuGet and the SDK update we should be able to.  Or it sounds like core-setup could upgrade at that point.

**Comment by dagood** [comment]
+@eerhardt, some source-build discussion about the Newtonsoft.Json 9.0.1 dependency `Microsoft.Extensions.DependencyModel` has when building for non-`netstandard2.0` TFMs.

**Comment by eerhardt** [comment]
See also https://github.com/dotnet/core-setup/issues/5045, which discusses removing TFMs lower than `netstandard2.0`.

**Comment by dleeapho** [comment]
Closing since this was addressed by source-build.
