### ISSUE TITLE
WPF has removed PresentationUI ref assembly

### ISSUE THREAD

**Issue by rladuca** [dotnet/core-setup#6901]
Follow on to: #6782 

As a heads up, WPF has made the switch to GenAPI for reference assemblies.  As such we've removed PresentationUI (or will be shortly) and handled the prior dangling reference from PresentationFramework's reference assembly.

This work is being done in https://github.com/dotnet/wpf/pull/1057 and its associated internal PR.

@dagood This should be coming in Monday or Tuesday.  I apologize for the late heads up and possible late flow, but we had issues with GenAPI code output that we had to manually overcome.

**Comment by rladuca** [comment]
We just got this in tonight.  The next flow should see the removal of PresentationUI with no dangling references.  Please let me know if anything goes awry.

**Comment by dagood** [comment]
I applied a fixup (removing classification from PresentationUI) to https://github.com/dotnet/core-setup/pull/6916 to unblock the PR.

**Comment by dagood** [comment]
PR was auto-merged successfully! Thanks for the heads up.
