### ISSUE TITLE
License issue : "Flagged: GPL-3.0-only in Microsoft.Extensions.DependencyModel"

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/core-setup#6908]
My [project ](https://github.com/dotnetcore/Natasha)uses the MIT License.

This is the result of a [fossa ](https://app.fossa.com/projects/git%2Bgithub.com%2Fdotnetcore%2FNatasha/refs/branch/master/ed4c128444d3083988acfebc02ebfb455c5eaa2f/issues/licensing?filter=policy_flag&revisionScanId=735420)scan.  How do I solve this problem?
![image](https://user-images.githubusercontent.com/16236903/59985080-c0abf600-9661-11e9-8b26-8a2c5dcdf3cb.png)

**Comment by dagood** [comment]
I don't seem to have access to the bit of UI in your screenshot showing the reason for the flag, but it looks like a false positive. The `.signature.p7s` file is about signing, not the license--this project uses the MIT license. It looks like you might have to try the Make Correction button and work with the FOSSA people.

**Comment by NMSAzulX** [comment]
@dagood  Okay, I soved it manually. Thank you very much.
