### ISSUE TITLE
Microsoft.NETCore.App 1.2.0-* should target netcoreapp1.2

### ISSUE THREAD

**Issue by davidfowl** [dotnet/core-setup#695]
It still only targets 2 tfms.

https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.App

/cc @weshaggard

**Comment by davidfowl** [comment]
It should target 3.

- netcoreapp1.0
- netcoreapp1.1
- netcoreapp1.2

**Comment by weshaggard** [comment]
I don't have any plans to do this right now as nothing is actually using netcoreapp1.2 in corefx yet. Is this blocking something for you @davidfowl?

**Comment by davidfowl** [comment]
It's not blocking anything right this moment but it has the potential for errors:

> (well they are actually using netcoreapp1.1 as a placeholder still)

I think *this* is a BIG mistake. I'd love for us to get in the habit of bumping the version immediately after we branch (like you do with netstandard1.7). Corefx/CoreCLR has to create the slot for other teams to build upon. As soon as there's a new API, it needs to go into the right folder automatically or it will cause mismatches and heartache for downstream components that assume the right thing was happening at the core. 

We're about to adopt the latest NetStandard.Library, currently 1.6.2 and in theory, nothing should break with Microsoft.NETCore.App 1.0 or Microsoft.NETCore.App 1.1 if the project's TFM hasn't changed. This is only true if we didn't mess anything up...

**Comment by Petermarcu** [comment]
Yeah, I believe we need NuGet support with the proper mappings to also come online right away to be able to do that properly.

**Comment by weshaggard** [comment]
>I think this is a BIG mistake. I'd love for us to get in the habit of bumping the version immediately after we branch (like you do with netstandard1.7). 

Agreed. We should do our best to bump these when we version but in some cases the tooling blocks our ability to do it right away. We will be bumping over the next few weeks in corefx and then I will follow-up with the change to the meta-package here. 

cc @ericstj

**Comment by weshaggard** [comment]
We have updated everything in our repo to be netcoreapp, which represents the latest version which currently maps to netstandard2.0 behind the scenes. So this has been fixed.
