### ISSUE TITLE
Extend nethost get_hostfxr_path to take an optional path to dotnet

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/core-setup#6958]
Currently the `nethost` `get_hostfxr_path` looks like this:
```C++
int get_hostfxr_path(
    char_t * buffer,
    size_t * buffer_size,
    const char_t * assembly_path)
```

It works basically exactly like `apphost`, in that it relies on the app itself or the environment variables to locate the `hostfxr`. This works well for scenarios which are `apphost` like, but it doesn't work for scenarios which are more `dotnet.exe` like.

ASP.NET uses this API to find `hostfxr` and then call the `hostfxr_initialize_for_dotnet_command_line`, but that only works sometimes. If the input is a true `dotnet.exe` command line like `<some path>/dotnet.exe <app path>/app.dll` then there's no way to combine these two APIs to get the desired result. Calling `get_hostfxr_path` on the `<app path>/app.dll` will not be able to find the `hostfxr` in the `<some path>` (unless there are env. variables setup).

To resolve this the proposal is to add a new optional parameter to `get_hostfxr_path` through with the caller could specify the path to the runtime if it's known. Note that there's still value in this function even if the caller knows the location of the runtime as something still has to perform the "find the latest version of `hostfxr`" part of the search.

```C++
struct get_hostfxr_parameters {
    size_t size;
    const char_t* dotnet_root;
};

int get_hostfxr_path(
    char_t * buffer,
    size_t * buffer_size,
    const char_t * assembly_path,
    const get_hostfxr_parameters * parameters /* optional */
)
``` 

The `dotnet_root` could be null, in which case the behavior remains unchanged (apphost behavior). If it is specified it should contain path to folder which contains `dotnet.exe` (which won't be verified), in which case the API should behave like `dotnet.exe` does (basically always take the `hostfxr` from the `dotnet_root`).

The `get_hostfxr_parameters` is extensible via the `size` field which effectively acts like a version of the structure.

With this change users like ASP.NET can parse the command and if it contains `dotnet.exe` they would pass the path to it (if there's some) to the API to get the desired behavior.

This still doesn't cover the case where the caller modifies `PATH` to point to non-standard location for `dotnet.exe` and then tries to use `dotnet.exe app.dll`, but there's really no good solution for that case without parsing the `PATH`.

Open questions:
* Maybe the extensible struct is an overkill and we should simply take an additional `const char_t * dotnet_root` parameter.

Compatibility notes:
* `nethost` is special in that the only way to update it in a given use case is through an explicit action. The `.dll` is shipped with customer app, and as such it can only be updated via an explicit action on the customer side. So even breaking changes in the library are not really breaking in the normal sense - if the customer doesn't explicitly upgrade to newer version, the existing library will remain unchanged.

**Comment by jkotalik** [comment]
The proposal looks great to me. One small question:

> This still doesn't cover the case where the caller modifies PATH to point to non-standard location for dotnet.exe and then tries to use dotnet.exe app.dll, but there's really no good solution for that case without parsing the PATH.

To make sure I understand that scenario, this can occur when someone appends dotnet.exe to PATH and there is already another dotnet.exe prior on the PATH. Ex: `C:\Program Files\dotnet\;C:\MyPath\To\Dotnet`. Many places today, we prepend dotnet.exe to the path such that if someone calls dotnet app.dll, it picks up the new one.

**Comment by vitek-karas** [comment]
I'm assuming that ASP.NET module takes the "command line" and parses is as `<dotnet_root>/dotnet.exe <app_path>`. If `dotnet_root` is absolute path than the proposal above will work. If it's a relative path I think it should work as well (based on current directory). But if `dotnet_root` is empty, then the `dotnet.exe` is normally resolved from the `PATH`. We can't replicate that resolution and I assume ASP.NET doesn't do that either. Then there are two options:
* The `PATH` points to globally installed location (basically what one gets by running our runtime installers) - in that case the above will still work because we will find the globally installed location based on registry or just going to program files.
* The `PATH` points to a custom location - so something on the machine modified the `PATH` and "prepended" the custom location. In this case the above will not work and I'm no aware of any way to actually make it work (other then replicating `PATH` resolution, which is super tricky)

**Comment by jkotalik** [comment]
We did make prepended PATH resolution to a custom location work in ANCM today, and depending on verification it may be a requirement. Commonly on Azure App Service, when installing a preview build of .NET, we prepend the path to a custom dotnet location. 

To make it work, we did have to path probe to solve this problem.

**Comment by vitek-karas** [comment]
Even better then, as it should work in pretty much all cases for ASP.NET.

**Comment by elinor-fung** [comment]
I like the struct for extensibility. I do think it could make sense to move the optional `assembly_path` parameter into `get_hostfxr_parameters` as well?
