### ISSUE TITLE
Integrate intellisense xml files into WindowsDesktop shared framework

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/core-setup#6966]
WPF's transport packages (Microsoft.DotNet.Wpf.GitHub, Microsoft.DotNet.Wpf.DncEng) now carry intellisense.xml files. 

These should be integrated into Microsoft.WindowsDesktop.App. 

WinForms will start carrying these intellinsense xmls soon in their transport packages as well (if they don't already). 

/cc @dagood 
/cc @merriemcgaw

**Comment by AdamYoblick** [comment]
Thank you Vatsan. I will be working on this later today and tomorrow.

**Comment by dagood** [comment]
Can you clarify what's missing? https://dotnetcli.blob.core.windows.net/dotnet/Runtime/3.0.0-preview8-27827-03/Microsoft.WindowsDesktop.App.Ref.3.0.0-preview8-27827-03.nupkg, for example, has:

```
ref\netcoreapp3.0\PresentationCore.xml
ref\netcoreapp3.0\PresentationFramework.Aero.xml
ref\netcoreapp3.0\PresentationFramework.Aero2.xml
ref\netcoreapp3.0\PresentationFramework.AeroLite.xml
ref\netcoreapp3.0\PresentationFramework.Classic.xml
ref\netcoreapp3.0\PresentationFramework.Luna.xml
ref\netcoreapp3.0\PresentationFramework.Royale.xml
ref\netcoreapp3.0\PresentationFramework.xml
ref\netcoreapp3.0\ReachFramework.xml
ref\netcoreapp3.0\System.Printing.xml
ref\netcoreapp3.0\System.Windows.Controls.Ribbon.xml
ref\netcoreapp3.0\System.Windows.Input.Manipulations.xml
ref\netcoreapp3.0\System.Windows.Presentation.xml
ref\netcoreapp3.0\System.Xaml.xml
ref\netcoreapp3.0\UIAutomationClient.xml
ref\netcoreapp3.0\UIAutomationClientSideProviders.xml
ref\netcoreapp3.0\UIAutomationProvider.xml
ref\netcoreapp3.0\UIAutomationTypes.xml
ref\netcoreapp3.0\WindowsFormsIntegration.xml
```

The issue title suggests they're expected in the *shared framework*, but I would only expect them in the targeting pack to be used when developing for WindowsDesktop.

**Comment by vatsan-madhavan** [comment]
You are right - I was indeed looking for it in the shared framework. I think that was not the right place to look as you've pointed out. The ref-pack does have the xml's - the issue is moot. 

Thanks for looking at the quickly and clarifying where to look - appreciate it!

**Comment by AdamYoblick** [comment]
@dagood The winforms ref package now has intellisense xml files in it as well. Our master has the change, and the build is currently running. The PR build passed so I don't foresee any issues.

**Comment by merriemcgaw** [comment]
Sweet!
