### ISSUE TITLE
MSI installer outputs are not signed in most recent release/3.0 build

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#7031]
E.g. this build:

* https://dotnetcli.blob.core.windows.net/dotnet/Runtime/3.0.0-preview7-27901-06/dotnet-runtime-3.0.0-preview7-27901-06-win-x64.msi
* https://dotnetcli.blob.core.windows.net/dotnet/Runtime/3.0.0-preview7-27901-06/dotnet-targeting-pack-3.0.0-preview7-27901-06-win-x64.msi
* https://dotnetcli.blob.core.windows.net/dotnet/Runtime/3.0.0-preview7-27901-06/dotnet-runtime-3.0.0-preview7-27901-06-win-x64.exe (this is an example of a file that *is* signed, not an MSI)

https://dev.azure.com/dnceng/internal/_build/results?buildId=246234

It looks like the MSIs are built (`Create installers`), then signed (`Sign MSI and cab files`), then built again (`Create bundles`), and the second build overwrites the signed artifacts. The bundle build step shouldn't build the MSIs.

@johnbeisner can you comment on how blocking this is? Could we manually sign these files for VS insertion to avoid a respin?

I'm taking a look whether this is a regression from preview 6.

/cc @wtgodbe

**Comment by dagood** [comment]
Preview 6 MSIs are signed, this is a regression. Based on the sequence of events in the build, I'd bet something went wrong with msbuild target dependencies. Will look further.

**Comment by leecow** [comment]
Thanks, Davis - unsigned MSIs will indeed block the release.

**Comment by dagood** [comment]
The fix has been merged into `release/3.0` by https://github.com/dotnet/core-setup/pull/7033, waiting for next build to confirm MSIs are signed.

**Comment by dagood** [comment]
Confirmed all MSIs (and bundle installers) are signed in the latest 3.0 build. I also made sure the copies in the VS insertion nupkgs are signed.
