### ISSUE TITLE
Use Arcade publish functionality

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#7118]
The initial implementation of publish as part of the move to the Arcade SDK still uses the finalize job and custom tasks. Core-Setup should rely on Arcade publishing functionality instead, where possible.

**Comment by dleeapho** [comment]
Currently dependent on Arcade publish functionality that is not yet complete.

**Comment by dagood** [comment]
Completed by https://github.com/dotnet/core-setup/pull/7725 (master) and https://github.com/dotnet/core-setup/pull/7735 (release/3.0). Will handle any new issues that pop up as new build breaks.
