### ISSUE TITLE
Latest DependencyModel writes / as \u0002f breaks all but bleeding edge versions of xunit + `dotnet test`

### ISSUE THREAD

**Issue by nguerrera** [dotnet/core-setup#7137]
Deps files come out like this:

```
      "Microsoft.CodeCoverage\u002f16.0.1": {
        "runtime": {
          "lib\u002fnetcoreapp1.0\u002fMicrosoft.VisualStudio.CodeCoverage.Shim.dll": {
            "assemblyVersion": "15.0.0.0",
            "fileVersion": "16.0.28223.3002"
          }
        }
      },
      "Microsoft.CSharp\u002f4.0.1": {
```

Where \u0002f could be /

This breaks `dotnet test` on `dotnet new xunit` unless the xunit version used has https://github.com/xunit/visualstudio.xunit/commit/7553f4fa3b67884ccdda597f5429c5cdf2809d77 from yesterday.

Once https://github.com/dotnet/corefx/issues/37192 is available, DependencyModel should use it to only escape what's truly necessary. At a minimum / should be allowed through.

cc @ericstj @steveharter

**Comment by nguerrera** [comment]
Putting this in 3.0 milestone because we will have to pin the version of dependency model to a preview 6 build and we can't ship like that.

**Comment by nguerrera** [comment]
Looks like it + escaping is also a problem (so / fix is not sufficient). Ideally, the escaping would mimic what newtonsoft.json was doing with 2.2 dependency model.

**Comment by GrabYourPitchforks** [comment]
How is this breaking? This is perfectly valid JSON. In theory every single character could be "\uXXXX" escaped and it would still be a legitimate, well-formed payload. All JSON consumers need to anticipate "\uXXXX" escape sequences in the payload and handle them appropriately, otherwise they're not spec-compliant.

**Comment by nguerrera** [comment]
It's not about theoretical spec compliance. It's about the practical fact that every project in the world will have to take a new xunit to use 3.0 SDK because until a few days ago the private json reader in xunit was not spec compliant around this. 

It will break users that upgrade to 3.0 SDK without upgrading xunit. In this emprical sense, it is a breaking change.

I could maybe live with that (though it's not my call) if the failure was at all obvious, but thanks to my biggest pet peeve of all time, somebody is catching IndexOutOfRangeException and it manifests as "no tests discovered", which googling will very likely lead you on to a wild goose chase through the 42000 ways you can get this error. :(

Also, to be honest, the .deps file looks ugly and unreadable with this over-escaping. @davidfowl files bugs. / is incredibly common in the file, writing it as \u002f is just weird. What purpose does that serve?

**Comment by GrabYourPitchforks** [comment]
"/" should probably be allowed unescaped by default. I've been investigating this and I never found a valid reason why it was escaped. Escaping "+" definitely serves a purpose and prevents viable, real-world attacks for which there exists proofs of concept. See my comment at https://github.com/dotnet/corefx/issues/38354#issuecomment-504780719 for further information.

**Comment by GrabYourPitchforks** [comment]
That said, there are a few workarounds that can be performed. The JSON serializer is getting an option to pass a custom escaper. We could introduce a flag that directs the serializer to be less aggressive about escaping, and at your call site you could set that flag. (This flag clearly _would not_ be enabled by default, and we'd need to create some sort of signoff procedure for anybody who sets it.) You could also take the output of JSON serialization, search-and-replace "\uXXXX" with its unescaped equivalent, and write the replaced string to disk.

**Comment by nguerrera** [comment]
I assume 'you' here is the DependencyContext writer in this repo. We will do no such post-processing. I am not at all making any case to change System.Text.Json defaults, but I think the DependencyModel API should make .deps files that are compatible with readers in the wild unless there really is a security hole in that. 

As far as security hole, would it at all convince you that nobody is providing deps files as a web service or whatever. These are always written to local disk and read from local disk.

**Comment by GrabYourPitchforks** [comment]
> I think the DependencyModel API should make .deps files that are compatible with readers in the wild unless there really is a security hole in that.

Totally fine by me. :)

The scenario is well-defined, and I don't want to block this scenario from working. ASP.NET is in a similar situation, where they control the entire scenario end-to-end so they can make firm claims about how the data will be processed.

At the `System.Text.Json` level, the APIs have no knowledge whatsoever of the scenario in play or how the data will ultimately be used. So the default escaper opts to be very cautious. I'm trying to think of ways that would allow scenarios like the one in this work item to behave as expected while at the same time discouraging the average developer from opting out of our default protections.
