### ISSUE TITLE
Fix some CoreFX PDBs not being included in symbol archive zip/tarball

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#7147]
Reported at https://github.com/dotnet/source-build/issues/783#issuecomment-509816845:

> I looked at dll files vs pdb files in a 3.0 Preview 6 build (using source-build) and noticed that pdb files exist for all shared framwork dll files except:
> 
> ```
> Microsoft.Win32.Registry.dll
> SOS.NETCore.dll
> System.IO.FileSystem.AccessControl.dll
> System.IO.Pipes.AccessControl.dll
> System.Private.CoreLib.dll
> System.Private.DataContractSerialization.dll
> System.Private.Uri.dll
> System.Private.Xml.dll
> System.Private.Xml.Linq.dll
> System.Runtime.WindowsRuntime.dll
> System.Runtime.WindowsRuntime.UI.Xaml.dll
> System.Security.AccessControl.dll
> System.Security.Cryptography.Cng.dll
> System.Security.Cryptography.OpenSsl.dll
> System.Security.Principal.Windows.dll
> ```
> 
> Is this expected?
> 
> My test script is available here: https://gist.github.com/omajid/bd283b8f284247512329a15ae59ce6fc

This issue is present in the Microsoft build too, not just source-build. The "Symbols (zip)" linked in the readme has this gap. The `.ni.pdb` files seem to be present, there. For example:

```
System.IO.Pipes.AccessControl.ni.pdb <= Missing PDB for this
System.IO.Pipes.ni.pdb
System.IO.Pipes.pdb
```

The "Symbols (tar.gz)" links don't have `.ni.pdb` files, but have the same gap.

The transport package from CoreFX does seem to have the PDBs (checked preview 6 and `4.6.0-preview7.19326.2`), so I think something's going wrong in Core-Setup.

**Comment by omajid** [comment]
With 3.0 preivew 7, there's no longer a `SOS.NETCore.dll` at all, so there's no matching `SOS.NETCore.dll.pdb` either.

**Comment by dagood** [comment]
I noticed the missing files in the preview 7 symbol tarball correspond to the difference between the files that are in the shared framework vs. the targeting pack. This probably had to do with the complicated way the symbols are gathered together to put in the zip/tarball--maybe it used the wrong list of DLLs for discovery somehow.

But it looks like this got worse in preview 8, there are no CoreFX PDBs at all in the symbol packages or symbol archive tarball, only the crossgen outputs. The Arcade SDK migration would be the cause here. I think that to fix this, the symbol gathering logic should be simplified and move to the `depproj`--and doing so should also fix the preview 7 issue.

I'm planning to fix this for 3.0: the preview 8 issue is a clear regression due to infra changes that results in a broken artifact used to ship symbols with source-builds.

**Comment by dagood** [comment]
Noticed that `dotnet` symbols don't show up, but that being missing dates back much further. Opened https://github.com/dotnet/core-setup/issues/7954 for that separately, if it's even a problem.

**Comment by dagood** [comment]
Fixed with https://github.com/dotnet/core-setup/pull/7959 and https://github.com/dotnet/core-setup/pull/7995 (3.0 port).

**Comment by omajid** [comment]
With rc1, the only dll file missing a pdb file is `System.Runtime.CompilerServices.Unsafe.dll`

**Comment by dagood** [comment]
That's built from IL, so I'm guessing it makes sense for it not to have a PDB: https://github.com/dotnet/corefx/tree/master/src/System.Runtime.CompilerServices.Unsafe/src. (If not, CoreFX would be the place for a new issue. The PDB doesn't exist in the CoreFX transport package.)
