### ISSUE TITLE
Update versions of additional Nuget packages for 1.1.x servicing

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#715]
Please see the changes done in https://github.com/dotnet/core-setup/commit/3f9e52752857442a4b41aca085548863e0b6a24a#diff-68a141467209dfeea5bc5130245d26f4. 

These packages need to be updated for servicing 1.1.x as well. @schellap Can you PTAL at this at the earliest?

**Comment by schellap** [comment]
@gkhanna79, even though nothing changed in these packages, these just have to be produced with new version numbers?

**Comment by schellap** [comment]
>  these just have to be produced with new version numbers?
I believe this is to not overwrite uploaded blob storage packages.

**Comment by gkhanna79** [comment]
Correct.

**Comment by schellap** [comment]
Fixed by https://github.com/dotnet/core-setup/pull/727
