### ISSUE TITLE
Microsoft.DiaSymReader.Native.*.dll needs to be added to Shared FX

### ISSUE THREAD

**Issue by tmat** [dotnet/core-setup#72]
Binaries

```
Microsoft.DiaSymReader.Native.amd64.dll  // 64bit Windows dotnet cli
Microsoft.DiaSymReader.Native.x86.dll    // 32bit Windows dotnet cli
```

from package https://www.nuget.org/packages/Microsoft.DiaSymReader.Native/1.4.0-rc 

need to be present in the Windows build of Shared FX in order for the compiler to be able to emit Windows PDBs on Windows.

**Comment by tmat** [comment]
We are currently discussing other options.

**Comment by joshfree** [comment]
This is actually against the wrong branch too for 1.0.0

**Comment by tmat** [comment]
The library is actually loaded from SDK as it is supposed to be. The path to the library is correctly specified in deps.json and picked up from there by the loader.
