### ISSUE TITLE
First step with 1.2.0-beta-001137-00 on Windows ARM32

### ISSUE THREAD

**Issue by JPBlanc** [dotnet/core-setup#721]
## Steps to reproduce

I download 1.2.0-beta-001137-00 for Windows ARM32 at https://github.com/dotnet/core-setup and copy the folder layout to my Raspberry PI3.
I build a portable app on my x64 machine and publish it locally.
I copy the published app to my device modifying the runtimeconfig.json.
I run dotnet <path to my publishedapp.dll> on my device.

here is a close to hello world program that read the console 

```
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.Write("Enter your firstname :");
            String firstName = Console.ReadLine ();
            Console.WriteLine("Hello World! {0}", firstName);
        }
    }
}
```

## Expected  behavior
Enter your firstname :julius
Hello World! julius

## Actual behavior
Enter your firstname :Hello World!

It seems that it's not able to read the Console.

## Environment data
`dotnet --info` output:

Microsoft .NET Core Shared Framework Host
  Version  : 1.2.0-beta-001137-00
  Build    : a04683c31689b0449e1b546ddafe461327dd3a48

**Comment by gkhanna79** [comment]
> It seems that it's not able to read the Console.

What is the error you are seeing? Do you have an exception stacktrace or crash dump?

**Comment by JPBlanc** [comment]
No Error, no Exception,

>  String firstName = Console.ReadLine ();

 is not waiting for characters, and firstName remains null (the actual behavior is really what I see on the console).

**Comment by steveharter** [comment]
Closing; over a year old.
