### ISSUE TITLE
Add framework list metadata to prevent WPF theme assemblies from being auto-referenced

### ISSUE THREAD

**Issue by nguerrera** [dotnet/core-setup#7218]
The targeting pack framework list for Microsoft.WindowsDesktop.App should add ReferencedByDefault="false" to the following assemblies:

PresentationFramework.Aero
PresentationFramework.Aero2,
PresentationFramework.AeroLite
PresentationFramework.Classic
PresentationFramework.Luna
PresentationFramework.Royale

See https://github.com/dotnet/sdk/issues/3265 and dotnet/designs#81

cc @dagood

**Comment by dagood** [comment]
How does this differ from having no `Profile` assignment?

Maybe my question is how the "Integration" assemblies, the ones with no profile per https://github.com/dotnet/cli/issues/10536#issuecomment-488871926, end up being referenced, vs. how these are referenced.

**Comment by nguerrera** [comment]
Replied here: https://github.com/dotnet/core-setup/issues/7344#issuecomment-514354724

**Comment by dagood** [comment]
Done by https://github.com/dotnet/core-setup/pull/7346 for preview 8. (Missed closing this issue earlier.)
