### ISSUE TITLE
Preparing ROOTFS for cross-compilation

### ISSUE THREAD

**Issue by hqueue** [dotnet/core-setup#729]
As discussed in PR #724  and suggested in issue #725, we believe that we should keep consistency with other repos (e.g. CoreCLR and CoreFX) in the way we do cross compilation.

Therefore we need ROOTFS as a first step and I'm going to prepare ROOTFS following the logic from CoreCLR.

### Target
- ARM (only ARM this time, or do we need other architectures too?)
### New directories
- core-setup/cross
- core-setup/cross/arm
- core-setup/cross/arm-softfp
### New script files
- core-estup/cross/build-rootfs.sh

**Comment by hqueue** [comment]
@gkhanna79 @schellap @ramarag @janvorli Looking for any comment. Thank you in advance!

**Comment by gkhanna79** [comment]
For now, Arm support is sufficient @hqueue. Thank you for getting this enabled.

CC @kouvel

**Comment by hqueue** [comment]
Close this issues, since PR #747 is merged.
