### ISSUE TITLE
Fix up list of Windows compatibility pack libraries included in WindowsDesktop targeting pack and runtime

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#7290]
There are some bits of the compat pack that are very commonly used in ports to .NET Core WindowsDesktop, and we'd like to include in the WD targeting pack (and runtime) for ease of use.

## Expose in Desktop SDK

Assembly | Justification
-- | --
Microsoft.Win32.Registry.AccessControl | ACLs makes sense on Windows
System.Diagnostics.EventLog |  
System.Diagnostics.PerformanceCounter |  
System.DirectoryServices |  
System.IO.FileSystem.AccessControl |  
System.IO.Pipes.AccessControl | ACLs makes sense on Windows
System.Threading.AccessControl | ACLs makes sense on Windows

## Do not expose (remove)

Assembly | Justification
-- | --
System.Security.Permissions | Legacy tech

**Comment by dagood** [comment]
> System.IO.Pipes.AccessControl

The situation here looks a little strange, so I want to confirm. New CoreFX builds aren't producing a package for this library, you can see this in the 3.0 preview6 Windows compat pack dependencies, for example:

https://www.nuget.org/packages/Microsoft.Windows.Compatibility/3.0.0-preview6.19303.8

```
...
System.IO.Packaging (>= 4.6.0-preview6.19303.8)
System.IO.Pipes.AccessControl (>= 4.5.1)
System.IO.Ports (>= 4.6.0-preview6.19303.8)
...
```

@ericstj The assembly is currently shipped "runtime only" in NETCoreApp. The other AccessControl bits have a freshly built nupkg available for me to use for refs in WindowsDesktop. Is CoreFX missing packaging for `System.IO.Pipes.AccessControl`, or has it just not needed any changes and I should use 4.5.1?

**Comment by ericstj** [comment]
The package for System.IO.Pipes.AccessControl was removed with https://github.com/dotnet/corefx/commit/4e76a6c02552422ce07967f4249acad3b71b80ef.  You can use the 4.5.1 package.  What happens WRT implementation when you do this? So long as we omit it, should be fine.  @JeremyKuhne @carlossanlop

**Comment by dagood** [comment]
With https://github.com/dotnet/core-setup/pull/7324 as it is, `System.IO.Pipes.AccessControl.dll` from the 4.5.1 package does end up in the sharedfx and runtime pack, but I can add `ExcludeAssets="Runtime"` to make that not happen. (Closure validation then still works because it automatically ignores references to assemblies included in NETCoreApp.) This seems reasonable to me.

(Overlap like this isn't detected automatically, see https://github.com/dotnet/core-setup/issues/6727, https://github.com/dotnet/core-setup/issues/7340.)

**Comment by ericstj** [comment]
Interesting that it's getting added to the runtime pack.  I wonder why: I would have expected conflict resolution to knock it out.  Perhaps that's not being used when constructing the higher level shared frameworks?  I wonder if there are other unnecessary copies of runtime files.

**Comment by dagood** [comment]
> I wonder if there are other unnecessary copies of runtime files.

Yeah, https://github.com/dotnet/core-setup/issues/6727 lists some that I saw.

> Perhaps that's not being used when constructing the higher level shared frameworks? [...] Did you look into feeding in the lower framework platform manifests as a mechanism for avoiding the duplication?

I haven't looked into any mechanism yet, that's tracked by https://github.com/dotnet/core-setup/issues/7340. This is something we've planned to do from the beginning but I haven't had time for it.

**Comment by dagood** [comment]
The additions are complete in `release/3.0` by #7372.

(Making the same change in `master` (https://github.com/dotnet/core-setup/pull/7324) isn't practical until WindowsDesktop repos produce 5.0 builds.)

Removing `System.Security.Permissions` hasn't been done, and doesn't seem to be in scope for 3.0/3.1. This is discussed in/tracked by https://github.com/dotnet/core-setup/issues/7344.

/cc @terrajobst
