### ISSUE TITLE
Updates to AppHostPack MSIs forces an update to VS's sign exception list

### ISSUE THREAD

**Issue by johnbeisner** [dotnet/core-setup#7327]
**Problem:**
Visual Studio's 'Insertion Sign Check' whitelist: \src\ProductData\Engineering\VS_Baseline.csv
has 24 entries for the 'AppHostPack' MSIs:
```
SRC\REDIST\COMMON\NETCOREAPPHOSTPACK_*.*\X64\DOTNET-APPHOST-PACK-*.*.*-WIN-X64.MSIDIR\CAB1.CAB.CABDIR\FIL958F02C8C5A5AF8D6A41944CC2CD3CCA.EXE
SRC\REDIST\COMMON\NETCOREAPPHOSTPACK_*.*\X64\DOTNET-APPHOST-PACK-*.*.*-WIN-X64.MSIDIR\CAB1.CAB.CABDIR\FILABD5C38B116BFF50E0C79AFD971CEF03.DLL
SRC\REDIST\COMMON\NETCOREAPPHOSTPACK_*.*\X86\DOTNET-APPHOST-PACK-*.*.*-WIN-X86.MSIDIR\CAB1.CAB.CABDIR\FIL400A0601E9D4B359F576E174E62D406E.EXE
SRC\REDIST\COMMON\NETCOREAPPHOSTPACK_*.*\X86\DOTNET-APPHOST-PACK-*.*.*-WIN-X86.MSIDIR\CAB1.CAB.CABDIR\FIL33C05CEAF0837A0E3F0C65FF87840B5F.DLL
```

These exception entries correspond to unsigned files in the MSIs: "apphost.exe" and "comhost.dll"

Each time we insert a new version of the 'AppHostPack' MSIs; the randomly generated fileId needs to be updated.

Solution:
Make the fileId static. 
See the method used in dotnet/core-sdk for the SDK toolset MSI.

**Comment by dagood** [comment]
Merged for 3.0 with https://github.com/dotnet/core-setup/pull/7393.
