### ISSUE TITLE
.Net core not installing

### ISSUE THREAD

**Issue by Mech0z** [dotnet/core-setup#734]
I installed https://dotnetcli.blob.core.windows.net/dotnet/release/1.1.0/Installers/Latest/dotnet-win-x64.latest.exe

But when I do 
dotnet --version
I get:
1.0.0-preview3-004056

When I start my aspnet core app I upgraded to 1.1 I get 

The specified framework 'Microsoft.NETCore.App', version '1.1.0' was not found.

Am I doing something wrong?

**Comment by gkhanna79** [comment]
Are you able to run a console (HelloWorld) app?

CC @schellap @ramarag

**Comment by Mech0z** [comment]
Yes that works, wonder why it gives me that error then :/

My code is here https://github.com/Mech0z/FoosballCore2/tree/Core-1.1-upgrade

Its running in docker if thats relevant

**Comment by gkhanna79** [comment]
Your CSProj only references Microsoft.NETCore.App 1.0.0. Where is the reference for 1.1.0?

@davidfowl do you have any thoughts?

**Comment by Mech0z** [comment]
Tried changing it to 1.1 but didnt help

The full error message is 

> realpath(): Invalid argument
> The specified framework 'Microsoft.NETCore.App', version '1.1.0' was not found.
>   - Check application dependencies and target a framework version installed at:
>       /usr/share/dotnet/shared/Microsoft.NETCore.App
>   - The following versions are installed:
>       1.0.1
>   - Alternatively, install the framework version '1.1.0'.
> The program '' has exited with code 131 (0x83).

**Comment by gkhanna79** [comment]
Your output above refers to a non-Windows path location but your link above is for Windows installer. Did you try the correct installer for the platform?

**Comment by Mech0z** [comment]
Maybe because I am running Docker for windows with Linux containers, maybe I need to upgrade the container somehow all though I would expect it to figure that out itself

**Comment by Mech0z** [comment]
Fixed with https://github.com/Mech0z/FoosballCore2/commit/068cf5bc106680a1f4e478b7e7b1a25175645df0 

Just thought NuGet upgrade packages would take care of that :) but thanks for pointing me in the right direction 👍
