### ISSUE TITLE
WindowsDesktop dependencies (WPF, WinForms) are stale in master

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#7343]
It looks like `dotnet-wpf-int` isn't producing builds for the `.NET Core 5 Dev` channel yet, so `master` isn't getting updates. A few solutions:

* Change the subscription `master` has on the WindowsDesktop repos to use the 3.0 channel.
* Start merging `release/3.0` into `master` to get updates. (Still flowing, there.)

@wtgodbe, thoughts?

/cc @vatsan-madhavan @zsd4yr @ericstj @mmitche

**Comment by mmitche** [comment]
@dagood This is by design.  There are no 5.0 branded wpf/winforms assets yet.  We do not want to mix 5.0 and 3.0 together in a single build, and so we will be in this state for 5.0 until wpf/winforms have a branch producing 5.0 branded outputs.

**Comment by ericstj** [comment]
Why let them continue to get staler and staler in master?  Are the old 3.0 bits that are there any better than newer 3.0 bits from release?  I can imagine that not having them up to date will block some changes that need to be made in master.

**Comment by dagood** [comment]
> We do not want to mix 5.0 and 3.0 together in a single build

To make sure this is clear, we already do this: core-setup pulls in 3.0 WPF and WinForms assets and redistributes them as a 5.0 WindowsDesktop sharedfx and set of packages.

(Looks like we have another reason to split out WD generation into another repo (https://github.com/dotnet/core-setup/issues/5732).)

**Comment by mmitche** [comment]
Ahh that is true.  We could flow to 5.0 Dev in addition to 3.0 Dev, which would solve the problem...any objections?

And yes, #5732 would be great to do once we get a little clearer on what the repo structure will look like.

**Comment by dagood** [comment]
Sounds fine to me. I like that better than my suggestion about changing the Core-Setup subscription, because once the WD repos do create 5.0 assets, the change will be to where they publish rather than tracking down subscriptions that need to be added.

**Comment by mmitche** [comment]
Done.  New builds of master should flow into .NET Core 5 Dev and into core-setup master

**Comment by wtgodbe** [comment]
Ack, I agree with the solution here, thanks @mmitche

**Comment by dagood** [comment]
`master` is getting updates again, e.g. https://github.com/dotnet/core-setup/pull/7366. Thanks!
