### ISSUE TITLE
Remove Arcade SDK versioning workaround while doing branding update from preview8 to preview9

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#7348]
https://github.com/dotnet/core-setup/pull/7347 adds a workaround to keep Arcade SDK versions above the BuildTools versions, and it must be removed:

https://github.com/dotnet/core-setup/blob/7eada7f4473f28b4eaf16272ff923666f29483a4/eng/Versions.props#L7-L13

**Comment by dagood** [comment]
FYI @wtgodbe

**Comment by hoyosjs** [comment]
This downgrade problem hit master builds as well (.NET Core Dev 5). The highest versioned `Microsoft.NETCore.App` (and `Microsoft.NETCore.App.Internal`) pack is `5.0.0-alpha1.27919.8`, while the latest sane build is `5.0.0-alpha1.19381.4`. Should this fix be replicated on master until `alpha2` branding is building? @dagood

**Comment by dagood** [comment]
Where does it cause problems? I want to minimize usage of the workaround. I wouldn't expect it to be causing any issues in the SDK because it doesn't even build for 5.0 yet.

**Comment by dagood** [comment]
Closing: this was done by https://github.com/dotnet/core-setup/pull/7500.
