### ISSUE TITLE
dotnet error

### ISSUE THREAD

**Issue by maxi2009** [dotnet/core-setup#7470]
C:\Users\Maximiliano>dotnet new console -o Myapp
Failed to load the dll from [C:\Program Files\dotnet\host\fxr\2.2.6\hostfxr.dll], HRESULT: 0x80070057
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\2.2.6\hostfxr.dll failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

Este problema es en visual studio code,  Windows 7 Ultimate SP1

**Comment by vitek-karas** [comment]
Can you please make sure that you followed the instructions in the link in the error message? Specifically this part:
>**For Windows 7 or Windows Server 2008 R2:**
>In addition to KB2999226, make sure you also have KB2533623 installed. If you don't have this update installed, you'll see an error similar to the following when you launch a .NET Core application: The library `hostfxr.dll` was found, but loading it from `C:\<path_to_app>\hostfxr.dll` failed.

**Comment by vitek-karas** [comment]
If you're still running into problems, please open another issue or reopen this one if it makes sense.
