### ISSUE TITLE
[release/3.0] Built app executable cannot be signed

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/core-setup#7550]
## Steps to reproduce
- Build an app with an xcopy install of .NET Core Preview 8 (3.0.100-preview8-013640)
- Use SignTool.exe to sign the built .exe

## Expected  behavior
Signing suceeds

## Actual behavior
Signing fails with `error: 0x800700C1`

## Notes
This is a regression (from Preview 7). The apphost.exe (and comhost.dll) in the NuGet packages out of core-setup are being signed.  We need to avoid signing them, as they are modified when building with the SDK.

This prevents VS from being able to update to build using the 3.0 SDK Preview 8.

This does not affect the bundle installer.

**Comment by elinor-fung** [comment]
cc @dagood @vitek-karas @AaronRobinsonMSFT

**Comment by dagood** [comment]
The fix is merged for 3.0 preview 8: https://github.com/dotnet/core-setup/pull/7549.
