### ISSUE TITLE
Add '--hostbuildonly' option

### ISSUE THREAD

**Issue by jyoungyun** [dotnet/core-setup#764]
## Expected  behavior

 `./build.sh --build-driver-only`

## Actual behavior
This option only builds the dotnet-host-build binary. This is useful when you want to call it directly after we modify the dotnet-host-build tool.

**Comment by hqueue** [comment]
> `dotnet --hostbuildonly`
@jyoungyun  I think you meant `build_projects/dotnet-host-build/build.sh` not `dotnet ` right?

**Comment by jyoungyun** [comment]
@hqueue Yes, right. I correct the content of this issue. Thank you.
