### ISSUE TITLE
how can i know a specific net core sdk using which version of core-setup?

### ISSUE THREAD

**Issue by liesauer** [dotnet/core-setup#7694]
let's say `SDK 2.2.205`, when i run `dotnet publish`, how can i know which version of `hostfxr` is using?

**Comment by vitek-karas** [comment]
There are potentially two `hostfxr`s in question:
* The `hostfxr` used to run the SDK itself (in the above case the `dotnet publish` command is implemented in the SDK as managed code and runs that way). This will typically be the globally installed `hostfxr` in something like `ProgramFiles\dotnet\host\fxr\` - it always uses the latest version available on the machine (regardless of which SDK is being used).
* The `hostfxr` which is copied into the app output if the app is built as self-contained. This one I don't know exactly, but I would expect it to match the TFM of the app - so if the app is targeting .NET Core 2.2 I would expect to get 2.2 hostfxr. (I tried on a simple repro project and it works that way).

**Comment by liesauer** [comment]
for the second one, is it reliable that i extract the version of package `Microsoft.NETCore.DotNetHostResolver` from `deps.json`?

**Comment by vitek-karas** [comment]
Sorry - I don't understand the question. The `Microsoft.NETCore.DotNetHostResolver` package is not referenced from `.deps.json`. Self-contained apps will have the `hostfxr.dll` listed as a native asset, but that's all.

Can I ask what is the scenario? Why do you need to know the version of `hostfxr` in the app?

**Comment by liesauer** [comment]
when we build a self-contained app, it has `Microsoft.NETCore.DotNetHostResolver/x.y.z` under `libraries` section in `.deps.json`, i have tested a couple of different netcore version, and it seems to be reliable for me.
i have a tool which is used to optimize a netcore self-contained app but have a bug, see #5645(we have discussed before), since this bug cannot be fixed in a short time, i need to build a patched `hostfxr`, it need to match and download the correct version of patched `hostfxr` and replace the original one when use my tool.

**Comment by vitek-karas** [comment]
The record in the `libraries` section will only be there for 2.* apps. 3.0 apps won't have it. Maybe a better way to do this would be to look at the `hostfxr.dll` itself and check its file version (build number).
