### ISSUE TITLE
Getting native binaries and executables entitled

### ISSUE THREAD

**Issue by jcagme** [dotnet/core-setup#7698]
As per the "Getting .NET Core ready for Mac OS Catalina" email we need to add a flag and entitlements to native binaries and executables to get them ready for notarization. 

The steps needed are:

1.	Add a plist which sets CSFlags to 65536. This is used to preserve the codesign flag “-o runtime” when codesign is called on it. We’d need to do “ld -sectcreate _TEXT __info_plist  plist_name.plist”. [This](https://microsoft.visualstudio.com/Edge/_git/chromium.src/pullrequest/3526425?_a=files) is what the Edge team did.
2.	Add entitlements. “codesign –entitlements <entitlements>  <asset>”. Here we need two things:
a.	Define what entitlements are needed. [This](https://developer.apple.com/documentation/bundleresources/entitlements) enumerates all the supported options. From what I saw I think we need something like: (to be verified by the product teams)
```xml
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
```
b.	Determine what binaries need to be entitled

ETA for this work is November when we release 3.1

fyi: @dagood @vitek-karas

**Comment by leecow** [comment]
@jeffschwMSFT / @markwilkie - based on our Tuesday discussion I understood that we do not need to worry about entitlements on our side, rather, this will be the responsibility of the dev if they want _their_ application to the 'proper' on Catalina. This is a separate issue from final hardening work which will be done for 3.1. Are both of these statements correct?

**Comment by jeffschwMSFT** [comment]
@leecow that is our current understanding.  We are looking to fully validate once we have signed packages, but experimentally and through discussions this is our current thinking.

**Comment by wjk** [comment]
Some things to keep in mind:

* If Hardened Runtime is enabled, you'll run into the problem described in https://github.com/mono/monodevelop/pull/8396 (scroll down until you see my review and the replies thereto).
* I do agree that ensuring notarization correctness should be the responsibility of the downstream dev using .NET Core, unless it hampers use of the `dotnet` tool during development, as installed from an installer package (which it probably will, as Apple will refuse to notarize installer packages containing binaries that don't have Hardened Runtime enabled).
* Also note that we can't sign the apphost at all, entitlements or no entitlements, as then when the build process stamps the file with the name of the DLL it launches, it will break the code signature and the file will no longer be usable. (I don't think this can be worked around by resigning the file afterwards, either.)

**Comment by jeffschwMSFT** [comment]
Thanks @wjk 

> unless it hampers use of the dotnet tool during development, as installed from an installer package

We do not anticipate any impact of using dotnet during development as it is not part of a bundle and hardened runtime checks are not in effect.  In what scenario do you anticipate an issue (note that we anticipate having all our native binaries signed and marked as hardened)?

> Also note that we can't sign the apphost at all

We (Microsoft) cannot sign for the reason you noted, but our customers can.  The intention is to document the necessary entitlements (and exceptions) needed to bundle .NET Core.

> If Hardened Runtime is enabled, you'll run into the problem described in mono/monodevelop#8396 (scroll down until you see my review and the replies thereto).

This is interesting, in reading the rules about dynamic loading we seem to be within the boundaries of what is allowed, but we will need to explore this further to ensure there are no additional issues.

**Comment by wjk** [comment]
@jeffschwMSFT I once tried to notarize an installer package containing a signed binary to be installed under `/usr/local` without having hardened runtime enabled on that binary, and the notarization service kicked it back with an error stating as such. Apart from that, everything else LGTM. Thanks!

**Comment by dagood** [comment]
@leecow, can you double check when this is required and find the right milestone/ship date?

**Comment by jeffschwMSFT** [comment]
We can close this issue.  We have the capability to add entitlements to the necessary binaries.  We are working through the other blocking issues for notarization.
