### ISSUE TITLE
[Nethost/Hostfxr] Hosting: `load_assembly_and_get_function_pointer` fails if native process runs Windows compatibility mode.

### ISSUE THREAD

**Issue by Sewer56** [dotnet/core-setup#7872]
## Steps to reproduce

- Clone the following repository: https://github.com/Reloaded-Project/Reloaded.Core.Bootstrap
- Build the project with Visual Studio 2019. 
- Enable compatibility mode for the output binary.
![image](https://user-images.githubusercontent.com/6697380/63812210-93a9e700-c921-11e9-9bf7-5a466af2972d.png)

If you would like to reproduce this in a more "real software scenario", feel free to try this with [Reloaded II](https://github.com/Reloaded-Project/Reloaded-II) (universal "Mod Loader" allowing arbitrary managed code injection in native processes), however for this one this shouldn't be necessary.

## Expected Behaviour
Calling `load_assembly_and_get_function_pointer` returns 0 and delegate address is filled.
![image](https://i.imgur.com/I3Ge9Iw.png)

## Actual Behaviour
Calling `load_assembly_and_get_function_pointer` returns 0x80070057 and delegate address is null.

## Environment data
```
Windows Version: Windows 10 1903 (Build 18362.327)
.NET Core Build: 3.0.100-preview8-013656
```

**Comment by elinor-fung** [comment]
The failure is in trying to add to the dictionary of assembly paths to ALCs. `ArgumentException` is being thrown based on the result of a call to `LCMapStringEx` : https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Globalization/CompareInfo.Windows.cs#L127-L135

Call stack:
```
>System.Private.CoreLib.dll!System.Globalization.CompareInfo.GetHashCodeOfStringCore(System.ReadOnlySpan<char> source, System.Globalization.CompareOptions options)
 System.Private.CoreLib.dll!System.Globalization.CompareInfo.GetHashCodeOfString(string source, System.Globalization.CompareOptions options)
 System.Private.CoreLib.dll!System.CultureAwareComparer.GetHashCode(string obj)
 System.Private.CoreLib.dll!System.Collections.Generic.Dictionary<string, Internal.Runtime.InteropServices.IsolatedComponentLoadContext>.TryInsert(string key, Internal.Runtime.InteropServices.IsolatedComponentLoadContext value, System.Collections.Generic.InsertionBehavior behavior)
 System.Private.CoreLib.dll!Internal.Runtime.InteropServices.ComponentActivator.GetIsolatedComponentLoadContext(string assemblyPath)
 System.Private.CoreLib.dll!Internal.Runtime.InteropServices.ComponentActivator.CreateDelegate(string assemblyPath, string typeName, string methodName, string delegateTypeName)
 System.Private.CoreLib.dll!Internal.Runtime.InteropServices.ComponentActivator.LoadAssemblyAndGetFunctionPointer(System.IntPtr assemblyPathNative, System.IntPtr typeNameNative, System.IntPtr methodNameNative, System.IntPtr delegateTypeNative, System.IntPtr reserved, System.IntPtr functionHandle)
 [Native to Managed Transition]	
 Reloaded.Core.Bootstrap.Example.exe!CoreCLR::load_assembly_and_get_function_pointer(const wchar_t * assembly_path, const wchar_t * type_name, const wchar_t * method_name, const wchar_t * delegate_type_name, void * reserved, void * * delegate)
 Reloaded.Core.Bootstrap.Example.exe!main(int argc, char * * argv)
 Reloaded.Core.Bootstrap.Example.exe!invoke_main()
 Reloaded.Core.Bootstrap.Example.exe!__scrt_common_main_seh()
 Reloaded.Core.Bootstrap.Example.exe!__scrt_common_main()
 Reloaded.Core.Bootstrap.Example.exe!mainCRTStartup()
 kernel32.dll!BaseThreadInitThunk()
 ntdll.dll!RtlUserThreadStart()

```

From this, I suspect this may be an issue with coreclr in general (or at least System.Globalization) - i.e. any host running in compatibility mode (apphost, dotnet) would have problems.

**Comment by vitek-karas** [comment]
Note: this also happens if the compatibility mode is set to Windows 8 (not that it matters much).
