### ISSUE TITLE
Enable CI support for Linux Arm32

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/core-setup#790]
CC @hqueue @kouvel @wtgodbe

**Comment by hqueue** [comment]
I think CI for Linux Arm32 will be based on cross build as in CoreCLR, right?

**Comment by gkhanna79** [comment]
@hqueue Correct. CI build is just like a developer build, but happens automatically for PRs.

**Comment by gkhanna79** [comment]
@hqueue  Since you brought up Arm32 CI support for CoreCLR, can you look into bringin this up as well? It will also help the Tizen armel build that you have been bringing up post the filing of this issue.

**Comment by hqueue** [comment]
@gkhanna79 Sorry for late reply. I almost missed this issue. I will take a look at this. It seems that core-setup has somewhat difference structure than CoreCLR. Please let me know where I can start, inclduing docuement, CI scripts and etc.

**Comment by gkhanna79** [comment]
@hqueue The CI script is the same (netci.groovy) though its contents would be different. CoreCLR's arm32 CI support is implemented in https://github.com/dotnet/coreclr/commits/master/tests/scripts/arm32_ci_script.sh and was enabled by @prajwal-aithal.

This should be a good starting point. CoreCLR CI integration is done at https://github.com/dotnet/coreclr/blob/master/netci.groovy#L2132. 

Let me know if there are other questions I can help answer.

**Comment by hqueue** [comment]
@gkhanna79 Oh, I think I misunderstood this task somewhat. At first, I thought this task is about arm32 CI for Core-Setup. You are talking about arm (hardfp) CI for CoreCLR, right ?

**Comment by gkhanna79** [comment]
> I thought this task is about arm32 CI for Core-Setup

@hqueue Yes, it is :) You had asked for pointers on how to go about doing it, so I pointed you to how it was enabled for CoreCLR.

**Comment by hqueue** [comment]
@gkhanna79 Please ignore my last comment above :) I find out that there is netci.groovy here and I will take a look into it. Sorry for any confusion I made.

**Comment by hqueue** [comment]
@gkhanna79 Are we using same CI machine for Core-Setup and CoreCLR ? We need ARM Emulator installed in CI machine to enable arm32 CI and I think "configuring CI host environment" is out-of-scope of netci.groovy.

**Comment by gkhanna79** [comment]
> Are we using same CI machine for Core-Setup and CoreCLR

I believe this is true but I will let @mmitche confirm as well.

> I think we have better to bring up arm32 CI for Core-Setup, CoreCLR, CoreFX altogether with more well-structured one

I am fine with this approach assuming it is not too far out since the goal is to ensure Core-Setup PRs do not break Arm32 - when do you think this will be done?

**Comment by hqueue** [comment]
> When do you think this will be done? I am fine with this approach assuming it is not too far out since the goal is to ensure Core-Setup PRs do not break Arm32

@gkhanna79 We are planning to start working on it from next Wednesday and will work on it as a top priority for a while. It may also include chaning configuration of CI host itself and we may need your supoort for configuring CI host machine too.

In short, we will do it ASAP from next Wednesday and we hope it be done a few weeks but we don't know how it will take exactly yet depending on scope we are going to refactor.

**Comment by gkhanna79** [comment]
@hqueue Your plan sounds good to me. Definitely let me know if you need any help. Is there an existing issue to track bringing up CI for Arm32 for CoreFX that we can add to the corresponding line-item at https://github.com/dotnet/core-setup/issues/725?

**Comment by hqueue** [comment]
@gkhanna79 I see. There are existing old issues but we will make new issues about refactoring and bring up arm32 CI  for CoreCLR and CoreFX next week, because old issues are not talking about refactoring. I will add them when ready. Thanks.

**Comment by hqueue** [comment]
@gkhanna79 As I've already described at https://github.com/dotnet/core-setup/issues/725#issuecomment-275324269, we have to use recent version of llvm for ARM release.

In short, we have to upgrade llvm to recent version in host machines used for CI and pipeline build for ARM release, since llvm has bug related to TLS for ARM when using `-O3` optimization.

Nextweek, we will test clang-3.8 and above and decide which verion might be suitable.
However even clang-3.8 has bug and we use patched clang-3.8 for ARM build now.
See https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md#how-to-enable--o3-optimization-level-for-armlinux

What do you think of this ? I think we all have to discuss and decide which version of llvm (clang) we are going to use in CI and pipile build.

BTW does CI and pipeline build system use same environment ? This might be another issue and should be considered. And I'm out-of-office until next Monday, because of lunar new year's day here :)

Happy new year again!

**Comment by qmfrederik** [comment]
@hqueue FYI, we found out that building .NET Core for aarch64 (not arm32) using clang3.8 doesn't always work (see #8927 for the full discussion); clang3.9 did work.

**Comment by gkhanna79** [comment]
@hqueue For Arm32, at minimum, we need to be able to produce .NET Core SharedFX (out of the core-setup repo) that can be used by folks. To achieve this, for the time being, can we switch Arm32 builds across CoreCLR/CoreFX/Core-setup repos to use -O1 flag?  Based upon the description at https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md#additional-optimization-levels-for-armlinux--oz-and--ofast, -O3 seems to be an optimization over -O1 but correctness-wise, -O1 should still work. This approach will produce a consumable Arm32 build.

If the above sounds reasonable to you, I would suggest that you make PRs to make this switch so that everything continues to work with the current toolset for cross build (clang 3.6) that is provisioned in CI and pipeline build. Once you have identified the appropriate version of clang that supports -O3 for Arm, we can then look into updating it across the board (including the Docker images that perform the Arm32 builds in pipeline build infrastructure).

In general, for eventual shipping, we should be using an officially supported toolset rather than building one on our own.

As an aside, CoreCLR repo specifies clang 3.6 for cross builds (https://github.com/dotnet/coreclr/blob/master/build.sh#L747) but CoreFX does not (see https://github.com/dotnet/corefx/blob/master/src/Native/build-native.sh). I have filed https://github.com/dotnet/corefx/issues/15511 and assigned it to you.

**Comment by hqueue** [comment]
> FYI, we found out that building .NET Core for aarch64 (not arm32) using clang3.8 doesn't always work (see dotnet/coreclr#8927 for the full discussion); clang3.9 did work.

@qmfrederik Thank you for sharing the thread :) That thread also gave me a lot information regarding clang 3.8 and 3.9.

**Comment by hqueue** [comment]
CI support for core-setup will be done along with CoreCLR (https://github.com/dotnet/coreclr/issues/9273).

**Comment by hqueue** [comment]
@gkhanna79 For corefx and corefx, we are almost done for arm32 cross-building in docker by now. (dotnet/corefx#15900 (merged), dotnet/coreclr#9445 (not merged yet))
Therefree I think it's time to discuss on enabling auto-PR test for coreclr and corefx.
Can we start discussion here ? or in the new issue ?

**Comment by hqueue** [comment]
@gkhanna79 @jyoungyun Let' discuss about "default triggers" and "on-demand triggers" for arm32 in core-setup, coreclr and corefx.
Following is a draft plan. For Core-Setup, I think you have similar plan in mind. What do you think of it ?

- Core-Setup
  **default triggers**  
  Ubuntu arm Release
  Ubuntu16.04 arm Release
  Tizen armel Release

- CoreCLR & CoreFX
  **default triggers**
    Ubuntu arm Release
    Tizen armel Release

  **on-demand triggers**
    Ubuntu arm Debug  
    Ubuntu16.04 arm Release
    Ubuntu16.04 arm Debug
    Tizen armel Debug

**Comment by gkhanna79** [comment]
@hqueue Overall this looks fine. Any reason 16.04 is excluded for CoreCLR and CoreFX from the default configuration?

CC @weshaggard

**Comment by hqueue** [comment]
@gkhanna79  There is no reason excluding 16.04 at all, just want to minimize the CI legs.
If there is room, we want to add CI for Debug instead of another Release.
Because there is little code difference between 14.04 and 16.04 Release build, but there is a lot of code difference between Release and Debug, also there is difference btw  arm and armel.

Therefore how about following legs for coreclr and corfx ?


- CoreCLR & CoreFX
  **default triggers**
  Ubuntu arm Release
  Tizen armel Release
  Ubuntu arm Debug
  Tizen armel Debug
    **on-demand triggers**
    Ubuntu16.04 arm Release
    Ubuntu16.04 arm Debug

**Comment by gkhanna79** [comment]
@hqueue what if you moved U16.04 Debug to default and moved Ubuntu Arm Debug to on-demand and keep everything else the same?

**Comment by hqueue** [comment]
@gkhanna79 That sounds better :)

**Comment by gkhanna79** [comment]
Excellent!

**Comment by hqueue** [comment]
Except Tizen armel CI for core-setup,  other ARM32 CI has been enabled as default.

Tizen armel CI will be enabled after pipeline build for Tizen armel is available.

**Comment by gkhanna79** [comment]
@hqueue When do you expect to add Tizen Armel leg to CI?

**Comment by hqueue** [comment]
> @hqueue When do you expect to add Tizen Armel leg to CI?

@jyoungyun Can you estimate when we can enable Tizen armel CI as in #17541 ?

**Comment by jyoungyun** [comment]
@gkhanna79 @hqueue I will post a PR for enabling Tizen armel CI at least unil May 14. I will ping again. :)

**Comment by gkhanna79** [comment]
Sounds good @jyoungyun - thank you!

**Comment by jyoungyun** [comment]
@gkhanna79 I wanna enable Tizen armel CI job in master branch. But you seems to be changing the core-setup build structure. Currently, the Ubuntu arm release build is being built for portable linux without using arm32_ci_script.sh. Is it your inteded? After merged your PR #2350, I will update arm32_ci_script.sh for building Tizen CI.

**Comment by jyoungyun** [comment]
@ellismg When I use /p:OverridePackageSource option, build is failed with the following errors.

```
Running: /opt/code/Tools/msbuild.sh /nologo /verbosity:minimal /clp:Summary /maxcpucount /l:BinClashLogger,Tools/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log /p:OSGroup=Linux /p:Architecture=x64 /p:CrossBuild=true /p:DistroRid=tizen.4.0.0-armel /p:TargetArchitecture=armel /p:ConfigurationGroup=Release  /flp:v=normal  build.proj /p:SkipTests=true /p:DisableCrossgen=true /p:OverridePackageSource=https://tizen.myget.org/F/dotnet-core/api/v3/index.json
  Restoring all packages...
/opt/code/Tools/dotnetclisdk/sdk/2.0.0-preview1-005899/NuGet.targets(97,5): error : Failed to retrieve information about 'System.AppContext' from remote source '/opt/code/src/managed/Microsoft.DotNet.PlatformAbstractions/https:/tizen.myget.org/F/dotnet-core/api/v3/index.json'. [/opt/code/src/managed/Microsoft.DotNet.PlatformAbstractions/Microsoft.DotNet.PlatformAbstractions.csproj] [/opt/code/build.proj]
/opt/code/build.proj(64,5): error MSB3073: The command "/opt/code/Tools/dotnetclisdk/dotnet restore --packages "/opt/code/packages" --source https:/tizen.myget.org/F/dotnet-core/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://dotnet.myget.org/F/cli-deps/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://www.myget.org/F/nugetbuild/api/v3/index.json --source https://api.nuget.org/v3/index.json --source https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json "/opt/code/src/managed/Microsoft.DotNet.PlatformAbstractions/Microsoft.DotNet.PlatformAbstractions.csproj" " exited with code 1.
```

Could you help me to resolve this issue?

**Comment by gkhanna79** [comment]
@jyoungyun Ubuntu Arm leg (https://ci.dot.net/job/dotnet_core-setup/job/master/job/release_ubuntu_arm_prtest/49/console) is really Linux Armhf leg. 

For ArmEl, you should add a Tizen Armel leg (similar to what we have in coreCLR - like https://ci.dot.net/job/dotnet_coreclr/job/master/job/armel_cross_debug_tizen_prtest/2289/consoleFull).

**Comment by gkhanna79** [comment]
@ericstj @weshaggard Do you know why restore would fail for @jyoungyun above?

**Comment by ellismg** [comment]
In the error message there is only one slash after https:.  In dir.props we do this goofy %2F thing to prevent msbuild from normalizing slash slash into slash.  When passing a http source to this property you may need to do the same normalization?

**Comment by jyoungyun** [comment]
Thanks @ellismg. The issue was resolved :) I will add Tizen Armel leg soon.

**Comment by gkhanna79** [comment]
@jyoungyun Can we close this issue now that you have enabled the Tizen Armel CI support?

**Comment by jyoungyun** [comment]
@gkhanna79 Sure! Thank you for your effort and time :)
