### ISSUE TITLE
Symbol zip/tarball missing 'dotnet' host symbols

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#7954]
The symbol archive zip/tarball (`dotnet-runtime-symbols-3.0.0-...-win-x64.zip`) doesn't have symbols for `dotnet`/`dotnet.exe`, like `dotnet.pdb`, `dotnet.dbg`, `dotnet.dwarf`. It looks like it has been this way at least since 2.1.

The binary archive (`dotnet-runtime-3.0.0-...-win-x64.zip`) contains the `dotnet` host, so it seems reasonable to expect its symbols to be in the symbol archive.

Other hosts (`apphost`, `comhost`, ...) don't show up in the symbol archive either, but because they don't show up in the binary archive, this seems at least consistent and fine. This issue only tracks `dotnet` host symbols being missing.

---

This doesn't impact symbol availability for Microsoft builds because the symbols are published to symbol servers based on `Microsoft.NETCore.App.Host.<rid>.3.0.0-...symbols.nupkg`.

@omajid have you noticed this with source-builds, is it a problem there?

**Comment by omajid** [comment]
AFAIK, for consuming source-build on Linux we want split native (unmanaged) symbols. When I try and build for Fedora copr repos, I make sure nothing gets stripped and all executibles and shared object contain the debug info. The packaging tooling (rpmbuild, for me) later strips all the debuginfo and makes a separate `-debuginfo` package with it.

[This patch](https://pagure.io/dotnet-sig/dotnet-3-0/blob/master/f/core-setup-do-not-strip.patch) takes care of things on core-setup's side, I think.

**Comment by dagood** [comment]
Ah! I remember that now. Didn't put it together with why certain symbols being in that tarball matters. Seems like it would be neat for it to be possible to embed PDB info in the managed DLLs and strip it out during packaging as well, sometime in the future... 😄

In any case, closing because there's no known reason to fix this particular missing symbols file.

**Comment by dagood** [comment]
By the way, the patch shouldn't be necessary now--the `StripSymbols` MSBuild property has to be set to `true` in the build command to pass `--stripsymbols` to the native build script to turn on `STRIP_SYMBOLS` in CMake. I actually recently ran into a little surprise that the stripped symbol files were "missing" in a dev build until I remembered this.
