### ISSUE TITLE
Remove package version assumptions in nonshipping nupkg dependencies

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#8112]
Right now, Core-Setup builds nonshipping packages stable even though Arcade wants to build them unstable. See https://github.com/dotnet/arcade/pull/3909.

If I try to force a Core-Setup build with the shipping packages stabilized and nonshipping packages unstable, the nonshipping packages end up with invalid dependencies.

For example, Microsoft.NETCore.App.Internal `5.0.0-dev` ends up depending on `Microsoft.NETCore.DotNetHostPolicy` `5.0.0-dev`, but `DotNetHostPolicy` is actually shipping and `5.0.0`. There are also errors during test preparation where it gets the version of the wrong (?) package. There might be test errors masked by that earlier failure due to the bad dependencies.

To fix this, we probably need to iterate on changes that remove assumptions about versions and get them directly from the projects responsible for building the specific nupkgs. This would improve Core-Setup support of Arcade's principles.

**Comment by dagood** [comment]
This is required. During a stable build, the nonshipping packages are still published to a static feed: only the shipping ones are published to the generated-per-build isolated feed. This means that nonshipping packages must not be stable.

**Comment by dagood** [comment]
The versioning assumptions seem to go all the way into the SDK targets. (Not criticizing the assumptions... this is an exceedingly strange scenario that is completely unlike how the SDK is actually used.)

For example:
1. I got restore errors that it couldn't find the runtime pack with the prerelease version.
2. I changed `RuntimeFrameworkVersion` to use the runtime pack's stable version to fix that.
3. Now it complains that it can't find the legacy `runtime.<rid>.Microsoft.NETCore.App` package because it doesn't have a stable version.
4. To fix this I think I would have to find some way to conditionally change the logic used to resolve framework references.
5. ...? The above only scratches the surface with restoring the test asset projects... I'm sure there would also be failures within the tests when doing publish, etc.

Instead of going further down that road, I have a pre-test workaround in mind: I'm going to create a copy of the nupkgs with the prerelease parts of the versions chopped off, only for use within a Core-Setup build to run the tests. It won't be published or uploaded anywhere because the stable version can't be handled.

@vitek-karas, @mmitche, @MichaelSimons, does this sound objectionable?

---

The goal is to delete the legacy packages altogether and make shared frameworks truly testable. This might need https://github.com/dotnet/core-setup/issues/4809, I'm not currently familiar enough with that thread to know for sure.

**Comment by mmitche** [comment]
@dagood That sounds fine with me I think, though I'm not really seeing what you're getting at.

Are we at risk for a GA branded build by Sunday? night?

**Comment by dagood** [comment]
> Are we at risk for a GA branded build by Sunday? night?

Not with the new workaround, I expect I'll have that working by EOD today.

**Comment by dagood** [comment]
Done: ported to 3.0 by https://github.com/dotnet/core-setup/pull/8188.
