### ISSUE TITLE
Core-setup blob publishing location

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/core-setup#8254]
Looks like Core-setup is publishing blobs to this location of the private blob storage:

```dotnet/assets/core-setup/Runtime/*```

but Core-SDK is looking for the blobs in this location:

```dotnet/Runtime/*```

I don't think there was a change in Core-SDK recently around this. So I guess it's something that Core-setup is doing differently.

@dagood @livarcocc @mmitche @riarenas @markwilkie

**Comment by dagood** [comment]
Done with https://github.com/dotnet/core-setup/pull/8279 and https://github.com/dotnet/core-setup/pull/8286.
