### ISSUE TITLE
The tag v2.1.13-dependencies is missing

### ISSUE THREAD

**Issue by assyadh** [dotnet/core-setup#8275]
## Steps to reproduce
Go to https://github.com/dotnet/core-setup/tags

## Expected  behavior
The tag v2.1.13-dependencies should be present, as it was for 2.1.12:
https://github.com/dotnet/core-setup/releases/tag/v2.1.12-dependencies

## Actual behavior

The tag is not present.

## Environment data

n/a

**Comment by Anipik** [comment]
The build is failing on this PR  https://github.com/dotnet/core-setup/pull/7517 which is blocking the dependency tag work. I was little occupied with GA release but i can take a look later today.
feel free to go ahead and fix the failure. :)

**Comment by assyadh** [comment]
Hi,

Any ETA for this? I need to build this version ASAP as 2.1.13 fixes high severity issues.

Thanks.

**Comment by Anipik** [comment]
Should be resolved by EOD or tomorrow

**Comment by assyadh** [comment]
Thanks!

**Comment by Anipik** [comment]
the dependency tag has been created for 2.1.13 https://github.com/dotnet/core-setup/releases/tag/v2.1.13-dependencies

**Comment by assyadh** [comment]
Thanks
