### ISSUE TITLE
Installers and checksums should publish to suffixed locations

### ISSUE THREAD

**Issue by mmitche** [dotnet/core-setup#8278]
Right now the installers and checksums for 3.x and 5 branches are publishing to stable locations in a stable build. This means a subsequent build will need to overwrite. Instead,the subfolder under which the stable assets should be located should always be suffixed. For example:

Instead of:

dotnet/Runtime/3.0.1/installer-3.0.1.exe

Do:

dotnet/Runtime/3.0.1-servicing-1235/installer-3.0.1.exe

**Comment by dagood** [comment]
Duplicate of https://github.com/dotnet/core-setup/issues/8244

**Comment by mmitche** [comment]
Gracias.
