### ISSUE TITLE
dotnet-dev-1.1.14 package fails to install on Ubuntu

### ISSUE THREAD

**Issue by kimbaudi** [dotnet/core-setup#8298]
## Steps to reproduce

Open terminal and install `dotnet-dev-1.1.14` package.

```shell
sudo apt update
sudo apt install dotnet-dev-1.1.14
```

**Note:** `dotnet-dev-1.1.11` and `dotnet-dev-1.1.13` packages install fine without problems. But `dotnet-dev-1.1.14` package fails to install.

## Expected  behavior

The `dotnet-dev-1.1.14` package should install fine.

## Actual behavior

The `dotnet-dev-1.1.14` package fails to install.

Here is the output:

```shell
paul@paul-VirtualBox:~$ sudo apt install dotnet-dev-1.1.14
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-dev-1.1.14 : Depends: dotnet-sharedframework-microsoft.netcore.app-1.1.13 but it is not going to be installed
                     Depends: dotnet-sharedframework-microsoft.netcore.app-1.0.16 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

````

## Environment data

Ubuntu 18.04.3 LTS

**Comment by dagood** [comment]
.NET Core 1.0 and 1.1 are end-of-life, you should use one of the supported versions instead: https://dotnet.microsoft.com/download.

This package didn't support Ubuntu 18.04, it looks like only 14.04 and 16.04 were supported at that point in time.

/cc @leecow

---

For what it's worth, the first step to diagnose this type of issue is to drill into the dependencies to see why they aren't installable:

```
$ apt install dotnet-sharedframework-microsoft.netcore.app-1.1.13
...
The following packages have unmet dependencies:
 dotnet-sharedframework-microsoft.netcore.app-1.1.13 : Depends: libicu52 (>= 52~m1-1~) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

It looks like 18.04 has `libicu60` instead, based on `apt search libicu`.
