### ISSUE TITLE
WinForms .net core 3 app fails to find runtime for Desktop Apps

### ISSUE THREAD

**Issue by mscrivo** [dotnet/core-setup#8363]
## Steps to reproduce
Create a WinForms app that targets netcoreapp3.0 and build it. 
Run it on a machine that only has the .net core 3 Desktop runtime installed.

## Expected  behavior
The app should run with the desktop runtimes installed.

## Actual behavior
Observe that the app does not load, and you see this in the event viewer:

> A .NET Core application failed.
> Application: program.exe
> Path: C:\Program Files (x86)\Program\program.exe
> Message: It was not possible to find any compatible framework version
> The specified framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
>   - No frameworks were found.
> 
> You can resolve the problem by installing the specified framework and/or SDK.
>
> The .NET Core frameworks can be found at:
>   - https://aka.ms/dotnet-download)

## Environment data

It works fine if you install the full SDK.

**Comment by dagood** [comment]
Did you install the .NET Core Runtime too? This banner on https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-3.0.0-windows-x64-desktop-runtime-installer is meant to let you know:

![image](https://user-images.githubusercontent.com/12819531/65821256-cf71ee00-e1f8-11e9-9ad7-80498daa72f3.png)

We don't have an installer for 3.0 that bundles both together (or both x86 and x64 together), more info about that at https://github.com/dotnet/core-setup/issues/7763.

**Comment by mscrivo** [comment]
I see, thank you.
