### ISSUE TITLE
[Need Help]build core-setup under windows

### ISSUE THREAD

**Issue by liesauer** [dotnet/core-setup#8398]
in this document, what do u mean tools and sdks? can u just tell us which ones need to be enabled, because i tried enabling some related. but when i build core-setup, it said can not find the `Microsoft.DotNet.Arcade.Sdk` package.
https://github.com/dotnet/core-setup/blob/c8a7fa836b9a15e1a5a4398eb916666bfa9aa772/Documentation/building/windows-instructions.md#L17-L20

```
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。

    生成启动时间为 2019/10/1 23:12:39。
    正在还原 C:\Users\LiesAuer\AppData\Local\Temp\a967d406-53be-4b0e-88d8-66b438dcaedd 的包...
      GET https://api.nuget.org/v3-flatcontainer/microsoft.dotnet.arcade.sdk/index.json
      NotFound https://api.nuget.org/v3-flatcontainer/microsoft.dotnet.arcade.sdk/index.json 290 毫秒
    E:\Projects\core-setup\Directory.Build.props(11,3): error : 找不到包 Microsoft.DotNet.Arcade.Sdk。源 Microsoft Visual Studio Offline Packages, nuget.org 中不存在 具有此 ID 的包
    E:\Projects\core-setup\Directory.Build.props(11,3): error : C:\Program Files\dotnet\sdk\2.1.504\Sdks\Microsoft.DotNet.Arcade.Sdk\Sdk not found. Check that a recent enough .NET Core SDK is installed and/or increase the version specified in global.json.
    节点 1 上的项目“E:\Projects\core-setup\artifacts\obj\.Release\corehost\CMakeFiles\3.15.3\VCTargetsPath.vcxproj”(默认目标)。
    E:\Projects\core-setup\Directory.Build.props(11,31): error MSB4236: 找不到指定的 SDK“Microsoft.DotNet.Arcade.Sdk”。 [E:\Projects\core-setup\artifacts\obj\.Release\corehost\CMakeFiles\3.15.3\VCTargetsPath.vcxproj]
    已完成生成项目“E:\Projects\core-setup\artifacts\obj\.Release\corehost\CMakeFiles\3.15.3\VCTargetsPath.vcxproj”(默认目标)的操作 - 失败。

    生成失败。

      E:\Projects\core-setup\Directory.Build.props(11,3): error : 找不到包 Microsoft.DotNet.Arcade.Sdk。源 Microsoft Visual Studio Offline Packages, nuget.org 中不存 在具有此 ID 的包
      E:\Projects\core-setup\Directory.Build.props(11,3): error : C:\Program Files\dotnet\sdk\2.1.504\Sdks\Microsoft.DotNet.Arcade.Sdk\Sdk not found. Check that a recent enough .NET Core SDK is installed and/or increase the version specified in global.json.


    “E:\Projects\core-setup\artifacts\obj\.Release\corehost\CMakeFiles\3.15.3\VCTargetsPath.vcxproj”(默认目标) (1) ->
      E:\Projects\core-setup\Directory.Build.props(11,31): error MSB4236: 找不到指定的 SDK“Microsoft.DotNet.Arcade.Sdk”。 [E:\Projects\core-setup\artifacts\obj\.Release\corehost\CMakeFiles\3.15.3\VCTargetsPath.vcxproj]
```

**Comment by vitek-karas** [comment]
I don't think this has anything to do with the machine setup. Do you have a recent copy of the repo? I can't see that particular feed listed anywhere. Also if that doesn't help , please clean your repo (`git clean -xdf`) and try building again.
I think the important error is this line:
`NotFound https://api.nuget.org/v3-flatcontainer/microsoft.dotnet.arcade.sdk/index.json 290`

The rest is just a fallback from that one.

**Comment by liesauer** [comment]
it is totally a new clone. so am i missing some sdks? i installed those tools and sdks in vs installer already2019年10月2日 20:24，Vitek Karas <notifications@github.com>写道：I don't think this has anything to do with the machine setup. Do you have a recent copy of the repo? I can't see that particular feed listed anywhere. Also if that doesn't help , please clean your repo (git clean -xdf) and try building again.
I think the important error is this line:
NotFound https://api.nuget.org/v3-flatcontainer/microsoft.dotnet.arcade.sdk/index.json 290
The rest is just a fallback from that one.

**Comment by dagood** [comment]
Are you trying to build in VS from a fresh repo? That has issues, you have to build with the command line first to get things set up reliably. I think some of this is tracked at https://github.com/dotnet/arcade/issues/2377. `Microsoft.DotNet.Arcade.Sdk` comes from that repo, it's "just" a nuget package.

**Comment by liesauer** [comment]
i am trying to build using build.cmd under src/corehost. and my point is when i finish all the stuff in the vs installer, it should be ready to go. the only thing i want to build is corehost, no arcade. this one should be installed in the vs installer.



 
From: Davis Goodin
Date: 2019-10-02 22:52
To: dotnet/core-setup
CC: L!εsAμεr; Author
Subject: Re: [dotnet/core-setup] [Need Help]build core-setup under windows (#8398)
Are you trying to build in VS from a fresh repo? That has issues, you have to build with the command line first to get things set up reliably. I think some of this is tracked at dotnet/arcade#2377. Microsoft.DotNet.Arcade.Sdk comes from that repo, it's "just" a nuget package.

**Comment by dagood** [comment]
Interesting. @vitek-karas, is that a reasonable scenario? I'm not familiar enough with this scripts to understand why it ends up evaluating e.g. `core-setup\Directory.Build.props` which brings in the Arcade SDK reference.

If Arcade isn't necessary for this part of the build, I'd try adding a `Directory.Build.props`/`Directory.Build.targets` that isolate the generated (?) project from the rest of the repo, which does require the Arcade SDK. (When evaluating a project, directories are searched upwards for the first matching `Directory.Build.props` and `targets`.) We use this strategy for the test projects, which also exist in the `artifacts` directory.

**Comment by liesauer** [comment]
things just become more interesting. i clone the arcade and try to build it in vs. but failed, and said cannot find arcade sdk! what??? i am trying to build u! and u need yourself to build yourself? lol



 
From: Davis Goodin
Date: 2019-10-02 23:50
To: dotnet/core-setup
CC: L!εsAμεr; Author
Subject: Re: [dotnet/core-setup] [Need Help]build core-setup under windows (#8398)
Interesting. @vitek-karas, is that a reasonable scenario? I'm not familiar enough with this scripts to understand why it ends up evaluating e.g. core-setup\Directory.Build.props which brings in the Arcade SDK reference.
If Arcade isn't necessary for this part of the build, I'd try adding a Directory.Build.props/Directory.Build.targets that isolate the generated (?) project from the rest of the repo, which does require the Arcade SDK. (When evaluating a project, directories are searched upwards for the first matching Directory.Build.props and targets.) We use this strategy for the test projects, which also exist in the artifacts directory.

**Comment by dagood** [comment]
That's the issue I mentioned above, you can't build from VS immediately after cloning. https://github.com/dotnet/arcade/issues/2377.

It's also not uncommon for toolsets to depend on an earlier version of itself to build. For example, Roslyn is written in C#. MSBuild is built with MSBuild projects.

**Comment by vitek-karas** [comment]
Sorry for the confusion, but most our repos have to be built from the root of the repo - at least once. In the case of core-setup repo, the `src/corehost/build.cmd` is really just an implementation detail of the build system and should not be called on its own.
I strongly suggest you build the entire repo at least once, including all the tests (if you need to run any tests), this is done by running:  
`build.cmd -Test`
from the root of the repo.

After that you can build just the corehost parts by running `build.cmd /p:Subset=corehost`
You can get the full list of supported subsets by running `build.cmd /p:Subset=help`

I know this is not a perfect system, but it more or less works. If you plan to use this, please read the comment in the beginning of https://github.com/dotnet/core-setup/blob/master/Subsets.props as there are some combinations which don't do what one would normally expect.

**Comment by liesauer** [comment]
@vitek-karas i try to load the project in vs and said `[System.IO.Path]::GetDirectoryName('')` is invalid and load failed.
```
E:\Projects\core-setup\src\managed\Microsoft.DotNet.PlatformAbstractions\Microsoft.DotNet.PlatformAbstractions.csproj : error  : 无法计算表达式“[System.IO.Path]::GetDirectoryName('')”。路径的形式不合法。  E:\Projects\core-setup\Directory.Build.props

E:\Projects\core-setup\src\managed\Microsoft.Extensions.DependencyModel\Microsoft.Extensions.DependencyModel.csproj : error  : 无法计算表达式“[System.IO.Path]::GetDirectoryName('')”。路径的形式不合法。  E:\Projects\core-setup\Directory.Build.props

E:\Projects\core-setup\src\test\HostActivation.Tests\HostActivation.Tests.csproj : error  : 无法计算表达式“[System.IO.Path]::GetDirectoryName('')”。路径的形式不合法。  E:\Projects\core-setup\Directory.Build.props

E:\Projects\core-setup\src\test\Microsoft.Extensions.DependencyModel.Tests\Microsoft.Extensions.DependencyModel.Tests.csproj : error  : 无法计算表达式“[System.IO.Path]::GetDirectoryName('')”。路径的形式不合法。  E:\Projects\core-setup\Directory.Build.props

E:\Projects\core-setup\src\test\TestUtils\TestUtils.csproj : error  : 无法计算表达式“[System.IO.Path]::GetDirectoryName('')”。路径的形式不合法。  E:\Projects\core-setup\Directory.Build.props

E:\Projects\core-setup\src\managed\Microsoft.NET.HostModel\Microsoft.NET.HostModel.csproj : error  : 无法计算表达式“[System.IO.Path]::GetDirectoryName('')”。路径的形式不合法。  E:\Projects\core-setup\Directory.Build.props

E:\Projects\core-setup\src\test\BundleTests\AppHost.Bundle.Tests\AppHost.Bundle.Tests.csproj : error  : 无法计算表达式“[System.IO.Path]::GetDirectoryName('')”。路径的形式不合法。  E:\Projects\core-setup\Directory.Build.props

E:\Projects\core-setup\src\test\BundleTests\Microsoft.NET.HostModel.Bundle.Tests\Microsoft.NET.HostModel.Bundle.Tests.csproj : error  : 无法计算表达式“[System.IO.Path]::GetDirectoryName('')”。路径的形式不合法。  E:\Projects\core-setup\Directory.Build.props

E:\Projects\core-setup\src\test\BundleTests\Helpers\BundleHelper.csproj : error  : 无法计算表达式“[System.IO.Path]::GetDirectoryName('')”。路径的形式不合法。  E:\Projects\core-setup\Directory.Build.props

E:\Projects\core-setup\src\test\Microsoft.DotNet.CoreSetup.Packaging.Tests\Microsoft.DotNet.CoreSetup.Packaging.Tests.csproj : error  : 无法计算表达式“[System.IO.Path]::GetDirectoryName('')”。路径的形式不合法。  E:\Projects\core-setup\Directory.Build.props
```

and i try to run `build.cmd` from the root and said
```
& : 无法将“E:\Projects\core-setup\eng\common\Build.ps1”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称
的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 3
+ & "E:\Projects\core-setup\eng\common\Build.ps1" -restore -build
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (E:\Projects\cor...ommon\Build.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
the right name should be `build.ps1`, not `Build.ps1`

**Comment by vitek-karas** [comment]
Which project are you trying to load into VS?

To open anything in VS you first need to successfully build from command line (it restores packages and other things). Then you should be able to open the https://github.com/dotnet/core-setup/blob/master/Microsoft.DotNet.CoreSetup.sln from VS and it should load successfully. This solution contains all of the managed code in the repo (both product and tests).

To open the native portion, once you build it (assuming Windows x64 Debug), you should be able to open `<reporoot>/artifacts/obj/win-x64.Debug/corehost/Project.sln`. It contains all of the native code in the repo.

Can you please try to follow the instructions in the [build doc](https://github.com/dotnet/core-setup/blob/master/Documentation/building/windows-instructions.md) and see if it works? I know it builds the entire repo, but currently that is necessary to start with.

As for the `build.ps1` versus `Build.ps1` - on Windows file systems are not case sensitive so it should not matter.

**Comment by liesauer** [comment]
the first thing i have done was reading the doc! can u please just try to build this repo in a clear system? everything just keep reporting errors!



 
From: Vitek Karas
Date: 2019-10-03 20:12
To: dotnet/core-setup
CC: L!εsAμεr; Author
Subject: Re: [dotnet/core-setup] [Need Help]build core-setup under windows (#8398)
Which project are you trying to load into VS?
To open anything in VS you first need to successfully build from command line (it restores packages and other things). Then you should be able to open the https://github.com/dotnet/core-setup/blob/master/Microsoft.DotNet.CoreSetup.sln from VS and it should load successfully. This solution contains all of the managed code in the repo (both product and tests).
To open the native portion, once you build it (assuming Windows x64 Debug), you should be able to open <reporoot>/artifacts/obj/win-x64.Debug/corehost/Project.sln. It contains all of the native code in the repo.
Can you please try to follow the instructions in the build doc and see if it works? I know it builds the entire repo, but currently that is necessary to start with.
As for the build.ps1 versus Build.ps1 - on Windows file systems are not case sensitive so it should not matter.

**Comment by liesauer** [comment]
and i can't get any help from this conversation or any links u mentioned, u think it should work, but the fact is everything doesn't work in a clear system. so i THINK closing this issue is the best choice and stop wasting both ours time.

**Comment by dagood** [comment]
I happen to have a clean Windows VM I test installers on, so I gave it a try. The instructions work fine for me, *however* I also had to make guesses with the Visual Studio Installer choices--this is valid:

> in this document, what do u mean tools and sdks? can u just tell us which ones need to be enabled, because i tried enabling some related.

I enabled all three of the Windows workloads in VS 2019 Community: `.NET desktop development`, `Desktop development with C++`, and `Universal Windows Platform development`, and that let the build succeed. But the instructions didn't tell me to do this, and I couldn't map what's  in the instructions to anything actually in the installer. (Maybe it's different for VS 2017?) I probably installed much more than I really needed to.

@vitek-karas Can you look at updating that?

@liesauer All the errors you've run into seem related to trying to open something in Core-Setup using Visual Studio. If you can try it again with a fresh clone and not opening Visual Studio (only using the Visual Studio Installer to download/install prereqs), maybe we can help better.

**Comment by liesauer** [comment]
@dagood i already enabled those workloads.
![image](https://user-images.githubusercontent.com/8676741/66179313-03d32780-e69b-11e9-84bc-f26dcc13e589.png)

i have tried building the whole repo from the root by running `build.cmd` (and fresh clone of course), i have tried everything i can try, and got `Microsoft.DotNet.Arcade.Sdk` not found every single time.

**Comment by dagood** [comment]
Interesting... thanks for confirming. That is very strange. It should be finding the Arcade SDK in the dotnet-core feed:

https://github.com/dotnet/core-setup/blob/a8af0f3e03b7872099843e92d8803bf324096d39/NuGet.config#L14-L17

Based on this line:

```
E:\Projects\core-setup\Directory.Build.props(11,3): error : 找不到包 Microsoft.DotNet.Arcade.Sdk。源 Microsoft Visual Studio Offline Packages, nuget.org 中不存在 具有此 ID 的包
(Google tells me:)
E:\Projects\core-setup\Directory.Build.props(11,3): error : The package Microsoft.DotNet.Arcade.Sdk was not found. Source Microsoft Visual Studio Offline Packages, a package with this ID does not exist in nuget.org
```

it looks like it's only trying to look at the NuGet Gallery and the VS package cache--the NuGet.config wasn't applied, or is being overridden somehow, maybe? Nothing comes to mind that would cause this.

(The `NotFound https://api.nuget.org/v3-flatcontainer/microsoft.dotnet.arcade.sdk/index.json` is normal and fine. That URL is an API endpoint in the NuGet gallery. The Arcade SDK isn't there, which should be fine because NuGet is supposed to check all the feeds before giving up.)

Maybe you can try building with binlog output enabled, and send us that? It normally contains a lot more diagnostic info. Running `.\build.cmd /bl` will place `msbuild.binlog` in your repo's directory. They're read by http://msbuildlog.com/. (Take a look to make sure it's ok to send--it captures environment variables.)

**Comment by liesauer** [comment]
finally, make the build work!
1. enabling those workloads in vs installer(vs2017 15.9.7 community)
2. copy all the sources from `nuget.config` into vs nuget sources manager setting(the build task should read and parse the `nuget.config`, but it's not)
3. run `build.cmd` form the root(it will fail)
```
E:\Projects\core-setup\artifacts\toolset\restore.proj : error MSB4019: 未找到导入的项目“E:\Projects\core-setup\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19461.7\Sdk\Sdk.props”。请确认 <Import> 声明中的路径正确，且磁盘上存在该文件。
Build failed.
```
4. rename `.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19461.7\sdk` to `Sdk`(but windows should be case-insensitive right?)
5. run `build.cmd` again and fail again. `MSBUILD : error MSB1009: project file doesn't exist.` the original message is `MSBUILD : error MSB1009: 项目文件不存在。` i just translate it.
6. run again. it works miraculously! starting restoring packages.

but in my opinion, `2` `4` `5` shouldn't be happened, right?

**Comment by dagood** [comment]
Hmm, yeah, all the issues there look like case sensitivity. Would you happen to be virtualizing Windows and sharing an `E:\` drive from a different system that does have case sensitivity? Anything like that? Case sensitivity is (at least in cases I'm aware of) a property of the file system rather than the OS.

Also, apparently Win10 recently added a flag to enable case sensitivity on individual directories in NTFS partitions (for WSL2?)--but I think you'd be more likely to know you'd done this if it were what's happening here. (Learned this just now. 😄)

This repo can't do anything about handling case-sensitivity on Windows, AFAIK... I believe that assumption is baked into (the Windows versions of) a bunch of the tools we use, so it'd be a much wider set of changes.

**Comment by dagood** [comment]
Forgot to mention:

> 2. copy all the sources from `nuget.config` into vs nuget sources manager setting(the build task should read and parse the `nuget.config`, but it doesn't)

I believe this one could be case sensitivity because when NuGet searches for a NuGet.config when it thinks the filesystem is insensitive, it only looks for one casing relies on the filesystem to case-insensitively find the `NuGet.config`. https://github.com/NuGet/NuGet.Client/blob/caac28293a4032de8629b39597a179df988a612a/src/NuGet.Core/NuGet.Configuration/Settings/Settings.cs#L26-L37

And that `IsFileSystemCaseInsensitive` utility method is bogus:
https://github.com/NuGet/NuGet.Client/blob/caac28293a4032de8629b39597a179df988a612a/src/NuGet.Core/NuGet.Common/PathUtil/PathUtility.cs#L414

(That's just one example of how fixing this would require tooling changes.)

**Comment by liesauer** [comment]
i am running normal windows10, but updated to 1903 a few weeks ago. i will try agian on my another pc tomorrow, it is 1803.

**Comment by dagood** [comment]
Well, at this point I think you're best off looking for how to disable case sensitivity on that `E:\` drive, since it's clearly what's going on--I don't have any particular tips on how to check and fix it. Or, build the repo on a different drive.

**Comment by vitek-karas** [comment]
Just out of curiousity - can you try on the PC where it fails some operation which would show if the file system is really case sensitive? Maybe something like creating a file `foo.txt` and then trying to open it as `FOO.txt`?

I've never seen a Windows FS which would be case sensitive - so knowing that it can do that... would be valuable.

**Comment by liesauer** [comment]
> Hmm, yeah, all the issues there look like case sensitivity. Would you happen to be virtualizing Windows and sharing an `E:\` drive from a different system that does have case sensitivity? Anything like that? Case sensitivity is (at least in cases I'm aware of) a property of the file system rather than the OS.
> 
> Also, apparently Win10 recently added a flag to enable case sensitivity on individual directories in NTFS partitions (for WSL2?)--but I think you'd be more likely to know you'd done this if it were what's happening here. (Learned this just now. 😄)
> 
> This repo can't do anything about handling case-sensitivity on Windows, AFAIK... I believe that assumption is baked into (the Windows versions of) a bunch of the tools we use, so it'd be a much wider set of changes.

good point. `e:\Projects` is my share projects directory between windows and wsl. so when i have done something with this directory in wsl(may be `git clone` or something?), it make my `e:\Projects` become case sensitive! i clone this repo into both `d:\` and `e:\` and run `build.cmd`, case sensitive problem gone! is this a wsl bug? i have never heard of this.

**Comment by vitek-karas** [comment]
I don't know about the design of WSL, but I know that I tried to share the same clone between Windows and WSL and that didn't work well. If the project is cloned on Windows than the Linux in WSL will have trouble with different line endings. I played with it a little, but in the end it was not worth the hassle. I ended up with separate Windows clone and Linux clone.

**Comment by liesauer** [comment]
i found some articles that related.
[Improved per-directory case sensitivity support in WSL](https://devblogs.microsoft.com/commandline/improved-per-directory-case-sensitivity-support-in-wsl/)
[Per-directory case sensitivity and WSL](https://devblogs.microsoft.com/commandline/per-directory-case-sensitivity-and-wsl/)
but however, the cause has comfirmed. i will open another issue in [microsoft/WSL](https://github.com/microsoft/WSL)

**Comment by dagood** [comment]
Interesting... it's probably a well-intentioned feature, since on the Linux side of things, case-sensitivity is sometimes assumed and you could run into the exact opposite kind of problems there. Unfortunate that it isn't made clear to users when it's happening and what the side effects may be. 😕
