### ISSUE TITLE
$exception {"Could not load file or assembly 'System.EnterpriseServices'} - System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by tehseenshahab** [dotnet/core-setup#8424]
## Steps to reproduce
Upgrading Legacy WinForm Application to Core 3.0 WinForm application. 

## Error
**System.EnterpriseServices** is missing. 
PS: I know its not supported by core 3.0 

## Environment data

Can you suggest what the other way round to make this work. Or is there any **nuget** package available for this?

Thanks

**Comment by jeffschwMSFT** [comment]
@tehseenshahab how are you using enterpriseservices?  In my experience I have seen it most often used as a convenient out of proc COM server.  If that is the case, you can use COM in .NET Core 3.

Here is a sample for how to do COM in .NET Core, we can help discuss out of proc capabilities.

https://github.com/dotnet/samples/tree/master/core/extensions/COMServerDemo

cc @AaronRobinsonMSFT

**Comment by tehseenshahab** [comment]
@jeffschwMSFT, we are using following classes/functions of the enterpriseservices 
ContextUtil.DisableCommit();
ContextUtil.EnableCommit();
ContextUtil.IsInTransaction;
ContextUtil.IsCallerInRole(strRole);
ContextUtil.IsSecurityEnabled;
ContextUtil.SetAbort();
ContextUtil.SetComplete();


Please let me know if there is any alternative available in core 3.0 winform thanks

**Comment by vitek-karas** [comment]
Closing for lack of actionable data. Please reopen this issue if more info is available, or create a new issue (preferably in the dotnet/runtime repo).
