### ISSUE TITLE
"Failed to create CoreCLR, HRESULT: 0x8007001F" while using hostfxr API on Ubuntu 18.04

### ISSUE THREAD

**Issue by GlebChili** [dotnet/core-setup#8438]
Hello!

I'm trying to make use of new hostfxr API and integrate CoreCLR as "scripting" backend into Garry's Mod game. Garry's Mod loads shared library which in turn loads hostfxr, calls its API, and returns pointer to call managed function to Garry's Mod. Source code: https://github.com/GlebChili/GmodDotNet (devel_netcore_2 branch). Windows builds work just as expected, but on Ubuntu 18.04 hostfxr sends an error message "Failed to create CoreCLR, HRESULT: 0x8007001F" on `hostfxr_get_runtime_delegate` call.

I understand that my issue is connected with third party programm and can be inconvenient for dev team to investigate, but it would nice if somebody will give me an advice on what potentially can cause such behaviour or how can I get additional data for debuging.

Thanks!

## Steps to reproduce
1) Download and install Garry's Mod Dedicated Server (free) x86_64 beta branch

2) Install GmodNET as described here: https://github.com/GlebChili/GmodDotNet

3) Run Garry's Mod command `lua_run require("dotnet")`

## Expected  behavior
Load gracefully and create `ManagedGeneratedFile.txt` file in the root folder of the Garry's Mod.

## Actual behavior
Hostfxr sends error message "Failed to create CoreCLR, HRESULT: 0x8007001F", `hostfxr_get_runtime_delegate` returns `nullptr` instead of helper function to get managed delegate pointer.

## Environment data
__OS__: Ubuntu 18.04

__dotnet version__: x64 Linux Runtime 3.0.0 binaries downloaded from https://dotnet.microsoft.com/download/dotnet-core/3.0

**Comment by GlebChili** [comment]
I also wrote a simple app to test same case without Garry's Mod: https://github.com/GlebChili/HostFxrApiTest

Absolutely same behaviour was observed. But it is interesting that app runs as expected on WSL. I also resolved dependencies both by hands and by installing NET Core from the repositories.

**Comment by vitek-karas** [comment]
I was able to repro the failure with your simple app - thanks a lot!

I think I know what's wrong - although I have no idea where the error code `0x8007001F` comes from. The `0x1F` must be some error code of some linux function which fails inside the runtime (and the runtime wraps it as an `HRESULT`).

At the beginning you're calling `readlink` which will not write the nul termination character into the string buffer. So at least in my case the buffer had some garbage characters in it after the path to the executable.

After adding this:
```C++
    int s = readlink("/proc/self/exe", exec_path, 299);
    exec_path[s] = '\0';
```

The sample app works and prints out:
```
Execution was successful! 
```

It also produces the `ManagedGeneratedFile.txt` with content:
```
Managed code says hi!
```

Looking at the source of your real plugin, it seems to have the same problem. Note that the windows version of this function `GetModuleFileNameA` writes the nul terminator character, so it's not 100% equivalent to the Linux function.

**Comment by GlebChili** [comment]
Oh, indeed it helped! Thank you! I was thinking that problem was with one of the `hostfxr_initialize_parameters`'s fields, but the fact that everything worked under WSL made me doubt.
