### ISSUE TITLE
Standardize subset logic

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/core-setup#8498]
In CoreFx we use a build.proj file in the root which defines different targets that run based on properties being set, i.e. /p:BuildNative=true, /p:BuildManaged=true, /p:BuildPackages=true.
https://github.com/dotnet/corefx/blob/95e35e10d7c52a7eea38c2ae6402d29e2a01efc6/build.proj

Core-Setup works a bit differently as it has subsets that define which projects to build by setting the arcade property `ProjectToBuild` before the build step is triggered in arcade.

I would like to discuss pros and cons of these solutions to ideally choose and improve one to make it easier to merge repositories at a later point.

cc @dagood @jkoritzinsky

**Comment by dagood** [comment]
Closing: we decided to use the subsets approach for consolidation.
