### ISSUE TITLE
Include .NET Core Runtime in WindowsDesktop bundle

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#8504]
To run a .NET Core WPF/WinForms app, you need to install both the .NET Core Runtime and WindowsDesktop Runtime. (As well as the correct x86/x64 bitness.) This is unexpected and is a significant pain point when trying to deploy FDE WinForms and WPF apps.

This issue tracks the incremental step of including the .NET Core Runtime dependency in the installer bundle for the WindowsDesktop Runtime.

This will bring our current matrix of 4 installers needed to run WindowsDesktop apps:

|   | x64 | x86 |
| --- | --- | --- |
| .NET Core Runtime | x | x |
| .NET Desktop Runtime | x | x |

down to 2:

|   | x64 | x86 |
| --- | --- | --- |
| .NET Desktop Runtime | x | x |

Then, later, we may be able to combine the x86/x64 ones as well by completing https://github.com/dotnet/core-setup/issues/7763. (This is more difficult from an implementation perspective.)

/cc @KathleenDollard @leecow @dleeapho @MichaelSimons @rowanmiller

**Comment by KathleenDollard** [comment]
👍 Yeah!

**Comment by dagood** [comment]
This is merged for 3.1 preview 2 with PR https://github.com/dotnet/core-setup/pull/8508!

Waiting to gather data/feedback before potentially porting to the 3.0 servicing branch as well. (Not tracking that in this issue.)

Implementing it in 5.0+ has to be done separately in the dotnet/windowsdesktop repo, https://github.com/dotnet/windowsdesktop/issues/20 tracks that.

**Comment by cup** [comment]
https://github.com/dotnet/core-setup/issues/8862
