### ISSUE TITLE
Snap not working on Ubuntu core in Raspberry Pi 3 Model B v1.2

### ISSUE THREAD

**Issue by pictordx** [dotnet/core-setup#8505]
## Steps to reproduce
I created a snap to run .net 3.0 SDK in Ubuntu core installed in Raspberry Pi. When I run the dotnet command after install, it shows the below text

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

But when i run the command dotnet -h it shows the following error
Failed to create CoreCLR, HRESULT: 0x80070008

## Expected  behavior
Displays the help text

## Actual behavior
Failed to create CoreCLR, HRESULT: 0x80070008

## Environment data
Snapcraft.yaml contents

name: my-test-dotnet
version: '0.1'
summary: Test dotnet sdk
description: |
  Test dotnet sdk

grade: devel
confinement: strict

base: core18

architectures:
  - build-on: amd64
    run-on: armhf

apps:
  dotnet:
    command: dotnet

parts:
  dotnet-sdk:
    plugin: dump
    source: source/dotnet/dotnet-sdk-3.0.100-linux-arm.tar.gz

**Comment by dleeapho** [comment]
A quick look indicates [native dependencies](https://github.com/dotnet/core-setup/blob/master/src/pkg/packaging/snaps/dotnet-sdk-3/snap/snapcraft.yaml#L21) are missing and confinement would need to be `classic`. @leecow is also going to try this out.

**Comment by pictordx** [comment]
It would be great  if an armhf architecture of .net core sdk 3.0 available in snap store. Now only amd64 architecture is available

**Comment by am11** [comment]
Assuming curl, bash, libunwind and icu-libs are installed on your Pi, does `curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -Channel 3.0` install .NET runtime and sdk?

**Comment by dagood** [comment]
Closing: we think the main question is answered, that the yaml is missing native dependencies. Adding another architecture is on the roadmap.
