### ISSUE TITLE
Disable producing NETStandard targeting pack in 3.1 branch

### ISSUE THREAD

**Issue by dagood** [dotnet/core-setup#8507]
Right now, Core-Setup `release/3.1` still produces 2.1-versioned .NET Standard targeting packs with prerelease versions, which is *below* the 2.1.0 version we produced for 3.0.0 (`release/3.0`). This is confusing.

We should disable this targeting pack from building. Repos should keep pointing at the released 2.1 targeting pack.

The .NET Standard targeting pack is odd because it doesn't really belong in Core-Setup. That's why the usual approach of bumping up the version isn't an obvious solution.

**Comment by dleeapho** [comment]
When we do need to rev the targeting pack we'll need to manually enable it.

**Comment by dagood** [comment]
This specific work is done. Followup porting to master is already tracked by https://github.com/dotnet/core-setup/issues/8507, other bugs are filed as followup servicing infra bugs.
