### ISSUE TITLE
TargetArchitecture property

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/core-setup#8601]
Is core-setup allowing to specify an architecture (i.e. x64, x86, arm, arm64)? If yes, what msbuild property is expected? In CoreFx we currently use `ArchGroup` but we can easily pass in multiple ones like `TargetArchitecture` or consolidate.

cc @jkoritzinsky @dagood

**Comment by dagood** [comment]
Core-Setup uses `TargetArchitecture`, `/p:TargetArchitecture=x86` etc., and as of recently there's `BuildArchitecture` as well to handle building on a real arm64 machine:

https://github.com/dotnet/core-setup/blob/b6e04f97df5f62282cc7738a31ae697da43ab977/Directory.Build.props#L98-L100

I don't have the lay of the land with these props, but having `Target` in there seems like it's good. E.g. on Windows you target x86 but still use the x64 toolset. But that's just naming--consolidating is good either way if these props represent the same thing.

**Comment by ViktorHofer** [comment]
Thanks, I will for now set both properties and we should clean this up after the consolidation.

**Comment by dagood** [comment]
@ViktorHofer Do you think this discussion issue should go on to track cleanup or can it be closed?

**Comment by ViktorHofer** [comment]
Yes.
