### ISSUE TITLE
SLES 10.1 or 10.2 Support

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/core-setup#8703]
Is there any hope for a binary which will work or an option to build from source? TIA

**Comment by dagood** [comment]
It's hard to say it's impossible, however [.NET Core only supports SLES 12 SP2+](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md#linux) and [SUSE Linux Enterprise Server 10 SP\* itself is not supported as of 3+ years ago](https://www.suse.com/lifecycle/). The [source-build](https://github.com/dotnet/source-build) project exists but it doesn't seem useful to get .NET Core working on such an old, out-of-support distro version.
