### ISSUE TITLE
Single file: Guard against partial cleanup of extracted files

### ISSUE THREAD

**Issue by bezxyw** [dotnet/core-setup#8766]
After some time Windows can clean previously unpacked app folder i.e.
C:\Users\username\AppData\Local\Temp\.net\MyApp\alsn4mer.rpw\
And leaves it empty. 

Single .exe .net core app only check if folder exists and then tries to start app from MyApp.dll file. Which doesn't exist and app crashes with: 
"The application to execute does not exist: ... .dll" error.

**Comment by swaroop-sridhar** [comment]
In this version deletion of the some/all of the files in the extracted directory is a problem. The work-around is to manually clean the `C:\Users\username\AppData\Local\Temp.net\MyApp` directory.

**Comment by bezxyw** [comment]
@swaroop-sridhar yes, but when distributing single.exe on server farm + individual users in a company this becomes a bricked software on someone's machine. 
It will crash even before any logging will be sent to centralized service so you don't even know it 
happened. 

Either something will explode and you'll learn about your solution not working from another department or individual users.

**Comment by swaroop-sridhar** [comment]
@bezxyw I understand the issue you've pointed out.

In the current release, there's one solution to mitigate it:
The location where the bundle contents are extracted is configurable via the `DOTNET_BUNDLE_EXTRACT_BASE_DIR` environment variable. So, it can be set to any user directory that's not cleaned up automatically.

Subsequent implementation of single-file solution will reduce/eliminate the reliance on temporary extraction directories.

**Comment by bezxyw** [comment]
@swaroop-sridhar perfect! I can rollout this via GPO with IT. This will solve the issue for now. Thank you!

**Comment by swaroop-sridhar** [comment]
Dup of https://github.com/dotnet/core-setup/issues/8314
