### ISSUE TITLE
Load `.deps.json` using file and not assembly

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/core-setup#8805]
Is there a way to load and inspect targets and libraries using `Microsoft.Extensions.DependencyModel.DependencyContext` passing a path to dep file?

I need to load dep file to try to locate and load dll during instrumentation(`Mono.Cecil`) inside a msbuild task(coverlet coverage), https://github.com/dotnet/cli/issues/12705#issuecomment-547996287

Some context, coverlet need to instrument dll and we use `Mono.Cecil` to do that...instrumentation is started by "drivers"(msbuild task, console app or vstest collectors), cecil search for dll in "current" test assembly directory but sometime that dll isn't present(assets are not moved to bin folder but are resolved at runtime o in publish phase from nuget package folder) so we get a fail for lib not found.

My idea is to "load" target deps file and manually(cecil has got a customizable resolver) load and return dll to cecil.
At the moment the only other solution is to "manually" copy dll to output folder, but it's not so easy/friendly and it's weak.

**Comment by elinor-fung** [comment]
It sounds like you are looking for [`DependencyContextJsonReader`](https://github.com/dotnet/core-setup/blob/master/src/managed/Microsoft.Extensions.DependencyModel/DependencyContextJsonReader.cs).

**Comment by MarcoRossignoli** [comment]
Uh missing that I'll give it a try and come back thanks!

**Comment by MarcoRossignoli** [comment]
Thank's works as expected!
