### ISSUE TITLE
PLEASE keep the repo tag be semver2 compliant

### ISSUE THREAD

**Issue by liesauer** [dotnet/core-setup#8832]
since runtime versioning is semver2 compatible, u should keep this repo be semver2 compatible all the time too. but what u guys are doing???
![image](https://user-images.githubusercontent.com/8676741/68633437-dc3e6d00-052c-11ea-867f-3b1660cc1d3c.png)

**Comment by dagood** [comment]
Thanks for pointing it out, this is strange. @Anipik, I see you pushed the tag, why is a pseudo-semver-v1 version used for the preview3 tag?

(It's not a conventional semver v1 tag either, because `2` would be `02`.)

**Comment by Anipik** [comment]
I used pseudo-semver-v1 for preview3 because we have been using this convention all along(except for preview2). i can reverse it for preview if we want to change the convention to semver2 going forward

**Comment by dagood** [comment]
Looks like @leecow pushed the p1 tag, @vivmishra pushed the p2 one. Just not coordinated, then, I guess! IMO it should match the product's version, which would be 3.1.0-preview3.19553.2 in this case.

**Comment by Anipik** [comment]
i will change it to that in the morning

**Comment by dagood** [comment]
Thanks!

![image](https://user-images.githubusercontent.com/12819531/68695607-fda95400-0540-11ea-885e-abdd6ee6989c.png)
