### ISSUE TITLE
 [loc][Query][core-setup] Localizability of 0; "OptionBulletRemove, OptionRemoveLanguage

### ISSUE THREAD

**Issue by PDostalek** [dotnet/core-setup#8850]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
<b>/remove component{,component}</b>: A comma separated list of component identifiers to remove. The should be no spaces in the list. The set of components to remove are processed after the <b>/add</b> option. Child dependencies are automatically removed.

<b>/removeLanguage language{,language}</b>: Remove languages from the installation.

File Name:
DotNetCoreBootstrapperApplication.resources.dll

==========================================
Query:
Translator needs to know if "{,component}" or {,language} can be translated as the rest of the string. We have instruction within comment that is a numbered placeholder. Please advise.

**Comment by dagood** [comment]
@PDostalek, can you provide some more context on this question?

* Why is this being translated?
* Where was this file found?
* Why is this issue filed in this repo?

/cc @joeloff

**Comment by joeloff** [comment]
This should not be translated. This was part of the MBA related work. That project was put on hold and not being actively worked on right now.

**Comment by dagood** [comment]
Thanks, closing as answered.
