### ISSUE TITLE
Update maestro to cc @dotnet/core-setup-contrib on PRs

### ISSUE THREAD

**Issue by joshfree** [dotnet/core-setup#89]

**Comment by eerhardt** [comment]
This should be fixed now:  https://github.com/dotnet/versions/commit/4979fb642f036589bb249c24f7d06b7a8655a208.

I will close the issue when I see a successful PR created with the 'cc'.

**Comment by eerhardt** [comment]
I needed to make the same change in 2 places: https://github.com/dotnet/versions/commit/9e022bde83f64bcc37dc09badcd87e0ae2051962

Maestro now does this correctly.

Closing
