### ISSUE TITLE
Enable dotnet cache experience

### ISSUE THREAD

**Issue by schellap** [dotnet/core-setup#934]
### [`dotnet cache` core experience](https://github.com/dotnet/sdk/issues/554)
- [x] Enable [`dotnet cache` shim](https://github.com/dotnet/cli/issues/5161)   for the `cache` target and the command line switch in the CLI(@ramarag)
- [x] Implement the `cache` build target. i.e., allow `packages.targets` MSBuild target to be `restore`-ed into output directory (@ramarag)
- [x] Parse and filter the appropriate assets (*a la* `publish`) for the input packages and the target RID (@ramarag)
- [x] Integrate the feature with crossgen with appropriate error codes (@ramarag)
- [x] Layout the files into the appropriate output folder (@ramarag)
- [x] Enable an end to end test using `publish --profile` and `cache` (@ramarag)

### [`dotnet publish --profile` core experience](https://github.com/dotnet/sdk/issues/555)

- [x] Allow `dotnet publish` to take the `--profile` argument (@schellap / @ramarag)
- [x] Enable publish to filter the specified assemblies (@schellap / @ramarag)
- [x] Host should give a better message when assemblies are not found in cache & Add hints in deps.json to indicate an assembly has been filtered at publish time. (@ramarag)

### `dotnet build`
- [x] Persist the project TFM into the runtimeconfig.json (@schellap)
- [x] Corresponding host changes to perform lookup of the `DOTNET_SHARED_PACKAGES` (@schellap)

### Installers and layout changes
- [ ] ~Rename of the `Microsoft.NETCore.App` to `netcoreapp2.0` and corresponding host changes (@schellap)~
  + ~Note: this has to be backwards compatible (i.e., first expect TFM, if not present, use `framework.name`, else fail)~
EERHARDT: I don't think this renaming is worth the cost.
- [x] Consume `dotnet publish --profile` changes to form layout in: `DOTNET_ROOT/packages` and remove Roslyn packages from `Microsoft.NETCore.App` dependencies (@schellap)
- [ ] ~Author setups/zips for the above `DOTNET_ROOT/packages` to ship as part of the runtime installation. (@schellap)~
    + Note: For OSX, Debian and Windows
EERHARDT: This will be done separately by the ASP.NET team. This won't be done in the runtime installation.

Cc @gkhanna79 @livarcocc @piotrpMSFT

**Comment by ramarag** [comment]
Implements https://github.com/dotnet/core-proposals/pull/33

**Comment by gkhanna79** [comment]
@ramarag Please use this issue to tracking the various workitems for the feature.

CC @eerhardt

**Comment by ramarag** [comment]
cc @eerhardt do update the list above

**Comment by ramarag** [comment]
The only remaining item here is adding tests, which is dependent on the latest cli, which i believe is blocked on the change to update the repo's build system.

So moving it to 2.1

**Comment by gkhanna79** [comment]
@eerhardt @ramarag Do we still need tests for this in Core-Setup or do we have sufficient coverage in SDK/CLI repo for it?

**Comment by gkhanna79** [comment]
@eerhardt Should this be closed?

**Comment by eerhardt** [comment]
I just checked off the last box.  This feature is now done.
