### ISSUE TITLE
Author msi, deb, osx packages and zips for hostfxr.dll

### ISSUE THREAD

**Issue by schellap** [dotnet/core-setup#94]
1. We need zips, installers and Unix packaging for `hostfxr.dll` as it is a SxS component.
2. `hostfxr.dll` is clubbed with the `dotnet.exe` installer at this point. As we update `hostfxr.dll` we want to deliver it SxS instead of delivering it with the muxer.

Each build should produce this layout and the installers should produce the following layout:

`$DOTNET_ROOT/host/fxr/{version}/{hostfxr lib}`

Layout below:

`dotnet.exe`
> `shared/`
> `host/`
> > `fxr/`
> > > `1.0.0-rc3-00380/`
> > > > `hostfxr.dll`

Cc @brthor @eerhardt @gkhanna79 @piotrpMSFT @mellinoe

**Comment by gkhanna79** [comment]
@piotrpMSFT @ellismg @brthor Is this something that you can help drive since you already are familiar with package authoring across the platforms, as opposed to @schellap ramping up on it?

**Comment by gkhanna79** [comment]
@piotrpMSFT I have assigned this to you to route to someone who can help with this.

**Comment by gkhanna79** [comment]
@piotrpMSFT @eerhardt What are the next steps on this?

**Comment by gkhanna79** [comment]
@schellap Please sync with @ellismg on how to get this done.

**Comment by brthor** [comment]
I can help with debs/pkgs here.

**Comment by brthor** [comment]
@schellap  I pushed a commit to your branch but messed up, squashed my changes and couldn't force push to your branch.

You can pick up my commit here: https://github.com/brthor/core-setup/commit/7ce358a95ee44327b40035a18b0f82ea99560300

I've added the debs, pkgs, publishing of both to azure, publishing of the new deb to the deb repo. 

I manually verified installations of both the new debs and pkgs, and they seem to be kosher as far as packaging goes, I did not test whether the host was picking up the hostfxr from the subdirectory. 

Now we should just need MSIs.

**Comment by gkhanna79** [comment]
@brthor you are awesome! Thank you :)

**Comment by brthor** [comment]
Thanks @gkhanna79 !

@schellap also see here for cli changes
https://github.com/brthor/cli/commit/a8da9011c7e8edb31e0c54bf299cac11eb2cce2b

**Comment by gkhanna79** [comment]
Reopening to track merge of release branch fix (at https://github.com/dotnet/core-setup/pull/141)

**Comment by Petermarcu** [comment]
Merged
