### ISSUE TITLE
.dll files in the .NET Core tarball for Linux have incorrect permissions

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/core-setup#949]
(copied from dotnet/cli#5166)

## Steps to reproduce
Download the latest .NET Core tarball for Linux.
Unpackage the tarball.
The various `.dll` files in the tarball have permission `600`, making the files accessible for the owner, but not any other user.

## Expected  behavior
The files to be readable by any user in the system (I'm guessing that would be `644`)

## Actual behavior
The files have permission level `600`

**Comment by wjk** [comment]
@qmfrederik Actually, the standard permission level for files that should be readable by any user is `644`. Permission settings of `666` would grant any user on the system _write_ access to the file as well, which is probably not what you intended.

**Comment by qmfrederik** [comment]
@wjk That's correct, thanks! I updated the bug description.

**Comment by gkhanna79** [comment]
@schellap PTAL

**Comment by gkhanna79** [comment]
@qmfrederik I examined https://dotnetcli.blob.core.windows.net/dotnet/master/Binaries/Latest/dotnet-ubuntu.16.04-x64.latest.tar.gz (available from the Daily Builds section at https://github.com/dotnet/core-setup/blob/master/README.md) and I see the *.dlls with 644 (rw-r--r--) permission.

Can you point me to where you see the discrepancy?

**Comment by qmfrederik** [comment]
@gkhanna79 This appears to have been fixed in meanwhile, thanks!
